/* Super-admin data comes only from protected server RPCs and RLS tables. */
(function(root){root.createAdminPanel174=function(C,options={}){const toast=options.toast||((message)=>root.AnnotationApp.toast(message)),db=C.client,E=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n},check=r=>{if(r.error)throw r.error;return r.data};
const panel=E('dialog');panel.id=options.id||'adminPanel95';const head=E('div');head.className='adminHead95';head.append(E('strong','管理后台 · 用户与通知'));const close=E('button','×');close.setAttribute('aria-label','关闭');close.onclick=()=>panel.close();head.append(close);const body=E('div');body.className='adminBody95';panel.append(head,body);document.body.append(panel);
const bell=options.bell||E('button');if(!options.bell)bell.id='adminBell95';bell.title='新用户注册通知';bell.setAttribute('aria-label','管理员通知');bell.innerHTML='<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M5 17h14l-2-3V9a5 5 0 0 0-10 0v5zM10 20h4"/></svg><b hidden>0</b>';if(!options.bell)(options.account||document.getElementById('account47')).after(bell);bell.onclick=()=>open();bell.hidden=true;
let channel=null,timer=null,generation=0,owner='',lastId=0,loaded=false,events=[],offset=0,query='',notified=new Set(),notificationAllowed=typeof Notification!=='undefined'&&Notification.permission==='granted',loadFlight=null;
function admin(){return !!C.user&&C.isFounder132===true}
function button(parent,text,fn){const b=E('button',text);b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn()}catch(e){toast(e.message||e)}finally{b.disabled=false}};parent.append(b);return b}
function setup(error){const n=E('div');n.className='adminSetup95';n.append(E('strong','用户后台尚未连通'),E('p','数据库需要启用第95版升级。现有账号和书写仍可使用。'+(error?.message?'原因：'+error.message:'')));const link=E('a','查看数据库开通步骤');link.href='https://github.com/jearns/iinnkk/blob/main/ADMIN-95.md';link.target='_blank';link.rel='noopener';n.append(link);return n}
function toastEvent(row){if(row.kind!=='signup'||notified.has(row.id))return;notified.add(row.id);toast('新用户注册 · '+row.label);if(notificationAllowed&&'Notification'in window&&Notification.permission==='granted'){try{const n=new Notification('手笔 · 新用户注册',{body:row.label,tag:'signup95-'+row.id,icon:'favicon151.png'});n.onclick=()=>{window.focus();open()}}catch{}}}
async function loadNotices(){if(!admin())return;if(loadFlight)return loadFlight;const gen=generation;
 const flight=(async()=>{const read=check(await db.from('ink_admin_reads95').select('last_id').eq('owner',C.user.id).maybeSingle());const mark=Number(read?.last_id||0);const result=await db.from('ink_admin_events95').select('id,kind,owner,label,created_at',{count:'exact'}).gt('id',mark).order('id',{ascending:false}).limit(100);const rows=check(result)||[];if(gen!==generation||!admin())return;lastId=mark;events=rows;const count=result.count??rows.length,badge=bell.querySelector('b');badge.textContent=count>99?'99+':String(count);badge.hidden=!count;bell.title='管理员通知 · '+count+' 条未读';if(loaded)for(const row of rows)toastEvent(row);else for(const row of rows)notified.add(row.id);loaded=true;if(panel.open)renderNotices()})();loadFlight=flight;try{await flight}finally{if(loadFlight===flight)loadFlight=null}}
function renderNotices(){const section=body.querySelector('#adminNotices95');if(!section)return;section.replaceChildren(E('h3','通知栏 · 新用户注册'));if(!events.length)section.append(E('p','没有未读通知'));for(const row of events){const n=E('div');n.className='adminNotice95';n.append(E('strong',row.label),E('small','　'+new Date(row.created_at).toLocaleString('zh-CN')));section.append(n)}if(events.length)button(section,'以上通知标为已读',async()=>{check(await db.rpc('ink_admin_ack95',{p_last_id:Math.max(...events.map(e=>Number(e.id)))}));await loadNotices()})}
async function listUsers(){const gen=generation;if(!admin())throw Error('请用超级管理员登录');const list=body.querySelector('.adminUsers95'),status=body.querySelector('#adminStatus95');status.textContent='正在读取用户…';const rows=check(await db.rpc('ink_admin_users95',{p_query:query,p_offset:offset}));if(gen!==generation||!admin())return;list.replaceChildren();if(!Array.isArray(rows))throw Error('数据库升级尚未启用');const table=E('table'),thead=E('thead'),tr=E('tr');for(const label of ['用户','注册 / 验证','作品','角色与状态'])tr.append(E('th',label));thead.append(tr);table.append(thead);const tbody=E('tbody');table.append(tbody);list.append(table);
 for(const u of rows){const row=E('tr'),identity=E('td'),dates=E('td'),works=E('td',String(u.work_count||0)),actions=E('td');identity.append(E('strong',u.display_name||'待完善'),E('div',u.email||'第三方账号'),E('small',({female:'女',male:'男'})[u.gender]||'未透露'));dates.append(E('div',new Date(u.created_at).toLocaleDateString('zh-CN')),E('small',u.confirmed_at?'邮箱已验证':'待验证'));const role=E('select');role.setAttribute('aria-label','用户角色 '+u.display_name);for(const v of ['书家','书圣','书仙'])role.append(new Option(v+(v==='书仙'?' · 超级管理员':''),v));role.value=u.role;const disabled=E('input');disabled.type='checkbox';disabled.checked=!!u.disabled;const label=E('label','暂停发布与评论');label.prepend(disabled);actions.append(role,label);const save=button(actions,'保存用户设置',async()=>{if(role.value==='书仙'&&u.role!=='书仙'&&!confirm('授予 '+(u.email||u.display_name)+' 超级管理员权限？其将可查看用户资料并管理角色。'))return;check(await db.rpc('ink_admin_member95',{p_owner:u.owner,p_role:role.value,p_disabled:disabled.checked}));await listUsers();await loadNotices()});if(u.owner===C.user.id){role.disabled=true;disabled.disabled=true;save.disabled=true}row.append(identity,dates,works,actions);tbody.append(row)}status.textContent='第 '+(offset/50+1)+' 页 · '+rows.length+' 位用户';const pager=E('div');button(pager,'上一页',async()=>{offset=Math.max(0,offset-50);await listUsers()}).disabled=!offset;button(pager,'下一页',async()=>{offset+=50;await listUsers()}).disabled=rows.length<50;list.append(pager)}
async function open(){if(!admin())return;body.replaceChildren(E('p','查看新注册用户，整理角色与作品互动权限。'));const search=E('form');search.className='adminSearch95';const input=E('input');input.placeholder='搜索昵称或邮箱';input.setAttribute('aria-label','搜索用户');input.value=query;search.append(input);button(search,'搜索',async()=>{query=input.value.trim();offset=0;await listUsers()});search.onsubmit=e=>{e.preventDefault();query=input.value.trim();offset=0;listUsers().catch(e=>toast(e.message))};button(search,'刷新',async()=>{await listUsers();await loadNotices()});body.append(search);const status=E('p');status.id='adminStatus95';status.setAttribute('role','status');const list=E('div');list.className='adminUsers95';const notices=E('section');notices.id='adminNotices95';body.append(status,list,notices);button(body,'启用浏览器通知',async()=>{if(!('Notification'in window)){toast('此浏览器支持站内通知；系统通知需要浏览器支持');return}const permission=await Notification.requestPermission();notificationAllowed=permission==='granted';toast(notificationAllowed?'已开启：网站运行时新注册用户会弹出系统通知':'仍使用站内通知栏')});if(!panel.open)panel.showModal();try{await Promise.all([listUsers(),loadNotices()]);renderNotices()}catch(e){body.append(setup(e));status.textContent='尚未开通数据库管理'}}
function attachAccount(nav){if(!admin())return;button(nav,'管理后台',open).id='adminEntry95'}
function connect(){generation++;const previousOwner=owner;owner=admin()?C.user.id:'';bell.hidden=!owner;if(channel){db.removeChannel?.(channel);channel=null}clearInterval(timer);timer=null;loadFlight=null;events=[];loaded=false;notified=new Set();bell.querySelector('b').hidden=true;if(panel.open&&previousOwner!==owner){panel.close();body.replaceChildren()}if(!owner)return;
 loadNotices().catch(()=>{});if(db.channel)channel=db.channel('admin95:'+owner).on('postgres_changes',{event:'INSERT',schema:'public',table:'ink_admin_events95'},payload=>{if(!admin())return;toastEvent(payload.new);loadNotices().catch(()=>{})}).subscribe();timer=setInterval(()=>{if(admin())loadNotices().catch(()=>{})},15000)}
document.addEventListener(options.authEvent||'cloud-user84',connect);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&admin())loadNotices().catch(()=>{})});const controller={open,attachAccount,loadNotices,connect,get ready(){return admin()}};connect();return controller};if(document.getElementById('home154'))return;(function init(){if(!root.Revision95?.ready||!root.InkCloud75){setTimeout(init,80);return}root.Admin95=root.createAdminPanel174(root.InkCloud75)})()})(window);
