/* Portable device backup: merge imported works, never clear the local database. */
(function(){
async function encode(value){if(value instanceof Blob)return{$binary:'blob',type:value.type,data:await base64(await value.arrayBuffer())};if(value instanceof ArrayBuffer)return{$binary:'buffer',data:await base64(value)};if(Array.isArray(value))return Promise.all(value.map(encode));if(value&&typeof value==='object'){const result={};for(const [k,v]of Object.entries(value))if(!['__proto__','constructor','prototype'].includes(k))result[k]=await encode(v);return result}return value}
function base64(data){return new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.readAsDataURL(new Blob([data]))})}
function decode(value){if(value?.$binary){const bytes=Uint8Array.from(atob(value.data),c=>c.charCodeAt(0));return value.$binary==='blob'?new Blob([bytes],{type:value.type}):bytes.buffer}if(Array.isArray(value))return value.map(decode);if(value&&typeof value==='object'){const result={};for(const [k,v]of Object.entries(value))if(!['__proto__','constructor','prototype'].includes(k))result[k]=decode(v);return result}return value}
async function exportData(){await window.ZhenjiBackup.flush();const records=await DraftStore.dump(),local={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(/^(yuanji|zhenji)\./.test(k))local[k]=localStorage.getItem(k)}return new Blob([JSON.stringify({format:'zhenji-backup',version:1,created:new Date().toISOString(),records:await encode(records),local})],{type:'application/json'})}
async function importData(file){const data=JSON.parse(await file.text());if(data.format!=='zhenji-backup'||data.version!==1||!Array.isArray(data.records))throw Error('不是有效的真迹备份');const records=decode(data.records);if(records.some(r=>!Array.isArray(r)||r.length!==2||typeof r[0]!=='string'))throw Error('备份内容不完整');await DraftStore.merge(records);for(const [k,v]of Object.entries(data.local||{}))if(/^(yuanji|zhenji)\./.test(k)&&typeof v==='string')localStorage.setItem(k,v)}
window.PortableBackup={exportData,importData};
function install(){if(!window.ZhenjiBackup){setTimeout(install,100);return}const row=document.getElementById('paperQuickRow'),save=document.createElement('button'),restore=document.createElement('button'),input=document.createElement('input');save.id='backupExport';restore.id='backupImport';save.textContent='导出全部备份';restore.textContent='导入备份';input.type='file';input.accept='.json';input.hidden=true;row.append(save,restore,input);save.onclick=async()=>{save.disabled=true;try{const blob=await exportData(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='亲笔真迹-完整备份-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}catch{alert('备份失败，请重试；本机内容仍然保留。')}finally{save.disabled=false}};restore.onclick=()=>input.click();input.onchange=async()=>{const f=input.files[0];if(!f)return;if(!confirm('导入后会恢复备份中的草稿和设置，并合并作品库。同名作品编号以备份为准，其他作品保留。继续？'))return;try{await importData(f);window.ZhenjiBackup.pause();location.reload()}catch(e){alert(e.message||'导入未完成，请重试')}finally{input.value=''}}}install();
})();
