/* Small, independent startup guard: ES5 syntax, no application dependencies. */
(function(){
 var failures=[];window.StartupErrors106=window.StartupErrors106||failures;
 if(!Element.prototype.replaceChildren)Element.prototype.replaceChildren=function(){while(this.firstChild)this.removeChild(this.firstChild);for(var i=0;i<arguments.length;i++)this.appendChild(typeof arguments[i]==='string'?document.createTextNode(arguments[i]):arguments[i])};
 if(!HTMLImageElement.prototype.decode)HTMLImageElement.prototype.decode=function(){var im=this;return new Promise(function(resolve,reject){if(im.complete){im.naturalWidth?resolve():reject(Error('图片读取失败'));return}im.addEventListener('load',resolve,{once:true});im.addEventListener('error',reject,{once:true})})};
 if(!window.ResizeObserver){window.ResizeObserver=function(callback){this.callback=callback;this.targets=[];var self=this;this.listener=function(){self.targets.forEach(function(target){self.callback([{target:target,contentRect:target.getBoundingClientRect()}])})};window.addEventListener('resize',this.listener)};ResizeObserver.prototype.observe=function(target){this.targets.push(target);this.listener()};ResizeObserver.prototype.unobserve=function(target){this.targets=this.targets.filter(function(x){return x!==target})};ResizeObserver.prototype.disconnect=function(){this.targets=[];window.removeEventListener('resize',this.listener)}}
 if(!String.prototype.replaceAll)String.prototype.replaceAll=function(search,replacement){if(search instanceof RegExp){if(!search.global)throw TypeError('replaceAll requires global regex');return this.replace(search,replacement)}var escaped=String(search).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return this.replace(new RegExp(escaped,'g'),replacement)};
 var timer=setInterval(function(){var cover=document.getElementById('loading106'),home=document.getElementById('annotationHome');if(home&&window.Revision90&&window.Revision90.ready){if(cover)cover.remove();clearInterval(timer);return}if(!cover)return;var button=cover.querySelector('button');if(button)button.hidden=false;if(performance.now()>15000){cover.querySelector('span').textContent='加载较慢或资源未完成，请重试。本机作品仍保留。';clearInterval(timer)}},1000);
 window.addEventListener('pageshow',function(){var cover=document.getElementById('loading106');if(window.Revision90&&window.Revision90.ready&&cover)cover.remove()});
})();
