/* Durable, authorized operation log; concurrent strokes are merged by identity. */
(function(root){
 function applyOps(base,operations){const map=new Map(base.map(s=>[s.id128,s]));for(const row of operations)for(const op of row.payload||[]){if(op.kind==='delete')map.delete(op.id);else if(op.kind==='put'&&op.stroke?.id128)map.set(op.stroke.id128,op.stroke)}return [...map.values()]}
 root.SharedInk128={applyOps};
 if(!root.document)return;
 (function init(){if(!window.Revision128?.ready||!window.InkCloud75?.client){setTimeout(init,100);return}
 const A=AnnotationApp,cloud=InkCloud75,db=cloud.client,$=id=>document.getElementById(id);let room=null,page=null,baseline=new Map(),log=[],base=[],seq=0,polling=false,timer=0,backup=null,dirty=false,pendingBatch=null,lastUser='',generation=0,needsMerge=false;
 const uid=()=>cloud.user?.id,check=r=>{if(r.error)throw Error(r.error.message);return r.data},fingerprint=s=>JSON.stringify(s),identify=(s,i,seed='seed')=>({...s,id128:s.id128||seed+'-'+i});
 const dialog=document.createElement('dialog');dialog.className='collab128';dialog.innerHTML='<header class="dialogHead"><h2>共书 · 一起亲笔</h2><button data-close>×</button></header><p>家人一起练字、同学毕业留言、同事纪念。互相关注后，由发起人邀请，在同一页或一套纸上书写与批注。</p><section data-body></section><p data-status role="status"></p>';document.body.append(dialog);dialog.querySelector('[data-close]').onclick=()=>dialog.close();const body=dialog.querySelector('[data-body]'),status=dialog.querySelector('[data-status]');
 const bar=document.createElement('aside');bar.className='collabBar128';bar.hidden=true;bar.innerHTML='<span></span><button data-pages>页册</button><button data-leave>离开共书</button>';document.body.append(bar);const mark=text=>{status.textContent=text;bar.querySelector('span').textContent=text};
 const button=(host,label,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=async()=>{b.disabled=true;try{await fn()}catch(e){mark(e.message)}finally{b.disabled=false}};host.append(b);return b};
 const cacheKey=()=> 'shared-offline133:'+(uid()||'guest');let cached={rooms:[],pages:{},queues:{},drafts:{}},localFlight133=null,draining133=false;
 async function restoreCache133(){cached=await DraftStore.get(cacheKey())||{rooms:[],pages:{},queues:{},drafts:{}};cached.queues||={};cached.drafts||={}}
 async function persistCache133(){if(page)cached.drafts[page.id]=A.getState();if(room){cached.rooms=cached.rooms.filter(r=>r.id!==room.id);cached.rooms.unshift(room)}await DraftStore.set(cacheKey(),cached)}
 async function renameRoom141(r,title){const me=uid();if(!me||r.owner!==me)throw Error('只有发起人可以修改小组名称');title=String(title).trim().slice(0,120);if(!title)throw Error('请填写小组名称');if(r.offline133){r.title=title}else{if(!navigator.onLine)throw Error('请联网后修改小组名称');const saved=check(await db.from('ink_shared_rooms128').update({title}).eq('id',r.id).eq('owner',me).select('id,title,participants').single());if(uid()!==me)throw Error('账号已切换，请重新打开共书');Object.assign(r,saved)}if(room?.id===r.id)room=r;await persistCache133();return r}
 async function roomHeading141(host,r=room,editable=true){if(!r)return;if(editable&&navigator.onLine&&!r.offline133){try{const me=uid(),fresh=check(await db.from('ink_shared_rooms128').select('id,title,participants').eq('id',r.id).single());if(me!==uid())return;Object.assign(r,fresh)}catch{}}const box=document.createElement('section');box.className='roomHeading141';const name=document.createElement('strong');name.textContent=r.title;box.append(name);const members=document.createElement('p');members.className='roomMembers141';const ids=[...new Set(r.participants||[])];let profiles=[];if(navigator.onLine&&ids.length){try{profiles=check(await db.from('ink_profiles83').select('owner,display_name').in('owner',ids))||[];r.memberNames141=Object.fromEntries(profiles.map(p=>[p.owner,p.display_name]))}catch{}}members.textContent='共同书写：'+ids.map(id=>r.memberNames141?.[id]||(id===uid()?cloud.user?.user_metadata?.full_name||'我':'书友 '+id.slice(0,6))).join('、');box.append(members);if(editable&&r.owner===uid()){const input=document.createElement('input');input.value=r.title;input.maxLength=120;input.setAttribute('aria-label','小组名称');box.append(input);button(box,'保存组名',async()=>{await renameRoom141(r,input.value);name.textContent=r.title;input.value=r.title;mark('小组名称已更新')})}host.append(box)}
 async function drain133(){if(draining133||!navigator.onLine||!uid())return;draining133=true;const owner=uid(),cache=cached,key=cacheKey(),valid=()=>navigator.onLine&&uid()===owner;try{for(const r of cache.rooms.filter(r=>r.offline133)){if(!valid())return;const created=await db.from('ink_shared_rooms128').insert({id:r.id,owner,title:r.title,participants:[owner]});if(created.error&&created.error.code!=='23505')check(created);for(const p of cache.pages[r.id]||[]){if(!valid())return;const added=await db.from('ink_shared_pages128').insert({id:p.id,room:r.id,author:owner,title:p.title,draft:p.draft});if(added.error&&added.error.code!=='23505')check(added)}delete r.offline133;await DraftStore.set(key,cache)}for(const jobs of Object.values(cache.queues)){while(jobs.length){if(!valid())return;const op=jobs[0],r=await db.from('ink_shared_ops128').insert(op);if(r.error&&r.error.code!=='23505')check(r);jobs.shift();await DraftStore.set(key,cache)}}}finally{draining133=false}}
 async function flushLocal(){if(localFlight133)return localFlight133;localFlight133=flushLocalInner133();try{return await localFlight133}finally{localFlight133=null}}

 async function flushLocalInner133(){if(!page||!uid()||A.isDrawing128())return false;const savingOwner133=uid(),savingPage133=page.id,savingGeneration133=generation;const local=A.getState().flow.strokes.map((s,i)=>identify(s,i,'local-'+uid()));const payload=[];const now=new Map(local.map(s=>[s.id128,s]));for(const [id,s]of now)if(baseline.get(id)!==fingerprint(s))payload.push({kind:'put',stroke:s});for(const id of baseline.keys())if(!now.has(id))payload.push({kind:'delete',id});if(payload.length){pendingBatch=pendingBatch||{id:crypto.randomUUID(),page:page.id,writer:uid(),payload};const jobs=cached.queues[page.id]||=([]);if(!jobs.some(j=>j.id===pendingBatch.id))jobs.push(pendingBatch);await persistCache133();if(uid()!==savingOwner133||page?.id!==savingPage133||generation!==savingGeneration133)return false;for(const op of pendingBatch.payload){if(op.kind==='delete')baseline.delete(op.id);else if(op.kind==='put')baseline.set(op.stroke.id128,fingerprint(op.stroke))}pendingBatch=null;const latest=A.getState().flow.strokes;if(latest.length!==baseline.size||latest.some(s=>baseline.get(s.id128)!==fingerprint(s))){dirty=true;return false}}dirty=false;return true}
 async function sync(){if(polling||!page||!uid()||document.hidden)return;const run=generation,currentPage=page.id;polling=true;try{if(!await flushLocal())return;if(!navigator.onLine){mark(room.title+' · 离线草稿已保存在本机');return}await drain133();let rows=check(await db.from('ink_shared_ops128').select('seq,id,payload,writer').eq('page',currentPage).gt('seq',seq).order('seq').limit(500))||[];if(run!==generation||currentPage!==page?.id)return;if(rows.length){log.push(...rows);seq=rows.at(-1).seq;needsMerge=true}if(needsMerge){const current=A.getState().flow.strokes;if(A.isDrawing128()||current.length!==baseline.size||current.some(s=>baseline.get(s.id128)!==fingerprint(s))){dirty=true;return}const strokes=applyOps(base,log);if(A.collabMerge128(strokes)){baseline=new Map(strokes.map(s=>[s.id128,fingerprint(s)]));needsMerge=false;mark(room.title+' · 已同步')}else{dirty=true}}else mark(room.title+' · 共书中')}catch(e){mark('暂未同步，笔迹保留在本机：'+e.message)}finally{polling=false}}
 async function openPage(next){if(page)await flushLocal();generation++;page=next;base=(next.draft.flow?.strokes||[]).map((s,i)=>identify(s,i,next.id));log=[];seq=0;pendingBatch=null;const saved=cached.drafts[next.id],draft={...(saved||next.draft),flow:{strokes:saved?.flow?.strokes||base},editingWork110:null};await A.newBlank54();await A.restoreDraft(draft);A.setWorkIdentity128(null);A.collabMerge128(draft.flow.strokes);baseline=new Map(base.map(s=>[s.id128,fingerprint(s)]));bar.hidden=true;dialog.close();A.showWriter();clearInterval(timer);timer=setInterval(sync,1800);await sync()}
 async function pages(){if(!room)return;body.replaceChildren();await roomHeading141(body);const rows=navigator.onLine&&!room.offline133?check(await db.from('ink_shared_pages128').select('*').eq('room',room.id).order('created_at'))||[]:cached.pages[room.id]||[];cached.pages[room.id]=rows;await persistCache133();rows.forEach((p,i)=>button(body,(i+1)+' · '+p.title,()=>openPage(p)));button(body,'增加一张共书纸',async()=>{await flushLocal();const d=A.getState();d.flow={strokes:[]};d.signatureStrokes=[];d.editingWork110=null;let p={id:crypto.randomUUID(),room:room.id,author:uid(),title:'第 '+(rows.length+1)+' 页',draft:d};if(navigator.onLine&&!room.offline133)p=check(await db.from('ink_shared_pages128').insert(p).select().single());else if(!room.offline133){mark('新增共书页需要联网；当前页可以继续离线书写');return}rows.push(p);cached.pages[room.id]=rows;await persistCache133();await openPage(p)});if(navigator.onLine&&room.owner===uid())button(body,'邀请互关好友',()=>invite());if(page)leaveAction139(body);if(!dialog.open)dialog.showModal()}
 async function invite(){body.replaceChildren();await roomHeading141(body);const me=uid(),rows=check(await db.from('ink_follows116').select('follower,followed').or('follower.eq.'+me+',followed.eq.'+me))||[],mine=new Set(rows.filter(x=>x.follower===me).map(x=>x.followed)),mutual=[...new Set(rows.filter(x=>x.followed===me&&mine.has(x.follower)).map(x=>x.follower))];const profiles=mutual.length?check(await db.from('ink_profiles83').select('owner,display_name').in('owner',mutual)):[];if(!mutual.length){body.append(document.createTextNode('暂无互关好友。可邀请家人加入，或去书法殿堂关注喜欢的书友。'));button(body,'邀请好友加入',async()=>{const url=location.origin+location.pathname+'?join=shared';const text='一起在今日亲笔练字、批注或留言。注册后互相关注，就可以共书一页纸。';if(navigator.share)await navigator.share({title:'邀请一起共书',text,url});else{await navigator.clipboard.writeText(text+' '+url);mark('邀请链接已复制')}});button(body,'去书法殿堂互关',async()=>{dialog.close();await cloud.showGallery()})}for(const id of mutual){const name=profiles?.find(p=>p.owner===id)?.display_name||'书友 '+id.slice(0,6);button(body,(room.participants.includes(id)?'已加入 · ':'邀请 · ')+name,async()=>{if(room.participants.includes(id))return;const next=[...room.participants,id];check(await db.from('ink_shared_rooms128').update({participants:next}).eq('id',room.id));room.participants=next;await invite()})}button(body,'返回共书页册',pages)}
 async function open(){if(page)await flushLocal();await restoreCache133();await window.Revision128?.saveOnSwitch129?.();if(!uid()){A.toast('请先登录，再发起或加入共书');$('account47').click();return}body.replaceChildren();status.textContent='';if(room&&page){await roomHeading141(body);activeActions139(body);if(!dialog.open)dialog.showModal();return}const title=document.createElement('input');title.placeholder='家人练字 / 毕业留言 / 同事纪念';title.value='一起亲笔';body.append(title);button(body,'把当前作品发起共书',async()=>{A.finish();const draft=A.getState();const id=crypto.randomUUID();draft.flow.strokes=draft.flow.strokes.map((s,i)=>identify(s,i,id));draft.editingWork110=null;room={id,owner:uid(),title:title.value.trim().slice(0,120)||'一起亲笔',participants:[uid()],offline133:!navigator.onLine};if(navigator.onLine){const onlineRoom={...room};delete onlineRoom.offline133;room=check(await db.from('ink_shared_rooms128').insert(onlineRoom).select().single())}backup=A.getState();let first={id:crypto.randomUUID(),room:id,author:uid(),title:'第 1 页',draft};if(navigator.onLine)first=check(await db.from('ink_shared_pages128').insert(first).select().single());cached.pages[id]=[first];await persistCache133();await openPage(first);await pages()});button(body,'邀请好友加入',async()=>{const url=location.origin+location.pathname+'?join=shared';if(navigator.share)await navigator.share({title:'邀请一起共书',text:'一起练字、批注或留言。注册后互相关注即可共书。',url});else{await navigator.clipboard.writeText(url);mark('邀请链接已复制')}});button(body,'去书法殿堂互关',async()=>{dialog.close();await cloud.showGallery()});const rooms=navigator.onLine?check(await db.from('ink_shared_rooms128').select('*').order('created_at',{ascending:false}).limit(100))||[]:cached.rooms;cached.rooms=[...cached.rooms.filter(r=>r.offline133&&!rooms.some(x=>x.id===r.id)),...rooms];await DraftStore.set(cacheKey(),cached);for(const r of cached.rooms){const group=document.createElement('section');group.className='roomListing141';button(group,'进入 '+r.title,async()=>{if(page)await flushLocal();if(!backup)backup=A.getState();room=r;await pages()});await roomHeading141(group,r,false);body.append(group)}if(!dialog.open)dialog.showModal()}
 async function leave(){await flushLocal();await persistCache133();clearInterval(timer);generation++;room=null;page=null;pendingBatch=null;bar.hidden=true;await A.persist();if(backup){const state=backup;backup=null;await A.restoreDraft(state);A.setWorkIdentity128(state.editingWork110||null)}A.toast('已离开共书，笔迹留在共书页册')}
 function leaveAction139(host){button(host,'离开共书',async()=>{await leave();dialog.close()})}
 function activeActions139(host){button(host,'共书页册',pages);leaveAction139(host)}
 bar.querySelector('[data-pages]').onclick=()=>pages().catch(e=>mark(e.message));bar.querySelector('[data-leave]').onclick=()=>leave().catch(e=>mark(e.message));
 const entry=document.createElement('button');entry.id='sharedInk128';entry.className='tool90';entry.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M4 5h7l1 2 1-2h7v15h-7l-1 2-1-2H4zM12 7v13M7 9h2M15 9h2M7 13h2M15 13h2"/></svg><span>共书</span>';entry.title='与互关好友共同书写';entry.onclick=()=>open().catch(e=>mark(e.message));$('myWorks').before(entry);button($('worksDialog').querySelector('.dialogHead'),'共书页册',open);
 document.addEventListener('ink-stroke',e=>{if(!page)return;e.detail.stroke.id128=crypto.randomUUID();e.detail.stroke.writer128=uid();dirty=true;clearTimeout(window.sharedSaveTimer133);window.sharedSaveTimer133=setTimeout(()=>flushLocal().catch(e=>mark('本机共书保存待重试：'+e.message)),600)});
 addEventListener('online',()=>sync());
 document.addEventListener('cloud-copies83',()=>{if(lastUser&&lastUser!==uid()){clearInterval(timer);generation++;room=null;page=null;bar.hidden=true}lastUser=uid()||''});document.addEventListener('visibilitychange',()=>{if(document.hidden)flushLocal().catch(()=>{});else sync()});
 document.addEventListener('cloud-user84',async()=>{if(page)return;await restoreCache133();if(navigator.onLine)drain133().catch(e=>mark('共书草稿等待同步：'+e.message))});addEventListener('online',async()=>{if(page)return;await restoreCache133();drain133().catch(e=>mark('共书草稿等待同步：'+e.message))});Object.assign(root.SharedInk128,{open,sync,leave});
 })();
})(typeof window==='undefined'?globalThis:window);
