/* Durable, authorized operation log; concurrent strokes are merged by identity. */
(function(root){
 function applyOps(base,operations){const map=new Map(base.map(s=>[s.id128,s]));for(const row of operations)for(const op of row.payload||[]){if(op.kind==='delete')map.delete(op.id);else if(op.kind==='put'&&op.stroke?.id128)map.set(op.stroke.id128,op.stroke)}return [...map.values()]}
 root.SharedInk128={applyOps};
 if(!root.document)return;
 (function init(){if(!window.Revision128?.ready||!window.InkCloud75?.client||!window.SharedService142||!window.DraftCodec141){setTimeout(init,100);return}
 const A=AnnotationApp,cloud=InkCloud75,db=cloud.client,$=id=>document.getElementById(id);let room=null,page=null,baseline=new Map(),log=[],base=[],seq=0,polling=false,timer=0,backup=null,dirty=false,pendingBatch=null,lastUser='',generation=0,needsMerge=false;
 const uid=()=>cloud.user?.id,check=r=>{if(r.error)throw Error(r.error.message);return r.data},fingerprint=s=>JSON.stringify(s),identify=(s,i,seed='seed')=>({...s,id128:s.id128||seed+'-'+i});
 const dialog=document.createElement('dialog');dialog.className='collab128';dialog.innerHTML='<header class="dialogHead"><h2>共书 · 一起亲笔</h2><button data-close>×</button></header><p>家人一起练字、同学毕业留言、同事纪念。不必同时在线。像一卷历代递藏的真迹，书友接力题跋、钤印，各自留下一段墨缘。写完点击交卷，下位书友随时接续。</p><section data-body></section><p data-status role="status"></p>';document.body.append(dialog);dialog.querySelector('[data-close]').onclick=()=>{if(!body.inert){listGeneration143++;dialog.close()}};dialog.addEventListener('cancel',e=>{if(body.inert)e.preventDefault()});const body=dialog.querySelector('[data-body]'),status=dialog.querySelector('[data-status]');
 const bar=document.createElement('aside');bar.className='collabBar128';bar.hidden=true;bar.innerHTML='<span></span><button data-pages>页册</button><button data-leave>离开共书</button>';document.body.append(bar);const mark=text=>{status.textContent=text;bar.querySelector('span').textContent=text};
 const button=(host,label,fn)=>{const b=document.createElement('button');b.type='button';b.title=label;b.setAttribute('aria-label',label);b.className='relayIcon144';const paths={'交卷':'m5 12 4 4 10-11','钤印':'M7 15v-4h10v4M5 16h14v4H5zM10 4h4v7h-4z','题跋':'m4 20 4-1L20 7l-3-3L5 16z','离开':'M10 4H4v16h6M9 12h12m-4-4 4 4-4 4','邀请':'M8 3a3 3 0 100 6 3 3 0 000-6M2 20v-4a6 6 0 0112 0v4M19 8v8m-4-4h8','删除':'M4 7h16M9 3h6M6 7l1 14h10l1-14','结束':'M5 4h14v16H5zM9 10l2 2 4-4','保存':'M5 3h14v18H5zM8 3v6h8V3M8 15h8','页':'M4 4h7l1 2 1-2h7v15h-7l-1 2-1-2H4zM12 6v13'};const key=Object.keys(paths).find(k=>label.includes(k)),path=paths[key]||'m6 4 14 8-14 8V4';b.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="'+path+'"/></svg>';const caption=document.createElement('span');caption.textContent=/^发起/.test(label)?'发起':/^进入 /.test(label)?'进入':/^增加/.test(label)?'加纸':key==='页'?'页册':key||(/书写/.test(label)?'书写':/增加/.test(label)?'加纸':/发起/.test(label)?'发起':label.replace(/^进入 |^邀请 · |^已加入 · /,''));b.append(caption);b.onclick=async()=>{if(body.inert)return;b.disabled=true;body.inert=true;try{await fn()}catch(e){mark(e.message);A.toast(e.message);if(!dialog.open)dialog.showModal()}finally{body.inert=false;b.disabled=false}};host.append(b);return b};
 const cacheKey=()=> 'shared-offline133:'+(uid()||'guest');let cached={rooms:[],pages:{},queues:{},drafts:{}},localFlight133=null,draining133=false;
 const service142=SharedService142.create({cloud,codec:DraftCodec141});let closing142=false,previewAt142=0,baseDraft144=null,annotationBase144=null;
 const clone142=value=>structuredClone(value);
 async function create142(draft,title,thumbnail){if(!uid())throw Error('请先登录，再发起共书');if(page)throw Error('请先离开当前共书');A.finish();const previous=clone142(A.getState()),id=crypto.randomUUID();draft=clone142(draft);draft.flow.strokes=draft.flow.strokes.map((s,i)=>identify(s,i,id));draft.editingWork110=null;let r={id,owner:uid(),title:String(title||'一起亲笔').trim().slice(0,120)||'一起亲笔',participants:[uid()],offline133:!navigator.onLine},p={id:crypto.randomUUID(),room:id,author:uid(),title:'第 1 页',draft,thumbnail142:thumbnail||A.sharedThumbnail142()};if(navigator.onLine){mark('正在保存原笔迹并创建共书…');const saved=await service142.create(r,p);r=saved.room;p=saved.page}backup=previous;room=r;cached.pages[id]=[p];await persistCache133();await openPage(p);if(navigator.onLine)await invite();return r}
 async function fromWork142(id){await restoreCache133();const work=await DraftStore.get(id);if(!work)throw Error('作品暂时无法读取');return fromRecord142(work)}
 async function fromCloudWork142(row){await restoreCache133();return fromRecord142(await CloudDraft141.load(row))}
 async function fromRecord142(work){const account142=uid();await window.Revision128?.saveOnSwitch129?.();if(uid()!==account142)throw Error('账号已切换，请重新选择作品');if(!uid())throw Error('请先登录，再邀请书友');if(work.cloud141?.owner&&work.cloud141.owner!==uid())throw Error('请使用作品所属账号');let draft=work.draft;if(!draft){if(!work.blob)throw Error('作品图片暂时无法读取');draft=clone142(A.getState());draft.flow={strokes:[]};draft.signatureStrokes=[];draft.referenceData111='';draft.sealPositions={};draft.extraSeals=[];draft.photos=[{data:await dataURL142(work.blob),crop:{zoom:1,x:.5,y:.5}}];draft.photoData='';draft.values={...draft.values,photoMode:'gallery',guideMode:'off',headMode:'none',sealMode:'none',showLines:'no'}}const image=await thumbnail142(work.thumbnail||work.blob);if(uid()!==account142)throw Error('账号已切换，请重新选择作品');document.querySelectorAll('dialog').forEach(d=>{if(d.open)d.close()});body.replaceChildren();mark('正在发起共书…');if(!dialog.open)dialog.showModal();body.inert=true;try{await create142(draft,work.title,image);if(!dialog.open)dialog.showModal()}finally{body.inert=false}}
 async function thumbnail142(blob){if(!blob)return null;const url=URL.createObjectURL(blob);try{const image=await new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('作品缩略图读取失败'));im.src=url}),canvas=document.createElement('canvas'),scale=320/Math.max(image.width,image.height);canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.68)}finally{URL.revokeObjectURL(url)}}
 function dataURL142(blob){return new Promise((resolve,reject)=>{if(!blob){resolve(null);return}const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('缩略图读取失败'));reader.readAsDataURL(blob)})}
 async function forget142(r){for(const p of cached.pages[r.id]||[]){delete cached.queues[p.id];delete cached.drafts[p.id]}delete cached.pages[r.id];cached.rooms=cached.rooms.filter(x=>x.id!==r.id);if(room?.id===r.id){clearInterval(timer);generation++;room=null;page=null;pendingBatch=null;bar.hidden=true;A.setWorkIdentity128(null)}await DraftStore.set(cacheKey(),cached)}
 async function lifecycle142(r,remove=false){const me=uid(),wasActive=room?.id===r.id;if(r.owner!==me)throw Error('只有发起人可以结束或删除共书');if(!navigator.onLine)throw Error('请联网后结束或删除共书，当前笔迹已保存在本机');if(!confirm(remove?'删除全部共书页、共书作品及成员邀请？无法恢复。':'结束共书并解散成员邀请？完整作品会保留在你的作品表中。'))return;A.finish();if(page){if(!await flushLocal())throw Error('请先完成当前书写操作，再结束或删除共书');await drain133()}closing142=true;clearInterval(timer);generation++;try{if(r.offline133){if(!remove)await drain133();else{await forget142(r);await open();return}}Object.assign(r,await service142.close(r));const rows=check(await db.from('ink_shared_pages128').select('*').eq('room',r.id).order('created_at'))||[];if(!remove){for(const p of rows){if(uid()!==me)throw Error('账号已切换');mark('正在保存共书作品 '+p.title+'…');const id='shared-final:'+r.id+':'+p.id,old=await DraftStore.get(id),draft=await service142.snapshot(p),now=Date.now();draft.editingWork110=null;const blob=await A.workExport135({draft});const record={...old,id,title:r.title+' · '+p.title,date:new Date(now).toLocaleString('zh-CN'),created:old?.created||now,updated:now,blob,thumbnail:blob,draft,sharedRoom142:r.id,cloudLocalId142:'shared-archive:'+r.id+'|'+id};await DraftStore.saveWork(record);let saved=false;for(let i=0;i<15&&!saved;i++){if(uid()!==me)throw Error('账号已切换');saved=await cloud.saveNow101(record,false,true);if(!saved)await new Promise(resolve=>setTimeout(resolve,1000))}if(!saved)throw Error('云端保存正在忙，请稍后再次结束共书；作品已保存在本机')}}else{const cloudWorks=check(await db.from('ink_works').select('*').eq('owner',me).or('local_id.like.shared:'+r.id+'|%,local_id.like.shared-archive:'+r.id+'|%'))||[];for(const w of cloudWorks)await CloudDraft141.remove(w);const associated=new Set((cached.pages[r.id]||[]).map(p=>cached.drafts[p.id]?.editingWork110?.id).filter(Boolean)),index=await DraftStore.get('works-index')||[];for(const meta of index){if(uid()!==me)throw Error('账号已切换');const w=await DraftStore.get(meta.id);if(w&&(w.sharedRoom142===r.id||associated.has(w.id))){if(w.cloud141?.owner&&w.cloud141.owner!==me)continue;await CloudDraft141.deleteLocal(w.id);if(uid()!==me)throw Error('账号已切换');await DraftStore.deleteWorks([w.id])}}}const removed=await service142.remove(r);if(removed.cleanupPending)await DraftStore.set('shared-cleanup142:'+me+':'+r.id,r);await forget142(r);if(backup&&wasActive){const previous=backup;backup=null;await A.restoreDraft(previous);A.setWorkIdentity128(previous.editingWork110||null)}A.toast(remove?'共书作品及成员邀请已删除':rows.length?'共书已结束，作品已保存到我的作品并同步云端':'空共书已结束，没有作品页需要保存');document.dispatchEvent(new Event('cloud-copies83'));await open()}catch(e){mark('操作未完成，可重试：'+e.message);A.toast(e.message);if(!dialog.open)dialog.showModal();throw e}finally{closing142=false;if(page&&!room?.closed142)timer=setInterval(sync,30000)}}
 function lifecycleButtons142(host,r){if(r.owner!==uid())return;button(host,'结束',()=>lifecycle142(r));button(host,'删除',()=>lifecycle142(r,true))}
 function listingPreview142(host,r){const img=document.createElement('img');img.className='sharedPreview142';img.alt=r.title;img.loading='lazy';img.decoding='async';const p=(cached.pages[r.id]||[])[0];if(p?.thumbnail142){img.src=p.thumbnail142;host.prepend(img)}else host.dataset.preview143='pending'}
 let listGeneration143=0;
 async function listQuery143(query){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{return check(await query.abortSignal(controller.signal))||[]}finally{clearTimeout(timer)}}
 async function enterRoom143(r){await window.Revision128?.saveOnSwitch129?.();if(page)await flushLocal();if(!backup)backup=A.getState();room=r;const rows=navigator.onLine&&!r.offline133?await listQuery143(db.from('ink_shared_pages128').select('id,room,author,title,created_at,draft_path142,thumbnail142').eq('room',r.id).order('created_at')):cached.pages[r.id]||[];cached.pages[r.id]=rows;if(rows.length===1){await openPage(rows[0]);return}await pages()}

 async function restoreCache133(){cached=await DraftStore.get(cacheKey())||{rooms:[],pages:{},queues:{},drafts:{}};cached.queues||={};cached.drafts||={}}
 async function persistCache133(){if(page)cached.drafts[page.id]=A.getState();if(room){cached.rooms=cached.rooms.filter(r=>r.id!==room.id);cached.rooms.unshift(room)}await DraftStore.set(cacheKey(),cached)}
 async function renameRoom141(r,title){const me=uid();if(!me||r.owner!==me)throw Error('只有发起人可以修改小组名称');title=String(title).trim().slice(0,120);if(!title)throw Error('请填写小组名称');if(r.offline133){r.title=title}else{if(!navigator.onLine)throw Error('请联网后修改小组名称');const saved=check(await db.from('ink_shared_rooms128').update({title}).eq('id',r.id).eq('owner',me).select('id,title,participants').single());if(uid()!==me)throw Error('账号已切换，请重新打开共书');Object.assign(r,saved)}if(room?.id===r.id)room=r;await persistCache133();return r}
 async function roomHeading141(host,r=room,editable=true){if(!r)return;if(editable&&navigator.onLine&&!r.offline133){try{const me=uid(),fresh=check(await db.from('ink_shared_rooms128').select('id,title,participants').eq('id',r.id).single());if(me!==uid())return;Object.assign(r,fresh)}catch{}}const box=document.createElement('section');box.className='roomHeading141';const name=document.createElement('strong');name.textContent=r.title;box.append(name);const members=document.createElement('p');members.className='roomMembers141';const ids=[...new Set(r.participants||[])];let profiles=[];if(editable&&navigator.onLine&&ids.length){try{profiles=check(await db.from('ink_profiles83').select('owner,display_name').in('owner',ids))||[];r.memberNames141=Object.fromEntries(profiles.map(p=>[p.owner,p.display_name]))}catch{}}members.textContent='共同书写：'+ids.map(id=>r.memberNames141?.[id]||(id===uid()?cloud.user?.user_metadata?.full_name||'我':'书友 '+id.slice(0,6))).join('、');box.append(members);if(editable&&r.owner===uid()){const input=document.createElement('input');input.value=r.title;input.maxLength=120;input.setAttribute('aria-label','小组名称');box.append(input);button(box,'保存组名',async()=>{await renameRoom141(r,input.value);name.textContent=r.title;input.value=r.title;mark('小组名称已更新')})}host.append(box)}
 async function drain133(){if(!navigator.onLine||!uid())return;while(draining133)await new Promise(resolve=>setTimeout(resolve,25));if(!navigator.onLine||!uid())return;draining133=true;const owner=uid(),cache=cached,key=cacheKey(),valid=()=>navigator.onLine&&uid()===owner;try{for(const r of cache.rooms.filter(r=>r.offline133)){if(!valid())return;const list=cache.pages[r.id]||[];if(list.length){const saved=await service142.create(r,list[0]);Object.assign(r,saved.room);list[0]=saved.page;for(let i=1;i<list.length;i++){if(!valid())return;list[i]=await service142.addPage(r,list[i])}}delete r.offline133;await DraftStore.set(key,cache)}for(const jobs of Object.values(cache.queues)){while(jobs.length){if(!valid())return;const op=jobs[0],r=await db.from('ink_shared_ops128').insert(op);if(r.error&&r.error.code!=='23505'){const p=check(await db.from('ink_shared_pages128').select('room').eq('id',op.page).maybeSingle()),group=p?check(await db.from('ink_shared_rooms128').select('closed142').eq('id',p.room).maybeSingle()):null;if(group&&!group.closed142)check(r);await DraftStore.set('shared-detached142:'+owner+':'+op.page,cache.drafts[op.page]||{operations:jobs})}jobs.shift();await DraftStore.set(key,cache)}}for(const [cleanupKey,r]of await DraftStore.entries('shared-cleanup142:'+owner+':')){if(!valid())return;await service142.cleanup(r);await DraftStore.delete(cleanupKey)}}finally{draining133=false}}
 async function flushLocal(){if(localFlight133)return localFlight133;localFlight133=flushLocalInner133();try{return await localFlight133}finally{localFlight133=null}}

 async function flushLocalInner133(){if(!page||!uid()||A.isDrawing128())return false;const savingOwner133=uid(),savingPage133=page.id,savingGeneration133=generation;let annotationPayload144=[];if(annotationBase144){const delta=RelayModel144.annotationOps(annotationBase144,A.getState(),uid(),page.id);if(delta.payload.length)A.collabMerge144(delta.next);annotationPayload144=delta.payload;}let local=A.getState().flow.strokes.map((s,i)=>identify(s,i,'local-'+uid()));const remote144=applyOps(base,log),owned144=new Map(local.map(s=>[s.id128,s]));for(const s of remote144)if(s.writer128&&s.writer128!==uid())owned144.set(s.id128,s);const protected144=[...owned144.values()];if(JSON.stringify(protected144)!==JSON.stringify(local))A.collabMerge128(protected144);local=protected144;const payload=[...annotationPayload144];const now=new Map(local.map(s=>[s.id128,s]));for(const [id,s]of now)if((!s.writer128||s.writer128===uid())&&baseline.get(id)!==fingerprint(s))payload.push({kind:'put',stroke:s});for(const id of baseline.keys())if(!now.has(id)&&(applyOps(base,log).find(s=>s.id128===id)?.writer128===uid()))payload.push({kind:'delete',id});if(payload.length){pendingBatch=pendingBatch||{id:crypto.randomUUID(),page:page.id,writer:uid(),payload};const jobs=cached.queues[page.id]||=([]);if(!jobs.some(j=>j.id===pendingBatch.id))jobs.push(pendingBatch);await persistCache133();if(uid()!==savingOwner133||page?.id!==savingPage133||generation!==savingGeneration133)return false;for(const op of pendingBatch.payload){if(op.kind==='delete')baseline.delete(op.id);else if(op.kind==='put')baseline.set(op.stroke.id128,fingerprint(op.stroke))}pendingBatch=null;if(annotationBase144){const d=A.getState();annotationBase144=structuredClone({signatureStrokes:d.signatureStrokes,extraSeals:d.extraSeals})}const latest=A.getState().flow.strokes;if(latest.length!==baseline.size||latest.some(s=>baseline.get(s.id128)!==fingerprint(s))){dirty=true;return false}}dirty=false;return true}
 async function sync(){if(closing142||polling||!page||!uid()||document.hidden)return;const run=generation,currentPage=page.id;polling=true;try{if(!await flushLocal())return;if(!navigator.onLine){mark(room.title+' · 离线草稿已保存在本机');return}const fresh=check(await db.from('ink_shared_rooms128').select('id,closed142,participants').eq('id',room.id).maybeSingle());if(run!==generation)return;if(!fresh||fresh.closed142){await persistCache133();await DraftStore.set('shared-detached142:'+uid()+':'+page.id,A.getState());await A.autosave128();await forget142(room);await A.persist();A.toast('共书已结束，当前笔迹已保留在本机');return}await drain133();if(Date.now()-previewAt142>30000&&!A.isDrawing128()){check(await db.from('ink_shared_pages128').update({thumbnail142:A.sharedThumbnail142()}).eq('id',currentPage));previewAt142=Date.now()}let rows=check(await db.from('ink_shared_ops128').select('seq,id,payload,writer').eq('page',currentPage).gt('seq',seq).order('seq').limit(500))||[];if(run!==generation||currentPage!==page?.id)return;if(rows.length){log.push(...rows);seq=rows.at(-1).seq;needsMerge=true}if(needsMerge){const current=A.getState().flow.strokes;if(A.isDrawing128()||current.length!==baseline.size||current.some(s=>baseline.get(s.id128)!==fingerprint(s))){dirty=true;return}const strokes=applyOps(base,log);const annotations144=RelayModel144.mergeAnnotations(baseDraft144,log);if(A.collabMerge128(strokes)&&A.collabMerge144(annotations144)){baseline=new Map(strokes.map(s=>[s.id128,fingerprint(s)]));annotationBase144=annotations144;needsMerge=false;mark(room.title+' · 已交卷，书友可接续')}else{dirty=true}}else mark(room.title+' · 接力题跋')}catch(e){mark('暂未同步，笔迹保留在本机：'+e.message)}finally{polling=false}}
 async function openPage(next){listGeneration143++;if(room?.closed142)throw Error('共书已结束，请由发起人结束并保存作品');if(next.draft_path142&&!next.draft)next=await service142.hydrate(next);if(!next.draft)next=check(await db.from('ink_shared_pages128').select('*').eq('id',next.id).single());if(page)await flushLocal();generation++;page=next;baseDraft144=RelayModel144.seedDraft(next.draft,next.id,next.author||room.owner);base=(next.draft.flow?.strokes||[]).map((s,i)=>({...identify(s,i,next.id),writer128:s.writer128||next.author||room.owner}));log=[];seq=0;pendingBatch=null;const saved=cached.drafts[next.id],draft=RelayModel144.seedDraft({...(saved||baseDraft144),flow:{strokes:saved?.flow?.strokes||base},editingWork110:null},next.id,next.author||room.owner);annotationBase144=structuredClone({signatureStrokes:baseDraft144.signatureStrokes,extraSeals:baseDraft144.extraSeals});await A.newBlank54();await A.restoreDraft(draft);A.setWorkIdentity128(null);A.collabMerge128(draft.flow.strokes);baseline=new Map(base.map(s=>[s.id128,fingerprint(s)]));bar.hidden=true;dialog.close();A.showWriter();clearInterval(timer);timer=setInterval(sync,30000);await sync()}
 async function pages(){return dashboard145()}
 async function invite(){return dashboard145()}
 async function dashboard145(){if(!room)return;const me=uid(),r=room;body.replaceChildren();await roomHeading141(body);const actions=document.createElement('div');actions.className='relayActions145';body.append(actions);const sealLabel=document.createElement('label'),sealInput=document.createElement('input');sealLabel.className='sealInline145';sealLabel.append(document.createTextNode('收藏印'));sealInput.dataset.seal145='';sealInput.maxLength=12;sealInput.value=cloud.user?.user_metadata?.full_name||'我的珍藏';sealInput.setAttribute('aria-label','收藏印文，最多12字');sealLabel.append(sealInput);body.append(sealLabel);if(page)activeActions139(actions);lifecycleButtons142(actions,r);
 const section=document.createElement('section');section.className='relaySection145';const title=document.createElement('h3');title.textContent='共书页册';section.append(title);body.append(section);const rows=navigator.onLine&&!r.offline133?await listQuery143(db.from('ink_shared_pages128').select('id,room,author,title,created_at,draft_path142,thumbnail142').eq('room',r.id).order('created_at')):cached.pages[r.id]||[];if(room!==r||uid()!==me)return;cached.pages[r.id]=rows;const select=document.createElement('select');select.setAttribute('aria-label','选择共书页');select.add(new Option('选择一页，接力书写',''));rows.forEach((p,i)=>select.add(new Option((i+1)+' · '+p.title,p.id)));select.value=page?.id||'';select.onchange=async()=>{const next=rows.find(p=>p.id===select.value);if(!next)return;select.disabled=true;try{await openPage(next)}catch(e){mark(e.message)}finally{select.disabled=false}};section.append(select);button(section,'增加共书纸',async()=>{if(page)await flushLocal();const d=A.getState();d.flow={strokes:[]};d.signatureStrokes=[];d.editingWork110=null;let p={id:crypto.randomUUID(),room:r.id,author:me,title:'第 '+(rows.length+1)+' 页',draft:d};if(navigator.onLine&&!r.offline133)p=await service142.addPage(r,p);else if(!r.offline133)throw Error('新增共书页需要联网');rows.push(p);await persistCache133();await openPage(p)});
 if(r.owner===me&&navigator.onLine&&!r.closed142){const friends=document.createElement('section');friends.className='relaySection145';const h=document.createElement('h3');h.textContent='邀请互关书友';friends.append(h);body.append(friends);try{const follows=await listQuery143(db.from('ink_follows116').select('follower,followed').or('follower.eq.'+me+',followed.eq.'+me)),mine=new Set(follows.filter(x=>x.follower===me).map(x=>x.followed)),ids=[...new Set(follows.filter(x=>x.followed===me&&mine.has(x.follower)).map(x=>x.follower))],profiles=ids.length?await listQuery143(db.from('ink_profiles83').select('owner,display_name').in('owner',ids)):[];if(room!==r||uid()!==me)return;const chips=document.createElement('div');chips.className='relayInvites145';friends.append(chips);for(const id of ids){const name=profiles.find(p=>p.owner===id)?.display_name||'书友 '+id.slice(0,6);const b=button(chips,(r.participants.includes(id)?'已加入 · ':'邀请 · ')+name,async()=>{if(r.participants.includes(id))return;const next=[...r.participants,id];check(await db.from('ink_shared_rooms128').update({participants:next}).eq('id',r.id));r.participants=next;await persistCache133();b.querySelector('span').textContent=name+' · 已加入';mark(name+' 已加入这卷墨缘')});b.querySelector('span').textContent=name+(r.participants.includes(id)?' · 已加入':'')}
 if(!ids.length){const note=document.createElement('p');note.textContent='还没有互关书友，先邀请家人来认识这卷纸。';friends.append(note)}button(friends,'邀请好友加入',async()=>{const url=location.origin+location.pathname+'?join=shared',text='一起在今日亲笔接力题跋、钤印。注册后互相关注，就可以共书一页纸。';if(navigator.share)await navigator.share({title:'邀请一起共书',text,url});else{await navigator.clipboard.writeText(text+' '+url);mark('邀请链接已复制')}})}catch(e){const note=document.createElement('p');note.textContent='好友列表暂未加载：'+e.message;friends.append(note)}}await persistCache133();if(!dialog.open)dialog.showModal();mark(r.title+' · 所有共书操作都在这里')}
 async function open(){const run=++listGeneration143,me=uid();body.replaceChildren();status.textContent='正在读取共书…';if(!me){A.toast('请先登录，再发起或加入共书');$('account47').click();return}if(!dialog.open)dialog.showModal();if(page)await flushLocal();await restoreCache133();if(run!==listGeneration143||uid()!==me||!dialog.open)return;if(room&&page){await dashboard145();return}
 const title=document.createElement('input');title.placeholder='家人练字 / 毕业留言 / 同事纪念';title.value='一起亲笔';title.setAttribute('aria-label','共书名称');body.append(title);button(body,'发起共书并邀请',async()=>{await window.Revision128?.saveOnSwitch129?.();A.finish();await create142(A.getState(),title.value)});const list=document.createElement('section');list.className='sharedList143';body.append(list);
 async function draw(){list.replaceChildren();for(const r of cached.rooms){const group=document.createElement('section');group.className='roomListing141';button(group,'进入 '+r.title,()=>enterRoom143(r));await roomHeading141(group,r,false);lifecycleButtons142(group,r);listingPreview142(group,r);list.append(group)}}
 await draw();if(!navigator.onLine){mark('离线共书 · 已显示本机记录');return}try{const rooms=await listQuery143(db.from('ink_shared_rooms128').select('*').order('created_at',{ascending:false}).limit(100));if(run!==listGeneration143||uid()!==me||!dialog.open)return;cached.rooms=[...cached.rooms.filter(r=>r.offline133&&!rooms.some(x=>x.id===r.id)),...rooms];await draw();mark(rooms.length?'点击共书即可进入书写':'还没有共书，点击上方发起');const ids=rooms.map(r=>r.id),members=[...new Set(rooms.flatMap(r=>r.participants||[]))];const result=await Promise.allSettled([ids.length?listQuery143(db.from('ink_shared_pages128').select('id,room,author,title,created_at,thumbnail142,draft_path142').in('room',ids).order('created_at').limit(1500)):[],members.length?listQuery143(db.from('ink_profiles83').select('owner,display_name').in('owner',members)):[]]);if(run!==listGeneration143||uid()!==me||!dialog.open||page)return;
 if(result[0].status==='fulfilled'){const groups=new Map(ids.map(id=>[id,[]]));for(const p of result[0].value)groups.get(p.room)?.push(p);for(const [id,rows]of groups)cached.pages[id]=rows}if(result[1].status==='fulfilled'){const names=Object.fromEntries(result[1].value.map(p=>[p.owner,p.display_name]));rooms.forEach(r=>r.memberNames141=names)}await draw();await DraftStore.set(cacheKey(),cached)}catch(e){if(run===listGeneration143&&uid()===me&&dialog.open)mark('联网读取较慢，已保留本机共书。可关闭后重试：'+e.message)}}

 async function handoff144(){A.finish();if(!await flushLocal())throw Error('请先完成笔画');await sync();if(Object.values(cached.queues).some(j=>j.length)&&navigator.onLine)throw Error('仍有接力记录等待上传，请重试交卷');A.toast(navigator.onLine?'交卷成功！你的墨迹与收藏印，已交给下一位有缘人。':'离线交卷已存本机，联网后自动递给书友。')}
 async function leave(){A.finish();if(navigator.onLine)await handoff144();else await flushLocal();await persistCache133();clearInterval(timer);generation++;room=null;page=null;pendingBatch=null;bar.hidden=true;await A.persist();if(backup){const state=backup;backup=null;await A.restoreDraft(state);A.setWorkIdentity128(state.editingWork110||null)}A.toast('已离开共书，笔迹留在共书页册')}
 function leaveAction139(host){button(host,'离开共书',async()=>{await leave();dialog.close()})}
 function activeActions139(host){button(host,'交卷',handoff144);button(host,'题跋',()=>{dialog.close();A.showWriter();if(!A.signatureStatus110().active)A.toggleSignature110();A.toast('题跋留给后来人：今天的你，也是一位收藏家。')});button(host,'钤印',()=>{const name=String(body.querySelector('[data-seal145]')?.value||cloud.user?.user_metadata?.full_name||'我的珍藏').trim().slice(0,12);if(!name)return;A.relaySeal144(name);dialog.close();A.showWriter();A.toast('印章已落在纸上，可拖动定位，再点击共书交卷。')});button(host,'继续书写',()=>{dialog.close();A.showWriter()});leaveAction139(host)}
 bar.querySelector('[data-pages]').onclick=()=>pages().catch(e=>mark(e.message));bar.querySelector('[data-leave]').onclick=()=>leave().catch(e=>mark(e.message));
 const entry=document.createElement('button');entry.id='sharedInk128';entry.className='tool90';entry.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M4 5h7l1 2 1-2h7v15h-7l-1 2-1-2H4zM12 7v13M7 9h2M15 9h2M7 13h2M15 13h2"/></svg><span>共书</span>';entry.title='与互关好友共同书写';entry.onclick=()=>open().catch(e=>{mark(e.message);A.toast(e.message);if(!dialog.open)dialog.showModal()});$('myWorks').before(entry);button($('worksDialog').querySelector('.dialogHead'),'共书页册',open);
 document.addEventListener('ink-stroke',e=>{if(!page)return;e.detail.stroke.id128=crypto.randomUUID();e.detail.stroke.writer128=uid();dirty=true;clearTimeout(window.sharedSaveTimer133);window.sharedSaveTimer133=setTimeout(()=>flushLocal().catch(e=>mark('本机共书保存待重试：'+e.message)),600)});
 addEventListener('online',()=>sync());
 document.addEventListener('cloud-copies83',()=>{if(lastUser&&lastUser!==uid()){clearInterval(timer);generation++;room=null;page=null;bar.hidden=true}lastUser=uid()||''});document.addEventListener('visibilitychange',()=>{if(document.hidden)flushLocal().catch(()=>{});else sync()});
 document.addEventListener('cloud-user84',async()=>{if(page)return;await restoreCache133();if(navigator.onLine)drain133().catch(e=>mark('共书草稿等待同步：'+e.message))});addEventListener('online',async()=>{if(page)return;await restoreCache133();drain133().catch(e=>mark('共书草稿等待同步：'+e.message))});Object.assign(root.SharedInk128,{open,sync,leave,fromWork142,fromCloudWork142});Object.defineProperties(root.SharedInk128,{roomId142:{get:()=>room?.id||null},closing142:{get:()=>closing142}});
 })();
})(typeof window==='undefined'?globalThis:window);
