/* Supabase-only accounts. Local creative tools never depend on authentication. */
(function init(){
'use strict';
if(!window.InkStudio50?.ready){setTimeout(init,50);return}
const U=InkStudio50,E=U.E,app=AnnotationApp;let client,user=null,panel,body,status,authMode='login',busy=false,subscription;
window.Member47={user:null,canAdvanced:()=>true};
const names=[];for(const parent of [document.querySelector('.annotationBrand'),document.getElementById('topActions')]){const b=E('button',{type:'button',class:'accountName51','aria-label':'用户名与云端作品'},'');b.innerHTML='<svg viewBox="0 0 24 24" width="21" height="21" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="8" r="4"/><path d="M4 22v-2a8 8 0 0 1 16 0v2"/></svg>';b.onclick=open;parent?.append(b);names.push(b)}
function report(e){if(status)status.textContent=e.message||String(e);else app.toast(e.message||String(e))}
function action(parent,label,fn){const b=E('button',{type:'button'},label);b.onclick=async()=>{if(b.disabled)return;b.disabled=true;try{await fn()}catch(e){report(e)}finally{b.disabled=false}};parent.append(b);return b}
function updateUser(value){user=value;Member47.user=user;for(const b of names){b.title=user?(user.user_metadata?.display_name||user.email||'我的账号'):'我的账号';b.setAttribute('aria-label',b.title);b.classList.toggle('signedIn53',!!user)}if(panel&&!panel.hidden)render()}
function getConfig(){const c=window.IINNKK_SUPABASE||{};if(!c.url||!c.anonKey)return null;const url=new URL(c.url);if(url.protocol!=='https:')throw Error('Supabase Project URL 必须使用 HTTPS');if(c.anonKey.startsWith('sb_secret_'))throw Error('不能在前端配置 Secret Key');if(c.anonKey.split('.').length===3){try{const p=JSON.parse(atob(c.anonKey.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));if(p.role==='service_role')throw Error('不能在前端配置 service_role 密钥')}catch(e){if(e.message.includes('service_role'))throw e}}return c}
let pending;
async function connect(){if(client)return client;if(pending)return pending;pending=(async()=>{const c=getConfig();if(!c)throw Error('云端尚未配置。提供 Supabase Project URL 和 Anon / Publishable Key 后即可启用；本机创作不受影响。');if(!window.IInkSupabaseSDK)await new Promise((resolve,reject)=>{const script=E('script',{src:'supabase51.js?v=51'});script.onload=resolve;script.onerror=()=>{script.remove();reject(Error('账号模块未加载，请检查网络或源码包'))};document.head.append(script)});client=IInkSupabaseSDK.createClient(c.url,c.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:location.protocol!=='file:',storageKey:'iinnkk.supabase.auth'}});subscription=client.auth.onAuthStateChange((event,session)=>{setTimeout(()=>{updateUser(session?.user||null);if(event==='PASSWORD_RECOVERY'){authMode='recovery';open();render()}},0)}).data.subscription;const {data,error}=await client.auth.getSession();if(error)throw error;updateUser(data.session?.user||null);return client})().finally(()=>pending=null);return pending}
function open(){if(!panel){panel=E('section',{id:'accountPanel51','aria-label':'我的账号与云端作品'});const head=E('header');head.append(E('h2',{},'亲笔云笺'));action(head,'返回书写 ×',()=>{panel.hidden=true});body=E('div',{class:'accountBody51'});panel.append(head,body);document.body.append(panel)}panel.hidden=false;render();connect().catch(report)}
function field(parent,label,type){const l=E('label',{},label),i=E('input',{type,required:'',autocomplete:type==='password'?'current-password':'email'});l.append(i);parent.append(l);return i}
function render(){if(!body)return;body.replaceChildren();status=E('p',{role:'status',class:'accountStatus51'});body.append(status);body.append(E('p',{},'书写、选字、图文、印章和文创自由使用。登录用于云端保存与跨设备取回。'));
if(!user||authMode==='recovery'){const form=E('form'),email=authMode==='recovery'?null:field(form,'邮箱','email'),password=field(form,authMode==='recovery'?'设置新密码':'密码','password');password.minLength=8;const submit=E('button',{type:'submit'},authMode==='signup'?'注册账号':authMode==='recovery'?'更新密码':'登录');form.append(submit);form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;submit.disabled=true;try{const c=await connect();let result;if(authMode==='signup')result=await c.auth.signUp({email:email.value.trim(),password:password.value,options:location.protocol==='https:'?{emailRedirectTo:location.origin+location.pathname}:{}});else if(authMode==='recovery')result=await c.auth.updateUser({password:password.value});else result=await c.auth.signInWithPassword({email:email.value.trim(),password:password.value});if(result.error)throw result.error;if(authMode==='signup'&&!result.data.session)status.textContent='请到邮箱确认注册，然后返回这里登录。';else{authMode='login';updateUser(result.data.user)}}catch(e){report(e)}finally{password.value='';busy=false;submit.disabled=false}};body.append(form);if(authMode!=='recovery'){action(body,authMode==='signup'?'已有账号，去登录':'没有账号，注册',()=>{authMode=authMode==='signup'?'login':'signup';render()});action(body,'忘记密码',async()=>{if(!email.validity.valid||!email.value)throw Error('请先填写有效邮箱');if(location.protocol==='file:')throw Error('请在网站 HTTPS 地址上重置密码，本地可直接使用密码登录');const c=await connect(),r=await c.auth.resetPasswordForEmail(email.value.trim(),{redirectTo:location.origin+location.pathname});if(r.error)throw r.error;status.textContent='若邮箱已注册，将收到重置邮件。'})}return}
body.append(E('h3',{},user.email||'我的账号'));const tools=E('div',{class:'accountTools51'});body.append(tools);action(tools,'上传全部本机作品',uploadLocal);action(tools,'查看云端作品',listCloud);action(tools,'同步当前设置',async()=>{const c=await authorized(),r=await c.from('ink_settings').upsert({owner:user.id,settings:app.settingsSnapshot()});if(r.error)throw r.error;status.textContent='当前设置已同步到云端'});action(tools,'取回云端设置',async()=>{const c=await authorized(),r=await c.from('ink_settings').select('settings').eq('owner',user.id).maybeSingle();if(r.error)throw r.error;if(!r.data)throw Error('还没有云端设置');app.applyCloudSettings(r.data.settings);status.textContent='设置已取回并保存到本机'});action(tools,'会员功能',()=>{status.textContent='当前全部创作功能开放使用，无需购买会员。云端容量由所连接的 Supabase 项目配置决定。'});action(tools,'退出账号',async()=>{const r=await client.auth.signOut();if(r.error)throw r.error;updateUser(null)});body.append(E('div',{id:'cloudWorks51'}));}
async function authorized(){const c=await connect();const r=await c.auth.getUser();if(r.error||!r.data.user)throw Error('请点击顶部“我的账号”登录后使用云端同步');user=r.data.user;return c}
async function uploadLocal(){if(busy)return;busy=true;try{const c=await authorized(),owner=user.id,all=await DraftStore.get('works-index')||[];if(!all.length)throw Error('本机没有作品，请先生成并保存一幅作品');let done=0;for(const meta of all){const w=await DraftStore.get(meta.id);if(!w?.blob)continue;const previous=await c.from('ink_works').select('id,image_path,draft_path').eq('owner',owner).eq('local_id',w.id).maybeSingle();if(previous.error)throw previous.error;const id=previous.data?.id||crypto.randomUUID(),prefix=owner+'/'+id+'/'+crypto.randomUUID(),imagePath=prefix+'/image.png',draftPath=w.draft?prefix+'/draft.json':null,uploaded=[];try{const im=await c.storage.from('ink-works').upload(imagePath,w.blob,{contentType:w.blob.type||'image/png'});if(im.error)throw im.error;uploaded.push(imagePath);if(draftPath){const dr=await c.storage.from('ink-works').upload(draftPath,new Blob([JSON.stringify(w.draft)],{type:'application/json'}));if(dr.error)throw dr.error;uploaded.push(draftPath)}const row={id,owner,local_id:w.id,title:w.title||'亲笔真迹',image_path:imagePath,draft_path:draftPath,updated_at:new Date().toISOString()},r=await c.from('ink_works').upsert(row,{onConflict:'owner,local_id'});if(r.error)throw r.error;}catch(e){if(uploaded.length)await c.storage.from('ink-works').remove(uploaded);throw e}const old=[previous.data?.image_path,previous.data?.draft_path].filter(Boolean);if(old.length)await c.storage.from('ink-works').remove(old);status.textContent='已同步 '+(++done)+' / '+all.length+' 幅';}status.textContent='已同步 '+done+' 幅作品，本机原作保留。';await listCloud()}finally{busy=false}}
async function listCloud(){const c=await authorized(),owner=user.id,r=await c.from('ink_works').select('*').eq('owner',owner).order('updated_at',{ascending:false});if(r.error)throw r.error;const grid=document.getElementById('cloudWorks51');if(!grid)return;grid.replaceChildren();if(!r.data.length)grid.append(E('p',{},'云端还没有作品。'));for(const w of r.data){const card=E('article'),signed=await c.storage.from('ink-works').createSignedUrl(w.image_path,600);if(!signed.error)card.append(E('img',{src:signed.data.signedUrl,alt:w.title,loading:'lazy'}));card.append(E('h3',{},w.title));action(card,'下载为本机新副本',()=>pull(w,false));if(w.draft_path)action(card,'取回并继续编辑',()=>pull(w,true));action(card,'删除云端副本',async()=>{if(!confirm('删除云端副本？本机作品保留。'))return;await authorized();const removed=await c.storage.from('ink-works').remove([w.image_path,w.draft_path].filter(Boolean));if(removed.error)throw removed.error;const d=await c.from('ink_works').delete().eq('id',w.id).eq('owner',owner);if(d.error)throw d.error;await listCloud()});grid.append(card)}}
async function pull(w,edit){const c=await authorized(),im=await c.storage.from('ink-works').download(w.image_path);if(im.error)throw im.error;let draft=null;if(w.draft_path){const r=await c.storage.from('ink-works').download(w.draft_path);if(r.error)throw r.error;draft=JSON.parse(await r.data.text())}const now=Date.now(),id='work:cloud:'+crypto.randomUUID();await DraftStore.saveWork({id,title:w.title+' · 云端副本',date:new Date(now).toLocaleString(),created:now,blob:im.data,thumbnail:im.data,draft});if(edit&&draft){if(app.hasInk()&&!confirm('本机新副本已保存。切换到这幅云端作品编辑？当前草稿请先保存。'))return;await app.restoreDraft(draft);panel.hidden=true;app.showWriter()}else{status.textContent='已存入“我的作品”，没有覆盖本机原作。';await app.openWork(id)}}
// No network request when unconfigured. Returning users get their cached identity restored.
try{if(getConfig())connect().catch(report)}catch(e){report(e)}
window.InkCloud51={open,connect,getConfig};
})();
