(async function init(){if(!window.Revision47?.ready){setTimeout(init,40);return}const $=id=>document.getElementById(id),app=AnnotationApp,{create:E,dialog}=Revision47;let me=null,site={content:{},revision:0,templates:[]},session=null,parentWork=window.parentWork47||null,activeWork=null,publishBusy=false;
// Creative tools are available to everyone; cloud ownership and admin checks remain separate.
window.Member47={user:null,canAdvanced:()=>true};
const api=async(path,options={})=>{const headers=new Headers(options.headers);if(options.body&&typeof options.body!=='string'&&!(options.body instanceof Blob)&&!(options.body instanceof ArrayBuffer)){headers.set('content-type','application/json');options.body=JSON.stringify(options.body)}const r=await fetch(path,{...options,headers,credentials:'same-origin',cache:'no-store'});let d;try{d=await r.json()}catch{throw Error('此站尚未启用在线服务，本机作品仍可使用')}if(!r.ok)throw Error(d.error||'操作未完成，请重试');return d};
const report=e=>app.toast(e.message||String(e));const run=fn=>async()=>{try{await fn()}catch(e){report(e)}};const action=(label,fn,parent,primary=false)=>{const b=E('button',{class:primary?'primary':''},label);b.onclick=run(fn);parent.append(b);return b};
const account=dialog('accountDialog47','我的亲笔'),login=E('button',{id:'account47'},'登录');document.querySelector('.annotationBrand').append(login);login.onclick=()=>{renderAccount();app.openDialog(account.d.id)};
const gallery=E('section',{id:'community47'}),gh=E('div',{class:'actions47'}),grid=E('div',{class:'communityGrid47'});gh.append(E('h2',{},'亲笔广场'));action('刷新',loadGallery,gh);gallery.append(gh,grid);$('annotationHome').append(gallery);
async function loadSession(){session=await api('/api/session');me=session.user;login.textContent=me?me.name+' · '+({founder:'书仙',saint:'书圣',member:'书家'}[me.role]):'登录';window.Member47={user:me,canAdvanced:()=>true};return session}
function renderAccount(){const b=account.b;b.replaceChildren();if(!session){b.append(E('p',{class:'notice47'},'在线账号服务尚未连接。可继续本机书写；已保存的本机作品不会删除。'));action('重新连接',async()=>{await loadSession();renderAccount()},b);return}if(!me){b.append(E('p',{class:'notice47'},'创作功能全部免费开放，无需登录。登录仅用于云端同步和作品互动。'));const p=E('div',{class:'actions47'});for(const provider of session.providers){const a=E('a',{class:'provider47',href:provider.enabled?'/api/auth/'+provider.id+'/start':'#','aria-disabled':String(!provider.enabled)},provider.name);if(!provider.enabled)a.onclick=e=>{e.preventDefault();app.toast(provider.name+'登录尚未完成平台应用授权')};p.append(a)}b.append(p);if(session.sitesSignIn)b.append(E('a',{href:'/signin-with-chatgpt?return_to=%2F%3FsignedIn%3D1',target:'_top'},'使用 ChatGPT 登录'));b.append(E('p',{class:'notice47'},'灰色入口等待平台授权，不会模拟登录。'));return}
const name=E('input',{value:me.name,'aria-label':'显示名称',maxlength:'50'});b.append(name);action('保存昵称',async()=>{await api('/api/profile',{method:'PATCH',body:{name:name.value}});await loadSession();renderAccount()},b);const stats=E('div',{class:'accountStats47'});b.append(stats);api('/api/stats').then(s=>{for(const[k,label,v]of [['characters','估算书写字数',s.characters],['days','书写天数',s.days],['seconds','累计分钟',Math.round(s.seconds/60)]]){const d=E('div');d.append(E('strong',{},String(v||0)),E('small',{},label));stats.append(d)}}).catch(report);b.append(E('p',{class:'notice47'},'所有创作功能已免费开放，无体验期限'));
const a=E('div',{class:'actions47'});action('保存我的设置',saveCloudSettings,a);action('恢复云端设置',async()=>{const c=await api('/api/settings');if(!c.settings)throw Error('还没有云端设置');app.applyCloudSettings(c.settings);if(c.toolbar)restoreToolbarOrder(c.toolbar);if(c.moments)await DraftStore.set('annotation.moments.v1',c.moments);app.toast('已恢复云端设置')},a);action('我的云端作品',showMine,a);if(me.role==='founder'){action('网站管理',openAdmin,a);action('所见即所得编辑',()=>{account.d.close();startCMS()},a)}action('退出',async()=>{await api('/api/auth/logout',{method:'POST'});if(session.sitesSignIn)location.href='/signout-with-chatgpt?return_to=%2F';else{await loadSession();renderAccount()}},a);b.append(a)}
function requireLogin(){if(me)return true;renderAccount();app.openDialog(account.d.id);return false}
async function saveCloudSettings(){if(!requireLogin())return;await api('/api/settings',{method:'PUT',body:{settings:app.settingsSnapshot(),toolbar:window.toolbarOrder(),moments:await DraftStore.get('annotation.moments.v1')}});app.toast('设置已同步到账号')}
let settingsTimer;document.addEventListener('settings-changed47',()=>{if(me){clearTimeout(settingsTimer);settingsTimer=setTimeout(()=>saveCloudSettings().catch(report),900)}});$('saveSettings')?.addEventListener('click',()=>{if(me)saveCloudSettings().catch(report)});
function workCard(w){const b=E('button',{class:'communityCard47'}),im=E('img',{src:'/api/media/'+w.id,alt:w.title,loading:'lazy'});b.append(im,E('strong',{},w.title),E('small',{},w.author+' · '+(w.likes||0)+' 赞'));b.onclick=run(()=>openWork(w.id));return b}
async function loadGallery(){grid.replaceChildren();try{const d=await api('/api/works');if(!d.works.length)grid.append(E('p',{class:'notice47'},'第一幅公开亲笔，等你写下。'));for(const w of d.works)grid.append(workCard(w));const featured=d.works.filter(w=>w.featured);installFeatured(featured)}catch(e){grid.append(E('p',{class:'notice47'},'在线作品暂不可用，本机书写不受影响。'))}}
let featuredArea=null;function installFeatured(works){featuredArea?.remove();if(!works.length)return;featuredArea=E('section',{class:'featured47'});featuredArea.append(E('h3',{},'书仙推荐'));const row=E('div',{class:'communityGrid47'});row.style.cssText='display:flex;overflow-x:auto;scroll-snap-type:x mandatory';for(const w of works){const card=workCard(w);card.style.cssText='min-width:240px;scroll-snap-align:start';row.append(card)}featuredArea.append(row);gallery.before(featuredArea)}
const workView=dialog('workDialog47','亲笔作品');async function openWork(id){const d=await api('/api/works/'+id);activeWork=d.work;const b=workView.b;b.replaceChildren();b.append(E('img',{id:'workImage47',src:d.work.image,alt:d.work.title}),E('h3',{},d.work.title),E('p',{class:'notice47'},d.work.author+' · '+d.likes+' 赞'));const actions=E('div',{class:'actions47'});action('点赞',async()=>{if(!requireLogin())return;await api('/api/works/'+id+'/like',{method:'POST',body:{liked:true}});await openWork(id)},actions);action('取消赞',async()=>{if(!requireLogin())return;await api('/api/works/'+id+'/like',{method:'POST',body:{liked:false}});await openWork(id)},actions);action('分享／保存贴图',()=>shareWork(d.work),actions);if(d.work.allow_copy)action('一键临摹',()=>copyWork(d.work),actions,true);if(me?.id===d.work.owner){action('再次编辑',async()=>{const draft=await api('/api/works/'+id+'/draft');await app.restoreDraft(draft);workView.d.close();app.showWriter()},actions);action(d.work.visibility==='public'?'设为私密':'公开到首页',async()=>{await api('/api/works/'+id,{method:'PATCH',body:{visibility:d.work.visibility==='public'?'private':'public'}});await openWork(id);loadGallery()},actions);action('删除云端作品',async()=>{if(confirm('删除这幅云端作品及其点评？本机副本保留。')){await api('/api/works/'+id,{method:'DELETE'});workView.d.close();loadGallery()}},actions)}if(me?.role==='founder')action(d.work.featured?'取消推荐':'推荐到首页',async()=>{await api('/api/admin/feature',{method:'POST',body:{id,featured:!d.work.featured}});loadGallery();await openWork(id)},actions);b.append(actions);
if(d.work.visibility==='public'){const input=E('textarea',{placeholder:'写下你的点评',maxlength:'1000','aria-label':'作品点评'});b.append(input);action('发表点评',async()=>{if(!requireLogin())return;await api('/api/works/'+id+'/comments',{method:'POST',body:{body:input.value}});await openWork(id)},b)}const comments=E('div',{class:'comments47'});for(const c of d.comments)comments.append(E('p',{},c.author+'：'+c.body));b.append(comments);const series=await api('/api/works/'+id+'/series');if(series.works.length>1){b.append(E('h3',{},'原作与临摹系列'));const g=E('div',{class:'communityGrid47'});for(const w of series.works)if(w.id!==id)g.append(workCard(w));b.append(g)}app.openDialog(workView.d.id)}
async function shareWork(w){const url=location.origin+'/?work='+w.id,r=await fetch(w.image||'/api/media/'+w.id);if(!r.ok)throw Error('图片暂不可用');const blob=await r.blob(),file=new File([blob],w.title+'.png',{type:'image/png'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:w.title,text:'今日亲笔 · 亲笔手书，见墨如我',url});return}catch(e){if(e.name==='AbortError')return}}const a=E('a',{href:URL.createObjectURL(blob),download:w.title+'.png'});a.click();setTimeout(()=>URL.revokeObjectURL(a.href),60000);app.toast('图片已交给浏览器下载，可在微信／小红书选择这张贴图分享')}
async function copyWork(w){if(app.hasInk()&&!confirm('已写内容会先保存在本机，然后开始临摹，继续？'))return;if(app.hasInk())await app.savePage();const r=await fetch(w.image||'/api/media/'+w.id);if(!r.ok)throw Error('原作加载失败');parentWork=window.parentWork47=w.id;workView.d.close();await startReference([new File([await r.blob()],w.title+'.png',{type:'image/png'})]);}
const mine=dialog('cloudWorks47','我的云端作品');async function showMine(){const d=await api('/api/works?mine=1');mine.b.replaceChildren();if(!d.works.length)mine.b.append(E('p',{},'尚无云端作品。写完后点击“同步到我的账号”。'));for(const w of d.works)mine.b.append(workCard(w));app.openDialog(mine.d.id)}
async function syncWork(record,makePublic=false){if(!requireLogin())return;if(publishBusy)return;publishBusy=true;try{let id=record.cloudId||await DraftStore.get('cloud47:'+me.id+':'+record.id);if(!id){id=(await api('/api/works',{method:'POST',body:{title:record.title,parent:record.draft?.parentWork||null}})).id;await DraftStore.set('cloud47:'+me.id+':'+record.id,id)}await api('/api/works/'+id+'/image',{method:'PUT',headers:{'content-type':'image/png'},body:record.blob});if(record.draft)await api('/api/works/'+id+'/draft',{method:'PUT',body:record.draft});if(makePublic)await api('/api/works/'+id,{method:'PATCH',body:{visibility:'public'}});app.toast(makePublic?'作品已公开，可分享与点评':'作品已同步到账号');loadGallery();return id}finally{publishBusy=false}}
const localActions=E('div',{class:'actions47'});action('同步本机作品到账号',async()=>{if(!requireLogin())return;const list=await DraftStore.get('works-index')||[];if(!list.length)throw Error('还没有本机作品');const picker=dialog('syncPick47','选择要同步的作品');for(const meta of list){const row=E('div',{class:'actions47'});row.append(E('span',{},meta.title));action('私密同步',async()=>syncWork(await DraftStore.get(meta.id)),row);action('公开展示',async()=>syncWork(await DraftStore.get(meta.id),true),row);picker.b.append(row)}app.openDialog(picker.d.id)},localActions);action('云端作品',async()=>{if(requireLogin())await showMine()},localActions);$('worksDialog').querySelector('.dialogBody').prepend(localActions);
document.addEventListener('work-archived',async e=>{if(me){try{await syncWork(await DraftStore.get(e.detail.id))}catch(err){app.toast('本机已保存，云端同步未完成：'+err.message)}}});
// Inking activity: only active writing plus short inter-stroke gaps; no time while browsing or idle.
let activity={id:crypto.randomUUID(),day:new Date().toLocaleDateString('sv-SE'),seconds:0,characters:0,strokes:0},lastStroke=0,lastBox=null,activityTimer;
document.addEventListener('ink-stroke',e=>{if(!me)return;const p=e.detail.points;if(!p.length)return;const duration=Math.max(.05,(p.at(-1).t-p[0].t)/1000),now=Date.now(),xs=p.map(p=>p.x),ys=p.map(p=>p.y),box={x:(Math.min(...xs)+Math.max(...xs))/2,y:(Math.min(...ys)+Math.max(...ys))/2};activity.seconds+=duration+(lastStroke?Math.min(2,Math.max(0,(now-lastStroke)/1000-duration)):0);activity.strokes++;if(!lastBox||Math.hypot(box.x-lastBox.x,box.y-lastBox.y)>.32){activity.characters++;lastBox=box}lastStroke=now;clearTimeout(activityTimer);activityTimer=setTimeout(flushActivity,12000)});
async function flushActivity(){if(!me||!activity.strokes)return;const batch={...activity,seconds:Math.round(activity.seconds)};activity={id:crypto.randomUUID(),day:new Date().toLocaleDateString('sv-SE'),seconds:0,characters:0,strokes:0};try{await api('/api/stats',{method:'POST',body:batch,keepalive:true})}catch{await DraftStore.set('activity47:'+me.id+':'+batch.id,batch)}}document.addEventListener('visibilitychange',()=>{if(document.hidden)flushActivity()});
// Founder CMS: plain text and bounded layout styles, never executable HTML or CSS.
const admin=dialog('admin47','书仙管理');async function openAdmin(){if(me?.role!=='founder')throw Error('仅书仙可管理网站');const b=admin.b;b.replaceChildren();const tools=E('div',{class:'actions47'});action('现场编辑文字与布局',()=>{admin.d.close();startCMS()},tools);action('用户授权',manageUsers,tools);action('模板与临帖管理',manageTemplates,tools);action('附近历史记录',managePlaces,tools);b.append(tools,E('p',{class:'notice47'},'编辑后点击“发布修改”，所有访客将看到更新。个人工具栏设置仍属于各自账号。'));app.openDialog(admin.d.id)}
async function manageUsers(){const d=await api('/api/admin/users');admin.b.replaceChildren();for(const u of d.users){const row=E('div',{class:'actions47'});row.append(E('span',{},u.name+' · '+({founder:'书仙',saint:'书圣',member:'书家'}[u.role])));if(u.role!=='founder')action(u.role==='saint'?'设为书家':'升级书圣',async()=>{await api('/api/admin/users',{method:'PATCH',body:{id:u.id,role:u.role==='saint'?'member':'saint'}});await manageUsers()},row);admin.b.append(row)}}
let cmsPanel=null,cmsSelected=null,cmsDraft=null;const editable=new Map();function registerCMS(){const nodes=document.querySelectorAll('#annotationHome h1,#annotationHome h2,#annotationHome h3,#annotationHome p,#annotationHome .annotationIntro,#annotationHome footer span,#annotationHome button,#annotationHome .annotationGallery,#annotationHome #homeQuick47,#annotationHome #annotationCategories,dialog h2,dialog h3,dialog .note,dialog label,dialog button,#hintMessage,#hint small');let idx=0;for(const e of nodes){if(e.closest('#cmsPanel47')||e.id==='account47'||e.closest('#community47')||e.closest('#admin47')||e.closest('#accountDialog47'))continue;const root=e.closest('dialog')?.id||'home',key=e.id||root+'-'+e.tagName.toLowerCase()+'-'+idx++;e.dataset.cms47=key;editable.set(key,e)}}
function applyContent(content){for(const[key,data]of Object.entries(content.elements||{})){const e=editable.get(key);if(!e)continue;if(data.text!==undefined){const nodes=[...e.childNodes].filter(n=>n.nodeType===3);if(nodes.length){nodes[0].textContent=String(data.text);for(const n of nodes.slice(1))n.textContent=''}else if(!e.children.length)e.textContent=String(data.text)}e.hidden=!!data.hidden;for(const[k,min,max,unit]of [['fontSize',10,72,'px'],['width',10,100,'%'],['minHeight',0,800,'px'],['order',-100,100,'']])if(data[k]!==undefined)e.style[k]=Math.max(min,Math.min(max,+data[k]||min))+unit;if(/^#[a-f0-9]{6}$/i.test(data.color||''))e.style.color=data.color}
for(const item of AnnotationTemplates.items){const meta=content.scenes?.[item.key];if(meta?.title)item.title=meta.title;if(meta?.category)item.category=meta.category}
const categories=$('annotationCategories');[...categories.children].forEach((b,i)=>{const item=AnnotationTemplates.items.filter(x=>!content.scenes?.[x.key]?.hidden)[i];if(item)b.textContent=item.category})}
function startCMS(){if(me?.role!=='founder')throw Error('仅书仙可编辑');registerCMS();cmsDraft=structuredClone(site.content);document.body.classList.add('editMode47');cmsPanel?.remove();cmsPanel=E('aside',{id:'cmsPanel47'});cmsPanel.append(E('strong',{},'点击要编辑的文字或模块'));const actions=E('div',{class:'actions47'});action('发布修改',async()=>{const r=await api('/api/admin/site',{method:'PUT',body:{content:cmsDraft,revision:site.revision}});site={...site,content:cmsDraft,revision:r.revision};stopCMS();app.toast('页面内容已发布')},actions);action('放弃',()=>{stopCMS();location.reload()},actions);action('恢复隐藏模块',()=>{for(const d of Object.values(cmsDraft.elements||{}))d.hidden=false;applyContent(cmsDraft)},actions);cmsPanel.append(actions);document.body.append(cmsPanel);for(const e of editable.values()){e.draggable=true;e.ondragstart=ev=>{ev.dataTransfer.setData('text/plain',e.dataset.cms47)};e.ondragover=ev=>{if(document.body.classList.contains('editMode47'))ev.preventDefault()};e.ondrop=ev=>{if(!cmsDraft)return;ev.preventDefault();ev.stopPropagation();const id=ev.dataTransfer.getData('text/plain'),source=editable.get(id);if(source?.parentElement===e.parentElement){const siblings=[...e.parentElement.children];siblings.splice(siblings.indexOf(source),1);siblings.splice(siblings.indexOf(e),0,source);siblings.forEach((n,i)=>{if(n.dataset.cms47){cmsDraft.elements||={};cmsDraft.elements[n.dataset.cms47]={...cmsDraft.elements[n.dataset.cms47],order:i};n.style.order=i}})}}}}
function stopCMS(){document.body.classList.remove('editMode47');cmsPanel?.remove();cmsPanel=null;cmsDraft=null;cmsSelected?.classList.remove('editing47');for(const e of editable.values()){e.draggable=false;e.ondragstart=e.ondragover=e.ondrop=null}}
document.addEventListener('click',e=>{if(!cmsDraft||e.target.closest('#cmsPanel47'))return;const el=e.target.closest('[data-cms47]');if(!el)return;e.preventDefault();e.stopImmediatePropagation();cmsSelected?.classList.remove('editing47');cmsSelected=el;el.classList.add('editing47');cmsPanel.querySelector('.cmsFields47')?.remove();const fields=E('div',{class:'cmsFields47'}),key=el.dataset.cms47;cmsDraft.elements||={};const d=cmsDraft.elements[key]||={};const canText=[...el.childNodes].some(n=>n.nodeType===3&&n.textContent.trim())||!el.children.length;for(const[prop,label,type,value]of [['text','文字内容','textarea',d.text??[...el.childNodes].filter(n=>n.nodeType===3).map(n=>n.textContent).join('')],['fontSize','字号','number',d.fontSize||parseFloat(getComputedStyle(el).fontSize)],['color','颜色','color',d.color||'#293a33'],['width','宽度 %','number',d.width||100],['minHeight','最小高度','number',d.minHeight||0]]){if(prop==='text'&&!canText)continue;const l=E('label',{},label),input=E(type==='textarea'?'textarea':'input',type==='textarea'?{}:{type});input.value=value;input.oninput=()=>{d[prop]=type==='number'?+input.value:input.value;applyContent(cmsDraft)};l.append(input);fields.append(l)}action('删除此模块',()=>{d.hidden=true;applyContent(cmsDraft)},fields);cmsPanel.append(fields)},true);
async function manageTemplates(){admin.b.replaceChildren();const existing=await api('/api/admin/templates');const list=E('section');for(const item of AnnotationTemplates.items){const row=E('div',{class:'adminTemplate47'}),title=E('input',{value:site.content.scenes?.[item.key]?.title||item.title}),pos=E('input',{type:'number',value:String(site.content.scenes?.[item.key]?.position??AnnotationTemplates.items.indexOf(item)),min:'0'}),visible=E('input',{type:'checkbox','aria-label':'显示模板'});visible.checked=!site.content.scenes?.[item.key]?.hidden;row.append(title,pos,visible);list.append(row);const save=()=>{site.content.scenes||={};site.content.scenes[item.key]={...site.content.scenes[item.key],title:title.value,position:+pos.value,hidden:!visible.checked}};title.onchange=pos.onchange=visible.onchange=save}admin.b.append(E('h3',{},'首页模板：标题／顺序／显示'),list);action('保存模板编排',async()=>{const r=await api('/api/admin/site',{method:'PUT',body:{content:site.content,revision:site.revision}});site.revision=r.revision;applySceneOrder();applyContent(site.content);app.toast('模板编排已保存')},admin.b);
admin.b.append(E('h3',{},'上传临帖：整图或多张切割图'));const title=E('input',{placeholder:'临帖标题'}),files=E('input',{type:'file',accept:'image/png,image/jpeg,image/webp',multiple:''}),cols=E('input',{type:'number',min:'1',max:'30',value:'6'}),rows=E('input',{type:'number',min:'1',max:'30',value:'10'}),dir=E('select');dir.append(E('option',{value:'vertical'},'右起竖写'),E('option',{value:'horizontal'},'左起横写'));for(const[label,input]of [['标题',title],['原帖图片',files],['列数',cols],['行数',rows],['方向',dir]]){const l=E('label',{},label);l.append(input);admin.b.append(l)}action('上传并发布临帖',async()=>{if(!files.files.length)throw Error('请先选择原帖');if(files.files.length>60)throw Error('每组最多60张');const pages=[];for(const f of files.files)pages.push((await api('/api/admin/upload',{method:'POST',headers:{'content-type':f.type},body:f})).url);await api('/api/admin/templates',{method:'PUT',body:{title:title.value||'书法原帖',kind:'copybook',config:{pages,columns:+cols.value,rows:+rows.value,direction:dir.value,zoom:300,size:18}}});site=await api('/api/site');await manageTemplates()},admin.b);
for(const t of existing.templates.filter(t=>t.kind==='copybook')){const row=E('div',{class:'actions47'});row.append(E('span',{},t.title));action('试临',()=>useCopybook(t),row);action('编辑参数',()=>editCopybook(t),row);action(t.hidden?'重新上架':'下架',async()=>{await api('/api/admin/templates',{method:'PUT',body:{...t,hidden:!t.hidden}});await manageTemplates()},row);admin.b.append(row)}}
async function editCopybook(template){const d=dialog('editCopybook47','原帖参数'),config=structuredClone(template.config),fields={};for(const[key,label,type,value]of [['title','标题','text',template.title],['columns','列数','number',config.columns||6],['rows','行数','number',config.rows||10],['zoom','缩放 %','number',config.zoom||300],['size','笔径','number',config.size||18],['inkOpacity','墨迹不透明度 0—1','number',config.inkOpacity??.5],['position','展示顺序','number',template.position||0]]){const l=E('label',{},label),input=E('input',{type,value:String(value)});fields[key]=input;l.append(input);d.b.append(l)}const pages=E('div');function render(){pages.replaceChildren();config.pages.forEach((src,i)=>{const row=E('div',{class:'actions47'});row.append(E('span',{},'第 '+(i+1)+' 张'));if(i)action('上移',()=>{[config.pages[i-1],config.pages[i]]=[config.pages[i],config.pages[i-1]];render()},row);action('移除此页',()=>{if(config.pages.length<2)throw Error('至少保留一张原帖');config.pages.splice(i,1);render()},row);pages.append(row)})}render();d.b.append(pages);action('保存参数',async()=>{for(const k of ['columns','rows','zoom','size','inkOpacity'])config[k]=+fields[k].value;await api('/api/admin/templates',{method:'PUT',body:{...template,title:fields.title.value,position:+fields.position.value,config}});site=await api('/api/site');d.d.close();app.openDialog(admin.d.id);await manageTemplates()},d.b);app.openDialog(d.d.id)}
function applySceneOrder(){const items=AnnotationTemplates.items;const original=new Map(items.map((x,i)=>[x.key,i]));items.sort((a,b)=>(site.content.scenes?.[a.key]?.position??original.get(a.key))-(site.content.scenes?.[b.key]?.position??original.get(b.key)));AnnotationHome.reorder47?.(site.content.scenes||{})}
async function managePlaces(){admin.b.replaceChildren();admin.b.append(E('p',{class:'notice47'},'每条记录填写经纬度、年份、历史说明和来源网址。用户允许定位后，只显示10公里内有来源的记录。'));const fields={};for(const[key,label,type]of [['title','地点名','text'],['lat','纬度','number'],['lon','经度','number'],['year','年份','number'],['story','史实说明','text'],['source','来源网址','url']]){const l=E('label',{},label),i=E('input',{type});fields[key]=i;l.append(i);admin.b.append(l)}action('保存历史记录',async()=>{const record=Object.fromEntries(Object.entries(fields).map(([k,e])=>[k,e.value]));if(!record.title||!record.story||!/^https:\/\//.test(record.source))throw Error('请补齐地点、史实和可信来源');site.content.places||=[];site.content.places.push(record);const r=await api('/api/admin/site',{method:'PUT',body:{content:site.content,revision:site.revision}});site.revision=r.revision;await managePlaces()},admin.b);for(const p of site.content.places||[])admin.b.append(E('p',{},p.title+' · '+p.year+' · '+p.story))}
// Reference import has explicit row/column correction; image-based suggestions never pretend to be OCR.
let referenceConfig=null;async function startReference(files,config={}){referenceConfig=config;const transfer=new DataTransfer();for(const f of files)transfer.items.add(f);$('upload').files=transfer.files;$('upload').dispatchEvent(new Event('change'));app.showWriter()}
async function useCopybook(t){const files=[];for(const[src,i]of t.config.pages.map((x,i)=>[x,i])){const r=await fetch(src);if(!r.ok)throw Error('原帖加载失败');files.push(new File([await r.blob()],t.title+'-'+i+'.png',{type:r.headers.get('content-type')||'image/png'}))}admin.d.close();await startReference(files,t.config)}
const refTools=E('div',{class:'actions47'});action('在线原帖库',async()=>{const d=dialog('copyLibrary47','在线原帖');const books=site.templates.filter(t=>t.kind==='copybook');if(!books.length)d.b.append(E('p',{},'暂无公开原帖。书仙可在网站管理中上传，或直接上传本机图片。'));for(const t of books)action(t.title,async()=>{d.d.close();await useCopybook(t)},d.b);app.openDialog(d.d.id)},refTools);$('copyDialog').querySelector('.dialogBody').prepend(refTools);
document.addEventListener('writing-scenario47',()=>{parentWork=window.parentWork47=null});
document.addEventListener('reference-loaded47',async e=>{try{const im=e.detail.image;await app.reference47(im,referenceConfig||{});const segments=window.Reference47?.detect(im);if(segments?.length){const first=segments[0];app.focusPoint47(first.x*4,first.y*4*im.height/im.width)}referenceConfig=null;app.toast('已按原帖尺寸定位右上起笔；行列可在设置中校正，四向按钮逐字移动')}catch(err){report(err)}});
// Location is requested at the start of writing only after the user opts in; browser permission always applies.
const locButton=E('button',{id:'nearby47'},'附近历史落款');locButton.onclick=run(locateHistory);$('statusDetails42').append(locButton);Revision47.registerTool('nearbyQuick47','附近历史落款','<path d="M12 22s8-9 8-14a8 8 0 0 0-16 0c0 5 8 14 8 14Z"/><circle cx="12" cy="8" r="3"/>',locateHistory);
let askedLocation=false;const showWriter=app.showWriter;app.showWriter=()=>{showWriter();if(!askedLocation&&session&&localStorage.getItem('ink.nearby.enabled')!=='0'){askedLocation=true;locateHistory(true).catch(()=>{})}};
async function locateHistory(quiet=false){if(!navigator.geolocation)throw Error('此浏览器不支持定位');const pos=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,()=>reject(Error('未取得定位权限，可稍后重试')),{enableHighAccuracy:false,timeout:10000,maximumAge:300000}));localStorage.setItem('ink.nearby.enabled','1');const d=await api('/api/nearby?lat='+pos.coords.latitude.toFixed(3)+'&lon='+pos.coords.longitude.toFixed(3));if(quiet){if(d.events.length)app.toast('附近有 '+d.events.length+' 条历史落款，点附近历史按钮查看');return}const panel=dialog('nearbyDialog47','你到来之前');if(!d.events.length)panel.b.append(E('p',{},'附近10公里暂无已核实的历史记录。可以先写下今天的时间与感受。'));for(const event of d.events){const age=new Date().getFullYear()-Number(event.year),line=event.title+' · 在你来之前'+age+'年，'+event.story;panel.b.append(E('p',{class:'positionNote47'},line),E('a',{href:event.source,target:'_blank',rel:'noopener'},'查看来源'));action('用作落款参考',()=>{app.setGuide(line,'历史落款');panel.d.close();app.showWriter()},panel.b)}app.openDialog(panel.d.id)}
// Optional branded export with a real, public work permalink QR, outside the artwork.
async function branded(w){if(w.visibility!=='public')throw Error('请先公开作品，二维码才能供他人打开');const im=new Image();im.src=w.image;await im.decode();const c=document.createElement('canvas'),h=160;c.width=im.width;c.height=im.height+h;const t=c.getContext('2d');t.fillStyle='#f5f1e7';t.fillRect(0,0,c.width,c.height);t.drawImage(im,0,0);const factor=c.width/1000;t.fillStyle='#344338';t.font=Math.max(16,26*factor)+'px serif';t.fillText('今日亲笔',28,im.height+48);t.font=Math.max(12,16*factor)+'px sans-serif';t.fillText('亲笔手书，见墨如我 · iinnkk.me',28,im.height+86);t.drawImage($('appLogo'),Math.max(25,c.width-240),im.height+24,72,72);const qr=document.createElement('canvas');await InkQR47.toCanvas(qr,location.origin+'/?work='+w.id,{width:112,margin:1});t.drawImage(qr,c.width-132,im.height+20,112,112);const blob=await new Promise(r=>c.toBlob(r,'image/png'));const a=E('a',{href:URL.createObjectURL(blob),download:w.title+'-分享.png'});a.click();setTimeout(()=>URL.revokeObjectURL(a.href),60000)}
// No login or membership gate for local creative tools.
const originalOpen=openWork;openWork=async id=>{await originalOpen(id);action('保存带署名与二维码的装裱图',()=>branded(activeWork),workView.b)};
try{await loadSession();site=await api('/api/site');registerCMS();applySceneOrder();applyContent(site.content);if(me&&new URLSearchParams(location.search).has('signedIn'))renderAccount();if(me?.role==='founder')Revision47.registerTool('adminQuick47','书仙网站管理','<path d="m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6Z"/><path d="M8 12h8M12 8v8"/>',openAdmin)}catch(e){console.info('Online account service unavailable; local writing preserved')}
await loadGallery();const shared=new URLSearchParams(location.search).get('work');if(shared)openWork(shared).catch(report);
window.Community47={ready:true,api,openAdmin,openWork,saveCloudSettings,startReference,get user(){return me},get site(){return site}};
})();
