/* Boot compatibility for older iPad WebKit; runs before every application module. */
(function(){
 const at=function(index){const o=Object(this),n=o.length>>>0;let k=Math.trunc(Number(index)||0);if(k<0)k+=n;return k<0||k>=n?undefined:o[k]};
 for(const proto of [Array.prototype,String.prototype,Object.getPrototypeOf(Uint8Array.prototype)])if(!proto.at)Object.defineProperty(proto,'at',{value:at,configurable:true,writable:true});
 if(!Object.hasOwn)Object.hasOwn=(o,key)=>Object.prototype.hasOwnProperty.call(o,key);
 if(!globalThis.structuredClone)globalThis.structuredClone=function(value){const seen=new Map();function copy(v){if(v===null||typeof v!=='object')return v;if(seen.has(v))return seen.get(v);if(v instanceof Blob)return v.slice(0,v.size,v.type);if(v instanceof Date)return new Date(v);if(v instanceof ArrayBuffer)return v.slice(0);if(ArrayBuffer.isView(v))return v instanceof DataView?new DataView(v.buffer.slice(0),v.byteOffset,v.byteLength):new v.constructor(v);const out=Array.isArray(v)?[]:v instanceof Map?new Map():v instanceof Set?new Set():{};seen.set(v,out);if(v instanceof Map)for(const[k,x]of v)out.set(copy(k),copy(x));else if(v instanceof Set)for(const x of v)out.add(copy(x));else for(const k of Object.keys(v))out[k]=copy(v[k]);return out}return copy(value)};
 if(!Intl.DisplayNames){const regions={"AF":"阿富汗","AL":"阿尔巴尼亚","MK":"北马其顿","ES":"西班牙","IT":"意大利","FR":"法国","PL":"波兰","AT":"奥地利","BE":"比利时","HR":"克罗地亚","RO":"罗马尼亚","UA":"乌克兰","BG":"保加利亚","SI":"斯洛文尼亚","SK":"斯洛伐克","CH":"瑞士","BA":"波斯尼亚和黑塞哥维那","DE":"德国","CZ":"捷克","DZ":"阿尔及利亚","AD":"安道尔","AR":"阿根廷","BR":"巴西","AU":"澳大利亚","AZ":"阿塞拜疆","IR":"伊朗","BY":"白俄罗斯","BJ":"贝宁","BO":"玻利维亚","BW":"博茨瓦纳","KH":"柬埔寨","TD":"乍得","CA":"加拿大","CM":"喀麦隆","US":"美国","CL":"智利","CN":"中国","CO":"哥伦比亚","CG":"刚果（布）","CR":"哥斯达黎加","PA":"巴拿马","CI":"科特迪瓦","CU":"古巴","ME":"黑山","CY":"塞浦路斯","CD":"刚果（金）","DK":"丹麦","DM":"多米尼克","NL":"荷兰","EC":"厄瓜多尔","EG":"埃及","EE":"爱沙尼亚","ET":"埃塞俄比亚","GA":"加蓬","FJ":"斐济","FI":"芬兰","GE":"格鲁吉亚","GH":"加纳","GR":"希腊","GT":"危地马拉","VA":"梵蒂冈","HU":"匈牙利","IS":"冰岛","IN":"印度","ID":"印度尼西亚","IQ":"伊拉克","IE":"爱尔兰","IL":"以色列","JP":"日本","JM":"牙买加","JO":"约旦","MN":"蒙古","KZ":"哈萨克斯坦","KI":"基里巴斯","KE":"肯尼亚","LA":"老挝","LB":"黎巴嫩","LS":"莱索托","ZA":"南非","LY":"利比亚","MG":"马达加斯加","LT":"立陶宛","MW":"马拉维","MY":"马来西亚","ML":"马里","MT":"马耳他","MH":"马绍尔群岛","MU":"毛里求斯","MX":"墨西哥","RU":"俄罗斯","MA":"摩洛哥","NP":"尼泊尔","NO":"挪威","OM":"阿曼","PE":"秘鲁","PH":"菲律宾","PT":"葡萄牙","KR":"韩国","KN":"圣基茨和尼维斯","SA":"沙特阿拉伯","SN":"塞内加尔","RS":"塞尔维亚","SC":"塞舌尔","SL":"塞拉利昂","SG":"新加坡","SB":"所罗门群岛","LK":"斯里兰卡","PS":"巴勒斯坦领土","SR":"苏里南","SE":"瑞典","SY":"叙利亚","TJ":"塔吉克斯坦","UZ":"乌兹别克斯坦","TM":"土库曼斯坦","TH":"泰国","TN":"突尼斯","TR":"土耳其","AE":"阿拉伯联合酋长国","GB":"英国","TZ":"坦桑尼亚","VE":"委内瑞拉","VN":"越南","YE":"也门","ZW":"津巴布韦","AO":"安哥拉","AM":"亚美尼亚","BH":"巴林","BD":"孟加拉国","TG":"多哥","CV":"佛得角","KP":"朝鲜","DO":"多米尼加共和国","GM":"冈比亚","HT":"海地","HN":"洪都拉斯","KG":"吉尔吉斯斯坦","LV":"拉脱维亚","MR":"毛里塔尼亚","NA":"纳米比亚","NZ":"新西兰","NI":"尼加拉瓜","NG":"尼日利亚","PK":"巴基斯坦","PY":"巴拉圭","QA":"卡塔尔","SM":"圣马力诺","SS":"南苏丹","SD":"苏丹","UG":"乌干达","VU":"瓦努阿图","UY":"乌拉圭","ZM":"赞比亚","AG":"安提瓜和巴布达","BB":"巴巴多斯","MD":"摩尔多瓦","BZ":"伯利兹","NE":"尼日尔","BF":"布基纳法索","CF":"中非共和国","KM":"科摩罗","GN":"几内亚","SV":"萨尔瓦多","ER":"厄立特里亚","GW":"几内亚比绍","LU":"卢森堡","FM":"密克罗尼西亚","MZ":"莫桑比克","MM":"缅甸","PW":"帕劳","PG":"巴布亚新几内亚","RW":"卢旺达","LC":"圣卢西亚","ST":"圣多美和普林西比"};Intl.DisplayNames=function(){this.of=code=>regions[code]||code}}
 if(!crypto.randomUUID)crypto.randomUUID=()=>{const a=crypto.getRandomValues(new Uint8Array(16));a[6]=(a[6]&15)|64;a[8]=(a[8]&63)|128;const h=[...a].map(n=>n.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20)};
 const proto=globalThis.HTMLDialogElement?.prototype||HTMLElement.prototype;
 if(!proto.showModal){if(!('open'in proto))Object.defineProperty(proto,'open',{configurable:true,get(){return this.hasAttribute('open')},set(v){this.toggleAttribute('open',!!v)}});proto.showModal=function(){this.setAttribute('open','');this.classList.add('fallbackDialog106');this.setAttribute('role','dialog');this.setAttribute('aria-modal','true')};proto.show=proto.showModal;proto.close=function(){this.removeAttribute('open');this.dispatchEvent(new Event('close'))};document.addEventListener('keydown',e=>{if(e.key==='Escape'){const open=document.querySelectorAll('dialog[open]');open[open.length-1]?.close()}})}
})();
