(function(root){
const templates={};
const inspirations={kusun:{name:'怀素 · 苦笋帖',text:'苦笋及茗异常佳，乃可迳来。怀素上。',source:'怀素《苦笋帖》· 古帖释文',url:'https://www.shanghaimuseum.net/mu/frontend/pg/article/id/P00002749'},duck:{name:'王献之 · 鸭头丸帖',text:'鸭头丸，故不佳。明当必集，当与君相见。',source:'王献之《鸭头丸帖》· 古帖释文',url:'https://www.shanghaimuseum.net/mu/frontend/pg/m/article/id/CI00000376'},autumn:{name:'传王献之 · 中秋帖',text:'中秋不复不得相还，为即甚省如何，然胜人何庆等大军。',source:'传王献之《中秋帖》· 传世本释文',url:'https://www.dpm.org.cn'},stomach:{name:'张旭 · 肚痛帖',text:'忽肚痛不可堪，不知是冷热所致。水服大黄汤，冷热俱有益。',source:'张旭《肚痛帖》· 古帖释文，仅作临写',url:'https://digitalarchive.npm.gov.tw/Collection/Detail/28115?dep=P'}};
const scenes=root.LegacyCreativePaper.scenes,museumImages=[],pendingImages=new Map();
let exhibition=null,materials=null;
function load(src,done){const im=new Image();im.onload=()=>{done(im);root.CreativePaper.onReady?.()};im.onerror=()=>{root.CreativePaper.onError?.(src)};im.src=src}
function crop(t,im,i,w,h,rows){const col=i%3,row=Math.floor(i/3),sx=col*im.width/3,sy=rows[row]/1254*im.height,sh=(rows[row+1]-rows[row])/1254*im.height;t.drawImage(im,sx,sy,im.width/3,sh,0,0,w,h)}
function drawTemplate(t,b,p){if(p.art===undefined||!materials)return;crop(t,materials,p.art,b.w,b.h,[0,386,771,1254])}
const guideCache=new Map();
function drawGuide(t,a,text,vertical,alpha){if(!text||!alpha)return;const chars=[...text.replace(/\s/g,'')],key=JSON.stringify([text,a.w,a.h,vertical]);let sheet=guideCache.get(key);if(!sheet){sheet=document.createElement('canvas');const scale=Math.min(390,2000/Math.max(a.w,a.h));sheet.width=Math.max(1,Math.ceil(a.w*scale));sheet.height=Math.max(1,Math.ceil(a.h*scale));const g=sheet.getContext('2d'),cols=Math.max(1,Math.ceil(Math.sqrt(chars.length*a.w/a.h))),rows=Math.ceil(chars.length/cols),dx=sheet.width/cols,dy=sheet.height/rows,fs=Math.min(dx,dy)*.70;g.fillStyle='#56442f';g.textAlign='center';g.textBaseline='middle';g.font=fs+'px "Kaiti SC",STKaiti,serif';chars.forEach((ch,i)=>{const x=vertical?cols-1-Math.floor(i/rows):i%cols,y=vertical?i%rows:Math.floor(i/cols);g.fillText(ch,(x+.5)*dx,(y+.5)*dy)});if(guideCache.size>=3)guideCache.delete(guideCache.keys().next().value);guideCache.set(key,sheet)}t.save();t.globalAlpha=alpha;t.drawImage(sheet,a.x,a.y,a.w,a.h);t.restore()}

const rects=[[170,92,298,247],[550,109,701,247],[966,88,1107,262],[139,513,285,649],[492,449,686,598],[945,511,1119,634],[137,906,279,1042],null,[948,874,1142,1023]];
function scene(t,art,i,width,height){const meta=root.MuseumScenes.find(m=>m.key===i),im=museumImages[i];if(!meta||!im)throw Error('场景图片尚未加载');t.save();t.drawImage(im,0,0,width,height);const r=meta.slot,x=r[0]*width,y=r[1]*height,w=r[2]*width,h=r[3]*height,f=Math.min(w/art.width,h/art.height);t.drawImage(art,x+(w-art.width*f)/2,y+(h-art.height*f)/2,art.width*f,art.height*f);t.fillStyle='#171a17bf';t.fillRect(0,height*.92,width,height*.08);t.fillStyle='#fff6e4';t.font=Math.round(width*.019)+'px "PingFang SC",sans-serif';t.fillText(meta.name+'  ·  '+meta.people,width*.025,height*.953);t.fillStyle='#ddd1b9';t.font=Math.round(width*.011)+'px sans-serif';t.fillText('跨时空创意展陈 · 名作艺术化重绘 · 非真实同展',width*.025,height*.982);t.restore()}
function compose(target,art,key,size){if(!String(key).startsWith('museum:'))return root.LegacyCreativePaper.compose(target,art,key,size);target.width=size;target.height=Math.round(size*.75);scene(target.getContext('2d'),art,key.slice(7),size,target.height);return target}
function ready(key){return String(key).startsWith('museum:')?!!museumImages[key.slice(7)]:root.LegacyCreativePaper.ready(key)}
function ensure(key){if(!String(key).startsWith('museum:'))return root.LegacyCreativePaper.ensure(key);const i=key.slice(7),m=root.MuseumScenes.find(m=>m.key===i);if(!m)return Promise.reject(Error('模板已移除'));if(museumImages[i])return Promise.resolve();if(pendingImages.has(i))return pendingImages.get(i);const job=new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{museumImages[i]=im;pendingImages.delete(i);root.CreativePaper.onReady?.();resolve()};im.onerror=()=>{pendingImages.delete(i);reject(Error('场景未加载'))};im.src='museums/'+i+'.webp'});pendingImages.set(i,job);return job}
function release(key){if(String(key).startsWith('museum:'))delete museumImages[key.slice(7)];else root.LegacyCreativePaper.release(key)}
root.CreativePaper={templates,inspirations,scenes,drawTemplate:()=>{},drawGuide,compose,ready,ensure,release};root.LegacyCreativePaper.onReady=()=>root.CreativePaper.onReady?.();
})(globalThis);
