/* Seven light vector posters. No hidden images or facsimiles are decoded on startup. */
(function init(){if(!window.AnnotationHome||!window.Revision90?.ready&&!window.Revision88?.ready){setTimeout(init,100);return}
const A=AnnotationApp,$=id=>document.getElementById(id),E=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text)e.textContent=text;return e};
const slides=[
 {id:'daily-scene',k:'手笔 · 日常临帖',title:'每天一帖，\n给自己留点墨。',sub:'碎片时间也能练字。\n原帖浮窗相伴，今日进步留在文牒。',cta:'开始今天的临帖',ink:'#273f36',paper:'#eee7d5',accent:'#b14e36'},
 {id:'gift-scene',k:'手笔 · 节日赠礼',title:'祝福亲手写，\n心意有真迹。',sub:'生日、节日、毕业。\n写一张独一无二的亲笔祝福。',cta:'写一份亲笔心意',ink:'#583c34',paper:'#f1e0cf',accent:'#ad342b'},
 {id:'family-scene',k:'手笔 · 亲友共书',title:'你写一笔，\n我接一程。',sub:'家人练字、好友纪念。\n同一卷纸，收藏彼此的笔迹。',cta:'邀请亲友接力',ink:'#eee6cf',paper:'#32473e',accent:'#d5b072'},
 {id:'hello-world',n:'00',k:'亲笔 · 问好世界',title:'今日亲笔，\n问好世界！',sub:'以笔迹勾勒地球，以城市接续文明。\n从长安到伦敦、纽约和上海，一笔相逢。',cta:'亲笔向世界问好',ink:'#314b3e',paper:'#f1ecdf',accent:'#a44d36',glyph:'世'},
 {id:'civilization',n:'01',k:'文字 · 人类共同的长卷',title:'从世界各处，\n写向同一个人类。',sub:'甲骨、泥板、纸莎草与羊皮卷。\n不同文明留下不同笔迹，我们在这里相遇。',cta:'沿文明长卷漫游',ink:'#eae4cf',paper:'#273b42',accent:'#dbb47b',glyph:'文'},
 {id:'handwriting',n:'02',k:'亲笔 · 穿越千年的共鸣',title:'一笔落下，\n千年后仍有人懂。',sub:'书写，是文明、思想与表达最直觉的印记。\n纸上留下的，是一个人曾经鲜活的心跳。',cta:'留下今天的亲笔',ink:'#42382e',paper:'#eee3cc',accent:'#a44d35',glyph:'心'},
 {id:'constellation',n:'03',k:'今日亲笔 · 文字方舟',title:'人类群星闪耀时',sub:'一起结网记字，打造文字方舟！',cta:'加入这一卷星光',ink:'#eee9da',paper:'#29352f',accent:'#d6b779',glyph:'星'},
 {id:'reference',n:'01',k:'临帖浮窗',title:'古人的帖，\n就在你的笔边。',sub:'看原帖、翻组图、定位字格。\n浮窗相伴，让每一笔都有来处。',cta:'去临兰亭序',ink:'#243e38',paper:'#f0ead9',accent:'#c3603b',glyph:'永'},
 {id:'passport',n:'02',k:'我的书法通关文牒',title:'二十帖。\n把千年，亲笔走一遍。',sub:'古人原帖在左，你的临写在右。\n一站一印，认真写过的今天都会留下。',cta:'展开我的文牒',ink:'#faf0d6',paper:'#283e36',accent:'#d9ae67',glyph:'牒'},
 {id:'reader',n:'03',k:'文摘浮窗',title:'好文章，\n写一点就近一点。',sub:'全文就在笔边，边读边写。\n从前赤壁赋，写到你自己的江山。',cta:'亲笔写前赤壁赋',ink:'#3b414b',paper:'#e9edf0',accent:'#af533d',glyph:'赋'},
 {id:'relay',n:'04',k:'接力共书',title:'同一卷纸。\n不同时光的相逢。',sub:'朋友接力题跋，各自钤印。\n今天落笔，明天有人接续。',cta:'发起一卷墨缘',ink:'#442e28',paper:'#f1e1ce',accent:'#b23326',glyph:'缘'},
 {id:'expand',n:'05',k:'四向拓纸',title:'灵感还没写完？\n纸，跟你走。',sub:'预览三击显示拓纸箭头。\n点击或外拉加纸，向内收回。',cta:'试试四向拓纸',ink:'#e8e9df',paper:'#34464a',accent:'#d5a174',glyph:'展'},
 {id:'heritage',n:'06',k:'印 · 墨 · 纸',title:'把世界的颜色，\n写进自己的字。',sub:'印墨纸三色，取意世界遗产。\n读一段设计理念，写一张远方来信。',cta:'遇见一组世界遗产配色',ink:'#294943',paper:'#e3e8d9',accent:'#b36041',glyph:'境'},
 {id:'gestures',n:'07',k:'手势书写',title:'指尖一动。\n纸上有天地。',sub:'双击定位，三击拓纸，滑动换景。\n正文与题跋，也可以双指三击切换。',cta:'打开手势体验',ink:'#4b3847',paper:'#efe6ea',accent:'#a14b4b',glyph:'指'}
];
const culture=['hello-world','civilization','handwriting','constellation'];slides.sort((a,b)=>{const rank=s=>culture.includes(s.id)?culture.indexOf(s.id):s.id.endsWith('-scene')?4:5;return rank(a)-rank(b)});
const home=$('annotationHome'),hero=E('section','featureHero144'),viewport=E('div','featureViewport144'),nav=E('nav','featureNav144'),info=E('span','featureCount144');hero.id='featureHero144';hero.setAttribute('aria-label','新功能轮播');viewport.tabIndex=0;viewport.setAttribute('aria-roledescription','轮播');let index=0,paused=false,run=0;const panels=[];
for(const s of slides){const card=E('article','featureSlide144');card.dataset.slide146=s.id;card.setAttribute('aria-label',s.k+'：'+s.title.replace(/\n/g,''));card.style.setProperty('--f-ink',s.ink);card.style.setProperty('--f-paper',s.paper);card.style.setProperty('--f-accent',s.accent);const copy=E('div','featureCopy144'),label=E('small','featureKicker144','今日亲笔 / '+String(slides.indexOf(s)+1).padStart(2,'0')+' · '+s.k),title=E('h2','',s.title),desc=E('p','',s.sub),cta=E('button','featureCta144',s.cta+' ↗');cta.type='button';cta.onclick=async()=>{cta.disabled=true;try{await launch(s.id)}catch(e){A.toast(e.message)}finally{cta.disabled=false}};copy.append(label,title,desc,cta);const art=E('div','featureArt144');const image=E('img');image.src=(s.id.endsWith('-scene')?'banners149/':s.id==='hello-world'?'banners146/':['civilization','handwriting','constellation'].includes(s.id)?'banners145/':'banners144/')+s.id+'.svg';image.alt='';image.loading=slides.indexOf(s)===0?'eager':'lazy';image.decoding='async';art.append(image);card.append(copy,art);panels.push(card);viewport.append(card);const dot=E('button','featureDot144');dot.type='button';dot.title=dot.ariaLabel=s.k;dot.onclick=()=>{go(slides.indexOf(s));paused=true};nav.append(dot)}
const prev=E('button','','‹'),next=E('button','','›'),pause=E('button','','Ⅱ');prev.type=next.type=pause.type='button';prev.title=prev.ariaLabel='上一页';next.title=next.ariaLabel='下一页';pause.title=pause.ariaLabel='暂停轮播';prev.onclick=()=>{go(index-1);paused=true};next.onclick=()=>{go(index+1);paused=true};pause.onclick=()=>{paused=!paused;pause.textContent=paused?'▷':'Ⅱ';pause.title=pause.ariaLabel=paused?'播放轮播':'暂停轮播'};const controls=E('div','featureControls144');controls.append(prev,nav,info,pause,next);hero.append(viewport,controls);const quick=$('homeQuick47'),intro=home.querySelector('.annotationIntro');if(intro){intro.hidden=true;intro.after(hero)}else home.prepend(hero);if(quick)hero.before(quick);function go(i){index=(i+slides.length)%slides.length;viewport.scrollTo({left:index*viewport.clientWidth,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});for(const [j,p]of panels.entries()){p.inert=j!==index;p.querySelector('button').tabIndex=j===index?0:-1;nav.children[j].setAttribute('aria-current',String(j===index))}info.textContent=String(index+1).padStart(2,'0')+' / '+String(slides.length).padStart(2,'0')}go(0);viewport.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){go(index+1);paused=true}if(e.key==='ArrowLeft'){go(index-1);paused=true}});viewport.addEventListener('pointerdown',()=>paused=true,{passive:true});let scrollTimer;viewport.addEventListener('scroll',()=>{clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>{index=Math.round(viewport.scrollLeft/Math.max(1,viewport.clientWidth));for(const [j,p]of panels.entries()){p.inert=j!==index;p.querySelector('button').tabIndex=j===index?0:-1;nav.children[j].setAttribute('aria-current',String(j===index))}info.textContent=String(index+1).padStart(2,'0')+' / '+String(slides.length).padStart(2,'0')},100)},{passive:true});setInterval(()=>{if(!paused&&!document.hidden&&document.body.classList.contains('home-open')&&!hero.contains(document.activeElement)&&!matchMedia('(prefers-reduced-motion: reduce)').matches)go(index+1)},8000);addEventListener('resize',()=>go(index));
async function fresh(){await window.Revision128?.saveOnSwitch129?.();await CopyAlbums38.clear();const mode=InkStudio50.config.nav.find(m=>m.id==='letter');if(mode)await InkStudio50.applyMode(mode);await A.newBlank54();await A.configure47({values:{sceneChoice:'none',paperExtent:'fixed',ratio:'0.75',zoom:'200',showLines:'no'},size:40,focus:'start'});A.showWriter()}
async function launch(id){if(id==='daily-scene')id='reference';if(id==='gift-scene')id='handwriting';if(id==='family-scene')id='relay';if(id==='civilization'){document.getElementById('inkTimeline73')?.scrollIntoView({behavior:'smooth',block:'start'});return}if(id==='hello-world'||id==='constellation'||id==='handwriting'){await fresh();return}if(id==='passport'){await Passport144.open();return}if(id==='reference'){await TimelineCloud74.ready;const c=Timeline73.chapters.find(c=>c.id==='lanting')||Content133.linkedChapter143(Content133.canon[0]);if(!c)throw Error('兰亭序目录正在加载，请稍后重试');await Timeline73.openCopy(c);return}if(id==='relay'){await SharedInk128.open();return}await fresh();if(id==='reader'){const q=DailyQuotes38.all().find(q=>/前赤壁赋/.test(q.title||q.s||'')||(/赤壁赋/.test(q.title||q.s||'')&&!/后赤壁赋/.test(q.title||q.s||'')));if(!q)throw Error('前赤壁赋暂未加载，请从文摘目录选择');DailyQuotes38.selectId(q.id||q.s+'|'+q.q);$('readQuote').click();return}if(id==='heritage'){if(window.Revision94?.palette)Revision94.apply(Revision94.palette());else $('previewRandom79')?.click();A.toast('印、墨、纸来自同一段远方故事；在预览里读设计理念。')}if(!A.isOverview55())$('fitView').click();if(id==='expand'){if(window.PreviewPaper120&&document.getElementById('previewEdges120')?.hidden)PreviewPaper120.toggle();A.toast('预览三击纸面显示四向箭头；点击或外拉拓纸，向内收回。')}if(id==='gestures')gestureGuide()}
function gestureGuide(){let d=$('gestureGuide144');if(!d){d=E('dialog','gestureGuide144');d.id='gestureGuide144';const h=E('header','dialogHead'),x=E('button','','×');x.type='button';x.onclick=()=>d.close();h.append(E('h2','','指尖书写指南'),x);d.append(h);for(const [gesture,action]of [['预览 · 单指双击','定位到落点，进入书写'],['预览 · 单指三击','显示或隐藏四向拓纸箭头'],['预览 · 上滑','全屏并切换色彩'],['全屏 · 左右滑','切换装裱框架'],['全屏 · 下滑','退出全屏并展开配置'],['书写 · 双指拖动','移动纸张'],['双指三击','正文 ↔ 落款题跋'],['四击','切换格线'],['五击','清空当前书写区'],['六击','撤销上一步']]){const row=E('p');row.append(E('strong','',gesture),E('span','',action));d.append(row)}d.append(E('small','','清空前先保存作品；可用撤销找回当前步骤。'));document.body.append(d)}d.showModal()}
window.Features144={slides,launch,gestureGuide};
})();
