/* Public facsimile reader. Virtual slices never modify the source or the copy album. */
(function init(){if(!window.Revision146?.ready||!window.CopyAlbums38||!window.Revision81){setTimeout(init,80);return}
const A=AnnotationApp,M=GalleryModel148,E=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e},icon=TouchOrder129.icon;
function action(host,name,path,run,arrow=false){const b=E('button','readerAction148'+(arrow?' readerArrow148':''));b.type='button';b.title=b.ariaLabel=name;b.innerHTML=icon(path)+(arrow?'':'<span>'+name+'</span>');b.onclick=()=>Promise.resolve(run()).catch(e=>A.toast(e.message||'暂未完成，请重试'));host.append(b);return b}
const d=E('dialog','reader148');d.id='originalReader148';const head=E('header','dialogHead'),title=E('h2'),stage=E('div','readerStage148'),image=E('img'),strip=E('div','readerThumbs148'),controls=E('nav','readerControls148'),count=E('span','readerCount148'),body=E('section','readerText148');image.draggable=false;stage.append(image);head.append(title);action(head,'关闭','m6 6 12 12M18 6 6 18',()=>d.close());d.append(head,stage,strip,controls,body);document.body.append(d);let book=null,items=[],at=0,job=0,urls=[],dimensions=new Map();
function url(source){if(typeof source==='string')return new URL(source,location.href).href;const u=URL.createObjectURL(source);urls.push(u);return u}
function layout(host,img,item){const ratio=(item.width*item.w/item.height)||.8;host.style.aspectRatio=ratio;if(host===stage){const v=window.visualViewport;const width=Math.min(Math.max(100,d.clientWidth-24),(v?.height||innerHeight)*.52*ratio);host.style.width=width+'px';host.style.height=width/ratio+'px'}else{host.style.flexBasis=Math.max(32,Math.min(96,64*ratio))+'px';host.style.height=(Math.max(32,Math.min(96,64*ratio))/ratio)+'px'}img.style.width=(100/item.w)+'%';img.style.height='100%';img.style.left=(-item.x/item.w*100)+'%';img.style.maxWidth='none';img.style.position='absolute';img.style.top='0';img.src=item.src}
function drawStrip(){strip.replaceChildren();items.forEach((item,i)=>{const b=E('button','readerThumb148'),im=E('img');b.type='button';b.title=b.ariaLabel='第 '+(i+1)+' 幅'+(item.virtual?' · 长卷分段':'');im.alt=b.title;im.loading='lazy';im.draggable=false;b.append(im);layout(b,im,item);b.onclick=()=>select(i);strip.append(b)})}
function select(index){at=Math.max(0,Math.min(items.length-1,index));const item=items[at];if(!item)return;layout(stage,image,item);image.alt=book.title+' · 第 '+(at+1)+' 幅';count.textContent=(at+1)+' / '+items.length+(item.virtual?' · 长卷分段':'');left.disabled=at>=items.length-1;right.disabled=at===0;[...strip.children].forEach((b,i)=>b.setAttribute('aria-current',String(i===at)));const b=strip.children[at];if(b)b.scrollIntoView({block:'nearest',inline:'nearest'})}
const left=action(controls,'下一页','M15 5l-7 7 7 7',()=>select(at+1),true);controls.append(count);const right=action(controls,'上一页','M9 5l7 7-7 7',()=>select(at-1),true);action(controls,'临帖','m4 20 4-1L20 7l-3-3L5 16z',()=>{const write=book.onWrite;d.close();return write?.()});action(controls,'长卷','M4 5h16v14H4zM8 5v14M16 5v14',()=>Revision81.roll(book,true));
let gesture=null;stage.onpointerdown=e=>{gesture={x:e.clientX,y:e.clientY,id:e.pointerId};stage.setPointerCapture(e.pointerId)};stage.onpointerup=e=>{if(gesture&&Math.abs(e.clientX-gesture.x)>45&&Math.abs(e.clientX-gesture.x)>Math.abs(e.clientY-gesture.y))select(at+(e.clientX>gesture.x?1:-1));gesture=null};stage.onpointercancel=()=>gesture=null;d.addEventListener('keydown',e=>{if(e.target.closest('input,textarea'))return;if(e.key==='ArrowLeft'){e.preventDefault();select(at+1)}if(e.key==='ArrowRight'){e.preventDefault();select(at-1)}});
async function search(data){const title=String(data.title||book.title).split('·').at(-1).trim();try{await navigator.clipboard.writeText(title)}catch{const input=E('textarea');input.value=title;input.style.cssText='position:fixed;opacity:0;pointer-events:none';document.body.append(input);input.select();document.execCommand('copy');input.remove()}A.toast('作品名已复制：'+title+'。去微信「发现 → 视频号」粘贴搜索，了解本作品。')}
function details(data){body.replaceChildren();const toolbar=E('div','readerTextHead148');toolbar.append(E('h3','','作品全文'));action(toolbar,'搜索','M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14m5 12 6 6',()=>search(data));body.append(toolbar);const text=M.text(data,window.PracticeTexts);body.append(E('p','readerTranscript148',text||'本帖释文待补录。'));if(text)body.append(E('small','','释文供阅读参考，字形与异文以原帖为准。'));const href=M.link(data.videoUrl148);if(href){const a=E('a','videoLink148',data.videoTitle148||'微信视频号 · 作品介绍 ↗');a.href=href;a.target='_blank';a.rel='noopener noreferrer';body.append(a)}if(InkCloud75.isFounder132){action(toolbar,text?'释文':'补录','M5 6h14M5 12h14M5 18h14',()=>{const c=Timeline73.chapters.find(c=>c.id===book.id.replace(/^timeline73:/,''));if(c){d.close();return Timeline73.edit129(c)}})}}
d.addEventListener('close',()=>{job++;urls.forEach(URL.revokeObjectURL);urls=[];items=[];book=null;image.removeAttribute('src');strip.replaceChildren()});
CopyAlbums38.viewOriginal=async next=>{if(d.open)d.close();const run=++job;book=next;at=0;items=[];title.textContent=next.title;for(const [page,p]of next.pages.entries()){const src=url(p.image);items.push({src,page,x:0,w:1,width:800,height:1000})}drawStrip();select(0);const chapter=Timeline73.chapters.find(c=>c.id===next.id.replace(/^timeline73:/,'')),data=next.metadata148||(chapter?Timeline73.data129(chapter):{title:next.title});details(data);d.showModal();select(0);for(const [page,p]of next.pages.entries()){if(run!==job||!d.open)return;const current=items.find(i=>i.page===page);let size=dimensions.get(current.src);if(!size){try{const im=new Image();im.src=current.src;await im.decode();size={width:im.naturalWidth,height:im.naturalHeight};dimensions.set(current.src,size)}catch{continue}}if(run!==job||!d.open)return;const previous=items[at],same=previous?.page===page;const parts=M.segments(size.width,size.height).map(rect=>({...rect,...size,page,src:current.src,virtual:M.segments(size.width,size.height).length>1}));const start=items.findIndex(i=>i.page===page);items.splice(start,items.filter(i=>i.page===page).length,...parts);at=same?start:items.indexOf(previous);drawStrip();select(at);Revision146.fitDialogs()}};
addEventListener('resize',()=>{if(d.open)select(at)});window.visualViewport?.addEventListener('resize',()=>{if(d.open)select(at)});window.Gallery148={ready:true};})();
