/* Home stays independent of AnnotationApp. Editor and admin code have no startup path here. */
(function(){
const M=HomeModel154,$=id=>document.getElementById(id),E=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};const forwarded=M.handoff(location.href);if(forwarded){location.replace(forwarded);return}
const icons={rank:'M3 20h18M5 18V9h4v9m2 0V4h4v14m2 0v-6h4v6',hall:'m2 8 10-6 10 6H2Zm3 2v8m7-8v8m7-8v8M2 21h20',passport:'M5 3h14v18H5zM8 7h8M8 11h8M8 15h5',history:'M5 4h14v17H5zM8 2v5M16 2v5M5 9h14M8 13h3M8 17h6',messages:'M5 17V9a7 7 0 0 1 14 0v8l2 2H3zM10 22h4',works:'M4 3h16v18H4zM8 7h8M8 11h8M8 15h5',manage:'M5 6h14M5 12h14M5 18h14',copy:'m4 20 4-1L20 7l-3-3L5 16z',check:'M5 4h14v16H5zM8 12l3 3 5-6',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14m5 12 6 6',roll:'M4 5h16v14H4zM8 5v14M16 5v14'};
const icon=key=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="'+(icons[key]||icons.manage)+'"/></svg>';document.querySelectorAll('[data-icon154]').forEach(n=>n.innerHTML=icon(n.dataset.icon154));
let cachedUser154=null;try{const cached=JSON.parse(localStorage.getItem('sb-mymubscofhvnjixdupbh-auth-token')||'null'),u=cached?.user;if(u){cachedUser154=u;const name=u.user_metadata?.full_name||u.email?.split('@')[0]||'我';$('account154').textContent=Array.from(name)[0];$('account154').dataset.signed='true';$('account154').ariaLabel='我的书房 · '+name}}catch{}
const pendingScripts=new Map();function loadScript(path){if(pendingScripts.has(path))return pendingScripts.get(path);const p=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=path;const timer=setTimeout(()=>{s.remove();pendingScripts.delete(path);reject(Error('功能加载较慢，请重试'))},20000);s.onload=()=>{clearTimeout(timer);resolve()};s.onerror=()=>{clearTimeout(timer);pendingScripts.delete(path);s.remove();reject(Error('功能暂未送达，请重试'))};document.head.append(s)});pendingScripts.set(path,p);return p}
let toastTimer;function toast(text){$('toast154').textContent=text;$('toast154').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast154').hidden=true,3500)}
function syncTheme(){const dark=document.documentElement.dataset.theme==='dark';$('theme154').textContent=dark?'深':'浅';$('theme154').dataset.dark=String(dark);$('theme154').ariaLabel=dark?'深色，点击切换浅色':'浅色，点击切换深色'}syncTheme();$('theme154').onclick=()=>{const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';try{localStorage.setItem('iinnkk.home.theme78',dark?'stars':'river')}catch{}syncTheme()};
const nav=document.querySelector('.modes154'),brand=document.querySelector('.brand154');if(window.IntersectionObserver)new IntersectionObserver(entries=>{nav.classList.toggle('stuck154',!entries[0].isIntersecting)},{threshold:0}).observe(brand);
let marks=cachedUser154?.user_metadata?.timeline79||{};let data,chapters=[],founder=false,manifest=null,lastManifest='',worldObservers=[],imageURLs=[];const signatures={'王羲之':'书圣行书冠绝千古','王献之':'小圣一笔书开新境','颜真卿':'颜体雄浑正气千秋','柳公权':'柳体骨力独步唐楷','欧阳询':'欧楷险劲法度森严','赵孟頫':'赵体圆融复兴古法','苏轼':'尚意领袖天真烂漫','黄庭坚':'长枪大戟自成书风','米芾':'刷字奇逸宋四家','怀素':'狂草如风独步一时','张旭':'草圣狂逸笔走龙蛇','毛泽东':'毛体狂草独成一体','董其昌':'淡墨疏秀一代宗师','文徵明':'小楷精绝吴门领袖','孙过庭':'草书法理一卷兼备','智永':'真草双绝承继二王','褚遂良':'唐楷清丽秀骨天成','王铎':'涨墨连绵草书大家','傅山':'奇崛苍劲自成风骨'};
function action(key,label,href){const a=E(href?'a':'button','iconCaption154');if(href)a.href=href;else a.type='button';a.title=a.ariaLabel=label;a.innerHTML=icon(key)+'<span>'+label+'</span>';return a}
function card(c,multiple=false,featured=false){const n=E('article','card154');n.dataset.chapter154=c.id;const source=c.cover143||c.pages?.[0],cover=data?.covers?.[c.id],cropped=!featured&&!!cover&&!!source&&cover.source===source&&JSON.stringify(cover.crop)===JSON.stringify(CoverCrop145.clean(c.coverCrop145));const src=featured?c.src:cropped?new URL(cover.url,location.href).href:M.safeImage(source,location.href);if(src){const im=E('img');im.src=src;im.alt=c.title;im.loading='lazy';im.decoding='async';if(!featured&&!cropped)CoverCrop145.apply(im,c.coverCrop145);n.append(im)}else n.append(E('div','placeholder154',c.glyph||'筆'));const open=E('button','cardOpen154');open.type='button';open.ariaLabel='欣赏 '+c.title;open.onclick=()=>featured?location.assign(M.writer(c.local154?{edit:c.id}:{work:c.id},location.href)):openReader(c);n.append(open);const info=E('div','cardInfo154');info.append(E('small','cardEra156',featured?'本站推荐':(c.script||'')+' · '+(c.dateLabel||'年代待考')),E('strong','',c.title));if(!featured){info.append(E('p','cardNote156',c.milestone||''),E('small','cardPlace156',[c.place,c.museum].filter(Boolean).join(' · ')));if(c.status)info.append(E('small','cardStatus156',c.status))}n.append(info);if(!featured){const quick=E('nav','cardQuick154');const write=action('copy','临帖',M.writer({post:c.id},location.href)),check=action('check','打卡');check.onclick=async()=>{try{await loadScript('homepage-reader154.js?v=154');HomeReader154.visit(c,async()=>{const api=await cloud();marks=await api.mark(c.id,'visit');updateMarks();toast('打过卡了')})}catch(e){toast(e.message)}};if(marks[c.id]?.visit){check.title=check.ariaLabel='打过卡了';check.querySelector('span').textContent='打过卡了'}quick.append(write,check);n.append(quick);const maintain=action('manage','维护',M.writer({maintain:c.id},location.href));maintain.classList.add('maintain154');maintain.hidden=!founder;n.append(maintain)}if(multiple){const dots=E('span','dots154','•••');dots.ariaLabel='同作者多幅作品，左右滑动查看';n.append(dots)}return n}
function updateMarks(){document.querySelectorAll('.card154[data-chapter154]').forEach(n=>{const b=n.querySelector('.cardQuick154 button');if(!b)return;const done=!!marks[n.dataset.chapter154]?.visit;b.title=b.ariaLabel=done?'打过卡了':'打卡';b.querySelector('span').textContent=done?'打过卡了':'打卡'})}
function observeWorld(panel){let activated=false;const reveal=()=>{if(activated)return;activated=true;panel.classList.add('worldShown154');const card=panel.querySelector('.card154');const fit=()=>panel.style.setProperty('--world-height',Math.max(80,card.getBoundingClientRect().height-24)+'px');requestAnimationFrame(fit);if(window.ResizeObserver){const ro=new ResizeObserver(fit);ro.observe(card);worldObservers.push(ro)}};if(!window.IntersectionObserver){reveal();return}const io=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){io.disconnect();reveal()}},{threshold:.08});io.observe(panel);worldObservers.push(io)}
function renderTimeline(){worldObservers.forEach(o=>o.disconnect());worldObservers=[];const host=$('timeline154');const fragment=document.createDocumentFragment();fragment.append(E('h2','','经典名帖'));for(const group of GalleryModel148.groups(chapters,c=>c)){const panel=E('section','epoch154'),head=E('header'),c=group.chapters[0];head.append(E('h3','',(c.era||group.era||'年代待考')+' · '+group.name),E('small','',c.authorPosition151||signatures[group.name]||'笔墨自成一家'));panel.append(head);const worldId=group.chapters.find(c=>data.world?.[c.id])?.id,world=data.world?.[worldId];if(world){panel.append(E('div','worldHeading154','世界文字时空'));const aside=E('aside','world154'),im=E('img');im.src='world149/'+worldId+'.jpg';im.alt=world.title;im.loading='lazy';im.decoding='async';im.onerror=()=>im.remove();aside.append(im,E('time','',world.date),E('strong','',world.title),E('small','',world.note));const link=E('a','',world.place+' ↗');link.href=world.url;link.target='_blank';link.rel='noopener noreferrer';aside.append(link);if(worldId==='shigu'){const credit=E('a','worldCredit156','图：Mike Peel · CC BY-SA 4.0 · 缩小展示');credit.href='https://commons.wikimedia.org/wiki/File:Cyrus_Cylinder.jpg';credit.target='_blank';credit.rel='noopener noreferrer';aside.append(credit)}panel.append(aside)}const track=E('div','cardTrack154');track.append(...group.chapters.map(c=>card(c,group.chapters.length>1)));panel.append(track);fragment.append(panel);if(world)observeWorld(panel)}host.replaceChildren(fragment)}
function banners(slides){const viewport=document.querySelector('.bannerWindow154');viewport.replaceChildren();let at=0,paused=false,scrollTimer;for(const [i,s]of slides.entries()){const panel=E('article','bannerSlide154');panel.style.setProperty('--banner-paper',s.paper);panel.style.setProperty('--banner-ink',s.ink);const copy=E('div');copy.append(E('small','',s.k),E('h2','',s.title),E('p','',s.sub));const link=E('a','',s.cta+' ↗');link.href=s.id==='civilization'?'#timeline154':M.writer({feature:s.id},location.href);copy.append(link);const im=E('img');im.src=(s.id.endsWith('-scene')?'banners150/':s.id==='hello-world'?'banners146/':['civilization','handwriting','constellation'].includes(s.id)?'banners145/':'banners144/')+s.id+'.svg';im.alt='';im.loading=i===0?'eager':'lazy';im.decoding='async';panel.append(copy,im);viewport.append(panel)}function sync(){at=Math.max(0,Math.min(slides.length-1,Math.round(viewport.scrollLeft/Math.max(1,viewport.clientWidth))));$('bannerCount154').textContent=String(at+1).padStart(2,'0')+' / '+slides.length;[...viewport.children].forEach((p,i)=>{const a=p.querySelector('a');a.tabIndex=i===at?0:-1})}function go(i){at=(i+slides.length)%slides.length;viewport.scrollTo({left:at*viewport.clientWidth,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});$('bannerCount154').textContent=String(at+1).padStart(2,'0')+' / '+slides.length}$('bannerPrev154').onclick=()=>{paused=true;go(at-1)};$('bannerNext154').onclick=()=>{paused=true;go(at+1)};$('bannerPause154').onclick=()=>{paused=!paused;$('bannerPause154').textContent=paused?'▷':'Ⅱ';$('bannerPause154').ariaLabel=paused?'播放轮播':'暂停轮播'};viewport.addEventListener('pointerdown',()=>paused=true,{passive:true});viewport.addEventListener('scroll',()=>{clearTimeout(scrollTimer);scrollTimer=setTimeout(sync,90)},{passive:true});viewport.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){paused=true;go(at-1)}if(e.key==='ArrowRight'){paused=true;go(at+1)}});setInterval(()=>{if(!paused&&!document.hidden&&!$('banner154').contains(document.activeElement)&&!matchMedia('(prefers-reduced-motion: reduce)').matches)go(at+1)},8000);addEventListener('resize',()=>go(at));sync()}
async function json(path){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(path,{signal:controller.signal});if(!r.ok)throw Error('内容暂未展开');return await r.json()}finally{clearTimeout(timer)}}
async function openReader(chapter){try{await loadScript('homepage-reader154.js?v=154');await HomeReader154.open(chapter)}catch(e){toast(e.message)}}
async function boot(){try{data=await json('home-data154.json?v=154');banners(data.slides);chapters=M.chapters(data.chapters,{});renderTimeline();try{manifest=await json('timeline/manifest.json');lastManifest=JSON.stringify(manifest);chapters=M.chapters(data.chapters,manifest);renderTimeline()}catch{toast('原帖目录暂未加载，可继续书写。');const retry=E('button','','重新加载原帖');retry.onclick=()=>location.reload();$('timeline154').prepend(retry)}}catch(e){document.querySelector('.timelineLoading154').textContent=e.message;const retry=E('button','','重试');retry.onclick=()=>location.reload();$('timeline154').append(retry)}}
let cloudFlight;async function cloud(){if(cloudFlight)return cloudFlight;cloudFlight=(async()=>{await loadScript('supabase-config.js?v=154');await loadScript('supabase51.js?v=154');await loadScript('homepage-cloud154.js?v=154');return HomeCloud154})().catch(e=>{cloudFlight=null;throw e});return cloudFlight}
let featuredFlight;async function recommended(){if(featuredFlight)return featuredFlight;featuredFlight=(async()=>{const host=$('featured154');let locals=[];try{const ids=await DraftStore.get('featured54')||[],index=await DraftStore.get('works-index')||[],thumbs=await Promise.all(ids.slice(0,5).map(id=>DraftStore.get(id+':thumb')));locals=ids.slice(0,5).map((id,i)=>{if(!(thumbs[i] instanceof Blob))return null;const src=URL.createObjectURL(thumbs[i]);imageURLs.push(src);return {...index.find(w=>w.id===id),id,title:index.find(w=>w.id===id)?.title||'亲笔作品',src,local154:true}}).filter(Boolean);if(locals.length)host.replaceChildren(...locals.map(w=>card(w,false,true)))}catch{}try{const api=await cloud();const rows=await api.featured();if(rows.length)host.replaceChildren(...rows.map(w=>card(w,false,true)));else if(!locals.length)host.replaceChildren(E('p','loading154','还没有推荐作品，先留下你的大手笔。'));const profile=await api.profile();if(!profile.user){marks={};updateMarks()}if(profile.user){marks=profile.user.user_metadata?.timeline79||{};updateMarks();const name=profile.user.user_metadata?.full_name||profile.user.email?.split('@')[0]||'我';$('account154').textContent=Array.from(name)[0];$('account154').dataset.signed='true';$('account154').ariaLabel='我的书房 · '+name}founder=profile.founder;$('admin154').hidden=!founder;$('messages154').hidden=!founder;document.querySelectorAll('.maintain154').forEach(n=>n.hidden=!founder)}catch{if(!locals.length){host.replaceChildren(E('p','loading154','推荐作品暂未加载。'));const retry=E('button','','重试');retry.onclick=()=>{featuredFlight=null;recommended()};host.append(retry)}}})().finally(()=>featuredFlight=null);return featuredFlight}
const feature=$('featured154');if(window.IntersectionObserver){const io=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){io.disconnect();setTimeout(recommended,0)}},{rootMargin:'0px'});io.observe(feature)}else setTimeout(recommended,1500);
window.Home154={get data(){return data},get chapters(){return chapters},get founder(){return founder},toast,icon,action,loadScript,json,openReader,writer:params=>M.writer(params,location.href)};
$('home154').addEventListener('click',e=>{const a=e.target.closest('a[href*="writer.html"]');if(a?.search.includes('mode=shared'))try{sessionStorage.setItem('iinnkk.sharedEntry154','1')}catch{}});
boot();addEventListener('pageshow',e=>{if(e.persisted)recommended()});addEventListener('pagehide',e=>{if(!e.persisted)imageURLs.forEach(URL.revokeObjectURL)});
if('serviceWorker'in navigator&&isSecureContext)setTimeout(()=>navigator.serviceWorker.register('sw.js?v=156',{scope:'./',updateViaCache:'none'}).catch(()=>{}),1200);
})();
