/* A personal practice passport, grounded in saved originals rather than guessed quality scores. */
(function(root){
 function sourceId(record){return record.copySource141?.chapterId144||/^copy:([^|]+)\|/.exec(record.local_id||'')?.[1]||null}
 function progress(records,canon,link){const map=new Map();for(const r of records){const id=sourceId(r);if(!id||r.deleted_at144||r.draft&&!r.draft.flow?.strokes?.length&&!r.draft.signatureStrokes?.length)continue;const c=canon.find(w=>link(w)?.id===id);if(!c)continue;const value=map.get(c.id)||{count:0,days:new Set(),latest:null};value.count++;value.days.add(new Date(r.updated||r.created||r.updated_at||Date.now()).toLocaleDateString('en-CA'));if(!value.latest||Number(r.updated||r.created||Date.parse(r.updated_at))>Number(value.latest.updated||value.latest.created||Date.parse(value.latest.updated_at)))value.latest=r;map.set(c.id,value)}return map}
 root.PassportModel144={sourceId,progress};if(!root.document)return;
 (function init(){if(!root.Content133||!root.Timeline73||!root.AnnotationApp?.ready){setTimeout(init,100);return}const A=AnnotationApp,C=Content133,$=id=>document.getElementById(id),E=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};let generation=0,urls=[],activeQuest=null;
 const dialog=E('dialog',undefined,'passport144');dialog.id='passport144';dialog.setAttribute('aria-label','我的书法通关文牒');const head=E('header',undefined,'passportHead144'),close=E('button','×');close.type='button';close.title=close.ariaLabel='关闭通关文牒';close.onclick=()=>dialog.close();head.append(E('small','INK PASSPORT · 二十帖，穿越千年'),E('h2','我的书法\n通关文牒'),E('p','不催进度，不比输赢。\n和二十位纸上的高手，慢慢过招。'));const top=E('header',undefined,'dialogHead passportToolbar146');top.append(E('h2','我的书法通关文牒'),close);const summary=E('section',undefined,'passportSummary144'),scroll=E('main',undefined,'passportScroll144');dialog.append(top,head,summary,scroll);document.body.append(dialog);
 dialog.addEventListener('close',()=>{generation++;urls.forEach(URL.revokeObjectURL);urls=[]});
 const encouragement=['王羲之也没跳过第一笔。今天你落笔，就赢过了昨天的空白。','手指有点忙，心倒是慢下来了。写得有你自己的味道！','不用一夜封神，先让这一笔有个好归宿。','古人负责惊艳千年，你负责今天再写一点。','这一关不扣血，只长墨。大胆来！'];
 async function enter(work){const chapter=C.linkedChapter143(work),data=chapter&&Timeline73.data129(chapter);if(data?.deleted||!data?.pages?.length){A.toast('这一帖的原图正在等待上架；先从已备好原帖的一关开始。');return}dialog.close();activeQuest=work;await Timeline73.openCopy(chapter);A.toast(encouragement[(work.rank-1)%encouragement.length]);}
 async function render(records=[],instant146=false){const run=++generation,owner=window.InkCloud75?.user?.id;urls.forEach(URL.revokeObjectURL);urls=[];const index=instant146?[]:await DraftStore.get('works-index')||[],local=[];for(const meta of index){const w=await DraftStore.get(meta.id);if(w&&(!w.cloud141||w.cloud141.owner===owner))local.push(w)}if(run!==generation||!dialog.open||owner!==window.InkCloud75?.user?.id)return;const linked=new Set(local.map(w=>w.cloud141?.id)),all=[...local,...records.filter(r=>!linked.has(r.id))],canon=C.canon.slice(0,20),stats=progress(all,canon,C.linkedChapter143),done=stats.size,totalDays=new Set([...stats.values()].flatMap(s=>[...s.days])).size;summary.replaceChildren();const seal=E('div',String(done).padStart(2,'0')+'/'+canon.length,'passportSeal144'),text=E('div');text.append(E('strong',done===canon.length?'二十帖已留墨 · 文牒成卷':done?'已为 '+done+' 帖留下亲笔':'英雄，纸上见！'),E('p',totalDays?'已临写 '+totalDays+' 天 · 每次保存都算一次认真抵达。':'首关不限，选你喜欢的那一帖。'),E('small','留墨章依据保存记录；它记录坚持，不评判书法高低。'));summary.append(seal,text);const meter=E('progress');meter.max=canon.length;meter.value=done;meter.setAttribute('aria-label','已留墨 '+done+' 帖');summary.append(meter);scroll.replaceChildren();const sorted=[...canon].sort((a,b)=>Number(Timeline73.data129(C.linkedChapter143(a)||{}).year??C.canonYears144[a.rank-1])-Number(Timeline73.data129(C.linkedChapter143(b)||{}).year??C.canonYears144[b.rank-1]));
 for(const [i,w]of sorted.entries()){const source=C.sourceWork143(w),chapter=C.linkedChapter143(w),data=chapter&&Timeline73.data129(chapter),stat=stats.get(w.id),entry=E('article',undefined,'passportGate144'+(stat?' reached':'')),title=E('header'),year=data?.year||C.canonYears144[w.rank-1];title.append(E('time',year<0?'约公元前 '+Math.abs(year)+' 年':'公元 '+year+' 年'),E('span','第 '+String(i+1).padStart(2,'0')+' 站 · '+w.script),E('h3',source.title),E('p',source.author));const pair=E('div',undefined,'passportPair144'),original=E('button',undefined,'passportPaper144 original144'),copy=E('button',undefined,'passportPaper144 copy144');original.type=copy.type='button';original.append(E('small','古人原帖'));const img=source.deleted?'':source.cover143||source.pages?.[0];if(img){const im=E('img');im.src=img;im.alt=source.title+'原帖封面';window.CoverCrop145?.apply(im,data?.coverCrop145);im.loading='lazy';im.decoding='async';original.append(im)}else{original.append(E('div',source.title,'passportWaiting144'),E('small','原帖图像待上架'))}if(window.InkCloud75?.isFounder132){const upload=E('button',img?'维护':'上传','passportMaintain146');upload.type='button';upload.title=upload.ariaLabel=(img?'维护':'上传')+' '+source.title+' 原帖';upload.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M12 16V3m-4 4 4-4 4 4M4 14v7h16v-7"/></svg><span>'+(img?'维护':'上传')+'</span>';upload.onclick=e=>{e.stopPropagation();dialog.close();C.maintain143(w)};entry.append(upload)}original.onclick=()=>enter(w).catch(e=>A.toast(e.message));copy.append(E('small','我的临写'));if(stat){let blob=stat.latest.thumbnail||await DraftStore.get(stat.latest.id+':thumb');if(run!==generation||!dialog.open)return;const src=blob instanceof Blob?URL.createObjectURL(blob):stat.latest.src;if(blob instanceof Blob)urls.push(src);if(src){const im=E('img');im.src=src;im.alt=source.title+'我的临写';im.loading='lazy';copy.append(im)}else copy.append(E('span','已留墨','heroGlyph144'));copy.append(E('span',stat.days.size>=3?'坚持印':stat.count>=3?'再临印':'留墨印','gateStamp144'),E('small','已临 '+stat.count+' 幅 · '+stat.days.size+' 天'));}else{copy.append(E('span','英雄帖','heroGlyph144'),E('p','此处虚位以待\n请君提笔入关'));const invite=E('span',undefined,'passportPractice146');invite.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="m4 20 4-1L20 7l-3-3L5 16z"/></svg><span>临帖</span>';copy.append(invite)}copy.onclick=()=>enter(w).catch(e=>A.toast(e.message));pair.append(original,copy);entry.append(title,pair,E('p',encouragement[i%encouragement.length],'gatePraise144'));scroll.append(entry)}
 }
 async function open(){if(!dialog.open)dialog.showModal();summary.textContent='正在展开你的文牒…';await render([],true);if(!dialog.open)return;summary.append(E('small','正在读取你的临写记录…'));await render();if(window.InkCloud75?.user&&navigator.onLine){try{const records=await InkCloud75.mine111();if(dialog.open)await render(records)}catch{if(dialog.open)summary.append(E('small','云端暂未连接，已展示本机临写记录。'))}}}
 function mount(){const title=document.querySelector('#cloudGallery75 .canon133>h3');if(title&&!document.getElementById('passportEntry144')){const b=E('button',undefined,'passportEntry144');b.id='passportEntry144';b.type='button';b.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M6 3h12v18H6zM9 7h6M9 11h6M9 15l2 2 4-4"/></svg><span>我的书法通关文牒</span>';b.onclick=()=>open().catch(e=>A.toast(e.message));title.after(b)}}new MutationObserver(mount).observe(document.body,{childList:true,subtree:true});mount();
 document.addEventListener('work-archived',async e=>{if(!activeQuest)return;const work=await DraftStore.get(e.detail.id);if(sourceId(work)!==C.linkedChapter143(activeQuest)?.id||!work.draft?.flow?.strokes?.length)return;A.toast('本帖留墨章已收入文牒！'+encouragement[(activeQuest.rank-1)%encouragement.length]);activeQuest=null});document.addEventListener('cloud-user84',()=>{if(dialog.open)open().catch(()=>{})});root.Passport144={open,enter};
 })();
})(typeof window==='undefined'?globalThis:window);
