/* Transparent raster + true alpha-contour vectors, millimetre units. No embedded raster SVG. */
(function(){
'use strict';
const yieldUI=()=>new Promise(r=>setTimeout(r,0));
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
async function pngDPI(canvas,dpi=300){const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));if(!blob)throw Error('PNG 编码失败');const data=new Uint8Array(await blob.arrayBuffer()),chunk=new Uint8Array(21),view=new DataView(chunk.buffer);view.setUint32(0,9);chunk.set([112,72,89,115],4);const ppm=Math.round(dpi/0.0254);view.setUint32(8,ppm);view.setUint32(12,ppm);chunk[16]=1;view.setUint32(17,crc32(chunk.subarray(4,17)));return new Blob([data.subarray(0,33),chunk,data.subarray(33)],{type:'image/png'})}
function simplify(points){return points.filter((p,i,a)=>{const prev=a[(i+a.length-1)%a.length],next=a[(i+1)%a.length];return (p[0]-prev[0])*(next[1]-p[1])!==(p[1]-prev[1])*(next[0]-p[0]);});}
async function contours(canvas,threshold=24){
 const ratio=Math.min(1,1024/canvas.width,1024/canvas.height),c=document.createElement('canvas');c.width=Math.max(1,Math.round(canvas.width*ratio));c.height=Math.max(1,Math.round(canvas.height*ratio));const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(canvas,0,0,c.width,c.height);const w=c.width,h=c.height,data=ctx.getImageData(0,0,w,h).data,on=(x,y)=>x>=0&&y>=0&&x<w&&y<h&&data[(y*w+x)*4+3]>=threshold;
 const edges=new Map();let count=0;const key=(x,y)=>y*(w+1)+x,add=(x,y,xx,yy)=>{const k=key(x,y);if(!edges.has(k))edges.set(k,[]);edges.get(k).push(key(xx,yy));if(++count>1000000)throw Error('飞白细节过多，请调高轮廓阈值后重试。')};
 for(let y=0;y<h;y++){for(let x=0;x<w;x++){if(!on(x,y))continue;if(!on(x,y-1))add(x,y,x+1,y);if(!on(x+1,y))add(x+1,y,x+1,y+1);if(!on(x,y+1))add(x+1,y+1,x,y+1);if(!on(x-1,y))add(x,y+1,x,y)}if(y%32===0)await yieldUI();}
 const result=[];let walked=0;
 while(edges.size){const start=edges.keys().next().value;let k=start,prev=null,path=[];do{path.push([k%(w+1),Math.floor(k/(w+1))]);const targets=edges.get(k);if(!targets?.length)throw Error('轮廓未闭合，请调整阈值');let idx=0;if(targets.length>1&&prev!==null){const dx=k%(w+1)-prev%(w+1),dy=Math.floor(k/(w+1))-Math.floor(prev/(w+1));let best=-Infinity;targets.forEach((n,i)=>{const ex=n%(w+1)-k%(w+1),ey=Math.floor(n/(w+1))-Math.floor(k/(w+1)),score=dx*ey-dy*ex;if(score>best){best=score;idx=i}})}const next=targets.splice(idx,1)[0];if(!targets.length)edges.delete(k);prev=k;k=next;if(++walked>1000001)throw Error('轮廓数量超限')}while(k!==start);path=simplify(path);if(path.length>=3)result.push(path);if(result.length%64===0)await yieldUI();}
 if(!result.length)throw Error('此阈值下没有可用轮廓，请降低阈值。');return{paths:result,width:w,height:h};
}
function vectorFiles(trace,widthMM){const heightMM=widthMM*trace.height/trace.width,scale=widthMM/trace.width,n=x=>Number((x*scale).toFixed(4));
 const d=trace.paths.map(p=>'M'+p.map(q=>n(q[0])+','+n(q[1])).join('L')+'Z').join('');
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${widthMM}mm" height="${heightMM.toFixed(4)}mm" viewBox="0 0 ${widthMM} ${heightMM.toFixed(4)}"><title>亲笔墨迹轮廓 · 毫米</title><path d="${d}" fill="#000000" fill-rule="evenodd"/></svg>`;
 const lines=['0','SECTION','2','HEADER','9','$ACADVER','1','AC1015','9','$INSUNITS','70','4','0','ENDSEC','0','SECTION','2','ENTITIES'];
 for(const p of trace.paths){lines.push('0','LWPOLYLINE','100','AcDbEntity','8','INK','100','AcDbPolyline','90',String(p.length),'70','1');for(const [x,y]of p)lines.push('10',String(n(x)),'20',String(n(trace.height-y)))}lines.push('0','ENDSEC','0','EOF');return{svg,dxf:lines.join('\n')+'\n',heightMM};
}
let vendorPromise;
function vendor(){if(window.InkCraft3D50)return Promise.resolve(window.InkCraft3D50);if(!vendorPromise)vendorPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='craft3d50.js?v=50';s.onload=()=>resolve(window.InkCraft3D50);s.onerror=()=>{vendorPromise=null;s.remove();reject(Error('三维模块未加载，请确认源码包包含 craft3d50.js'))};document.head.append(s)});return vendorPromise;}
let panel,viewer,source,canvas,readyPackage=null,loadVersion=0;
async function open(){
 const U=InkStudio50,app=AnnotationApp;source=app.productionSource();if(!source?.strokes.length)throw Error('这幅作品没有可分离的笔迹数据。请先书写并生成作品；旧合成图片不能无损去背景。');
 viewer?.dispose();readyPackage=null;const serial=++loadVersion;panel=U.dialog('craftDialog50','文创二创 · 让亲笔走进生活');const {d,body}=panel;
 body.append(U.E('p',{class:'studioEyebrow50'},'真实笔迹 · 三维预览 · 生产图稿'));
 const tabs=U.E('div',{class:'studioActions50'}),stage=U.E('div',{class:'craftStage50','aria-label':'可旋转的文创三维预览'}),notice=U.E('p',{class:'studioNote50',role:'status'},'正在准备透明墨迹…'),controls=U.E('div',{class:'studioFields50'}),downloads=U.E('div',{class:'studioActions50'});body.append(tabs,stage,notice,controls,downloads);
 let type='mug',widthMM=100,threshold=24,busy=false;
 for(const [key,label]of [['mug','马克杯'],['shirt','文化衫'],['base','手办底座 / 摆件']]){const b=U.button(tabs,label,()=>{type=key;viewer?.setType(type);readyPackage=null;for(const t of tabs.children)t.setAttribute('aria-pressed',String(t===b))});b.setAttribute('aria-pressed',String(key===type))}
 function field(label,value,min,max,step,fn){const l=U.E('label',{},label),e=U.E('input',{type:'number',value,min,max,step});e.onchange=()=>{const n=Number(e.value);if(!Number.isFinite(n)||n<min||n>max){e.value=value;notice.textContent=label+'超出范围';return}fn(n);readyPackage=null};l.append(e);controls.append(l);return e;}
 field('图稿宽度（毫米）',widthMM,10,300,1,v=>widthMM=v);field('轮廓阈值（保留飞白）',threshold,1,240,1,v=>threshold=v);
 field('贴图大小 %',85,20,150,1,v=>viewer?.setPlacement({scale:v/100}));field('贴图横移 %',0,-50,50,1,v=>viewer?.setPlacement({x:v/100}));field('贴图纵移 %',0,-50,50,1,v=>viewer?.setPlacement({y:v/100}));
 let colorLabel=U.E('label',{},'产品底色'),color=U.E('input',{type:'color',value:'#ede5d7'});color.oninput=()=>{viewer?.setColor(color.value);readyPackage=null};colorLabel.append(color);controls.append(colorLabel);
 const generate=U.button(downloads,'导出文创生产文件',async()=>{if(busy||!canvas)return;busy=true;readyPackage=null;generate.disabled=true;for(const e of [...controls.querySelectorAll('input'),...tabs.querySelectorAll('button')])e.disabled=true;const exportSource=source,exportViewer=viewer,exportWidth=widthMM,exportThreshold=threshold,exportType=type;try{notice.textContent='正在生成 300 DPI 透明 PNG 与毫米矢量轮廓…';const production=await app.productionCanvas(exportSource,Math.ceil(exportWidth/25.4*300));const png=await pngDPI(production),trace=await contours(production,exportThreshold),v=vectorFiles(trace,exportWidth),meta={version:1,title:'今日亲笔',product:exportType,widthMM:exportWidth,heightMM:v.heightMM,dpi:300,threshold:exportThreshold,vectorTracePixels:[trace.width,trace.height],placement:exportViewer?.placement||{},formats:exportViewer?['PNG','SVG','DXF','GLB']:['PNG','SVG','DXF'],notes:'PNG 保留浓淡与飞白；SVG/DXF 为单色轮廓。GLB 是贴图效果模型，不是可直接打印的实体。生产前由供应商复核尺寸、最细笔画、出血、材质与模型壁厚。'};
 const entries=[{name:'ink-300dpi.png',blob:png},{name:'ink-outline.svg',blob:new Blob([v.svg],{type:'image/svg+xml'})},{name:'ink-outline.dxf',blob:new Blob([v.dxf],{type:'application/dxf'})},{name:'production.json',blob:new Blob([JSON.stringify(meta,null,2)],{type:'application/json'})}];
 if(serial!==loadVersion)return;if(exportViewer){const glb=await exportViewer.exportGLB();entries.push({name:exportType+'-preview.glb',blob:new Blob([glb],{type:'model/gltf-binary'})})}else meta.formats=meta.formats.filter(x=>x!=='GLB');
 entries.push({name:'README.txt',blob:new Blob(['亲笔文创生产参考包\n\n'+meta.notes+'\n\nDXF 单位：毫米；各轮廓为闭合多段线，孔洞由供应商按嵌套关系处理。SVG 使用 evenodd 保留孔洞。\n透明 PNG 为彩色原墨迹，含 300 DPI pHYs 信息。GLB 单位为米，仅供外观沟通。\n调整贴图位置不会改变原始生产墨稿；摆放参数记录于 production.json。'],{type:'text/plain;charset=utf-8'})});
 const zip=await WorkZip(entries);if(serial!==loadVersion)return;readyPackage={zip,meta};U.download(zip,'亲笔文创-'+exportType+'.zip');notice.textContent='生产参考包已导出：透明 PNG、SVG、DXF'+(viewer?'、GLB':'')+'。请供应商复核后投产。';}finally{busy=false;generate.disabled=false;for(const e of [...controls.querySelectorAll('input'),...tabs.querySelectorAll('button')])e.disabled=false}});
 const submit=U.button(downloads,'发送供应链',async()=>{const url=U.config.integrations.webhook;if(!url)throw Error('请先在本机管理中填写供应链 Webhook 地址');if(!readyPackage)throw Error('请先生成生产文件');const endpoint=U.safeURL(url),confirm=U.dialog('supplyConfirm50','确认发送生产图稿');confirm.body.append(U.E('p',{},'将生产参考包发送到 '+new URL(endpoint).host+'。这一步仅提交图稿，不代表下单或付款。'));const send=U.button(confirm.body,'发送这份图稿',async()=>{if(send.disabled)return;send.disabled=true;const form=new FormData();form.append('file',readyPackage.zip,'production.zip');form.append('metadata',JSON.stringify(readyPackage.meta));const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),60000);try{const r=await fetch(endpoint,{method:'POST',body:form,signal:controller.signal,redirect:'error',credentials:'omit'});if(!r.ok)throw Error('供应链未接收：HTTP '+r.status);notice.textContent='图稿已发送，接收方返回成功状态；请联系供应商确认工艺。';confirm.d.close()}finally{clearTimeout(timer);send.disabled=false}});confirm.d.showModal();});
 body.append(U.E('p',{class:'studioNote50'},'拖动模型旋转，双指缩放。三维图是产品效果预览；墨迹 PNG 保留透明背景，矢量轮廓适合交给印刷或雕刻供应商复核。'));
 d.addEventListener('close',()=>{++loadVersion;viewer?.dispose();viewer=null;canvas=null;readyPackage=null},{once:true});d.showModal();
 try{canvas=await app.productionCanvas(source,1000);if(serial!==loadVersion)return;const V=await vendor();if(serial!==loadVersion)return;viewer=V.create(stage,canvas);notice.textContent='拖动旋转；调整贴图大小与位置。';}catch(e){if(serial!==loadVersion)return;stage.replaceChildren();if(canvas){const im=U.E('img',{src:canvas.toDataURL(),alt:'透明笔迹平面预览'});stage.append(im)}notice.textContent='三维预览暂不可用：'+e.message+'。仍可导出透明图与矢量轮廓。';}
}
function init(){if(!window.InkStudio50?.ready){setTimeout(init,50);return}const U=InkStudio50,body=document.querySelector('#imageDialog .dialogBody');const row=U.E('div',{class:'studioActions50',id:'creationActions50'});U.button(row,'文创二创画布预览',open,{id:'craftOpen50'});body.prepend(row);}
window.InkProduction50={contours,vectorFiles,pngDPI,open};init();
})();
