/* Release 66: compact preview controls, readable guides and a persistent paper toolbar. */
(function init(){if(!window.AnnotationApp?.ready||!window.DailyQuotes38||!document.getElementById('previewEffects55')||!document.getElementById('extendPaper63')){setTimeout(init,45);return}
const $=id=>document.getElementById(id),toolbar=$('topActions'),extend=$('extendPaper63');
function alignLast(){if(extend.isConnected&&toolbar.lastElementChild!==extend)toolbar.append(extend)}alignLast();new MutationObserver(alignLast).observe(toolbar,{childList:true});
// The home and upper toolbar never show the administration shortcut.
function removeHomeEditor(){document.querySelectorAll('.annotationBrand .liveEdit53').forEach(b=>b.remove())}removeHomeEditor();new MutationObserver(removeHomeEditor).observe(document.querySelector('.annotationBrand'),{childList:true});
const scope=$('inkScope39');function scopeIcon(){if(!scope)return;const all=$('recolorScope').value==='all';scope.setAttribute('aria-label',all?'整幅墨色 · 点击改下一笔':'下一笔墨色 · 点击改整幅');scope.querySelector('path')?.setAttribute('d',all?'M12 2c3 5 7 8 7 12a7 7 0 0 1-14 0c0-4 4-7 7-12ZM8 14c0 2 2 4 4 4':'M4 20 16 4l4 3-11 16-5-3ZM9 17l4 3')}scope?.addEventListener('click',()=>requestAnimationFrame(scopeIcon));$('recolorScope')?.addEventListener('change',scopeIcon);scopeIcon();
const controls=$('previewEffects55'),actions=controls.querySelector('.previewActions56');const zoom=document.createElement('span');zoom.className='previewZoom66';for(const [label,factor] of [['−',1/1.45],['＋',1.45]]){const b=document.createElement('button');b.type='button';b.textContent=label;b.title=label==='＋'?'放大作品细节':'缩小作品';b.setAttribute('aria-label',b.title);b.onclick=()=>window.zoomPreview66?.(factor);zoom.append(b)}document.querySelector('.workspace').append(zoom);$('returnWriting59').textContent='返回书写';$('generateArtwork59').textContent='生成下载';
const panel=document.createElement('aside');panel.id='previewQuote66';panel.hidden=true;panel.innerHTML='<button class="quoteOpen66" type="button" aria-expanded="false">今日宜写 · 展开</button><div class="quoteBody66" hidden><div class="quoteLine66"></div><small class="quoteSource66"></small><div class="quoteTools66"><select aria-label="选择好词好句类别"></select><button type="button" class="quoteNext66">换一句</button><button type="button" class="quoteClose66" aria-label="收起好词好句">收起</button></div></div>';
document.querySelector('.workspace').append(panel);const open=panel.querySelector('.quoteOpen66'),body=panel.querySelector('.quoteBody66'),category=panel.querySelector('select');function sync(){const q=window.currentQuote;panel.querySelector('.quoteLine66').textContent=q?.q||$('quoteText')?.textContent||'';panel.querySelector('.quoteSource66').textContent=q?.s||$('quoteSource')?.textContent||'';if(q?.cat)category.value=q.cat}for(const option of document.querySelectorAll('[data-quote-category]'))category.add(new Option(option.textContent.split(' · ')[0],option.dataset.quoteCategory));open.onclick=()=>{body.hidden=!body.hidden;open.setAttribute('aria-expanded',String(!body.hidden));open.textContent=body.hidden?'今日宜写 · 展开':'今日宜写 · 收起';sync()};panel.querySelector('.quoteClose66').onclick=()=>open.click();panel.querySelector('.quoteNext66').onclick=()=>{window.DailyQuotes38.select(category.value||window.currentQuote?.cat||'moon');sync()};category.onchange=()=>{window.DailyQuotes38.select(category.value);sync()};document.addEventListener('quote-changed',sync);const daily=$('dailyQuote');if(daily)new MutationObserver(sync).observe(daily,{childList:true,subtree:true});new MutationObserver(()=>{panel.hidden=controls.hidden||document.body.classList.contains('home-open');if(!panel.hidden)sync()}).observe(controls,{attributes:true,attributeFilter:['hidden']});
document.documentElement.classList.add('ui-ready67');
})();
