/* Release 65: active writing preset, consistent seals and quiet writing surface. */
(function init(){if(!window.AnnotationApp?.ready||!window.InkStudio50?.ready||!window.WritingMusic||!document.getElementById('topMusic')){setTimeout(init,50);return}
const $=id=>document.getElementById(id),app=AnnotationApp;
// A home action always starts a new 创作 sheet, including when an old draft has ink.
const direct=$('continueWriting');direct.onclick=async()=>{const entry=InkStudio50.config.nav.find(n=>n.id==='letter');if(entry)await InkStudio50.applyMode(entry);else app.showWriter()};
// Persisted admin option labels from older releases must not restore obsolete vocabulary.
try{const key='iinnkk.optionLabels53',labels=JSON.parse(localStorage.getItem(key)||'{}');let changed=false;for(const [id,value] of [['headType','yin'],['headType','yang'],['tailType','yin'],['tailType','yang'],['extraSealType','yin'],['extraSealType','yang'],['selectedSealType','yin'],['selectedSealType','yang']]){const k=JSON.stringify([id,value]);if(k in labels){delete labels[k];changed=true}}if(changed)localStorage.setItem(key,JSON.stringify(labels))}catch{}
const names={yin:'阴刻',yang:'阳刻'};function sealLabels(){for(const id of ['headType','tailType','extraSealType','selectedSealType']){const select=$(id);if(!select)continue;for(const o of select.options)if(names[o.value])o.textContent=names[o.value]+(id==='headType'||id==='tailType'?(o.value==='yin'?' · 白文':' · 朱文'):'')}const font=$('sealFont');if(font?.value==='song'||font?.value==='regular')font.value='youlong'}sealLabels();
// No bundled copy of a restricted font: use a legitimate local installation or personal import.
if(!localStorage.getItem('iinnkk.sealDefault71')){for(const id of ['headFont','sealFont','extraSealFont'])if($(id)&&['youlong','small',''].includes($(id).value))$(id).value='yishan';localStorage.setItem('iinnkk.sealDefault71','1');app.refresh();app.persist?.()}
function loadSealFace(family,flag){return document.fonts.load('180px '+family,'今日亲笔見墨如我').then(faces=>{window[flag]=faces.length>0;window.sealFontRevision=(window.sealFontRevision||0)+1;app.refresh();$('sealFont').dispatchEvent(new Event('input'))}).catch(()=>{window[flag]=false})}
loadSealFace('YouLongSeal','youLongSealReady');
if(['headFont','sealFont','extraSealFont'].some(id=>$(id)?.value==='yishan'))loadSealFace('YiShanBeiSeal','yiShanBeiSealReady');
document.addEventListener('change',e=>{if(e.target?.value==='yishan'&&!window.yiShanBeiSealReady)loadSealFace('YiShanBeiSeal','yiShanBeiSealReady')});
document.fonts.load('180px ChongxiSeal','今日亲笔見墨如我').then(()=>{window.chongxiSealReady=true;window.sealFontRevision=(window.sealFontRevision||0)+1;app.refresh();$('sealFont').dispatchEvent(new Event('input'))}).catch(()=>{});
// A compact selector replaces the old button that silently cycled across tracks.
const music=$('topMusic'),picker=document.createElement('dialog');picker.id='musicPicker65';picker.setAttribute('aria-label','伴写声音');picker.innerHTML='<header><strong>伴写声音</strong><button type="button" class="closeMusic65" aria-label="关闭">×</button></header><div class="musicChoices65"></div><fieldset class="musicOrder72"><legend>播放顺序</legend><label><input type="radio" name="musicOrder72" value="sequence" checked>顺序播放</label><label><input type="radio" name="musicOrder72" value="random">随机播放</label></fieldset><div class="musicOwn72"><button type="button" id="musicUpload72">播放我的音乐 · 上传 MP3</button><label>在线音频链接<input id="musicURL72" type="url" inputmode="url" placeholder="https://…/music.mp3"></label><button type="button" id="musicLink72">播放在线音乐</button><small id="musicTip72">在线链接须允许浏览器直接播放音频。</small></div>';document.body.append(picker);picker.querySelector('.closeMusic65').onclick=()=>picker.close();const choices=picker.querySelector('.musicChoices65'),select=$('writingTrack');for(const o of select.options){if(o.value==='custom'||o.value==='remote')continue;const b=document.createElement('button');b.type='button';b.textContent=o.textContent;b.dataset.music=o.value;b.onclick=()=>{WritingMusic.choose(o.value)};choices.append(b)}const stop=document.createElement('button');stop.textContent='暂停声音';stop.onclick=()=>{WritingMusic.pause()};choices.append(stop);picker.querySelectorAll('[name="musicOrder72"]').forEach(r=>r.onchange=()=>WritingMusic.setOrder(r.value));$('musicUpload72').onclick=()=>WritingMusic.openUpload();$('musicLink72').onclick=()=>{if(WritingMusic.playURL($('musicURL72').value.trim()))picker.querySelector('.musicChoices65')?.scrollTo(0,0);else $('musicTip72').textContent='请填写可直接播放的 http/https 音频链接'};music.onclick=()=>{for(const b of choices.querySelectorAll('[data-music]'))b.classList.toggle('active',b.dataset.music===select.value);picker.querySelector('[name="musicOrder72"][value="'+WritingMusic.getOrder()+'"]').checked=true;picker.showModal()};music.title=music.ariaLabel='伴写声音 · 选择曲目';
// Long press and double tap on the canvas should not invoke iOS's text selection overlay.
const board=$('board');for(const event of ['selectstart','contextmenu','dragstart'])board.addEventListener(event,e=>{if(!e.target.closest('input,textarea,[contenteditable="true"]'))e.preventDefault()});document.addEventListener('selectionchange',()=>{if(document.body.classList.contains('home-open'))return;const a=document.activeElement;if(a?.matches('input,textarea,[contenteditable="true"]'))return;const selection=getSelection();if(selection?.rangeCount&&board.contains(selection.anchorNode))selection.removeAllRanges()});
})();
