/* Local layout editor and paper-mode orchestration. No remote admin authority. */
(function init(){if(!window.InkStudio50?.ready||!window.CopyAlbums38||!window.Status42||!window.Revision47){setTimeout(init,40);return}const U=InkStudio50,A=AnnotationApp,$=id=>document.getElementById(id),E=U.E;
$('managementEntry52')?.remove();$('studioManage50')?.remove();$('panPad47')?.remove();$('critiqueOpen50')?.remove();
// Settings are the only visible management entry; require the password on each entry.
for(const dialog of document.querySelectorAll('dialog .settingsTabs')){const b=E('button',{type:'button'},'本机管理');b.onclick=()=>U.openAdmin();dialog.append(b)}
const closeToParent=d=>{const parent=[...document.querySelectorAll('dialog[open]')].find(x=>x!==d);return()=>{d.close();if(parent?.isConnected&&!parent.open)parent.showModal()}};
// Short, selectable status information.
const short={dragon:'云龙',none:'素面',plain:'素笺',xuan:'纤宣',hemp:'古麻',silk:'绢纹',watercolor:'水彩',parchment:'古卷'};
function status(){for(const[id,control,prefix]of [['statusRatio42','ratio',''],['statusPattern42','paperPattern',''],['statusMaterial42','material',''],['statusColor42','papercolor','纸色'],['statusMount42','sceneChoice','']]){const e=$(id),c=$(control);if(!e||!c)continue;let t=short[c.value]||c.selectedOptions?.[0]?.textContent||'';if(control==='ratio')t=Math.abs(+c.value-.75)<.001?'3:4':Math.abs(+c.value-1)<.001?'斗方':t.split(/[ ·]/)[0];if(control==='sceneChoice')t=c.value==='none'?'常裱':'趣裱';e.textContent=prefix||t.split(/[ ·]/)[0].slice(0,4)}}const oldStatus=Status42.sync;Status42.sync=()=>{oldStatus();status()};status();
// The Yong diagram is intentionally a pale teaching guide, not an attributed facsimile.
window.drawYong53=(t,a)=>{let opts;try{opts=JSON.parse(localStorage.getItem('iinnkk.yong53')||'{}')}catch{opts={}}if(opts.enabled===false)return;const size=Math.min(a.w,a.h)*.69,x=a.x+a.w/2,y=a.y+a.h/2;t.save();t.globalAlpha=.10;t.fillStyle='#73523c';t.font=size+'px AnnotationHand,ZhenjiKai,"Kaiti SC",Caption38,serif';t.textAlign='center';t.textBaseline='middle';t.fillText(opts.text||'永',x,y);t.globalAlpha=.25;t.font=Math.min(a.w,a.h)*.037+'px Caption38,serif';const labels=opts.notes||['侧 · 点贵侧锋','勒 · 横须逆入','努 · 竖应挺劲','趯 · 钩先蹲锋','策 · 提须疾出','掠 · 长撇舒展','啄 · 短撇劲利','磔 · 捺渐开张'];labels.forEach((v,i)=>t.fillText(v,x+(i<4?-1:1)*a.w*.32,a.y+a.h*(.12+(i%4)*.25)));t.restore()};
let current=localStorage.getItem('iinnkk.mode53')||'',switching=false;window.practiceMode53=U.config.nav.find(n=>n.id===current)?.layout==='single'?'single':'';const switcher=E('nav',{id:'writerModes53','aria-label':'书写模式'});$('bottomIcons39').before(switcher);
function modeButtons(){switcher.replaceChildren();for(const n of U.config.nav){const b=E('button',{type:'button','aria-pressed':String(current===n.id)},n.title);b.onclick=()=>U.applyMode(n).catch(U.report);switcher.append(b)}}modeButtons();document.addEventListener('studio-config50',modeButtons);
const loadImage=src=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('字帖图片未加载'));im.src=src});
if(current==='copy')DraftStore.get('copy-ref53').then(async src=>{if(!A.getReference()&&current==='copy'){const im=await loadImage(src||await DraftStore.get('default-reference53')||'practice/thousand-guide53.svg');if(current==='copy'&&!A.getReference())A.setReference(im)}}).catch(U.report);
async function fitReference(im,focus=true){const boxes=Reference47.detect(im),b=boxes[0]||{x:.86,y:.1,w:.12,h:.1};const board=$('board').getBoundingClientRect(),ratio=im.width/im.height,pw=4,ph=4/ratio,base=Math.max(board.width/pw,board.height/ph),scale=Math.min(board.width/(pw*b.w*1.65),board.height/(ph*b.h*1.65)),zoom=Math.max(100,Math.min(2500,Math.round(scale/base*100)));$('zoom').max='2500';const oldLocked=window.writingLocked;window.writingLocked=false;await A.configure47({values:{stationery:'vermillion',paperExtent:'fixed',ratio:String(ratio),refFit:'contain',refX:'50',refY:'50',zoom:String(focus?zoom:+$('zoom').value||zoom),sceneChoice:'none',guideMode:'off',showLines:'no'},inkOpacity:1});A.setReference(im);if(focus)A.focusPoint({x:b.x*pw,y:b.y*ph});window.writingLocked=oldLocked;Revision39.syncLock();A.persist();}
window.Modes53={async activate(n,apply){if(switching)return;switching=true;try{if(current){A.finish();await DraftStore.set('mode53:'+current,{...A.getState(),modeConfig53:JSON.stringify(U.config.nav.find(x=>x.id===current))});if(current==='copy'){const im=A.getReference();if(im){const c=document.createElement('canvas');c.width=im.width;c.height=im.height;c.getContext('2d').drawImage(im,0,0);await DraftStore.set('copy-ref53',c.toDataURL('image/jpeg',.92))}await CopyAlbums38.pause?.()}}window.writingLocked=false;A.setReference(null);window.practiceMode53=n.layout==='single'?'single':'';current=n.id;localStorage.setItem('iinnkk.mode53',current);document.dispatchEvent(new CustomEvent('mode-changed54',{detail:n}));await apply();const saved=await DraftStore.get('mode53:'+n.id);if(saved){await A.restoreDraft(saved);await A.configure47({});if(saved.modeConfig53&&saved.modeConfig53!==JSON.stringify(n))await apply()}if(n.id==='copy'){window.practiceMode53='';const resumed=await CopyAlbums38.resume?.();if(!resumed){const src=await DraftStore.get('copy-ref53')||localStorage.getItem('iinnkk.defaultReference53');if(src){await fitReference(await loadImage(src),!saved)}else{const configured=await DraftStore.get('default-reference53');if(configured)await fitReference(await loadImage(configured),true);else{await fitReference(await loadImage('practice/thousand-guide53.svg'),true);A.toast('千字文排字练习底本 · 请在后台上传文徵明原帖')}}}window.annotationInkOpacity=1}else{A.setReference(null);await CopyAlbums38.pause?.()}window.writingLocked=true;Revision39.syncLock();A.refresh();if(n.layout==='single'&&!saved)A.focusPoint({x:2,y:2/(+document.getElementById('ratio').value||1)});modeButtons();A.showWriter()}finally{switching=false}},fitReference,async referenceLoaded(im,focus=true){current='copy';localStorage.setItem('iinnkk.mode53','copy');window.practiceMode53='';modeButtons();await fitReference(im,focus);window.writingLocked=true;Revision39.syncLock()}};
document.addEventListener('reference-loaded47',e=>Modes53.referenceLoaded(e.detail.image).catch(U.report));
document.addEventListener('reset-mode53',()=>{current='';localStorage.removeItem('iinnkk.mode53');window.practiceMode53='';CopyAlbums38.pause();modeButtons()});
// Per-option labels are editable without changing serialized option values.
let labels={};try{labels=JSON.parse(localStorage.getItem('iinnkk.optionLabels53')||'{}')}catch{}
function applyLabels(){for(const [key,text]of Object.entries(labels)){const [id,value]=JSON.parse(key);const option=[...($(id)?.options||[])].find(o=>o.value===value);if(option)option.textContent=text}status()}applyLabels();
function adminExtras(body){const details=E('details');details.append(E('summary',{},'选项名称与临帖预设'));const select=E('select',{'aria-label':'选择要改名的选项'}),name=E('input',{type:'text','aria-label':'选项新名称',placeholder:'修改名称'});for(const s of document.querySelectorAll('select[id]'))if(!s.closest('.studioDialog50'))for(const o of s.options){const key=JSON.stringify([s.id,o.value]);select.append(E('option',{value:key},(s.closest('label')?.childNodes[0]?.textContent||s.id).trim().slice(0,12)+' / '+o.textContent))}select.onchange=()=>{name.value=select.selectedOptions[0]?.textContent.split(' / ').at(-1)||''};name.onchange=()=>{if(!U.isAdmin)return;labels[select.value]=name.value.slice(0,60);localStorage.setItem('iinnkk.optionLabels53',JSON.stringify(labels));applyLabels()};details.append(select,name);const file=E('input',{type:'file',accept:'image/*','aria-label':'替换默认临帖原帖'}),note=E('p',{},'文徵明小楷千字文原帖尚待上传；当前内置为千字文排字练习底本，不是真迹。上传原帖即可替换，组图请到临帖菜单上传。');file.onchange=async()=>{if(!U.isAdmin||!file.files[0])return;try{const f=file.files[0];if(f.size>20*1024*1024)throw Error('图片请小于20MB');const reader=new FileReader();reader.onload=async()=>{await DraftStore.set('default-reference53',reader.result);await DraftStore.set('copy-ref53',reader.result);await CopyAlbums38.clear();await DraftStore.set('mode53:copy',null);note.textContent='默认原帖已保存，下次进入临帖使用。'};reader.readAsDataURL(f)}catch(e){U.report(e)}};details.append(note,file);const y=E('input',{type:'text',value:'永','aria-label':'单字水印'});let yc={};try{yc=JSON.parse(localStorage.getItem('iinnkk.yong53')||'{}')}catch{}y.value=yc.text||'永';y.onchange=()=>{yc.text=y.value.slice(0,2);localStorage.setItem('iinnkk.yong53',JSON.stringify(yc));A.refresh()};const yn=E('textarea',{'aria-label':'永字八法说明',placeholder:'八法说明，每行一条'});yn.value=(yc.notes||['侧 · 点贵侧锋','勒 · 横须逆入','努 · 竖应挺劲','趯 · 钩先蹲锋','策 · 提须疾出','掠 · 长撇舒展','啄 · 短撇劲利','磔 · 捺渐开张']).join('\n');yn.onchange=()=>{yc.notes=yn.value.split('\n').slice(0,8);localStorage.setItem('iinnkk.yong53',JSON.stringify(yc));A.refresh()};details.append(E('p',{},'单字水印与八法提示'),y,yn);body.append(details)}document.addEventListener('admin-panel53',e=>adminExtras(e.detail.body));
// WYSIWYG: reorder in normal document flow so deleted blocks reflow automatically.
const LS='iinnkk.layout53';let layout={blocks:{},custom:[],order:[]};try{layout={...layout,...JSON.parse(localStorage.getItem(LS)||'{}')}}catch{}let editing=false,selected=null,bar;const targets=['.annotationBrand h1','.annotationBrand p','#annotationHome footer span','.annotationIntro','#homeQuick47','#annotationCategories','.annotationGallery','.annotationAction','#annotationHome footer','.topStrip','#writerModes53','#statusBar42'];
function keyFor(el){return el.dataset.editKey53||targets.find(s=>el.matches(s))}
function persistLayout(){if(!U.isAdmin)return;localStorage.setItem(LS,JSON.stringify(layout));window.dispatchEvent(new Event('resize'))}
function applyLayout(){for(const c of layout.custom){let e=document.querySelector('[data-edit-key53="'+c.id+'"]');if(!e){e=E('section',{'data-edit-key53':c.id,class:'customBlock53'},c.text);(c.page==='home'?$('annotationHome'):$('bottomDock')).append(e)}}for(const [key,v]of Object.entries(layout.blocks)){const e=key.startsWith('custom-')?document.querySelector('[data-edit-key53="'+key+'"]'):document.querySelector(key);if(!e)continue;e.hidden=!!v.hidden;if(v.text!==undefined&&!e.querySelector('button,input,select,canvas,img'))e.textContent=v.text;for(const p of ['fontSize','color','width','minHeight'])if(v[p])e.style[p]=v[p];e.style.maxWidth='100%';e.style.boxSizing='border-box';}const ordered=layout.order.map(key=>document.querySelector(key.startsWith('custom-')?'[data-edit-key53="'+key+'"]':key)).filter(Boolean);for(const parent of new Set(ordered.map(e=>e.parentElement))){const group=ordered.filter(e=>e.parentElement===parent),slots=[...parent.children].filter(e=>group.includes(e)).map(e=>{const mark=document.createComment('edit-slot');e.before(mark);return mark});group.forEach((e,i)=>slots[i].replaceWith(e))}}applyLayout();
function elements(){return [...targets.map(s=>document.querySelector(s)),...document.querySelectorAll('[data-edit-key53]')].filter(Boolean)}
function choose(el){selected=el;elements().forEach(e=>e.classList.toggle('editSelected53',e===el));renderBar()}
function change(p,v){if(!selected)return;const key=keyFor(selected);layout.blocks[key]||={};layout.blocks[key][p]=v;applyLayout();persistLayout()}
function renderBar(){bar?.remove();if(!editing)return;bar=E('aside',{id:'liveEditPanel53'});const title=E('strong',{},'实时编辑');bar.append(title);const add=(label,fn)=>U.button(bar,label,fn);add('完成',()=>toggle(false));add('新增文字',()=>{const id='custom-'+Date.now();layout.custom.push({id,text:'点击编辑这段文字',page:document.body.classList.contains('home-open')?'home':'writer'});applyLayout();persistLayout();choose(document.querySelector('[data-edit-key53="'+id+'"]'))});add('恢复布局',()=>{localStorage.removeItem(LS);location.reload()});if(selected){const leaf=!selected.querySelector('button,input,select,canvas,img');if(leaf){const input=E('textarea',{'aria-label':'编辑文字'});input.value=selected.textContent;input.oninput=()=>change('text',input.value);bar.append(input)}for(const [label,p,type,value]of [['字号','fontSize','number',parseFloat(getComputedStyle(selected).fontSize)],['宽度%','width','number',parseFloat(selected.style.width)||100],['高度','minHeight','number',parseFloat(selected.style.minHeight)||0]]){const l=E('label',{},label),i=E('input',{type,value,min:p==='fontSize'?10:0,max:p==='width'?100:600});i.oninput=()=>change(p,Math.max(p==='fontSize'?10:0,Math.min(p==='width'?100:600,+i.value))+(p==='width'?'%':'px'));l.append(i);bar.append(l)}const color=E('input',{type:'color','aria-label':'文字颜色',value:'#625543'});color.oninput=()=>change('color',color.value);bar.append(color);add('隐藏模块',()=>{change('hidden',true);selected=null;renderBar()});add('前移',()=>move(-1));add('后移',()=>move(1));const handle=E('button',{type:'button',class:'dragHandle53','aria-label':'拖动模块'},'☰ 拖动模块');handle.onpointerdown=e=>{handle.setPointerCapture(e.pointerId)};handle.onpointerup=e=>{const at=document.elementFromPoint(e.clientX,e.clientY);const dest=elements().find(el=>el===at||el.contains(at));if(dest&&dest!==selected&&dest.parentElement===selected.parentElement){dest.before(selected);saveOrder()}};bar.append(handle)}document.body.append(bar)}
function saveOrder(){layout.order=elements().sort((a,b)=>a.compareDocumentPosition(b)&Node.DOCUMENT_POSITION_FOLLOWING?-1:1).map(keyFor);persistLayout()}
function move(n){if(!selected)return;const candidates=elements().filter(e=>e.parentElement===selected.parentElement),i=candidates.indexOf(selected),dest=candidates[i+n];if(!dest)return;if(n<0)dest.before(selected);else dest.after(selected);saveOrder()}
function toggle(on){if(!U.isAdmin)return;editing=on;document.body.classList.toggle('editing53',editing);elements().forEach(e=>e.classList.toggle('editable53',editing));if(!on){selected=null;elements().forEach(e=>e.classList.remove('editSelected53'))}renderBar();window.dispatchEvent(new Event('resize'))}
document.addEventListener('click',e=>{if(!editing||e.target.closest('#liveEditPanel53,.liveEdit53,dialog'))return;const el=elements().find(el=>el===e.target||el.contains(e.target));if(el){e.preventDefault();e.stopImmediatePropagation();choose(el)}},true);
const editButtons=[];for(const parent of [document.querySelector('.annotationBrand'),$('topActions')]){const b=E('button',{type:'button',class:'liveEdit53',hidden:''},'实时编辑');b.onclick=()=>toggle(!editing);parent?.append(b);editButtons.push(b)}function showAdmin(){editButtons.forEach(b=>b.hidden=!U.isAdmin);if(!U.isAdmin&&editing){editing=false;bar?.remove();document.body.classList.remove('editing53');elements().forEach(e=>e.classList.remove('editable53','editSelected53'))}}document.addEventListener('admin-unlocked53',showAdmin);document.addEventListener('admin-locked53',showAdmin);showAdmin();
})();
