/* Version 82: horizontal scrolls, focused interactions, and on-page content controls. */
(function init(){if(!window.AnnotationApp?.ready||!window.Timeline73||!window.CopyAlbums38||!window.Revision62?.photoPanel||!window.DailyQuotes38){setTimeout(init,80);return}
 const $=id=>document.getElementById(id),A=AnnotationApp,home=$('annotationHome'),rail=$('inkTimeline73');
 // Only the first horizontal lane opens the public hall at its far edge.
 let firstTouch=null;rail.addEventListener('touchstart',e=>{const lane=e.target.closest('.timelineBranch76');firstTouch=lane===rail.querySelector('.timelineBranch76')?{x:e.touches[0].clientX,lane,atEnd:lane.scrollLeft+lane.clientWidth>=lane.scrollWidth-8}:null},{passive:true});rail.addEventListener('touchend',e=>{if(!firstTouch)return;const {x,lane,atEnd}=firstTouch;firstTouch=null;if(atEnd&&x-e.changedTouches[0].clientX>54&&lane.scrollLeft+lane.clientWidth>=lane.scrollWidth-14)window.InkCloud75?.showGallery?.().catch(err=>A.toast(err.message))},{passive:true});
 // The same history marks also act as small direct choices: write now or stamp a completed visit.
 let marker=null;document.addEventListener('click',e=>{const button=e.target.closest('.timelineMarks79 [data-mark="copy"]');if(!button)return;e.preventDefault();e.stopImmediatePropagation();marker?.remove();marker=document.createElement('div');marker.className='copyMark82';const write=document.createElement('button'),stamp=document.createElement('button');write.textContent='亲笔临写';stamp.textContent='阴刻 · 临写过了';marker.append(write,stamp);document.body.append(marker);const r=button.getBoundingClientRect();marker.style.left=Math.max(8,Math.min(innerWidth-marker.offsetWidth-8,r.left))+'px';marker.style.top=Math.min(innerHeight-marker.offsetHeight-8,r.bottom+5)+'px';const id=button.closest('.timelineCard73')?.dataset.id,c=Timeline73.chapters.find(x=>x.id===id);write.onclick=()=>{marker.remove();marker=null;if(c)Timeline73.openCopy(c).catch(err=>A.toast(err.message))};stamp.onclick=async()=>{try{if(!window.InkCloud75?.user){$('account47')?.click();return}await InkCloud75.mark(id,'copy');marker.remove();marker=null}catch(err){A.toast(err.message)}}},{capture:true});document.addEventListener('pointerdown',e=>{if(marker&&!e.target.closest('.copyMark82,.timelineMarks79 [data-mark="copy"]')){marker.remove();marker=null}},{capture:true});
 // Keep publishing choices together in a single compact row.
 const works=$('worksGrid');if(works){const align=()=>{for(const card of works.querySelectorAll('.workCard')){const cloud=card.querySelector('.cloudSave75'),feature=card.querySelector('.feature54');if(cloud&&feature&&feature.parentElement!==cloud)cloud.append(feature)}};new MutationObserver(align).observe(works,{childList:true,subtree:true});align()}
 // A user can intentionally enter copying from a facsimile cover; saved pages remain accessible.
 const originalViewer=$('copyAlbumViewer38');originalViewer?.addEventListener('close',()=>{const buttons=originalViewer.querySelectorAll('.musicActions button');buttons.forEach(b=>b.disabled=false)});
 // Preview image treatments are toggleable. Removing the photo also removes its old cover caption.
 const panel=Revision62.photoPanel,formats=panel.querySelectorAll('.photoLayouts62')[2];if(formats){for(const button of formats.querySelectorAll('button')){const original=button.onclick;button.onclick=e=>{const again=button.getAttribute('aria-pressed')==='true';for(const b of formats.querySelectorAll('button'))b.setAttribute('aria-pressed','false');if(again){window.previewComparison73=false;Revision62.clearOverlay();A.refresh();return}button.setAttribute('aria-pressed','true');original?.call(button,e)}}}
 $('removePhoto')?.addEventListener('click',()=>{formats?.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed','false'));window.previewComparison73=false;Revision62.clearOverlay()});
 // On iPad, a two-finger gesture resizes the long-scroll image in the preview; one finger still pans horizontally.
 const preview=$('rollPreview82'),scroller=preview?.querySelector('.rollScroll82'),image=scroller?.querySelector('img');if(scroller&&image){let start=0,base=0;scroller.addEventListener('touchstart',e=>{if(e.touches.length===2){start=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);base=image.getBoundingClientRect().height}},{passive:true});scroller.addEventListener('touchmove',e=>{if(e.touches.length!==2||!start)return;e.preventDefault();const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY),before=scroller.scrollWidth,ratio=(scroller.scrollLeft+scroller.clientWidth/2)/before;image.style.height=Math.max(180,Math.min(2200,base*d/start))+'px';scroller.scrollLeft=ratio*scroller.scrollWidth-scroller.clientWidth/2},{passive:false});scroller.addEventListener('touchend',e=>{if(e.touches.length<2)start=0})}
 // Administrative quote categories live next to the visible quote editor, including order and naming.
 document.addEventListener('front-quote-open82',e=>{const dialog=e.detail.dialog,panel=dialog.querySelector('.adminInner62');if(!panel)return;dialog.querySelector('details')?.setAttribute('open','');const manager=document.createElement('section');manager.className='quoteCategories82';manager.innerHTML='<h3>类别管理</h3><div class="categoryRows82"></div><div class="categoryAdd82"><input aria-label="新类别名称" placeholder="新增类别名称"><button type="button">增加类别</button></div><small role="status"></small>';panel.prepend(manager);const rows=manager.querySelector('.categoryRows82'),status=manager.querySelector('[role=status]'),input=manager.querySelector('input'),categorySelect=panel.querySelector('.adminRow62 select');function draw(){rows.replaceChildren();for(const b of $('quoteMenu').querySelectorAll('[data-quote-category]')){const id=b.dataset.quoteCategory,row=document.createElement('div'),name=document.createElement('input');row.className='categoryRow82';name.value=b.textContent.split(' · ')[0];name.setAttribute('aria-label',id+'类别名称');const save=document.createElement('button'),up=document.createElement('button'),down=document.createElement('button'),del=document.createElement('button');save.textContent='改名';up.textContent='↑';down.textContent='↓';del.textContent='×';save.onclick=()=>{try{DailyQuotes38.manageCategory(id,name.value);Revision62.registerCategory(id);if(categorySelect?.querySelector('[value="'+id+'"]'))categorySelect.querySelector('[value="'+id+'"]').textContent=name.value;status.textContent='已修改 '+name.value}catch(err){status.textContent=err.message}};up.onclick=()=>{DailyQuotes38.moveCategory(id,-1);draw()};down.onclick=()=>{DailyQuotes38.moveCategory(id,1);draw()};del.onclick=()=>{try{DailyQuotes38.manageCategory(id,'','remove');categorySelect?.querySelector('[value="'+id+'"]')?.remove();draw()}catch(err){status.textContent=err.message}};row.append(name,save,up,down,del);rows.append(row)}}manager.querySelector('.categoryAdd82 button').onclick=()=>{const label=input.value.trim();if(!label)return;const id='custom'+Date.now().toString(36);try{DailyQuotes38.manageCategory(id,label);Revision62.registerCategory(id);categorySelect?.append(new Option(label,id));categorySelect.value=id;categorySelect?.dispatchEvent(new Event('change'));input.value='';draw()}catch(err){status.textContent=err.message}};draw()});
 // Avoid iOS selection popups while writing. Inputs and deliberate editing remain usable.
 const editable=e=>e.target instanceof Element&&!!e.target.closest('input,textarea,select,[contenteditable="true"]');for(const type of ['contextmenu','selectstart','dragstart'])document.addEventListener(type,e=>{if(!document.body.classList.contains('home-open')&&!editable(e))e.preventDefault()},{capture:true});document.addEventListener('keydown',e=>{if(!document.body.classList.contains('home-open')&&!editable(e)&&(e.metaKey||e.ctrlKey)&&['c','x','a'].includes(e.key.toLowerCase()))e.preventDefault()},{capture:true});document.addEventListener('selectionchange',()=>{if(document.body.classList.contains('home-open')||editable({target:document.activeElement}))return;const selection=getSelection();if(selection?.rangeCount&&selection.anchorNode?.parentElement?.closest('#dailyDialog,#board'))selection.removeAllRanges()});
 const bookmark=$('dailyDialog');if(bookmark){const order=bookmark.querySelector('.bookmarkNav81 button:nth-child(2)');if(order){order.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h14l-3-3m3 3-3 3M20 17H6l3-3m-3 3 3 3"/></svg>';let random=false;order.onclick=()=>{random=!random;order.innerHTML=random?'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h3c6 0 6 12 12 12h3m-3-3 3 3-3 3M3 18h3c2 0 3-1 4-3m2-6c1-2 2-3 6-3h3m-3-3 3 3-3 3"/></svg>':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h14l-3-3m3 3-3 3M20 17H6l3-3m-3 3 3 3"/></svg>';order.setAttribute('aria-label',random?'随机':'顺序');document.dispatchEvent(new CustomEvent('bookmark-order82',{detail:{random}}))}}}
})();
