(function init112(){
 if(!window.Revision111?.ready){setTimeout(init112,40);return}
 const A=AnnotationApp,D=DailyQuotes38,$=id=>document.getElementById(id),category='user_input';let own=[],hydrating=false,saving=false;
 D.manageCategory(category,'用户录入');
 const dialog=document.createElement('dialog');dialog.id='userExcerpt112';dialog.setAttribute('aria-label','自己录入文摘');dialog.innerHTML='<header class="dialogHead"><h2>自己录入</h2><button type="button" data-close aria-label="关闭">×</button></header><form class="dialogBody"><p>默认归入“用户录入”，保存后直接打开浮窗，方便对照书写。</p><label>标题（选填）<input id="excerptTitle112" maxlength="80" placeholder="如：今天想写的一段话"></label><label>作者（选填）<input id="excerptAuthor112" maxlength="80" placeholder="默认：我"></label><label>正文<textarea id="excerptText112" rows="8" maxlength="30000" required placeholder="输入或粘贴文字，保留换行与分段"></textarea></label><p id="excerptStatus112" role="status"></p><button id="saveExcerpt112" type="submit" class="primary">保存并打开浮窗</button></form>';document.body.append(dialog);dialog.querySelector('[data-close]').onclick=()=>dialog.close();
 function hydrate(){if(hydrating||!own.length)return;const all=D.all(),missing=own.filter(q=>!all.some(x=>x.id===q.id));if(!missing.length)return;hydrating=true;try{D.setAll([...all,...missing])}finally{hydrating=false}}
 const ready=DraftStore.get('myQuotes').then(rows=>{own=(Array.isArray(rows)?rows:[]).filter(q=>q.cat===category);hydrate()}).catch(()=>{});
 document.addEventListener('quote-changed',hydrate);
 async function open(){await ready;const menu=$('excerptCategories91');if(menu)menu.hidden=true;$('topQuotes').setAttribute('aria-expanded','false');if($('dailyDialog').open)$('dailyDialog').close();$('excerptStatus112').textContent='';if(!dialog.open)dialog.showModal();$('excerptText112').focus()}
 dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();if(saving)return;const q=$('excerptText112').value.replace(/\r\n?/g,'\n').trim();if(!q){$('excerptStatus112').textContent='请先输入正文。';return}saving=true;$('saveExcerpt112').disabled=true;try{await ready;const existing=await DraftStore.get('myQuotes')||[],duplicate=existing.find(x=>x.cat===category&&x.q===q),title=$('excerptTitle112').value.trim()||q.split('\n')[0].slice(0,18),author=$('excerptAuthor112').value.trim()||'我',row=duplicate||{id:'user112-'+crypto.randomUUID(),cat:category,title,author,q,full:q,s:author+'《'+title+'》',source:author+'《'+title+'》',supplied:true,era:'用户录入',url:''};const merged=duplicate?existing:[...existing,row];await DraftStore.set('myQuotes',merged);own=merged.filter(x=>x.cat===category);hydrate();dialog.close();D.selectId(row.id);$('readQuote').click();$('readerJump90').hidden=true;$('readerTitle90').setAttribute('aria-expanded','false');$('excerptTitle112').value='';$('excerptAuthor112').value='';$('excerptText112').value='';A.toast('已存入用户录入，可对照浮窗书写')}catch{$('excerptStatus112').textContent='保存未完成，录入内容仍保留，请重试。'}finally{saving=false;$('saveExcerpt112').disabled=false}};
 // An empty personal category opens the editor rather than showing an unrelated text.
 document.addEventListener('click',e=>{const b=e.target.closest('[data-quote-category91="user_input"],[data-quote-category="user_input"]');if(b&&!D.all().some(q=>q.cat===category)){e.preventDefault();e.stopImmediatePropagation();open()}},true);
 window.UserExcerpts112={ready:true,open,hydrate};
})();
