/* Release 65: active writing preset, consistent seals and quiet writing surface. */
(function init(){if(!window.AnnotationApp?.ready||!window.InkStudio50?.ready||!window.WritingMusic||!document.getElementById('topMusic')){setTimeout(init,50);return}
const $=id=>document.getElementById(id),app=AnnotationApp;
// A home action always starts a new 创作 sheet, including when an old draft has ink.
const direct=$('continueWriting');direct.onclick=async()=>{const entry=InkStudio50.config.nav.find(n=>n.id==='letter');if(entry)await InkStudio50.applyMode(entry);else app.showWriter()};
// Persisted admin option labels from older releases must not restore obsolete vocabulary.
try{const key='iinnkk.optionLabels53',labels=JSON.parse(localStorage.getItem(key)||'{}');let changed=false;for(const [id,value] of [['headType','yin'],['headType','yang'],['tailType','yin'],['tailType','yang'],['extraSealType','yin'],['extraSealType','yang'],['selectedSealType','yin'],['selectedSealType','yang']]){const k=JSON.stringify([id,value]);if(k in labels){delete labels[k];changed=true}}if(changed)localStorage.setItem(key,JSON.stringify(labels))}catch{}
const names={yin:'阴刻',yang:'阳刻'};function sealLabels(){for(const id of ['headType','tailType','extraSealType','selectedSealType']){const select=$(id);if(!select)continue;for(const o of select.options)if(names[o.value])o.textContent=names[o.value]+(id==='headType'||id==='tailType'?(o.value==='yin'?' · 白文':' · 朱文'):'')}const font=$('sealFont');if(font?.value==='song'||font?.value==='regular')font.value='youlong'}sealLabels();
// No bundled copy of a restricted font: use a legitimate local installation or personal import.
if(!localStorage.getItem('iinnkk.sealDefault65')){for(const id of ['headFont','sealFont','extraSealFont'])if($(id))$(id).value='youlong';localStorage.setItem('iinnkk.sealDefault65','1');app.refresh()}
(async()=>{try{const face=new FontFace('YouLongSeal','local("字魂游龙篆书"), local("ZiHunYouLongZhuanShu")');await face.load();document.fonts.add(face);window.youLongSealReady=true;window.sealFontRevision=(window.sealFontRevision||0)+1;app.refresh();$('sealFont').dispatchEvent(new Event('input'))}catch{window.youLongSealReady=false}})();
document.fonts.load('180px ChongxiSeal','今日亲笔見墨如我').then(()=>{window.chongxiSealReady=true;window.sealFontRevision=(window.sealFontRevision||0)+1;app.refresh();$('sealFont').dispatchEvent(new Event('input'))}).catch(()=>{});
// A compact selector replaces the old button that silently cycled across tracks.
const music=$('topMusic'),picker=document.createElement('dialog');picker.id='musicPicker65';picker.setAttribute('aria-label','伴写声音');picker.innerHTML='<header><strong>伴写声音</strong><button type="button" class="closeMusic65" aria-label="关闭">×</button></header><div class="musicChoices65"></div>';document.body.append(picker);picker.querySelector('.closeMusic65').onclick=()=>picker.close();const choices=picker.querySelector('.musicChoices65'),select=$('writingTrack');for(const o of select.options){const b=document.createElement('button');b.type='button';b.textContent=o.textContent;b.dataset.music=o.value;b.onclick=()=>{WritingMusic.choose(o.value);picker.close()};choices.append(b)}const stop=document.createElement('button');stop.textContent='暂停声音';stop.onclick=()=>{WritingMusic.pause();picker.close()};choices.append(stop);music.onclick=()=>{for(const b of choices.querySelectorAll('[data-music]'))b.classList.toggle('active',b.dataset.music===select.value);picker.showModal()};music.title=music.ariaLabel='伴写声音 · 选择曲目';
// Long press and double tap on the canvas should not invoke iOS's text selection overlay.
const board=$('board');for(const event of ['selectstart','contextmenu','dragstart'])board.addEventListener(event,e=>{if(!e.target.closest('input,textarea,[contenteditable="true"]'))e.preventDefault()});document.addEventListener('selectionchange',()=>{if(document.body.classList.contains('home-open'))return;const a=document.activeElement;if(a?.matches('input,textarea,[contenteditable="true"]'))return;const selection=getSelection();if(selection?.rangeCount&&board.contains(selection.anchorNode))selection.removeAllRanges()});
})();
