/* 第62版：本机后台内容管理、扩纸字、临帖组图与图文创作。 */
(function init(){if(!window.InkStudio50?.ready||!window.DailyQuotes38?.setAll||!window.CopyAlbums38||!window.AnnotationApp?.ready){setTimeout(init,50);return}
const $=id=>document.getElementById(id),U=InkStudio50,A=AnnotationApp,E=U.E;
const safe=(v,n=30000)=>String(v||'').trim().slice(0,n),clone=x=>structuredClone(x);
let quoteRows=DailyQuotes38.all(),presets=[],photoPresets=[],photoLoadBusy=false,settings={defaultCategory:'moon',order:'sequence',preview:['书风','墨迹','纸色','线条','纹样','框架','流变','图文配置']};
const allowed=new Set([...document.querySelectorAll('[data-quote-category]')].map(e=>e.dataset.quoteCategory));
function load(){Promise.all([DraftStore.get('quotes62'),DraftStore.get('reference62'),DraftStore.get('settings62'),DraftStore.get('photoPresets62')]).then(([rows,p,s,photos])=>{if(Array.isArray(rows)){quoteRows=rows;DailyQuotes38.setAll(quoteRows)}if(Array.isArray(p))presets=p;if(Array.isArray(photos))photoPresets=photos;if(s)settings={...settings,...s};localStorage.setItem('iinnkk.quoteDefault62',settings.defaultCategory);localStorage.setItem('iinnkk.quoteOrder62',settings.order);DailyQuotes38.select(settings.defaultCategory);registerDates();syncPreview();renderPhotoPresets()}).catch(e=>console.warn('62 内容库读取失败',e))}load();
async function saveQuotes(){if(!U.isAdmin)throw Error('请先进入本机管理');if(quoteRows.length>2500)throw Error('条目最多2500条');await DraftStore.set('quotes62',quoteRows);DailyQuotes38.setAll(quoteRows);registerDates()}
function registerDates(){for(const row of quoteRows)for(const [date,type] of [[row.birth,'诞辰'],[row.death,'逝世纪念']])if(date&&/^\d{2}-\d{2}$/.test(date))window.Moments?.addVerified(date,row.author+type,'选一段《'+(row.title||'作品')+'》，亲笔纪念'+row.author)}
function quoteForm(host){const wrap=E('details',{class:'adminSection62'}),head=E('summary',{},'好词好句 · 批量编辑'),panel=E('div',{class:'adminInner62'});wrap.append(head,panel);let filtered=[];const cat=E('select'),order=E('select'),query=E('input',{type:'search',placeholder:'搜索作者、国别、作品与正文','aria-label':'搜索词句'}),list=E('div',{class:'quoteList62'}),state=E('small',{role:'status'});
for(const key of allowed)cat.append(E('option',{value:key},document.querySelector('[data-quote-category="'+key+'"]')?.textContent.split(' · ')[0]||key));cat.value=settings.defaultCategory;for(const [key,title] of [['sequence','按顺序'],['random','随机且避免重复']])order.append(E('option',{value:key},title));order.value=settings.order;
const controls=E('div',{class:'adminRow62'});controls.append(E('label',{},'默认类别 '),cat,E('label',{},'显示方式 '),order,query);panel.append(controls,list);
const actions=E('div',{class:'adminRow62'}),add=E('button',{type:'button'},'新增条目'),batch=E('button',{type:'button'},'批量导入 / 替换'),exportButton=E('button',{type:'button'},'导出句库 JSON');actions.append(add,batch,exportButton,state);panel.append(actions);host.append(wrap);
cat.onchange=async()=>{settings.defaultCategory=cat.value;localStorage.setItem('iinnkk.quoteDefault62',cat.value);await DraftStore.set('settings62',settings);DailyQuotes38.select(cat.value);draw()};order.onchange=async()=>{settings.order=order.value;localStorage.setItem('iinnkk.quoteOrder62',order.value);await DraftStore.set('settings62',settings);DailyQuotes38.refresh()};query.oninput=draw;
function editor(index){const row=quoteRows[index],d=E('dialog',{class:'adminDialog62'}),h=E('header',{class:'dialogHead'},'修订词句'),body=E('div',{class:'dialogBody'}),fields={};for(const [key,name] of [['cat','类别'],['author','作者'],['country','国别'],['title','作品名'],['birth','诞辰（月-日）'],['death','逝世纪念（月-日）'],['q','完整正文'],['url','出处网址']]){const label=E('label',{},name),input=key==='q'?E('textarea',{rows:'9'}):key==='cat'?E('select'):E('input',{type:'text'});if(key==='cat')for(const x of allowed)input.append(E('option',{value:x},x));input.value=row[key]||'';label.append(input);fields[key]=input;body.append(label)}const buttons=E('div',{class:'adminRow62'}),save=E('button',{type:'button'},'保存'),del=E('button',{type:'button'},'删除条目'),cancel=E('button',{type:'button'},'返回');buttons.append(save,del,cancel);body.append(buttons);d.append(h,body);document.body.append(d);d.showModal();cancel.onclick=()=>{if(row.id?.startsWith('admin62:')&&!row.q)quoteRows=quoteRows.filter(x=>x!==row);d.close();d.remove()};save.onclick=async()=>{const next={...row,...Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,safe(v.value,k==='q'?30000:200)]))};if(!next.q||!next.author||!next.title||!next.country||!allowed.has(next.cat)||[next.birth,next.death].some(x=>x&&!/^\d{2}-\d{2}$/.test(x))){state.textContent='请填写正文、作者、国别及作品名';return}next.s=next.author+'《'+next.title+'》';next.source=next.s;quoteRows[index]=next;try{await saveQuotes();d.close();d.remove();draw()}catch(e){state.textContent=e.message}};del.onclick=async()=>{quoteRows.splice(index,1);await saveQuotes();d.close();d.remove();draw()}}
function draw(){list.replaceChildren();const q=query.value.trim().toLowerCase();filtered=quoteRows.map((r,i)=>({...r,index:i})).filter(r=>r.cat===cat.value&&(!q||[r.q,r.author,r.country,r.title,r.s].some(x=>String(x||'').toLowerCase().includes(q))));for(const row of filtered.slice(0,80)){const button=E('button',{type:'button',class:'quoteRow62'},(row.author||row.s?.split('《')[0]||'作者待补')+' · '+(row.country||'国别待补')+' · '+(row.title||row.s?.match(/《([^》]+)/)?.[1]||'作品待补')+'\n'+safe(row.q,85));button.onclick=()=>editor(row.index);list.append(button)}state.textContent='本类 '+filtered.length+' 条 · 当前显示前80条'}draw();
add.onclick=()=>{const row={id:'admin62:'+crypto.randomUUID(),cat:cat.value,q:'',author:'',country:'',title:'',s:'',source:'',url:''};quoteRows.unshift(row);editor(0)};
batch.onclick=()=>{const d=E('dialog',{class:'adminDialog62'}),body=E('div',{class:'dialogBody'}),help=E('p',{},'每行：作者 | 国别 | 作品名 | 正文；也可粘贴含 cat、author、country、title、q 的 JSON 数组。只添加新行；“替换当前类别”会先清空该类别。'),area=E('textarea',{rows:'12',placeholder:'鲁迅 | 中国 | 野草 | 希望本是无所谓有，无所谓无的。'}),append=E('button',{type:'button'},'批量增加'),replace=E('button',{type:'button'},'替换当前类别'),close=E('button',{type:'button'},'返回'),status=E('p',{role:'status'});body.append(help,area,append,replace,close,status);d.append(body);document.body.append(d);d.showModal();close.onclick=()=>{d.close();d.remove()};async function submit(replacing){try{const raw=area.value.trim(),parsed=raw.startsWith('[')?JSON.parse(raw):raw.split(/\r?\n/).filter(Boolean).map(line=>{const [author,country,title,...q]=line.split('|');return{author,country,title,q:q.join('|')}});if(!Array.isArray(parsed)||parsed.length>1000||!parsed.length)throw Error('请提供1到1000条');const rows=parsed.map((r,i)=>{const author=safe(r.author,100),country=safe(r.country,50),title=safe(r.title,120),q=safe(r.q);if(!author||!country||!title||!q)throw Error('第'+(i+1)+'行缺少必填字段');return{id:'admin62:'+crypto.randomUUID(),cat:allowed.has(r.cat)?r.cat:cat.value,author,country,title,q,s:author+'《'+title+'》',source:author+'《'+title+'》',url:safe(r.url,500)}});if(replacing)quoteRows=quoteRows.filter(r=>r.cat!==cat.value);quoteRows.push(...rows);await saveQuotes();d.close();d.remove();draw()}catch(e){status.textContent=e.message||'导入失败'}}append.onclick=()=>submit(false);replace.onclick=()=>submit(true)};
exportButton.onclick=()=>{const a=E('a',{download:'iinnkk-quotes62.json',href:URL.createObjectURL(new Blob([JSON.stringify(quoteRows,null,2)],{type:'application/json'}))});a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000)};
}
// A gallery entry stores a page group as Blobs in IndexedDB and can become the default copy model.
function galleryForm(host){const details=E('details',{class:'adminSection62'}),panel=E('div',{class:'adminInner62'}),title=E('input',{type:'text',placeholder:'帖名 / 作者 / 年代'}),input=E('input',{type:'file',accept:'image/jpeg,image/png,image/webp',multiple:''}),save=E('button',{type:'button'},'批量上传组图'),list=E('div'),status=E('small',{role:'status'});details.append(E('summary',{},'临帖 · 组图与默认推荐'),panel);panel.append(title,input,save,status,list);host.append(details);
function paint(){list.replaceChildren();for(const item of presets){const row=E('div',{class:'adminRow62'}),name=E('span',{},item.title+' · '+item.pages.length+'张'),choose=E('button',{type:'button'},item.default?'默认进入 ✓':'设为默认'),remove=E('button',{type:'button'},'删除');choose.onclick=async()=>{presets.forEach(x=>x.default=x.id===item.id);await DraftStore.set('reference62',presets);paint()};remove.onclick=async()=>{presets=presets.filter(x=>x.id!==item.id);await DraftStore.set('reference62',presets);paint()};row.append(name,choose,remove);list.append(row)}}paint();
save.onclick=async()=>{if(!U.isAdmin||!input.files.length)return;const files=[...input.files];if(files.length>60||files.some(f=>f.size>20e6)){status.textContent='最多60张，每张小于20MB';return}try{const pages=files.map(f=>({name:f.name,image:f,workIds:[]})),item={id:'admin62:'+crypto.randomUUID(),title:safe(title.value,100)||files[0].name,pages,default:!presets.some(p=>p.default)};presets.unshift(item);await DraftStore.set('reference62',presets);input.value='';paint();status.textContent='组图已保存到本机，可以从临帖入口继续临写'}catch(e){presets.shift();status.textContent='本机空间不足，组图未保存'}};
}
async function defaultCopy(){const item=presets.find(p=>p.default);if(!item)return false;await CopyAlbums38.openPages55({id:item.id,title:item.title,pages:item.pages});A.showWriter();return true}
function hookCopy(){for(const parent of [document.getElementById('homeQuick47'),document.getElementById('writerModes53')]){const button=[...(parent?.querySelectorAll('button')||[])].find(x=>x.textContent.trim()==='临帖');if(button&&!button.dataset.copy62){button.dataset.copy62='yes';button.addEventListener('click',async e=>{if(!presets.some(p=>p.default))return;e.stopImmediatePropagation();e.preventDefault();try{await defaultCopy()}catch(err){A.toast('推荐原帖打开失败，请在后台重试上传')}} ,true)}}}
hookCopy();document.addEventListener('studio-config50',hookCopy);
function nav62(){const buttons=[...(document.querySelectorAll('#homeQuick47 button'))],single=buttons.find(b=>b.textContent==='单字'||b.textContent==='大字'),copy=buttons.find(b=>b.textContent==='临帖'),creative=buttons.find(b=>b.textContent==='创作');if(single)single.textContent='大字';if(copy&&creative){let photo=buttons.find(b=>b.textContent==='图文');if(!photo){photo=E('button',{type:'button'},'图文');creative.before(photo)}photo.onclick=()=>U.applyMode(U.config.nav.find(n=>n.id==='photo')||{...U.config.nav.find(n=>n.id==='letter'),id:'photo',title:'图文'}).catch(U.report)}const nav=U.config.nav;if(!nav.some(n=>n.id==='photo')&&U.isAdmin){const c=U.config;c.nav.splice(c.nav.findIndex(n=>n.id==='letter'),0,{...c.nav.find(n=>n.id==='letter'),id:'photo',title:'图文'});U.saveConfig(c)}}nav62();document.addEventListener('admin-unlocked53',nav62);
let currentMode='';document.addEventListener('mode-changed54',e=>{currentMode=e.detail.id;if(currentMode==='photo'){const mode=$('photoMode');mode.value='editorial';mode.dispatchEvent(new Event('change'));A.addPhotos&&!photoLoadBusy&&A.getState()?.photos?.length===0&&(photoLoadBusy=true,fetch('annotations/marble.webp?v=62').then(r=>r.blob()).then(blob=>A.addPhotos([new File([blob],'书写与影像.webp',{type:'image/webp'})])).catch(()=>{}).finally(()=>photoLoadBusy=false));}if(currentMode==='single')bigButtons.hidden=false;else bigButtons.hidden=true;setTimeout(()=>{if(currentMode==='photo')DailyQuotes38.select(settings.defaultCategory)},20)});
const bigButtons=E('div',{id:'bigPaper62',hidden:''}),add=E('button',{type:'button'},'＋ 加纸加字'),info=E('span',{},'单字 · 米字格');bigButtons.append(add,info);document.getElementById('board')?.parentElement.append(bigButtons);
let big={dir:'vertical',rows:1,cols:1};const dialog=E('dialog',{id:'bigDialog62',class:'adminDialog62'}),dbody=E('div',{class:'dialogBody'}),dir=E('select'),count=E('input',{type:'number',min:'1',max:'7',value:'2'}),bands=E('input',{type:'number',min:'1',max:'7',value:'1'}),apply=E('button',{type:'button'},'扩展纸张'),back=E('button',{type:'button'},'返回');for(const [value,label] of [['horizontal','横批 · 从右到左'],['vertical','竖幅 · 从上向下']])dir.append(E('option',{value},label));dbody.append(E('h2',{},'大字 · 加纸加字'),E('label',{},'书写方向'),dir,E('label',{},'每行/列字数'),count,E('label',{},'行/列数量'),bands,apply,back);dialog.append(dbody);document.body.append(dialog);add.onclick=()=>dialog.showModal();back.onclick=()=>dialog.close();apply.onclick=async()=>{const n=Math.max(1,Math.min(7,+count.value||1)),b=Math.max(1,Math.min(7,+bands.value||1)),vertical=dir.value==='vertical';big={dir:dir.value,rows:vertical?n:b,cols:vertical?b:n};const ratio=Math.max(.25,Math.min(5,(vertical?b:n)/(vertical?n:b)));await A.configure47({values:{ratio:String(ratio),followDirection:vertical?'vertical':'horizontal',rows:String(big.rows),columns:String(big.cols),letterLayout:'custom',ruling:'mi',showLines:'yes',paperExtent:'fixed'},focus:'start'});info.textContent=(vertical?'竖幅':'横批')+' · '+n+'字 × '+b+(vertical?'列':'行');dialog.close();A.showWriter()};
// Existing photo tools remain authoritative. Full-paper preview exposes them without leaving preview.
const photoPanel=E('section',{id:'photoPanel62'}),photoTitle=E('strong',{},'图文配置 · 在画面中重组影像与亲笔'),photoFile=E('input',{type:'file',accept:'image/*',multiple:''}),layout=E('div',{class:'photoLayouts62'}),overlay=E('div',{class:'photoLayouts62'}),remove=E('button',{type:'button'},'移除当前图片'),status=E('small',{role:'status'},'轻点画中图片可调整、交换或移除。');const recommended=E('div',{class:'photoLayouts62'});photoPanel.append(photoTitle,photoFile,recommended,layout,overlay,remove,status);$('previewEffects55')?.insertBefore(photoPanel,$('previewEffects55').querySelector('.previewActions56'));photoFile.onchange=()=>{A.addPhotos([...photoFile.files]).catch(()=>status.textContent='图片导入失败，请重试')};remove.onclick=()=>$('removePhoto')?.click();for(const opt of $('photoMode').options){const b=E('button',{type:'button'},opt.textContent);b.dataset.layout=opt.value;b.onclick=()=>{ $('photoMode').value=opt.value;$('photoMode').dispatchEvent(new Event('change',{bubbles:true}));updateLayout()};layout.append(b)}function updateLayout(){layout.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.layout===$('photoMode').value)))}updateLayout();
const overlayInput=E('input',{type:'text',placeholder:'自定文化元素标题，如：一张写给世界的明信片',maxlength:'45'});overlayInput.oninput=()=>{overlayTitle=safe(overlayInput.value,45);A.refresh()};photoPanel.append(overlayInput);for(const [name,layoutKey] of [['明信片','postcard'],['世界遗产','gallery'],['电影海报','cover'],['音乐专辑封面','polaroid'],['书籍封面','editorial']]){const b=E('button',{type:'button'},name);b.onclick=()=>{ $('photoMode').value=layoutKey;$('photoMode').dispatchEvent(new Event('change'));overlayInput.value=name;overlayTitle=name;status.textContent=name+'排版已套用，可继续上传、交换图片与书写';updateLayout();A.refresh()};overlay.append(b)}
function renderPhotoPresets(){recommended.replaceChildren();for(const p of photoPresets){const b=E('button',{type:'button'},p.title);b.onclick=()=>A.addPhotos([p.image]).catch(()=>status.textContent='推荐图片打开失败');recommended.append(b)}}
function previewAdmin(host){const d=E('details',{class:'adminSection62'}),inner=E('div',{class:'adminInner62'}),order=E('div');d.append(E('summary',{},'全纸预览 · 选项增删排序'),inner);inner.append(E('p',{},'可拖动选项顺序、隐藏功能；上传的图片会成为前台图文预设。'),order);const imgTitle=E('input',{type:'text',placeholder:'图片名称'}),imgFile=E('input',{type:'file',accept:'image/jpeg,image/png,image/webp',multiple:''}),imgSave=E('button',{type:'button'},'上传推荐图片'),imgList=E('div',{class:'adminRow62'});imgSave.onclick=async()=>{if(!U.isAdmin)return;const files=[...imgFile.files];if(files.length>20||files.some(f=>f.size>15e6)){imgSave.textContent='最多20张，每张小于15MB';return}const next=files.map((f,i)=>({id:crypto.randomUUID(),title:safe(imgTitle.value,50)||f.name,image:f}));photoPresets.push(...next);await DraftStore.set('photoPresets62',photoPresets);renderPhotoPresets();renderImages()};function renderImages(){imgList.replaceChildren();for(const p of photoPresets){const row=E('span',{},p.title+' '),remove=E('button',{type:'button'},'×');remove.onclick=async()=>{photoPresets=photoPresets.filter(x=>x.id!==p.id);await DraftStore.set('photoPresets62',photoPresets);renderImages();renderPhotoPresets()};row.append(remove);imgList.append(row)}}renderImages();inner.append(imgTitle,imgFile,imgSave,imgList);function paint(){order.replaceChildren();for(const name of settings.preview){const row=E('div',{class:'adminRow62',draggable:'true'}),label=E('span',{},'☰ '+name),remove=E('button',{type:'button'},'移除');row.append(label,remove);remove.onclick=async()=>{settings.preview=settings.preview.filter(n=>n!==name);await DraftStore.set('settings62',settings);paint();syncPreview()};row.ondragstart=e=>e.dataTransfer.setData('text/plain',name);row.ondragover=e=>e.preventDefault();row.ondrop=async e=>{e.preventDefault();const n=e.dataTransfer.getData('text/plain'),a=settings.preview,i=a.indexOf(n),j=a.indexOf(name);if(i<0||j<0)return;a.splice(j,0,a.splice(i,1)[0]);await DraftStore.set('settings62',settings);paint();syncPreview()};order.append(row)}}paint();const choose=E('select');for(const key of ['书风','墨迹','纸色','线条','纹样','框架','流变','图文配置'])choose.append(E('option',{value:key},key));const add=E('button',{type:'button'},'恢复选项');add.onclick=async()=>{if(!settings.preview.includes(choose.value))settings.preview.push(choose.value);await DraftStore.set('settings62',settings);paint();syncPreview()};inner.append(choose,add);host.append(d)}function syncPreview(){const tabs=[...$('previewEffects55').querySelectorAll('.finalSteps54 button')];for(const tab of tabs){if(tab.textContent==='文创预览'||tab.textContent==='圈选局部')continue;tab.hidden=!settings.preview.includes(tab.textContent)}const step=tabs[0]?.parentElement;if(step)for(const key of settings.preview){const button=tabs.find(b=>b.textContent===key);if(button)step.append(button)}photoPanel.hidden=!settings.preview.includes('图文配置')}
function setupAdmin(e){if(!U.isAdmin)return;quoteForm(e.detail.body);galleryForm(e.detail.body);previewAdmin(e.detail.body)}document.addEventListener('admin-panel53',setupAdmin);
// Country labels are metadata, not guesses. Palette order varies only among accessible contrasts.
const colorSets={'法国':['#183d74','#fffaf0','#bc3037'],'中国':['#852c2b','#f5dfa3','#dfb759'],'美国':['#a52b36','#fffaf0','#214673'],'英国':['#213d68','#fffaf0','#bb3038'],'日本':['#f4f2eb','#242a30','#bc3241'],'俄罗斯':['#273e78','#fffaf0','#af343f'],'德国':['#262528','#f6d06e','#be3535'],'印度':['#276d4d','#fffaf0','#e9813c'],'爱尔兰':['#257454','#fffaf0','#e68f42'],'智利':['#245085','#fffaf0','#c52b39'],'哥伦比亚':['#e8bf3c','#193e79','#b83036'],'波兰':['#f6f3ed','#31343a','#bd3145'],'西班牙':['#af3232','#f4d369','#7d242a'],'捷克':['#f4f3ec','#164d89','#b83142'],'黎巴嫩':['#f3eee4','#2c6239','#bd3643']};const luminance=hex=>{const x=hex.match(/[a-f\d]{2}/gi).map(v=>parseInt(v,16)/255).map(c=>c<=.04045?c/12.92:((c+.055)/1.055)**2.4);return .2126*x[0]+.7152*x[1]+.0722*x[2]};let lastPalette=null,overlayTitle='';document.addEventListener('quote-changed',e=>{const q=e.detail;if(q.cat!=='literature'){lastPalette=null;return;}const author=q.author||String(q.s||'').split('《')[0].trim(),title=q.title||String(q.s||'').match(/《([^》]+)》/)?.[1]||'作品未署名',country=q.country||window.LiteraryCountries61?.[author];$('quoteSource').textContent='文学佳句 · '+author+'《'+title+'》 · '+(country||'请补充国别');if(!country||!colorSets[country])return;const colors=colorSets[country],choices=[];for(let p=0;p<3;p++)for(let i=0;i<3;i++)if(i!==p){const ratio=(Math.max(luminance(colors[p]),luminance(colors[i]))+.05)/(Math.min(luminance(colors[p]),luminance(colors[i]))+.05);if(ratio>=4.5)choices.push({paper:colors[p],ink:colors[i],seal:colors[3-p-i]})}if(!choices.length)return;const chosen=choices[Math.floor(Math.random()*choices.length)];lastPalette={...chosen,credit:country+'旗色 × '+author+'《'+title+'》 · 纸墨印章三色'};A.applyLiteraryPalette61?.(chosen)});
window.Revision62={getPalette:()=>lastPalette,getOverlay:()=>overlayTitle,getPresets:()=>presets,defaultCopy};
})();
