/* V84: create directories, move existing works, and browse the same albums in the cloud. */
(function init(){if(!window.AnnotationApp?.ready||!window.WorkAlbumModel84||!window.DraftStore||!window.Revision81){setTimeout(init,80);return}
 const $=id=>document.getElementById(id),A=AnnotationApp,M=WorkAlbumModel84,dialog=$('worksDialog'),grid=$('worksGrid');let data=M.normalize({}),selected='',loaded=false,loadedOwner='',syncing=null,refreshing=false,pending=false;
 const order=$('dailyDialog')?.querySelector('.bookmarkNav81 button:nth-child(2)');if(order){let random=false;const icons={repeat:'<path d="m17 3 4 4-4 4M3 11V9a2 2 0 0 1 2-2h16M7 21l-4-4 4-4m14 0v2a2 2 0 0 1-2 2H3"/>',shuffle:'<path d="M3 7h3c5 0 7 10 12 10h3m-3-3 3 3-3 3M3 17h3c2 0 3-1 4-3m3-4c1-2 3-3 5-3h3m-3-3 3 3-3 3"/>'};function paintOrder(){order.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true">'+icons[random?'shuffle':'repeat']+'</svg>';order.title=order.getAttribute('aria-label')||'';order.setAttribute('aria-label',random?'乱序随机，点击切换顺序循环':'顺序循环，点击切换乱序随机');order.title=order.getAttribute('aria-label');order.dataset.mode84=random?'shuffle':'repeat'}paintOrder();order.onclick=()=>{random=!random;paintOrder();document.dispatchEvent(new CustomEvent('bookmark-order82',{detail:{random}}))}}
 const toolbar=document.createElement('section');toolbar.className='albumToolbar84';toolbar.innerHTML='<div class="albumNavigation84"><select aria-label="作品专辑"></select><button type="button" data-action="new">新建专辑</button><button type="button" data-action="rename">改名</button><button type="button" data-action="remove">删除目录</button></div><div class="albumCreate84" hidden><input maxlength="36" aria-label="专辑名称" placeholder="专辑名称"><button type="button">保存</button><button type="button">×</button></div><small role="status"></small>';
 dialog.querySelector('.albumFilter81')?.remove();dialog.querySelector('.dialogBody').prepend(toolbar);const filter=toolbar.querySelector('select'),form=toolbar.querySelector('.albumCreate84'),input=form.querySelector('input'),status=toolbar.querySelector('[role=status]');let editing='new';
 function report(e){status.textContent=e?.message||String(e);A.toast(status.textContent)}
 async function load(sync=false){if(!loaded){data=M.normalize(await DraftStore.get('work-albums81'));loaded=true}const owner=window.InkCloud75?.user?.id||'';if(sync&&owner&&owner!==loadedOwner){if(syncing)return syncing;syncing=(async()=>{try{const previousOwner=await DraftStore.get('work-albums84-owner'),localUpdated=await DraftStore.get('work-albums84-updated')||0;if(previousOwner&&previousOwner!==owner){await DraftStore.set('work-albums84:'+previousOwner,{albums:data,updated:localUpdated});const own=await DraftStore.get('work-albums84:'+owner);data=M.normalize(own?.albums);await DraftStore.set('work-albums84-updated',own?.updated||0)}const remote=await InkCloud75.loadWorkAlbums(),updated=await DraftStore.get('work-albums84-updated')||0;if(remote&&remote.updated>=updated){data=M.normalize(remote.albums);await DraftStore.set('work-albums84-updated',remote.updated)}else if(Object.keys(data).length)await InkCloud75.saveWorkAlbums(data,updated||Date.now());await DraftStore.set('work-albums81',data);await DraftStore.set('work-albums84-owner',owner);loadedOwner=owner}catch(e){status.textContent='本机专辑可用；云端目录暂未读取：'+e.message}finally{syncing=null}})();await syncing}return data}
 async function save(next){data=M.normalize(next);const updated=Date.now();await DraftStore.set('work-albums81',data);await DraftStore.set('work-albums84-updated',updated);status.textContent='专辑已保存';if(window.InkCloud75?.user){try{await InkCloud75.saveWorkAlbums(data,updated);status.textContent='专辑已同步'}catch(e){status.textContent='本机已保存；云端同步未完成：'+e.message}}document.dispatchEvent(new Event('work-albums-updated84'));draw()}
 function options(select,current=''){select.replaceChildren(new Option('未分类',''),...Object.keys(data).map(name=>new Option(name,name)));select.value=Object.hasOwn(data,current)?current:''}
 function draw(){filter.replaceChildren(new Option('全部作品',''),new Option('未分类','@none'),...Object.keys(data).map(name=>new Option(name+' · '+data[name].length+'幅',name)));if(selected&&!Object.hasOwn(data,selected)&&selected!=='@none')selected='';filter.value=selected;for(const b of toolbar.querySelectorAll('[data-action=rename],[data-action=remove]'))b.disabled=!selected||selected==='@none';toolbar.querySelector('[data-action=new]').disabled=Object.keys(data).length>=100;for(const card of grid.querySelectorAll('.workCard[data-work-id]'))attach(card);grid.querySelectorAll('.albumCard38').forEach(card=>card.hidden=!!selected)}
 function renderLocal(){draw();$('worksSearch').dispatchEvent(new Event('input'))}
 async function refresh(){if(refreshing){pending=true;return}refreshing=true;try{await load();draw()}catch(e){report(e)}finally{refreshing=false;if(pending){pending=false;refresh()}}}
 function attach(card){let select=card.querySelector('.albumAssign84');if(!select){const row=document.createElement('label');row.className='albumPlacement84';row.textContent='专辑 ';select=document.createElement('select');select.className='albumAssign84';select.setAttribute('aria-label','将作品放入专辑');row.append(select);card.append(row);select.onchange=async()=>{try{await save(M.assign(data,[card.dataset.workId],select.value));renderLocal()}catch(e){report(e)}}}options(select,M.membership(data,card.dataset.workId))}
 filter.onchange=()=>{selected=filter.value;renderLocal()};function openForm(action){editing=action;form.hidden=false;input.value=action==='rename'?selected:'';input.focus()}
 toolbar.querySelector('[data-action=new]').onclick=()=>openForm('new');toolbar.querySelector('[data-action=rename]').onclick=()=>openForm('rename');toolbar.querySelector('[data-action=remove]').onclick=async()=>{const name=selected;if(!name||name==='@none')return;if(!confirm('删除目录“'+name+'”？作品会保留在未分类中。'))return;try{await save(M.remove(data,name));selected='';renderLocal()}catch(e){report(e)}};
 form.querySelector('button').onclick=async()=>{try{const name=input.value.trim(),next=editing==='rename'?M.rename(data,selected,name):M.create(data,name);await save(next);selected=name;form.hidden=true;renderLocal()}catch(e){report(e)}};form.querySelector('button:last-child').onclick=()=>form.hidden=true;input.onkeydown=e=>{if(e.key==='Enter')form.querySelector('button').click();if(e.key==='Escape')form.hidden=true};
 const batch=document.createElement('button');batch.id='batchAlbum84';batch.textContent='移入专辑';batch.hidden=true;$('workBatchTools').append(batch);batch.onclick=async()=>{const ids=A.selectedWorkIds?.()||[];if(!ids.length){A.toast('请先选中作品');return}const popup=document.createElement('dialog');popup.className='albumMove84';const select=document.createElement('select'),move=document.createElement('button'),close=document.createElement('button');options(select,selected);move.textContent='移入';close.textContent='取消';popup.append(select,move,close);document.body.append(popup);popup.showModal();close.onclick=()=>popup.close();popup.onclose=()=>popup.remove();move.onclick=async()=>{try{await save(M.assign(data,ids,select.value));popup.close();renderLocal()}catch(e){report(e)}}};new MutationObserver(()=>{batch.hidden=$('batchAll').hidden}).observe($('batchAll'),{attributes:true,attributeFilter:['hidden']});
 new MutationObserver(()=>refresh()).observe(grid,{childList:true});new MutationObserver(()=>{if(dialog.open)load(true).then(renderLocal).catch(report)}).observe(dialog,{attributes:true,attributeFilter:['open']});document.addEventListener('work-albums84',async()=>{await save(await DraftStore.get('work-albums81'));renderLocal()});document.addEventListener('cloud-user84',()=>{loadedOwner=''});
 window.WorkAlbums84={filterMeta:work=>!selected||(selected==='@none'?!M.membership(data,work.id):data[selected]?.includes(work.id)),get:()=>data,load,assign:async(id,name)=>save(M.assign(data,[id],name)),async enhanceCloudMine(host,works){await load(true);const selector=document.createElement('select');selector.className='cloudAlbumFilter84';selector.setAttribute('aria-label','按专辑浏览云端作品');selector.replaceChildren(new Option('全部专辑',''),new Option('未分类','@none'),...Object.keys(data).map(name=>new Option(name,name)));const manage=document.createElement('button');manage.textContent='管理专辑';manage.className='cloudAlbumManage84';manage.onclick=()=>{host.closest('dialog')?.close();$('myWorks').click()};host.querySelector('h3')?.after(selector,manage);const cards=[...host.querySelectorAll('.cloudWork75')];cards.forEach((card,index)=>{const id=works[index]?.local_id?.split('|').at(-1)||works[index]?.local_id;if(!id)return;const assign=document.createElement('select');assign.className='albumAssign84';assign.setAttribute('aria-label','将云端作品放入专辑');options(assign,M.membership(data,id));assign.onchange=async()=>{try{await save(M.assign(data,[id],assign.value));apply()}catch(e){report(e)}};card.append(assign)});function apply(){cards.forEach((card,index)=>{const id=works[index]?.local_id?.split('|').at(-1)||works[index]?.local_id;card.hidden=!!selector.value&&(selector.value==='@none'?!!M.membership(data,id):!data[selector.value]?.includes(id))})}selector.onchange=apply}};load().then(draw).catch(report);
})();
