(function init108(){
 if(!window.Revision107?.ready){setTimeout(init108,40);return}
 const A=AnnotationApp,$=id=>document.getElementById(id);document.body.classList.add('ui108');
 // Preserve full titles in a single, horizontally scrollable line.
 const title=$('readerTitle90');function fitTitle(){title.title=title.textContent;title.style.setProperty('font-size','12px','important');const reader=$('dailyDialog');if(reader.dataset.resized133==='true')return;const ctx=document.createElement('canvas').getContext('2d');ctx.font='12px system-ui';const measured=ctx.measureText(title.textContent).width;title.style.setProperty('font-size',Math.min(12,12*(innerWidth-82)/Math.max(1,measured))+'px','important');reader.style.setProperty('width',Math.min(innerWidth-12,Math.max(280,ctx.measureText(title.textContent).width+70))+'px','important')}
 new MutationObserver(fitTitle).observe(title,{childList:true,characterData:true,subtree:true});new ResizeObserver(fitTitle).observe(title);fitTitle();
 const readerText=$('quoteExpanded');function readerLayout(){const raw=readerText.textContent||'',lines=raw.split('\n'),out=[];for(const line of lines){if([...line.trim()].length===1&&out.length)out[out.length-1]+=line.trim();else out.push(line)}const clean=out.join('\n');if(clean!==raw)readerText.textContent=clean;const ctx=document.createElement('canvas').getContext('2d'),width=readerText.clientWidth;if(!width)return;let chosen=15;for(let size=15;size>=13;size-=.25){ctx.font=size+'px STKaiti,serif';let orphan=false;for(const line of out){let used=0,n=0;for(const ch of line){const w=ctx.measureText(ch).width;if(used+w>width){used=0;n=0}used+=w;n++}if(n===1&&line.length>1)orphan=true}if(!orphan){chosen=size;break}}readerText.style.setProperty('font-size',chosen+'px','important')}
 new MutationObserver(readerLayout).observe(readerText,{childList:true,characterData:true,subtree:true});new ResizeObserver(readerLayout).observe(readerText);readerLayout();
 function dialog(id,name){const d=document.createElement('dialog');d.id=id;d.innerHTML='<header class="dialogHead"><h2>'+name+'</h2><button type="button" aria-label="关闭">×</button></header><div class="dialogBody"></div>';document.body.append(d);d.querySelector('button').onclick=()=>d.close();return d}
 function slider(host,name,id,value,max,onChange,points){const label=document.createElement('label');label.className='field108';label.textContent=name;const range=document.createElement('input');range.type='range';range.dataset.slider100='yes';range.dataset.stepper63='yes';range.id=id;range.min='1';range.max=String(max);range.step='1';range.value=value;range.setAttribute('aria-label',name);const output=document.createElement('output');output.textContent=value;range.oninput=()=>{output.textContent=range.value;onChange(+range.value)};label.append(output,range);host.append(label);const row=document.createElement('div');row.className='points108';for(const n of points||[1,2,3,5,7,10]){const b=document.createElement('button');b.type='button';b.textContent=n;b.onclick=()=>{range.value=n;range.dispatchEvent(new Event('input',{bubbles:true}))};row.append(b)}label.append(row);return range}
 // The top line tool adjusts stroke optimisation, independent of paper grid lines.
 const line=dialog('lineDialog108','线条优化'),lineBody=line.querySelector('.dialogBody'),toggle=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.id='lineAssist108';toggle.className='choice108';toggle.append(check,document.createTextNode('开启线条优化'));lineBody.append(toggle);check.onchange=()=>{$('inkMode').value=check.checked?'assist':'raw';$('inkMode').dispatchEvent(new Event('change',{bubbles:true}));A.persist()};const speed=slider(lineBody,'综合书风','lineStrength108',A.getState().brush.lineStrength108??50,100,v=>{A.setLineProfile108(v);describeLine(v)},[0,25,50,75,100]);speed.min='0';const stage=document.createElement('strong');stage.className='lineStage108';const tip=document.createElement('small');tip.textContent='一条滑轨联动提按、平滑、柔软、收锋和速度；同步调整当前作品，并保留每笔原有笔径。';lineBody.append(stage,tip);function describeLine(v){const names=['圆厚朴拙','沉着劲健','提按分明','柔韧流畅','飞动尖锋'];stage.textContent=names[Math.min(4,Math.floor((+v+12.5)/25))]+' · '+v;speed.parentElement.querySelector('output').textContent=v}describeLine(speed.value);
 $('topLines').onclick=()=>{check.checked=$('inkMode').value==='assist';speed.value=A.getState().brush.lineStrength108??50;describeLine(speed.value);$('lineStrength108Number').value=speed.value;line.showModal()};
 // Consistent expansion form: each field owns its slider and quick values.
 const big=$('bigDialog62'),body=big.querySelector('.dialogBody'),heading=body.querySelector('h2'),presets=body.querySelector('.presets107'),direction=body.querySelector('select'),count=$('bigCount107'),bands=$('bigBands107'),buttons=[...body.querySelectorAll(':scope>button')];
 function wrapField(name,control){const label=document.createElement('label');label.className='field108';label.textContent=name;const extras=[];let n=control.nextElementSibling;while(n&&n.matches('.rangePoints100,.adjust103')){extras.push(n);n=n.nextElementSibling}for(const extra of extras)if(extra.matches('.rangePoints100')&&extra.querySelector('output'))label.append(extra.querySelector('output'));label.append(control,...extras.filter(e=>!e.matches('.rangePoints100')));if(control.type==='range'){const points=document.createElement('div');points.className='points108';for(const n of [1,2,3,5,7,10]){const b=document.createElement('button');b.type='button';b.textContent=n;b.onclick=()=>{control.value=n;control.dispatchEvent(new Event('input',{bubbles:true}))};points.append(b)}label.append(points)}return label}
 const fields=document.createElement('div');fields.className='fields108';fields.append(wrapField('书写方向',direction),wrapField('每行 / 每列字数',count),wrapField('行 / 列数量',bands));const foot=document.createElement('footer');foot.className='actions108';foot.append(...buttons);body.replaceChildren(heading,presets,fields,foot);
 // Grid quantities stay on the same paper without rescaling existing ink.
 const grid=dialog('gridDialog108','格线 · 行列字格'),gb=grid.querySelector('.dialogBody');const gridType=document.createElement('label');gridType.className='field108';gridType.textContent='格线样式';const select=document.createElement('select');for(const [name,value]of [['无格线','none'],['竖线','vertical'],['横线','horizontal'],['米字格','mi'],['回宫格','hui'],['米字叠回宫','mi-hui']])select.append(new Option(name,value));gridType.append(select);gb.append(gridType);select.onchange=()=>{$('ruling').value=select.value;$('showLines').value=select.value==='none'?'no':'yes';A.refreshPaper();A.persist()};let rows,cols,chars,cells;let busy=false;
 function syncGrid(){busy=true;for(const [r,id]of [[rows,'rows'],[cols,'columns']]){r.max=String(Math.max(+r.max,+$(id).value));r.value=$(id).value}const total=+rows.value* +cols.value;for(const r of [chars,cells]){r.max=String(Math.max(+r.max,total));r.value=total};for(const r of [rows,cols,chars,cells])r.parentElement.querySelector('output').textContent=r.value;busy=false}
 function updateGrid(key,v){if(busy)return;if(key==='rows'||key==='columns'){$(key).max=String(Math.max(1000,v*2));$(key).value=v}else{const n=Math.ceil(v/Math.max(1,+$('columns').value));$('rows').max=String(Math.max(10000,n));$('rows').value=n}$('letterLayout').value='custom';A.refreshPaper();A.persist();syncGrid()}
 rows=slider(gb,'行数','gridRows108',1,1000,v=>updateGrid('rows',v));cols=slider(gb,'列数','gridCols108',1,1000,v=>updateGrid('columns',v));chars=slider(gb,'字数','gridChars108',1,10000,v=>updateGrid('total',v),[1,2,3,4,5,7,10,16]);cells=slider(gb,'格数','gridCells108',1,10000,v=>updateGrid('total',v),[1,2,4,9,16,25]);const note=document.createElement('small');note.textContent='字数与格数按当前列数补齐整行；改行列不改变已有笔迹。';gb.append(note);
 const tabs=$('previewEffects55').querySelector('.finalSteps54');const gridTab=[...tabs.children].find(b=>b.textContent.trim()==='格线'),oldGrid=gridTab.onclick;gridTab.onclick=()=>{oldGrid.call(gridTab);const rail=$('previewEffects55').querySelector('.finalRail54'),b=document.createElement('button');b.id='gridCounts108';b.textContent='行列字格';b.onclick=()=>{syncGrid();select.value=$('showLines').value==='no'?'none':$('ruling').value;grid.showModal()};rail.append(b)};
 // Photo contours are shared by live paper, editor mask, saved drafts and export.
 const aspect=$('photoAspect');aspect.setAttribute('aria-label','调整轮廓');aspect.replaceChildren(new Option('调整轮廓',''),...[['正方形','square'],['长方形','rectangle'],['圆形','circle'],['折扇形','fan'],['团窗形','window']].map(([n,v])=>new Option(n,v)));
 // Group existing work actions without replacing their handlers or cloud controls.
 function workLayout(){for(const card of document.querySelectorAll('.workCard,.cloudWork75')){let holder=card.querySelector(':scope>.workActions108');if(!holder){holder=document.createElement('div');holder.className='workActions108';card.append(holder)}for(const child of [...card.children])if(child!==holder&&!child.matches('.workView,input,label,img,span,strong,small,select')&&(child.matches('button')||child.querySelector('button')))holder.append(child)}}
 let workFrame153=0;function scheduleWork153(){if(workFrame153)return;workFrame153=requestAnimationFrame(()=>{workFrame153=0;workLayout()})}for(const host of [$('worksGrid'),$('cloudAccount75'),$('cloudGallery75')])if(host)new MutationObserver(scheduleWork153).observe(host,{childList:true,subtree:true});workLayout();
 // Keep exact quantities editable: older decorators turn bare number inputs into sliders.
 function exactNumber(control,name,limit){
  const label=control.closest('.field108'),input=document.createElement('input');
  input.type='number';input.min=control.min||'0';input.step='1';input.inputMode='numeric';input.value=control.value;
  input.id=control.id+'Number';input.className='number108';input.dataset.slider100='yes';input.dataset.stepper63='yes';input.dataset.adjust103='yes';
  input.setAttribute('aria-label',name+'精确数值');if(limit)input.max=String(limit);
  label.querySelector(':scope>output')?.setAttribute('hidden','');label.append(input);
  const sync=()=>{input.value=control.value};control.addEventListener('input',sync);
  input.onchange=()=>{const value=Number(input.value);if(!input.value||!Number.isFinite(value)||value<Number(input.min)){sync();return}
   const n=Math.min(limit||Number.MAX_SAFE_INTEGER,Math.max(Number(input.min),Math.floor(value)));
   if(n>+control.max)control.max=String(n);control.value=String(n);
   control.dispatchEvent(new Event('input',{bubbles:true}));control.dispatchEvent(new Event('change',{bubbles:true}));sync();
  };
  return input;
 }
 for(const [control,name,limit]of [[speed,'综合书风',100],[rows,'行数'],[cols,'列数'],[chars,'字数'],[cells,'格数'],[count,'每行 / 每列字数'],[bands,'行 / 列数量']])exactNumber(control,name,limit);
 const originalSyncGrid=syncGrid;syncGrid=()=>{originalSyncGrid();for(const r of [rows,cols,chars,cells]){$(r.id+'Number').value=r.value}};
 window.Revision108={ready:true};
})();
