(function previewPaperControls(){
 if(!window.Revision119?.ready||!window.AnnotationApp?.paperFrame107){setTimeout(previewPaperControls,80);return}
 const A=AnnotationApp,board=document.getElementById('board');const layer=document.createElement('div');layer.id='previewEdges120';layer.hidden=true;board.append(layer);
 const names={left:'向左扩纸',right:'向右扩纸',top:'向上扩纸',bottom:'向下扩纸'};let drag=null,busy=false,enabled=false;
 function place(){const visible=enabled&&A.isOverview55()&&A.scene()==='none'&&!document.body.classList.contains('home-open');layer.hidden=!visible;if(!visible)return;const p=A.paperFrame107();if(p.scale)Object.assign(layer.style,{left:p.x+'px',top:p.y+'px',width:p.w+'px',height:p.h+'px'})}
 async function expand(edge,amount){if(busy)return;const grid=A.writingGrid67(),unit=(edge==='left'||edge==='right'?grid.dx:grid.dy)||.4;const steps=Math.max(1,Math.round(Math.abs(amount)/unit)),delta=Math.sign(amount||1)*Math.min(50,steps*unit);busy=true;try{if(!A.expandPaperEdge(edge,delta))throw Error(delta<0?'纸边已贴近文字、图片或最小尺寸':'请先结束当前书写');A.toast((delta>0?'已扩展':'已收回')+({left:'左',right:'右',top:'上',bottom:'下'}[edge])+'侧纸张；可撤销');place()}catch(error){A.toast('调整未完成：'+error.message)}finally{busy=false}}
 for(const edge of Object.keys(names)){const button=document.createElement('button');button.type='button';button.className='previewEdge120 '+edge;button.setAttribute('aria-label',names[edge]+'或收回');button.title='点击向外扩一格；沿边向外或向内拖动调整';button.innerHTML='<svg viewBox="0 0 20 20" aria-hidden="true"><path d="M2 10h16M6 6l-4 4 4 4m8-8 4 4-4 4"/></svg>';layer.append(button);
  button.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();button.setPointerCapture(e.pointerId);drag={id:e.pointerId,edge,x:e.clientX,y:e.clientY,scale:A.paperFrame107().scale}});
  button.addEventListener('pointermove',e=>{if(drag?.id!==e.pointerId||drag.edge!==edge)return;e.preventDefault();const n=edge==='left'?drag.x-e.clientX:edge==='right'?e.clientX-drag.x:edge==='top'?drag.y-e.clientY:e.clientY-drag.y;button.dataset.grow=Math.abs(n)>12?(n>0?'＋':'−')+(Math.abs(n)/drag.scale).toFixed(2):''});
  const release=e=>{if(drag?.id!==e.pointerId||drag.edge!==edge)return;e.preventDefault();e.stopPropagation();const n=edge==='left'?drag.x-e.clientX:edge==='right'?e.clientX-drag.x:edge==='top'?drag.y-e.clientY:e.clientY-drag.y,scale=drag.scale;drag=null;delete button.dataset.grow;if(e.type==='pointerup')expand(edge,Math.abs(n)>12?Math.max(-50,Math.min(50,n/scale)):0)};button.addEventListener('pointerup',release);button.addEventListener('pointercancel',release);
 }
 const panel=document.getElementById('bigDialog62')?.querySelector('.dialogBody')||document.getElementById('bigDialog62');if(panel){const toggle=document.createElement('label');toggle.className='paperEdgeToggle120';toggle.innerHTML='<input type="checkbox" id="paperEdgeEnabled120"> 四向扩纸 <small>点击扩一格，向外或向内拖动；只调整对应宽或高</small>';panel.prepend(toggle);toggle.querySelector('input').onchange=e=>{enabled=e.target.checked;place()}}
 const top=document.getElementById('topAddPaper90');if(top){top.title='扩纸';top.setAttribute('aria-label','扩纸')}
 document.addEventListener('preview-painted94',place);document.addEventListener('ink-view-changed90',place);window.addEventListener('resize',place);place();
 const sample=document.createElement('button');sample.type='button';sample.id='thousandSample120';sample.className='tool90';sample.textContent='千字样本';sample.title='生成 1000 个字位、2000 笔的测试草稿，替换当前未保存草稿';const sampleTools=document.createElement('details');sampleTools.className='paperSample120';sampleTools.innerHTML='<summary>千字压力测试</summary>';sampleTools.append(sample);panel?.append(sampleTools);
 sample.onclick=async()=>{if(!confirm('载入千字压力样本会替换当前未保存草稿。已保存的作品不会删除。继续？'))return;sample.disabled=true;try{
  const draft=A.getState(),strokes=[],width=4,height=45,cols=10,rows=100;
  for(let i=0;i<1000;i++){const col=cols-1-i%cols,row=Math.floor(i/cols),x=.28+col*.35,y=.28+row*.44,seed=i*2;
   for(const [j,points] of [[0,[[x+.07,y+.06],[x+.23,y+.32]]],[1,[[x+.25,y+.08],[x+.06,y+.3]]]])strokes.push({points:points.map(([px,py],k)=>({x:px,y:py,t:k*18,pressure:.5})),settings:{...draft.brush,size:20},seed:seed+j,done:true,inkMode:'raw'})}
  const next={...draft,flow:{strokes},signatureStrokes:[],values:{...draft.values,paperExtent:'infinite',ratio:String(width/height),columns:String(cols),rows:String(rows),zoom:'400',guideMode:'off',sceneChoice:'none'},infiniteExtent:{w:width,h:height},camera:{x:2.5,y:0},writingView110:{camera:{x:2.5,y:0},focused:true},editingWork110:null};
  await A.restoreDraft(next);A.showWriter();A.persist();A.toast('已载入 1000 字位 / 2000 笔；可试缩放、变色与预览拖边')
 }catch(error){A.toast('样本未能载入：'+error.message)}finally{sample.disabled=false}};
 window.PreviewPaper120={expand,place,toggle:()=>{enabled=!enabled;const check=document.getElementById('paperEdgeEnabled120');if(check)check.checked=enabled;place();A.toast(enabled?'四向扩纸已开启':'四向扩纸已收起');return enabled}};
})();
