(()=>{
const countries={
'中国':'中国','鲁迅':'中国','老舍':'中国','朱自清':'中国','钱钟书':'中国','张爱玲':'中国','史铁生':'中国','路遥':'中国','余华':'中国','陈忠实':'中国','刘震云':'中国','金庸':'中国','莫言':'中国','刘慈欣':'中国',
'吉卜林':'英国','叶芝':'爱尔兰','萧伯纳':'爱尔兰','罗曼·罗兰':'法国','加缪':'法国','萨特':'法国','雨果':'法国','大仲马':'法国','圣埃克苏佩里':'法国','帕斯卡':'法国','卢梭':'法国',
'泰戈尔':'印度','黑塞':'德国','尼采':'德国','罗素':'英国','海明威':'美国','川端康成':'日本','索尔仁尼琴':'俄罗斯','聂鲁达':'智利','马尔克斯':'哥伦比亚','辛波斯卡':'波兰','莎士比亚':'英国','塞万提斯':'西班牙','简·奥斯汀':'英国','夏洛蒂·勃朗特':'英国','艾米莉·勃朗特':'英国','狄更斯':'英国','托尔斯泰':'俄罗斯','陀思妥耶夫斯基':'俄罗斯','普希金':'俄罗斯','高尔基':'俄罗斯','梭罗':'美国','纪伯伦':'黎巴嫩','卡夫卡':'捷克','菲茨杰拉德':'美国','奥威尔':'英国','塞林格':'美国','昆德拉':'捷克','培根':'英国','伍尔夫':'英国','狄兰·托马斯':'英国','阿西莫夫':'美国','赫伯特':'美国','勒古恩':'美国','赫胥黎':'英国'};
const palettes={
'法国':['#183d74','#fffaf0','#bc3037'],'中国':['#852c2b','#f5dfa3','#dfb759'],'美国':['#a52b36','#fffaf0','#214673'],'英国':['#213d68','#fffaf0','#bb3038'],'日本':['#f4f2eb','#242a30','#bc3241'],'俄罗斯':['#273e78','#fffaf0','#af343f'],'德国':['#262528','#f6d06e','#be3535'],'印度':['#276d4d','#fffaf0','#e9813c'],'爱尔兰':['#257454','#fffaf0','#e68f42'],'智利':['#245085','#fffaf0','#c52b39'],'哥伦比亚':['#e8bf3c','#193e79','#b83036'],'波兰':['#f6f3ed','#31343a','#bd3145'],'西班牙':['#af3232','#f4d369','#7d242a'],'捷克':['#f4f3ec','#164d89','#b83142'],'黎巴嫩':['#f3eee4','#2c6239','#bd3643']};
const $=id=>document.getElementById(id),box=document.createElement('section');box.id='liu61Editor';box.hidden=true;box.innerHTML='<p>刘欢亲自作词 · 十首作品。可将自己有权使用的完整歌词粘贴在此，全文仅存本机并完整显示供临写。</p><label>完整歌词<textarea id="liu61Text" rows="9" placeholder="请粘贴完整歌词，每段可换行"></textarea></label><button id="liu61Save" type="button">保存到本机并显示全文</button><p id="liu61Result" role="status"></p>';
$('quotePrompt').after(box);const input=$('liu61Text');
$('liu61Save').onclick=async()=>{const q=window.currentQuote;if(q?.cat!=='liu')return;const lyric=input.value.trim();if(!lyric){$('liu61Result').textContent='请先粘贴你有权使用的歌词全文';return}if(lyric.length>30000){$('liu61Result').textContent='单首歌词请控制在三万字以内';return}try{const saved=await DraftStore.get('liu61.lyrics')||{};saved[q.id]=lyric;await DraftStore.set('liu61.lyrics',saved);window.setLiuLyrics61(q.id,lyric);$('liu61Result').textContent='已保存于本机，全文可在上方阅读与临写'}catch{$('liu61Result').textContent='本机存储失败，请保留你的歌词副本'}};
DraftStore.get('liu61.lyrics').then(saved=>{if(!saved||typeof saved!=='object')return;for(const [id,lyric] of Object.entries(saved))if(typeof lyric==='string'&&lyric.length<=30000)window.setLiuLyrics61(id,lyric)}).catch(()=>{});
let lastCountry='';document.addEventListener('quote-changed',e=>{const q=e.detail;box.hidden=q.cat!=='liu';if(q.cat==='liu'){$('liu61Result').textContent='';input.value=q.editorial?'':q.q;return}if(q.cat!=='literature'){lastCountry='';return;}const author=q.author||String(q.source||q.s).split('《')[0].trim(),title=q.title||String(q.source||q.s).match(/《([^》]+)》/)?.[1]||'作品',country=q.country||countries[author]||'国别待核';const shortTitle=String(title).split(/[，。；,]/)[0].trim();const credit=author+'《'+(shortTitle.length>18?'作品名待核':shortTitle)+'》 · '+country;$('quoteSource').textContent='文学佳句 · '+credit;const label=$('dailyQuote').querySelector('small');if(label)label.textContent=' '+credit;
const colors=palettes[country];if(!colors)return;if(lastCountry===country)return;lastCountry=country;window.AnnotationApp?.applyLiteraryPalette61?.({paper:colors[0],ink:colors[1],seal:colors[2]})});
document.addEventListener('annotation-selected',e=>{if(e.detail?.key==='liuhuan'){lastCountry='';window.selectLiu61?.()}});
})();
