(function init97(){
 if(!window.Revision94?.ready||!window.Toolbar95||!document.getElementById('previewEffects55')){setTimeout(init97,60);return}
 const A=AnnotationApp,$=id=>document.getElementById(id),body=document.body,board=$('board'),panel=$('previewEffects55'),steps=panel.querySelector('.finalSteps54'),rail=panel.querySelector('.finalRail54');
 for(const b of steps.querySelectorAll('button')){const label=b.textContent.trim();if(label==='图文配置')b.textContent='图文';if(/文创/.test(label)){b.textContent='文创';b.hidden=true}if(label==='流变')b.hidden=true}
 const bell=$('adminBell95'),reminder=$('homeMoments')||$('momentReminder'),theme=document.querySelector('#homeActions90 .homeTheme78');if(theme){if(reminder)theme.before(reminder);if(bell)theme.before(bell)}
 const ratio=[...steps.querySelectorAll('button')].find(b=>b.textContent==='比例'),current=steps.querySelector('[aria-current=true]');ratio?.click();requestAnimationFrame(()=>{const h=rail.getBoundingClientRect().height;panel.style.setProperty('--rail-height97',(h>0?h:54)+'px');if(current&&current!==ratio&&!current.hidden)current.click()});
 const actions=panel.querySelector('.previewActions93');$('previewReset73').hidden=true;actions.id='previewFloating97';actions.hidden=true;
 const random=$('previewRandom79');random.classList.add('tool90','topRandom99');random.innerHTML='<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M3 6h3l12 12h3M3 18h3L18 6h3M18 3l3 3-3 3M18 15l3 3-3 3"/></svg><span>随机</span>';random.title='随机配色';random.setAttribute('aria-label','随机配色');$('export').after(random);$('export').onclick=()=>A.showDownloadOptions();actions.remove();

 const flags={top:false,bottom:false,config:false},toggles={};
 function setPart(part,hidden){flags[part]=hidden;body.classList.toggle('hide-'+part+'97',hidden);const b=toggles[part];b.textContent=hidden?'⌄':'⌃';b.setAttribute('aria-expanded',String(!hidden));b.setAttribute('aria-label',(hidden?'展开':'收起')+{top:'顶部工具',bottom:'底部工具',config:'预览选项'}[part]);requestAnimationFrame(()=>{A.refresh();place()})}
 for(const part of Object.keys(flags)){const b=document.createElement('button');b.id='toggle-'+part+'97';b.className='foldArrow97';b.type='button';toggles[part]=b;b.onclick=()=>setPart(part,!flags[part]);body.append(b);setPart(part,false)}
 let previousOverview=false;
 function place(){const overview=A.isOverview55(),home=body.classList.contains('home-open');if(overview&&!previousOverview){previousOverview=true;for(const part of Object.keys(flags))setPart(part,false)}else previousOverview=overview;actions.hidden=true;for(const part of Object.keys(flags))toggles[part].hidden=home||part==='config'&&!overview;if(!overview)return;if(!flags.bottom){$('bottomIcons39').hidden=false;body.classList.remove('dock-icons-collapsed56')}const f=A.previewFrame94(),r=board.getBoundingClientRect(),w=126;actions.style.setProperty('left',Math.max(4,Math.min(r.width-w-4,f.x+f.width-w-8))+'px','important');actions.style.setProperty('top',Math.max(0,Math.min(r.height-28,f.sheetBottom+f.gap*.5-14))+'px','important');actions.style.setProperty('width',w+'px','important')}
 document.addEventListener('preview-painted94',()=>requestAnimationFrame(place));addEventListener('resize',place);new MutationObserver(place).observe(panel,{attributes:true,attributeFilter:['hidden']});
 document.addEventListener('click',e=>{if(e.target.closest('#fitView,#annotationHomeButton,#returnWriting59'))requestAnimationFrame(place);if(e.target.closest('#fitView')&&A.isOverview55()){for(const part of Object.keys(flags))setPart(part,false)}if(e.target.closest('#fitView')||e.target.closest('.finalSteps54 button')?.textContent==='图文'){const hint=$('iconHint'),toast=$('toast');if(hint&&/查看整张纸/.test(hint.textContent))hint.hidden=true;if(toast&&/查看整张纸/.test(toast.textContent))toast.style.display='none'}},true);
 let swipe=null,multi=false;
 board.addEventListener('pointerdown',e=>{if(!A.isOverview55()||e.target!==$('live'))return;if(swipe){multi=true;swipe=null;return}if(multi)return;swipe={id:e.pointerId,x:e.clientX,y:e.clientY,t:e.timeStamp}},true);
 board.addEventListener('pointermove',e=>{if(swipe?.id===e.pointerId&&!multi){e.preventDefault();e.stopImmediatePropagation()}},{capture:true,passive:false});
 board.addEventListener('pointerup',e=>{if(multi){multi=false;swipe=null;return}const s=swipe;swipe=null;if(!s||s.id!==e.pointerId||!A.isOverview55())return;const dx=e.clientX-s.x,dy=e.clientY-s.y;if(Math.max(Math.abs(dx),Math.abs(dy))<50||e.timeStamp-s.t>1200)return;e.preventDefault();e.stopImmediatePropagation();$('live').dispatchEvent(new PointerEvent('pointercancel',{pointerId:e.pointerId,bubbles:true}));if(Math.abs(dy)>Math.abs(dx)){if(dy<0){if(flags.top&&flags.bottom&&flags.config)Revision94.apply(Revision94.palette());else for(const part of Object.keys(flags))setPart(part,true)}else for(const part of Object.keys(flags))setPart(part,false)}else{const keys=[...$('quickMount').options].map(o=>o.value),i=keys.indexOf($('quickMount').value);$('quickMount').value=keys[(i+(dx<0?1:-1)+keys.length)%keys.length];$('quickMount').dispatchEvent(new Event('change',{bubbles:true}))}requestAnimationFrame(place)},true);
 board.addEventListener('pointercancel',()=>{swipe=null;multi=false},true);
 place();window.Revision97={ready:true,setPart,get flags(){return {...flags}}};
})();
