/* V131: per-page reference geometry; the same settings feed preview and export. */
(function(root){
 const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));
 function normalize(value={}){const crop=value.crop||{},x=clamp(crop.x,0,.95),y=clamp(crop.y,0,.95);return{enabled:value.enabled!==false,opacity:value.opacity===undefined?20:clamp(value.opacity,0,100),crop:{x,y,w:clamp(crop.w??1,.05,1-x),h:clamp(crop.h??1,.05,1-y)}}}
 function applyGroup(album,value){album.reference131=normalize(value);for(const page of album.pages)page.reference131=normalize(value)}
 root.ReferenceModel131={normalize,applyGroup};if(!root.document)return;
 function init(){if(!root.Reference129?.ready||!document.getElementById('writerModes53')){setTimeout(init,80);return}
 const A=AnnotationApp,C=CopyAlbums38,R=Reference129,T=TouchOrder129,$=id=>document.getElementById(id),E=(tag,text,cls)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e};let fallback=normalize(),analysisOpen=false,urls=[];
 const page=()=>C.active?.pages[C.active.index],config=()=>normalize(page()?.reference131||C.active?.reference131||fallback);
 function save(value,all=false){value=normalize(value);if(C.active){if(all)applyGroup(C.active,value);else page().reference131=value;C.persist129().catch(e=>A.toast(e.message))}else fallback=value;A.refresh();A.persist();R.refreshSettings()}
 function btn(host,title,path,fn,pressed){const b=E('button',null,'referenceButton129');b.type='button';b.title=b.ariaLabel=title;b.innerHTML=T.icon(path)+'<span></span>';b.querySelector('span').textContent=title;if(pressed!==undefined)b.setAttribute('aria-pressed',String(pressed));b.onclick=async()=>{try{await fn()}catch(e){A.toast(e.message||'操作未完成')}};host.append(b);return b}
 const imagePath='M3 4h18v16H3zM3 16l6-6 5 5 3-3 4 4',bookPath='M4 4h7l1 2 1-2h7v15h-7l-1 2-1-2H4zM12 6v14',tune='M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M10 15v6';
 function renderControls(host){host.replaceChildren();const wrap=E('div',null,'referenceSettings129'),row=E('div',null,'referencePrimary129');wrap.append(row);host.append(wrap);btn(row,'全图铺满',imagePath,()=>{const c=config();c.enabled=!c.enabled;save(c)},config().enabled);btn(row,'悬浮原帖',bookPath,async()=>{R.settings.floating=!R.settings.floating;try{await R.loadImage()}catch(e){R.settings.floating=false;throw e}localStorage.setItem('reference.settings129',JSON.stringify(R.settings));R.refreshSettings()},R.settings.floating);btn(row,'选择原帖',bookPath,R.openPicker);btn(row,'上传参考','M12 16V3m-4 4 4-4 4 4M4 14v7h16v-7',()=>$('upload').click());btn(row,'组图排序',imagePath,()=>{const d=E('dialog',null,'referenceOrderDialog129');const h=E('header',null,'dialogHead');h.append(E('h2','长按拖动组图排序'));btn(h,'关闭','M6 6l12 12M18 6L6 18',()=>d.close());d.append(h);const list=E('div');d.append(list);document.body.append(d);renderStrip(list);d.addEventListener('close',()=>d.remove(),{once:true});d.showModal()});btn(row,'原帖长卷',imagePath,()=>Revision81.roll(C.active,true));btn(row,'临写长卷',bookPath,async()=>{await Revision128.saveOnSwitch129();await Revision81.roll(C.active,false)});btn(row,'当前作品分析',tune,()=>{analysisOpen=!analysisOpen;R.refreshSettings()},analysisOpen);
 if(analysisOpen){const panel=E('div',null,'referenceAnalysis131'),p=R.profile;panel.append(E('p',p?.summary||'选择原帖后分析。'),E('small',p?.basis||''),E('p',p?.tips||''));const fields={};for(const [key,label,value,min,max]of [['zoom','纸张 %',500,100,1000],['size','笔径',15,1,400],['lineStrength','综合书风',100,0,100]]){const l=E('label',label),input=E('input');input.type='number';input.value=value;input.min=min;input.max=max;fields[key]=input;l.append(input);panel.append(l)}btn(panel,'匹配参数',tune,async()=>{const zoom=clamp(fields.zoom.value,100,1000),size=clamp(fields.size.value,1,400),strength=clamp(fields.lineStrength.value,0,100);A.setLineProfile108(strength);await A.configure47({preset:p?.preset,size,brushPatch:{...p?.patch,lineStrength108:strength},values:{zoom:String(zoom)}});A.persist()});wrap.append(panel)}
 }
 function drawBackground(t,b,scale=1){const ref=A.getReference();if(!ref)return false;const c=config();if(!c.enabled)return true;const crop=c.crop,rw=ref.naturalWidth||ref.width,rh=ref.naturalHeight||ref.height,sw=rw*crop.w,sh=rh*crop.h,k=Math.min(b.w/sw,b.h/sh),w=sw*k,h=sh*k;t.save();t.scale(scale,scale);t.globalAlpha=c.opacity/100;t.drawImage(ref,rw*crop.x,rh*crop.y,sw,sh,(b.w-w)/2,(b.h-h)/2,w,h);t.restore();return true}
 const strip=E('div',null,'referenceStrip131');$('writerModes53').before(strip);
 function renderStrip(host=strip){const album=C.active;host.replaceChildren();if(!album)return;T.render(host,album.pages,{name:p=>p.name||p.image?.name||String(p.image).split('/').at(-1),image:p=>{if(typeof p.image==='string')return new URL(p.image,location.href).href;const u=URL.createObjectURL(p.image);urls.push(u);return u},open:async(p,i)=>{try{await C.select128(i);await R.entered();const c=config();c.enabled=true;save(c);A.showWriter();if(!A.isOverview55())$('fitView').click();R.openSettings()}catch(e){A.toast(e.message)}},move:async(from,to)=>{await C.reorder128(from,to,album.id);renderStrip(host)}});host.querySelectorAll('article').forEach((card,i)=>{card.setAttribute('aria-current',String(i===album.index));card.ariaLabel=card.querySelector('span').textContent+'，轻点切换，长按排序'})}
 function refreshStrip(){urls.forEach(URL.revokeObjectURL);urls=[];renderStrip();strip.hidden=localStorage.getItem('iinnkk.mode53')!=='copy'||!C.active}
 function entered(){const c=config();c.enabled=true;save(c);refreshStrip()}
 function editor(){const ref=A.getReference();if(!ref)return;const d=E('dialog',null,'referenceCrop131'),h=E('header',null,'dialogHead');h.append(E('strong','原帖 · 全图与裁切'));btn(h,'关闭','M6 6l12 12M18 6L6 18',()=>d.close());d.append(h);const canvas=E('canvas');const k=Math.min(1,900/(ref.naturalWidth||ref.width),650/(ref.naturalHeight||ref.height));canvas.width=(ref.naturalWidth||ref.width)*k;canvas.height=(ref.naturalHeight||ref.height)*k;d.append(canvas);let draft=config(),start=null,drag=false;function paint(){const t=canvas.getContext('2d'),c=draft.crop;t.clearRect(0,0,canvas.width,canvas.height);t.drawImage(ref,0,0,canvas.width,canvas.height);t.fillStyle='#30251d66';t.fillRect(0,0,canvas.width,canvas.height);t.drawImage(ref,c.x*ref.width,c.y*ref.height,c.w*ref.width,c.h*ref.height,c.x*canvas.width,c.y*canvas.height,c.w*canvas.width,c.h*canvas.height);t.strokeStyle='#cb3528';t.lineWidth=2;t.strokeRect(c.x*canvas.width,c.y*canvas.height,c.w*canvas.width,c.h*canvas.height)}const point=e=>{const b=canvas.getBoundingClientRect();return{x:clamp((e.clientX-b.left)/b.width,0,1),y:clamp((e.clientY-b.top)/b.height,0,1)}};canvas.onpointerdown=e=>{e.preventDefault();start=point(e);drag=false;canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!start)return;e.preventDefault();const p=point(e);if(Math.hypot(p.x-start.x,p.y-start.y)<.02)return;drag=true;draft.crop=normalize({crop:{x:Math.min(p.x,start.x),y:Math.min(p.y,start.y),w:Math.abs(p.x-start.x),h:Math.abs(p.y-start.y)}}).crop;paint()};canvas.onpointerup=canvas.onpointercancel=()=>start=null;d.append(E('small','在原帖上拖动选取保留区域。'));const row=E('div',null,'referenceCropTools131');btn(row,'全图',imagePath,()=>{draft.crop={x:0,y:0,w:1,h:1};paint()});const label=E('label','浓度 '),slider=E('input');slider.type='range';slider.min=0;slider.max=100;slider.value=draft.opacity;const out=E('output',draft.opacity+'%');slider.oninput=()=>{draft.opacity=+slider.value;out.textContent=slider.value+'%'};label.append(slider,out);row.append(label);btn(row,'应用本页',tune,()=>{draft.enabled=true;save(draft);d.close()});btn(row,'本组全局设定','M4 4h12v12H4zM8 20h12V8',()=>{draft.enabled=true;save(draft,true);d.close()});d.append(row);d.addEventListener('close',()=>d.remove(),{once:true});document.body.append(d);paint();d.showModal()}
 let tap=null,timer=0;const live=$('live');live.addEventListener('pointerdown',e=>{if(e.button>0||localStorage.getItem('iinnkk.mode53')!=='copy'||!A.isOverview55())return;tap={x:e.clientX,y:e.clientY,time:e.timeStamp,id:e.pointerId}},true);live.addEventListener('pointerup',e=>{if(!tap||tap.id!==e.pointerId)return;const p=tap;tap=null;if(Math.hypot(p.x-e.clientX,p.y-e.clientY)>8||e.timeStamp-p.time>300)return;if(timer){clearTimeout(timer);timer=0;return}timer=setTimeout(()=>{timer=0;if(A.isOverview55()&&config().enabled)editor()},360)},true);live.addEventListener('pointercancel',()=>tap=null);
 document.addEventListener('copy-page128',refreshStrip);document.addEventListener('copy-order128',refreshStrip);document.addEventListener('mode-changed54',refreshStrip);
 // The old split/crop overlays have no active geometry in V131.
 $('copyLayout111').value='background';[...$('copyLayout111').options].filter(o=>o.value!=='background').forEach(o=>o.remove());
 root.Reference131={renderControls,drawBackground,entered,editor};R.refreshSettings();refreshStrip();
 const home=$('annotationHome'),hero=home?.querySelector('.annotationBrand h1');if(home&&hero){const logo=E('button',null,'homeLogo131');logo.ariaLabel='返回首页顶部';const im=E('img');im.src='favicon90.png';im.alt='今日亲笔';logo.append(im);home.append(logo);logo.onclick=()=>{home.scrollTo({top:0,behavior:'smooth'});window.scrollTo({top:0,behavior:'smooth'})};const update=()=>{logo.hidden=!document.body.classList.contains('home-open')||hero.getBoundingClientRect().bottom>Math.max(0,home.getBoundingClientRect().top)};document.addEventListener('scroll',update,{capture:true,passive:true});new MutationObserver(update).observe(document.body,{attributes:true,attributeFilter:['class']});addEventListener('resize',update);update()}
 }
 init();
})(typeof window==='undefined'?globalThis:window);
