/* Release 66: compact preview controls, readable guides and a persistent paper toolbar. */
(function init(){if(!window.AnnotationApp?.ready||!window.DailyQuotes38||!document.getElementById('previewEffects55')||!document.getElementById('extendPaper63')){setTimeout(init,45);return}
const $=id=>document.getElementById(id),toolbar=$('topActions'),extend=$('extendPaper63');
function alignLast(){if(extend.isConnected&&toolbar.lastElementChild!==extend)toolbar.append(extend)}alignLast();new MutationObserver(alignLast).observe(toolbar,{childList:true});
// The home and upper toolbar never show the administration shortcut.
function removeHomeEditor(){document.querySelectorAll('.annotationBrand .liveEdit53').forEach(b=>b.remove())}removeHomeEditor();new MutationObserver(removeHomeEditor).observe(document.querySelector('.annotationBrand'),{childList:true});
const scope=$('inkScope39');function scopeIcon(){if(!scope)return;const all=$('recolorScope').value==='all';scope.setAttribute('aria-label',all?'整幅墨色 · 点击改下一笔':'下一笔墨色 · 点击改整幅');scope.querySelector('path')?.setAttribute('d',all?'M12 2c3 5 7 8 7 12a7 7 0 0 1-14 0c0-4 4-7 7-12ZM8 14c0 2 2 4 4 4':'M4 20 16 4l4 3-11 16-5-3ZM9 17l4 3')}scope?.addEventListener('click',()=>requestAnimationFrame(scopeIcon));$('recolorScope')?.addEventListener('change',scopeIcon);scopeIcon();
const controls=$('previewEffects55'),actions=controls.querySelector('.previewActions56');const zoom=document.createElement('span');zoom.className='previewZoom66';for(const [label,factor] of [['−',1/1.45],['＋',1.45]]){const b=document.createElement('button');b.type='button';b.textContent=label;b.title=label==='＋'?'放大作品细节':'缩小作品';b.setAttribute('aria-label',b.title);b.onclick=()=>window.zoomPreview66?.(factor);zoom.append(b)}document.querySelector('.workspace').append(zoom);const quoteToggle=document.createElement('button');quoteToggle.id='previewQuotes70';quoteToggle.type='button';quoteToggle.title='显示或隐藏好词好句';quoteToggle.setAttribute('aria-label',quoteToggle.title);quoteToggle.innerHTML=$('topQuotes').innerHTML;quoteToggle.onclick=()=>$('topQuotes').click();actions.prepend(quoteToggle);const syncQuoteToggle=()=>quoteToggle.setAttribute('aria-pressed',String($('quotesVisibility').value==='shown'));$('topQuotes').addEventListener('click',syncQuoteToggle);syncQuoteToggle();$('returnWriting59').textContent='返回书写';$('generateArtwork59').textContent='生成下载';
// The original daily quote bar and its category menu stay mounted in both modes.
// Its buttons keep the same listeners, accessibility labels, and reading dialog.
document.documentElement.classList.add('ui-ready67');
})();
