(function init118(){
 if(!window.WritingRank117||!window.AnnotationApp?.ready){setTimeout(init118,60);return}
 const A=AnnotationApp,$=id=>document.getElementById(id),rank=()=>WritingRank117.open();
 const icon=document.createElement('button');icon.id='homeRank118';icon.type='button';icon.className='homeIcon111';icon.title=icon.ariaLabel='写字排行榜';icon.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M3 20h18M5 18V9h4v9m2 0V4h4v14m2 0v-6h4v6M13 2l1 2"/></svg>';icon.onclick=rank;$('homeWorks111').before(icon);
 for(const id of ['homeWorks111','homeHall111'])$(id).querySelector('span')?.remove();
 const works=$('worksDialog').querySelector('.dialogHead'),entry=document.createElement('button');entry.type='button';entry.className='worksRank118';entry.textContent='♕';entry.title=entry.ariaLabel='写字排行榜';entry.onclick=rank;works.insertBefore(entry,works.querySelector('[data-close]'));
 const ratio=$('ratio'),effects=$('previewEffects55'),rail=effects.querySelector('.finalRail54');
 function ratios(){const row=rail.querySelector('.ratioRail80');if(!row)return;const custom=[...row.children].find(b=>b.textContent==='自定义比例'),wechat=[...row.children].find(b=>b.textContent==='微信贴图'),cover=[...row.children].find(b=>b.textContent==='朋友圈封面');if(custom){if(wechat)row.insertBefore(wechat,custom);if(cover)row.insertBefore(cover,custom);custom.onclick=()=>openRatio()}}
 const oldRatio=$('previewRatio79').onclick;$('previewRatio79').onclick=function(e){oldRatio?.call(this,e);ratios()};
 function openRatio(){let d=$('customRatio118');if(!d){d=document.createElement('dialog');d.id='customRatio118';d.innerHTML='<header><h2>自定义比例</h2><button type="button" data-close aria-label="关闭">×</button></header><form method="dialog"><label>宽 <input name="width" type="number" min="1" max="10000" step="any" required value="3"></label><label>高 <input name="height" type="number" min="1" max="10000" step="any" required value="4"></label><button type="submit">应用比例</button></form>';document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.querySelector('form').onsubmit=e=>{e.preventDefault();const w=+d.querySelector('[name=width]').value,h=+d.querySelector('[name=height]').value;if(!Number.isFinite(w/h)||w<=0||h<=0||w/h<.05||w/h>20)return;const value=(w/h).toFixed(6);let option=[...ratio.options].find(o=>o.value===value);if(!option){option=new Option('自定义比例 · '+w+':'+h,value);ratio.add(option)}ratio.value=value;ratio.dispatchEvent(new Event('change',{bubbles:true}));d.close();$('previewRatio79').click();A.persist()}}const v=+ratio.value||.75;d.querySelector('[name=width]').value=+(v*100).toFixed(2);d.querySelector('[name=height]').value=100;d.showModal()}
 // Reference editing shares the photo editor's two explicit modes: frame and image.
 const frame=$('board').querySelector('.copyFrame117'),tips=frame?.querySelector('span');let mode='image',drag=null;
 const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),layout=()=>$('copyLayout111').value,def=()=>layout()==='top'?{x:0,y:0,w:100,h:25}:{x:0,y:0,w:20,h:100};
 function fields(){return{x:+$('copyFrameX118').value,y:+$('copyFrameY118').value,w:+$('copyFrameW118').value,h:+$('copyFrameH118').value}}
 function set(v){for(const [k,id] of [['x','copyFrameX118'],['y','copyFrameY118'],['w','copyFrameW118'],['h','copyFrameH118']])$(id).value=String(v[k]);A.refresh();A.persist();WritingRank117.framePosition()}
 function controls(){const row=rail.querySelector('.copyOptions111');if(!row)return;const a=document.createElement('button'),b=document.createElement('button'),replace=document.createElement('button');a.textContent='调整外框';b.textContent='调整图片';replace.textContent='替换原帖';a.onclick=()=>{mode='frame';controls()};b.onclick=()=>{mode='image';controls()};replace.onclick=()=>{const input=$('copyDialog').querySelector('input[type=file]');if(input)input.click();else A.openDialog('copyDialog')};a.setAttribute('aria-pressed',String(mode==='frame'));b.setAttribute('aria-pressed',String(mode==='image'));row.prepend(a,b,replace);if(tips)tips.textContent=mode==='frame'?'拖动外框 · 右下角缩放':'拖动图片 · 双指缩放'}
 const copy=[...effects.querySelectorAll('.finalSteps54 button')].find(b=>b.textContent.trim()==='临帖');if(copy){const old=copy.onclick;copy.onclick=function(e){old?.call(this,e);controls()}}
 $('copyLayout111').addEventListener('change',()=>set(def()));
 if(frame){const position=WritingRank117.framePosition;WritingRank117.framePosition=()=>{position();if(frame.hidden)return;const paper=A.paperFrame107(),f=fields();Object.assign(frame.style,{left:paper.x+paper.w*f.x/100+'px',top:paper.y+paper.h*f.y/100+'px',width:paper.w*f.w/100+'px',height:paper.h*f.h/100+'px'})};for(const event of ['preview-painted94','reference-set111','reference-layout111','ink-view-changed90'])document.addEventListener(event,()=>WritingRank117.framePosition());const handle=document.createElement('button');handle.className='copyResize118';handle.type='button';handle.ariaLabel='缩放原帖外框';handle.textContent='⤢';frame.append(handle);
 frame.addEventListener('pointerdown',e=>{if(mode!=='frame')return;e.stopImmediatePropagation();drag={id:e.pointerId,startX:e.clientX,startY:e.clientY,start:fields(),kind:e.target===handle?'resize':'move'};frame.setPointerCapture(e.pointerId)},true);
 frame.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;e.stopImmediatePropagation();const paper=A.paperFrame107(),dx=(e.clientX-drag.startX)/paper.w*100,dy=(e.clientY-drag.startY)/paper.h*100,v={...drag.start};if(drag.kind==='resize'){v.w=clamp(v.w+dx,8,100-v.x);v.h=clamp(v.h+dy,8,100-v.y)}else{v.x=clamp(v.x+dx,0,100-v.w);v.y=clamp(v.y+dy,0,100-v.h)}set(v)},true);for(const name of ['pointerup','pointercancel'])frame.addEventListener(name,e=>{if(drag?.id===e.pointerId){e.stopImmediatePropagation();drag=null}},true)}
 // Selection and seal inspector leave the writing surface available after editing.
 document.addEventListener('pointerdown',e=>{if(!$('sealInspector').hidden&&!e.target.closest('#sealInspector,#sealHandles,#sealOverlay'))$('finishSealSelection').click();if($('selectInk').getAttribute('aria-pressed')==='true'&&!e.target.closest('.inkSelectionLayer,#selectInk')&&e.target.closest('#board,#writerLeft90,#topActions'))window.inkEditor?.close()},true);
 WritingRank117.framePosition();window.Revision118={ready:true,openRatio};
})();
