(function init(){if(!window.Revision39?.ready||typeof window.AnnotationApp?.sealUnit!=='function'){setTimeout(init,30);return}const $=id=>document.getElementById(id),app=AnnotationApp;
document.title='今日亲笔 · 亲笔手书，见墨如我';
const defaults={head:'亲笔手书',tail:'见墨如我'};for(const key of ['head','tail']){if(['真迹','亲笔','今日親筆','手書真跡','今日亲笔','手书真迹'].includes($(key+'Text').value)){app.editSeal(key,{config:{text:defaults[key],type:key==='head'?'yang':'yin',shape:key==='head'?'tall':'square',layout:key==='head'?'vertical':'horizontal',font:'small'}})}}
const container=$('sealDialog').querySelector('.sealGroups39');
window.SealMenu41=()=>{container.replaceChildren();for(const [name,kind]of [['引首章','head'],['腰章','waist'],['落款章','tail']]){let key=kind==='waist'?'extra0':kind;const section=document.createElement('section'),title=document.createElement('h3');title.textContent=name;section.append(title);const grid=document.createElement('div');grid.className='sealFields41';section.append(grid);container.append(section);
const get=()=>app.sealItems().find(s=>s.key===key);let item=get(),cfg=item?.config||{text:kind==='waist'?'见字如面':defaults[kind],font:'small',type:kind==='tail'?'yin':'yang',shape:kind==='head'?'tall':'square',layout:kind==='head'?'vertical':'horizontal',fontScale:1};
const preview=document.createElement('canvas');preview.width=preview.height=160;preview.className='stampSample41';preview.setAttribute('aria-label',name+'预览');const paint=()=>{const t=preview.getContext('2d');t.clearRect(0,0,160,160);t.drawImage(SealEngine.stamp({...cfg,fontLoaded:true}),0,0,160,160)};
const update=patch=>{if(!get()){if(kind==='waist')key=app.ensureWaist();else app.showSeal(key)}if(patch.config)cfg={...cfg,...patch.config};app.editSeal(key,patch);paint()};
function field(label,value,choices,change,type='text'){const l=document.createElement('label');l.textContent=label;const e=document.createElement(choices?'select':'input');e.dataset.stamp=kind;e.dataset.field=label;if(choices)for(const [v,n]of choices)e.add(new Option(n,v));else{e.type=type;if(type==='number'){e.min=label==='字体大小'?'60':'2';e.max=label==='字体大小'?'100':'30';e.step='1'}else e.maxLength=6}e.value=value;e.onchange=()=>change(e.value);l.append(e);grid.append(l);return e}
const content=field('文字内容',cfg.text,null,v=>update({config:{text:v}}));field('内容推荐','',[['','选择印文'],...['亲笔手书','见字如我','留下真迹','见字如面','翰墨有情','长乐未央','心手相应','清风明月','山高水长','书为心画','自得其乐','静观','墨趣'].map(x=>[x,x])],v=>{if(v){content.value=v;update({config:{text:v}})}});
field('字体',cfg.font,[['small','篆书'],['song','宋体 · 细'],['regular','楷体 · 细'],['custom','已导入字体']],v=>update({config:{font:v}}));field('字体大小',Math.round((cfg.fontScale||1)*100),null,v=>update({config:{fontScale:Math.max(.6,Math.min(1,+v/100))}}),'number');field('印章大小',Math.round((item?.size||app.sealUnit()*7)/app.sealUnit()),null,v=>update({size:Math.max(2,Math.min(30,+v||7))*app.sealUnit()}),'number');field('文字排版',cfg.layout,[['horizontal','左右排布'],['vertical','上下竖排']],v=>update({config:{layout:v}}));field('阴阳文',cfg.type,[['yang','阳文 · 朱文'],['yin','阴文 · 白文']],v=>update({config:{type:v}}));field('印章形状',cfg.shape,[['square','方印'],['tall','长方竖印'],['wide','长方横印'],['oval','椭圆'],['stone','随形石印'],['gourd','葫芦']],v=>update({config:{shape:v}}));section.append(preview);paint();}}
SealMenu41();
// A postcard stays an ordinary editable photo layout, with paper-coordinate decorations.
for(const id of ['photoMode','quickPhotoMode'])if(![...$(id).options].some(o=>o.value==='postcard'))$(id).add(new Option('明信片 · 风光与手书','postcard'));
const postal=document.createElement('div');postal.className='postcardSettings41';postal.innerHTML='<h3>明信片邮戳</h3><div class="twoCol"><label>城市<input id="postalCity41" maxlength="24" value="巴黎"></label><label>日期<input id="postalDate41" maxlength="24" value="2026.9.18"></label></div><button id="usePostcard41">使用明信片排版</button>';$('photoMode').closest('label').after(postal);
for(const [id,store]of [['postalCity41','postcardCity'],['postalDate41','postcardDate']]){$(id).value=$(store).value;$(id).onchange=()=>{$(store).value=$(id).value;app.refreshPaper();app.persist()}}
$('usePostcard41').onclick=()=>{$('quickPhotoMode').value='postcard';$('quickPhotoMode').dispatchEvent(new Event('change'));app.toast('明信片已应用，可上传风光照片并写下寄语')};
window.Postcard41={draw(t,b){t.save();t.scale(1/200,1/200);b={w:b.w*200,h:b.h*200};t.fillStyle='#fff9ed';t.fillRect(0,0,b.w,b.h);t.lineWidth=b.w*.004;for(let i=0;i<32;i++){t.strokeStyle=i%2?'#8c3430':'#456271';t.beginPath();t.moveTo((i+.1)*b.w/32,b.h*.025);t.lineTo((i+.7)*b.w/32,b.h*.025);t.moveTo((i+.1)*b.w/32,b.h*.975);t.lineTo((i+.7)*b.w/32,b.h*.975);t.stroke()}t.strokeStyle='#bcb09b';t.lineWidth=b.w*.0015;t.strokeRect(b.w*.065,b.h*.07,b.w*.87,b.h*.44);t.fillStyle='#8b806d';t.font=b.w*.025+'px Caption38,serif';t.textAlign='center';t.fillText('在这里放一张风光照片',b.w*.5,b.h*.30);t.textAlign='left';t.fillText('POSTCARD  /  亲笔寄语',b.w*.09,b.h*.57);const x=b.w*.82,y=b.h*.615,R=b.w*.105;t.save();t.globalAlpha=.65;t.strokeStyle='#6b6254';t.lineWidth=b.w*.0018;for(let row=-2;row<=2;row++){t.beginPath();for(let i=0;i<=90;i++){const wx=x-R*3.15+i/90*R*2.25,wy=y+row*R*.23+Math.sin(i/90*Math.PI*5)*R*.095;if(i===0)t.moveTo(wx,wy);else t.lineTo(wx,wy)}t.stroke()}t.restore();t.globalAlpha=.82;t.strokeStyle='#6b6254';t.lineWidth=b.w*.003;t.beginPath();t.arc(x,y,R,0,Math.PI*2);t.stroke();t.lineWidth=b.w*.001;t.beginPath();t.arc(x,y,R*.85,0,Math.PI*2);t.stroke();t.fillStyle='#645a4b';t.textAlign='center';t.font=b.w*.026+'px Caption38,serif';t.fillText($('postcardCity').value||'巴黎',x,y-R*.23,R*1.6);t.font=b.w*.019+'px Caption38,serif';t.fillText($('postcardDate').value||'2026.9.18',x,y+R*.28,R*1.7);t.restore()}};
window.Revision41={ready:true};app.refreshPaper();})();
