/* V128: idle saving and one shared reference page order. */
(function init128(){
 if(!window.AnnotationApp?.ready||!window.CopyAlbums38||!window.Revision118?.ready){setTimeout(init128,80);return}
 const A=AnnotationApp,$=id=>document.getElementById(id),C=CopyAlbums38;
 let timer=0,saving=false,dirty=false,lastSaved=0,lastCloudSaved=0;
 function queueAutosave(){dirty=true;clearTimeout(timer);timer=setTimeout(flush,Math.max(1800,8000-(Date.now()-lastSaved)))}
 async function flush(){if(!dirty)return;if(saving||A.isDrawing128()||document.querySelector('#imageDialog[open]')){timer=setTimeout(flush,1500);return}saving=true;dirty=false;try{const record=await A.autosave128();if(record&&window.InkCloud75?.user&&Date.now()-lastCloudSaved>30000){try{if(await InkCloud75.saveNow101(record,undefined,true))lastCloudSaved=Date.now()}catch(e){console.warn('Cloud autosave pending',e);dirty=true}}lastSaved=Date.now()}catch(e){dirty=true;console.warn('Autosave deferred',e);timer=setTimeout(flush,5000)}finally{saving=false}}
 document.addEventListener('ink-stroke',queueAutosave);document.addEventListener('visibilitychange',()=>{if(document.hidden)flush()});
 document.addEventListener('contextmenu',e=>{if(e.target.closest('#copyDock111,#copyPages38,#copyAlbumViewer38,.timelineArrow73,.copyReference128,.referenceThumbs128'))e.preventDefault()},true);
 const thumbs=document.createElement('div');thumbs.className='referenceThumbs128';$('albumImage38').after(thumbs);let thumbURLs=[];
 const source=p=>typeof p.image==='string'?new URL(p.image,location.href).href:(()=>{const u=URL.createObjectURL(p.image);thumbURLs.push(u);return u})();
 function paintThumbs(){thumbURLs.forEach(URL.revokeObjectURL);thumbURLs=[];thumbs.replaceChildren();const album=C.viewed;if(!album)return;album.pages.forEach((p,i)=>{const cell=document.createElement('div'),button=document.createElement('button'),im=document.createElement('img');im.src=source(p);im.alt=p.name||'原帖 '+(i+1);button.append(im);button.setAttribute('aria-pressed',String(i===C.index128));button.onclick=async()=>{await C.selectViewed128(i);paintThumbs()};cell.append(button);if(C.albums.includes(album))for(const [label,d]of [['←',-1],['→',1]]){const b=document.createElement('button');b.textContent=label;b.disabled=i+d<0||i+d>=album.pages.length;b.onclick=async()=>{await C.reorder128(i,i+d,album.id);paintThumbs()};cell.append(b)}thumbs.append(cell)})}
 new MutationObserver(paintThumbs).observe($('albumImage38'),{attributes:true,attributeFilter:['src']});document.addEventListener('copy-order128',paintThumbs);
 const ref=document.createElement('section');ref.className='copyReference128';ref.hidden=true;ref.innerHTML='<header><strong>原帖参考</strong><button data-close aria-label="关闭原帖">×</button></header><div class="referenceViewport128"><img alt="原帖局部参考" draggable="false"></div><footer><button data-minus>−</button><button data-plus>＋</button><button data-reset>全图</button><label><input type="checkbox" data-sync checked>跟随字位</label></footer>';$('board').append(ref);
 const image=ref.querySelector('img'),viewport=ref.querySelector('.referenceViewport128');let refURL='',zoom=1,pan={x:0,y:0},move=null,lastCell='',advanceTimer=0;
 const setTransform=()=>image.style.transform='translate('+pan.x+'px,'+pan.y+'px) scale('+zoom+')';
 async function currentImage(){const album=C.active;if(!album)return;const page=album.pages[album.index];if(refURL.startsWith('blob:'))URL.revokeObjectURL(refURL);refURL=typeof page.image==='string'?new URL(page.image,location.href).href:URL.createObjectURL(page.image);image.src=refURL;await image.decode();zoom=1;pan={x:0,y:0};setTransform()}
 ref.querySelector('[data-close]').onclick=()=>ref.hidden=true;
 ref.querySelector('[data-plus]').onclick=()=>{zoom=Math.min(16,zoom*1.3);setTransform()};ref.querySelector('[data-minus]').onclick=()=>{zoom=Math.max(1,zoom/1.3);setTransform()};ref.querySelector('[data-reset]').onclick=()=>{image.style.width='100%';image.style.height='100%';zoom=1;pan={x:0,y:0};setTransform()};
 ref.querySelector('header').onpointerdown=e=>{if(e.target.closest('button'))return;e.preventDefault();const r=ref.getBoundingClientRect();move={kind:'window',id:e.pointerId,x:e.clientX,y:e.clientY,left:r.left,top:r.top};ref.setPointerCapture(e.pointerId)};
 viewport.onpointerdown=e=>{e.preventDefault();move={kind:'image',id:e.pointerId,x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};ref.setPointerCapture(e.pointerId)};
 ref.onpointermove=e=>{if(move?.id!==e.pointerId)return;const dx=e.clientX-move.x,dy=e.clientY-move.y;if(move.kind==='window'){ref.style.left=Math.max(0,Math.min(innerWidth-ref.offsetWidth,move.left+dx))+'px';ref.style.top=Math.max(0,Math.min(innerHeight-60,move.top+dy))+'px'}else{pan={x:move.px+dx,y:move.py+dy};setTransform()}};ref.onpointerup=ref.onpointercancel=()=>move=null;
 viewport.onwheel=e=>{e.preventDefault();zoom=Math.max(1,Math.min(16,zoom*Math.exp(-e.deltaY*.002)));setTransform()};
 const tools=document.createElement('section');tools.className='copyTools128';tools.innerHTML='<h3>临帖方式 · V128</h3><div><button data-layout="background">全图铺满</button><button data-layout="left">左帖右写</button><button data-layout="floating">悬浮原帖</button></div><label><input id="copyAdvance128" type="checkbox">停笔后自动下一个字</label><label>停笔等待（秒）<input id="copyPause128" type="number" min="1" max="10" step="0.5" value="2.5"></label><label>原帖每列字数<input id="copyRows128" type="number" min="1" max="100" value="7"></label><div><button data-next>下一个字</button><button data-page>下一张纸</button><button data-order>组图与排序</button></div>';$('copyDialog').querySelector('.dialogBody').prepend(tools);
 tools.querySelectorAll('[data-layout]').forEach(b=>b.onclick=async()=>{const layout=b.dataset.layout;if(layout==='floating'){await currentImage();ref.hidden=false;await A.configure47({values:{copyLayout111:'background',opacity:'0'}})}else{ref.hidden=true;await A.configure47({values:{copyLayout111:layout,copyFrameX118:'0',copyFrameY118:'0',copyFrameW118:'40',copyFrameH118:'100',copyAuto111:'on',refFit:'cover',opacity:layout==='background'?'20':'100'}})}$('copyDialog').close()});
 async function nextPage(){clearTimeout(advanceTimer);await C.saveCurrent();if(C.active&&C.active.index<C.active.pages.length-1){await C.change128(1);return}const state=A.getState();await A.savePage();if(C.active)await C.newPaper128();else await A.startSeriesPage119(state);if(C.active){await currentImage();const bitmap=new Image();bitmap.src=image.src;await bitmap.decode();A.setReference(bitmap)}A.showWriter();A.toast('已保存上一张，开始新纸')}
 async function nextCell(){clearTimeout(advanceTimer);if(A.isDrawing128())return;if(!A.nextCell128())await nextPage()}
 tools.querySelector('[data-next]').onclick=nextCell;tools.querySelector('[data-page]').onclick=()=>nextPage().catch(e=>A.toast(e.message));
 tools.querySelector('[data-order]').onclick=()=>{const album=C.active;if(!album)return A.toast('请先上传或打开组图');const d=document.createElement('dialog');d.className='copyOrder128';const close=document.createElement('button');close.textContent='完成 ×';close.onclick=()=>d.close();d.append(close);const rows=document.createElement('div');d.append(rows);const urls=[];function draw(){urls.forEach(URL.revokeObjectURL);urls.length=0;rows.replaceChildren();album.pages.forEach((p,i)=>{const row=document.createElement('div'),im=document.createElement('img'),name=document.createElement('span');im.src=typeof p.image==='string'?new URL(p.image,location.href).href:URL.createObjectURL(p.image);if(im.src.startsWith('blob:'))urls.push(im.src);name.textContent=(i+1)+' · '+p.name;row.append(im,name);for(const [label,delta]of [['↑',-1],['↓',1]]){const b=document.createElement('button');b.textContent=label;b.disabled=i+delta<0||i+delta>=album.pages.length;b.onclick=async()=>{await C.reorder128(i,i+delta,album.id);draw()};row.append(b)}const go=document.createElement('button');go.textContent='临写';go.onclick=async()=>{await C.select128(i);d.close();$('copyDialog').close()};row.append(go);rows.append(row)})}draw();d.addEventListener('close',()=>{urls.forEach(URL.revokeObjectURL);d.remove()});document.body.append(d);d.showModal()};
 function followCell(row,col){if(!ref.querySelector('[data-sync]').checked||ref.hidden)return;const rows=Math.max(1,+$('copyRows128').value||7),cols=Math.max(1,+$('copyColumns111').value||1),key=row+':'+col;if(key===lastCell)return;lastCell=key;const w=viewport.clientWidth,h=viewport.clientHeight,k=Math.min(w/image.naturalWidth,h/image.naturalHeight),iw=image.naturalWidth*k,ih=image.naturalHeight*k,c=A.referenceCells128()?.[col],glyph=c?.glyphs?.[row],cx=c?.x??(1-(col+.5)/cols),cy=glyph?.y??((row+.5)/rows),cw=c?.w??1/cols,ch=glyph?.h??1/rows;zoom=Math.max(1,Math.min(16,.9*Math.min(w/(cw*iw),h/(ch*ih))));pan={x:w/2-cx*iw*zoom,y:h/2-cy*ih*zoom};image.style.width=iw+'px';image.style.height=ih+'px';setTransform()}
 document.addEventListener('copy-cell128',e=>followCell(e.detail.row,e.detail.col));
 document.addEventListener('ink-stroke',e=>{if(!C.active||localStorage.getItem('iinnkk.mode53')!=='copy')return;const p=e.detail.points[Math.floor(e.detail.points.length/2)],g=A.writingGrid67(),a=g.area;followCell(Math.max(0,Math.floor((p.y-a.y)/g.dy)),Math.max(0,Math.floor((a.x+a.w-p.x)/g.dx)));if($('copyAdvance128').checked){clearTimeout(advanceTimer);advanceTimer=setTimeout(()=>nextCell().catch(e=>A.toast(e.message)),Math.max(1000,+$('copyPause128').value*1000))}});
 $('live').addEventListener('pointerdown',()=>clearTimeout(advanceTimer),true);document.addEventListener('copy-page128',()=>{lastCell='';if(!ref.hidden)currentImage().catch(e=>A.toast(e.message))});
 window.Revision128={ready:true,queueAutosave,flush,nextCell,nextPage};
})();
