(function init111(){
 if(!window.Revision110?.ready){setTimeout(init111,40);return}
 const A=AnnotationApp,$=id=>document.getElementById(id),effects=$('previewEffects55'),steps=effects.querySelector('.finalSteps54'),rail=effects.querySelector('.finalRail54');document.body.classList.add('ui111');
 const button=(text,fn,id)=>{const b=document.createElement('button');b.type='button';b.textContent=text;if(id)b.id=id;b.onclick=fn;return b};
 // The original work is the editing destination; native Save overwrites it directly.
 $('export').onclick=async()=>{if(A.writing()||$('export').disabled)return;if(!A.getState().editingWork110){A.showDownloadOptions();return}$('export').disabled=true;try{await A.savePage()}finally{$('export').disabled=false}};
 $('downloadDialog').querySelector('h2').textContent='保存作品';$('generateDownload').textContent='保存作品';$('creationActions50')?.remove();
 $('imageDialog').querySelector('[data-close]').onclick=()=>{const back=$('imageDialog').dataset.fromWorks111;$('imageDialog').close();if(back)$('myWorks').click()};
 $('worksDialog').querySelector('.dialogBody>.note').textContent='所有亲笔集中在这里：私藏与发布清晰标记。编辑保留原纸面缩放和笔径，保存直接更新同一幅作品。';
 // The two home entries reuse the authoritative local/cloud gallery services.
 function homeIcon(name,id,path,fn){const b=button('',fn,id);b.className='homeIcon111';b.title=name;b.setAttribute('aria-label',name);b.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="'+path+'"/></svg><span>'+name+'</span>';return b}
 const mine=homeIcon('我的作品','homeWorks111','M4 3h16v18H4zM8 7h8M8 11h8M8 15h5',()=>$('myWorks').click()),hall=homeIcon('书法殿堂','homeHall111','m2 8 10-6 10 6H2Zm3 2v8m7-8v8m7-8v8M2 21h20',()=>window.InkCloud75?InkCloud75.showGallery().catch(e=>A.toast(e.message)):A.toast('作品服务正在连接，请稍后重试'));
 const calendar=$('homeMoments');calendar.before(mine,hall);
 for(const b of $('worksDialog').querySelectorAll('.dialogHead button'))if(b.textContent==='我的作品')b.textContent='书法殿堂';
 const cloudHost=document.createElement('section');cloudHost.id='cloudOnly111';$('worksGrid').after(cloudHost);let records=[],generation=0,filter='all',localBindings141=new Map(),pendingIds141=new Set();
 const filterRow=document.createElement('nav');filterRow.className='workFilters111';filterRow.setAttribute('aria-label','作品可见性');for(const [title,value]of [['全部','all'],['私藏','private'],['发布','published']]){const b=button(title,()=>{filter=value;paintWorks()});b.dataset.filter=value;filterRow.append(b)}$('worksSearch').closest('label').after(filterRow);
 function localId(row){return String(row.local_id||'').split('|').at(-1)}
 function paintWorks(){for(const b of filterRow.children)b.setAttribute('aria-pressed',String(b.dataset.filter===filter));for(const card of $('worksGrid').querySelectorAll('.workCard[data-work-id]')){const record=records.find(r=>r.id===localBindings141.get(card.dataset.workId))||records.find(r=>localId(r)===card.dataset.workId),published=!!record?.published;let mark=card.querySelector('.visibility111');if(!mark){mark=document.createElement('strong');mark.className='visibility111';card.prepend(mark)}const text=pendingIds141.has(card.dataset.workId)?'原笔迹保存在本机':published?'已发布'+(record?.draft_path?' · 原笔迹已同步':' · 仅图片'):record?(record.draft_path?'共书 · 原笔迹已同步':'私藏 · 仅图片已同步'):'本机作品';if(mark.textContent!==text)mark.textContent=text;mark.dataset.published=String(published);card.querySelector('.cloudEdit141')?.remove();card.hidden=filter==='published'?!published:filter==='private'?published:false}for(const c of cloudHost.children){const published=c.dataset.published==='true';c.hidden=filter==='published'?!published:filter==='private'?published:false}}
 async function refreshSyncMarks141(){const owner=window.InkCloud75?.user?.id;pendingIds141=new Set((await window.OfflineSync101?.pending?.()||[]).filter(j=>!j.owner||j.owner===owner).map(j=>j.id));paintWorks()}
 async function refreshMine(){const request=++generation;await refreshSyncMarks141();cloudHost.replaceChildren();records=[];paintWorks();if(!window.InkCloud75?.user)return;try{records=await InkCloud75.mine111();if(request!==generation||!$('worksDialog').open)return;const locals=await Promise.all((await DraftStore.get('works-index')||[]).map(w=>DraftStore.get(w.id)));localBindings141=new Map(locals.filter(w=>w?.cloud141?.id&&w.cloud141.owner===InkCloud75.user?.id).map(w=>[w.id,w.cloud141.id]));const bound=new Set(localBindings141.values()),unbound=new Set(locals.filter(w=>w&&!w.cloud141).map(w=>w.id)),represented=new Set();for(const record of records){const nativeId=localId(record);if(bound.has(record.id))continue;if(unbound.has(nativeId)&&!represented.has(nativeId)){represented.add(nativeId);continue}const card=document.createElement('article');card.className='cloudWork75';card.dataset.cloudId144=record.id;card.dataset.published=String(!!record.published);const image=document.createElement('img');image.src=record.src;image.alt=record.title;image.loading='lazy';const name=document.createElement('strong');name.textContent=record.title;const mark=document.createElement('small');mark.className='visibility111';mark.textContent=(record.published?'已发布':'私藏')+' · 云端'+(record.draft_path?' · 可继续编辑':' · 旧版图片');card.append(image,name,mark,button('浏览',()=>InkCloud75.openWork(record)),button('↓ 下载',async()=>{try{const local=await CloudDraft141.load(record);await CopyAlbums38.downloadWork178(local.id)}catch(e){A.toast(e.message)}}),button(record.draft_path?'继续编辑':'继续题写',async()=>{try{await CloudDraft141.edit(record)}catch(e){A.toast(e.message)}}),button('共书',async()=>{try{await SharedInk128.fromCloudWork142(record)}catch(e){A.toast(e.message)}}),button('删除',async()=>{if(!confirm('移入回收站？24 小时内可以恢复。'))return;try{await Trash144.cloud(record);await refreshMine()}catch(e){A.toast(e.message)}}));image.onclick=()=>InkCloud75.openWork(record);cloudHost.append(card)}paintWorks()}catch(e){if(request!==generation)return;cloudHost.append(document.createTextNode('云端作品暂未读取：'+e.message+'；本机作品可继续使用。'))}}
 document.addEventListener('work-autosaved128',e=>{pendingIds141.add(e.detail.id);paintWorks()});document.addEventListener('work-archived',e=>{pendingIds141.add(e.detail.id);paintWorks()});document.addEventListener('work-synced101',()=>refreshSyncMarks141().catch(()=>{}));
 $('worksDialog').addEventListener('toggle',()=>{if($('worksDialog').open)refreshMine()});let paintFrame153=0;new MutationObserver(()=>{if(paintFrame153)return;paintFrame153=requestAnimationFrame(()=>{paintFrame153=0;paintWorks()})}).observe($('worksGrid'),{childList:true,subtree:true});document.addEventListener('cloud-copies83',()=>{if($('worksDialog').open)refreshMine()});
 // Choose a source first. This capture precedes the old default-copy shortcut.
 window.addEventListener('click',e=>{const b=e.target.closest('#homeQuick47 button');if(b?.textContent.trim()!=='临帖')return;e.preventDefault();e.stopImmediatePropagation();A.openDialog('copyDialog')},true);
 // The three writing modes use their normal persisted mode configuration.

 // Native reference changes notify the settings without opening unrelated panels.
 function tab(name,render){const b=[...steps.children].find(x=>x.textContent.trim()===name);b.onclick=()=>{for(const s of steps.children)s.setAttribute('aria-current',String(s===b));effects.classList.remove('photoActive63','photoActive106','customStyle109');render()};return b}
 const presets=[
  {title:'引首·今日亲笔',key:'head',text:'今日亲笔',shape:'tall',layout:'horizontal',color:'#b62118',font:'yishan'},
  {title:'引首·亲笔书写',key:'head',text:'亲笔书写',shape:'tall',layout:'horizontal',color:'#d6ad38',font:'small'},
  {title:'落款·见墨如我',key:'tail',text:'见墨如我',shape:'square',layout:'horizontal',type:'yin',color:'#2867b1',font:'yishan'},
  {title:'落款·见字如面',key:'tail',text:'见字如面',shape:'square',layout:'horizontal',type:'yin',color:'#74549c',font:'small'}
 ];
 function stampOptions(){const row=document.createElement('div');row.className='sealPresets111';for(const p of [...presets,...(window.Seals129?.presets||[])]){const b=button(p.title,()=>{const preview=A.isOverview55();A.applySealPreset114(p.key,{...p,text:p.text,shape:p.shape,layout:p.layout,color:p.color,font:p.font,type:p.type||'yang',fontLoaded:true});A.persist();if(preview&&!A.isOverview55())$('fitView').click();stampOptions()});const c=document.createElement('canvas');c.width=c.height=100;const im=SealEngine.stamp({...p,type:p.type||'yang',rough:.12,fontLoaded:true});c.getContext('2d').drawImage(im,0,0,100,100);b.prepend(c);const item=A.sealItems().find(i=>i.key===p.key);b.setAttribute('aria-pressed',String(item?.config.text===p.text));row.append(b)}row.append(button('更多设置',()=>A.openDialog('sealDialog')));rail.replaceChildren(row)}tab('印章',stampOptions);
 const dock=document.createElement('div');dock.id='copyDock111';dock.setAttribute('aria-label','原帖参照：左右滑动换列');const tools=document.createElement('div');tools.id='copyTools111';const label=document.createElement('output');tools.append(button('上一列',()=>moveColumn(-1)),label,button('下一列',()=>moveColumn(1)));$('board').parentElement.append(dock,tools);let down=null;
 dock.onpointerdown=e=>{down={x:e.clientX,y:e.clientY};dock.setPointerCapture(e.pointerId);e.stopPropagation()};dock.onpointerup=e=>{if(down&&Math.abs(e.clientX-down.x)>24)moveColumn(e.clientX>down.x?1:-1);down=null;e.stopPropagation()};dock.onpointercancel=()=>{down=null};
 function moveColumn(delta){const n=+$('copyColumns111').value||1;$('copyColumn111').value=String(Math.max(0,Math.min(n-1,+$('copyColumn111').value+delta)));$('copyPan115').value='0';A.refresh();A.persist();dockState()}
 function dockState(){const layout=$('copyLayout111').value,on=!!A.getReference()&&!A.isOverview55()&&!document.body.classList.contains('home-open');dock.hidden=!on||layout==='background';tools.hidden=!on||layout==='background';dock.dataset.layout=layout;label.textContent=(+$('copyColumn111').value+1)+' / '+$('copyColumns111').value;}
 function setLayout(layout){window.previewComparison73=false;const preview=A.isOverview55();$('copyLayout111').value=layout;$('copyLayout111').dispatchEvent(new Event('change'));A.refresh();A.persist();if(preview&&!A.isOverview55())$('fitView').click();copyOptions();dockState()}
 function copyOptions(){window.Reference129?.renderPreview?.(rail)}tab('临帖',copyOptions);
 for(const e of ['reference-layout111','reference-set111','preview-painted94','mode-ready109','ink-view-changed90'])document.addEventListener(e,dockState);new MutationObserver(dockState).observe(document.body,{attributes:true,attributeFilter:['class']});
 const styleTab=[...steps.children].find(x=>x.textContent.trim()==='书风'),oldStyle=styleTab.onclick;styleTab.onclick=async e=>{await oldStyle.call(styleTab,e);rail.classList.add('styleRail111')};steps.addEventListener('click',()=>rail.classList.remove('styleRail111'),true);const numeric=$('lineStrength108Number');if(numeric){numeric.readOnly=true;numeric.tabIndex=-1;numeric.setAttribute('aria-label','综合书风数值（使用滑动块调节）')}
 // New cut-paper templates deliberately keep a square stone face for large grids.
 const big=$('bigDialog62');big.querySelector('h2').textContent='量字裁纸';if($('extendPaper63')){$('extendPaper63').title='量字裁纸';$('extendPaper63').setAttribute('aria-label','量字裁纸')}if($('topAddPaper90')){$('topAddPaper90').title='量字裁纸';$('topAddPaper90').setAttribute('aria-label','量字裁纸')} const quick=big.querySelector('.presets107');let selected=null;quick.addEventListener('click',e=>{if(e.target.closest('button')&&!e.target.closest('[data-template111]'))selected=null},true);
 const configs=[['双排五字竖联',5,2,'couplet'],['双排七字竖联',7,2,'couplet'],['百字格',10,10,'stone'],['千字格',50,20,'stone']];for(const [name,rows,cols,paper]of configs){if(quick.querySelector('[data-grid159="'+rows+':'+cols+'"]'))continue;const b=button(name,()=>{selected={rows,cols,paper};$('bigCount107').max='1000';$('bigBands107').max='1000';$('bigCount107').value=rows;$('bigBands107').value=cols;big.querySelector('select').value='vertical';for(const c of [$('bigCount107'),$('bigBands107')])c.dispatchEvent(new Event('input',{bubbles:true}));for(const other of quick.children)other.setAttribute('aria-pressed',String(other===b));apply.click()});b.dataset.template111=paper;quick.append(b)}
 const apply=$('applyBigPaper159'),oldApply=apply.onclick;apply.onclick=async e=>{if(!selected){$('paperPreset111').value='plain';return oldApply.call(apply,e)}const p=selected,old=A.getState(),single=+old.values.rows===1&&+old.values.columns===1;const preview=A.isOverview55();window.bigPaperLayout63={active:true,rows:p.rows,cols:p.cols,orientation:'vertical',reverseHorizontal:false,firstCell:null};await A.configure47({values:{ratio:String(4/(.36+3.52*p.rows/p.cols)),rows:String(p.rows),columns:String(p.cols),paperPreset111:p.paper,copyLayout111:'background',...(p.rows===10&&p.cols===10?{zoom:'500'}:p.rows===50&&p.cols===20?{zoom:'1000'}:{}),letterLayout:'custom',stationery:'vermillion',sceneChoice:'none',paperExtent:'fixed',papercolor:'#141414',ruling:'mi',showLines:'yes',followDirection:'vertical',guideMode:'off'},brushPatch:{color:'#fffaf0'},size:p.rows===10&&p.cols===10?8:p.rows===50&&p.cols===20?4:Math.max(2,Math.round(old.brush.size/(p.cols||1))),focus:'start'});A.applyLiteraryPalette61({paper:'#141414',ink:'#fffaf0',seal:'#b62118'});A.setPaletteCredit96({name:'碑刻留韵',referencePlace:'泰山石刻',referenceDescription:'摩崖石刻的苍劲与岁月肌理'});if(single&&old.flow.strokes.length)A.fitInkFirstCell107();if(preview&&!A.isOverview55())$('fitView').click();big.close();A.persist();};
 window.Revision111={ready:true,presets,stampOptions129:stampOptions,refreshMine,setLayout,moveColumn};dockState();
})();
