/* 第74版：首屏和手写面积、可移动参照书签与后台入口。 */
(function init(){if(!window.AnnotationApp?.ready||!window.Timeline73||!window.Status42||!document.getElementById('bottomIcons39')){setTimeout(init,55);return}
 const $=id=>document.getElementById(id),dock=$('bottomDock'),icons=$('bottomIcons39'),status=$('statusBar42'),toggle=$('dockToggle'),board=$('board');
 // Preserve the expansion control but move it into the last icon row. Remove the status bar completely.
 if(toggle&&!toggle.hidden){toggle.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M4 7h16M4 12h16M4 17h16"/></svg>';toggle.title='展开／收起底部工具';toggle.setAttribute('aria-label',toggle.title);icons.append(toggle)}const iconsToggle=$('bottomIconsToggle56');if(iconsToggle){icons.append(iconsToggle);iconsToggle.onclick=()=>{const collapsed=icons.classList.toggle('condensed74');iconsToggle.setAttribute('aria-expanded',String(!collapsed));iconsToggle.title=collapsed?'展开底部图标':'收起底部图标'}}if(status)status.remove();
 const display=document.createElement('output');display.id='writingStatus74';display.setAttribute('aria-label','当前笔径与缩放');board.append(display);function update(){display.textContent='笔径 '+Math.round(+$('size').value)+'  ·  '+Math.round(+$('zoom').value)+'%'}const sync=Status42.sync;Status42.sync=()=>{sync();update()};for(const id of ['size','zoom','quickSize'])for(const event of ['input','change'])$(id)?.addEventListener(event,update);update();
 // Front-end live edit remains available to administrators at the far right.
 const edit=document.querySelector('#topActions .liveEdit53');if(edit){edit.hidden=false;edit.classList.add('liveEditIcon74');edit.textContent='✎';edit.setAttribute('aria-label','实时编辑');edit.title='实时编辑';icons.append(edit);function auth(){edit.hidden=!InkStudio50.isAdmin}document.addEventListener('admin-unlocked53',auth);auth()}
 // Use absolute pointer coordinates and inline important styles to override earlier modal geometry.
 const bookmark=$('dailyDialog'),grip=bookmark?.querySelector('.dialogHead');if(grip){grip.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('button'))return;e.stopImmediatePropagation();e.preventDefault();const bounds=bookmark.getBoundingClientRect(),ox=e.clientX-bounds.left,oy=e.clientY-bounds.top;grip.setPointerCapture(e.pointerId);function move(p){bookmark.style.setProperty('left',Math.max(0,Math.min(innerWidth-bounds.width,p.clientX-ox))+'px','important');bookmark.style.setProperty('top',Math.max(0,Math.min(innerHeight-bounds.height,p.clientY-oy))+'px','important')}function end(){grip.removeEventListener('pointermove',move);grip.removeEventListener('pointerup',end);grip.removeEventListener('pointercancel',end)}grip.addEventListener('pointermove',move);grip.addEventListener('pointerup',end);grip.addEventListener('pointercancel',end)},{capture:true})}
})();
