(async function init(){if(!window.Revision46?.ready||!window.AnnotationHome){setTimeout(init,30);return}const $=id=>document.getElementById(id),app=AnnotationApp;
const create=(tag,attrs={},value)=>{const e=document.createElement(tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(value!==undefined)e.textContent=value;return e};
function dialog(id,title){document.getElementById(id)?.remove();const d=create('dialog',{id}),h=create('div',{class:'dialogHead'}),b=create('div',{class:'dialogBody'}),close=create('button',{},'完成 ×');h.append(create('h2',{},title),close);d.append(h,b);document.body.append(d);close.onclick=()=>d.close();return {d,b}}
const nav=$('annotationCategories');document.querySelector('.annotationGallery').after(nav);const quick=create('nav',{id:'homeQuick47','aria-label':'常用书写入口'});nav.after(quick);
async function preset(name){document.dispatchEvent(new Event('writing-scenario47'));if(app.hasInk()&&!confirm('切换书写布局会保留当前墨迹。是否继续？'))return;const values={ratio:'0.75',showLines:'yes',inkMode:'assist',paperPattern:'dragon',followDirection:'vertical',sceneChoice:'none',paperExtent:'fixed',photoMode:'hero2',ruling:'vertical',letterLayout:'custom',zoom:'400',columns:'6',rows:'8'};let config={values,preset:'zhang',size:18,inkOpacity:1,focus:'start'};if(name==='single'){Object.assign(values,{ratio:'1',rows:'1',columns:'1',letterLayout:'1,1,vertical',zoom:'100',ruling:'none',showLines:'no'});config.preset='ouyang';config.size=400}if(name==='letter'){Object.assign(values,{stationery:'letter',zoom:'300',columns:'6'})}if(name==='copy'){Object.assign(values,{zoom:'300',ruling:'hui',paperExtent:'infinite'});config.inkOpacity=.5}await app.configure47(config);app.showWriter();if(name==='copy')app.openDialog('copyDialog')}
for(const[key,name]of [['single','单字'],['letter','写信'],['copy','临帖']]){const b=create('button',{},name);b.onclick=()=>preset(key);quick.append(b)}
$('continueWriting').onclick=async()=>{if(!app.hasInk())await app.configure47({values:{ratio:'0.75',ruling:'vertical',showLines:'yes',zoom:'400',inkMode:'assist',paperPattern:'dragon'},size:18,inkOpacity:1,focus:'start'});app.showWriter()};
$('appLogo').style.cursor='pointer';$('appLogo').setAttribute('role','button');$('appLogo').setAttribute('aria-label','回到首页');$('appLogo').tabIndex=0;$('appLogo').onclick=()=>AnnotationHome.show();$('appLogo').onkeydown=e=>{if(e.key==='Enter')AnnotationHome.show()};
const first=await DraftStore.get('ui47.defaults').catch(()=>false);if(!first){$('quotesVisibility').value='shown';$('quotesVisibility').dispatchEvent(new Event('change'));document.body.classList.remove('quotes-hidden');if(!app.hasInk())await app.configure47({values:{ratio:'0.75',ruling:'vertical',showLines:'yes',zoom:'400',inkMode:'assist',paperPattern:'dragon'},size:18,inkOpacity:1,focus:'start'});await DraftStore.set('ui47.defaults',true)}
// Keep serialized legacy carrier controls, but remove their duplicated UI from settings.
$('stationery').closest('label')?.setAttribute('hidden','');$('stationeryChoices')?.setAttribute('hidden','');
const pad=create('div',{id:'panPad47','aria-label':'按一个字的位置移动纸张'});for(const[label,dx,dy]of [['↑',0,-1],['←',-1,0],['→',1,0],['↓',0,1]]){const b=create('button',{'aria-label':'移纸 '+label},label);b.onpointerdown=e=>e.stopPropagation();b.onclick=()=>app.nudge47(dx,dy);pad.append(b)}$('board').append(pad);
const sizeDialog=dialog('sizeModes47','笔径与书写位置');const n=create('input',{type:'number',min:'1',max:'1000','aria-label':'笔径'});sizeDialog.b.append(n);const modes=create('div',{class:'actions47'});for(const[label,size,focus]of [['正文 · 18',18,'start'],['落款 · 12',12,'signature']]){const b=create('button',{},label);b.onclick=async()=>{await app.configure47({values:{zoom:'400',inkMode:'assist'},size,focus});sizeDialog.d.close();app.showWriter()};modes.append(b)}sizeDialog.b.append(modes);n.onchange=()=>{const v=Math.max(1,Math.min(1000,+n.value||18));$('sizeNumber').value=v;$('sizeNumber').dispatchEvent(new Event('change'));app.updatePosition()};$('topSize').onclick=()=>{n.value=app.getState().brush.size;app.openDialog('sizeModes47')};
const opacityLabel=create('label',{},'墨迹不透明度');const op=create('input',{type:'range',min:'1',max:'100',value:String(Math.round((window.annotationInkOpacity??1)*100))});const out=create('output',{},op.value+'%');opacityLabel.append(op,out);sizeDialog.b.append(opacityLabel);op.oninput=()=>{window.annotationInkOpacity=+op.value/100;out.textContent=op.value+'%';app.refresh();app.persist()};
const settings=dialog('toolSettings47','快捷按钮设置'),table=create('table',{class:'toolbarTable47'});table.innerHTML='<thead><tr><th>功能</th><th>顶部</th><th>底部</th><th>排序</th></tr></thead><tbody></tbody>';settings.b.append(create('p',{class:'notice47'},'勾选显示位置；拖动整行或点上下箭头排序。设置自动保存，更新版本后保留。'),table);
const parking=create('div',{id:'toolParking47'});document.body.append(parking);const registry=new Map();const topDefaults=['annotationHomeButton','myWorks','selectInk','undo','redo','clear','fitView','topQuotes','recordProcess'];const bottomDefaults=['menuToggle','topSize','export','topOptimize','copyPagesQuick39','photoSettingsQuick42','topLines','topInk','inkScope39','calendarMoments','topReset','lockWriting39','styleCycle39','topDirection','topAuto','topMusic','topStart'];
for(const id of [...topDefaults,...bottomDefaults,'topRemove','topUpload','topPattern','topRatio','topMount','topParticle','topGuide']){const e=$(id);if(e){registry.set(id,{id,button:e,title:e.getAttribute('aria-label')||e.title||id});e.removeAttribute('aria-hidden')}}
const other=create('button',{id:'toolSettingsQuick47',title:'配置快捷按钮','aria-label':'配置快捷按钮'});other.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M3 6h18M3 12h18M3 18h18"/><circle cx="8" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="10" cy="18" r="2"/></svg>';other.onclick=()=>{renderTable();app.openDialog('toolSettings47')};registry.set(other.id,{id:other.id,button:other,title:'配置快捷按钮'});bottomDefaults.push(other.id);
// Every value-setting control gets an optional targeted shortcut as well.
for(const e of document.querySelectorAll('dialog input[id],dialog select[id],dialog textarea[id]')){if(e.type==='hidden'||e.closest('#toolSettings47')||e.closest('[hidden]'))continue;const label=e.closest('label');if(!label)continue;const id='setting47-'+e.id,title=(label.childNodes[0]?.textContent||e.id).trim().slice(0,30);const b=create('button',{id,title,'aria-label':title});b.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/></svg>';b.onclick=()=>{app.openDialog(e.closest('dialog').id);requestAnimationFrame(()=>{e.scrollIntoView({block:'center'});e.focus({preventScroll:true})})};registry.set(id,{id,button:b,title})}
let config=await DraftStore.get('toolbar47').catch(()=>null);if(!config){const old=window.toolbarOrder?.();config={version:47,order:[...new Set([...(old?.top||topDefaults),...(old?.bottom||bottomDefaults),...registry.keys()])],top:old?.top||topDefaults,bottom:[...new Set([...(old?.bottom||bottomDefaults),'toolSettingsQuick47'])]}}
function normalize(c){const ids=[...registry.keys()];return {version:47,order:[...new Set([...(c?.order||[]).filter(x=>registry.has(x)),...ids])],top:(c?.top||[]).filter(x=>registry.has(x)),bottom:(c?.bottom||[]).filter(x=>registry.has(x))}}
function apply(c){config=normalize(c);for(const id of config.order){const item=registry.get(id),b=item.button;document.querySelector('[data-mirror47="'+id+'"]')?.remove();b.hidden=false;b.removeAttribute('aria-hidden');if(config.top.includes(id))$('topActions').append(b);else if(config.bottom.includes(id))$('bottomIcons39').append(b);else parking.append(b);if(config.top.includes(id)&&config.bottom.includes(id)){const copy=b.cloneNode(true);copy.removeAttribute('id');copy.dataset.mirror47=id;copy.onclick=()=>b.click();$('bottomIcons39').append(copy)}}}
async function save(){try{await DraftStore.set('toolbar47',config);await app.saveCurrentSettings();document.dispatchEvent(new Event('settings-changed47'))}catch{app.toast('按钮设置未保存，请重试')}}
window.toolbarOrder=()=>({...config,top:[...$('topActions').children].map(e=>e.id).filter(x=>registry.has(x)),bottom:[...$('bottomIcons39').children].map(e=>e.dataset.mirror47||e.id).filter(x=>registry.has(x)),order:[...new Set([...$('topActions').children,...$('bottomIcons39').children].map(e=>e.dataset.mirror47||e.id).filter(x=>registry.has(x)).concat(config.order))]});
window.restoreToolbarOrder=c=>{if(c?.version===47){apply(c);DraftStore.set('toolbar47',config)}else apply(config)};
let dragId=null;function renderTable(){const tbody=table.tBodies[0];tbody.replaceChildren();for(const id of config.order){const item=registry.get(id),tr=create('tr',{draggable:'true','data-tool':id}),label=create('td');label.innerHTML=item.button.querySelector('svg')?.outerHTML||'';label.append(document.createTextNode(item.title));tr.append(label);for(const side of ['top','bottom']){const td=create('td'),input=create('input',{type:'checkbox','aria-label':item.title+'显示在'+(side==='top'?'顶部':'底部')});input.checked=config[side].includes(id);input.onchange=()=>{config[side]=input.checked?[...config[side],id]:config[side].filter(x=>x!==id);apply(config);save()};td.append(input);tr.append(td)}const td=create('td');for(const[txt,step]of [['↑',-1],['↓',1]]){const b=create('button',{},txt);b.onclick=()=>{const i=config.order.indexOf(id),j=i+step;if(j<0||j>=config.order.length)return;[config.order[i],config.order[j]]=[config.order[j],config.order[i]];apply(config);renderTable();save()};td.append(b)}tr.append(td);tr.ondragstart=()=>dragId=id;tr.ondragover=e=>e.preventDefault();tr.ondrop=e=>{e.preventDefault();if(dragId===id)return;config.order=config.order.filter(x=>x!==dragId);config.order.splice(config.order.indexOf(id),0,dragId);apply(config);renderTable();save()};tbody.append(tr)}}
apply(config);for(const row of [$('topActions'),$('bottomIcons39')])row.addEventListener('pointerup',()=>{setTimeout(()=>{config=normalize(window.toolbarOrder());DraftStore.set('toolbar47',config)},0)});
for(const d of document.querySelectorAll('dialog .settingsTabs')){const b=create('button',{},'快捷按钮');b.onclick=()=>{renderTable();app.openDialog('toolSettings47')};d.append(b)}
// Existing settings and icons are now ready in their final persisted positions.
window.Revision47={ready:true,preset,create,dialog,registerTool:(id,title,path,fn)=>{const b=create('button',{id,title,'aria-label':title});b.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6">'+path+'</svg>';b.onclick=fn;registry.set(id,{id,title,button:b});config.order.push(id);apply(config);return b},toolbar:()=>config};
document.documentElement.classList.add('ui-ready');app.updatePosition();window.dispatchEvent(new Event('resize'));
})();
