/* One reference controller for the preview rail, main menu and floating panorama. */
(function init129(){
 if(!window.Revision128?.ready||!window.TouchOrder129?.render||!window.ReferenceAnalysis129||!window.ReferenceIO129){setTimeout(init129,80);return}
 const A=AnnotationApp,C=CopyAlbums38,$=id=>document.getElementById(id),T=TouchOrder129;
 const icon=T.icon,paths={close:'M6 6l12 12M18 6L6 18',prev:'M15 5l-7 7 7 7',next:'M9 5l7 7-7 7',target:'M12 2v4M12 18v4M2 12h4M18 12h4M7 7h10v10H7z',fit:'M4 9V4h5M15 4h5v5M20 15v5h-5M9 20H4v-5',upload:'M12 16V3m-4 4 4-4 4 4M4 14v7h16v-7',book:'M4 4h7l1 2 1-2h7v15h-7l-1 2-1-2H4zM12 6v14',edit:'M4 20l1-5L17 3l4 4L9 19z',settings:'M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M10 15v6',image:'M3 4h18v16H3zM3 16l6-6 5 5 3-3 4 4'};
 const E=(tag,text,cls)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e};
 function button(host,title,path,fn){const b=E('button',null,'referenceButton129');b.type='button';b.title=b.ariaLabel=title;b.innerHTML=icon(paths[path]||path)+'<span></span>';b.querySelector('span').textContent=title;b.onclick=async()=>{try{await fn()}catch(e){A.toast(e.message||'操作未完成')}};host.append(b);return b}
 const settings={floating:false,follow:true,auto:false,pause:3.5,rows:7,detail:false,layout:'background',opacity:20};try{Object.assign(settings,JSON.parse(localStorage.getItem('reference.settings129')||'{}'))}catch{}settings.layout='background';settings.detail=false;settings.auto=false;settings.pause=Math.max(3.5,Number(settings.pause)||3.5);
 let current={row:0,col:0},profile=null,profileJob=0,advanceTimer=0,previewHost=null,imageURL='',imageGeneration=0,loadedReference=null,pendingReference=null,pendingImage=null,manuallySized=false,zoom=1,pan={x:0,y:0},points=new Map(),gesture=null,lastTap=null,windowDrag=null;
 const floating=E('section',null,'referenceFloat129');floating.hidden=true;floating.innerHTML='<div class="referenceViewport129"><div class="referencePlane129"><img draggable="false" alt="原帖全景"><i class="referenceFocus129" aria-label="当前列"></i><i class="referenceGlyph131" aria-label="当前字米字格"></i></div></div><header><strong>原帖</strong><button data-close aria-label="关闭原帖浮窗">'+icon(paths.close)+'</button></header><footer><button data-follow aria-label="跟随字位" title="跟随字位">'+icon(paths.target)+'</button><button data-prev aria-label="上一页" title="上一页">'+icon(paths.prev)+'</button><button data-next aria-label="下一页" title="下一页">'+icon(paths.next)+'</button></footer><button data-resize aria-label="调整浮窗尺寸">'+icon('M10 20l10-10M15 20l5-5')+'</button>';$('board').append(floating);
 for(const type of ['pointerdown','pointermove','pointerup','pointercancel','wheel','contextmenu'])floating.addEventListener(type,e=>{e.stopPropagation();if(type==='contextmenu')e.preventDefault()});
 const viewport=floating.querySelector('.referenceViewport129'),plane=floating.querySelector('.referencePlane129'),red=floating.querySelector('.referenceFocus129');let image=floating.querySelector('img');
 function persist(){try{localStorage.setItem('reference.settings129',JSON.stringify(settings))}catch{}A.persist()}
 function cell(row=current.row,col=current.col){const columns=A.referenceCells128()||[],c=columns[col],g=c?.glyphs?.[Math.min(row,(c?.glyphs?.length||1)-1)],cols=columns.length||+$('columns').value||1,rows=Math.max(1,settings.rows);return{x:Math.max(0,(c?.x??1-(col+.5)/cols)-(c?.w??1/cols)/2),y:Math.max(0,(g?.y??(Math.min(row,rows-1)+.5)/rows)-(g?.h??1/rows)/2),w:c?.w??1/cols,h:g?.h??1/rows}}
 function transform(){if(!image.naturalWidth)return;const k=Math.min(viewport.clientWidth/image.naturalWidth,viewport.clientHeight/image.naturalHeight),w=image.naturalWidth*k,h=image.naturalHeight*k;plane.style.width=w+'px';plane.style.height=h+'px';plane.style.transform='translate('+pan.x+'px,'+pan.y+'px) scale('+zoom+')';const c=cell();Object.assign(red.style,{left:c.x*w+'px',top:'0px',width:c.w*w+'px',height:h+'px'});const glyph=floating.querySelector('.referenceGlyph131');Object.assign(glyph.style,{left:c.x*w+'px',top:c.y*h+'px',width:c.w*w+'px',height:c.h*h+'px'});glyph.hidden=!settings.follow;red.style.borderWidth=(1.6/zoom)+'px';red.hidden=!settings.follow;floating.querySelector('[data-follow]').setAttribute('aria-pressed',String(settings.follow))}
 function fit(){zoom=1;const k=Math.min(viewport.clientWidth/image.naturalWidth,viewport.clientHeight/image.naturalHeight);pan={x:(viewport.clientWidth-image.naturalWidth*k)/2,y:(viewport.clientHeight-image.naturalHeight*k)/2};transform()}
 function closeup(){const c=cell(),k=Math.min(viewport.clientWidth/image.naturalWidth,viewport.clientHeight/image.naturalHeight),w=image.naturalWidth*k,h=image.naturalHeight*k;zoom=Math.min(20,Math.max(1,.9*Math.min(viewport.clientWidth/(c.w*w),viewport.clientHeight/(c.h*h))));pan={x:viewport.clientWidth/2-(c.x+c.w/2)*w*zoom,y:viewport.clientHeight/2-(c.y+c.h/2)*h*zoom};transform()}
 function sizeFloat(){if(manuallySized||!image.naturalWidth||!image.naturalHeight)return;const area=$('board').getBoundingClientRect(),size=ReferenceIO129.fitWindow(image.naturalWidth,image.naturalHeight,Math.min(240,Math.max(140,area.width*.36)),Math.min(380,Math.max(170,area.height*.5)));floating.style.width=size.width+'px';floating.style.height=size.height+'px'}
 async function loadImage(){const token=++imageGeneration,ref=A.getReference();if(!settings.floating||!ref){floating.hidden=true;return}if(loadedReference!==ref){if(pendingReference!==ref){pendingReference=ref;pendingImage=ReferenceIO129.capture(ref).catch(error=>{if(pendingReference===ref){pendingReference=null;pendingImage=null}throw error})}let next;try{next=await pendingImage}catch(error){if(token!==imageGeneration)return;throw error}if(token!==imageGeneration)return;next.alt='原帖全景';next.draggable=false;image.replaceWith(next);image=next;loadedReference=ref;manuallySized=false}if(token!==imageGeneration)return;const album=C.active,page=album?.pages[album.index];floating.querySelector('strong').textContent=page?.name||album?.title||'原帖';floating.hidden=false;sizeFloat();fit();navState()}
 function navState(){const a=C.active;floating.querySelector('[data-prev]').disabled=!a||a.index===0;floating.querySelector('[data-next]').disabled=!a||a.index>=a.pages.length-1}
 async function pageChange(delta){await C.change128(delta);await loadImage();await analyzeCurrent();navState()}
 floating.querySelector('[data-close]').onclick=()=>{settings.floating=false;imageGeneration++;floating.hidden=true;persist();refreshSettings()};floating.querySelector('[data-prev]').onclick=()=>pageChange(-1).catch(e=>A.toast(e.message));floating.querySelector('[data-next]').onclick=()=>pageChange(1).catch(e=>A.toast(e.message));floating.querySelector('[data-follow]').onclick=()=>{settings.follow=!settings.follow;if(settings.follow)fit();transform();persist()};
 const center=()=>{const p=[...points.values()];return{x:p.reduce((n,a)=>n+a.x,0)/p.length,y:p.reduce((n,a)=>n+a.y,0)/p.length,d:p.length===2?Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y):0}};
 viewport.onpointerdown=e=>{e.preventDefault();points.set(e.pointerId,{x:e.clientX,y:e.clientY});viewport.setPointerCapture(e.pointerId);gesture={...center(),time:e.timeStamp,start:{x:e.clientX,y:e.clientY},multi:points.size>1,moved:false};if(points.size>1)lastTap=null};
 viewport.onpointermove=e=>{if(!points.has(e.pointerId))return;e.preventDefault();points.set(e.pointerId,{x:e.clientX,y:e.clientY});const c=center(),g=gesture;if(!g)return;const box=viewport.getBoundingClientRect();if(points.size===2&&c.d&&g.d){const factor=Math.max(1,Math.min(20,zoom*c.d/g.d))/zoom;pan={x:c.x-box.left-(g.x-box.left-pan.x)*factor,y:c.y-box.top-(g.y-box.top-pan.y)*factor};zoom*=factor;g.multi=true}else{pan.x+=c.x-g.x;pan.y+=c.y-g.y}if(Math.hypot(c.x-g.start.x,c.y-g.start.y)>5)g.moved=true;gesture={...g,...c};transform()};
 viewport.onpointerup=e=>{if(!points.has(e.pointerId))return;const g=gesture;points.delete(e.pointerId);if(points.size){gesture={...g,...center(),multi:true};return}gesture=null;if(!g?.multi&&!g?.moved&&e.timeStamp-g.time<300){if(lastTap&&e.timeStamp-lastTap.t<340&&Math.hypot(e.clientX-lastTap.x,e.clientY-lastTap.y)<24){lastTap=null;selectAt(e.clientX,e.clientY);closeup()}else lastTap={t:e.timeStamp,x:e.clientX,y:e.clientY}}};viewport.onpointercancel=e=>{points.delete(e.pointerId);gesture=null;lastTap=null};viewport.onwheel=e=>{e.preventDefault();zoom=Math.min(20,Math.max(1,zoom*Math.exp(-e.deltaY*.002)));transform()};
 function selectAt(x,y){const box=viewport.getBoundingClientRect(),k=Math.min(viewport.clientWidth/image.naturalWidth,viewport.clientHeight/image.naturalHeight),px=(x-box.left-pan.x)/(image.naturalWidth*k*zoom),py=(y-box.top-pan.y)/(image.naturalHeight*k*zoom),columns=A.referenceCells128()||[];const col=columns.length?columns.reduce((best,c,i)=>Math.abs(c.x-px)<Math.abs(columns[best].x-px)?i:best,0):Math.max(0,Math.min(+$('columns').value-1,Math.floor((1-px)*+$('columns').value)));const glyphs=columns[col]?.glyphs||[];const row=glyphs.length?glyphs.reduce((best,g,i)=>Math.abs(g.y-py)<Math.abs(glyphs[best].y-py)?i:best,0):Math.max(0,Math.min(settings.rows-1,Math.floor(py*settings.rows)));setCell(row,col);A.focusCell129(row,col);persist()}
 floating.querySelector('header').onpointerdown=e=>{if(e.target.closest('button'))return;e.preventDefault();const box=floating.getBoundingClientRect();windowDrag={id:e.pointerId,x:e.clientX,y:e.clientY,left:floating.offsetLeft,top:floating.offsetTop,resize:false};floating.setPointerCapture(e.pointerId)};
 floating.querySelector('[data-resize]').onpointerdown=e=>{e.preventDefault();e.stopPropagation();windowDrag={id:e.pointerId,x:e.clientX,y:e.clientY,width:floating.offsetWidth,height:floating.offsetHeight,resize:true};floating.setPointerCapture(e.pointerId)};
 floating.onpointermove=e=>{if(windowDrag?.id!==e.pointerId)return;const g=windowDrag,dx=e.clientX-g.x,dy=e.clientY-g.y;if(g.resize){manuallySized=true;floating.style.width=Math.max(100,Math.min($('board').clientWidth-10,g.width+dx))+'px';floating.style.height=Math.max(100,Math.min($('board').clientHeight-10,g.height+dy))+'px';transform()}else{floating.style.left=Math.max(0,Math.min(innerWidth-floating.offsetWidth,g.left+dx))+'px';floating.style.top=Math.max(50,Math.min(innerHeight-60,g.top+dy))+'px'}};floating.onpointerup=floating.onpointercancel=()=>windowDrag=null;
 function setCell(row,col){row=Math.max(0,Math.min(A.writingGrid67().rows-1,row));col=Math.max(0,Math.min(A.writingGrid67().cols-1,col));if(current.row===row&&current.col===col)return;current={row,col};transform();if(settings.detail)A.refresh();document.dispatchEvent(new CustomEvent('reference-cell129',{detail:current}))}
 function drawBackground(t,b,scale,dock){return window.Reference131?.drawBackground(t,b,scale,dock)||false}
 function refreshSettings(){if(previewHost?.isConnected&&[...$('previewEffects55').querySelectorAll('[aria-current=true]')].some(b=>b.textContent.trim()==='临帖'))renderControls(previewHost);if(copyDialog.open)renderMenu()}
 function inputRow(host,title,type,value,onchange){const l=E('label',null,'referenceField129'),span=E('span',title),input=E('input');input.type=type;if(type==='checkbox')input.checked=!!value;else input.value=value;l.append(span,input);input.onchange=()=>onchange(type==='checkbox'?input.checked:Number(input.value));host.append(l);return input}
 function renderControls(host){if(window.Reference131)return Reference131.renderControls(host);host.replaceChildren()}
 const copyDialog=$('copyDialog'),legacy=E('div',null,'legacyReference129');legacy.hidden=true;const oldBody=copyDialog.querySelector('.dialogBody');legacy.append(...oldBody.childNodes);document.body.append(legacy);copyDialog.querySelector('.settingsTabs')?.remove();copyDialog.querySelector('h2').textContent='临帖 · 原帖与设定';const controls=E('section',null,'referenceControls129'),catalog=E('section',null,'referenceCatalog129');oldBody.append(controls,catalog);let pickerOnly=false;
 function renderMenu(){renderControls(controls);catalog.replaceChildren();const header=E('div',null,'referenceCatalogHead129');header.append(E('h3','选择原帖'));button(header,'名帖管理','settings',openCatalogueManager);catalog.append(header);const list=E('div',null,'referenceCatalogueList129');catalog.append(list);for(const c of Timeline73.chapters.filter(c=>!Timeline73.data129(c).deleted)){const data=Timeline73.data129(c);const b=E('button');b.type='button';b.append(E('strong',data.title),E('small',[data.era||c.era,data.script||c.script,data.pages?.length?data.pages.length+' 页':'待上传'].filter(Boolean).join(' · ')));b.onclick=async()=>{b.disabled=true;try{await Timeline73.openCopy(c);copyDialog.close()}catch(e){A.toast(e.message)}finally{b.disabled=false}};list.append(b)}for(const p of Revision62.getPresets()){const b=E('button',p.title);b.onclick=async()=>{try{await C.openPages55(p);copyDialog.close();await entered()}catch(e){A.toast(e.message)}};list.append(b)}controls.hidden=pickerOnly}
 function openPicker(){pickerOnly=true;renderMenu();A.openDialog('copyDialog')}
 function openSettings(){const tab=[...$('previewEffects55').querySelectorAll('.finalSteps54 button,.finalSteps55 button,button')].find(b=>b.textContent.trim()==='临帖');if(tab){Revision97.setPart('config',false);tab.click()}else{pickerOnly=false;renderMenu();A.openDialog('copyDialog')}}
 copyDialog.addEventListener('toggle',()=>{if(copyDialog.open){pickerOnly=!A.getReference();renderMenu()}});
 const originalUpload=$('upload').onchange;$('upload').onchange=async e=>{await originalUpload.call($('upload'),e);await entered()};
 async function entered(){if(!A.getReference())return;await A.configure47({size:15,mountKey:'bare',brushPatch:{lineStrength108:100},values:{zoom:'500',rows:String(Math.max(settings.rows,...A.referenceCells128().map(c=>c.glyphs?.length||0))),columns:String(A.referenceCells128().length||6),copyLayout111:'background',opacity:String(settings.opacity)}});A.showWriter();if(!A.isOverview55())$('fitView').click();window.Reference131?.entered();await loadImage();await analyzeCurrent();openSettings()}
 async function analyzeCurrent(){const job=++profileJob,ref=A.getReference();if(!ref)return;const a=C.active,p=a?.pages[a.index];const nextProfile=(p?.analysis129?.version===131?p.analysis129:null)||await ReferenceAnalysis129.analyze(ref,[p?.name,a?.title,p?.filename,p?.image?.name].filter(Boolean).join(' '),A.presets);if(job!==profileJob)return;profile=nextProfile;if(p){p.analysis129=profile;await C.persist129()}refreshSettings()}
 const thumbHost=E('div',null,'referenceThumbs129');$('albumImage38').after(thumbHost);let thumbsURLs=[];
 function pagesForPreview(){return C.viewed||C.active}
 function picture(p){if(typeof p.image==='string')return new URL(p.image,location.href).href;const u=URL.createObjectURL(p.image);thumbsURLs.push(u);return u}
 function renderThumbs(){thumbsURLs.forEach(URL.revokeObjectURL);thumbsURLs=[];const album=pagesForPreview();if(!album)return;T.render(thumbHost,album.pages,{name:p=>p.name||String(p.image).split('/').at(-1),image:picture,move:C.albums.includes(album)?async(from,to)=>{await C.reorder128(from,to,album.id);renderThumbs()}:null})}
 new MutationObserver(renderThumbs).observe($('albumImage38'),{attributes:true,attributeFilter:['src']});document.addEventListener('copy-order128',renderThumbs);
 function openOrder(){const album=C.active;if(!album)return A.toast('请先选择或上传原帖');const d=E('dialog',null,'referenceOrderDialog129'),head=E('header',null,'dialogHead');head.append(E('h2','组图 · 长按拖动排序'));button(head,'关闭','close',()=>d.close());d.append(head);const rows=E('div');d.append(rows);const urls=[];const image=p=>{if(typeof p.image==='string')return new URL(p.image,location.href).href;const u=URL.createObjectURL(p.image);urls.push(u);return u};function draw(){urls.forEach(URL.revokeObjectURL);urls.length=0;T.render(rows,album.pages,{name:p=>p.name||'原帖',image,move:async(from,to)=>{await C.reorder128(from,to,album.id);draw()},open:async(p,i)=>{await C.select128(i);d.close();copyDialog.close();await entered()}})}d.addEventListener('close',()=>{urls.forEach(URL.revokeObjectURL);d.remove()});document.body.append(d);draw();d.showModal()}
 async function openCatalogueManager(){const admin=InkStudio50.isAdmin,d=E('dialog',null,'referenceManager129'),head=E('header',null,'dialogHead');head.append(E('h2','经典名帖 · 统一编排'));button(head,'关闭','close',()=>d.close());if(admin)button(head,'新增名帖','book',()=>{d.close();Timeline73.add129()});d.append(head);if(admin&&!TimelineCloud74.hasToken()){const token=E('input');token.type='password';token.placeholder='GitHub 临时管理令牌（仅本页内存）';d.append(token);button(d,'连接管理','settings',()=>{TimelineCloud74.connect(token.value.trim());token.value='';A.toast('已连接本页管理')})}d.append(E('p',admin?'长按拖动编排顺序，点击维护可修订、上传组图或删除。':'点击名帖选择临写；管理功能供管理员使用。'));const list=E('div');d.append(list);function draw(){const chapters=Timeline73.chapters.filter(c=>!Timeline73.data129(c).deleted);T.render(list,chapters,{name:c=>{const p=Timeline73.data129(c);return [p.era||c.era,p.title].filter(Boolean).join(' · ')},open:c=>admin?(d.close(),Timeline73.edit129(c)):(d.close(),Timeline73.openCopy(c)),move:admin?async(from,to)=>{const ordered=T.move(chapters,from,to).map(c=>c.id);await TimelineCloud74.publishOrder129(ordered);Timeline73.sort129();Timeline73.refresh();draw()}:null,actions:(card,c)=>{if(admin)button(card,'维护','edit',()=>{d.close();Timeline73.edit129(c)})}})}document.body.append(d);draw();d.addEventListener('close',()=>d.remove());d.showModal()}
 async function nextCell(){clearTimeout(advanceTimer);if(A.isDrawing128())return;const grid=A.writingGrid67();let {row,col}=current;if(A.getState().values.followDirection==='horizontal'){if(++col>=grid.cols){col=0;row++}}else if(++row>=grid.rows){row=0;col++}if(row>=grid.rows||col>=grid.cols)return nextPaper();A.focusCell129(row,col);setCell(row,col)}
 async function nextPaper(){clearTimeout(advanceTimer);await C.saveCurrent();await Revision128.saveOnSwitch129();if(C.active&&C.active.index<C.active.pages.length-1)await C.change128(1);else if(C.active)await C.newPaper128();else await A.startSeriesPage119(A.getState());await loadImage();await analyzeCurrent()}
 document.addEventListener('copy-cell128',e=>setCell(e.detail.row,e.detail.col));document.addEventListener('ink-stroke',e=>{if(!C.active||C.paused129||localStorage.getItem('iinnkk.mode53')!=='copy')return;const p=e.detail.points[Math.floor(e.detail.points.length/2)],g=A.writingGrid67(),a=g.area;setCell(Math.max(0,Math.floor((p.y-a.y)/g.dy)),Math.max(0,Math.floor((a.x+a.w-p.x)/g.dx)));});$('live').addEventListener('pointerdown',()=>clearTimeout(advanceTimer),true);
 document.addEventListener('copy-page128',()=>{current={row:0,col:0};loadImage().then(analyzeCurrent).catch(e=>A.toast(e.message));navState()});document.addEventListener('mode-changed54',()=>{if(localStorage.getItem('iinnkk.mode53')!=='copy'){floating.hidden=true;clearTimeout(advanceTimer)}});document.addEventListener('timeline-cloud74',()=>{if(copyDialog.open)renderMenu()});window.addEventListener('resize',()=>{sizeFloat();transform()});
 function syncFloat(){floating.hidden=!settings.floating||!A.getReference()||document.body.classList.contains('home-open')||localStorage.getItem('iinnkk.mode53')!=='copy'}new MutationObserver(syncFloat).observe(document.body,{attributes:true,attributeFilter:['class']});
 // Remove old visible controls; their hidden input values remain the engine's serialization contract.
 $('copyNav80')?.remove();$('copyEnd38').onclick=null;$('copyEnd38').disabled=true;$('copyTools111').hidden=true;for(const id of ['usePractice','removeRef'])$(id).disabled=true;
 window.Reference129={ready:true,renderPreview:host=>{previewHost=host;renderControls(host)},openSettings,openPicker,drawBackground,entered,cell,setCell,openCatalogueManager,refreshSettings,settings,loadImage,get profile(){return profile}};
 renderMenu();if(A.getReference())loadImage().then(analyzeCurrent).catch(()=>{});
})();
