(function init107(){
 if(!window.Features106?.ready){setTimeout(init107,40);return}
 const A=AnnotationApp,$=id=>document.getElementById(id),left=$('writerLeft90'),effects=$('previewEffects55');
 function caption(b,name){if(!b)return;b.hidden=false;b.classList.add('tool90');b.dataset.caption90=name;const svg=b.querySelector('svg')?.cloneNode(true);b.replaceChildren();if(svg)b.append(svg);else b.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M4 4h16v16H4zM8 8h8M8 12h8M8 16h5"/></svg>';const s=document.createElement('span');s.textContent=name;b.append(s);b.title=name;b.setAttribute('aria-label',name)}
 for(const [id,name]of [['topSize','笔径'],['topLines','线条'],['topAuto','走纸'],['topInk','墨色'],['topMusic','音乐']]){caption($(id),name);left.append($(id))}
 for(const id of ['annotationHomeButton','myWorks','topQuotes','topAddPaper90','topSize','topAuto','topLines','topInk','topMusic','recordProcess','selectInk'])if($(id))left.append($(id));
 document.body.classList.add('tools107');
 const reader=$('dailyDialog'),readerHead=reader.querySelector('.dialogHead');new ResizeObserver(()=>reader.style.setProperty('--readHead107',Math.ceil(readerHead.getBoundingClientRect().height)+'px')).observe(readerHead);
 const popup=document.createElement('dialog');popup.id='quick107';popup.innerHTML='<header class="dialogHead"><h2></h2><button type="button" aria-label="关闭">×</button></header><div class="dialogBody"></div>';document.body.append(popup);popup.querySelector('button').onclick=()=>popup.close();const content=popup.querySelector('.dialogBody');
 function open(name){popup.querySelector('h2').textContent=name;content.replaceChildren();popup.showModal()}
 function choice(text,value,checked,change){const l=document.createElement('label');l.className='choice107';const c=document.createElement('input');c.type='radio';c.name='choice107';c.value=value;c.checked=checked;c.onchange=change;l.append(c,document.createTextNode(text));content.append(l)}
 $('topAuto').onclick=()=>{open('走纸');const s=A.getState(),direction=$('followDirection').value,reverse=!!window.bigPaperLayout63?.reverseHorizontal;for(const [name,value]of [['停止走纸','off'],['从上向下','vertical'],['从右向左','right'],['从左向右','left']])choice(name,value,value==='off'?$('autoScroll').value==='off':$('autoScroll').value==='on'&&(value==='vertical'?direction==='vertical':direction==='horizontal'&&(value==='right')===reverse),()=>{$('autoScroll').value=value==='off'?'off':'on';if(value!=='off'){$('followDirection').value=value==='vertical'?'vertical':'horizontal';window.bigPaperLayout63={...window.bigPaperLayout63,reverseHorizontal:value==='right'};$('followDirection').dispatchEvent(new Event('change',{bubbles:true}))}A.refresh();A.persist()})};
 $('topInk').onclick=()=>{open('墨色');for(const [name,value]of [['下一笔改色','next'],['整幅改色','all']])choice(name,value,$('recolorScope').value===value,()=>{$('recolorScope').value=value;A.persist()});const colors=document.createElement('div');colors.className='colors107';for(const [name,color]of [['玄墨','#050505'],['朱红','#c62820'],['靛蓝','#2867b1'],['明黄','#f5c400'],['绛紫','#74549c'],['雪白','#fffaf0']]){const b=document.createElement('button');b.title=name;b.setAttribute('aria-label',name);b.style.background=color;b.onclick=()=>{const control=$('freeInk');control.value=color;control.dispatchEvent(new Event('input',{bubbles:true}));control.dispatchEvent(new Event('change',{bubbles:true}))};colors.append(b)}const custom=document.createElement('input');custom.type='color';custom.value=A.getState().brush.color;custom.setAttribute('aria-label','自定义墨色');custom.oninput=()=>{$('freeInk').value=custom.value;$('freeInk').dispatchEvent(new Event('input',{bubbles:true}))};colors.append(custom);content.append(colors)};
 // Writing-scale changes are manual only; two fingers translate without zooming.
 const hint=$('writingHint100');const hintPosition=()=>{const f=A.paperFrame107();hint.style.setProperty('left',(f.x+f.w*.06)+'px','important');hint.style.setProperty('top',(f.y+f.h*.06)+'px','important')};document.addEventListener('preview-painted94',hintPosition);document.addEventListener('ink-view-changed90',hintPosition);addEventListener('resize',hintPosition);hintPosition();
 // Expanded single-character work fits proportionally into the first upper-right cell.
 const big=$('bigDialog62'),apply=[...big.querySelectorAll('button')].find(b=>b.textContent==='扩展纸张'),originalApply=apply.onclick;
 apply.onclick=async e=>{A.finish();const before=A.getState(),single=window.practiceMode53==='single'&&+before.values.rows===1&&+before.values.columns===1,preview=A.isOverview55();await originalApply.call(apply,e);gridForRatio();if(single&&before.flow.strokes.length)A.fitInkFirstCell107();if(preview&&!A.isOverview55())$('fitView').click()};
 const fields=[...big.querySelectorAll('input')].filter(e=>e.type==='range'||e.type==='number').slice(0,2),direction=big.querySelector('select');fields[0].id='bigCount107';fields[1].id='bigBands107';
 const templates=[['单格福字','vertical',1,1],['两字竖幅','vertical',2,1],['三字竖幅','vertical',3,1],['四字匾额','horizontal',4,1],['五言竖幅','vertical',5,1],['七言对联','vertical',7,2],['九字雅集','vertical',3,3],['十二字长笺','vertical',6,2],['十六字方章','vertical',4,4]];
 const common=document.createElement('div');common.className='presets107';for(const [name,dir,count,bands]of templates){const b=document.createElement('button');b.type='button';b.textContent=name;b.onclick=()=>{direction.value=dir;for(const [i,v]of [[0,count],[1,bands]]){fields[i].value=v;fields[i].dispatchEvent(new Event('input',{bubbles:true}));fields[i].dispatchEvent(new Event('change',{bubbles:true}))}};common.append(b)}big.querySelector('h2').after(common);
 const ratio=$('ratio');for(const o of [...ratio.options])if(/自定义/.test(o.textContent))o.remove();for(const o of ratio.options)if(/贴图/.test(o.textContent))o.textContent='微信贴图 · 3:4';
 function gridForRatio(){const square=Math.abs(+ratio.value-1)<.000001;$('showLines').value=square?'yes':'no';if(square)$('ruling').value='mi';A.refreshPaper();}
 ratio.addEventListener('change',gridForRatio);
 $('previewRatio79').onclick=()=>{const steps=effects.querySelector('.finalSteps54'),rail=effects.querySelector('.finalRail54');for(const b of steps.children)b.setAttribute('aria-current',String(b===$('previewRatio79')));const row=document.createElement('div');row.className='ratioRail80';for(const o of [...ratio.options].filter(o=>! /自定义/.test(o.textContent))){const b=document.createElement('button');b.textContent=o.textContent.replace(/ ·.*/,'');b.setAttribute('aria-pressed',String(o.value===ratio.value));b.onclick=()=>{const overview=A.isOverview55();ratio.value=o.value;ratio.dispatchEvent(new Event('change',{bubbles:true}));if(overview&&!A.isOverview55())$('fitView').click();for(const other of row.children)other.setAttribute('aria-pressed',String(other===b))};row.append(b)}const custom=document.createElement('button');custom.textContent='自定义比例';custom.onclick=()=>{big.showModal();common.scrollLeft=0};row.append(custom);rail.replaceChildren(row)};
 for(const b of effects.querySelectorAll('.finalSteps54 button'))if(b.textContent.trim()==='线条')b.textContent='格线';
 // Enter photo layout directly from the mode bar and keep upload as the first accent action.
 const choices=Revision62.photoPanel.querySelector('.photoChoices106'),upload=[...choices.children].find(b=>b.textContent==='添加图片');choices.prepend(upload);upload.classList.add('upload107');
 document.addEventListener('click',e=>{const b=e.target.closest('#writerModes53 button,#homeQuick47 button');if(b?.textContent.trim()!=='图文')return;e.preventDefault();e.stopImmediatePropagation();A.showWriter();if(!A.isOverview55())$('fitView').click();for(const part of ['top','config'])Revision97.setPart(part,false);Revision62.photoStep.click();requestAnimationFrame(()=>document.dispatchEvent(new Event('mode-ready109')))},true);
 const photo=$('photoModeTools'),aspect=$('photoAspect');$('board').parentElement.append(photo);photo.prepend(aspect);$('photoCropMode').textContent='调整图片';const replace=document.createElement('button');replace.type='button';replace.textContent='替换图片';replace.onclick=()=>$('photoReplace').click();photo.append(replace);
 const workspace=$('board').parentElement;let photoFrame=0;function photoLayout(){photoFrame=0;const height=photo.hidden?0:44;workspace.style.setProperty('--photo107',height+'px');A.refresh()};new MutationObserver(()=>{if(!photoFrame)photoFrame=requestAnimationFrame(photoLayout)}).observe(photo,{attributes:true,attributeFilter:['hidden']});workspace.style.setProperty('--photo107','0px');
 // Rebuild the model picker with explicit period/style filters and a tidy catalogue.
 const library=$('copyDialog').querySelector('.copyLibrary106'),filters=document.createElement('div');filters.className='copyFilters107';const era=document.createElement('select'),style=document.createElement('select');era.setAttribute('aria-label','临帖朝代');style.setAttribute('aria-label','临帖书风');filters.append(era,style);library.before(filters);
 const items=()=>[...Revision62.getPresets().map(p=>({title:p.title,era:p.era||p.dynasty||'我的作品',style:p.style||'自选书风',open:()=>CopyAlbums38.openPages55(p)})),...Timeline73.chapters.filter(c=>!c.fresh&&!c.line&&c.id!=='today').map(c=>({title:c.title,era:c.era||c.dynasty||'其他',style:c.script||c.style||'书法真迹',open:()=>Timeline73.openCopy(c)}))];
 let rows=items();for(const [select,key,name]of [[era,'era','全部朝代'],[style,'style','全部书风']]){select.append(new Option(name,''));for(const v of [...new Set(rows.map(r=>r[key]))])select.append(new Option(v,v))}
 function catalogue(){library.replaceChildren();rows=items();for(const r of rows.filter(r=>(!era.value||r.era===era.value)&&(!style.value||r.style===style.value))){const b=document.createElement('button');b.type='button';const title=document.createElement('strong'),meta=document.createElement('small');title.textContent=r.title;meta.textContent=r.era+' · '+r.style;b.append(title,meta);b.onclick=async()=>{try{await r.open();A.showWriter();$('copyDialog').close();Revision97.setPart('top',false)}catch(err){A.toast(err.message||'请上传自己的原帖')}};library.append(b)}}era.onchange=style.onchange=catalogue;$('copyDialog').addEventListener('toggle',()=>requestAnimationFrame(catalogue));catalogue();
 // Remove old mounting clauses from already-saved palette credits.
 const credit=A.getState().paletteCredit96;if(credit)A.setPaletteCredit96({...credit,idea:Revision94.designIdea104(credit.idea)});
 window.Revision107={ready:true,templates};
})();
