/* 第73版：书法历史卷、书签参照与作品预览。 */
(function init(){if(!window.AnnotationApp?.ready||!window.Timeline73||!window.Revision62?.photoPanel){setTimeout(init,60);return}
 const $=id=>document.getElementById(id),A=AnnotationApp,preview=$('previewEffects55'),rail=preview.querySelector('.finalRail54'),photo=Revision62.photoPanel,board=$('board');
 // Reset modifies settings without erasing handwriting. Return to preview after configuration resets focus.
 const actions=preview.querySelector('.previewActions56'),reset=document.createElement('button');reset.type='button';reset.id='previewReset73';reset.textContent='重置';actions.prepend(reset);const writing=$('returnWriting59'),save=$('generateArtwork59');writing.textContent='书写';save.textContent='下载';reset.onclick=async()=>{reset.disabled=true;try{window.previewComparison73=false;await A.configure47({values:{ratio:'0.75',paperPattern:'dragon',paperExtent:'fixed',zoom:'100',sceneChoice:'none',showLines:'yes'},preset:'yan',size:800,mountKey:'paris',focus:'start'});if(!A.isOverview55())$('fitView').click();A.toast('已恢复默认设置，笔迹仍可继续编辑')}finally{reset.disabled=false}};
 // Preserve the existing upper toolbar and offer a fixed, text-only writing shortcut.
 const shortcuts=document.createElement('nav');shortcuts.id='writingQuick73';shortcuts.setAttribute('aria-label','书写快捷操作');for(const [label,id] of [['预览','fitView'],['下载','export'],['清屏','clear']]){const button=document.createElement('button');button.type='button';button.textContent=label;button.onclick=()=>$(id).click();shortcuts.append(button)}document.querySelector('.topStrip').append(shortcuts);
 // Photo formats belong in the rail; crop and layout tools stay directly beneath the preview image.
 const step=Revision62.photoStep,outer=photo.querySelectorAll('.photoLayouts62')[2],inner=photo.querySelectorAll('.photoLayouts62')[1];const comparison=document.createElement('button');comparison.type='button';comparison.textContent='临帖对比';comparison.onclick=()=>{if(!A.getReference()){A.toast('请先选择并上传原帖图片，再临帖对比');return}window.previewComparison73=true;A.refresh();A.toast('原帖 20% · 临摹 80%')};outer.prepend(comparison);
 const innerToolbar=document.createElement('div');innerToolbar.id='photoInside73';innerToolbar.append(inner);board.append(innerToolbar);photo.querySelector('input[type="file"]')?.setAttribute('hidden','');photo.querySelectorAll(':scope > strong,:scope > small,:scope > select,:scope > input[type="text"],:scope > .photoLayouts62:not(:last-of-type)').forEach(e=>{if(e!==outer&&e!==inner)e.hidden=true});const photoClick=step.onclick;step.onclick=function(event){photoClick.call(this,event);rail.replaceChildren(outer);innerToolbar.hidden=false};innerToolbar.hidden=true;preview.querySelectorAll('.finalSteps54 button').forEach(b=>{if(b!==step)b.addEventListener('click',()=>{innerToolbar.hidden=true},{capture:true})});outer.querySelectorAll('button:not(:first-child)').forEach(b=>b.addEventListener('click',()=>{window.previewComparison73=false;A.refresh()},{capture:true}));document.addEventListener('pointerdown',e=>{if(!innerToolbar.hidden&&!e.target.closest('#photoInside73,#board,#previewEffects55'))innerToolbar.hidden=true},{capture:true});$('fitView').addEventListener('click',()=>{if(!A.isOverview55())innerToolbar.hidden=true});
 // Add the same six golden patterns to both writing menus; 54 already exposes them in preview.
 for(const id of ['paperPattern','quickPattern']){const select=$(id);for(const [value,title] of [['gold_fret','描金回纹'],['gold_fangsheng','方胜纹'],['gold_ice','冰裂纹'],['gold_cloud','祥云纹'],['gold_lotus','缠枝莲'],['gold_scroll','卷草纹']])if(select&&!select.querySelector('option[value="'+value+'"]'))select.add(new Option(title,value))}
 // Reading bookmark opens non-modally so it can remain visible while writing and can be dragged by its header.
 const dialog=$('dailyDialog');dialog.classList.add('quoteBookmark73');const open=()=>{if(dialog.open)return;dialog.show();dialog.style.left='max(8px, env(safe-area-inset-left))';dialog.style.top='max(64px, env(safe-area-inset-top))'};$('readQuote').onclick=open;$('quoteDetails').onclick=open;function theme(){const ink=$('headColor')?.value||'#b62118';dialog.style.setProperty('--bookmark-seal73',ink);dialog.style.setProperty('--bookmark-text73',/^#(?:[0-7][0-9a-f]{5})$/i.test(ink)?'#fff9eb':'#231c16')}document.addEventListener('quote-changed',theme);theme();const observer=new MutationObserver(()=>{if(!document.body.classList.contains('home-open')&&!dialog.open)open()});observer.observe(document.body,{attributes:true,attributeFilter:['class']});if(!document.body.classList.contains('home-open'))open();
 // Browser selection handles on long press disrupt touch writing; editable controls remain selectable.
 function writingSurface(node){return node instanceof Element&&!!node.closest('#board,#dailyBar,#writingQuick73')&&!node.closest('input,textarea,select,[contenteditable="true"]')}
 for(const type of ['selectstart','contextmenu','dragstart'])document.addEventListener(type,e=>{if(writingSurface(e.target)){e.preventDefault()}},{capture:true});
})();
