(async function init(){if(!window.Revision46?.ready||!window.AnnotationHome){setTimeout(init,30);return}const $=id=>document.getElementById(id),app=AnnotationApp;
const create=(tag,attrs={},value)=>{const e=document.createElement(tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(value!==undefined)e.textContent=value;return e};
function dialog(id,title){document.getElementById(id)?.remove();const d=create('dialog',{id}),h=create('div',{class:'dialogHead'}),b=create('div',{class:'dialogBody'}),close=create('button',{},'完成 ×');h.append(create('h2',{},title),close);d.append(h,b);document.body.append(d);close.onclick=()=>d.close();return {d,b}}
const nav=$('annotationCategories');document.querySelector('.annotationGallery').after(nav);const quick=create('nav',{id:'homeQuick47','aria-label':'常用书写入口'});document.querySelector('.annotationGallery').before(quick);
async function preset(name){document.dispatchEvent(new Event('writing-scenario47'));const values={ratio:'0.75',showLines:'yes',inkMode:'assist',paperPattern:'dragon',followDirection:'vertical',sceneChoice:'none',paperExtent:'fixed',photoMode:'hero2',ruling:'vertical',letterLayout:'custom',zoom:'400',columns:'6',rows:'8'};let config={values,preset:'zhang',size:18,inkOpacity:1,focus:'start'};if(name==='single'){Object.assign(values,{ratio:'1',rows:'1',columns:'1',letterLayout:'1,1,vertical',zoom:'100',ruling:'mi',showLines:'yes'});config.preset='ouyang';config.size=400}if(name==='letter'){Object.assign(values,{stationery:'letter',zoom:'300',columns:'6'})}if(name==='copy'){Object.assign(values,{zoom:'300',ruling:'hui',paperExtent:'fixed',ratio:'0.75',stationery:'vermillion'});config.inkOpacity=.5}await app.configure47(config);app.showWriter()}
for(const [key,name] of [['single','单字'],['letter','写信'],['copy','临帖']]){const b=create('button',{type:'button','data-preset':key,'aria-label':name});b.append(create('strong',{},name));b.onclick=()=>preset(key);quick.append(b)}
$('continueWriting').onclick=async()=>{if(!app.hasInk())await app.configure47({values:{ratio:'0.75',ruling:'vertical',showLines:'yes',zoom:'400',inkMode:'assist',paperPattern:'dragon'},size:18,inkOpacity:1,focus:'start'});app.showWriter()};
$('appLogo').style.cursor='pointer';$('appLogo').setAttribute('role','button');$('appLogo').setAttribute('aria-label','回到首页');$('appLogo').tabIndex=0;$('appLogo').onclick=()=>AnnotationHome.show();$('appLogo').onkeydown=e=>{if(e.key==='Enter')AnnotationHome.show()};
const first=await DraftStore.get('ui47.defaults').catch(()=>false);if(!first){$('quotesVisibility').value='shown';$('quotesVisibility').dispatchEvent(new Event('change'));document.body.classList.remove('quotes-hidden');if(!app.hasInk())await app.configure47({values:{ratio:'0.75',ruling:'vertical',showLines:'yes',zoom:'400',inkMode:'assist',paperPattern:'dragon'},size:18,inkOpacity:1,focus:'start'});await DraftStore.set('ui47.defaults',true)}
// Keep serialized legacy carrier controls, but remove their duplicated UI from settings.
$('stationery').closest('label')?.setAttribute('hidden','');$('stationeryChoices')?.setAttribute('hidden','');

const sizeDialog=dialog('sizeModes47','笔径与书写位置');const n=create('input',{type:'number',min:'1',max:'1000','aria-label':'笔径'});sizeDialog.b.append(n);const modes=create('div',{class:'actions47'});for(const[label,size,focus]of [['正文 · 18',18,'start'],['落款 · 12',12,'signature']]){const b=create('button',{},label);b.onclick=async()=>{await app.configure47({values:{zoom:'400',inkMode:'assist'},size,focus});sizeDialog.d.close();app.showWriter()};modes.append(b)}sizeDialog.b.append(modes);n.onchange=()=>{const v=Math.max(1,Math.min(1000,+n.value||18));$('sizeNumber').value=v;$('sizeNumber').dispatchEvent(new Event('change'));app.updatePosition()};$('topSize').onclick=()=>{n.value=app.getState().brush.size;app.openDialog('sizeModes47')};
const opacityLabel=create('label',{},'墨迹不透明度');const op=create('input',{type:'range',min:'1',max:'100',value:String(Math.round((window.annotationInkOpacity??1)*100))});const out=create('output',{},op.value+'%');opacityLabel.append(op,out);sizeDialog.b.append(opacityLabel);op.oninput=()=>{window.annotationInkOpacity=+op.value/100;out.textContent=op.value+'%';app.refresh();app.persist()};
const settings=dialog('toolSettings47','快捷按钮'),table=create('div',{id:'toolsTable47'});settings.b.append(table);let settingsParent='paperDialog';function openTools53(parent){settingsParent=parent||[...document.querySelectorAll('dialog[open]')].find(d=>d!==settings.d)?.id||'paperDialog';renderTable();app.openDialog('toolSettings47')}settings.d.querySelector('.dialogHead button').onclick=()=>{settings.d.close();app.openDialog(settingsParent)};
const parking=create('div',{id:'toolParking47'});document.body.append(parking);const registry=new Map();const topDefaults=['annotationHomeButton','myWorks','selectInk','undo','redo','clear','fitView','topQuotes','recordProcess'];const bottomDefaults=['menuToggle','topSize','lockWriting39','export','topOptimize','copyPagesQuick39','photoSettingsQuick42','topLines','topInk','inkScope39','calendarMoments','topReset','styleCycle39','topDirection','topAuto','topMusic','topStart'];
for(const id of [...topDefaults,...bottomDefaults,'topRemove','topUpload','topPattern','topRatio','topMount','topParticle','topGuide']){const e=$(id);if(e){registry.set(id,{id,button:e,title:e.getAttribute('aria-label')||e.title||id});e.removeAttribute('aria-hidden')}}
const other=create('button',{id:'toolSettingsQuick47',title:'配置快捷按钮','aria-label':'配置快捷按钮'});other.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M3 6h18M3 12h18M3 18h18"/><circle cx="8" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="10" cy="18" r="2"/></svg>';other.onclick=()=>openTools53();registry.set(other.id,{id:other.id,button:other,title:'配置快捷按钮'});bottomDefaults.push(other.id);
// Every value-setting control gets an optional targeted shortcut as well.
for(const e of document.querySelectorAll('dialog input[id],dialog select[id],dialog textarea[id]')){if(e.type==='hidden'||e.closest('#toolSettings47')||e.closest('[hidden]'))continue;const label=e.closest('label');if(!label)continue;const id='setting47-'+e.id,title=(label.childNodes[0]?.textContent||e.id).trim().slice(0,30);const b=create('button',{id,title,'aria-label':title});b.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/></svg>';b.onclick=()=>{app.openDialog(e.closest('dialog').id);requestAnimationFrame(()=>{e.scrollIntoView({block:'center'});e.focus({preventScroll:true})})};registry.set(id,{id,button:b,title})}
let config;try{config=JSON.parse(localStorage.getItem('iinnkk.toolbar53')||'null')}catch{}config||=await DraftStore.get('toolbar47').catch(()=>null);if(!config){const old=window.toolbarOrder?.();config={version:47,order:[...new Set([...(old?.top||topDefaults),...(old?.bottom||bottomDefaults),...registry.keys()])],top:old?.top||topDefaults,bottom:[...new Set([...(old?.bottom||bottomDefaults),'toolSettingsQuick47'])]}}
function normalize(c){const ids=[...registry.keys()];return {version:47,order:[...new Set([...(c?.order||[]).filter(x=>registry.has(x)),...ids])],top:(c?.top||[]).filter(x=>registry.has(x)),bottom:(c?.bottom||[]).filter(x=>registry.has(x))}}
function apply(c){config=normalize(c);for(const {button}of registry.values()){button.hidden=false;parking.append(button)}document.querySelectorAll('[data-mirror47]').forEach(e=>e.remove());for(const side of ['top','bottom'])for(const id of config[side]){const b=registry.get(id).button;if(side==='bottom'&&config.top.includes(id)){const copy=b.cloneNode(true);copy.removeAttribute('id');copy.dataset.mirror47=id;copy.onclick=()=>b.click();$('bottomIcons39').append(copy)}else $(side==='top'?'topActions':'bottomIcons39').append(b)}}
async function save(){try{localStorage.setItem('iinnkk.toolbar53',JSON.stringify(config));await (localStorage.setItem('iinnkk.toolbar53',JSON.stringify(config)),DraftStore.set('toolbar47',config));await app.saveCurrentSettings();document.dispatchEvent(new Event('settings-changed47'))}catch{app.toast('按钮设置未保存，请重试')}}
window.toolbarOrder=()=>({...config,top:[...$('topActions').children].map(e=>e.id).filter(x=>registry.has(x)),bottom:[...$('bottomIcons39').children].map(e=>e.dataset.mirror47||e.id).filter(x=>registry.has(x)),order:[...new Set([...$('topActions').children,...$('bottomIcons39').children].map(e=>e.dataset.mirror47||e.id).filter(x=>registry.has(x)).concat(config.order))]});
window.restoreToolbarOrder=c=>{if(c?.version===47){apply(c);(localStorage.setItem('iinnkk.toolbar53',JSON.stringify(config)),DraftStore.set('toolbar47',config))}else apply(config)};
function renderTable(){table.replaceChildren();for(const [side,title]of [['top','顶部图标'],['bottom','底部图标']]){const section=create('section',{class:'toolGroup53'});section.append(create('h3',{},title));for(const id of config[side]){const item=registry.get(id),row=create('div',{class:'toolRow53','data-side':side,'data-id':id}),label=create('span',{},item.title),handle=create('button',{'aria-label':'拖动排序 '+item.title,class:'dragHandle53'},'☰'),remove=create('button',{'aria-label':'移除 '+item.title},'×');remove.onclick=()=>{config[side]=config[side].filter(x=>x!==id);apply(config);renderTable();save()};handle.draggable=true;handle.ondragstart=e=>e.dataTransfer.setData('text/plain',id);row.ondragover=e=>e.preventDefault();const move=source=>{if(!config[side].includes(source)||source===id)return;config[side]=config[side].filter(x=>x!==source);config[side].splice(config[side].indexOf(id),0,source);apply(config);renderTable();save()};row.ondrop=e=>{e.preventDefault();move(e.dataTransfer.getData('text/plain'))};handle.onpointerdown=e=>{handle.setPointerCapture(e.pointerId);e.stopPropagation()};handle.onpointerup=e=>{const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.toolRow53');if(target?.dataset.side===side){const dest=target.dataset.id;if(dest!==id){config[side]=config[side].filter(x=>x!==id);config[side].splice(config[side].indexOf(dest),0,id);apply(config);renderTable();save()}}};row.append(handle,label,remove);section.append(row)}const select=create('select',{'aria-label':'添加到'+title});select.append(create('option',{value:''},'添加图标…'));for(const[id,item]of registry)if(!config[side].includes(id))select.append(create('option',{value:id},item.title));select.onchange=()=>{if(!select.value)return;config[side].push(select.value);apply(config);renderTable();save()};section.append(select);table.append(section)}}
if(!localStorage.getItem('iinnkk.lockAdjacent53')){config.bottom=config.bottom.filter(x=>x!=='lockWriting39');config.bottom.splice(Math.max(0,config.bottom.indexOf('topSize')+1),0,'lockWriting39');localStorage.setItem('iinnkk.lockAdjacent53','1');localStorage.setItem('iinnkk.toolbar53',JSON.stringify(config))}apply(config);for(const row of [$('topActions'),$('bottomIcons39')])row.addEventListener('pointerup',()=>{setTimeout(()=>{config=normalize(window.toolbarOrder());(localStorage.setItem('iinnkk.toolbar53',JSON.stringify(config)),DraftStore.set('toolbar47',config))},0)});
for(const d of document.querySelectorAll('dialog .settingsTabs')){const b=create('button',{},'快捷按钮');b.onclick=()=>openTools53(d.closest('dialog').id);d.append(b)}
// Existing settings and icons are now ready in their final persisted positions.
window.Revision47={ready:true,preset,create,dialog,registerTool:(id,title,path,fn)=>{const b=create('button',{id,title,'aria-label':title});b.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6">'+path+'</svg>';b.onclick=fn;registry.set(id,{id,title,button:b});config.order.push(id);apply(config);return b},toolbar:()=>config,openTools:openTools53};
document.documentElement.classList.add('ui-ready');app.updatePosition();window.dispatchEvent(new Event('resize'));
})();


