(function init(){
 if(!window.UserExcerpts112?.ready){setTimeout(init,40);return}
 const A=AnnotationApp,$=id=>document.getElementById(id),ratio=$('ratio'),effects=$('previewEffects55'),rail=effects.querySelector('.finalRail54');
 // Square cover asset, with image and lettering in the central safe band.
 if(![...ratio.options].some(o=>o.value==='1.000000'))ratio.prepend(new Option('朋友圈封面 · 1:1','1.000000'));
 for(const id of ['photoMode','quickPhotoMode'])if(![...$(id).options].some(o=>o.value==='moments114'))$(id).add(new Option('朋友圈封面 · 个性手书','moments114'));
 const upload=document.createElement('input');upload.type='file';upload.accept='image/*';upload.hidden=true;upload.id='coverUpload114';document.body.append(upload);
 upload.onchange=async()=>{try{await A.replaceCoverPhoto114([...upload.files]);}catch(e){A.toast('照片未能读取，请重试')}finally{upload.value=''}};
 function button(label,action){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=action;return b}
 async function apply(){await A.configure47({photoLayout114:true,values:{ratio:'1.000000',stationery:'plain',sceneChoice:'none',paperExtent:'fixed',photoMode:'moments114',paperPattern:'none',paperPreset111:'plain',showLines:'no',guideMode:'off',papercolor:'#f3efe5',rows:'2',columns:'4',followDirection:'horizontal',zoom:'200',headMode:'none',sealMode:'none'},brushPatch:{color:'#24483f'},mountKey:'bare',size:25,focus:'start'});A.setPaletteCredit96(null);A.showWriter();if(!A.isOverview55())$('fitView').click();A.persist();}
 function write(){if(A.isOverview55())$('fitView').click();const a=A.writingGrid67().area;A.focusPoint({x:a.x+a.w*.12,y:a.y+a.h*.24});A.toast('在留白处亲写金句；双指移动纸面，预览查看封面')}
 function panel(){if($('coverPanel114'))return;const section=document.createElement('section');section.id='coverPanel114';const sample=document.createElement('canvas');sample.width=sample.height=360;sample.setAttribute('aria-label','朋友圈封面示意：左侧图片，右侧手写金句，右下头像留白');const t=sample.getContext('2d');t.scale(360,360);draw(t,{w:1,h:1},{photo:false,guides:true});const note=document.createElement('p');note.textContent='方图封面，图文置于中央，右下为头像留白；微信中可调整裁切。示意字不导出，亲写自己的座右铭。';section.append(sample,note,button('替换图片',()=>upload.click()),button('手写金句',write));rail.append(section)}
 const old=$('previewRatio79').onclick;$('previewRatio79').onclick=async e=>{await old.call($('previewRatio79'),e);if($('photoMode').value==='moments114')panel()};
 ratio.addEventListener('change',()=>{if($('photoMode').value==='moments114'&&ratio.value!=='1.000000')$('coverPanel114')?.remove()});
 function draw(t,b,{photo,guides}){t.save();t.fillStyle='#f3efe5';t.fillRect(0,0,b.w,b.h);if(!photo){const x=.06*b.w,y=.18*b.h,w=.36*b.w,h=.58*b.h;t.save();t.beginPath();t.rect(x,y,w,h);t.clip();const g=t.createLinearGradient(0,y,0,y+h);g.addColorStop(0,'#d6e1d9');g.addColorStop(1,'#7d9f8b');t.fillStyle=g;t.fillRect(x,y,w,h);t.fillStyle='#eee5c8';t.beginPath();t.arc(x+w*.72,y+h*.22,w*.12,0,7);t.fill();for(let i=0;i<3;i++){t.fillStyle=['#93b1a2','#658b7c','#355f53'][i];t.beginPath();t.moveTo(x-w*.2,y+h);t.lineTo(x+w*.3,y+h*(.38+i*.17));t.lineTo(x+w*.7,y+h*(.66+i*.07));t.lineTo(x+w*1.2,y+h*(.43+i*.14));t.lineTo(x+w*1.2,y+h);t.fill()}t.restore()}
 if(guides){t.fillStyle='#315649';t.font=b.w*.056+'px serif';t.textAlign='left';t.fillText('心有山海',b.w*.49,b.h*.39);t.fillText('步履不停',b.w*.49,b.h*.49);t.fillStyle='#7c8d81';t.font=b.w*.024+'px sans-serif';t.fillText('此处亲写你的金句',b.w*.49,b.h*.59);t.fillText('点击替换图片',b.w*.095,b.h*.80);t.strokeStyle='#aaa99b';t.lineWidth=b.w*.002;t.setLineDash([b.w*.01,b.w*.01]);t.strokeRect(b.w*.79,b.h*.79,b.w*.15,b.h*.15);t.font=b.w*.022+'px sans-serif';t.fillText('头像留白',b.w*.80,b.h*.88)}t.restore()}
 window.MomentsCover114={ready:true,apply,write,draw};A.refresh();
})();
