/* Writing record: count completed strokes and elapsed writing time from first ink.
   Characters are explicitly estimated; old works have no measured duration. */
(function init117(){
 if(!window.AnnotationApp?.ready||!window.InkCloud75||!window.WritingMusic){setTimeout(init117,60);return}
 const cloud=InkCloud75,db=cloud.client,$=id=>document.getElementById(id);
 const element=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e};
 const action=(parent,text,fn,label)=>{const b=element('button',text);b.type='button';b.setAttribute('aria-label',label||text);b.onclick=async e=>{e.stopPropagation();b.disabled=true;try{await fn(b)}catch(error){AnnotationApp.toast(error.message||String(error))}finally{b.disabled=false}};parent.append(b);return b};
 const localKey='ink.writing116',read=()=>{try{return JSON.parse(localStorage.getItem(localKey))||{strokes:0,seconds:0}}catch{return{strokes:0,seconds:0}}};
 let record=read(),lastStroke=0,uploadTimer=0,remoteOwner=null,remoteBase={strokes:0,seconds:0},syncing=false;
 function saveLocal(){try{localStorage.setItem(localKey,JSON.stringify(record))}catch{}clearTimeout(uploadTimer);uploadTimer=setTimeout(sync,1400)}
 async function sync(){if(syncing||!cloud.user||!navigator.onLine)return;syncing=true;try{const owner=cloud.user.id;if(remoteOwner!==owner){const r=await db.from('ink_writing116').select('strokes,seconds').eq('owner',owner).maybeSingle();if(r.error)throw r.error;remoteBase=r.data||{strokes:0,seconds:0};remoteOwner=owner}const pending={...record},next={owner,strokes:remoteBase.strokes+pending.strokes,seconds:remoteBase.seconds+pending.seconds,updated_at:new Date().toISOString()};const r=await db.from('ink_writing116').upsert(next,{onConflict:'owner'});if(r.error)throw r.error;remoteBase={strokes:next.strokes,seconds:next.seconds};record={strokes:Math.max(0,record.strokes-pending.strokes),seconds:Math.max(0,record.seconds-pending.seconds)};try{localStorage.setItem(localKey,JSON.stringify(record))}catch{}if(record.strokes)saveLocal()}catch(e){console.warn('写字记录稍后同步：',e.message)}finally{syncing=false}}
 document.addEventListener('ink-stroke',e=>{const now=Date.now(),points=e.detail?.points||[],duration=points.length>1?Math.max(1,Math.min(30,(points.at(-1).t-points[0].t)/1000)):1;record.strokes++;record.seconds+=lastStroke&&now-lastStroke<120000?Math.max(1,Math.round((now-lastStroke)/1000)):Math.round(duration);lastStroke=now;saveLocal()});
 document.addEventListener('cloud-user84',()=>{remoteOwner=null;if(cloud.user)sync()});
 const chars=s=>Math.round((s||0)/7),time=s=>{const m=Math.floor((s||0)/60);return Math.floor(m/60)+'小时'+(m%60)+'分'};
 let ranks=[],profiles=new Map(),likes=[],follows=[];
 async function load(){const [totals,people,heart,follow]=await Promise.all([db.from('ink_writing116').select('owner,strokes,seconds').order('seconds',{ascending:false}).limit(100),db.from('ink_profiles83').select('owner,display_name').limit(200),db.from('ink_writing_likes116').select('owner,admirer').limit(500),db.from('ink_follows116').select('followed,follower').limit(500)]);for(const r of [totals,people,heart,follow])if(r.error)throw r.error;ranks=totals.data||[];profiles=new Map((people.data||[]).map(x=>[x.owner,x.display_name]));likes=heart.data||[];follows=follow.data||[];return ranks}
 function name(owner){return profiles.get(owner)||(owner===cloud.user?.id?cloud.user.user_metadata?.full_name:null)||'亲笔书家'}
 function avatar(owner){return element('span',Array.from(name(owner))[0]||'亲','rankAvatar117')}
 async function toggle(table,person,column,rows){if(!cloud.user){$('account47').click();return false}if(person===cloud.user.id)return false;const owner=cloud.user.id,existing=rows.some(x=>x[column]===person&&(x.admirer||x.follower)===owner),r=existing?await db.from(table).delete().eq(column,person).eq(table==='ink_follows116'?'follower':'admirer',owner):await db.from(table).insert({[column]:person,[table==='ink_follows116'?'follower':'admirer']:owner});if(r.error)throw r.error;await load();return !existing}
 async function render(host){const section=element('section',null,'writingRank117'),head=element('header',null,'rankHead117');head.append(element('h2','写字排行榜'));const mine=action(head,'我的写字统计',()=>{if(!cloud.user){$('account47').click();return}return show(cloud.user.id)},'打开我的写字统计');mine.className='rankMine117';section.append(head);host.append(section);const pending=element('p','正在整理写字记录…');section.append(pending);
  try{await load();pending.remove();if(!ranks.length){section.append(element('p','还没有写字记录。完成一笔后开始累计；旧作品的时长无法补算。'));return}ranks.forEach((item,index)=>{const row=element('div',null,'rankRow117');const identity=action(row,'',()=>show(item.owner),name(item.owner)+'的写字记录');identity.className='rankIdentity117';identity.append(avatar(item.owner),element('span',(index+1)+' · '+name(item.owner)));const values=element('span',null,'rankValues117');values.append(element('strong','约'+chars(item.strokes)+'字'),element('small',time(item.seconds)));row.append(values);const heart=action(row,likes.some(x=>x.owner===item.owner&&x.admirer===cloud.user?.id)?'♥':'♡',async b=>{const liked=await toggle('ink_writing_likes116',item.owner,'owner',likes);b.textContent=liked?'♥':'♡';b.setAttribute('aria-pressed',String(liked))},'赞 '+name(item.owner));heart.className='rankHeart117';heart.setAttribute('aria-pressed',String(likes.some(x=>x.owner===item.owner&&x.admirer===cloud.user?.id)));const following=()=>follows.some(x=>x.followed===item.owner&&x.follower===cloud.user?.id),follow=action(row,'',async b=>{if(!cloud.user){$('account47').click();return}b.disabled=true;try{const on=await toggle('ink_follows116',item.owner,'followed',follows);b.setAttribute('aria-pressed',String(on));b.title=on?'取消关注':'关注'}finally{b.disabled=false}},'关注 '+name(item.owner));follow.className='rankFollow131';follow.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><circle cx="9" cy="7" r="3"/><path d="M3 20v-3a6 6 0 0112 0v3M19 8v8M15 12h8"/></svg>';follow.setAttribute('aria-pressed',String(following()));follow.hidden=item.owner===cloud.user?.id;section.append(row)});section.append(element('small','字数按七笔一字估算；时长从本版实际落笔起累计，暂停超过两分钟的间隔不计入。','rankFoot117'))}catch(e){pending.textContent='写字记录暂未读取：'+e.message}}
 const medals=[['初试笔锋',1],['百字相伴',100],['千字成篇',1000],['一小时静心',0,3600],['十小时持恒',0,36000]];
 async function show(owner){const panel=element('dialog',null,'rankDialog117'),head=element('header',null,'rankDetailHead117'),nameNode=element('strong','写字记录');head.append(nameNode);action(head,'×',()=>panel.close(),'关闭写字记录');panel.append(head,element('p','正在读取统计…'));document.body.append(panel);panel.addEventListener('close',()=>panel.remove(),{once:true});panel.showModal();try{await load();const item=ranks.find(x=>x.owner===owner)||{owner,strokes:0,seconds:0},position=ranks.findIndex(x=>x.owner===owner)+1;nameNode.textContent=name(owner)+'的写字记录';const summary=element('section',null,'rankSummary117');summary.append(avatar(owner),element('h2',name(owner)),element('p','约 '+chars(item.strokes)+' 字 · '+time(item.seconds)+' · '+(position?'第 '+position+' 名':'尚未上榜')));panel.replaceChildren(head,summary);
  const awards=element('div',null,'rankMedals117');awards.append(element('h3','写字勋章'));for(const [label,words,seconds=0]of medals){const earned=words?chars(item.strokes)>=words:item.seconds>=seconds,medal=element('span',(earned?'✦ ':'◇ ')+label);medal.className=earned?'earned117':'locked117';awards.append(medal)}panel.append(awards);
  const tools=element('div',null,'rankDetailActions117');if(owner!==cloud.user?.id){const following=follows.some(x=>x.followed===owner&&x.follower===cloud.user?.id);action(tools,following?'已关注':'关注',async b=>{const yes=await toggle('ink_follows116',owner,'followed',follows);b.textContent=yes?'已关注':'关注'});action(tools,likes.some(x=>x.owner===owner&&x.admirer===cloud.user?.id)?'♥ 已赞':'♡ 点赞',async b=>{const yes=await toggle('ink_writing_likes116',owner,'owner',likes);b.textContent=yes?'♥ 已赞':'♡ 点赞'})}action(tools,'↗ 分享写字记录',async()=>{const text=name(owner)+'写字约'+chars(item.strokes)+'字，累计'+time(item.seconds)+'。今日亲笔';if(navigator.share)await navigator.share({title:'写字记录',text,url:location.origin+location.pathname});else if(navigator.clipboard){await navigator.clipboard.writeText(text+' '+location.href);AnnotationApp.toast('写字记录已复制')}});panel.append(tools);
  panel.append(element('h3','公开作品'));const works=element('div',null,'rankWorks117');panel.append(works);const r=await db.from('ink_works').select('id,title,owner,image_path,published').eq('owner',owner).eq('published',true).order('updated_at',{ascending:false}).limit(18);if(r.error)throw r.error;if(!r.data?.length)works.append(element('p','尚未发布作品。'));for(const work of r.data||[]){const tile=action(works,work.title,()=>{panel.close();return cloud.openWork(work)});tile.title=work.title;db.storage.from('ink-works').createSignedUrl(work.image_path,1800).then(({data})=>{if(data?.signedUrl){const im=element('img');im.src=data.signedUrl;im.alt=work.title;im.loading='lazy';tile.prepend(im)}})}}catch(e){panel.append(element('p','记录读取失败：'+e.message))}}
 // Preview reference frame: the crop controls feed the same compositor used for exports.
 const frame=element('div',null,'copyFrame117');frame.setAttribute('aria-label','拖动原帖看局部，双指缩放');frame.hidden=true;$('board').append(frame);const tips=element('span','拖动看局部 · 双指缩放');frame.append(tips);const points=new Map();let previous=null;
 function framePosition(){const on=AnnotationApp.isOverview55()&&!!AnnotationApp.getReference()&&!document.body.classList.contains('home-open'),layout=$('copyLayout111').value;if(!on||!['left','top'].includes(layout)){frame.hidden=true;return}const canvas=$('paper'),rect=canvas.getBoundingClientRect();const paper=AnnotationApp.paperFrame107?.();if(!paper){frame.hidden=true;return}const clip=layout==='left'?{x:paper.x,y:paper.y,w:paper.w*.2,h:paper.h}:{x:paper.x,y:paper.y,w:paper.w,h:paper.h*.25};Object.assign(frame.style,{left:clip.x+'px',top:clip.y+'px',width:clip.w+'px',height:clip.h+'px'});frame.hidden=false}
 const syncCrop=()=>{for(const [id,label,format] of [['copyZoom115','原帖放大',v=>Number(v).toFixed(1)+'倍'],['copyPan115','局部位置',v=>Math.round(v)+'%']]){const range=document.querySelector('#previewEffects55 input[aria-label=\"'+label+'\"]');if(range){range.value=$(id).value;const output=range.parentElement?.querySelector('output');if(output)output.textContent=format(+range.value)}}};
 const center=()=>{const p=[...points.values()];return{x:p.reduce((n,v)=>n+v.x,0)/p.length,y:p.reduce((n,v)=>n+v.y,0)/p.length,d:p.length>1?Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y):0}};
 frame.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();frame.setPointerCapture(e.pointerId);points.set(e.pointerId,{x:e.clientX,y:e.clientY});previous=center()});frame.addEventListener('pointermove',e=>{if(!points.has(e.pointerId))return;e.preventDefault();e.stopPropagation();points.set(e.pointerId,{x:e.clientX,y:e.clientY});const next=center(),layout=$('copyLayout111').value;if(previous){if(next.d&&previous.d){$('copyZoom115').value=String(Math.max(1,Math.min(12,+$('copyZoom115').value*next.d/previous.d)))}else{const span=layout==='top'?frame.clientWidth:frame.clientHeight,delta=layout==='top'?next.x-previous.x:next.y-previous.y;$('copyPan115').value=String(Math.max(0,Math.min(100,+$('copyPan115').value-delta/Math.max(1,span)*100/Math.max(1,+$('copyZoom115').value))))}syncCrop();AnnotationApp.refresh();AnnotationApp.persist()}previous=next});for(const event of ['pointerup','pointercancel','lostpointercapture'])frame.addEventListener(event,e=>{points.delete(e.pointerId);previous=points.size?center():null});frame.addEventListener('wheel',e=>{e.preventDefault();$('copyZoom115').value=String(Math.max(1,Math.min(12,+$('copyZoom115').value*(e.deltaY<0?1.12:.89))));syncCrop();AnnotationApp.refresh();AnnotationApp.persist()},{passive:false});for(const event of ['preview-painted94','reference-set111','reference-layout111','ink-view-changed90'])document.addEventListener(event,framePosition);new MutationObserver(framePosition).observe(document.body,{attributes:true,attributeFilter:['class']});
 // Keep playback controls in the music dialog while retaining file/link import below.
 const picker=$('musicPicker65'),music=WritingMusic,select=$('writingTrack');if(picker){const header=picker.querySelector('header'),oldOpen=$('topMusic').onclick,cover=element('div',null,'musicHero117'),disc=element('div','♫','musicDisc117'),title=element('strong'),artist=element('small'),transport=element('div',null,'musicTransport117');cover.append(disc,title,artist);header.after(cover,transport);const options=[...select.options].filter(o=>o.value!=='custom'&&o.value!=='remote');const syncPanel=()=>{title.textContent=select.selectedOptions[0]?.textContent||'伴写音乐';artist.textContent=music.tracks.find(t=>t.key===select.value)?.artist||'今日亲笔 · 聆听';transport.querySelector('[data-play]')?.replaceChildren(document.createTextNode(music.audio.paused?'▶':'Ⅱ'));transport.querySelector('[data-order]')?.replaceChildren(document.createTextNode(music.getOrder()==='random'?'⤨':'☷'));for(const b of picker.querySelectorAll('[data-music]'))b.classList.toggle('active',b.dataset.music===select.value)};const step=delta=>{const i=options.findIndex(o=>o.value===select.value);music.choose(options[(i+delta+options.length)%options.length].value);syncPanel()};action(transport,'Ⅰ◀',()=>step(-1),'上一曲');const play=action(transport,'▶',()=>{music.audio.paused?music.play():music.pause();syncPanel()},'播放或暂停');play.dataset.play='';const order=action(transport,'☷',()=>{music.setOrder(music.getOrder()==='random'?'sequence':'random');syncPanel()},'顺序或随机播放');order.dataset.order='';action(transport,'▶Ⅰ',()=>step(1),'下一曲');picker.querySelector('.musicChoices65')?.addEventListener('click',()=>setTimeout(syncPanel,0));$('topMusic').onclick=()=>{oldOpen?.();syncPanel()};music.audio.addEventListener('play',syncPanel);music.audio.addEventListener('pause',syncPanel);select.addEventListener('change',syncPanel)}
 window.WritingRank117={render,show,load,toggleFollow133:owner=>toggle('ink_follows116',owner,'followed',follows),isFollowing133:owner=>follows.some(x=>x.followed===owner&&x.follower===cloud.user?.id),open:()=>{const d=element('dialog',null,'rankDialog117 rankList118'),h=element('header',null,'rankDetailHead117');h.append(element('strong','写字排行榜'));action(h,'×',()=>d.close(),'关闭排行榜');d.append(h);document.body.append(d);d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();render(d);return d},get record(){return record},framePosition};
 framePosition();
})();
