/* Version 81: compact controls, albums, original works and public gallery. */
(function init(){if(!window.AnnotationApp?.ready||!window.CopyAlbums38||!window.Timeline73||!window.DailyQuotes38){setTimeout(init,90);return}
 const $=id=>document.getElementById(id),app=AnnotationApp;
 function message(e){app.toast(e?.message||String(e))}
 function download(blob,name){const link=document.createElement('a'),url=URL.createObjectURL(blob);link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
 async function picture(source){const img=new Image(),url=typeof source==='string'?source:URL.createObjectURL(source);try{img.src=url;await img.decode();return img}finally{if(typeof source!=='string')setTimeout(()=>URL.revokeObjectURL(url),60000)}}
 async function roll(album,original=false){if(!album?.pages?.length)throw Error('这组原帖没有图片');if(!original)await CopyAlbums38.saveCurrent();const pictures=[];for(const page of album.pages){let source=page.image;if(!original){const id=page.workIds?.at(-1),saved=id&&await DraftStore.get(id);if(!saved?.blob)continue;source=saved.blob}pictures.push(await picture(source))}if(!pictures.length)throw Error('先逐页点“保存本页”，再拼合长卷');const width=1200,gap=24,heights=pictures.map(im=>Math.round(im.naturalHeight*width/im.naturalWidth)),height=heights.reduce((a,b)=>a+b,0)+gap*(heights.length-1);if(height>30000||width*height>65e6)throw Error('长卷过长，请分组下载');const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');ctx.fillStyle='#f5f0e5';ctx.fillRect(0,0,width,height);let top=0;pictures.forEach((im,i)=>{ctx.drawImage(im,0,top,width,heights[i]);top+=heights[i]+gap});const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));if(!blob)throw Error('长卷生成失败');download(blob,album.title+(original?'·真迹':'·临帖')+'长卷.jpg');app.toast('已拼合 '+pictures.length+' 页')}
 const viewer=$('copyAlbumViewer38');if(viewer){const actions=viewer.querySelector('.musicActions'),one=document.createElement('button'),all=document.createElement('button');one.textContent='下载本页';all.textContent='拼合长卷';actions.append(one,all);const current=()=>CopyAlbums38.viewed;one.onclick=async()=>{try{const album=current();if(!album)throw Error('请先保存临帖本页');if(viewer.dataset.original81){const i=Number(($('albumPage38').textContent.match(/^\d+/)||[])[0])-1;const src=album.pages[i]?.image;if(src instanceof Blob)download(src,album.title+'·原帖第'+(i+1)+'页.jpg');else if(src)window.open(src,'_blank','noopener');return}const i=Number(($('albumPage38').textContent.match(/^\d+/)||[])[0])-1,id=album.pages[i]?.workIds?.at(-1),saved=id&&await DraftStore.get(id);if(!saved?.blob)throw Error('请先保存本页');download(saved.blob,album.title+'·第'+(i+1)+'页.png')}catch(e){message(e)}};all.onclick=()=>{const album=current();roll(album,!!viewer.dataset.original81).catch(message)};viewer.addEventListener('close',()=>{delete viewer.dataset.original81;$('albumEdit38').disabled=false});viewer.querySelector('#albumImage38').style.touchAction='pinch-zoom'}
 const float=$('copyNav80');if(float){const stitch=document.createElement('button');stitch.type='button';stitch.textContent='卷';stitch.title='拼合临帖长卷';stitch.setAttribute('aria-label','拼合所有已保存的临帖页');float.append(stitch);stitch.onclick=()=>roll(CopyAlbums38.active).catch(message)}
 const quick=[...document.querySelectorAll('#writingQuick73 button')].find(x=>x.textContent==='预览');function syncPreview(){if(quick)quick.textContent=app.isOverview55()?'书写':'预览'}$('fitView')?.addEventListener('click',()=>setTimeout(syncPreview,50));new MutationObserver(syncPreview).observe(document.body,{attributes:true,attributeFilter:['class']});syncPreview();
 const bookmark=$('dailyDialog'),head=bookmark?.querySelector('.dialogHead');if(head){const edit=document.createElement('button');edit.type='button';edit.className='bookmarkEdit81';edit.textContent='编辑';edit.onclick=()=>{try{window.Revision62?.openQuoteEditor();bookmark.close()}catch(e){message(e)}};head.append(edit);const sync=()=>edit.hidden=!window.InkStudio50?.isAdmin;document.addEventListener('admin-unlocked53',sync);sync()}
 if(bookmark&&head){const tools=document.createElement('div');tools.className='bookmarkNav81';tools.innerHTML='<button type="button" aria-label="上一条">‹</button><button type="button" aria-label="顺序或随机">顺序</button><button type="button" aria-label="下一条">›</button>';bookmark.append(tools);let random=false;const rows=()=>DailyQuotes38.all().filter(q=>q.cat===(window.currentQuote?.cat||'poetry'));function move(direction){const list=rows();if(!list.length)return;const id=window.currentQuote?.id,at=list.findIndex(q=>q.id===id);const next=random?Math.floor(Math.random()*list.length):(at+direction+list.length)%list.length;DailyQuotes38.selectId(list[next].id)}tools.children[0].onclick=()=>move(-1);tools.children[1].onclick=()=>{random=!random;tools.children[1].textContent=random?'随机':'顺序'};tools.children[2].onclick=()=>move(1);head.querySelector('.bookmarkSource79')?.addEventListener('click',()=>{const picker=head.querySelector('.bookmarkPicker79');if(!picker)return;const sorted=[...picker.options].sort((a,b)=>{const rows=DailyQuotes38.all(),left=rows.findIndex(q=>q.id===a.value),right=rows.findIndex(q=>q.id===b.value);return left-right});picker.replaceChildren(...sorted)},true)}
 // The download album is selected before the work is archived; names and membership persist together.
 const downloadDialog=$('downloadDialog'),worksDialog=$('worksDialog');if(downloadDialog){const row=document.createElement('label');row.className='downloadAlbum81';row.textContent='存入专辑';const select=document.createElement('select'),newName=document.createElement('input');newName.placeholder='新专辑名称';newName.maxLength=36;row.append(select,newName);downloadDialog.querySelector('.dialogBody')?.append(row);let chosen='';async function albums(){return await DraftStore.get('work-albums81')||{}}async function options(){const data=await albums();select.replaceChildren(new Option('不分类',''),...Object.keys(data).map(x=>new Option(x,x)),new Option('新建专辑…','+'));select.value=chosen&&data[chosen]?chosen:'';newName.hidden=select.value!=='+'}downloadDialog.addEventListener('close',()=>{newName.hidden=true});$('export')?.addEventListener('click',()=>setTimeout(options,10));select.onchange=()=>newName.hidden=select.value!=='+';downloadDialog.querySelector('#generateDownload')?.addEventListener('click',()=>{chosen=select.value==='+'?newName.value.trim():select.value;if(chosen)DraftStore.get('work-albums81').then(data=>DraftStore.set('work-albums81',{...(data||{}),[chosen]:(data||{})[chosen]||[]}))},true);document.addEventListener('work-archived',async e=>{if(!chosen)return;const data=await albums();data[chosen]=[e.detail.id,...(data[chosen]||[]).filter(id=>id!==e.detail.id)];await DraftStore.set('work-albums81',data);chosen='';filterWorks()});let filter;async function filterWorks(){if(!worksDialog?.open)return;const data=await albums();if(!filter){filter=document.createElement('select');filter.className='albumFilter81';filter.setAttribute('aria-label','按专辑筛选我的作品');worksDialog.querySelector('.dialogHead')?.append(filter);filter.onchange=apply}const selected=filter.value;filter.replaceChildren(new Option('全部作品',''),...Object.keys(data).map(x=>new Option(x,x)));filter.value=selected;function apply(){const ids=new Set(data[filter.value]||[]);worksDialog.querySelectorAll('#worksGrid .workCard[data-work-id]').forEach(card=>card.hidden=!!filter.value&&!ids.has(card.dataset.workId))}apply()}worksDialog?.addEventListener('click',()=>setTimeout(filterWorks,60));new MutationObserver(()=>filterWorks()).observe($('worksGrid'),{childList:true})}
 // Small settings appear next to their icon; long dialogs keep their full view.
 const compact=new Set(['toolPopup79','sizeDialog38','brushDialog','paperDialog','sealDialog','musicDialog','mountDialog']);let anchor=null;document.addEventListener('pointerdown',e=>{const b=e.target.closest('button');if(b&&!b.closest('dialog'))anchor=b.getBoundingClientRect()},true);function place(dialog){if(!anchor||!compact.has(dialog.id)||!dialog.open)return;requestAnimationFrame(()=>{const w=Math.min(dialog.offsetWidth,innerWidth-16),h=Math.min(dialog.offsetHeight,innerHeight-16);dialog.style.position='fixed';dialog.style.margin='0';dialog.style.left=Math.max(8,Math.min(innerWidth-w-8,anchor.left+anchor.width/2-w/2))+'px';dialog.style.top=Math.max(8,Math.min(innerHeight-h-8,anchor.bottom+7))+'px'})}new MutationObserver(records=>{for(const r of records)if(r.target instanceof HTMLDialogElement)place(r.target)}).observe(document.body,{subtree:true,attributes:true,attributeFilter:['open']});
 window.Revision81={roll};
})();
