(function init103(){
 if(!window.Revision100?.ready){setTimeout(init103,60);return}
 const $=id=>document.getElementById(id),panel=$('paperPen100');for(const id of ['sizeNumber','quickSizeNumber','size'])if($(id))$(id).min='1';let anchor=null;
 function position(el,button){if(!button||el.dataset.fixedDialog==='true')return;const r=button.getBoundingClientRect(),w=el.offsetWidth||280,h=el.offsetHeight||240;el.style.setProperty('position','fixed','important');el.style.setProperty('margin','0','important');el.style.setProperty('right','auto','important');el.style.setProperty('bottom','auto','important');el.style.setProperty('left',Math.max(8,Math.min(innerWidth-w-8,r.left+r.width/2-w/2))+'px','important');el.style.setProperty('top',Math.max(8,Math.min(innerHeight-h-8,r.top>innerHeight/2?r.top-h-8:r.bottom+8))+'px','important')}
 function open(button){anchor=button;for(const row of panel.querySelectorAll('[data-source]')){const source=$(row.dataset.source);row.querySelector('input').value=source.value;row.querySelector('output').textContent=source.value+(row.dataset.source==='zoom'?'%':'')}panel.hidden=false;position(panel,button)}
 for(const id of ['topSize','zoomQuick79'])$(id).onclick=()=>open($(id));document.addEventListener('writing-pinch100',()=>position(panel,$('topSize')));
 function controls(root){for(const range of root.querySelectorAll('input[type=range]')){if(range.dataset.step103)continue;range.dataset.step103='yes';const box=document.createElement('span');box.className='adjust103';for(const [label,dir]of [['−',-1],['+',1]]){const b=document.createElement('button');b.type='button';b.textContent=label;b.setAttribute('aria-label',(dir<0?'减小':'增大')+(range.getAttribute('aria-label')||''));b.onclick=()=>{range.value=+range.value+dir*(+range.step||1);range.dispatchEvent(new Event('input',{bubbles:true}));range.dispatchEvent(new Event('change',{bubbles:true}))};box.append(b)}range.after(box)}}
 controls(document);new MutationObserver(records=>{for(const r of records)for(const n of r.addedNodes)if(n.nodeType===1&&!n.matches('.adjust103'))controls(n)}).observe(document.body,{subtree:true,childList:true});
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(b&&!b.closest('dialog,#paperPen100')){anchor=b;requestAnimationFrame(()=>{for(const d of document.querySelectorAll('dialog[open]:not(#dailyDialog)'))position(d,b)})}},true);
 let drag=null;document.addEventListener('pointerdown',e=>{const box=e.target.closest('dialog,#paperPen100');if(!box||box.dataset.fixedDialog==='true'||box.id==='dailyDialog'||e.target.closest('button,input,select,textarea,a,label'))return;const r=box.getBoundingClientRect();drag={box,id:e.pointerId,x:e.clientX,y:e.clientY,left:r.left,top:r.top};box.setPointerCapture(e.pointerId);e.preventDefault()},true);
 document.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const{box}=drag;box.style.setProperty('left',Math.max(0,Math.min(innerWidth-box.offsetWidth,drag.left+e.clientX-drag.x))+'px','important');box.style.setProperty('top',Math.max(0,Math.min(innerHeight-40,drag.top+e.clientY-drag.y))+'px','important');box.style.setProperty('right','auto','important');box.style.setProperty('bottom','auto','important');box.style.setProperty('margin','0','important');e.preventDefault()},{capture:true,passive:false});for(const name of ['pointerup','pointercancel'])document.addEventListener(name,()=>drag=null,true);
 window.Revision103={ready:true};
})();
