(function init109(){
 if(!window.Revision108?.ready){setTimeout(init109,40);return}
 const A=AnnotationApp,$=id=>document.getElementById(id),effects=$('previewEffects55'),steps=effects.querySelector('.finalSteps54'),rail=effects.querySelector('.finalRail54');document.body.classList.add('ui109');
 const lineBody109=$('lineDialog108').querySelector('.dialogBody');steps.addEventListener('click',()=>{if(lineBody109.parentElement!==$('lineDialog108'))$('lineDialog108').append(lineBody109);effects.classList.remove('customStyle109')},true);
 const choices=Revision62.photoPanel.querySelector('.photoChoices106'),postcard=[...choices.children].find(b=>b.textContent==='明信片');choices.children[0].after(postcard);
 function button(name,fn){const b=document.createElement('button');b.type='button';b.textContent=name;b.onclick=fn;return b}
 function configuration(name,ids,dialog){let tab=[...steps.children].find(b=>b.textContent.trim()===name);if(!tab){tab=button(name,()=>{});steps.append(tab)}tab.onclick=()=>{for(const b of steps.children)b.setAttribute('aria-current',String(b===tab));effects.classList.remove('photoActive63');const group=document.createElement('div');group.className='settings109';for(const id of ids){const source=$(id);if(!source)continue;const label=document.createElement('label');label.textContent=(source.closest('label')?.childNodes[0]?.textContent||id).trim();const input=source.cloneNode(true);input.removeAttribute('id');input.value=source.value;input.dataset.slider100='yes';input.dataset.stepper63='yes';input.setAttribute('aria-label',label.textContent);const update=()=>{source.value=input.value;source.dispatchEvent(new Event(source.type==='range'?'input':'change',{bubbles:true}));A.refreshPaper();A.persist()};input.onchange=update;if(input.type==='range')input.oninput=update;label.append(input);group.append(label)}group.append(button('更多设置',()=>A.openDialog(dialog)));rail.replaceChildren(group)}}
 configuration('印章',['headMode','headText','headType','headSize','sealMode','tailText','tailType','tailSize'],'sealDialog');
 configuration('临帖',['guideMode','guideOpacity'], 'copyDialog');
 for(const tab of [...steps.children]){const name=tab.textContent.trim();if(!['书风','纹样','格线'].includes(name))continue;const old=tab.onclick;tab.onclick=async function(e){await old?.call(this,e);if(name==='书风'){rail.append(button('自定义',()=>{const body=lineBody109;body.id='customStyle109';rail.replaceChildren(body);effects.classList.add('customStyle109')}))}else{const last=[...rail.querySelectorAll('button')].find(b=>b.textContent.trim()===(name==='纹样'?'无底纹':'无格线'));if(last)last.parentElement.append(last)}}}
 const lineOpen=$('topLines').onclick;$('topLines').onclick=()=>{const body=lineBody109;$('lineDialog108').append(body);effects.classList.remove('customStyle109');lineOpen()};
 function status(){const paper=A.getState().values.papercolor||'#ffffff',dark=Revision93.contrast(paper,'#fffaf0')>Revision93.contrast(paper,'#302719');$('previewWatermark90')?.style.setProperty('color',dark?'#fffaf0':'#302719','important');const auto=$('topAuto'),off=$('autoScroll').value==='off',vertical=$('followDirection').value==='vertical',right=!!window.bigPaperLayout63?.reverseHorizontal,key=off?'off':vertical?'down':right?'left':'right';const name={off:'停止走纸',down:'从上向下',left:'从右向左',right:'从左向右'}[key],paths={off:'M6 6h12v12H6z',down:'M12 4v16m-5-5 5 5 5-5',left:'M20 12H4m5-5-5 5 5 5',right:'M4 12h16m-5-5 5 5-5 5'};if(auto.dataset.direction109!==key){auto.dataset.direction109=key;auto.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="'+paths[key]+'"/></svg><span>走纸</span>';auto.title=name;auto.setAttribute('aria-label',name)}auto.setAttribute('aria-pressed',String(!off));$('topLines').setAttribute('aria-pressed',String($('inkMode').value==='assist'));for(const b of document.querySelectorAll('#writerLeft90 button,#writerRight90 button'))b.classList.toggle('active109',b.getAttribute('aria-pressed')==='true'||b.getAttribute('aria-expanded')==='true')}
 document.addEventListener('change',status);document.addEventListener('click',()=>requestAnimationFrame(status));document.addEventListener('preview-painted94',status);status();
 document.addEventListener('mode-ready109',()=>{if(Revision94.templateFollows)Revision94.apply(Revision94.palette())});
 const text=$('quoteExpanded');function paragraphs(){const raw=text.textContent||'';if(raw.length<400)return;const value=raw.split('\n').map(line=>{if(line.length<400)return line;const sentences=line.match(/[^。！？]+[。！？]?[”」]?/g)||[line],out=[];let part='';for(const sentence of sentences){part+=sentence;if(part.length>=160){out.push(part);part=''}}if(part)out.push(part);return out.join('\n\n')}).join('\n');if(value!==raw)text.textContent=value}new MutationObserver(paragraphs).observe(text,{childList:true,characterData:true,subtree:true});paragraphs();
 function quoteGroup(q){let era=String(q.dynasty||q.era||'').trim();const aliases={'唐代':'唐','唐朝':'唐','初唐':'唐','盛唐':'唐','中唐':'唐','晚唐':'唐','北宋':'宋','南宋':'宋','两宋之际':'宋','宋代':'宋','宋朝':'宋','元代':'元','明代':'明','清代':'清'};era=aliases[era]||era;return (q.country==='中国'||!q.country)&&era?era:q.country||era||'其他'}
 window.Revision109={ready:true,status,quoteGroup};
})();
