(function init119(){
 if(!window.Revision118?.ready||!window.InkCloud75){setTimeout(init119,50);return}
 const A=AnnotationApp,$=id=>document.getElementById(id),dialog=$('downloadDialog'),body=dialog.querySelector('.dialogBody');
 const choice=document.createElement('fieldset');choice.id='saveChoice119';choice.innerHTML='<legend>保存方式</legend><label><input type="radio" name="saveKind119" value="single" checked> 单张作品</label><label><input type="radio" name="saveKind119" value="series"> 作为套作品的一页</label><label class="seriesName119">套作品名称<input id="seriesName119" maxlength="40" placeholder="例如：我的手书集"></label><label class="publish119"><input id="publish119" type="checkbox"> 公开发布到书法殿堂</label><small>未勾选时只保存为私藏；公开发布需要登录账号。</small>';
 body.append(choice);const name=$('seriesName119'),publish=$('publish119');let pendingSeries=null,lastSeries=null;
 function update(){choice.classList.toggle('series119',choice.querySelector(':checked[name="saveKind119"]')?.value==='series')}
 choice.addEventListener('change',update);update();
 $('generateDownload').addEventListener('click',()=>{const series=choice.querySelector(':checked[name="saveKind119"]')?.value==='series';if(series&&!name.value.trim()&&!pendingSeries){name.value='亲笔作品集 '+new Date().toLocaleDateString('zh-CN')}window.SaveChoice119={kind:series?'series':'single',name:name.value.trim(),seriesId:series?pendingSeries:null,publish:publish.checked};if(publish.checked&&!InkCloud75.user)A.toast('作品已本机保存；登录账号后可在我的作品中公开发布')},true);
 $('export').addEventListener('click',()=>{if(A.getState().editingWork110)return;const series=!!pendingSeries;choice.querySelector('[value="series"]').checked=series;choice.querySelector('[value="single"]').checked=!series;publish.checked=false;update()});
 async function index(){return await DraftStore.get('work-series119')||{}}
 async function addPage(id,config){const all=await index(),seriesId=config.seriesId||'series:'+Date.now()+':'+Math.random().toString(36).slice(2,7);let series=all[seriesId];const work=await DraftStore.get(id);if(!work)return;if(!series)series={id:seriesId,title:config.name||work.title,created:Date.now(),pages:[],template:work.draft};if(!series.pages.includes(id))series.pages.push(id);series.template=work.draft||series.template;all[seriesId]=series;await DraftStore.set('work-series119',all);lastSeries=seriesId;pendingSeries=null;decorate();next.hidden=false;next.textContent='继续写第 '+(series.pages.length+1)+' 页';document.dispatchEvent(new Event('work-series119'))}
 document.addEventListener('work-archived',e=>{if(e.detail.choice?.kind==='series')addPage(e.detail.id,e.detail.choice).catch(err=>A.toast('套作品页序未保存：'+err.message))});
 const next=document.createElement('button');next.type='button';next.id='nextPage119';next.hidden=true;next.textContent='继续写下一页';$('imageDialog').querySelector('.dialogHead').append(next);
 async function start(seriesId){const series=(await index())[seriesId];if(!series)return;await A.startSeriesPage119(series.template||A.getState());pendingSeries=seriesId;lastSeries=seriesId;name.value=series.title;choice.querySelector('[value="series"]').checked=true;choice.querySelector('[value="single"]').checked=false;update();$('imageDialog').close();$('worksDialog').close();A.showWriter();A.toast('已按「'+series.title+'」模板开始第 '+(series.pages.length+1)+' 页')}
 next.onclick=()=>{if(lastSeries)start(lastSeries).catch(e=>A.toast(e.message))};
 const section=document.createElement('section');section.id='workSeries119';$('worksGrid').before(section);
 async function decorate(){if(!$('worksDialog').open)return;const all=await index();section.replaceChildren();const series=Object.values(all);if(!series.length)return;const title=document.createElement('h3');title.textContent='套作品';section.append(title);for(const item of series){const row=document.createElement('div');row.className='seriesRow119';const label=document.createElement('strong');label.textContent=item.title+' · '+item.pages.length+' 页';const open=document.createElement('button');open.textContent='查看页序';open.onclick=()=>{const panel=document.createElement('dialog');panel.className='seriesDialog119';const head=document.createElement('header');head.textContent=item.title+' · '+item.pages.length+' 页';const close=document.createElement('button');close.textContent='关闭';close.onclick=()=>panel.close();head.append(close);panel.append(head);item.pages.forEach((id,i)=>{const b=document.createElement('button');b.textContent='第 '+(i+1)+' 页';b.onclick=()=>{$('worksDialog').close();panel.close();A.openWork(id)};panel.append(b)});const more=document.createElement('button');more.textContent='按此模板续写下一页';more.onclick=()=>{panel.close();start(item.id)};panel.append(more);panel.addEventListener('close',()=>panel.remove(),{once:true});document.body.append(panel);panel.showModal()};const add=document.createElement('button');add.textContent='续写下一页';add.onclick=()=>start(item.id);row.append(label,open,add);section.append(row);for(const [i,id]of item.pages.entries()){const card=$('worksGrid').querySelector('[data-work-id="'+CSS.escape(id)+'"]');if(card){let mark=card.querySelector('.seriesMark119');if(!mark){mark=document.createElement('span');mark.className='seriesMark119';card.prepend(mark)}mark.textContent=item.title+' · 第 '+(i+1)+' 页'}}}}
 $('worksDialog').addEventListener('toggle',()=>{if($('worksDialog').open)decorate()});new MutationObserver(()=>{if($('worksDialog').open)decorate()}).observe($('worksGrid'),{childList:true});
 // A recent ink hue is not immediately repeated on the next new mode.
 let lastHue=-1;function hue(hex){const r=parseInt(hex.slice(1,3),16)/255,g=parseInt(hex.slice(3,5),16)/255,b=parseInt(hex.slice(5,7),16)/255,high=Math.max(r,g,b),low=Math.min(r,g,b),d=high-low;if(d<.1)return -1;return (high===r?((g-b)/d)%6:high===g?(b-r)/d+2:(r-g)/d+4)*60+360}
 document.addEventListener('mode-ready109',e=>{if(e.detail?.restored)return;const pool=HeritagePalettes102.filter(p=>p.paper&&p.ink&&Revision93.contrast(p.paper,p.ink)>=4.5),options=pool.filter(p=>{const h=hue(p.ink)%360;return h<0||lastHue<0||Math.min(Math.abs(h-lastHue),360-Math.abs(h-lastHue))>65});const p={...(options.length?options:pool)[Math.floor(Math.random()*(options.length||pool.length))]};if(!p)return;lastHue=hue(p.ink)%360;const seals=['#a82d29','#aa741d','#66509c','#2867b1','#267567'].filter(c=>Revision93.contrast(p.paper,c)>=2.5);p.seal=seals[Math.floor(Math.random()*seals.length)]||'#a82d29';Revision94.apply(p)});
 window.Revision119={ready:true,start,decorate};
})();
