/* Stable viewport geometry, square seals and compact work actions. */
(function(root){
function readerBounds(viewport,rect,width,height){const gap=8,w=Math.max(80,viewport.width),h=Math.max(80,viewport.height),left=viewport.left||0,top=viewport.top||0;const desiredW=Math.min(w-gap*2,Math.max(Math.min(220,w-gap*2),width)),desiredH=Math.min(h-gap*2,Math.max(Math.min(220,h-gap*2),height));return{left:Math.max(left+gap,Math.min(left+w-gap-desiredW,rect.left)),top:Math.max(top+gap,Math.min(top+h-gap-desiredH,rect.top)),width:desiredW,height:desiredH}}
root.ReaderBounds152={fit:readerBounds};if(!root.document)return;
(function init(){if(!root.Revision151?.ready){setTimeout(init,80);return}const $=id=>document.getElementById(id),A=AnnotationApp;
function avatar(){const b=$('account47');if(!b||!root.InkCloud75?.user)return;const name=InkCloud75.user.user_metadata?.full_name||InkCloud75.user.email?.split('@')[0]||'我',char=Array.from(name)[0],key=char+'|'+(root.sealFontRevision||0);if(b.dataset.seal152===key&&b.querySelector('canvas'))return;const canvas=document.createElement('canvas');canvas.width=canvas.height=128;canvas.ariaHidden='true';canvas.getContext('2d').drawImage(SealEngine.stamp({text:char,type:'yin',font:'yishan',fontLoaded:!!root.yiShanBeiSealReady,color:'#b62118',rough:.08}),0,0,128,128);b.replaceChildren(canvas);b.dataset.seal152=key;b.classList.add('squareSeal152')}
document.addEventListener('cloud-user84',avatar);document.fonts?.addEventListener('loadingdone',avatar);avatar();
const theme=$('themeSwitch90');function syncTheme(){if(!theme)return;const dark=document.body.dataset.homeTheme==='stars',text=dark?'深':'浅';theme.dataset.mode=dark?'dark':'light';let label=theme.querySelector('span');if(!label){label=document.createElement('span');theme.replaceChildren(label)}if(label.textContent!==text)label.textContent=text;theme.ariaLabel=dark?'深色，点击切浅色':'浅色，点击切深色'}new MutationObserver(syncTheme).observe(document.body,{attributes:true,attributeFilter:['data-home-theme']});syncTheme();
const works=$('worksDialog');function captions(){if(!works)return;for(const b of works.querySelectorAll('.dialogHead button')){const name=b.ariaLabel||b.title||'';const text=/写字排行榜/.test(name)?'排名':/书法殿堂/.test(name)?'殿堂':null;if(!text)continue;if(b.dataset.caption145!==text)b.dataset.caption145=text;const label=b.querySelector('.caption149');if(label&&label.textContent!==text)label.textContent=text}}const workHead=works?.querySelector('.dialogHead');if(workHead)new MutationObserver(captions).observe(workHead,{childList:true,subtree:true});captions();
function viewport(){const v=window.visualViewport;return{left:v?.offsetLeft||0,top:v?.offsetTop||0,width:v?.width||innerWidth,height:v?.height||innerHeight}}function fitReader(){const reader=$('dailyDialog');if(!reader?.open||reader.dataset.resized133!=='true')return;const r=reader.getBoundingClientRect(),b=readerBounds(viewport(),r,r.width,r.height);for(const[k,v]of Object.entries(b))reader.style.setProperty(k,v+'px','important')}
addEventListener('resize',fitReader);window.visualViewport?.addEventListener('resize',fitReader);
// Refresh the real viewport after Safari/Chrome finish rotating, without changing paper or ink.
let frame;function layout(){cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const v=viewport(),root=document.documentElement;root.style.setProperty('--app-height',v.height+'px');root.style.setProperty('--app-width',v.width+'px');root.style.setProperty('--view-top',v.top+'px');root.style.setProperty('--view-left',v.left+'px');A.refresh();fitReader()})}addEventListener('orientationchange',()=>{layout();setTimeout(layout,250);setTimeout(layout,700)});addEventListener('pageshow',layout);
root.Revision152={ready:true};})();
})(typeof window==='undefined'?globalThis:window);
