(function init(){if(!window.Revision93?.ready||!window.Palettes94||!window.Timeline73){setTimeout(init,60);return}
const $=id=>document.getElementById(id),A=AnnotationApp;
const intro=document.querySelector('#annotationHome .annotationIntro');
if(intro){intro.querySelector('.heroConstellation91')?.remove();const picture=document.createElement('picture');picture.className='heroPicture94';const source=document.createElement('source');source.media='(max-width:600px)';source.srcset='hero-mobile94.webp';const img=document.createElement('img');img.src='hero-wide94.webp';img.alt='以李斯、王羲之、颜真卿、苏轼、黄庭坚、达芬奇、手岛右卿、伊本·穆格莱为灵感的AI群像';img.fetchPriority='high';img.decoding='async';picture.append(source,img);intro.prepend(picture);
 const people=[['秦','李斯','峄山刻石'],['东晋','王羲之','兰亭序'],['唐','颜真卿','祭侄文稿'],['北宋','苏轼','寒食帖'],['北宋','黄庭坚','砥柱铭'],['意大利','达芬奇','阿伦德尔手稿'],['日本','手岛右卿','崩坏'],['阿拔斯王朝','伊本·穆格莱','古兰经抄写']];const labels=document.createElement('div');labels.className='heroPeople94';labels.setAttribute('aria-label','书法人物与代表作品');people.forEach(([era,name,work],i)=>{const label=document.createElement('div');label.className='heroPerson94';label.style.setProperty('--hero-x94',(25+(i+.94)*75/8)+'%');label.style.setProperty('--mobile-x94',((i%4)*25+24)+'%');label.style.setProperty('--mobile-y94',(i<4?42:75)+'%');for(const [tag,text]of [['span',era],['b',name],['span',work]]){const node=document.createElement(tag);node.textContent=text;label.append(node)}label.title=era+' · '+name+' · '+work;if(i===7)label.title+='；关联其比例书法贡献，不宣称现存抄本为本人亲笔';labels.append(label)});intro.append(labels)}
const logo=$('annotationHomeButton'),left=$('writerLeft90');if(logo&&left){left.prepend(logo);logo.onclick=()=>{document.getElementById('dailyDialog')?.close();AnnotationHome.show();toTop()}}
function toTop(){const home=$('annotationHome');if(document.body.classList.contains('home-open')&&home){home.style.scrollSnapType='none';home.scrollTo({top:0,behavior:'instant'})}window.scrollTo({top:0,behavior:'instant'})}
document.addEventListener('dblclick',e=>{if(e.target.closest('.annotationBrand,.annotationIntro,.topStrip,#homeTop76')){if(e.target.closest('input,textarea,select'))return;toTop()}},true);
let lastTop=0;document.addEventListener('pointerup',e=>{if(e.pointerType!=='touch'||!document.body.classList.contains('home-open')||e.clientY>65||e.target.closest('button,input,select,a'))return;const now=performance.now();if(now-lastTop<340){toTop();lastTop=0}else lastTop=now},true);
const account=$('cloudAccount75'),head=account?.querySelector('.cloud75-head');if(head){head.querySelector('button')?.classList.add('accountClose94')}
const note=document.createElement('aside');note.id='paletteNote94';note.className='paletteNote94';note.hidden=true;note.setAttribute('role','status');note.setAttribute('aria-live','polite');$('board').append(note);let current=null,framePending=false;
const colours=Palettes94.map(p=>{p={...p};if(Revision93.contrast(p.paper,p.ink)<4.5)p.ink=Revision93.contrast(p.paper,'#000000')>Revision93.contrast(p.paper,'#ffffff')?'#000000':'#ffffff';return p});let last='';
function palette(){const q=window.currentQuote||{},era=q.dynasty||q.era||'',priority=colours.filter(p=>p.family==='中国'&&q.country==='中国'||['唐','宋'].includes(p.family)&&era.includes(p.family)||q.country&&p.family===q.country);const pool=(priority.length&&Math.random()<.6?priority:colours).filter(p=>p.id!==last);const p={...pool[Math.floor(Math.random()*pool.length)]};last=p.id;return p}
function positionNote(){framePending=false;note.hidden=true;}
function scheduleNote(){if(!framePending){framePending=true;requestAnimationFrame(positionNote)}}
function apply(p){const rgb=(p.paper||'#ffffff').match(/[a-f0-9]{2}/gi).map(x=>parseInt(x,16)),light=rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722,cool=rgb[2]>rgb[0]+8;const mounts=light<100?['gallery','paris','nordic']:cool?['ru','gallery','nordic','walnut']:['song','japanese','paris','walnut'];const key=mounts[Math.floor(Math.random()*mounts.length)],m=Mounting.presets[key],words={song:'素绫暖灰',japanese:'浮裱浅木',nordic:'深盒白橡',paris:'细边香槟',ru:'细缘汝青',walnut:'悬浮乌木',gallery:'错层雪白'};p={...p,idea:'墨纸相映 · '+words[key],titleColor:Revision93.contrast(m.mat,p.ink)>=3?p.ink:(Revision93.contrast(m.mat,'#805437')>=3?'#805437':'#e7bc86')};const control=$('quickMount');control.value=key;control.dispatchEvent(new Event('change',{bubbles:true}));current=p;A.setPaletteCredit96?.(p);note.replaceChildren();const title=document.createElement('strong'),idea=document.createElement('small');title.textContent=p.name;idea.textContent=p.idea;note.append(title,idea);Revision88.applyPalette(p);scheduleNote()}
$('previewRandom79').onclick=()=>apply(palette());$('previewReset73').addEventListener('click',()=>{current=null;A.setPaletteCredit96?.(null);note.hidden=true});document.addEventListener('quote-changed',()=>apply(palette()));document.addEventListener('preview-painted94',scheduleNote);addEventListener('resize',scheduleNote);new ResizeObserver(scheduleNote).observe($('board'));document.addEventListener('change',e=>{if(['color','papercolor','headColor','freeInk','freePaper'].includes(e.target.id)){current=null;A.setPaletteCredit96?.(null);note.hidden=true}});
Revision93.palette=palette;window.Revision94={ready:true,palettes:colours,palette,apply,toTop,get current(){return current}};
})();
