/* Version 80: editorial homepage, preview controls, reading, and copy navigation. */
(function init(){
 if(!window.AnnotationApp?.ready||!window.DailyQuotes38||!window.Revision62||!window.Timeline73||!document.getElementById('previewRatio79')){setTimeout(init,80);return}
 const $=id=>document.getElementById(id),A=AnnotationApp;
 for(const nav of [$('homeQuick47'),$('writerModes53')]){const buttons=[...nav?.querySelectorAll('button')||[]],photo=buttons.find(b=>b.textContent.trim()==='图文'),create=buttons.find(b=>b.textContent.trim()==='创作');if(photo&&create)nav.insertBefore(photo,create)}
 // A bookmark is a reference sheet. Reading it never changes the selected work.
 const bookmark=$('dailyDialog'),quoteText=$('quoteText'),source=bookmark?.querySelector('.bookmarkSource79'),picker=bookmark?.querySelector('.bookmarkPicker79');
 quoteText?.addEventListener('click',e=>e.stopImmediatePropagation(),true);
 if(source&&picker){source.onclick=()=>{picker.replaceChildren();const rows=DailyQuotes38.all(),groups=new Map();for(const q of rows){const group=q.country||q.era||q.dynasty||({'poetry':'中国诗词','moon':'中秋专题','liu':'刘欢作品'}[q.cat])||q.cat||'其他';if(!groups.has(group))groups.set(group,[]);groups.get(group).push(q)}for(const [group,items] of [...groups].sort((a,b)=>a[0].localeCompare(b[0],'zh'))){const opt=document.createElement('optgroup');opt.label=group;items.sort((a,b)=>(a.author||'').localeCompare(b.author||'','zh')||(a.title||'').localeCompare(b.title||'','zh'));for(const q of items){const option=document.createElement('option');option.value=q.id||q.s+'|'+q.q;option.textContent=[q.author,q.title||q.s].filter(Boolean).join(' · ');opt.append(option)}picker.append(opt)}picker.value=window.currentQuote?.id||'';picker.hidden=!picker.hidden;if(!picker.hidden)picker.focus()};picker.onchange=()=>{const row=DailyQuotes38.all().find(q=>(q.id||q.s+'|'+q.q)===picker.value);if(row)DailyQuotes38.selectId(row.id);picker.hidden=true};document.addEventListener('quote-changed',e=>{const q=e.detail;source.textContent=[q.country||q.era||q.dynasty||'中国',q.author,q.title||String(q.s||'').match(/《([^》]+)》/)?.[1]].filter(Boolean).join(' · ')})}
 // Keep the user's last deliberate category within this visit; default new visits to poetry.
 try{localStorage.setItem('iinnkk.quoteDefault62','poetry')}catch{};DraftStore.get('settings62').then(settings=>{if(settings){settings.defaultCategory='poetry';return DraftStore.set('settings62',settings)}}).catch(()=>{});DailyQuotes38.select('poetry');
 document.addEventListener('click',e=>{const card=e.target.closest('.timelineNow73');if(!card||window.InkStudio50?.isAdmin)return;const id=card.dataset.id;if(!id)return;e.preventDefault();e.stopImmediatePropagation();window.InkCloud75?.openPublicByLocalId(id).catch(error=>A.toast(error.message))},true);
 const preview=$('previewEffects55'),rail=preview?.querySelector('.finalRail54'),steps=preview?.querySelector('.finalSteps54'),ratio=$('previewRatio79');
 function refit(){if(A.isOverview55()){const toggle=$('fitView');toggle.click();toggle.click()}}
 if(ratio&&rail){ratio.onclick=()=>{steps.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===ratio));rail.replaceChildren();const choices=document.createElement('div');choices.className='ratioRail80';for(const option of $('ratio').options){if(!option.value)continue;const b=document.createElement('button');b.type='button';b.textContent=option.textContent.trim().split(/[（(]/)[0].replace(/微信.*贴图/,'贴图').slice(0,8);b.title=option.textContent;b.setAttribute('aria-pressed',String(option.value===$('ratio').value));b.onclick=()=>{$('ratio').value=option.value;$('ratio').dispatchEvent(new Event('change',{bubbles:true}));choices.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));refit()};choices.append(b)}rail.append(choices)}}
 preview?.querySelector('.previewZoom66')?.remove();
 const random=$('previewRandom79');if(random)random.onclick=()=>{const sets=[{paper:'#f7f1e3',ink:'#182c35',seal:'#a63530',mount:'paris'},{paper:'#172a36',ink:'#fff5df',seal:'#e9aa62',mount:'song'},{paper:'#a82724',ink:'#fff9df',seal:'#f3d77d',mount:'dark'},{paper:'#dbe6e4',ink:'#173e36',seal:'#a6312a',mount:'nordic'}],p=sets[Math.floor(Math.random()*sets.length)];A.applyLiteraryPalette61(p);const mount=$('quickMount');if(mount&&[...mount.options].some(x=>x.value===p.mount)){mount.value=p.mount;mount.dispatchEvent(new Event('change',{bubbles:true}))}refit()};
 // Page controls remain within reach while a long model book is being traced.
 const float=document.createElement('div');float.id='copyNav80';float.innerHTML='<button type="button" data-copy="prev" aria-label="临帖上一页">‹</button><button type="button" data-copy="view" aria-label="拼帖预览">▤</button><button type="button" data-copy="next" aria-label="临帖下一页">›</button>';document.body.append(float);const sync=()=>{const quick=$('copyPageQuick38');float.hidden=!quick||quick.hidden||document.body.classList.contains('home-open');for(const [key,id] of [['prev','copyPrev38'],['next','copyNext38']])float.querySelector('[data-copy="'+key+'"]').disabled=!!$(id)?.disabled};for(const [key,id] of [['prev','copyPrev38'],['next','copyNext38'],['view','copyPageQuick38']])float.querySelector('[data-copy="'+key+'"]').onclick=()=>$(id)?.click();new MutationObserver(sync).observe($('copyPageQuick38'),{attributes:true,attributeFilter:['hidden']});new MutationObserver(sync).observe($('copyPrev38').parentElement,{subtree:true,attributes:true,attributeFilter:['disabled']});sync();
})();
