/* Version 79: one compact timeline, study marks and direct writing controls. */
(function init(){if(!window.Timeline73||!window.InkCloud75||!window.AnnotationApp?.ready||!document.getElementById('bottomIcons39')){setTimeout(init,80);return}
 const $=id=>document.getElementById(id),A=AnnotationApp,home=$('annotationHome');
 const nav=$('homeQuick47'),brand=document.createElement('button');brand.id='homeBrand79';brand.type='button';brand.innerHTML='<span class="homeBrandSeal79">筆</span><span>今日亲笔</span>';brand.setAttribute('aria-label','今日亲笔，回到首页顶部');brand.onclick=()=>home.scrollTo({top:0,behavior:'instant'});nav?.prepend(brand);
 const intro=home.querySelector('.annotationIntro');if(intro){intro.replaceChildren();const h=document.createElement('strong'),p=document.createElement('small');h.textContent='人类群星闪耀时';p.textContent='在数字赛博空间，你我一起结网记字！';intro.append(h,p)}
 function refreshMarks(){for(const card of home.querySelectorAll('.timelineCard73[data-id]')){if(card.classList.contains('timelineNow73')||card.dataset.id==='qianzi-source')continue;let row=card.querySelector('.timelineMarks79');if(!row){row=document.createElement('div');row.className='timelineMarks79';for(const [kind,label] of [['copy','临写'],['visit','打卡']]){const b=document.createElement('button');b.type='button';b.dataset.mark=kind;b.textContent=label;b.onclick=async e=>{e.stopPropagation();const cloud=window.InkCloud75;if(!cloud.user){$('account47')?.click();A.toast('登录后同步书法足迹');return}const c=Timeline73.chapters.find(x=>x.id===card.dataset.id);if(!c)return;if(kind==='copy'){await cloud.mark(c.id,'copy');Timeline73.openCopy(c).catch(()=>A.toast('原帖尚未上传，已记录临摹意向'))}else{const dialog=document.createElement('dialog');dialog.className='visitDialog79';const title=document.createElement('strong');title.textContent=c.title+' · '+c.museum;dialog.append(title);const visits=[[/国立故宫博物院/,'https://www.npm.gov.tw/Articles.aspx?l=1&sno=02007004'],[/西安碑林博物馆/,'https://www.beilin-museum.com/index.php'],[/苏州博物馆/,'https://www.szmuseum.com/Wap/Account/VenuesReservation'],[/故宫博物院/,'https://ticket.dpm.org.cn/']];const booking=visits.find(([re])=>re.test(c.museum||''))?.[1];if(booking||c.url){const a=document.createElement('a');a.href=booking||c.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=booking?'馆方预约与参观 ↗':'馆藏资料 · 核对开放信息 ↗';dialog.append(a)}const done=document.createElement('button');done.textContent='我已到访 · 领取阳刻章';done.onclick=async()=>{await cloud.mark(c.id,'visit');dialog.close();dialog.remove();refreshMarks()};const close=document.createElement('button');close.textContent='关闭 ×';close.onclick=()=>{dialog.close();dialog.remove()};dialog.append(done,close);document.body.append(dialog);dialog.showModal()}refreshMarks()};row.append(b)}card.append(row)}const marks=window.InkCloud75.marks[card.dataset.id]||{};for(const b of row.querySelectorAll('button')){const done=!!marks[b.dataset.mark];b.classList.toggle('done79',done);b.textContent=done?(b.dataset.mark==='copy'?'阴刻 · 临写过了':'阳刻 · 打过卡了'):(b.dataset.mark==='copy'?'临写':'打卡')}}}
 new MutationObserver(()=>refreshMarks()).observe($('inkTimeline73'),{childList:true,subtree:false});document.addEventListener('timeline-mark79',refreshMarks);refreshMarks();
 // The lock controls paper gestures after a diameter is committed. Brush editing stays accessible.
 $('lockWriting39')?.remove();for(const id of ['brushDialog','sizeDialog38','sizeModes47'])$(id)?.addEventListener('close',()=>{window.writingLocked=true;window.Revision39?.syncLock?.();A.persist()});
 const icons=$('bottomIcons39'),zoom=document.createElement('button');zoom.type='button';zoom.id='zoomQuick79';zoom.title='纸面缩放';zoom.setAttribute('aria-label','纸面缩放');zoom.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M3 9V3h6M15 3h6v6M21 15v6h-6M9 21H3v-6M3 3l6 6m12-6-6 6m6 12-6-6M3 21l6-6"/></svg>';($('topSize')||$('sizeQuick54')||icons.firstElementChild)?.after(zoom);
 const popup=document.createElement('dialog');popup.id='toolPopup79';popup.innerHTML='<header><strong></strong><button type="button" data-close>×</button></header><div class="toolPopupBody79"></div>';document.body.append(popup);popup.querySelector('[data-close]').onclick=()=>popup.close();const content=popup.querySelector('.toolPopupBody79');
 function open(title){popup.querySelector('strong').textContent=title;content.replaceChildren();if(!popup.open)popup.showModal()}
 function choose(label,fn){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>{fn();popup.close()};content.append(b)}
 zoom.onclick=()=>{open('纸面缩放');for(const n of [100,150,200,300,400,500,750,1000])choose(n+'%',()=>setZoom(n));const slider=document.createElement('input');slider.type='range';slider.min='50';slider.max='1000';slider.step='5';slider.value=$('zoom').value;slider.setAttribute('aria-label','缩放滑块');const value=document.createElement('output');value.textContent=slider.value+'%';slider.oninput=()=>{value.textContent=slider.value+'%';setZoom(+slider.value)};content.append(slider,value);const done=document.createElement('button');done.textContent='完成';done.onclick=()=>{window.writingLocked=true;A.persist();popup.close()};content.append(done)};
 function setZoom(n){window.writingLocked=false;$('zoom').disabled=false;$('zoom').value=String(n);$('zoom').dispatchEvent(new Event('input',{bubbles:true}));$('zoom').dispatchEvent(new Event('change',{bubbles:true}));window.writingLocked=true;window.Revision39?.syncLock?.();A.persist();A.refresh()}
 const ink=$('topInk');if(ink)ink.onclick=e=>{e.preventDefault();open('墨色');for(const b of document.querySelectorAll('[data-ink]')){const swatch=document.createElement('button');swatch.type='button';swatch.className='inkSwatch91';swatch.title=b.getAttribute('aria-label')||b.dataset.ink;swatch.setAttribute('aria-label',swatch.title);swatch.style.setProperty('--swatch91',b.dataset.ink);swatch.onclick=()=>{b.click();popup.close()};content.append(swatch)};const color=document.createElement('input');color.type='color';color.value='#263b42';color.setAttribute('aria-label','自定义墨色');color.oninput=()=>{const field=$('freeInk');if(field){field.value=color.value;field.dispatchEvent(new Event('input',{bubbles:true}));field.dispatchEvent(new Event('change',{bubbles:true}))}};content.append(color)};
 const style=$('styleCycle39');if(style)style.onclick=()=>{open('书风与笔墨');for(const [key,p] of Object.entries(A.presets))choose(p.name.split('·')[0].split('-')[0].slice(0,6),()=>{$('quickStyle').value=key;$('quickStyle').dispatchEvent(new Event('change',{bubbles:true}))});const detail=document.createElement('button');detail.textContent='全部笔墨参数 ↗';detail.onclick=()=>{popup.close();A.openDialog('brushDialog')};content.append(detail)};
 // Ratio comes before the calligraphy style in the preview's category row.
 const effects=$('previewEffects55'),steps=effects?.querySelector('.finalSteps54');if(steps){const ratio=document.createElement('button');ratio.id='previewRatio79';ratio.type='button';ratio.textContent='比例';steps.prepend(ratio);ratio.onclick=()=>{open('作品比例');for(const option of $('ratio').options)choose(option.textContent,()=>{$('ratio').value=option.value;$('ratio').dispatchEvent(new Event('change',{bubbles:true}));A.refresh()})}};
 const actions=effects?.querySelector('.previewActions56');if(actions){const original=[...actions.querySelectorAll('button')];if(original.length>=2){original.at(-2).textContent='书写';original.at(-1).textContent='下载'}const random=document.createElement('button');random.id='previewRandom79';random.type='button';random.textContent='随机';actions.prepend(random);random.onclick=async()=>{const schemes=[['#f5f1e6','#172c38','#af392f','paris'],['#182e38','#f7f1df','#e5a653','song'],['#b12624','#fff7d8','#e2bd76','dark'],['#d8e5e7','#183e34','#9d352f','nordic']];const [paper,ink,seal,mount]=schemes[Math.floor(Math.random()*schemes.length)];await A.configure47({values:{papercolor:paper,headColor:seal,tailColor:seal},mountKey:mount});const c=$('freeInk');if(c){c.value=ink;c.dispatchEvent(new Event('input',{bubbles:true}));c.dispatchEvent(new Event('change',{bubbles:true}))}A.refresh()}};
 for(const el of [$('postcardCity'),$('postalCity41')])if(el&&el.value==='巴黎'){el.value='上海';el.dispatchEvent(new Event('change',{bubbles:true}))}
 const bookmark=$('dailyDialog');if(bookmark){const head=bookmark.querySelector('.dialogHead');head.querySelector('h2')?.remove();const source=document.createElement('button');source.type='button';source.className='bookmarkSource79';source.textContent='国家 · 作者 · 作品名';const picker=document.createElement('select');picker.className='bookmarkPicker79';picker.hidden=true;picker.setAttribute('aria-label','跳选文学佳句');head.prepend(source,picker);source.onclick=()=>{picker.replaceChildren();for(const q of DailyQuotes38.all().filter(x=>x.cat===(window.currentQuote?.cat||'poetry')).sort((a,b)=>String(a.country||a.era||'').localeCompare(String(b.country||b.era||''),'zh')||String(a.author||'').localeCompare(String(b.author||''),'zh'))){const o=document.createElement('option');o.value=q.id;o.textContent=[q.country,q.author,q.title].join(' · ');picker.append(o)}picker.value=window.currentQuote?.id||'';picker.hidden=!picker.hidden;if(!picker.hidden)picker.focus()};picker.onchange=()=>{DailyQuotes38.selectId(picker.value);picker.hidden=true};const close=head.querySelector('[data-close]');if(close){close.textContent='×';close.setAttribute('aria-label','关闭书签')}function updateBookmark(){const q=window.currentQuote;if(!q)return;source.textContent=[q.country||q.era||'中国',q.author||'',q.title||''].filter(Boolean).join(' · ')}document.addEventListener('quote-changed',updateBookmark);updateBookmark();
}
})();
