(function init(){if(!window.Revision38||!window.Moments||!window.CopyAlbums38||!document.getElementById('annotationHome')){setTimeout(init,40);return}const $=id=>document.getElementById(id),app=AnnotationApp,icon=Revision38.icon;
const row=document.createElement('nav');row.id='bottomIcons39';row.setAttribute('aria-label','常用书写工具');$('bottomDock').prepend(row);
const ids=['topPattern','topMusic','topRatio','topMount','topLines','topInk','calendarMoments','topReset'];
for(const id of ids)if($(id))row.append($(id));
const make=(id,label,path,fn)=>{const b=icon(id,label,path);row.append(b);b.onclick=fn;return b};
make('copyPagesQuick39','多图临帖：切换与结束','<rect x="3" y="6" width="14" height="15"/><path d="M7 2h14v15M6 14h8m-3-3 3 3-3 3"/>',()=>app.openDialog('copyDialog'));
const lock=make('lockWriting39','锁定缩放与笔径','<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4"/>',()=>{window.writingLocked=!window.writingLocked;syncLock();app.persist();app.toast(window.writingLocked?'已锁定缩放和笔径，双指移纸':'已解锁，可双指缩放与移动')});
function syncLock(){lock.setAttribute('aria-pressed',String(!!window.writingLocked));lock.title=window.writingLocked?'已锁定 · 点击解锁':'未锁定 · 点击锁定';lock.querySelector('path').setAttribute('d',window.writingLocked?'M8 10V6a4 4 0 0 1 8 0v4':'M8 10V6a4 4 0 0 1 7-2');for(const id of ['size','sizeNumber','quickSize','quickSizeNumber','topSize','zoom'])if($(id))$(id).disabled=!!window.writingLocked}syncLock();
make('styleCycle39','书风：张旭／颜真卿／王铎','<path d="m4 20 4-1L20 7l-3-3L5 16zM3 7h8M3 11h5"/>',()=>{const styles=['zhang','yan','wangduo'],s=$('quickStyle'),n=styles[(styles.indexOf(s.value)+1)%3],locked=app.getState().brush.size;s.value=n;s.dispatchEvent(new Event('change'));if(window.writingLocked){$('sizeNumber').value=locked;$('sizeNumber').dispatchEvent(new Event('change'))}app.updatePosition();app.toast(app.presets[n].name)});
const scope=make('inkScope39','墨色作用范围','<path d="M4 6h16M4 12h16M4 18h16"/>',()=>{const s=$('recolorScope');s.value=s.value==='all'?'next':'all';syncScope();app.persist();app.toast(s.selectedOptions[0].textContent)});
function syncScope(){const all=$('recolorScope').value==='all';scope.setAttribute('aria-pressed',String(all));scope.title=all?'整幅改色 · 点击改下一笔':'只改下一笔 · 点击整幅改色';scope.querySelector('path').setAttribute('d',all?'M4 6h16M4 12h16M4 18h16':'M4 19c4 0 4-5 8-5m0 0 6-10 3 2-7 10-2-2')}syncScope();if($('topInk'))$('topInk').after(scope);
const oldRestore=window.restoreToolbarOrder;window.restoreToolbarOrder=order=>{oldRestore(order);for(const id of ids)if($(id))row.append($(id));if($('topInk'))$('topInk').after(scope)};
row.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.title){let tip=$('bottomTip39');if(!tip){tip=document.createElement('div');tip.id='bottomTip39';document.body.append(tip)}tip.textContent=b.title;const r=b.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(innerWidth-210,r.left))+'px';tip.style.top=Math.max(8,r.top-42)+'px';tip.hidden=false;clearTimeout(tip.timer);tip.timer=setTimeout(()=>tip.hidden=true,1600)}});
// One compact editor for every stamp; original controls remain only as serialized settings.
const old=$('sealDialog').querySelector('.dialogBody');old.hidden=true;const menu=document.createElement('div');menu.className='dialogBody sealGroups39';$('sealDialog').append(menu);
function sealMenu(){if(window.SealMenu41)return SealMenu41();menu.replaceChildren();for(const [label,key]of [['引首章','head'],['腰章','waist'],['落款章','tail']]){const section=document.createElement('section'),h=document.createElement('h3');h.textContent=label;section.append(h);const items=app.sealItems().filter(s=>key==='waist'?s.key.startsWith('extra'):s.key===key);if(!items.length){const p=document.createElement('p');p.textContent=key==='waist'?'编辑任意印章，点击“复制此印”后拖到腰部。':'当前未启用';section.append(p)}for(const item of items){const b=document.createElement('button');b.textContent=item.config.text+' · 编辑';b.onclick=()=>{$('sealDialog').close();app.selectSeal(item.key)};section.append(b)}if(key!=='waist'&&!items.length){const b=document.createElement('button');b.textContent='启用'+label;b.onclick=()=>{$('sealDialog').close();app.showSeal(key)};section.append(b)}menu.append(section)}}
new MutationObserver(()=>{if($('sealDialog').open)sealMenu()}).observe($('sealDialog'),{attributes:true,attributeFilter:['open']});sealMenu();
$('addSeal').hidden=true;$('extraSealDialog').hidden=true;
const inspector=$('sealInspector');const rotate=document.createElement('label');rotate.innerHTML='旋转 °<input id="selectedSealAngle" type="number" min="-180" max="180" value="0">';inspector.append(rotate);$('selectedSealAngle').onchange=()=>{const key=app.selectedSealKey();if(key)app.editSeal(key,{angle:Math.max(-180,Math.min(180,+$('selectedSealAngle').value||0))})};
const color=document.createElement('label');color.innerHTML='印色<input id="selectedSealColor" type="color" value="#b62118">';inspector.append(color);$('selectedSealColor').onchange=()=>{const key=app.selectedSealKey();if(key)app.editSeal(key,{config:{color:$('selectedSealColor').value}})};
const copy=document.createElement('button');copy.id='copyCurrentSeal39';copy.textContent='复制此印';copy.onclick=app.copySeal;inspector.append(copy);
// Homepage calendar is always visible, independent of the quote strip.
const cal=$('homeMoments');$('continueWriting').before(cal);function remind(){const e=Moments.upcoming(366)[0];cal.textContent=e?(e.inDays?e.inDays+'天后 · ':'今天 · ')+e.title:'设置纪念日'}remind();new MutationObserver(remind).observe($('momentReminder'),{childList:true,subtree:true});
const brand=document.createElement('canvas');brand.className='brandPen39';brand.width=brand.height=100;$('annotationHome').querySelector('h1').prepend(brand);function paintLogo(){brand.getContext('2d').clearRect(0,0,100,100);brand.getContext('2d').drawImage($('appLogo'),0,0,100,100)}paintLogo();document.fonts.ready.then(paintLogo);document.fonts.addEventListener('loadingdone',paintLogo);
// New defaults only for a new or untouched old default sheet; existing custom stamps survive.
app.updatePosition();window.Revision39={ready:true,syncLock:()=>{syncLock();syncScope()}};})();
