(function init100(){
 if(!window.Revision97?.ready){setTimeout(init100,60);return}
 const A=AnnotationApp,$=id=>document.getElementById(id),board=$('board');
 const hint=document.createElement('aside');hint.id='writingHint100';hint.innerHTML='<b>双指操作</b><span>双指自由拖动纸张</span><span>双击进入全屏预览</span>';board.append(hint);
 let touched=false,lastMode='';function sync(){const mode=document.body.classList.contains('home-open')?'home':A.isOverview55()?'preview':'writer';if(mode!==lastMode){touched=false;lastMode=mode;hint.innerHTML=mode==='preview'?'<b>单指操作</b><span>双击定位书写</span><span>上滑全屏换色</span><span>左右滑动换框</span><span>下滑退出全屏</span><span>三击拓展纸张</span>':'<b>双指操作</b><span>双指自由拖动纸张</span><span>双击进入全屏预览</span>'}hint.hidden=mode==='home'||touched;}new MutationObserver(sync).observe(document.body,{attributes:true,attributeFilter:['class']});
 document.addEventListener('pointerdown',()=>{touched=true;hint.hidden=true},{capture:true});document.addEventListener('preview-painted94',sync);$('fitView').addEventListener('click',()=>requestAnimationFrame(sync));sync();
 const panel=document.createElement('section');panel.id='paperPen100';panel.hidden=true;panel.innerHTML='<header>纸笔尺寸 <button type="button" aria-label="关闭纸笔尺寸">×</button></header>';panel.querySelector('button').onclick=()=>panel.hidden=true;document.body.append(panel);
 for(const [id,title,values]of [['sizeNumber','笔径',[5,10,15,20,30,60,120]],['zoom','纸面',[50,100,150,200,300,400,500]],['inkOpacity38','不透明度',[15,25,50,75,100]]]){const source=$(id),row=document.createElement('label'),name=document.createElement('span'),range=document.createElement('input'),read=document.createElement('output'),quick=document.createElement('div');name.textContent=title;range.type='range';range.dataset.stepper63='yes';range.min=id==='sizeNumber'?1:source.min||25;range.max=source.max||1000;range.step=source.step||1;range.value=source.value;range.setAttribute('aria-label',title);read.textContent=range.value+(id!=='sizeNumber'?'%':'');range.oninput=()=>{source.value=range.value;source.dispatchEvent(new Event(id==='sizeNumber'?'change':'input',{bubbles:true}));read.textContent=range.value+(id!=='sizeNumber'?'%':'')};for(const value of values){const b=document.createElement('button');b.type='button';b.textContent=value+(id!=='sizeNumber'?'%':'');b.onclick=()=>{range.value=value;range.oninput()};quick.append(b)}row.append(name,range,read,quick);panel.append(row);row.dataset.source=id;}
 document.addEventListener('writing-pinch100',()=>{for(const row of panel.querySelectorAll('[data-source]')){const source=$(row.dataset.source);row.querySelector('input').value=source.value;row.querySelector('output').textContent=source.value+(row.dataset.source==='zoom'?'%':'')}panel.hidden=false});
 function sliders(root){for(const field of root.querySelectorAll('input[type=number],input[type=range]')){if(field.closest('#paperPen100')||field.dataset.slider100||field.hidden)continue;field.dataset.slider100='yes';const isNumber=field.type==='number',value=+field.value||0;if(isNumber){field.type='range';if(!field.min)field.min='0';if(!field.max)field.max=String(Math.max(100,value*4));if(!field.step)field.step='1';field.value=String(value);field.addEventListener('input',()=>field.dispatchEvent(new Event('change',{bubbles:true})))}const min=+field.min,max=+field.max,step=+field.step||1;if(!Number.isFinite(max)||max<=min)continue;const options=document.createElement('span');options.className='rangePoints100';const out=document.createElement('output');out.textContent=field.value;options.append(out);const common=field.id==='zoom'?[50,100,200,400,800]:/size/i.test(field.id)?[30,60,100,200,500]:null;const magnitude=Math.pow(10,Math.max(0,Math.floor(Math.log10(max-min))-1));const vals=common?common.filter(n=>n>=min&&n<=max):[.1,.3,.6,.9].map(f=>Math.min(max,Math.max(min,Math.round(Math.round((min+(max-min)*f)/magnitude)*magnitude/step)*step)));for(const n of vals){const b=document.createElement('button');b.type='button';b.textContent=String(Number(n.toFixed(2)));b.onclick=()=>{field.value=n;field.dispatchEvent(new Event('input',{bubbles:true}));field.dispatchEvent(new Event('change',{bubbles:true}))};options.append(b)}field.after(options);field.addEventListener('input',()=>out.textContent=field.value)}}
 sliders(document);new MutationObserver(records=>{for(const record of records)for(const node of record.addedNodes)if(node.nodeType===1&&!node.matches('.rangePoints100'))sliders(node)}).observe(document.body,{childList:true,subtree:true});
 const auto=$('topAuto');if(auto){auto.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M5 3h14v13H5zM9 7h6M9 10h6M12 16v6m-3-3 3 3 3-3"/></svg>';auto.title='自动走纸';auto.setAttribute('aria-label','自动走纸')}
 $('topSize').onclick=()=>{panel.hidden=false};$('zoomQuick79').onclick=()=>{panel.hidden=false};
 const effects=$('previewEffects55'),rail=effects.querySelector('.finalRail54'),note=effects.querySelector('.finalNote54');
 const ratioNote=()=>{const n=+$('ratio').value;note.textContent=n>1.3?'横幅舒展，宜长句与行气贯通。':n<.65?'立轴修长，宜纵势与上下呼应。':n===1?'方笺均衡，疏密相生，四面留白。':'竖幅从容，章法在虚实之间。'};effects.addEventListener('click',e=>{if(e.target.closest('#previewRatio79,.ratioRail80 button'))requestAnimationFrame(ratioNote)});
 effects.addEventListener('click',e=>{const b=e.target.closest('.finalRail54 button');if(!b)return;requestAnimationFrame(()=>{if(!note.textContent||b.closest('#photoPanel62'))return;note.title=note.textContent})});
 window.Revision100={ready:true};
})();
