/* Toolbar and numeric controls: one compact, accessible interaction on every screen. */
(function init(){if(!window.Revision62||!window.Revision47?.ready||!document.getElementById('bigDialog62')){setTimeout(init,45);return}
const $=id=>document.getElementById(id),old=$('bigPaper62'),dialog=$('bigDialog62');old?.remove();
const icon=document.createElement('button');icon.id='extendPaper63';icon.type='button';icon.title='大字 · 加纸加字';icon.setAttribute('aria-label',icon.title);icon.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" width="21" height="21" aria-hidden="true"><rect x="4" y="3" width="12" height="16" rx="1.6"/><path d="M8 8h4m-2-2v4M20 10v11m-4-5h8"/></svg>';icon.onclick=()=>{if(!dialog.open)dialog.showModal()};const actions=$('topActions');actions.querySelector('#annotationHomeButton')?.after(icon);if(!icon.parentElement)actions.prepend(icon);
function mode(){icon.hidden=localStorage.getItem('iinnkk.mode53')!=='single'}document.addEventListener('mode-changed54',mode);document.addEventListener('studio-config50',()=>{if(!icon.isConnected)actions.querySelector('#annotationHomeButton')?.after(icon);mode()});mode();
// The editing tool stays beside the bottom dock; the home header does not need a second copy.
document.querySelector('.annotationBrand .liveEdit53')?.remove();$('zoomReadout')?.remove();
function decorate(input){if(!input||input.dataset.stepper63||input.closest('.stepper63')||input.type!=='number'&&input.type!=='range')return;input.dataset.stepper63='yes';const isRange=input.type==='range';if(isRange&&input.parentElement?.querySelector('input[type=number]'))return;const wrap=document.createElement('span');wrap.className='stepper63';const less=document.createElement('button'),more=document.createElement('button');for(const [b,label] of [[less,'减少'],[more,'增加']]){b.type='button';b.className='stepperButton63';b.textContent=label==='减少'?'−':'+';b.setAttribute('aria-label',label+(input.getAttribute('aria-label')||input.closest('label')?.textContent?.trim().slice(0,15)||'数值'))}
input.before(wrap);if(isRange){const editor=document.createElement('input');editor.type='number';editor.className='rangeNumber63';editor.setAttribute('aria-label',(input.closest('label')?.textContent?.trim().slice(0,20)||'数值')+'精确数值');for(const a of ['min','max','step'])if(input.hasAttribute(a))editor.setAttribute(a,input.getAttribute(a));editor.value=input.value;wrap.append(input,less,editor,more);editor.onchange=()=>{const lo=Number(input.min||0),hi=Number(input.max||100),v=Number(editor.value);if(!Number.isFinite(v)){editor.value=input.value;return}input.value=String(Math.min(hi,Math.max(lo,v)));editor.value=input.value;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))};input.addEventListener('input',()=>editor.value=input.value)}else wrap.append(less,input,more);
function adjust(delta){const step=Number(input.step)||1,min=input.min===''?-Infinity:Number(input.min),max=input.max===''?Infinity:Number(input.max),value=Number(input.value)||0;const v=Math.min(max,Math.max(min,Math.round((value+delta*step)*1000)/1000));input.value=String(v);if(isRange)wrap.querySelector('.rangeNumber63').value=input.value;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))}less.onclick=()=>adjust(-1);more.onclick=()=>adjust(1)}
function scan(root=document){for(const e of root.querySelectorAll?.('input[type=number],input[type=range]')||[])decorate(e)}scan();new MutationObserver(records=>{for(const r of records)for(const node of r.addedNodes)if(node.nodeType===1){if(node.matches?.('input[type=number],input[type=range]'))decorate(node);scan(node)}}).observe(document.body,{childList:true,subtree:true});
})();
