/* Unified paper preview and local copybook library. */
(function init(){
if(!window.FinalStudio54||!window.InkCloud51||!window.Modes53){setTimeout(init,50);return}
const A=AnnotationApp,U=InkStudio50,$=id=>document.getElementById(id),E=U.E;
const readout=$('zoomReadout');readout.hidden=true;
for(const [id,label,dialog,control] of [['statusZoom55','缩放','paperDialog','zoom'],['statusSize55','笔径','brushDialog','sizeNumber']]){const b=E('button',{id,type:'button'},label);b.onclick=()=>{A.openDialog(dialog);requestAnimationFrame(()=>{$(control).scrollIntoView({block:'center'});$(control).focus()})};$('statusDetails42').prepend(b)}
const sync=Status42.sync;Status42.sync=()=>{sync();$('statusZoom55').textContent=$('zoom').value+'%';$('statusSize55').textContent='笔径 '+A.getState().brush.size};Status42.sync();
const edit=[...document.querySelectorAll('.liveEdit53')].at(-1);if(edit){$('dockToggle').before(edit);edit.classList.add('writerEdit55')}
const account=document.querySelector('#topActions .accountName51');if(account)$('topActions').append(account);
const effects=$('previewEffects55'),workspace=$('board').parentElement,icons=$('bottomIcons39');let previousTop=null,previousIcons=null,previewWasOpen=false;
function setIcons(open){icons.hidden=!open;document.body.classList.toggle('dock-icons-collapsed56',!open);iconsToggle.setAttribute('aria-expanded',String(open));iconsToggle.setAttribute('aria-label',open?'收起底部工具':'展开底部工具');iconsToggle.innerHTML=open?'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="m6 15 6-6 6 6"/></svg>':'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="m6 9 6 6 6-6"/></svg>';const companion=$('previewToolsToggle56');if(companion)companion.setAttribute('aria-label',open?'收起底部工具':'展开底部工具')}
const iconsToggle=E('button',{id:'bottomIconsToggle56',type:'button',title:'收起或展开底部工具'});iconsToggle.onclick=()=>setIcons(icons.hidden);$('statusBar42').append(iconsToggle);setIcons(true);
const previewTools=E('button',{id:'previewToolsToggle56',type:'button','aria-label':'展开底部工具',title:'展开底部工具'});previewTools.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M4 6h16M4 12h16M4 18h16"/></svg>';previewTools.onclick=()=>{setIcons(icons.hidden);previewTools.setAttribute('aria-label',icons.hidden?'展开底部工具':'收起底部工具')};effects.querySelector('.previewActions56')?.append(previewTools);
function layoutPreview(){const showing=!effects.hidden&&!document.body.classList.contains('home-open');if(showing!==previewWasOpen){previewWasOpen=showing;if(showing){previousTop=$('topActions').hidden;previousIcons=icons.hidden;if(!previousTop)$('topToggle').click();setIcons(false)}else{if(previousTop===false&&$('topActions').hidden)$('topToggle').click();if(previousIcons!==null)setIcons(!previousIcons);previousTop=previousIcons=null}document.body.classList.toggle('preview-open56',showing)}if(showing){const h=Math.ceil(effects.getBoundingClientRect().height);workspace.style.setProperty('--preview-controls-height56',h+'px')}requestAnimationFrame(()=>window.dispatchEvent(new Event('resize')))}
new MutationObserver(layoutPreview).observe(effects,{attributes:true,attributeFilter:['hidden']});new ResizeObserver(()=>{if(!effects.hidden){const h=Math.ceil(effects.getBoundingClientRect().height);if(workspace.style.getPropertyValue('--preview-controls-height56')!==h+'px')workspace.style.setProperty('--preview-controls-height56',h+'px')}}).observe(effects);
function previewSync(){effects.hidden=!A.isOverview55()||document.body.classList.contains('home-open')}
for(const id of ['resetSettings','topReset'])$(id)?.addEventListener('click',()=>requestAnimationFrame(previewSync));document.addEventListener('mode-changed54',()=>effects.hidden=true);
// The icon row is permanent. The advanced controls stay behind the menu rather than reserving a blank dock.
$('dockState').value='collapsed';$('dockContent').hidden=true;$('bottomDock').classList.add('collapsed');$('dockToggle').hidden=true;
const advanced=E('button',{type:'button',class:'advanced55','aria-label':'更多纸笔设置',title:'更多纸笔设置'});advanced.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.55" stroke-linecap="round"><path d="M4 6h16M4 12h16M4 18h16"/><circle cx="9" cy="6" r="2" fill="#faf6ec"/><circle cx="16" cy="12" r="2" fill="#faf6ec"/><circle cx="11" cy="18" r="2" fill="#faf6ec"/></svg>';advanced.onclick=()=>{A.openDialog('brushDialog')};$('bottomIcons39').append(advanced);
// A short signing stroke starts immediately above the default lower-left seal.
const sign=E('button',{type:'button',id:'signatureShortcut55','aria-label':'落款，笔径十二',title:'落款 · 笔径 12'});sign.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="m5 19 3-1L20 5l-1-1L7 16l-2 3Z"/><path d="M8 20h12M12 13l2 2"/></svg>';sign.onclick=async()=>{if(A.isOverview55())$('fitView').click();const size=$('sizeNumber');size.value='12';size.dispatchEvent(new Event('change',{bubbles:true}));A.focusPoint({x:.42,y:4/(+document.getElementById('ratio').value||.75)-.85});A.toast('落款笔径 12；已定位至落款章上方')};$('bottomIcons39').append(sign);
const number=$('sizeNumber');if(number){const controls=E('span',{class:'sizeStepper55'});for(const [label,delta] of [['−',-1],['+',1]]){const b=E('button',{type:'button','aria-label':delta>0?'增大笔径':'减小笔径'},label);b.onclick=()=>{number.value=String(Math.max(6,Math.min(1000,Math.round(+number.value||35)+delta)));number.dispatchEvent(new Event('change',{bubbles:true}))};controls.append(b)}number.after(controls);$('brushDialog').addEventListener('close',()=>{window.writingLocked=true;Revision39.syncLock()})}
const quote=$('quoteMenu'),quoteButton=$('nextQuote');if(quote&&quoteButton){document.body.append(quote);const place=()=>{const r=quoteButton.getBoundingClientRect();quote.style.top=Math.min(r.bottom+4,innerHeight-quote.offsetHeight-8)+'px';quote.style.left=Math.max(8,Math.min(r.right-quote.offsetWidth,innerWidth-quote.offsetWidth-8))+'px'};new MutationObserver(()=>{if(!quote.hidden)requestAnimationFrame(place)}).observe(quote,{attributes:true,attributeFilter:['hidden']});addEventListener('resize',place)}
// A library record contains original pages, never cropped previews.
let books=[];const library=E('section',{id:'copyLibrary55'});$('copyDialog').querySelector('.dialogBody').prepend(library);
async function load(){books=await DraftStore.get('copy-library55')||[];drawLibrary()}
function drawLibrary(){library.replaceChildren(E('h3',{},'经典字帖集'));for(const book of books.filter(b=>b.published)){const b=E('button',{type:'button'},book.title+' · '+book.pages.length+'页');b.onclick=()=>openBook(book).catch(U.report);library.append(b)}}
async function openBook(book){await A.newBlank54();await CopyAlbums38.openPages55(book);A.showWriter();$('copyDialog').close()}
load().catch(U.report);
document.addEventListener('admin-panel53',e=>{
 const box=E('details',{class:'copyAdmin55'});box.append(E('summary',{},'字帖集管理'));const title=E('input',{placeholder:'字帖名称，如 文徵明·小楷千字文','aria-label':'字帖名称'}),files=E('input',{type:'file',multiple:'',accept:'image/png,image/jpeg,image/webp','aria-label':'按顺序上传整帖或组图'}),list=E('div'),msg=E('p',{role:'status'},'可上传、改名、排序、发布和设为默认。本机发布仅此设备可见；导出字帖包可供其他设备导入。');
 const add=E('button',{type:'button'},'保存新字帖集');add.onclick=async()=>{if(!U.isAdmin)return;if(!title.value.trim()||!files.files.length){msg.textContent='请填写名称并选择字帖图片';return}if(files.files.length>60||[...files.files].some(f=>f.size>20*1024*1024)){msg.textContent='最多60页，每页不超过20MB';return}add.disabled=true;try{const pages=[];for(const f of files.files)pages.push({name:f.name,image:f});books.push({id:crypto.randomUUID(),title:title.value.trim(),published:false,pages});await save();title.value='';files.value='';msg.textContent='已保存，点击发布后出现在临帖字帖集'}catch(err){msg.textContent=err.message}finally{add.disabled=false}};
 const imp=E('input',{type:'file',accept:'.json','aria-label':'导入字帖包'});imp.onchange=async()=>{try{if(!U.isAdmin||!imp.files[0])return;const book=JSON.parse(await imp.files[0].text());if(!book.title||!Array.isArray(book.pages)||book.pages.length>60||book.pages.some(p=>!/^data:image\/(png|jpeg|webp);base64,/.test(p.image)))throw Error('字帖包格式不正确');book.id=crypto.randomUUID();book.published=false;books.push(book);await save()}catch(err){msg.textContent=err.message}};
 box.append(msg,title,files,add,imp,list);e.detail.body.append(box);
 async function save(){if(!U.isAdmin)return;await DraftStore.set('copy-library55',books);draw();drawLibrary()}
 function draw(){list.replaceChildren();books.forEach((book,i)=>{const row=E('article',{class:'copyBook55'}),name=E('input',{value:book.title,'aria-label':'编辑字帖名称'});name.onchange=()=>{book.title=name.value.trim()||book.title;save()};row.append(name,E('small',{},book.pages.length+'页'));for(const [label,fn]of [[book.published?'下架':'发布',async()=>{book.published=!book.published;await save()}],['试临',()=>openBook(book)],['设为默认',async()=>{const page=book.pages[0],src=typeof page.image==='string'?page.image:await dataURL(page.image);await CopyAlbums38.clear();await DraftStore.set('copy-ref53',src);await DraftStore.set('default-reference53',src);await DraftStore.set('mode53:copy',null);msg.textContent='已设为默认字帖'}],['上移',()=>{if(i){books.splice(i-1,0,books.splice(i,1)[0]);save()}}],['下移',()=>{if(i<books.length-1){books.splice(i+1,0,books.splice(i,1)[0]);save()}}],['导出字帖包',async()=>{const pages=[];for(const p of book.pages)pages.push({...p,image:typeof p.image==='string'?p.image:await dataURL(p.image)});U.download(new Blob([JSON.stringify({...book,pages})],{type:'application/json'}),book.title+'.json')}],['删除',async()=>{if(confirm('删除此字帖集？')){books=books.filter(b=>b!==book);await save()}}]])U.button(row,label,fn);list.append(row)})}draw();
});
function dataURL(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('无法读取图片'));r.readAsDataURL(blob)})}
})();
