/* Version 81: compact controls, albums, original works and public gallery. */
(function init(){if(!window.AnnotationApp?.ready||!window.CopyAlbums38||!window.Timeline73||!window.DailyQuotes38){setTimeout(init,90);return}
 const $=id=>document.getElementById(id),app=AnnotationApp;
 function message(e){app.toast(e?.message||String(e))}
 function download(blob,name){const link=document.createElement('a'),url=URL.createObjectURL(blob);link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
 async function picture(source){const img=new Image(),url=typeof source==='string'?source:URL.createObjectURL(source);try{img.src=url;await img.decode();return img}finally{if(typeof source!=='string')setTimeout(()=>URL.revokeObjectURL(url),60000)}}
 const rollDialog=document.createElement('dialog');rollDialog.id='rollPreview82';rollDialog.innerHTML='<header><strong>临帖长卷</strong><button type="button" data-close>×</button></header><div class="rollScroll82"><img alt="横向临帖长卷，可双指缩放并从右向左欣赏"></div><footer><span>从右向左展开 · 双指缩放</span><button type="button" data-download>下载长卷</button></footer>';document.body.append(rollDialog);rollDialog.querySelector('[data-close]').onclick=()=>rollDialog.close();let rollURL='';rollDialog.addEventListener('close',()=>{if(rollURL){URL.revokeObjectURL(rollURL);rollURL=''}});
 async function roll(album,original=false){if(!album?.pages?.length)throw Error('这组原帖没有图片');if(!original){await CopyAlbums38.saveCurrent();if(album===CopyAlbums38.active&&!album.pages[album.index].workIds?.length&&app.getState()?.flow?.strokes?.length)await app.savePage()}const pictures=[];for(const page of album.pages){let source=page.image;if(!original){const id=page.workIds?.at(-1),saved=id&&await DraftStore.get(id);if(!saved?.blob)continue;source=saved.blob}pictures.push(await picture(source))}if(!pictures.length)throw Error('请先临写并保存至少一页');const height=900,gap=12,widths=pictures.map(im=>Math.max(1,Math.round(im.naturalWidth*height/im.naturalHeight))),width=widths.reduce((a,b)=>a+b,0)+gap*(widths.length-1);if(width>30000||width*height>45e6)throw Error('长卷过长，请分组预览');const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');ctx.fillStyle='#f5f0e5';ctx.fillRect(0,0,width,height);let right=width;pictures.forEach((im,i)=>{right-=widths[i];ctx.drawImage(im,right,0,widths[i],height);right-=gap});const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));if(!blob)throw Error('长卷生成失败');if(rollURL)URL.revokeObjectURL(rollURL);rollURL=URL.createObjectURL(blob);const img=rollDialog.querySelector('img'),scroller=rollDialog.querySelector('.rollScroll82');img.src=rollURL;rollDialog.querySelector('strong').textContent=album.title+(original?' · 真迹长卷':' · 临写长卷');rollDialog.querySelector('[data-download]').onclick=()=>download(blob,album.title+(original?'·真迹':'·临写')+'长卷.jpg');if(!rollDialog.open)rollDialog.showModal();await img.decode();scroller.scrollLeft=scroller.scrollWidth;app.toast('已拼合 '+pictures.length+' 页，可先预览再下载')}

 const viewer=$('copyAlbumViewer38');if(viewer){const actions=viewer.querySelector('.musicActions'),one=document.createElement('button'),all=document.createElement('button');one.textContent='下载本页';all.textContent='拼合长卷';actions.append(one,all);const current=()=>CopyAlbums38.viewed;one.onclick=async()=>{try{const album=current();if(!album)throw Error('请先保存临帖本页');if(viewer.dataset.original81){const i=Number(($('albumPage38').textContent.match(/^\d+/)||[])[0])-1;const src=album.pages[i]?.image;if(src instanceof Blob)download(src,album.title+'·原帖第'+(i+1)+'页.jpg');else if(src)window.open(src,'_blank','noopener');return}const i=Number(($('albumPage38').textContent.match(/^\d+/)||[])[0])-1,id=album.pages[i]?.workIds?.at(-1),saved=id&&await DraftStore.get(id);if(!saved?.blob)throw Error('请先保存本页');download(saved.blob,album.title+'·第'+(i+1)+'页.png')}catch(e){message(e)}};all.onclick=()=>{const album=current();roll(album,!!viewer.dataset.original81).catch(message)};viewer.addEventListener('close',()=>{delete viewer.dataset.original81;$('albumEdit38').disabled=false});viewer.querySelector('#albumImage38').style.touchAction='pinch-zoom'}
 const float=$('copyNav80');if(float){const stitch=document.createElement('button');stitch.type='button';stitch.textContent='卷';stitch.title='拼合临帖长卷';stitch.setAttribute('aria-label','拼合所有已保存的临帖页');float.append(stitch);stitch.onclick=()=>roll(CopyAlbums38.active).catch(message)}
 const quick=[...document.querySelectorAll('#writingQuick73 button')].find(x=>x.textContent==='预览');function syncPreview(){if(quick)quick.textContent=app.isOverview55()?'书写':'预览'}$('fitView')?.addEventListener('click',()=>setTimeout(syncPreview,50));new MutationObserver(syncPreview).observe(document.body,{attributes:true,attributeFilter:['class']});syncPreview();
 const bookmark=$('dailyDialog'),head=bookmark?.querySelector('.dialogHead');if(head){const edit=document.createElement('button');edit.type='button';edit.className='bookmarkEdit81';edit.textContent='编辑';edit.onclick=()=>{try{window.Revision62?.openQuoteEditor();bookmark.close()}catch(e){message(e)}};head.append(edit);const sync=()=>edit.hidden=!window.InkStudio50?.isAdmin;document.addEventListener('admin-unlocked53',sync);sync()}
 if(bookmark&&head){const tools=document.createElement('div');tools.className='bookmarkNav81';tools.innerHTML='<button type="button" aria-label="上一条">‹</button><button type="button" aria-label="顺序或随机">顺序</button><button type="button" aria-label="下一条">›</button>';bookmark.append(tools);let random=false;document.addEventListener('bookmark-order82',e=>{random=!!e.detail.random});const rows=()=>DailyQuotes38.all().filter(q=>q.cat===(window.currentQuote?.cat||'poetry'));function move(direction){const list=rows();if(!list.length)return;const key=q=>q.id||q.s+'|'+q.q,id=window.currentQuote&&key(window.currentQuote),at=list.findIndex(q=>key(q)===id);const next=random?Math.floor(Math.random()*list.length):(at+direction+list.length)%list.length;DailyQuotes38.selectId(key(list[next]))}tools.children[0].onclick=()=>move(-1);tools.children[1].onclick=()=>{random=!random;tools.children[1].textContent=random?'随机':'顺序'};tools.children[2].onclick=()=>move(1);head.querySelector('.bookmarkSource79')?.addEventListener('click',()=>{const picker=head.querySelector('.bookmarkPicker79');if(!picker)return;/* The picker is already grouped by country or dynasty and author. */},true)}
 // The download album is selected before the work is archived; names and membership persist together.
 const downloadDialog=$('downloadDialog'),worksDialog=$('worksDialog');if(downloadDialog){const row=document.createElement('label');row.className='downloadAlbum81';row.textContent='存入专辑';const select=document.createElement('select'),newName=document.createElement('input');newName.placeholder='新专辑名称';newName.maxLength=36;row.append(select,newName);downloadDialog.querySelector('.dialogBody')?.append(row);let chosen='';async function albums(){return await DraftStore.get('work-albums81')||{}}async function options(){const data=await albums();select.replaceChildren(new Option('不分类',''),...Object.keys(data).map(x=>new Option(x,x)),new Option('新建专辑…','+'));select.value=chosen&&data[chosen]?chosen:'';newName.hidden=select.value!=='+'}downloadDialog.addEventListener('close',()=>{newName.hidden=true});$('export')?.addEventListener('click',()=>setTimeout(options,10));select.onchange=()=>newName.hidden=select.value!=='+';downloadDialog.querySelector('#generateDownload')?.addEventListener('click',()=>{chosen=select.value==='+'?newName.value.trim():select.value;if(chosen)DraftStore.get('work-albums81').then(data=>DraftStore.set('work-albums81',{...(data||{}),[chosen]:(data||{})[chosen]||[]}))},true);document.addEventListener('work-archived',async e=>{if(!chosen)return;const data=await albums();data[chosen]=[e.detail.id,...(data[chosen]||[]).filter(id=>id!==e.detail.id)];await DraftStore.set('work-albums81',data);chosen='';filterWorks()});let filter;async function filterWorks(){if(!worksDialog?.open)return;const data=await albums();if(!filter){filter=document.createElement('select');filter.className='albumFilter81';filter.setAttribute('aria-label','按专辑筛选我的作品');worksDialog.querySelector('.dialogHead')?.append(filter);filter.onchange=apply}const selected=filter.value;filter.replaceChildren(new Option('全部作品',''),...Object.keys(data).map(x=>new Option(x,x)));filter.value=selected;function apply(){const ids=new Set(data[filter.value]||[]);worksDialog.querySelectorAll('#worksGrid .workCard[data-work-id]').forEach(card=>card.hidden=!!filter.value&&!ids.has(card.dataset.workId))}apply()}worksDialog?.addEventListener('click',()=>setTimeout(filterWorks,60));new MutationObserver(()=>filterWorks()).observe($('worksGrid'),{childList:true})}
 // Small settings appear next to their icon; long dialogs keep their full view.
 const compact=new Set(['toolPopup79','sizeDialog38','brushDialog','paperDialog','sealDialog','musicDialog','mountDialog']);let anchor=null;document.addEventListener('pointerdown',e=>{const b=e.target.closest('button');if(b&&!b.closest('dialog'))anchor=b.getBoundingClientRect()},true);function place(dialog){if(!anchor||!compact.has(dialog.id)||!dialog.open)return;requestAnimationFrame(()=>{const w=Math.min(dialog.offsetWidth,innerWidth-16),h=Math.min(dialog.offsetHeight,innerHeight-16);dialog.style.position='fixed';dialog.style.margin='0';dialog.style.left=Math.max(8,Math.min(innerWidth-w-8,anchor.left+anchor.width/2-w/2))+'px';dialog.style.top=Math.max(8,Math.min(innerHeight-h-8,anchor.bottom+7))+'px'})}new MutationObserver(records=>{for(const r of records)if(r.target instanceof HTMLDialogElement)place(r.target)}).observe(document.body,{subtree:true,attributes:true,attributeFilter:['open']});
 window.Revision81={roll};
})();
