/* One reference controller for the preview rail, main menu and floating panorama. */
(function init129(){
 if(!window.Revision111?.ready||!window.Revision128?.ready||!window.TouchOrder129?.render||!window.ReferenceAnalysis129||!window.ReferenceIO129){setTimeout(init129,80);return}
 const A=AnnotationApp,C=CopyAlbums38,$=id=>document.getElementById(id),T=TouchOrder129;
 const icon=T.icon,paths={close:'M6 6l12 12M18 6L6 18',prev:'M15 5l-7 7 7 7',next:'M9 5l7 7-7 7',target:'M12 2v4M12 18v4M2 12h4M18 12h4M7 7h10v10H7z',fit:'M4 9V4h5M15 4h5v5M20 15v5h-5M9 20H4v-5',upload:'M12 16V3m-4 4 4-4 4 4M4 14v7h16v-7',book:'M4 4h7l1 2 1-2h7v15h-7l-1 2-1-2H4zM12 6v14',edit:'M4 20l1-5L17 3l4 4L9 19z',settings:'M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M10 15v6',image:'M3 4h18v16H3zM3 16l6-6 5 5 3-3 4 4'};
 const E=(tag,text,cls)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e};
 function button(host,title,path,fn){const b=E('button',null,'referenceButton129');b.type='button';b.title=b.ariaLabel=title;b.innerHTML=icon(paths[path]||path)+'<span></span>';b.querySelector('span').textContent=title;b.onclick=async()=>{try{await fn()}catch(e){A.toast(e.message||'操作未完成')}};host.append(b);return b}
 const settings={floating:true,follow:true,auto:false,pause:3.5,rows:7,detail:false,layout:'background',opacity:20};try{Object.assign(settings,JSON.parse(localStorage.getItem('reference.settings129')||'{}'))}catch{}settings.layout='background';settings.view133='full';settings.detail=false;settings.auto=false;settings.pause=Math.max(3.5,Number(settings.pause)||3.5);
 let current={row:0,col:0},profile=null,profileJob=0,advanceTimer=0,previewHost=null,imageURL='',imageGeneration=0,loadedReference=null,pendingReference=null,pendingImage=null,loadedCrop137='',pendingCrop137='',displayCrop137={x:0,y:0,w:1,h:1},manuallySized=false,manuallyMoved140=false,floatSide140='left',zoom=1,pan={x:0,y:0},points=new Map(),gesture=null,lastTap=null,windowDrag=null;
 const floating=E('section',null,'referenceFloat129');floating.hidden=true;floating.innerHTML='<div class="referenceViewport129"><div class="referencePlane129"><img draggable="false" alt="原帖全景"><i class="referenceFocus129" aria-label="当前列"></i><i class="referenceGlyph131" aria-label="当前字米字格"></i></div></div><header><strong>原帖</strong><button data-close aria-label="关闭原帖浮窗">'+icon(paths.close)+'</button></header><footer><button data-full aria-label="全图" title="全图">'+icon(paths.fit)+'</button><button data-columns aria-label="全列" title="全列">'+icon('M4 3h4v18H4zM10 3h4v18h-4zM16 3h4v18h-4z')+'</button><button data-follow aria-label="跟随字位" title="跟随字位">'+icon(paths.target)+'</button><button data-prev aria-label="上一页" title="上一页">'+icon(paths.prev)+'</button><button data-next aria-label="下一页" title="下一页">'+icon(paths.next)+'</button></footer><button data-resize aria-label="调整浮窗尺寸">'+icon('M10 20l10-10M15 20l5-5')+'</button>';document.body.append(floating);
 for(const type of ['pointerdown','pointermove','pointerup','pointercancel','wheel','contextmenu'])floating.addEventListener(type,e=>{e.stopPropagation();if(type==='contextmenu')e.preventDefault()});
 const viewport=floating.querySelector('.referenceViewport129'),plane=floating.querySelector('.referencePlane129'),red=floating.querySelector('.referenceFocus129');let image=floating.querySelector('img');
 function persist(){try{localStorage.setItem('reference.settings129',JSON.stringify(settings))}catch{}A.persist()}
 function sourceCell137(row=current.row,col=current.col){const columns=A.referenceCells128()||[],c=columns[col],g=c?.glyphs?.[Math.min(row,(c?.glyphs?.length||1)-1)],cols=columns.length||+$('columns').value||1,rows=Math.max(1,settings.rows);return{x:Math.max(0,(c?.x??1-(col+.5)/cols)-(c?.w??1/cols)/2),y:Math.max(0,(g?.y??(Math.min(row,rows-1)+.5)/rows)-(g?.h??1/rows)/2),w:c?.w??1/cols,h:g?.h??1/rows}}
 function cell(row=current.row,col=current.col){return ReferenceGeometry133.croppedRect137(sourceCell137(row,col),displayCrop137)}
 function columns137(){return ReferenceGeometry133.croppedColumns137(A.referenceCells128()||[],displayCrop137)}
 function transform(){if(!image.naturalWidth)return;const k=Math.min(viewport.clientWidth/image.naturalWidth,viewport.clientHeight/image.naturalHeight),w=image.naturalWidth*k,h=image.naturalHeight*k;plane.style.width=w+'px';plane.style.height=h+'px';plane.style.transform='translate('+pan.x+'px,'+pan.y+'px) scale('+zoom+')';const c=cell(),box=ReferenceFrames136.column(c,columns137(),current.col,settings.frame135);for(const [key,value]of Object.entries({left:box.x*w+'px',top:box.y*h+'px',width:box.w*w+'px',height:box.h*h+'px'}))red.style.setProperty(key,value,'important');const glyph=floating.querySelector('.referenceGlyph131'),g=ReferenceFrames136.glyph(c,box,image.naturalWidth/image.naturalHeight,settings.glyphFrame136);Object.assign(glyph.style,{left:g.x*w+'px',top:g.y*h+'px',width:g.w*w+'px',height:g.h*h+'px'});glyph.style.setProperty('--handle135',(22/zoom)+'px');glyph.style.borderWidth=(1.6/zoom)+'px';glyph.hidden=!settings.follow;red.style.setProperty('--handle135',(22/zoom)+'px');red.style.borderWidth=(1.6/zoom)+'px';red.hidden=!settings.follow;for(const [key,mode]of [['full','full'],['columns','columns']])floating.querySelector('[data-'+key+']').setAttribute('aria-pressed',String(settings.view133===mode));floating.querySelector('[data-follow]').setAttribute('aria-pressed',String(settings.follow))}
 function edgeHandles136(node,key,base){for(const edge of ['left','right','top','bottom']){const handle=E('b',null,'referenceEdge135 '+edge);handle.dataset.edge135=edge;handle.setAttribute('aria-label','拖动调整红框'+({left:'左边',right:'右边',top:'上边',bottom:'下边'}[edge]));node.append(handle);handle.onpointerdown=e=>{e.preventDefault();e.stopPropagation();const original=base(),a=settings[key]||{},k=Math.min(viewport.clientWidth/image.naturalWidth,viewport.clientHeight/image.naturalHeight),drag={id:e.pointerId,x:e.clientX,y:e.clientY,w:image.naturalWidth*k*zoom,h:image.naturalHeight*k*zoom,box:{x:original.x+(a.x||0),y:original.y+(a.y||0),w:original.w+(a.w||0),h:original.h+(a.h||0)}};handle.setPointerCapture(e.pointerId);handle.onpointermove=ev=>{if(ev.pointerId!==drag.id)return;ev.preventDefault();ev.stopPropagation();const b=ReferenceFrames136.resize(drag.box,edge,(ev.clientX-drag.x)/drag.w,(ev.clientY-drag.y)/drag.h);settings[key]={x:b.x-original.x,y:b.y-original.y,w:b.w-original.w,h:b.h-original.h};transform()};handle.onpointerup=handle.onpointercancel=ev=>{ev.stopPropagation();handle.onpointermove=null;persist()}}}}
 edgeHandles136(red,'frame135',()=>ReferenceFrames136.column(cell(),columns137(),current.col));edgeHandles136(floating.querySelector('.referenceGlyph131'),'glyphFrame136',()=>ReferenceFrames136.glyph(cell(),ReferenceFrames136.column(cell(),columns137(),current.col,settings.frame135),image.naturalWidth/image.naturalHeight));
 function fit(){if(settings.view133==='columns')return columnsView();zoom=1;const k=Math.min(viewport.clientWidth/image.naturalWidth,viewport.clientHeight/image.naturalHeight);pan={x:(viewport.clientWidth-image.naturalWidth*k)/2,y:(viewport.clientHeight-image.naturalHeight*k)/2};transform()}
 function columnsView(){if(!image.naturalWidth)return;const columns=columns137(),c=cell(),k=Math.min(viewport.clientWidth/image.naturalWidth,viewport.clientHeight/image.naturalHeight),w=image.naturalWidth*k,h=image.naturalHeight*k,region=ReferenceGeometry133.threeColumns(columns,current.col,c);zoom=Math.max(1,viewport.clientHeight/h);pan={x:viewport.clientWidth/2-region.center*w*zoom,y:0};transform()}
 function closeup(){settings.view133='columns';manuallySized=false;sizeFloat();columnsView()}
 function sizeFloat(){if(manuallySized||!image.naturalWidth||!image.naturalHeight)return;const area=$('board').getBoundingClientRect(),size=ReferenceIO129.fitWindow(image.naturalWidth,image.naturalHeight,Math.min(288,Math.max(168,area.width*.432)),Math.min(456,Math.max(204,area.height*.6)));if(settings.view133==='columns'){const paper=A.isOverview55()?A.paperFrame107?.():null,visible=ReferenceWindow134.aligned(area,paper),region=ReferenceGeometry133.threeColumns(columns137(),current.col,cell());if(!manuallyMoved140){floating.style.left=(floatSide140==='right'?Math.max(0,innerWidth-Math.max(110,Math.min(innerWidth,visible.height*image.naturalWidth*region.w/image.naturalHeight))):0)+'px';floating.style.top=visible.top+'px'}floating.style.height=visible.height+'px';floating.style.width=Math.max(110,Math.min(innerWidth,visible.height*image.naturalWidth*region.w/image.naturalHeight))+'px'}else{floating.style.width=size.width+'px';floating.style.height=size.height+'px';if(!manuallyMoved140)floating.style.left=(floatSide140==='right'?Math.max(0,innerWidth-size.width):8)+'px'}}
 const referenceVisible143=()=>!document.body.classList.contains('home-open')&&localStorage.getItem('iinnkk.mode53')==='copy';
 async function loadImage(){if(!referenceVisible143()){imageGeneration++;floating.hidden=true;return}const token=++imageGeneration,ref=A.getReference(),crop={...(window.Reference131?.config133.crop||{x:0,y:0,w:1,h:1})},cropKey=JSON.stringify(crop);if(!settings.floating||!ref){floating.hidden=true;return}if(loadedReference!==ref||loadedCrop137!==cropKey){if(pendingReference!==ref||pendingCrop137!==cropKey){pendingReference=ref;pendingCrop137=cropKey;pendingImage=ReferenceIO129.capture(ref,crop).catch(error=>{if(pendingReference===ref&&pendingCrop137===cropKey){pendingReference=null;pendingImage=null}throw error})}let next;try{next=await pendingImage}catch(error){if(token!==imageGeneration)return;throw error}if(token!==imageGeneration||!referenceVisible143()){floating.hidden=true;return}next.alt='原帖全景';next.draggable=false;image.replaceWith(next);image=next;loadedReference=ref;loadedCrop137=cropKey;displayCrop137=crop;current=ReferenceGeometry133.retainCell137(A.referenceCells128()||[],crop,current);manuallySized=false}if(token!==imageGeneration||!referenceVisible143()){floating.hidden=true;return}const album=C.active,page=album?.pages[album.index];floating.querySelector('strong').textContent=page?.name||album?.title||'原帖';floating.hidden=false;sizeFloat();fit();navState()}
 function navState(){const a=C.active;floating.querySelector('[data-prev]').disabled=!a||a.index===0;floating.querySelector('[data-next]').disabled=!a||a.index>=a.pages.length-1}
 async function pageChange(delta){await C.change128(delta);await loadImage();await analyzeCurrent();navState()}
 floating.querySelector('[data-close]').onclick=()=>{settings.floating=false;imageGeneration++;floating.hidden=true;persist();refreshSettings()};floating.querySelector('[data-prev]').onclick=()=>pageChange(-1).catch(e=>A.toast(e.message));floating.querySelector('[data-next]').onclick=()=>pageChange(1).catch(e=>A.toast(e.message));floating.querySelector('[data-full]').onclick=()=>{settings.view133='full';manuallySized=false;floating.style.left='8px';floating.style.top='56px';sizeFloat();fit();persist()};floating.querySelector('[data-columns]').onclick=()=>{settings.view133='columns';settings.follow=true;manuallySized=false;sizeFloat();fit();persist()};floating.querySelector('[data-follow]').onclick=()=>{settings.follow=!settings.follow;if(settings.follow)fit();transform();persist()};
 const center=()=>{const p=[...points.values()];return{x:p.reduce((n,a)=>n+a.x,0)/p.length,y:p.reduce((n,a)=>n+a.y,0)/p.length,d:p.length===2?Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y):0}};
 viewport.onpointerdown=e=>{e.preventDefault();points.set(e.pointerId,{x:e.clientX,y:e.clientY});viewport.setPointerCapture(e.pointerId);gesture={...center(),time:e.timeStamp,start:{x:e.clientX,y:e.clientY},multi:points.size>1,moved:false};if(points.size>1)lastTap=null};
 viewport.onpointermove=e=>{if(!points.has(e.pointerId))return;e.preventDefault();points.set(e.pointerId,{x:e.clientX,y:e.clientY});const c=center(),g=gesture;if(!g)return;const box=viewport.getBoundingClientRect();if(points.size===2&&c.d&&g.d){const factor=Math.max(1,Math.min(20,zoom*c.d/g.d))/zoom;pan={x:c.x-box.left-(g.x-box.left-pan.x)*factor,y:c.y-box.top-(g.y-box.top-pan.y)*factor};zoom*=factor;g.multi=true}else{pan.x+=c.x-g.x;pan.y+=c.y-g.y}if(Math.hypot(c.x-g.start.x,c.y-g.start.y)>5)g.moved=true;gesture={...g,...c};transform()};
 viewport.onpointerup=e=>{if(!points.has(e.pointerId))return;const g=gesture;points.delete(e.pointerId);if(points.size){gesture={...g,...center(),multi:true};return}gesture=null;if(!g?.multi&&!g?.moved&&e.timeStamp-g.time<300){if(lastTap&&e.timeStamp-lastTap.t<340&&Math.hypot(e.clientX-lastTap.x,e.clientY-lastTap.y)<24){lastTap=null;closeup()}else{selectAt(e.clientX,e.clientY);lastTap={t:e.timeStamp,x:e.clientX,y:e.clientY}}}};viewport.onpointercancel=e=>{points.delete(e.pointerId);gesture=null;lastTap=null};viewport.onwheel=e=>{e.preventDefault();zoom=Math.min(20,Math.max(1,zoom*Math.exp(-e.deltaY*.002)));transform()};
 function selectAt(x,y){const box=viewport.getBoundingClientRect(),k=Math.min(viewport.clientWidth/image.naturalWidth,viewport.clientHeight/image.naturalHeight),px=displayCrop137.x+(x-box.left-pan.x)/(image.naturalWidth*k*zoom)*displayCrop137.w,py=displayCrop137.y+(y-box.top-pan.y)/(image.naturalHeight*k*zoom)*displayCrop137.h,columns=A.referenceCells128()||[];const col=columns.length?columns.reduce((best,c,i)=>Math.abs(c.x-px)<Math.abs(columns[best].x-px)?i:best,0):Math.max(0,Math.min(+$('columns').value-1,Math.floor((1-px)*+$('columns').value)));const glyphs=columns[col]?.glyphs||[];const row=glyphs.length?glyphs.reduce((best,g,i)=>Math.abs(g.y-py)<Math.abs(glyphs[best].y-py)?i:best,0):Math.max(0,Math.min(settings.rows-1,Math.floor(py*settings.rows)));setCell(row,col);const source=sourceCell137(),ref=A.getReference(),point=ReferenceGeometry133.sourceToPaper({x:source.x+source.w/2,y:source.y+source.h/2},A.paperBounds133(),ref.naturalWidth||ref.width,ref.naturalHeight||ref.height,window.Reference131?.config133.crop);A.focusPoint47(point.x,point.y);persist()}
 floating.querySelector('header').onpointerdown=e=>{if(e.target.closest('button'))return;e.preventDefault();const box=floating.getBoundingClientRect();windowDrag={id:e.pointerId,x:e.clientX,y:e.clientY,left:floating.offsetLeft,top:floating.offsetTop,resize:false};floating.setPointerCapture(e.pointerId)};
 floating.querySelector('[data-resize]').onpointerdown=e=>{e.preventDefault();e.stopPropagation();windowDrag={id:e.pointerId,x:e.clientX,y:e.clientY,width:floating.offsetWidth,height:floating.offsetHeight,left:floating.getBoundingClientRect().left,top:floating.getBoundingClientRect().top,resize:true};floating.setPointerCapture(e.pointerId)};
 floating.onpointermove=e=>{if(windowDrag?.id!==e.pointerId)return;const g=windowDrag,dx=e.clientX-g.x,dy=e.clientY-g.y;if(g.resize){manuallySized=true;floating.style.width=Math.max(100,Math.min(Math.max(100,innerWidth-g.left),g.width+dx))+'px';floating.style.height=Math.max(100,Math.min(Math.max(100,innerHeight-g.top),g.height+dy))+'px';transform()}else{manuallyMoved140=true;floating.style.left=(g.left+dx)+'px';floating.style.top=(g.top+dy)+'px'}};floating.onpointerup=floating.onpointercancel=()=>windowDrag=null;
 function setCell(row,col,moveWindow140=false){const source=A.referenceCells128()||[],grid=A.writingGrid67();col=Math.max(0,Math.min((source.length||grid.cols)-1,col));row=Math.max(0,Math.min((source[col]?.glyphs?.length||grid.rows)-1,row));const changed140=current.row!==row||current.col!==col;current={row,col};if(moveWindow140&&!manuallyMoved140){floatSide140=col>=(source.length||grid.cols)/2?'right':'left';sizeFloat()}if(!changed140)return;if(settings.follow&&settings.view133==='columns')columnsView();else transform();if(settings.detail)A.refresh();document.dispatchEvent(new CustomEvent('reference-cell129',{detail:current}))}
 function drawBackground(t,b,scale,dock){return window.Reference131?.drawBackground(t,b,scale,dock)||false}
 function refreshSettings(){if(previewHost?.isConnected&&[...$('previewEffects55').querySelectorAll('[aria-current=true]')].some(b=>b.textContent.trim()==='临帖'))renderControls(previewHost);if(copyDialog.open)renderMenu()}
 function inputRow(host,title,type,value,onchange){const l=E('label',null,'referenceField129'),span=E('span',title),input=E('input');input.type=type;if(type==='checkbox')input.checked=!!value;else input.value=value;l.append(span,input);input.onchange=()=>onchange(type==='checkbox'?input.checked:Number(input.value));host.append(l);return input}
 function renderControls(host){if(window.Reference131)return Reference131.renderControls(host);host.replaceChildren()}
 const copyDialog=$('copyDialog'),legacy=E('div',null,'legacyReference129');legacy.hidden=true;const oldBody=copyDialog.querySelector('.dialogBody');legacy.append(...oldBody.childNodes);document.body.append(legacy);copyDialog.querySelector('.settingsTabs')?.remove();copyDialog.querySelector('h2').textContent='临帖 · 原帖与设定';const controls=E('section',null,'referenceControls129'),catalog=E('section',null,'referenceCatalog129');oldBody.append(controls,catalog);let pickerOnly=false;
 function renderMenu(){renderControls(controls);catalog.replaceChildren();const header=E('div',null,'referenceCatalogHead129');header.append(E('h3','选择原帖'));if(InkCloud75.isFounder132)button(header,'名帖管理','settings',openCatalogueManager);catalog.append(header);const list=E('div',null,'referenceCatalogueList129');catalog.append(list);for(const c of Timeline73.chapters.filter(c=>!Timeline73.data129(c).deleted)){const data=Timeline73.data129(c);const b=E('button');b.type='button';b.append(E('strong',data.title),E('small',[data.era||c.era,data.script||c.script,data.pages?.length?data.pages.length+' 页':'待上传'].filter(Boolean).join(' · ')));b.onclick=async()=>{b.disabled=true;try{await Timeline73.openCopy(c);copyDialog.close()}catch(e){A.toast(e.message)}finally{b.disabled=false}};list.append(b)}for(const p of Revision62.getPresets()){const b=E('button',p.title);b.onclick=async()=>{try{await C.openPages55(p);copyDialog.close();await entered()}catch(e){A.toast(e.message)}};list.append(b)}controls.hidden=pickerOnly}
 function openPicker(){pickerOnly=true;renderMenu();A.openDialog('copyDialog')}
 function openSettings(){const tab=[...$('previewEffects55').querySelectorAll('.finalSteps54 button,.finalSteps55 button,button')].find(b=>b.textContent.trim()==='临帖');if(tab){Revision97.setPart('config',false);tab.click()}else{pickerOnly=false;renderMenu();A.openDialog('copyDialog')}}
 copyDialog.addEventListener('toggle',()=>{if(copyDialog.open){pickerOnly=!A.getReference();renderMenu()}});
 const originalUpload=$('upload').onchange;$('upload').onchange=async e=>{await originalUpload.call($('upload'),e);await entered()};
 async function entered(){if(!A.getReference())return;settings.floating=true;settings.follow=true;settings.view133='full';manuallyMoved140=false;floatSide140='left';current={row:0,col:0};persist();const match=C.active?.pages[C.active.index]?.parameters132||{};await A.configure47({preset:match.preset,size:match.size||15,mountKey:'bare',brushPatch:{...ParticleBrush.lineProfile108(match.lineStrength??100),...match.patch,lineStrength108:match.lineStrength??100},values:{zoom:String(match.zoom||500),rows:String(Math.max(settings.rows,...A.referenceCells128().map(c=>c.glyphs?.length||0))),columns:String(A.referenceCells128().length||6),copyLayout111:'background',stationery:'plain',material:'plain',sceneChoice:'none',paperPattern:'none',opacity:String(settings.opacity)}});A.showWriter();if(!A.isOverview55())$('fitView').click();window.Reference131?.entered();openSettings();requestAnimationFrame(()=>{loadImage().then(analyzeCurrent).catch(e=>A.toast(e.message))})}
 async function analyzeCurrent(){if(!referenceVisible143())return;const job=++profileJob,ref=A.getReference();if(!ref)return;const a=C.active,p=a?.pages[a.index];const nextProfile=(p?.analysis129?.version===131?p.analysis129:null)||await ReferenceAnalysis129.analyze(ref,[p?.name,a?.title,p?.filename,p?.image?.name].filter(Boolean).join(' '),A.presets);if(job!==profileJob)return;profile=nextProfile;if(p){p.analysis129=profile;await C.persist129()}refreshSettings()}
 const thumbHost=E('div',null,'referenceThumbs129');$('albumImage38').after(thumbHost);let thumbsURLs=[],thumbAlbum155=null,thumbSources155=[];
 function pagesForPreview(){return C.viewed||C.active}
 function picture(p){if(typeof p.image==='string')return new URL(p.image,location.href).href;const u=URL.createObjectURL(p.image);thumbsURLs.push(u);return u}
 function renderThumbs(){if(!$('copyAlbumViewer38').open){thumbHost.replaceChildren();thumbAlbum155=null;return}const album=pagesForPreview();if(!album)return;const items=CopyPreviewModel161.items(album,true),key=items.map(p=>p.image).join('|');if(album!==thumbAlbum155||key!==thumbSources155.join('|')){thumbHost.replaceChildren();thumbsURLs.forEach(URL.revokeObjectURL);thumbsURLs=[];thumbAlbum155=album;thumbSources155=items.map(p=>p.image);T.render(thumbHost,items,{hideNames:true,name:p=>'第 '+(p.page+1)+' 页 · '+(p.original?'原帖':'临写'),image:picture,open:p=>C.selectViewed161(p.page,p.original)})}thumbHost.querySelectorAll('article').forEach((n,i)=>n.setAttribute('aria-current',String(items[i]?.page===C.index128&&items[i]?.original===C.original161)))}
 new MutationObserver(renderThumbs).observe($('albumImage38'),{attributes:true,attributeFilter:['src']});document.addEventListener('copy-order128',renderThumbs);document.addEventListener('copy-view143',renderThumbs);new MutationObserver(renderThumbs).observe($('copyAlbumViewer38'),{attributes:true,attributeFilter:['open']});
 function openOrder(){const album=C.active;if(!album)return A.toast('请先选择或上传原帖');const d=E('dialog',null,'referenceOrderDialog129'),head=E('header',null,'dialogHead');head.append(E('h2','组图 · 长按拖动排序'));button(head,'关闭','close',()=>d.close());d.append(head);const rows=E('div');d.append(rows);const urls=[];const image=p=>{if(typeof p.image==='string')return new URL(p.image,location.href).href;const u=URL.createObjectURL(p.image);urls.push(u);return u};function draw(){urls.forEach(URL.revokeObjectURL);urls.length=0;T.render(rows,album.pages,{name:p=>p.name||'原帖',image,move:async(from,to)=>{await C.reorder128(from,to,album.id);draw()},open:async(p,i)=>{await C.select128(i);d.close();copyDialog.close();await entered()}})}d.addEventListener('close',()=>{urls.forEach(URL.revokeObjectURL);d.remove()});document.body.append(d);draw();d.showModal()}
 async function openCatalogueManager(){if(!InkCloud75.isFounder132)return;const admin=InkStudio50.isAdmin,d=E('dialog',null,'referenceManager129'),head=E('header',null,'dialogHead');head.append(E('h2','经典名帖 · 统一编排'));button(head,'关闭','close',()=>d.close());if(admin)button(head,'新增名帖','book',()=>{d.close();Timeline73.add129()});d.append(head);if(admin&&!TimelineCloud74.hasToken()){const token=E('input');token.type='password';token.placeholder='GitHub 临时管理令牌（仅本页内存）';d.append(token);button(d,'连接管理','settings',()=>{TimelineCloud74.connect(token.value.trim());token.value='';A.toast('已连接本页管理')})}d.append(E('p',admin?'长按拖动编排顺序，点击维护可修订、上传组图或删除。':'点击名帖选择临写；管理功能供管理员使用。'));const list=E('div');d.append(list);function draw(){const chapters=Timeline73.chapters.filter(c=>!Timeline73.data129(c).deleted);T.render(list,chapters,{name:c=>{const p=Timeline73.data129(c);return [p.era||c.era,p.title].filter(Boolean).join(' · ')},open:c=>admin?(d.close(),Timeline73.edit129(c)):(d.close(),Timeline73.openCopy(c)),move:admin?async(from,to)=>{const ordered=T.move(chapters,from,to).map(c=>c.id);await TimelineCloud74.publishOrder129(ordered);Timeline73.sort129();Timeline73.refresh();draw()}:null,actions:(card,c)=>{if(admin)button(card,'维护','edit',()=>{d.close();Timeline73.edit129(c)})}})}document.body.append(d);draw();d.addEventListener('close',()=>d.remove());d.showModal()}
 async function nextCell(){clearTimeout(advanceTimer);if(A.isDrawing128())return;const grid=A.writingGrid67();let {row,col}=current;if(A.getState().values.followDirection==='horizontal'){if(++col>=grid.cols){col=0;row++}}else if(++row>=grid.rows){row=0;col++}if(row>=grid.rows||col>=grid.cols)return nextPaper();A.focusCell129(row,col);setCell(row,col)}
 async function nextPaper(){clearTimeout(advanceTimer);await C.saveCurrent();await Revision128.saveOnSwitch129();if(C.active&&C.active.index<C.active.pages.length-1)await C.change128(1);else if(C.active)await C.newPaper128();else await A.startSeriesPage119(A.getState());await loadImage();await analyzeCurrent()}
 function syncPaperPoint(p){const ref=A.getReference();if(!ref||!p)return;const at=ReferenceGeometry133.paperToSource(p,A.paperBounds133(),ref.naturalWidth||ref.width,ref.naturalHeight||ref.height,window.Reference131?.config133.crop),columns=A.referenceCells128()||[];if(!columns.length)return;const col=columns.reduce((best,c,i)=>Math.abs(c.x-at.x)<Math.abs(columns[best].x-at.x)?i:best,0),glyphs=columns[col].glyphs||[];const row=glyphs.length?glyphs.reduce((best,g,i)=>Math.abs(g.y-at.y)<Math.abs(glyphs[best].y-at.y)?i:best,0):Math.max(0,Math.min(settings.rows-1,Math.floor(at.y*settings.rows)));setCell(row,col,true)}
 document.addEventListener('copy-cell128',e=>e.detail.point?syncPaperPoint(e.detail.point):setCell(e.detail.row,e.detail.col,true));document.addEventListener('ink-stroke',e=>{if(!C.active||C.paused129||localStorage.getItem('iinnkk.mode53')!=='copy')return;syncPaperPoint(e.detail.points[Math.floor(e.detail.points.length/2)])});$('live').addEventListener('pointerdown',()=>clearTimeout(advanceTimer),true);
 document.addEventListener('reference-crop137',()=>{delete settings.frame135;delete settings.glyphFrame136;loadImage().catch(e=>A.toast(e.message))});document.addEventListener('copy-page128',()=>{current={row:0,col:0};delete settings.frame135;delete settings.glyphFrame136;loadImage().then(analyzeCurrent).catch(e=>A.toast(e.message));navState()});document.addEventListener('mode-changed54',()=>{if(localStorage.getItem('iinnkk.mode53')!=='copy'){floating.hidden=true;clearTimeout(advanceTimer)}});document.addEventListener('cloud-user84',()=>{refreshSettings()});document.addEventListener('timeline-cloud74',()=>{if(copyDialog.open)renderMenu()});window.addEventListener('resize',()=>{sizeFloat();fit()});let overview134=A.isOverview55();function syncColumnHeight134(){if(settings.view133!=='columns'||floating.hidden)return;const next=A.isOverview55();if(next!==overview134){manuallySized=false;overview134=next}sizeFloat();columnsView()}for(const event of ['preview-painted94','ink-view-changed90'])document.addEventListener(event,syncColumnHeight134);new ResizeObserver(syncColumnHeight134).observe($('board'));$('zoom').addEventListener('input',()=>requestAnimationFrame(syncColumnHeight134));
 function syncFloat(){const visible=referenceVisible143();if(!visible){imageGeneration++;profileJob++;floating.hidden=true;return}if(settings.floating&&A.getReference()){if(loadedReference!==A.getReference())loadImage().then(analyzeCurrent).catch(()=>{});else floating.hidden=false}}new MutationObserver(syncFloat).observe(document.body,{attributes:true,attributeFilter:['class']});
 // Remove old visible controls; their hidden input values remain the engine's serialization contract.
 $('copyNav80')?.remove();$('copyEnd38').onclick=null;$('copyEnd38').disabled=true;$('copyTools111').hidden=true;for(const id of ['usePractice','removeRef'])$(id).disabled=true;
 window.Reference129={ready:true,renderPreview:host=>{previewHost=host;renderControls(host)},openSettings,openPicker,drawBackground,entered,cell,setCell,openCatalogueManager,refreshSettings,settings,loadImage,get profile(){return profile}};
 renderMenu();if(A.getReference())loadImage().then(analyzeCurrent).catch(()=>{});
})();
