(function init120(){
 if(!window.Revision119?.ready||!window.Revision100?.ready){setTimeout(init120,50);return}
 const A=AnnotationApp,$=id=>document.getElementById(id),hint=$('writingHint100'),preview=$('previewWatermark90');
 // The first photo-writing page introduces the site; a previously saved page retains its own picture.
 document.addEventListener('mode-ready109',async e=>{if(e.detail?.mode!=='photo'||e.detail?.restored)return;try{const response=await fetch('promo-calligraphy120.webp');if(!response.ok)throw Error('图片不可用');const blob=await response.blob();if(localStorage.getItem('iinnkk.mode53')!=='photo')return;await A.replaceCoverPhoto114([new File([blob],'今日亲笔·推广图.webp',{type:'image/webp'})]);A.persist()}catch(error){A.toast('默认图暂未载入，可点击添加图片')}});
 let anchor=null,frame=0;
 function colorAt(x,y){const paper=$('paper'),r=paper.getBoundingClientRect();try{const cx=Math.max(0,Math.min(paper.width-1,Math.floor((x-r.left)*paper.width/r.width))),cy=Math.max(0,Math.min(paper.height-1,Math.floor((y-r.top)*paper.height/r.height))),p=paper.getContext('2d').getImageData(cx,cy,1,1).data;const luminance=(.2126*p[0]+.7152*p[1]+.0722*p[2]);return luminance<130?'#fff7e3':'#29251f'}catch{const hex=$('papercolor').value,m=hex.match(/^#([0-9a-f]{6})$/i);if(!m)return '#2a2620';const n=parseInt(m[1],16);return ((n>>16)*.2126+((n>>8)&255)*.7152+(n&255)*.0722)<130?'#fff7e3':'#29251f'}}
 function paint(){frame=0;const board=$('board').getBoundingClientRect(),focus=anchor&&!A.isOverview55()?anchor:{clientX:board.left+board.width/2,clientY:board.top+board.height/2},color=colorAt(focus.clientX,focus.clientY),shadow=color==='#fff7e3'?'#000c':'#fff9';for(const el of [hint,preview])if(el){el.style.setProperty('color',color,'important');el.style.setProperty('text-shadow','0 1px 4px '+shadow+',0 0 9px '+shadow,'important')}if(anchor&&!A.isOverview55()&&!hint.hidden){hint.style.setProperty('left',Math.max(100,Math.min(board.width-100,focus.clientX-board.left))+'px','important');hint.style.setProperty('top',Math.max(70,Math.min(board.height-70,focus.clientY-board.top))+'px','important')}}
 const schedule=()=>{if(!frame)frame=requestAnimationFrame(paint)};
 document.addEventListener('writing-position120',e=>{const p=A.paperFrame107(),board=$('board').getBoundingClientRect();anchor={clientX:board.left+p.x+e.detail.x*p.scale,clientY:board.top+p.y+e.detail.y*p.scale};hint.innerHTML='<b>落笔即可开始</b><span>见墨如我 · iinnkk.me</span>';hint.hidden=false;hint.classList.add('located120');schedule()});
 document.addEventListener('pointerdown',e=>{if(e.target.closest('#board')){anchor=null;hint.classList.remove('located120')}},true);
 document.addEventListener('preview-painted94',schedule);document.addEventListener('ink-view-changed90',schedule);document.addEventListener('change',e=>{if(['papercolor','photoMode','paperPattern'].includes(e.target.id))schedule()});new MutationObserver(schedule).observe(document.body,{attributes:true,attributeFilter:['class']});schedule();
 window.Revision120={ready:true};
})();
