(function init(){if(!window.Revision93?.ready||!window.Palettes94||!window.HeritagePalettes102||!window.Timeline73){setTimeout(init,60);return}
const $=id=>document.getElementById(id),A=AnnotationApp;
let templateFollows=true;try{templateFollows=localStorage.getItem('template-follows124')!=='false'}catch{}
function syncTemplateToggle(){const b=$('previewRandom79');if(!b)return;b.innerHTML='<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true">'+(templateFollows?'<path d="M3 6h3l12 12h3M3 18h3L18 6h3M18 3l3 3-3 3M18 15l3 3-3 3"/>':'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>')+'</svg><span>'+(templateFollows?'随变':'不变')+'</span>';b.setAttribute('aria-pressed',String(templateFollows));b.title=b.getAttribute('aria-label')||'';b.setAttribute('aria-label',(templateFollows?'随变：模板随佳句和上下滑动变化，点击固定':'不变：保持当前模板，点击恢复随变'));b.title=b.getAttribute('aria-label');}
function toggleTemplateFollow(){templateFollows=!templateFollows;try{localStorage.setItem('template-follows124',String(templateFollows))}catch{}syncTemplateToggle();A.toast(templateFollows?'随变：模板跟随佳句与滑动变化':'不变：已固定当前模板');}

const intro=document.querySelector('#annotationHome .annotationIntro');
if(intro){intro.querySelector('.heroConstellation91')?.remove();const picture=document.createElement('picture');picture.className='heroPicture94';const source=document.createElement('source');source.media='(max-width:600px)';source.srcset='hero-mobile94.webp';const img=document.createElement('img');img.src='hero-wide94.webp';img.alt='以李斯、王羲之、颜真卿、苏轼、黄庭坚、达芬奇、手岛右卿、伊本·穆格莱为灵感的AI群像';img.fetchPriority='high';img.decoding='async';picture.append(source,img);intro.classList.add('heroPending101');const reveal=()=>img.decode().catch(()=>{}).then(()=>intro.classList.remove('heroPending101'));img.addEventListener('load',reveal);img.addEventListener('error',()=>intro.classList.add('heroFailed101'));intro.prepend(picture);if(img.complete&&img.naturalWidth)reveal();
 const people=[['秦','李斯','峄山刻石'],['东晋','王羲之','兰亭序'],['唐','颜真卿','祭侄文稿'],['北宋','苏轼','寒食帖'],['北宋','黄庭坚','砥柱铭'],['意大利','达芬奇','阿伦德尔手稿'],['日本','手岛右卿','崩坏'],['阿拔斯王朝','伊本·穆格莱','古兰经抄写']];const labels=document.createElement('div');labels.className='heroPeople94';labels.setAttribute('aria-label','书法人物与代表作品');people.forEach(([era,name,work],i)=>{const label=document.createElement('div');label.className='heroPerson94';label.style.setProperty('--hero-x94',(25+(i+.94)*75/8)+'%');label.style.setProperty('--mobile-x94',((i%4)*25+24)+'%');label.style.setProperty('--mobile-y94',(i<4?42:75)+'%');for(const [tag,text]of [['span',era],['b',name],['span',work]]){const node=document.createElement(tag);node.textContent=text;label.append(node)}label.title=era+' · '+name+' · '+work;if(i===7)label.title+='；关联其比例书法贡献，不宣称现存抄本为本人亲笔';labels.append(label)});intro.append(labels)}
const logo=$('annotationHomeButton'),left=$('writerLeft90');if(logo&&left){left.prepend(logo);logo.onclick=()=>{document.getElementById('dailyDialog')?.close();AnnotationHome.show();toTop()}}
function toTop(){const home=$('annotationHome');if(document.body.classList.contains('home-open')&&home){home.style.scrollSnapType='none';home.scrollTo({top:0,behavior:'instant'})}window.scrollTo({top:0,behavior:'instant'})}
document.addEventListener('dblclick',e=>{if(e.target.closest('.annotationBrand,.annotationIntro,.topStrip,#homeTop76')){if(e.target.closest('input,textarea,select'))return;toTop()}},true);
let lastTop=0;document.addEventListener('pointerup',e=>{if(e.pointerType!=='touch'||!document.body.classList.contains('home-open')||e.clientY>65||e.target.closest('button,input,select,a'))return;const now=performance.now();if(now-lastTop<340){toTop();lastTop=0}else lastTop=now},true);
const account=$('cloudAccount75'),head=account?.querySelector('.cloud75-head');if(head){head.querySelector('button')?.classList.add('accountClose94')}
const note=document.createElement('aside');note.id='paletteNote94';note.className='paletteNote94';note.hidden=true;note.setAttribute('role','status');note.setAttribute('aria-live','polite');$('board').append(note);let current=null,framePending=false;
const colours=HeritagePalettes102.map(p=>{p={...p};if(Revision93.contrast(p.paper,p.ink)<4.5)p.ink=Revision93.contrast(p.paper,'#000000')>Revision93.contrast(p.paper,'#ffffff')?'#000000':'#ffffff';return p});let last='';
function palette(){const q=window.currentQuote||{},era=q.dynasty||q.era||'',priority=colours.filter(p=>p.family==='中国'&&q.country==='中国'||['唐','宋'].includes(p.family)&&era.includes(p.family)||q.country&&(p.family===q.country||p.countries?.includes(q.country)));const leading=colours.filter(p=>['中国','意大利','法国','德国','西班牙','印度','墨西哥','英国','俄罗斯','伊朗'].includes(p.country));const pool=(priority.length&&Math.random()<.5?priority:Math.random()<.6?leading:colours).filter(p=>p.id!==last);const p={...pool[Math.floor(Math.random()*pool.length)]};if(p.countries?.length>1){const country=p.countries.includes(q.country)?q.country:p.countries[Math.floor(Math.random()*p.countries.length)];if(country!==p.country){p.country=p.family=country;p.name=country+'·'+p.moodTitle;p.idea=country+'·'+p.referencePlace+'：'+p.referenceDescription}}last=p.id;const seals=['#b62118','#d56528','#bd8d19','#66509c','#2867b1','#267567','#91245a','#173d45','#fffaf0','#e5c26d'];p.seal=seals[Math.floor(Math.random()*seals.length)];if(p.seal===A.getState().values.headColor)p.seal=seals[(seals.indexOf(p.seal)+1)%seals.length];if(Math.random()<.35){const old=p.paper;p.paper=p.ink;p.ink=old;p.idea=String(p.idea||'').replace(/[。\s]+$/,'')+'；深纸映浅墨。'}const candidates=seals.filter(c=>Revision93.contrast(p.paper,c)>=2.5&&c!==A.getState().values.headColor);p.seal=candidates[Math.floor(Math.random()*candidates.length)]||'#b62118';return p}
function positionNote(){framePending=false;note.hidden=true;}
function scheduleNote(){if(!framePending){framePending=true;requestAnimationFrame(positionNote)}}
function designIdea104(base){return String(base||'').replace(/\s*装裱：.*$/,'').replace(/，[^，。]*映衬墨纸与印色。$/,'').trim()}
function apply(p){const state=A.getState(),mat=Mounting.presets[state.mountKey]?.mat||'#eee9dc';p={...p,idea:designIdea104(p.idea),titleColor:Revision93.contrast(mat,p.ink)>=3?p.ink:Revision93.contrast(mat,'#805437')>=3?'#805437':'#e7bc86'};if(window.Revision110)p.idea=Revision110.designIdea(p,{values:{papercolor:p.paper,headColor:p.seal,tailColor:p.seal},brush:{color:p.ink}});current=p;A.setPaletteCredit96?.(p);note.replaceChildren();const title=document.createElement('strong'),idea=document.createElement('small');title.textContent=p.name;idea.textContent=p.idea;note.append(title,idea);Revision88.applyPalette(p);scheduleNote()}
$('previewRandom79').onclick=toggleTemplateFollow;syncTemplateToggle();$('previewReset73').addEventListener('click',()=>{current=null;A.setPaletteCredit96?.(null);note.hidden=true});document.addEventListener('quote-changed',()=>{if(templateFollows)apply(palette())});document.addEventListener('preview-painted94',scheduleNote);addEventListener('resize',scheduleNote);new ResizeObserver(scheduleNote).observe($('board'));document.addEventListener('change',e=>{if(['color','papercolor','headColor','freeInk','freePaper'].includes(e.target.id)){scheduleNote()}});

Revision93.palette=palette;window.Revision94={ready:true,syncTemplateToggle,get templateFollows(){return templateFollows},designIdea104,palettes:colours,palette,apply,toTop,get current(){return current}};
})();
