(function init(){if(!window.Revision90?.ready||!window.InkCloud75){setTimeout(init,70);return}
const $=id=>document.getElementById(id),E=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e},C=InkCloud75;
const button=(host,text,fn)=>{const b=E('button',text);b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn()}catch(e){if(e.name!=='AbortError')AnnotationApp.toast(e.message||'分享准备失败')}finally{b.disabled=false}};host.append(b);return b};
const publicURL=id=>{const url=new URL(location.origin+location.pathname);if(id)url.searchParams.set('work',id);return url.href};
async function source(work){if(work.blob)return work.blob;const {data,error}=await C.client.storage.from('ink-works').createSignedUrl(work.image_path,3600);if(error)throw error;const response=await fetch(data.signedUrl);if(!response.ok)throw Error('作品图片暂时无法读取');return response.blob()}
async function open(work,target){const blob=await source(work),image=await createImageBitmap(blob),canvas=document.createElement('canvas');canvas.width=1080;canvas.height=target==='小红书贴图'?1440:target==='微信贴图'?1080:1440;const ctx=canvas.getContext('2d');ctx.fillStyle='#f5f5ef';ctx.fillRect(0,0,canvas.width,canvas.height);const footer=target==='微信贴图'?150:250,pad=48,scale=Math.min((canvas.width-pad*2)/image.width,(canvas.height-footer-pad*2)/image.height);ctx.drawImage(image,(canvas.width-image.width*scale)/2,pad+(canvas.height-footer-pad*2-image.height*scale)/2,image.width*scale,image.height*scale);image.close();ctx.fillStyle='#223c38';ctx.font='32px system-ui';ctx.fillText(String(work.title||'我的亲笔').slice(0,26),pad,canvas.height-footer+42,740);ctx.font='24px system-ui';ctx.fillText(work.published?'扫码欣赏原作 · 点赞 · 评论 · 留下你的亲笔':'今日亲笔 · iinnkk.me · 来写一幅自己的真迹',pad,canvas.height-65,750);const url=publicURL(work.published?work.id:null);if(window.InkQR47){const qr=document.createElement('canvas');await InkQR47.toCanvas(qr,url,{width:150,margin:1,errorCorrectionLevel:'M'});ctx.drawImage(qr,canvas.width-198,canvas.height-198,150,150)}const output=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));const file=new File([output],'今日亲笔-'+target+'.png',{type:'image/png'});
const dialog=E('dialog');dialog.className='cloud75-dialog sharePanel93';const head=E('div');head.className='cloud75-head';head.append(E('strong',target));button(head,'关闭',()=>dialog.close());dialog.append(head);const preview=E('img');preview.src=URL.createObjectURL(output);preview.alt=target+'分享贴图';dialog.append(preview);dialog.append(E('p',target==='微信朋友圈'?'微信内请点右上角“…”分享到朋友圈；其他浏览器可以打开系统分享菜单，或保存这张图后到微信发布。':target==='小红书贴图'?'已准备3:4贴图。保存后打开小红书，点“＋”选择这张图，添加文案再发布。':'已准备方形微信贴图。保存后可在微信聊天或朋友圈选图发送。'));dialog.append(E('p',work.published?'二维码直达这幅公开作品，访客可点赞、评论并注册。':'这幅作品仍为私藏，二维码只打开网站，不公开原作。需要原作互动请先在作品页点“发布”。'));const feedback=E('p');feedback.setAttribute('role','status');dialog.append(feedback);const actions=E('div');actions.className='shareTools93';dialog.append(actions);button(actions,'系统分享',async()=>{if(!navigator.share){feedback.textContent='此浏览器不支持系统分享，请使用保存贴图和复制链接。';return}if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:work.title||'今日亲笔',text:'见墨如我',url});else await navigator.share({title:work.title||'今日亲笔',url})});button(actions,'保存贴图',()=>{const a=E('a');a.href=preview.src;a.download=file.name;a.click();feedback.textContent='已请求保存；微信内如未下载，可长按贴图保存到相册。'});button(actions,'复制链接',async()=>{try{await navigator.clipboard.writeText(url);feedback.textContent='链接已复制'}catch{const field=E('input');field.value=url;field.readOnly=true;dialog.append(field);field.select();feedback.textContent='请长按选中的链接复制'}});document.body.append(dialog);dialog.addEventListener('close',()=>{URL.revokeObjectURL(preview.src);dialog.remove()},{once:true});dialog.showModal();if(target==='微信朋友圈'&&work.published)configureWechat(work,url).catch(()=>{feedback.textContent='微信自定义分享暂未开通，可保存贴图或从右上角菜单分享链接。'});
}
async function configureWechat(work,link){const endpoint=window.IINNKK_SUPABASE.wechatShareEndpoint;if(!endpoint||!/MicroMessenger/i.test(navigator.userAgent))return;const requestURL=location.href.split('#')[0];const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:requestURL})});if(!r.ok)throw Error('微信分享签名尚未开通');const config=await r.json();if(!window.wx)await new Promise((resolve,reject)=>{const s=E('script');s.src='https://res.wx.qq.com/open/js/jweixin-1.6.0.js';s.onload=resolve;s.onerror=reject;document.head.append(s)});await new Promise((resolve,reject)=>{wx.ready(resolve);wx.error(reject);wx.config({...config,jsApiList:['updateAppMessageShareData','updateTimelineShareData']})});const image=await C.client.storage.from('ink-works').createSignedUrl(work.image_path,3600);wx.updateAppMessageShareData({title:work.title||'今日亲笔',desc:'欣赏原作、点赞评论，也来写下你的亲笔',link,imgUrl:image.data?.signedUrl||''});wx.updateTimelineShareData({title:work.title||'今日亲笔',link,imgUrl:image.data?.signedUrl||''})}
function attach(){for(const card of document.querySelectorAll('#worksGrid .workCard[data-work-id]')){if(card.querySelector('.shareTools93'))continue;const tools=E('div');tools.className='shareTools93';for(const target of ['微信朋友圈','微信贴图','小红书贴图'])button(tools,target,async()=>{const local=await DraftStore.get(card.dataset.workId);if(!local?.blob)throw Error('本机作品暂时无法读取');let cloud=null;if(C.user){const {data}=await C.client.from('ink_works').select('id,title,image_path,published').eq('owner',C.user.id).eq('local_id',C.cloudLocalId(local.id)).maybeSingle();cloud=data}await open({...local,...cloud,blob:local.blob},target)});card.append(tools)}}
const grid=$('worksGrid');if(grid){new MutationObserver(attach).observe(grid,{childList:true,subtree:true});attach()}
window.Share93={open,publicURL};const id=new URLSearchParams(location.search).get('work');if(id&&/^[0-9a-f-]{36}$/i.test(id)){C.client.from('ink_works').select('id,title,owner,local_id,image_path,published,updated_at').eq('id',id).eq('published',true).maybeSingle().then(({data,error})=>{if(error||!data){AnnotationApp.toast('这幅作品未公开或已下架');return}C.openWork(data).catch(e=>AnnotationApp.toast(e.message))})}
})();
