/* Local-first studio. Configuration is device-local, never an online identity. */
window.InkLocalMode50=true;
(function(){
'use strict';
const KEY='iinnkk.studio.v1',AUTH='iinnkk.studio.admin.v1';
const copy=x=>JSON.parse(JSON.stringify(x)),clamp=(x,a,b)=>Math.max(a,Math.min(b,Number(x)||a));
const defaults={version:1,brand:{name:'今日亲笔',slogan:'亲笔手书，见墨如我',color:'#34382e',size:28},integrations:{ai:'',model:'',protocol:'responses',webhook:''},nav:[
 {id:'single',title:'单字',layout:'single',format:'square',direction:'vertical',rows:1,columns:1,size:400,zoom:100,preset:'ouyang',ruling:'mi',pattern:'dragon',material:'plain',paper:'#f5f1e6',ink:'#050505',dry:.14,dynamics:.6,opacity:1,text:'',advanced:{}},
 {id:'copy',title:'临帖',layout:'free',format:'letter',direction:'vertical',rows:10,columns:6,size:18,zoom:300,preset:'zhang',ruling:'hui',pattern:'dragon',material:'plain',paper:'#f5f1e6',ink:'#050505',dry:.4,dynamics:.9,opacity:1,text:'',advanced:{}},
 {id:'letter',title:'创作',layout:'free',format:'letter',direction:'vertical',rows:8,columns:6,size:35,zoom:200,preset:'zhang',ruling:'vertical',pattern:'dragon',material:'plain',paper:'#f5f1e6',ink:'#050505',dry:.4,dynamics:.9,opacity:1,text:'',advanced:{}}
 ]};
const formats={square:['斗方',1,'vermillion'],letter:['书信 · 3:4',.75,'letter'],couplet:['对联',.544444,'vermillion'],horizontal:['横幅',1.85567,'vermillion'],middle:['中堂',.538889,'scroll'],plaque:['匾额',3,'plaque'],postcard:['明信片',.75,'postcard'],fan:['扇面',1.8,'studioFan']};
const E=(tag,attrs={},text)=>{const e=document.createElement(tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,String(v));if(text!==undefined)e.textContent=text;return e};
function normalize(raw){
 if(!raw||raw.version!==1||!Array.isArray(raw.nav)||raw.nav.length>24)throw Error('配置格式不正确：最多 24 个入口');
 const c=copy(defaults),ids=new Set();
 c.nav=raw.nav.map((n,i)=>{const d={...copy(defaults.nav[1]),...n};d.id=String(n.id||'nav-'+i).replace(/[^\w-]/g,'').slice(0,60)||'nav-'+i;if(ids.has(d.id))throw Error('入口编号重复');ids.add(d.id);d.title=String(n.title||'新入口').slice(0,16);d.text=String(n.text||'').slice(0,20000);d.format=formats[d.format]?d.format:'letter';d.layout=['single','combination','poem','free'].includes(d.layout)?d.layout:'free';d.direction=d.direction==='horizontal'?'horizontal':'vertical';d.rows=Math.round(clamp(d.rows,1,30));d.columns=Math.round(clamp(d.columns,1,30));d.size=clamp(d.size,1,1000);d.zoom=clamp(d.zoom,50,800);d.dry=clamp(d.dry,0,1);d.dynamics=clamp(d.dynamics,0,1);d.opacity=clamp(d.opacity,.01,1);for(const k of ['paper','ink'])if(!/^#[a-f0-9]{6}$/i.test(d[k]))d[k]=defaults.nav[1][k];d.advanced=n.advanced&&typeof n.advanced==='object'?n.advanced:{};return d;});
 for(const k of ['name','slogan'])c.brand[k]=String(raw.brand?.[k]||c.brand[k]).slice(0,80);c.brand.size=clamp(raw.brand?.size||28,18,44);if(/^#[a-f0-9]{6}$/i.test(raw.brand?.color))c.brand.color=raw.brand.color;
 for(const k of ['ai','model','webhook'])c.integrations[k]=String(raw.integrations?.[k]||'').slice(0,500);c.integrations.protocol=raw.integrations?.protocol==='chat'?'chat':'responses';
 return c;
}
let config=copy(defaults),loadError='';try{const raw=localStorage.getItem(KEY);if(raw)config=normalize(JSON.parse(raw));if(!localStorage.getItem('iinnkk.nav54')){const single=config.nav.find(n=>n.id==='single'),copyMode=config.nav.find(n=>n.id==='copy'),creation=config.nav.find(n=>n.id==='letter');if(single&&copyMode&&creation){creation.title='创作';creation.zoom=200;creation.size=35;config.nav=[single,copyMode,creation,...config.nav.filter(n=>!['single','copy','letter'].includes(n.id))];localStorage.setItem(KEY,JSON.stringify(config))}localStorage.setItem('iinnkk.nav54','1')}}catch{loadError='本机配置无法读取，暂用默认入口；原数据未覆盖。'}
let app,unlocked=!!localStorage.getItem(AUTH)&&localStorage.getItem('iinnkk.remember55')==='yes',admin,selected=config.nav[0]?.id,status,applying=false,managementParent53=null;
function save(next=config){const valid=normalize(next);try{localStorage.setItem(KEY,JSON.stringify(valid))}catch{throw Error('本机存储已满或被禁用，修改未保存；请先导出配置。')}if(next!==config)config=valid;else{config.nav.forEach((n,i)=>Object.assign(n,valid.nav[i]));config.brand=valid.brand;config.integrations=valid.integrations;}renderNav();applyBrand();if(status)status.textContent='已保存到此设备 · '+new Date().toLocaleTimeString();document.dispatchEvent(new Event('studio-config50'));}
function download(blob,name){const a=E('a',{href:URL.createObjectURL(blob),download:name});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),60000)}
function safeURL(value){const u=new URL(value,location.href);if(!['https:','http:'].includes(u.protocol)||u.username||u.password||(u.protocol==='http:'&&!['localhost','127.0.0.1'].includes(u.hostname)))throw Error('接口请使用 HTTPS 完整地址');if(u.hostname==='api.openai.com')throw Error('请填写代理地址，不要把 OpenAI 密钥放入前端');return u.href;}
function applyBrand(){const h=document.querySelector('.annotationBrand h1');if(h){const logo=h.querySelector('img,svg,canvas');h.textContent=config.brand.name;if(logo)h.prepend(logo);h.style.fontSize=config.brand.size+'px';h.style.color=config.brand.color}const s=document.querySelector('.annotationBrand p');if(s)s.textContent=config.brand.slogan;document.title=config.brand.name+' · '+config.brand.slogan;}
function renderNav(){const nav=document.getElementById('homeQuick47');if(!nav)return;nav.replaceChildren();nav.style.gridTemplateColumns=`repeat(${Math.min(3,Math.max(1,config.nav.length))},minmax(0,1fr))`;for(const n of config.nav){const b=E('button',{type:'button','data-preset':n.id,'aria-label':n.title},n.title);b.onclick=()=>applyMode(n).catch(report);nav.append(b)}nav.hidden=!config.nav.length;}
function report(e){app?.toast(e.message||String(e));if(status)status.textContent=e.message||String(e)}
function knownSelect(id,v,fallback){const el=document.getElementById(id);return el?.options&&[...el.options].some(o=>o.value===String(v))?String(v):fallback}
async function applyMode(n,internal=false){
 if(window.Modes53&&!internal)return Modes53.activate(n,()=>applyMode(n,true));
 if(applying)return;applying=true;
 try{const [label,ratio,stationery]=formats[n.format];const allowed=app.settingsSnapshot().values,values={};for(const [k,v]of Object.entries(n.advanced.values||{}))if(k in allowed&&document.getElementById(k)&&typeof v!=='object')values[k]=String(v);
 Object.assign(values,{stationery,ratio:String(ratio),paperExtent:'fixed',sceneChoice:'none',photoMode:n.format==='postcard'?'postcard':'hero2',letterLayout:'custom',followDirection:n.direction,rows:String(n.rows),columns:String(n.columns),ruling:knownSelect('ruling',n.ruling,'none'),showLines:n.ruling==='none'?'no':'yes',papercolor:n.paper,material:knownSelect('material',n.material,'plain'),paperPattern:knownSelect('paperPattern',n.pattern,'none'),zoom:String(n.zoom),inkMode:'assist',guideMode:n.text?'custom38':'off'});
 if(n.layout==='single')Object.assign(values,{rows:'1',columns:'1',ruling:'mi',showLines:'yes',papercolor:'#e4d5b5',zoom:'100'});
 if(n.format==='couplet')Object.assign(values,{columns:'2',followDirection:'vertical'});
 const preset=app.presets[n.preset]?n.preset:'zhang';const patch={};for(const k of ['softness','smoothing','taper','fullness'])if(Number.isFinite(n.advanced.brush?.[k]))patch[k]=clamp(n.advanced.brush[k],0,k==='fullness'?2:1);
 await app.configure47({values,preset,size:n.layout==='single'?400:n.size,inkOpacity:n.opacity,mountKey:n.layout==='single'?'dark':n.advanced.mountKey||'paris',brushPatch:{...patch,dry:n.dry,dynamics:n.dynamics,color:n.ink},focus:'start'});
 if(n.text)app.setGuide(n.text,'参考文字');window.writingLocked=true;window.Revision39?.syncLock();document.dispatchEvent(new Event('writing-scenario47'));app.showWriter();
 }finally{applying=false}
}
function dialog(id,title){document.getElementById(id)?.remove();const d=E('dialog',{id,class:'studioDialog50'}),head=E('header',{class:'dialogHead'}),body=E('div',{class:'dialogBody'});head.append(E('h2',{},title));const close=E('button',{type:'button','aria-label':'关闭'},'完成 ×');const parent=[...document.querySelectorAll('dialog[open]')].at(-1);close.onclick=()=>{d.close();if(parent?.isConnected&&!parent.open)parent.showModal();else if(id==='studioAdmin50'){if(managementParent53?.isConnected)app.openDialog(managementParent53.id);else app.openDialog('paperDialog')}};head.append(close);d.append(head,body);document.body.append(d);return {d,body};}
function button(parent,text,fn,attrs={}){const b=E('button',{type:'button',...attrs},text);b.onclick=async()=>{try{await fn()}catch(e){const body=b.closest('dialog')?.querySelector('.dialogBody');if(body){let error=body.querySelector('.studioActionError50');if(!error){error=E('p',{class:'studioActionError50 studioError50',role:'alert'});body.prepend(error)}error.textContent=e.message||String(e)}report(e)}};parent.append(b);return b;}
function field(parent,label,value,type,onchange,options){const l=E('label',{},label),e=E(options?'select':type==='textarea'?'textarea':'input',options||type==='textarea'?{}:{type});if(options)for(const [v,t]of options)e.append(E('option',{value:v},t));e.value=value;e.oninput=()=>{try{onchange(type==='number'||type==='range'?Number(e.value):e.value)}catch(err){report(err)}};l.append(e);parent.append(l);return e;}
async function digest(password,salt){if(!crypto.subtle)throw Error('此浏览器未提供本地口令功能，请用 Safari/Chrome 的 HTTPS 或 localhost 打开');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);return Array.from(new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',iterations:100000,salt:new TextEncoder().encode(salt)},key,256)),x=>x.toString(16).padStart(2,'0')).join('');}
async function unlock(force=false){
 managementParent53=document.querySelector('dialog[open]:not(.studioDialog50)')||managementParent53;
 if(unlocked)return openAdmin();const {d,body}=dialog('studioUnlock50','本机管理员登录');let stored;try{stored=JSON.parse(localStorage.getItem(AUTH)||'null')}catch{throw Error('本机管理口令无法读取，请先备份本机配置')}
 body.append(E('p',{class:'studioNote50'},stored?'账号 admin，输入之前设置的本机管理密码。':'首次登录：用户名 admin，密码 admin。仅管理当前浏览器的本机配置，不是云端管理员账号。'));
 const form=E('form'),ul=E('label',{},'用户名'),username=E('input',{type:'text',value:'admin',required:'',autocomplete:'username'}),pl=E('label',{},'密码'),pw=E('input',{type:'password',required:'',autocomplete:'current-password'});ul.append(username);pl.append(pw);
 const error=E('p',{role:'status',class:'studioError50'}),submit=E('button',{type:'submit',class:'studioPrimary50'},'登录管理');const remember=E('input',{type:'checkbox'}),rl=E('label',{},'保持本机管理登录');remember.checked=localStorage.getItem('iinnkk.remember55')==='yes';rl.prepend(remember);form.append(ul,pl,rl,error,submit);
 form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;try{if(username.value.trim()!=='admin')throw Error('本机管理员用户名为 admin');if(stored){if(await digest(pw.value,stored.salt)!==stored.hash)throw Error('密码不正确，请使用本机原管理密码')}else{if(pw.value!=='admin')throw Error('首次登录密码为 admin');const salt=crypto.randomUUID();localStorage.setItem(AUTH,JSON.stringify({salt,hash:await digest(pw.value,salt)}))}pw.value='';localStorage.setItem('iinnkk.remember55',remember.checked?'yes':'no');unlocked=true;document.dispatchEvent(new Event('admin-unlocked53'));d.close();openAdmin()}catch(err){error.textContent=err.message}finally{submit.disabled=false}};body.append(form);d.showModal();
}
async function changePassword52(){requireAdmin();const {d,body}=dialog('studioPassword52','修改本机管理密码'),form=E('form'),p=E('input',{type:'password',minlength:'8',required:'',autocomplete:'new-password','aria-label':'新密码'}),again=E('input',{type:'password',minlength:'8',required:'',autocomplete:'new-password','aria-label':'再次输入新密码'}),error=E('p',{role:'status'}),submit=E('button',{type:'submit'},'保存新密码');body.append(E('p',{},'用户名保持 admin；新密码至少 8 位。'));form.append(p,again,error,submit);body.append(form);form.onsubmit=async e=>{e.preventDefault();try{requireAdmin();if(p.value!==again.value)throw Error('两次密码不一致');const salt=crypto.randomUUID();localStorage.setItem(AUTH,JSON.stringify({salt,hash:await digest(p.value,salt)}));d.close();app.toast('本机管理密码已修改')}catch(e){error.textContent=e.message}};d.showModal();
}
function requireAdmin(){if(!unlocked)throw Error('请先解锁本机管理');}
function openAdmin(){requireAdmin();admin=dialog('studioAdmin50','创作工作台 · 本机管理');const {d,body}=admin;body.append(E('p',{class:'studioEyebrow50'},'编排你的纸、墨与每一次落笔'));
 const tools=E('div',{class:'studioActions50'});button(tools,'新增入口',()=>{const n={...copy(defaults.nav[1]),id:'nav-'+crypto.randomUUID(),title:'新入口'};config.nav.push(n);selected=n.id;save();openAdmin()});button(tools,'导出配置',()=>download(new Blob([JSON.stringify(config,null,2)],{type:'application/json'}),'今日亲笔-本机配置.json'));const file=E('input',{type:'file',accept:'.json,application/json',hidden:''});file.onchange=async()=>{try{requireAdmin();if(file.files[0].size>3000000)throw Error('配置文件过大');const incoming=normalize(JSON.parse(await file.files[0].text()));save(incoming);selected=config.nav[0]?.id;openAdmin()}catch(e){report(e)}};tools.append(file);button(tools,'导入配置',()=>file.click());button(tools,'修改管理密码',changePassword52);button(tools,'锁定管理',()=>{localStorage.removeItem('iinnkk.remember55');unlocked=false;document.dispatchEvent(new Event('admin-locked53'));d.close();d.remove()});body.append(tools);status=E('p',{class:'studioStatus50',role:'status'},'修改自动保存到 LocalStorage，仅此设备生效');body.append(status);
 const layout=E('div',{class:'studioAdminGrid50'}),list=E('nav',{class:'studioNavList50','aria-label':'导航排序'}),editor=E('section',{class:'studioEditor50'});layout.append(list,editor);body.append(layout);
 function reorder(id,to){const i=config.nav.findIndex(n=>n.id===id);if(i<0||to<0||to>=config.nav.length)return;config.nav.splice(to,0,config.nav.splice(i,1)[0]);save();renderList()}
 let drag=null;
 function renderList(){list.replaceChildren();config.nav.forEach((n,i)=>{const row=E('div',{class:'studioNavRow50',draggable:'true','data-id':n.id});const choose=button(row,n.title,()=>{selected=n.id;renderList();renderEditor()},{'aria-current':String(n.id===selected)});button(row,'↑',()=>reorder(n.id,i-1),{'aria-label':'上移 '+n.title});button(row,'↓',()=>reorder(n.id,i+1),{'aria-label':'下移 '+n.title});row.ondragstart=e=>{drag=n.id;e.dataTransfer.setData('text/plain',n.id)};row.ondragover=e=>e.preventDefault();row.ondrop=e=>{e.preventDefault();reorder(drag,i)};
 // Touch drag handle preserves page scrolling elsewhere; arrows remain a keyboard alternative.
 const handle=button(row,'☰',()=>{}, {'aria-label':'拖动排序 '+n.title,class:'studioDrag50'});let startY;handle.onpointerdown=e=>{startY=e.clientY;handle.setPointerCapture(e.pointerId);e.preventDefault()};handle.onpointerup=e=>{if(startY===undefined)return;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-id]');if(target)reorder(n.id,config.nav.findIndex(x=>x.id===target.dataset.id));else if(Math.abs(e.clientY-startY)>24)reorder(n.id,i+(e.clientY>startY?1:-1));startY=undefined};list.append(row)});}
 function renderEditor(){editor.replaceChildren();const n=config.nav.find(x=>x.id===selected);if(!n){editor.append(E('p',{},'新增一个入口，开始编排。'));return}
 const change=(key,value)=>{n[key]=value;save();if(key==='title')renderList()};
 field(editor,'入口名称',n.title,'text',v=>change('title',v)).maxLength=16;
 const actions=E('div',{class:'studioActions50'});button(actions,'预览此入口',async()=>{await applyMode(n);d.close()},{class:'studioPrimary50'});button(actions,'读取当前书写设置',()=>{const s=app.settingsSnapshot();Object.assign(n,{advanced:s,opacity:s.inkOpacity??1,size:s.brush.size,dry:s.brush.dry,dynamics:s.brush.dynamics,ink:s.brush.color,paper:s.values.papercolor,pattern:s.values.paperPattern,material:s.values.material,ruling:s.values.showLines==='no'?'none':s.values.ruling,zoom:+s.values.zoom,rows:+s.values.rows,columns:+s.values.columns,direction:s.values.followDirection});save();renderEditor()});button(actions,'删除入口',()=>{config.nav=config.nav.filter(x=>x.id!==n.id);selected=config.nav[0]?.id;save();renderList();renderEditor()});editor.append(actions);
 const grid=E('div',{class:'studioFields50'});editor.append(grid);
 const selects=[['layout','字数内容',[['single','单字'],['combination','多字组合'],['poem','经典诗词'],['free','自由输入']]],['format','宣纸幅式',Object.entries(formats).map(([k,v])=>[k,v[0]])],['direction','书写方向',[['vertical','竖排 · 右起'],['horizontal','横排 · 左起']]],['preset','水墨书风',Object.entries(app.presets).map(([k,v])=>[k,v.name])],['ruling','格线',[['mi','米字格'],['jiu','九宫格'],['hui','回宫格'],['vertical','竖线'],['horizontal','横线'],['none','无格']]],['pattern','边缘纹样',[...document.getElementById('paperPattern').options].map(o=>[o.value,o.text])],['material','纸张材质',[...document.getElementById('material').options].map(o=>[o.value,o.text])]];
 for(const[k,label,opts]of selects)field(grid,label,n[k],'select',v=>{change(k,v);if(k==='layout'&&v==='single'){n.ruling='mi';n.rows=n.columns=1;save();renderEditor()}},opts);
 for(const[k,label,min,max,step]of [['rows','行数',1,30,1],['columns','列数',1,30,1],['size','笔径',1,1000,1],['zoom','纸张缩放 %',50,800,10],['dry','飞白 / 枯笔',0,1,.01],['dynamics','提按变化',0,1,.01],['opacity','墨迹不透明度',.01,1,.01]]){const e=field(grid,label,n[k],'number',v=>change(k,v));Object.assign(e,{min,max,step})}
 field(grid,'复古纸色',n.paper,'color',v=>change('paper',v));field(grid,'墨色',n.ink,'color',v=>change('ink',v));
 if(n.layout==='poem'){const choices=[['春晓','春眠不觉晓，处处闻啼鸟。夜来风雨声，花落知多少。'],['登鹳雀楼','白日依山尽，黄河入海流。欲穷千里目，更上一层楼。'],['静夜思','床前明月光，疑是地上霜。举头望明月，低头思故乡。']];const p=E('div',{class:'studioActions50'});for(const [name,text]of choices)button(p,name,()=>{change('text',text);renderEditor()});editor.append(p)}
 field(editor,'参考文字（可自由输入，留空则不显示）',n.text,'textarea',v=>change('text',v)).maxLength=20000;
 const advanced=E('details'),summary=E('summary',{},'更多预设 · 印章、照片排版与笔墨细节');advanced.append(summary);const fields=E('div',{class:'studioFields50'});advanced.append(fields);editor.append(advanced);
 const settingIds=['headText','headType','headShape','headFont','headSize','tailText','tailType','tailShape','sealFont','tailSize','postcardCity','postcardDate','photoVeil','autoScroll','panSpeed','guideOpacity'];
 const snap=app.settingsSnapshot();for(const id of settingIds){const source=document.getElementById(id);if(!source)continue;const label=(source.closest('label')?.childNodes[0]?.textContent||id).trim();const opts=source.options?[...source.options].map(o=>[o.value,o.text]):null;const v=n.advanced.values?.[id]??snap.values[id];field(fields,label,v,opts?'select':source.type==='range'?'number':'text',value=>{n.advanced.values||={};n.advanced.values[id]=value;save()},opts)}
 }
 renderList();renderEditor();
 const brand=E('details');brand.append(E('summary',{},'网站文字与视觉'));const bg=E('div',{class:'studioFields50'});brand.append(bg);for(const[k,label,type]of [['name','网站名称','text'],['slogan','Slogan','text'],['color','标题颜色','color'],['size','标题字号','number']])field(bg,label,config.brand[k],type,v=>{config.brand[k]=v;save()});body.append(brand);
 const integrations=E('details');integrations.append(E('summary',{},'供应链接口'));const ig=E('div',{class:'studioFields50'});integrations.append(ig);for(const[k,label]of [['webhook','供应链 Webhook 地址']])field(ig,label,config.integrations[k],'text',v=>{config.integrations[k]=v;save()});integrations.append(E('p',{class:'studioNote50'},'供应链提交需手动确认。'));body.append(integrations);document.dispatchEvent(new CustomEvent('admin-panel53',{detail:{body}}));d.showModal();
}
async function init(){if(!window.Revision47?.ready||!window.AnnotationApp){setTimeout(init,40);return}app=AnnotationApp;renderNav();applyBrand();if(loadError)report(Error(loadError));
 const access=E('details',{class:'studioAccess50'});access.append(E('summary',{},'本机管理'));button(access,'解锁网站后台管理面板',()=>unlock(true));document.getElementById('paperDialog').querySelector('.dialogBody').append(access);
 document.addEventListener('keydown',e=>{if(e.altKey&&e.shiftKey&&e.key.toLowerCase()==='m'){e.preventDefault();unlock().catch(report)}});
 // Existing writer controls keep their original storage, and mirror settings locally for portable front-end use.
 let timer;document.addEventListener('change',e=>{if(e.target.closest('dialog')&&!e.target.closest('.studioDialog50')){clearTimeout(timer);timer=setTimeout(()=>{try{localStorage.setItem('iinnkk.writer.settings.v1',JSON.stringify(app.settingsSnapshot()))}catch(err){report(Error('本机设置未保存，请检查存储空间'))}},300)}});
 window.InkStudio50.ready=true;if(new URLSearchParams(location.search).get('manage')==='1'){document.getElementById('managementEntry52')?.remove();unlock().catch(report)}
}
window.InkStudio50={ready:false,get config(){return copy(config)},get isAdmin(){return unlocked},saveConfig:next=>{requireAdmin();save(next)},formats,normalize,E,dialog,button,download,safeURL,openAdmin:()=>unlock(true),applyMode,report};init();
})();
