/* Public GitHub Pages archive. Admin writes use a session-only fine-grained GitHub token. */
(function(){
 const repo='jearns/iinnkk',api='https://api.github.com/repos/'+repo,manifestPath='timeline/manifest.json';
 let token='',catalog={version:74,entries:{}},ready;
 const validId=id=>/^[a-z0-9_-]{1,60}$/.test(id);
 const filename=s=>typeof s==='string'&&/^timeline\/pages\/[a-z0-9_-]+\/(?:[a-z0-9_-]+\/)?[^/\\\x00-\x1f]+\.(?:jpe?g|png|webp)$/i.test(s)&&!s.split('/').some(p=>p==='.'||p==='..');
 function clean(raw){const entries={};for(const [id,r] of Object.entries(raw?.entries||{})){if(!validId(id)||!r||typeof r!=='object')continue;entries[id]={deleted:!!r.deleted,era:String(r.era||'').slice(0,40),script:String(r.script||'').slice(0,40),year:Number(r.year)||0,dateLabel:String(r.dateLabel||'').slice(0,100),glyph:String(r.glyph||'筆').slice(0,4),order:Number(r.order)||0,title:String(r.title||'').slice(0,120),place:String(r.place||'').slice(0,120),museum:String(r.museum||'').slice(0,180),status:String(r.status||'').slice(0,240),parentId:validId(r.parentId||'')?r.parentId:'',url:/^https:\/\//.test(r.url)?String(r.url).slice(0,500):'',style:String(r.style||'zhang').slice(0,40),size:Math.max(6,Math.min(1000,+r.size||350)),zoom:Math.max(25,Math.min(2500,+r.zoom||160)),cover143:filename(r.cover143)?r.cover143:'',coverCrop145:CoverCrop145.clean(r.coverCrop145),author:String(r.author||'').slice(0,120),fullText148:String(r.fullText148||'').slice(0,30000),videoUrl148:GalleryModel148.link(r.videoUrl148).slice(0,2000),videoTitle148:String(r.videoTitle148||'').slice(0,120),pageNames:Array.isArray(r.pageNames)?r.pageNames.map(n=>String(n).slice(0,240)).slice(0,150):[],pages:Array.isArray(r.pages)?r.pages.filter(filename).slice(0,150):[]}}for(const [id,e]of Object.entries(entries)){const rawEntry=raw.entries[id];for(const key of ['era','script','dateLabel'])if(!rawEntry[key])delete e[key];if(rawEntry.year===undefined)delete e.year}return{version:74,entries,order129:Array.isArray(raw?.order129)?raw.order129.filter(validId):[]}}
 async function request(path,method='GET',body,authorized=true){const headers={Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};if(authorized&&token)headers.Authorization='Bearer '+token;if(body)headers['Content-Type']='application/json';const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);let res;try{res=await fetch(api+path,{method,headers,body:body?JSON.stringify(body):undefined,cache:'no-store',signal:controller.signal})}finally{clearTimeout(timer)};if(!res.ok){let message='';try{message=(await res.json()).message||''}catch{}throw Error('GitHub '+res.status+(message?' · '+message.slice(0,100):''))}return res.json()}
 async function fetchCatalog(){try{const response=await fetch(new URL(manifestPath,location.href),{cache:'default'});if(response.ok)catalog=clean(await response.json())}catch{}return catalog}
 async function remoteCatalog143(){try{const raw=await request('/contents/'+manifestPath+'?ref=main', 'GET',null,false);if(raw?.content){const bytes=Uint8Array.from(atob(raw.content.replace(/\s/g,'')),c=>c.charCodeAt(0));catalog=clean(JSON.parse(new TextDecoder().decode(bytes)));return catalog}}catch{}try{const response=await fetch(new URL(manifestPath+'?v='+Date.now(),location.href),{cache:'no-store'});if(response.ok)catalog=clean(await response.json())}catch{}return catalog}
 ready=fetchCatalog();setTimeout(()=>{if(navigator.onLine)remoteCatalog143().then(()=>document.dispatchEvent(new Event('timeline-cloud74')))},15000);
 function connect(value){if(!/^github_pat_[A-Za-z0-9_]+$|^ghp_[A-Za-z0-9]+$/.test(value||''))throw Error('请填入 GitHub 细粒度令牌');token=value}
 function base64(buffer){const a=new Uint8Array(buffer);let binary='';for(let i=0;i<a.length;i+=32768)binary+=String.fromCharCode(...a.subarray(i,i+32768));return btoa(binary)}
 async function compress(file){if(!(file instanceof Blob)||file.size>20e6)throw Error('单张原图需小于 20MB');const u=URL.createObjectURL(file);try{const img=new Image();img.src=u;await img.decode();const scale=GalleryModel148.uploadScale(img.naturalWidth,img.naturalHeight),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const c=canvas.getContext('2d');c.fillStyle='#f9f6f0';c.fillRect(0,0,canvas.width,canvas.height);c.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('图片压缩失败')),(/\.png$/i.test(file.name)?'image/png':/\.webp$/i.test(file.name)?'image/webp':'image/jpeg'),.86));if(blob.size>5e6)throw Error('压缩后超过 5 MB，请先缩小原图');return base64(await blob.arrayBuffer())}finally{URL.revokeObjectURL(u)}}
 let writing=false;
 async function publish(id,fields,images=[],report=()=>{}){if(writing)throw Error('正在上传，请等当前操作完成');if(!token)throw Error('先填入一次性 GitHub 写入令牌');if(!validId(id)||images.length>150)throw Error('图片或碑帖编号不符合要求');writing=true;try{
  report('正在读取线上目录…');const [ref,current]=await Promise.all([request('/git/ref/heads/main'),request('/contents/'+manifestPath+'?ref=main').catch(()=>null)]);const base=ref.object.sha,commit=await request('/git/commits/'+base);let latest={version:74,entries:{}};if(current?.content){try{const bytes=Uint8Array.from(atob(current.content.replace(/\s/g,'')),c=>c.charCodeAt(0));latest=clean(JSON.parse(new TextDecoder().decode(bytes)))}catch{}}
  const previous=latest.entries[id],uploaded=[],elements=[];if(images.length&&new Set([...(previous?.pages||[]),...(fields.pages||[]),...images]).size>150)throw Error('本帖组图合计最多150张');
  for(let i=0;i<images.length;i++){report('正在压缩并上传原帖 '+(i+1)+' / '+images.length);const content=await compress(images[i]);const blob=await request('/git/blobs','POST',{content,encoding:'base64'});const originalName=images[i].name||'原帖.jpg';if(/[\/\\\x00-\x1f]/.test(originalName)||originalName==='.'||originalName==='..')throw Error('文件名不可包含路径');const path='timeline/pages/'+id+'/'+Date.now().toString(36)+'-'+i.toString(36)+'/'+originalName;uploaded.push(path);elements.push({path,mode:'100644',type:'blob',sha:blob.sha})}
  const result=ReferenceUpload138.published(previous,fields,images,uploaded),paths=result.pages,names=result.names;
  if(Array.isArray(fields.orderRequest129))latest.order129=fields.orderRequest129.filter(validId);latest.entries[id]={...clean({entries:{[id]:{...fields,cover143:images.includes(fields.cover143)?uploaded[images.indexOf(fields.cover143)]:paths.includes(fields.cover143)?fields.cover143:'',pageNames:names,pages:paths}}}).entries[id]};const json=JSON.stringify(latest,null,2)+'\n',blob=await request('/git/blobs','POST',{content:json,encoding:'utf-8'});elements.push({path:manifestPath,mode:'100644',type:'blob',sha:blob.sha});report('正在发布线上目录…');const tree=await request('/git/trees','POST',{base_tree:commit.tree.sha,tree:elements});const next=await request('/git/commits','POST',{message:'content: update '+id+' reference gallery',tree:tree.sha,parents:[base]});try{await request('/git/refs/heads/main','PATCH',{sha:next.sha,force:false})}catch(e){throw Error('发布未完成：远端同期有更新，请重新点保存。'+e.message)}catalog=latest;document.dispatchEvent(new CustomEvent('timeline-cloud74',{detail:{id,commit:next.sha}}));return latest.entries[id]
 }finally{writing=false}}
 window.TimelineCloud74={get order129(){return catalog.order129||[]},publishOrder129:ids=>publish(ids[0],{...(window.Timeline73?.data129(window.Timeline73.chapters.find(c=>c.id===ids[0]))||catalog.entries[ids[0]]||{}),orderRequest129:ids}),get ready(){return ready},get:id=>catalog.entries[id],all:()=>catalog.entries,refresh:async()=>{ready=remoteCatalog143();setTimeout(()=>{if(navigator.onLine)remoteCatalog143().then(()=>document.dispatchEvent(new Event('timeline-cloud74')))},15000);await ready;document.dispatchEvent(new Event('timeline-cloud74'));return catalog},connect,publish,hasToken:()=>!!token};
})();
