/* A local-first history scroll. Official collection links are metadata, never substituted for facsimile images. */
(function init(){
 if(!window.CalligraphyTimeline73||!window.AnnotationHome||!window.InkStudio50?.ready||!window.CopyAlbums38?.openPages55||!window.DraftStore||!window.TimelineCloud74){setTimeout(init,45);return}
 const $=id=>document.getElementById(id),U=InkStudio50,A=AnnotationApp,chapters=[...CalligraphyTimeline73].sort((a,b)=>(b.year||0)-(a.year||0));
 const E=(tag,cls='',text='')=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text)e.textContent=text;return e};
 const section=E('section','timeline73'),title=E('div','timelineHead73'),intro=E('div','timelineIntro73'),rail=E('div','timelineRail73');section.id='inkTimeline73';rail.tabIndex=0;rail.setAttribute('aria-label','全球文字文明与中国书法时间轴：向下穿越年代，左右翻看同题书作');
 title.innerHTML='<span>人类群星闪耀时</span><small>在数字赛博空间，你我一起结网记字！</small>';
 const prev=E('button','timelineArrow73','‹'),next=E('button','timelineArrow73','›');prev.type=next.type='button';prev.setAttribute('aria-label','向今翻动');next.setAttribute('aria-label','向古翻动');
 const theme=E('div','homeTheme78');theme.setAttribute('role','group');theme.setAttribute('aria-label','首页主题');for(const [label,key] of [['浅色河流','river'],['深色星空','stars']]){const b=E('button','',label);b.type='button';b.dataset.theme=key;b.onclick=()=>{document.body.dataset.homeTheme=key;try{localStorage.setItem('iinnkk.home.theme78',key)}catch{};theme.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))};theme.append(b)}const savedTheme=(()=>{try{return localStorage.getItem('iinnkk.home.theme78')}catch{return null}})();theme.querySelector('[data-theme="'+(savedTheme==='river'?'river':'stars')+'"]').click();
 const wrap=E('div','timelineFrame73');wrap.append(prev,rail,next);section.append(title,theme,intro,wrap);
 const home=$('annotationHome'),gallery=home?.querySelector('.annotationGallery');if(!gallery)return;gallery.before(section);document.documentElement.classList.add('timeline-ready73');
 function sortChapters(){chapters.sort((a,b)=>(Number(TimelineCloud74.get(b.id)?.year??b.year)||0)-(Number(TimelineCloud74.get(a.id)?.year??a.year)||0)||a.id.localeCompare(b.id))}const uploads=new Map(),imageURLs=new Set();let rendering=0,chosen=null,activeIndex=0;
 async function load(){render();await TimelineCloud74.ready;for(const [id,c]of Object.entries(TimelineCloud74.all()))if(!chapters.some(x=>x.id===id))chapters.push({id,...c});sortChapters();const values=U.isAdmin?await Promise.all(chapters.map(c=>DraftStore.get('timeline73:'+c.id).catch(()=>null))):[];chapters.forEach((c,i)=>{const online=TimelineCloud74.get(c.id);if(online)uploads.set(c.id,online);else if(U.isAdmin&&values[i])uploads.set(c.id,values[i])});render()}
 const modal=E('dialog','timelineDialog73');modal.id='timelineDialog73';modal.innerHTML='<header class="dialogHead"><h2>碑帖真迹</h2><button type="button" data-close>关闭 ×</button></header><div class="timelineDialogBody73"></div>';document.body.append(modal);modal.querySelector('[data-close]').onclick=()=>modal.close();
 function unroll(delta){const panels=[...rail.children];activeIndex=Math.max(0,Math.min(panels.length-1,activeIndex+delta));panels[activeIndex]?.scrollIntoView({behavior:'smooth',block:'center'})}prev.onclick=()=>unroll(-1);next.onclick=()=>unroll(1);
 function chapterData(c){const data={...c,...uploads.get(c.id)};if(!Array.isArray(data.pages)||!window.ReferenceOrder134)return data;const order=ReferenceOrder134.resolve(c.id,data.pages);return{...data,pages:order,pageNames:order.map(p=>data.pageNames?.[data.pages.indexOf(p)]||String(p).split('/').at(-1))}}
 async function reorderPages134(id,pages){const c=chapters.find(c=>c.id===id);if(!c)return;const raw={...c,...uploads.get(id)};ReferenceOrder134.remember(id,raw.pages||[],pages);if(U.isAdmin&&TimelineCloud74.hasToken()){const names=pages.map(p=>raw.pageNames?.[raw.pages.indexOf(p)]||String(p).split('/').at(-1));const published=await TimelineCloud74.publish(id,{...raw,pages:pages.slice(),pageNames:names});uploads.set(id,published)}}
 document.addEventListener('reference-order134',()=>render());
 function imageFor(blob){if(typeof blob==='string'&&/^timeline\/pages\/[a-z0-9_-]+\/(?:[a-z0-9_-]+\/)?[^/\\\x00-\x1f]+\.(?:jpe?g|png|webp)$/i.test(blob)&&!blob.split('/').some(p=>p==='.'||p==='..'))return new URL(blob,location.href).href;if(!(blob instanceof Blob))return '';const u=URL.createObjectURL(blob);imageURLs.add(u);return u}
 function clearURLs(){for(const u of imageURLs)URL.revokeObjectURL(u);imageURLs.clear()}
 function card(c,featured=false){const data=featured?c:chapterData(c),button=E('article','timelineCard73'+(featured?' timelineNow73':''));button.tabIndex=0;button.setAttribute('role','button');button.dataset.id=data.id;button.style.setProperty('--ink-era',featured?'#774333':(data.order%3===0?'#354d48':data.order%3===1?'#59433d':'#4d5664'));
  const hero=E('div','timelineHero73');if(featured&&(data.blob||data.src)){const image=E('img');image.src=data.src||imageFor(data.blob);image.alt='本站推荐的书写作品';image.loading='eager';image.decoding='async';image.fetchPriority='high';hero.append(image)}else if(!featured&&data.pages?.[0]){const image=E('img');image.src=imageFor(data.cover143||data.pages[0]);image.loading='lazy';image.decoding='async';image.alt=data.title+'原帖封面';hero.append(image)}else hero.append(E('span','timelineGlyph73',data.glyph||'筆'));
  if(!featured){const landmark=E('div','timelineLandmark79');landmark.setAttribute('aria-label','馆藏城市与建筑意象');landmark.innerHTML='<svg viewBox="0 0 180 100" aria-hidden="true" fill="none" stroke="currentColor"><path d="M8 86H172M19 79V42L90 12L161 42V79M13 42H167M28 50H152M31 78V52M52 78V52M73 78V52M94 78V52M115 78V52M136 78V52M157 78V52M16 91H164" stroke-width="2"/><path d="M79 30h22M85 19h10" stroke-width="1"/></svg>';landmark.append(E('small','',data.place+' · '+data.museum));hero.append(landmark)}
  if(!featured&&!data.pages?.length)hero.append(E('small','timelineAwait73','等待原帖图像'));
  const info=E('div','timelineInfo73');info.append(E('small','timelinePeriod73',featured?'今天 · 继往开来':data.era+' · '+data.script),E('strong','',featured?(data.title||'今日亲笔 · 由你接续千年'):data.title),E('time','timelineDate78',featured?(data.workDay84||window.WorkMeta84?.dateOnly(data.updated_at||data.created)||''):data.dateLabel||'年代待考'),E('p','timelineMilestone77',featured?'让今天的亲笔，成为这一卷继续生长的新篇。':data.milestone||''),E('span','',featured?'最新本站推荐 · 当代亲笔作品':data.place+' · '+data.museum),E('small','timelineStatus73',featured?'':data.status));button.append(hero,info);button.onclick=()=>{if(featured){data.src?window.InkCloud75?.openWork(data).catch(err=>A.toast(err.message)):data.id&&A.openWork(data.id);return}if(data.pages?.length)CopyAlbums38.viewOriginal({id:'timeline73:'+c.id,title:data.title,pages:data.pages.map((image,i)=>({name:data.pageNames?.[i]||image.split('/').at(-1),image})),onWrite:()=>openCopy(c)}).catch(err=>A.toast(err.message||'真迹预览失败'));else detail(c)};button.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target===button){e.preventDefault();button.click()}};if(U.isAdmin&&!featured&&c.id!=='qianzi-source'){const manage=E('button','timelineManage74','维护');manage.type='button';manage.setAttribute('aria-label','维护 '+data.title);manage.onclick=e=>{e.stopPropagation();edit(c)};button.append(manage)}return button}
 function epoch(item,title,note,branches=[],worldId=''){const panel=E('section','timelineEpoch76'),label=E('div','timelineEra76');label.append(E('span','',title),E('small','',note));panel.append(label);const lane=E('div','timelineBranch76');lane.append(item,...branches);const world=window.TimelineWorld78?.[worldId];if(world){const aside=E('aside','timelineWorld78');aside.append(E('time','',world.date),E('strong','',world.title),E('span','',world.note));const link=E('a','',world.place+' ↗');link.href=world.url;link.target='_blank';link.rel='noopener noreferrer';aside.append(link);panel.append(aside)}panel.append(lane);return panel}
 function copyCard(work){const b=card(work,true);b.classList.add('timelineCopy83');b.querySelector('.timelinePeriod73').textContent='原帖的亲笔临写';b.querySelector('.timelineInfo73 > span').textContent='由原帖向外生长的当代作品';b.querySelector('.timelineMilestone77').textContent='点赞、评论，或继续临写这一帖。';b.querySelector('img')?.setAttribute('alt',work.title+' · 临写作品');return b}
 async function render(){const token=++rendering,homeY=home?.scrollTop||0;clearURLs();const ids=await DraftStore.get('featured54').catch(()=>[])||[],work=ids[0]?await DraftStore.get(ids[0]).catch(()=>null):null;if(token!==rendering)return;rail.replaceChildren();const publicTask=Promise.resolve(window.InkCloud75?.featured?.()||[]).catch(()=>[]),copiesTask=Promise.resolve(window.InkCloud75?.publishedCopies?.()||[]).catch(()=>[]);let publicWorks=[],copies=[];const byChapter=new Map();for(const item of copies)if(item.chapterId){const group=byChapter.get(item.chapterId)||[];group.push(item);byChapter.set(item.chapterId,group)}if(token!==rendering)return;const featured=publicWorks.length?publicWorks:[{id:ids[0],blob:work?.blob,created:work?.created,title:work&&window.WorkMeta84?WorkMeta84.format(window.InkCloud75?.user?.user_metadata?.full_name||window.InkCloud75?.user?.email?.split('@')[0]||'亲笔书家',work.title,work.created,work.quoteAuthor,work.quoteTitle):work?.title}];rail.append(epoch(card(featured[0],true),'今日，你亲笔来续写文明！','本站推荐 · 当代亲笔作品',featured.slice(1).map(w=>card(w,true))));
 const qianzi=chapters.filter(c=>!chapterData(c).deleted&&c.title.includes('千字文'));let inserted=false;
 for(const c of chapters){if(chapterData(c).deleted)continue;if(c.title.includes('千字文')||chapterData(c).parentId)continue;if(!inserted&&c.year<550){const root={id:'qianzi-source',era:'梁',script:'文本源头',title:'周兴嗣·千字文',dateLabel:'约公元500—550年',place:'梁朝',museum:'原作手迹未传',status:'从同一篇千字文展开历代不同书风；向左或向右浏览后世版本。',milestone:'周兴嗣把一千个汉字组织为可诵可写的共同文本，后世书家由此展开同题创作。',portraitLabel:'周兴嗣',glyph:'千',order:8};rail.append(epoch(card(root),'梁 · 千字文','同题作品横向展开 · '+qianzi.length+' 种后世书风',[]));const lane=rail.lastElementChild.querySelector('.timelineBranch76');for(const copy of qianzi){lane.append(card(copy));for(const work of byChapter.get(copy.id)||[])lane.append(copyCard(work))}inserted=true}rail.append(epoch(card(c),c.era+' · '+c.script,c.dateLabel||c.title,[...chapters.filter(x=>chapterData(x).parentId===c.id).map(x=>card(x)),...(byChapter.get(c.id)||[]).map(copyCard)],c.id))}
 if(!inserted){const root={id:'qianzi-source',era:'梁',script:'文本源头',title:'周兴嗣·千字文',place:'梁朝',museum:'原作手迹未传',status:'历代千字文书风沿横向展开',milestone:'一篇文章成为千年的共同书写题目。',portraitLabel:'周兴嗣',glyph:'千'};rail.append(epoch(card(root),'梁 · 千字文','同题书法左右滑动',qianzi.flatMap(x=>[card(x),...(byChapter.get(x.id)||[]).map(copyCard)])))}
 publicTask.then(works=>{if(token!==rendering||!works.length)return;const replacement=epoch(card(works[0],true),'今日，你亲笔来续写文明！','本站推荐 · 当代亲笔作品',works.slice(1).map(w=>card(w,true)));rail.firstElementChild?.replaceWith(replacement)});
 copiesTask.then(works=>{if(token!==rendering)return;for(const work of works){if(!work.chapterId)continue;const anchor=[...rail.querySelectorAll('.timelineCard73:not(.timelineNow73)')].find(c=>c.dataset.id===work.chapterId);if(anchor)anchor.after(copyCard(work))}});
 activeIndex=0;if(homeY>0)requestAnimationFrame(()=>home.scrollTop=homeY);intro.textContent='中国书法在右，世界文字时空在左；同一时代，各有光芒。';}
 async function openFeaturedAdmin(){modal.querySelector('h2').textContent='本日展卷';const body=modal.querySelector('.timelineDialogBody73');body.replaceChildren(E('p','','首屏取“我的作品”中最新推荐的一幅。推荐、取消与排序在作品管理中完成。'));const b=E('button','timelinePrimary73','管理我的作品');b.onclick=()=>{modal.close();$('myWorks')?.click()};body.append(b);if(!modal.open)modal.showModal()}
 function source(body,data){if(!data.url)return;const a=E('a','timelineSource73','查看馆方或资料来源 ↗');a.href=data.url;a.target='_blank';a.rel='noopener noreferrer';body.append(a)}
 function detail(c){chosen=c;const data=chapterData(c),body=modal.querySelector('.timelineDialogBody73');modal.querySelector('h2').textContent=data.era+' · '+data.title;body.replaceChildren();body.append(E('p','timelineMuseum73',data.place+' · '+data.museum),E('p','',data.status),E('p','',data.pages?.length?'原帖 '+data.pages.length+' 张 · 预设 '+data.style+' 书风 / 笔径 '+data.size+' / 缩放 '+data.zoom+'%':'此篇的真迹图尚未由管理员上传。馆藏说明可参考，临写须先取得对应碑帖图像。'));source(body,data);if(data.pages?.length){const go=E('button','timelinePrimary73','打开临帖 · '+data.pages.length+' 张');go.onclick=()=>{modal.close();openCopy(c).catch(err=>A.toast(err.message||'临帖打开失败'))};body.append(go)}if(!modal.open)modal.showModal()}
 async function openCopy(c){const data=chapterData(c),pages=data.pages;if(!pages?.length)throw Error('管理员尚未上传原帖组图');if(modal.open)modal.close();await CopyAlbums38.openPages55({id:'timeline73:'+c.id,title:data.title,author:data.author||'',pages:pages.map((image,i)=>({name:data.pageNames?.[i]||image.split('/').at(-1),image,workIds:[]}))});await A.configure47({preset:A.presets[data.style]?data.style:'zhang',size:35,values:{zoom:'200',sceneChoice:'none',paperExtent:'fixed',opacity:'20',refFit:'contain'},focus:'start'});A.showWriter();if(!A.isOverview55())$('fitView').click();if(window.Reference129?.entered)await window.Reference129.entered();else window.Reference129?.openSettings?.();}
 async function edit(c){if(!InkCloud75.isFounder132)return;chosen=c;const d=chapterData(c),body=modal.querySelector('.timelineDialogBody73');modal.querySelector('h2').textContent='维护 · '+c.title;body.replaceChildren();body.classList.add('referenceMaintenance136');const gallery=E('div');body.append(gallery);const metadata=E('details'),summary=E('summary','','帖名、作者与馆藏设定'),form=E('div');metadata.append(summary,form);body.append(metadata);const fields={};for(const [key,label,type] of [['title','封面与帖名','text'],['author','作者','text'],['era','时代','text'],['script','书体','text'],['year','年份（公元前用负数）','number'],['dateLabel','年代说明','text'],['place','国家与城市','text'],['museum','现存机构或版本','text'],['status','原件、摹本或亡佚说明','text'],['url','馆藏网址','url'],['size','笔径','number'],['zoom','页面缩放 %','number']]){const l=E('label','timelineField73',label),input=E('input');input.type=type;input.value=d[key]??'';if(type==='number'&&key!=='year'){input.min='20';input.max=key==='size'?'1000':'500'}l.append(input);form.append(l);fields[key]=input}
 const coverLabel=E('label','timelineField73','首页封面用图'),cover=E('select');cover.setAttribute('aria-label','首页封面用图');coverLabel.append(cover);body.append(coverLabel);
 const parentLabel=E('label','timelineField73','主帖 / 从帖'),parent=E('select');parent.add(new Option('主帖 · 时间轴源头',''));for(const source of chapters.filter(x=>x.id!==c.id))parent.add(new Option('从帖 · '+source.title,source.id));parent.value=d.parentId||'';parentLabel.append(parent);form.append(parentLabel);
 const styleLabel=E('label','timelineField73','书风'),style=E('select');for(const [key,preset] of Object.entries(A.presets))style.add(new Option(preset.name.split('-')[0],key));style.value=A.presets[d.style]?d.style:'zhang';styleLabel.append(style);form.append(styleLabel);
 const tokenField=E('input');tokenField.type='password';tokenField.autocomplete='off';tokenField.placeholder=TimelineCloud74.hasToken()?'已在本页连接，可留空':'输入仅授权此仓库 Contents 写入的细粒度 GitHub 令牌';const tokenLabel=E('label','timelineField73','线上管理 · GitHub 临时令牌');tokenLabel.append(tokenField);body.append(tokenLabel,E('small','', '令牌只保存在本页内存，不写进作品、浏览器存储或代码仓库。'));const files=E('input');files.type='file';files.accept='image/jpeg,image/png,image/webp';files.multiple=true;const upload=E('label','timelineField73','追加原帖组图（保留现有图片，每张最多 20 MB，合计最多 150 张）');upload.append(files);body.append(upload);
 const pageOrder=gallery;let ordered=[...(d.pages||[])],coverPage=d.cover143||ordered[0];function drawOrder(){cover.replaceChildren(new Option('自动使用第一张',''));ordered.forEach((page,i)=>cover.add(new Option((i+1)+' · '+(page.name||d.pageNames?.[i]||String(page).split('/').at(-1)),String(i))));cover.value=ordered.includes(coverPage)?String(ordered.indexOf(coverPage)):'';cover.onchange=()=>{coverPage=cover.value===''?null:ordered[Number(cover.value)]};window.ReferenceGallery136.render(pageOrder,ordered,{name:(page,i)=>page.name||d.pageNames?.[i]||String(page).split('/').at(-1),image:page=>typeof page==='string'?new URL(page,location.href).href:imageFor(page),move:async(from,to)=>{const names=ordered.map((page,i)=>page.name||d.pageNames?.[i]||String(page).split('/').at(-1));const [p]=ordered.splice(from,1);ordered.splice(to,0,p);const [n]=names.splice(from,1);names.splice(to,0,n);d.pageNames=names;d.pages=ordered;if(ordered.every(p=>typeof p==='string'))await reorderPages134(c.id,ordered);drawOrder()}})}drawOrder();const syncOrder134=e=>{if(e.detail.id!==c.id||ordered.some(p=>p instanceof Blob))return;const fresh=chapterData(c);ordered=[...fresh.pages||[]];d.pageNames=fresh.pageNames;d.pages=ordered;drawOrder()};document.addEventListener('reference-order134',syncOrder134);modal.addEventListener('close',()=>document.removeEventListener('reference-order134',syncOrder134),{once:true});files.onchange=()=>{const oldNames=ordered.map((p,i)=>p.name||d.pageNames?.[i]||String(p).split('/').at(-1));ordered=ReferenceUpload138.append(ordered,ReferenceGallery136.numbered([...files.files]));d.pageNames=ordered.map((p,i)=>p.name||oldNames[i]||String(p).split('/').at(-1));pageOrder.dataset.page136='0';drawOrder()};
 const count=E('small','',d.pages?.length?'当前已存 '+d.pages.length+' 张；新选图片将追加，原有图片和排序保留。':'尚未上传图像');body.append(count);source(body,d);
 const actions=E('div','timelineEditorActions73'),save=E('button','timelinePrimary73','保存封面与预设'),remove=E('button','','移除已上传图像');actions.append(save,remove);body.append(actions);const deletePost=E('button','','删除本帖');actions.append(deletePost);deletePost.onclick=async()=>{if(!U.isAdmin||!confirm('从前台移除此帖？已保存的临写作品会保留。'))return;try{if(tokenField.value)TimelineCloud74.connect(tokenField.value.trim());const result=await TimelineCloud74.publish(c.id,{...d,deleted:true},[],v=>count.textContent=v);uploads.set(c.id,result);modal.close();render()}catch(e){count.textContent=e.message}};remove.onclick=async()=>{if(!U.isAdmin)return;try{if(tokenField.value){TimelineCloud74.connect(tokenField.value.trim());tokenField.value=''}const next=await TimelineCloud74.publish(c.id,{...d,pages:[]},[],v=>count.textContent=v);uploads.set(c.id,next);modal.close();render()}catch(e){count.textContent=e.message}};
 save.onclick=async()=>{if(!U.isAdmin)return;const f=files.files.length?ordered.filter(p=>p instanceof Blob):[];if(ordered.length>150||f.some(x=>x.size>20e6)){count.textContent='本帖组图合计最多150张，每张不超过20MB';return}const next={...d,deleted:false,...Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,['size','zoom','year'].includes(k)?+v.value:v.value.trim().slice(0,200)])),style:style.value,parentId:parent.value,cover143:coverPage||''};try{if(tokenField.value){TimelineCloud74.connect(tokenField.value.trim());tokenField.value=''}d.pages=ordered;next.pages=ordered;const local=f.length?f:Array.isArray(d.pages)?d.pages.filter(p=>p instanceof Blob):[];const published=await TimelineCloud74.publish(c.id,next,local,v=>count.textContent=v);uploads.set(c.id,published);Object.assign(c,published);sortChapters();modal.close();render()}catch(e){count.textContent=e.message||'线上上传失败，请重试'}};if(!modal.open)modal.showModal()}
 // One delegated handler covers the home and the in-editor copy shortcut, including admin renames.
 document.addEventListener('click',e=>{if(window.Revision90)return;const button=e.target.closest('button');if(!button||!button.closest('#homeQuick47,#writerModes53')||button.textContent.trim()!=='临帖')return;e.preventDefault();e.stopImmediatePropagation();modal.querySelector('h2').textContent='择一帖，临其神';const body=modal.querySelector('.timelineDialogBody73');body.replaceChildren();const grid=E('div','timelinePicker73');for(const c of chapters)grid.append(card(c));body.append(E('p','','沿历史长卷挑选名帖。点封面查看原件与预设。'),grid);if(!modal.open)modal.showModal()},true);
 document.addEventListener('work-featured54',render);let lastAdmin=U.isAdmin;document.addEventListener('admin-unlocked53',()=>{if(lastAdmin===U.isAdmin)return;lastAdmin=U.isAdmin;load()});document.addEventListener('cloud-copies83',render);document.addEventListener('timeline-cloud74',()=>{for(const [id,data]of Object.entries(TimelineCloud74.all()))if(!chapters.some(c=>c.id===id))chapters.push({id,...data});sortChapters();for(const c of chapters){const remote=TimelineCloud74.get(c.id);if(remote){uploads.set(c.id,remote);CopyAlbums38.syncCatalogue134?.(c.id,chapterData(c)).catch(e=>A.toast(e.message))}}render()});load();
 window.Timeline73={chapters,openCopy,reorderPages134,refresh:render,edit129:edit,add129:()=>addPost.click(),data129:chapterData,sort129:sortChapters};const addPost=E('button','timelineAdd128','新增碑帖');title.append(addPost);const syncAdmin=()=>addPost.hidden=!U.isAdmin;syncAdmin();document.addEventListener('admin-unlocked53',syncAdmin);document.addEventListener('cloud-copies83',syncAdmin);addPost.onclick=()=>{if(!U.isAdmin)return;const c={id:'post-'+crypto.randomUUID(),title:'新碑帖',era:'当代',script:'楷书',year:new Date().getFullYear(),glyph:'筆',order:chapters.length,size:40,zoom:200,pages:[],place:'',museum:'',status:''};chapters.push(c);edit(c)};setInterval(()=>{const lane=rail.firstElementChild?.querySelector('.timelineBranch76');if(!lane||lane.children.length<2||document.hidden||!document.body.classList.contains('home-open'))return;const i=([...lane.children].findIndex(x=>x.getBoundingClientRect().left>=lane.getBoundingClientRect().left-10)+1)%lane.children.length;lane.scrollTo({left:lane.children[i]?.offsetLeft-lane.children[0].offsetLeft||0,behavior:'smooth'})},6000);
})();
