/* A local-first history scroll. Official collection links are metadata, never substituted for facsimile images. */
(function init(){
 if(!window.CalligraphyTimeline73||!window.AnnotationHome||!window.InkStudio50?.ready||!window.CopyAlbums38?.openPages55||!window.DraftStore||!window.TimelineCloud74){setTimeout(init,45);return}
 const $=id=>document.getElementById(id),U=InkStudio50,A=AnnotationApp,chapters=[...CalligraphyTimeline73].reverse();
 const E=(tag,cls='',text='')=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text)e.textContent=text;return e};
 const section=E('section','timeline73'),title=E('div','timelineHead73'),intro=E('div','timelineIntro73'),rail=E('div','timelineRail73');section.id='inkTimeline73';rail.tabIndex=0;rail.setAttribute('aria-label','中国书法千年长卷：向左滑动，依次回望早期书迹');
 title.innerHTML='<span>千里书法江山图</span><small>当代新作 · 向左展开历史 · 殷商甲骨</small>';
 const prev=E('button','timelineArrow73','‹'),next=E('button','timelineArrow73','›');prev.type=next.type='button';prev.setAttribute('aria-label','向今卷动');next.setAttribute('aria-label','向古卷动');
 const wrap=E('div','timelineFrame73');wrap.append(prev,rail,next);section.append(title,intro,wrap);
 const home=$('annotationHome'),gallery=home?.querySelector('.annotationGallery');if(!gallery)return;gallery.before(section);document.documentElement.classList.add('timeline-ready73');
 const uploads=new Map(),imageURLs=new Set();let rendering=0,chosen=null,activeIndex=0;
 async function load(){await TimelineCloud74.ready;const values=U.isAdmin?await Promise.all(chapters.map(c=>DraftStore.get('timeline73:'+c.id).catch(()=>null))):[];chapters.forEach((c,i)=>{const online=TimelineCloud74.get(c.id);if(online?.pages?.length||online?.title)uploads.set(c.id,online);else if(U.isAdmin&&values[i])uploads.set(c.id,values[i])});render()}
 const modal=E('dialog','timelineDialog73');modal.id='timelineDialog73';modal.innerHTML='<header class="dialogHead"><h2>碑帖真迹</h2><button type="button" data-close>关闭 ×</button></header><div class="timelineDialogBody73"></div>';document.body.append(modal);modal.querySelector('[data-close]').onclick=()=>modal.close();
 function unroll(delta){const cards=[...rail.children];activeIndex=Math.max(0,Math.min(cards.length-1,activeIndex+delta));rail.scrollTo({left:cards[activeIndex].offsetLeft-cards[0].offsetLeft,behavior:'smooth'})}prev.onclick=()=>unroll(-1);next.onclick=()=>unroll(1);rail.addEventListener('scroll',()=>{const cards=[...rail.children];if(cards.length)activeIndex=cards.reduce((b,c,i)=>Math.abs(c.offsetLeft-rail.scrollLeft)<Math.abs(cards[b].offsetLeft-rail.scrollLeft)?i:b,0)},{passive:true});
 function chapterData(c){return {...c,...uploads.get(c.id)}}
 function imageFor(blob){if(typeof blob==='string'&&/^timeline\/pages\/[a-z0-9_-]+\/[a-z0-9_-]+\.jpe?g$/.test(blob))return new URL(blob,location.href).href;if(!(blob instanceof Blob))return '';const u=URL.createObjectURL(blob);imageURLs.add(u);return u}
 function clearURLs(){for(const u of imageURLs)URL.revokeObjectURL(u);imageURLs.clear()}
 function card(c,featured=false){const data=featured?c:chapterData(c),button=E('article','timelineCard73'+(featured?' timelineNow73':''));button.tabIndex=0;button.setAttribute('role','button');button.dataset.id=data.id;button.style.setProperty('--ink-era',featured?'#774333':(data.order%3===0?'#354d48':data.order%3===1?'#59433d':'#4d5664'));
  const hero=E('div','timelineHero73');if(featured&&data.blob){const image=E('img');image.src=imageFor(data.blob);image.alt='管理员推荐的书写作品';image.loading='lazy';hero.append(image)}else if(!featured&&data.pages?.[0]){const image=E('img');image.src=imageFor(data.pages[0]);image.loading='lazy';image.alt=data.title+'原帖封面';hero.append(image)}else hero.append(E('span','timelineGlyph73',data.glyph||'筆'));
  if(!featured&&!data.pages?.length)hero.append(E('small','timelineAwait73','等待原帖图像'));
  const info=E('div','timelineInfo73');info.append(E('small','timelinePeriod73',featured?'今天 · 继往开来':data.era+' · '+data.script),E('strong','',featured?(data.title||'今日亲笔 · 由你接续千年'):data.title),E('span','',featured?'最新管理员推荐 · 当代亲笔作品':data.place+' · '+data.museum),E('small','timelineStatus73',featured?'让你的作品成为这卷长图的第一章':data.status));button.append(hero,info);button.onclick=()=>{if(featured){U.isAdmin?openFeaturedAdmin():data.id&&A.openWork(data.id);return}if(data.pages?.length)openCopy(c).catch(err=>A.toast(err.message||'临帖打开失败'));else detail(c)};button.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target===button){e.preventDefault();button.click()}};if(U.isAdmin&&!featured){const manage=E('button','timelineManage74','维护');manage.type='button';manage.setAttribute('aria-label','维护 '+data.title);manage.onclick=e=>{e.stopPropagation();edit(c)};button.append(manage)}return button}
 async function render(){const token=++rendering;clearURLs();const ids=await DraftStore.get('featured54').catch(()=>[])||[],work=ids[0]?await DraftStore.get(ids[0]).catch(()=>null):null;if(token!==rendering)return;rail.replaceChildren();rail.append(card({id:ids[0],blob:work?.blob,title:work?.title},true));for(const c of chapters)rail.append(card(c));rail.scrollLeft=0;activeIndex=0;intro.textContent='现在 → 民国 → 清 · 明 · 元 · 宋 · 唐 · 晋 · 汉 · 秦 · 周 → 殷商  ·  共 '+CalligraphyTimeline73.length+' 则书法史';}
 async function openFeaturedAdmin(){modal.querySelector('h2').textContent='本日展卷';const body=modal.querySelector('.timelineDialogBody73');body.replaceChildren(E('p','','首屏取“我的作品”中最新推荐的一幅。推荐、取消与排序在作品管理中完成。'));const b=E('button','timelinePrimary73','管理我的作品');b.onclick=()=>{modal.close();$('myWorks')?.click()};body.append(b);if(!modal.open)modal.showModal()}
 function source(body,data){if(!data.url)return;const a=E('a','timelineSource73','查看馆方或资料来源 ↗');a.href=data.url;a.target='_blank';a.rel='noopener noreferrer';body.append(a)}
 function detail(c){chosen=c;const data=chapterData(c),body=modal.querySelector('.timelineDialogBody73');modal.querySelector('h2').textContent=data.era+' · '+data.title;body.replaceChildren();body.append(E('p','timelineMuseum73',data.place+' · '+data.museum),E('p','',data.status),E('p','',data.pages?.length?'原帖 '+data.pages.length+' 张 · 预设 '+data.style+' 书风 / 笔径 '+data.size+' / 缩放 '+data.zoom+'%':'此篇的真迹图尚未由管理员上传。馆藏说明可参考，临写须先取得对应碑帖图像。'));source(body,data);if(data.pages?.length){const go=E('button','timelinePrimary73','打开临帖 · '+data.pages.length+' 张');go.onclick=()=>{modal.close();openCopy(c).catch(err=>A.toast(err.message||'临帖打开失败'))};body.append(go)}if(!modal.open)modal.showModal()}
 async function openCopy(c){const data=chapterData(c),pages=data.pages;if(!pages?.length)throw Error('管理员尚未上传原帖组图');if(modal.open)modal.close();const entry=U.config.nav.find(n=>n.id==='copy');if(entry)await U.applyMode(entry);await CopyAlbums38.openPages55({id:'timeline73:'+c.id,title:data.title,pages:pages.map((image,i)=>({name:data.title+' · '+(i+1),image,workIds:[]}))});await A.configure47({preset:A.presets[data.style]?data.style:'zhang',size:Math.max(6,Math.min(1000,+data.size||350)),values:{zoom:String(+data.zoom||160),sceneChoice:'none',paperExtent:'fixed',opacity:'20',refFit:'contain'},focus:'start'});A.showWriter();}
 async function edit(c){chosen=c;const d=chapterData(c),body=modal.querySelector('.timelineDialogBody73');modal.querySelector('h2').textContent='维护 · '+c.title;body.replaceChildren();const fields={};for(const [key,label,type] of [['title','封面与帖名','text'],['place','国家与城市','text'],['museum','现存机构或版本','text'],['status','原件、摹本或亡佚说明','text'],['url','馆藏网址','url'],['size','笔径','number'],['zoom','页面缩放 %','number']]){const l=E('label','timelineField73',label),input=E('input');input.type=type;input.value=d[key]??'';if(type==='number'){input.min='20';input.max=key==='size'?'1000':'500'}l.append(input);body.append(l);fields[key]=input}
 const styleLabel=E('label','timelineField73','书风'),style=E('select');for(const [key,preset] of Object.entries(A.presets))style.add(new Option(preset.name.split('-')[0],key));style.value=A.presets[d.style]?d.style:'zhang';styleLabel.append(style);body.append(styleLabel);
 const tokenField=E('input');tokenField.type='password';tokenField.autocomplete='off';tokenField.placeholder=TimelineCloud74.hasToken()?'已在本页连接，可留空':'输入仅授权此仓库 Contents 写入的细粒度 GitHub 令牌';const tokenLabel=E('label','timelineField73','线上管理 · GitHub 临时令牌');tokenLabel.append(tokenField);body.append(tokenLabel,E('small','', '令牌只保存在本页内存，不写进作品、浏览器存储或代码仓库。'));const files=E('input');files.type='file';files.accept='image/jpeg,image/png,image/webp';files.multiple=true;const upload=E('label','timelineField73','碑帖组图 · 批量选取（每张最多 20 MB，最多 60 张）');upload.append(files);body.append(upload);
 const count=E('small','',d.pages?.length?'当前已存 '+d.pages.length+' 张；不选文件即保留原图。':'尚未上传图像');body.append(count);source(body,d);
 const actions=E('div','timelineEditorActions73'),save=E('button','timelinePrimary73','保存封面与预设'),remove=E('button','','移除已上传图像');actions.append(save,remove);body.append(actions);remove.onclick=async()=>{if(!U.isAdmin)return;try{if(tokenField.value){TimelineCloud74.connect(tokenField.value.trim());tokenField.value=''}const next=await TimelineCloud74.publish(c.id,{...d,pages:[]},[],v=>count.textContent=v);uploads.set(c.id,next);modal.close();render()}catch(e){count.textContent=e.message}};
 save.onclick=async()=>{if(!U.isAdmin)return;const f=[...files.files];if(f.length>60||f.some(x=>x.size>20e6)){count.textContent='一次最多60张，每张不超过20MB';return}const next={...d,...Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,k==='size'||k==='zoom'?+v.value:v.value.trim().slice(0,200)])),style:style.value};try{if(tokenField.value){TimelineCloud74.connect(tokenField.value.trim());tokenField.value=''}const local=f.length?f:Array.isArray(d.pages)?d.pages.filter(p=>p instanceof Blob):[];const published=await TimelineCloud74.publish(c.id,next,local,v=>count.textContent=v);uploads.set(c.id,published);modal.close();render()}catch(e){count.textContent=e.message||'线上上传失败，请重试'}};if(!modal.open)modal.showModal()}
 // One delegated handler covers the home and the in-editor copy shortcut, including admin renames.
 document.addEventListener('click',e=>{const button=e.target.closest('button');if(!button||!button.closest('#homeQuick47,#writerModes53')||button.textContent.trim()!=='临帖')return;e.preventDefault();e.stopImmediatePropagation();modal.querySelector('h2').textContent='择一帖，临其神';const body=modal.querySelector('.timelineDialogBody73');body.replaceChildren();const grid=E('div','timelinePicker73');for(const c of chapters)grid.append(card(c));body.append(E('p','','沿历史长卷挑选名帖。点封面查看原件与预设。'),grid);if(!modal.open)modal.showModal()},true);
 document.addEventListener('work-featured54',render);document.addEventListener('admin-unlocked53',load);document.addEventListener('timeline-cloud74',()=>{for(const c of chapters){const remote=TimelineCloud74.get(c.id);if(remote)uploads.set(c.id,remote)}render()});load();
 window.Timeline73={chapters,openCopy,refresh:render};
})();
