/* Curated historical labels. A location is shown only for a documented physical witness.
   Missing originals, copies and uncertain private holdings are explicitly distinguished. */
window.CalligraphyTimeline73=[
 ['oracle','殷商','甲骨文','甲骨','中国·河南安阳','多馆分藏；安阳殷墟博物馆展示出土甲骨','传世甲骨分藏多馆，非单一作品','https://www.anyang.gov.cn/','ouyang',320,170,'甲'],
 ['maogong','西周','毛公鼎','金文','中国·台北','国立故宫博物院','原器','https://www.npm.gov.tw/','yan',430,145,'鼎'],
 ['sanshi','西周','散氏盘','金文','中国·台北','国立故宫博物院','原器','https://digitalarchive.npm.gov.tw/opendata/Pub/Detail/1462?dep=U&mode=full','yan',420,145,'盤'],
 ['hezun','西周','何尊','金文','中国·宝鸡','宝鸡青铜器博物院','原器','https://wwj.baoji.gov.cn/col1892/col17273/202505/t20250512_1147496.html','yan',420,145,'中'],
 ['shizhoupian','西周','史籀篇','古籀','原书亡佚','无原件馆藏','仅见后世文献征引；并非可临的现存真迹','','ouyang',360,150,'籀'],
 ['wangziwu','东周·春秋','王子午鼎','楚系金文','中国·河南','出土一组七鼎；具体器物藏地待核','请以具体馆藏器号核对','', 'yan',390,150,'楚'],
 ['shigu','东周·战国','石鼓文','籀文','中国·北京','故宫博物院','原石；年代学界有不同看法','https://www.dpm.org.cn/collection/impres/234438.html','ouyang',420,140,'鼓'],
 ['yishan','秦','李斯·峄山碑','小篆','秦代原石亡佚','后世摹刻分藏各地','临帖应注明所用刻本，不称秦代原石','https://www.dpm.org.cn/','ouyang',350,160,'篆'],
 ['mawangdui','西汉','马王堆帛书','帛书','中国·长沙','湖南博物院','出土帛书多种，需按篇目选原件','https://www.hnmuseum.com/','ouyang',340,165,'帛'],
 ['juyan','西汉','居延汉简','简牍','中国·甘肃及台北','多馆分藏；选择具体简号后标馆藏','并非单一一件作品','', 'yan',400,150,'简'],
 ['caoquan','东汉','曹全碑','隶书','中国·西安','西安碑林博物馆','原碑','https://beilin-museum.com/','liu',430,140,'隶'],
 ['zhangzhi','东汉','张芝·冠军帖','草书','原迹不存','历代刻帖传本分藏','传张芝书，归属与原貌需注明','', 'zhang',280,200,'草'],
 ['xuanshi','三国·魏','钟繇·宣示表','楷书','原迹不存','后世摹本、刻本分藏','不将摹本标为三国真迹','', 'liu',380,160,'楷'],
 ['yuanshe','三国·蜀','诸葛亮·远涉帖','行草','原迹不存','传本版本待核','传诸葛亮书，作者归属待考','', 'zhang',310,175,'涉'],
 ['jijiuzhang','三国·吴','皇象·急就章','章草','原迹不存','后世刻本分藏','具体临摹版本由管理员注明','', 'zhang',350,170,'章'],
 ['pingfu','西晋','陆机·平复帖','章草','中国·北京','故宫博物院','传世墨迹','https://www.dpm.org.cn/collection/handwriting/234553.html','zhang',370,165,'平'],
 ['shengjiao','东晋书风·唐代刻石','怀仁集王羲之字·圣教序','行书','中国·西安','西安碑林博物馆','唐代集字刻碑，并非王羲之亲笔原帖','https://beilin-museum.com/','wang',350,175,'羲'],
 ['gushi','唐','张旭·古诗四帖','草书','中国·沈阳','辽宁省博物馆','传张旭书，归属有讨论','https://zhuanti.mct.gov.cn/lnsbwg2022.html','zhang',330,185,'旭'],
 ['yanqinli','唐','颜真卿·颜勤礼碑','楷书','中国·西安','西安碑林博物馆','原碑','https://beilin-museum.com/','yan',420,140,'颜'],
 ['jiucheng','唐','欧阳询·九成宫醴泉铭','楷书','中国·陕西麟游','九成宫遗址','原碑现存于遗址','', 'ouyang',370,160,'欧'],
 ['shupu','唐','孙过庭·书谱','草书','中国·台北','国立故宫博物院','传世墨迹卷','https://digitalarchive.npm.gov.tw/Collection/Detail/14900?dep=P','zhang',350,170,'譜'],
 ['zixu','唐','怀素·自叙帖','草书','中国·台北','国立故宫博物院','传世墨迹卷','https://digitalarchive.npm.gov.tw/Collection/Detail/14890?dep=P','huaisu',320,180,'素'],
 ['caoshuqianzi','宋','赵佶·草书千字文','草书','中国·沈阳','辽宁省博物馆','泥金云龙笺墨迹','https://zhuanti.mct.gov.cn/lnsbwg2022.html','zhang',340,175,'宋'],
 ['dizhu','宋','黄庭坚·砥柱铭','行书','私人藏家','现存私人收藏；馆藏未公开确认','请勿填写拍卖行作为现存馆','', 'huang',350,170,'黄'],
 ['hanshi','宋','苏轼·黄州寒食帖','行书','中国·台北','国立故宫博物院','传世墨迹','https://south.npm.gov.tw/ExhibitionsDetailC003110.aspx?Cond=4856521d-6e8e-4a08-94fb-7f0ae6ff4741&State=&appname=','su',360,160,'苏'],
 ['chibi','元','赵孟頫·前后赤壁赋','行书','中国·台北','国立故宫博物院','传世墨迹卷','https://digitalarchive.npm.gov.tw/Collection/Detail/373?dep=P','wang',350,165,'趙'],
 ['tengwang','明','祝允明·草书滕王阁序并诗','草书','中国·苏州','苏州博物馆','传世草书长卷','', 'zhang',330,175,'祝'],
 ['zhangbaoyi','清','王铎·赠张抱一草书诗卷','草书','馆藏待核','请以指定版本登记具体收藏','同题材传本信息需按实物核对','', 'wangduo',370,165,'铎'],
 ['dengqianzi','清','邓石如·千字文','篆书','版本待核','同题作品多本，需指定馆藏版本','不可把不同本子混作同一真迹','', 'ouyang',380,145,'邓'],
 ['yuyouren','民国','于右任·草书满江红','草书','版本待核','请管理员指定馆藏与具体墨迹','同词书写有不同作品','', 'zhang',340,180,'右'],
 ['qinling','当代','毛泽东·沁园春·雪','草书','手稿版本待核','请管理员指定所用手稿及收藏机构','作品原词与题写手迹须区分','', 'zhang',360,180,'雪']
].map(([id,era,title,script,place,museum,status,url,style,size,zoom,glyph],order)=>({id,era,title,script,place,museum,status,url,style,size,zoom,glyph,order}));
