/* Recoverable deletion; preserve identity and editable originals for 24 hours. */
(function(root){
 const DAY=86400000;
 function create({store,cloud,online=()=>navigator.onLine,now=()=>Date.now()}){
  const check=r=>{if(r.error)throw Error(r.error.message);return r.data},uid=()=>cloud?.user?.id||'guest',key=(owner,id)=>'trash144:'+owner+':'+id;
  const guard=owner=>{if(uid()!==owner)throw Error('账号已切换，请重新打开作品管理')};
  async function cancel(id,owner){for(const [k,j]of await store.entries('cloud-outbox101:'))if(j.id===id&&(!j.owner||j.owner===owner))await store.delete(k);await store.set('cloud-delete141:'+owner+':'+id,{at:now(),trash144:true})}
  async function moveLocal(id,owner,cloudRow=null){const record=await store.get(id);if(!record)return;guard(owner);if(record.cloud141?.owner&&record.cloud141.owner!==owner)throw Error('请登录作品所属账号');const thumbnail=await store.get(id+':thumb');await store.moveTrash144(id,key(owner,id),{record,thumbnail,cloudId:cloudRow?.id||record.cloud141?.id||null,owner,deleted:cloudRow?.deleted_at144?Date.parse(cloudRow.deleted_at144):now()});await cancel(id,owner);if(root.AnnotationApp?.getState().editingWork110?.id===id)root.AnnotationApp.setWorkIdentity128(null)}
  async function cloudRemove(row){const owner=uid();if(owner==='guest'||row.owner!==owner)throw Error('只能删除自己的作品');if(!online())throw Error('云端作品需要联网后移入回收站');const saved=check(await cloud.client.rpc('ink_trash_work144',{work_id:row.id}));guard(owner);for(const meta of await store.get('works-index')||[]){const record=await store.get(meta.id);if(record?.cloud141?.id===row.id&&record.cloud141.owner===owner||!record?.cloud141&&String(row.local_id).split('|').at(-1)===meta.id)await moveLocal(meta.id,owner,saved)}return saved}
  async function local(id){const owner=uid(),record=await store.get(id);if(!record)return;if(record.cloud141?.owner&&record.cloud141.owner!==owner)throw Error('请登录作品所属账号');if(cloud?.user){if(!online())throw Error('请联网后删除，以同步移入云端回收站');const row=await root.CloudDraft141.findLocal(id);guard(owner);if(row)await cloudRemove(row)}await moveLocal(id,owner)}
  async function cloudById(id){const owner=uid();const row=check(await cloud.client.from('ink_works').select('*').eq('id',id).eq('owner',owner).single());guard(owner);return cloudRemove(row)}
  async function purgeLocal(){const owner=uid();for(const [k,item]of await store.entries('trash144:'+owner+':'))if(now()-item.deleted>=DAY)await store.delete(k)}
  async function list(){await purgeLocal();const owner=uid(),locals=(await store.entries('trash144:'+owner+':')).map(([k,v])=>({...v,key:k,title:v.record.title}));let remote=[];if(owner!=='guest'&&online()){remote=check(await cloud.client.from('ink_works').select('id,title,owner,local_id,image_path,deleted_at144').eq('owner',owner).not('deleted_at144','is',null).gt('deleted_at144',new Date(now()-DAY).toISOString()).order('deleted_at144',{ascending:false}))||[];guard(owner)}const ids=new Set(locals.map(r=>r.cloudId));return [...locals,...remote.filter(r=>!ids.has(r.id)).map(r=>({owner,cloudId:r.id,title:r.title,deleted:Date.parse(r.deleted_at144),remote:r}))].sort((a,b)=>b.deleted-a.deleted)}
  async function restore(item){const owner=uid();guard(item.owner);if(now()-item.deleted>=DAY)throw Error('已超过24小时，作品无法恢复');let restored=null;if(item.cloudId){if(!online())throw Error('请联网后恢复云端作品');restored=check(await cloud.client.rpc('ink_restore_work144',{work_id:item.cloudId}));guard(owner)}if(item.record){const record={...item.record,thumbnail:item.thumbnail};if(restored){record.cloud141={...record.cloud141,updatedAt:restored.updated_at};if(record.draft?.editingWork110)record.draft.editingWork110.cloud141=record.cloud141;}await store.restoreTrash144(item.key,record);await store.delete('cloud-delete141:'+owner+':'+record.id)}else if(restored){const loaded=await root.CloudDraft141.load(restored);await store.delete('cloud-delete141:'+owner+':'+loaded.id);}return restored}
  return{local,cloud:cloudRemove,cloudById,list,restore,purgeLocal};
 }
 root.TrashService144={create,DAY};if(!root.document)return;
 (function init(){if(!root.AnnotationApp?.batchState144||!root.CloudDraft141||!root.InkCloud75?.client||!root.Revision111?.ready||!document.getElementById('cloudOnly111')){setTimeout(init,100);return}const A=AnnotationApp,$=id=>document.getElementById(id),C=InkCloud75,T=root.Trash144=create({store:DraftStore,cloud:C});let busy=false,renderGeneration=0;
 const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e},button=(text,fn)=>{const b=el('button',text);b.type='button';b.onclick=async()=>{if(busy)return;busy=true;b.disabled=true;try{await fn()}catch(e){A.toast(e.message)}finally{busy=false;b.disabled=false}};return b};
 const dialog=el('dialog',null,'trashDialog144'),head=el('header',null,'dialogHead'),body=el('section',null,'trashBody144');dialog.id='trashDialog144';head.append(el('h2','回收站'),button('×',()=>dialog.close()));dialog.append(head,el('p','删除后保留24小时，可恢复到原作品编号；到期自动彻底删除。'),body);document.body.append(dialog);
 async function refresh(){const run=++renderGeneration,owner=C.user?.id;body.replaceChildren(el('p','正在打开回收站…'));const items=await T.list();if(run!==renderGeneration||owner!==C.user?.id)return;body.replaceChildren();if(!items.length)body.append(el('p','回收站空空如也，好字都在书房里。'));for(const item of items){const card=el('article',null,'trashCard144');card.append(el('strong',item.title),el('small','剩余 '+Math.max(0,Math.ceil((86400000-Date.now()+item.deleted)/60000))+' 分钟'),button('恢复',async()=>{await T.restore(item);document.dispatchEvent(new Event('cloud-copies83'));await A.reloadWorks144();await refresh();A.toast('作品回来了，编号、原笔迹都在。')}));body.append(card)}}
 $('worksDialog').querySelector('.dialogHead').append(button('回收站',async()=>{dialog.showModal();await refresh()}));
 const tools=$('workBatchTools');for(const [label,action]of [['批量发布','publish'],['批量私藏','private'],['批量推荐','feature']]){const b=button(label,()=>batch(action));b.dataset.batch144=action;tools.append(b)}
 async function batch(action){if(!C.user)throw Error('请先登录');if(action==='feature'&&!C.isFounder132)throw Error('推荐由管理员维护');const owner=C.user.id,ids=A.selectedWorkIds();let done=0,fail=[];for(const id of ids){try{if(C.user?.id!==owner)throw Error('账号已切换');let row;if(id.startsWith('cloud144:'))row={id:id.slice(9)};else{const record=await DraftStore.get(id);if(record?.cloud141?.owner&&record.cloud141.owner!==owner)throw Error('作品属于另一账号');row=await CloudDraft141.findLocal(id);if(!row){const saved=await C.saveNow101(record,action!=='private',true);if(!saved)throw Error('原笔迹尚未同步，请稍后重试');row=await CloudDraft141.findLocal(id)}}if(!row)throw Error('作品未读取');const values=action==='feature'?{featured:true,published:true}:{published:action==='publish',...(action==='private'?{featured:false}:{})};const r=await C.client.from('ink_works').update(values).eq('id',row.id).eq('owner',owner).is('deleted_at144',null).select('id');if(r.error||!r.data?.length)throw Error(r.error?.message||'作品已删除');done++;A.selectWork144(id,false)}catch(e){fail.push(e.message)}}document.dispatchEvent(new Event('cloud-copies83'));document.dispatchEvent(new Event('work-featured54'));A.toast('已完成 '+done+' 幅'+(fail.length?'，'+fail.length+' 幅未完成：'+fail[0]:''));syncUI()}
 function syncUI(){const state=A.batchState144(),ids=new Set(A.selectedWorkIds());for(const b of tools.querySelectorAll('[data-batch144]')){b.hidden=!state.active||b.dataset.batch144==='feature'&&!C.isFounder132;b.disabled=busy||!ids.size}for(const card of $('cloudOnly111')?.querySelectorAll('[data-cloud-id144]')||[]){let pick=card.querySelector('.cloudPick144');if(!state.active){pick?.remove();continue}if(!pick){pick=el('input',null,'cloudPick144');pick.type='checkbox';pick.setAttribute('aria-label','选择 '+card.querySelector('strong')?.textContent);pick.onchange=()=>{A.selectWork144('cloud144:'+card.dataset.cloudId144,pick.checked);syncUI()};card.prepend(pick)}pick.checked=ids.has('cloud144:'+card.dataset.cloudId144);pick.disabled=busy}}
 tools.addEventListener('click',()=>setTimeout(syncUI,0));$('batchAll').addEventListener('click',()=>{for(const card of $('cloudOnly111').querySelectorAll('[data-cloud-id144]'))if(!card.hidden)A.selectWork144('cloud144:'+card.dataset.cloudId144,true);syncUI()});$('batchNone').addEventListener('click',()=>{for(const id of A.selectedWorkIds())A.selectWork144(id,false);syncUI()});$('worksGrid').addEventListener('change',syncUI);new MutationObserver(syncUI).observe($('cloudOnly111'),{childList:true});document.addEventListener('cloud-copies83',()=>{syncUI();T.purgeLocal().catch(()=>{})});setInterval(()=>T.purgeLocal().catch(()=>{}),60000);T.purgeLocal().catch(()=>{});syncUI();
 })();
})(typeof window==='undefined'?globalThis:window);
