/* Four handwritten type blocks: editable Blender scene and printer-ready STL package. */
(function(){
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function transformed(st){const g=st.geometry,cs=Math.cos(g?.r||0),sn=Math.sin(g?.r||0),k=g?.k??1;return st.points.map(p=>({x:(g?.x||0)+k*(p.x*cs-p.y*sn),y:(g?.y||0)+k*(p.x*sn+p.y*cs),t:p.t,pressure:p.pressure}))}
function groups(strokes,direction='vertical'){
 const axis=direction==='vertical'?'y':'x',ordered=strokes.filter(s=>s.points?.length).map(st=>{const pts=transformed(st);return{st,pts,position:pts.reduce((n,p)=>n+p[axis],0)/pts.length}}).sort((a,b)=>a.position-b.position);
 if(ordered.length<4)throw Error('至少需要四笔，并请按「今日亲笔」四字顺序书写');
 let centers=[0,1,2,3].map(i=>ordered[Math.min(ordered.length-1,Math.floor((i+.5)*ordered.length/4))].position);
 for(let pass=0;pass<12;pass++){const bins=[[],[],[],[]];for(const item of ordered){let best=0;for(let i=1;i<4;i++)if(Math.abs(item.position-centers[i])<Math.abs(item.position-centers[best]))best=i;bins[best].push(item)}centers=bins.map((bin,i)=>bin.length?bin.reduce((n,p)=>n+p.position,0)/bin.length:centers[i]);}
 const bins=[[],[],[],[]];for(const item of ordered){let best=0;for(let i=1;i<4;i++)if(Math.abs(item.position-centers[i])<Math.abs(item.position-centers[best]))best=i;bins[best].push(item)}if(bins.some(bin=>!bin.length))throw Error('四个字的位置无法区分，请在预览中分开书写');return bins
}
function rasterize(group,brush,res=256){const pts=group.flatMap(o=>o.pts),minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y)),factor=.78/Math.max(.16,maxX-minX,maxY-minY),dx=.5-(maxX+minX)*factor/2,dy=.5-(maxY+minY)*factor/2,c=document.createElement('canvas');c.width=c.height=res;const ctx=c.getContext('2d');for(const o of group){const st={...o.st,geometry:undefined,points:o.pts.map(p=>({...p,x:p.x*factor+dx,y:p.y*factor+dy})),settings:{...o.st.settings,size:clamp((o.st.settings?.size||30)*factor,2,180),color:'#050505'},done:true};brush.render(st,ctx,res,res)}const pixels=ctx.getImageData(0,0,res,res).data,mask=new Uint8Array(res*res);for(let i=0;i<mask.length;i++)mask[i]=pixels[i*4+3]>45?1:0;return{canvas:c,mask,res}}
function reliefMesh(width,height,nx,ny,top,bottom){const facets=[],at=(x,y,z)=>[x*width/nx,y*height/ny,z],quad=(a,b,c,d)=>{facets.push([a,b,c],[a,c,d])};for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){quad(at(x,y,top(x,y)),at(x+1,y,top(x+1,y)),at(x+1,y+1,top(x+1,y+1)),at(x,y+1,top(x,y+1)));quad(at(x,y+1,bottom(x,y+1)),at(x+1,y+1,bottom(x+1,y+1)),at(x+1,y,bottom(x+1,y)),at(x,y,bottom(x,y)))}for(let x=0;x<nx;x++){quad(at(x,0,bottom(x,0)),at(x+1,0,bottom(x+1,0)),at(x+1,0,top(x+1,0)),at(x,0,top(x,0)));quad(at(x+1,ny,bottom(x+1,ny)),at(x,ny,bottom(x,ny)),at(x,ny,top(x,ny)),at(x+1,ny,top(x+1,ny)))}for(let y=0;y<ny;y++){quad(at(0,y,bottom(0,y)),at(0,y+1,bottom(0,y+1)),at(0,y+1,top(0,y+1)),at(0,y,top(0,y)));quad(at(nx,y+1,bottom(nx,y+1)),at(nx,y,bottom(nx,y)),at(nx,y,top(nx,y)),at(nx,y+1,top(nx,y+1)))}return facets}
function binaryStl(facets,name){const out=new ArrayBuffer(84+facets.length*50),v=new DataView(out);new TextEncoder().encode(name).slice(0,80).forEach((n,i)=>v.setUint8(i,n));v.setUint32(80,facets.length,true);facets.forEach((triangle,i)=>{let p=84+i*50;const [a,b,c]=triangle,u=b.map((n,j)=>n-a[j]),w=c.map((n,j)=>n-a[j]),normal=[u[1]*w[2]-u[2]*w[1],u[2]*w[0]-u[0]*w[2],u[0]*w[1]-u[1]*w[0]],len=Math.hypot(...normal)||1;for(const n of normal)v.setFloat32(p,(n/len),true),p+=4;for(const point of triangle)for(const n of point)v.setFloat32(p,n,true),p+=4;v.setUint16(p,0,true)});return new Blob([out],{type:'model/stl'})}
function block(mask,res,{size=22,thickness=8,recess=.8,emboss=.8,pitch=.25}={}){const n=Math.round(size/pitch),inside=(x,y)=>mask[clamp(Math.floor(y/n*res),0,res-1)*res+clamp(Math.floor(x/n*res),0,res-1)]===1,top=(x,y)=>thickness-(inside(x,y)?recess:0),bottom=(x,y)=>inside(x,y)?-emboss:0;return binaryStl(reliefMesh(size,size,n,n,top,bottom),'handwritten-type')}
function box({size=22,thickness=8,emboss=.8,clearance=1.2,wall=2,floor=2,pitch=.5}={}){const pocket=size+clearance,total=2*pocket+3*wall,depth=thickness+emboss+1.2,height=floor+depth,n=Math.round(total/pitch),top=(x,y)=>{const xx=x*total/n,yy=y*total/n;for(let row=0;row<2;row++)for(let col=0;col<2;col++){const left=wall+col*(pocket+wall),bottom=wall+row*(pocket+wall);if(xx>left&&xx<left+pocket&&yy>bottom&&yy<bottom+pocket)return floor}return height};return binaryStl(reliefMesh(total,total,n,n,top,()=>0),'four-type-box')}
const blender=`# 在 Blender 的「脚本」工作区打开并运行；STL 文件与本脚本放在同一文件夹。\nimport bpy, os\nfrom math import radians\nbpy.ops.wm.read_factory_settings(use_empty=True)\nbpy.context.scene.unit_settings.system = 'METRIC'\nbpy.context.scene.unit_settings.scale_length = 0.001\nfolder = os.path.dirname(bpy.context.space_data.text.filepath) if getattr(bpy.context.space_data, 'text', None) else os.getcwd()\nfor i, glyph in enumerate('今日亲笔'):\n    name = f'{i+1}-{glyph}-正面阴文-背面镜像阳文.stl'\n    path = os.path.join(folder, name)\n    if hasattr(bpy.ops.wm, 'stl_import'):\n        bpy.ops.wm.stl_import(filepath=path)\n    else:\n        bpy.ops.import_mesh.stl(filepath=path)\n    obj = bpy.context.selected_objects[0]\n    obj.name = glyph + '｜双面活字'\n    obj.location = ((i % 2) * 28, (i // 2) * 28, 1)\npath = os.path.join(folder, '四字收纳盒.stl')\nif hasattr(bpy.ops.wm, 'stl_import'):\n    bpy.ops.wm.stl_import(filepath=path)\nelse:\n    bpy.ops.import_mesh.stl(filepath=path)\nbox = bpy.context.selected_objects[0]\nbox.name = '四字收纳盒'\nbox.location = (65, 0, 0)\nbpy.ops.wm.save_as_mainfile(filepath=os.path.join(folder, '今日亲笔-活字设计.blend'))\n# 在 Blender 调整模型后分别导出 STL；用拓竹工作室导入并检查切片与支撑。\n`;
window.Type3D122={groups,rasterize,reliefMesh,binaryStl,block,box,blender};
(function init(){if(!window.AnnotationApp?.ready||!window.PreviewPaper120||!window.WorkZip||!window.ParticleBrush){setTimeout(init,80);return}const A=AnnotationApp,dialog=document.getElementById('bigDialog62'),host=dialog?.querySelector('.dialogBody');if(!host)return;const section=document.createElement('section');section.id='type3d122';section.innerHTML='<h3>毕昇活字 · 3D</h3><p>把当前手写的「今日亲笔」做成四枚双面活字：正面阴文，背面镜像阳文；附四格收纳盒。</p><label>书写方向<select id="typeDirection122"><option value="vertical">从上到下</option><option value="horizontal">从左到右</option></select></label><label>活字边长（毫米）<input id="typeSize122" type="number" min="15" max="40" value="22"></label><button type="button" id="typeExport122">生成 Blender 与拓竹模型包</button><p id="typeStatus122" role="status">先写完四个字，再生成模型。下载 ZIP 后运行其中的 Blender 脚本，或把 STL 导入拓竹工作室。</p>';host.append(section);document.getElementById('typeExport122').onclick=async()=>{const button=document.getElementById('typeExport122'),status=document.getElementById('typeStatus122');button.disabled=true;status.textContent='正在从原笔迹生成四枚活字与收纳盒…';try{const state=A.getState(),bins=groups(state.flow.strokes,document.getElementById('typeDirection122').value),size=clamp(+document.getElementById('typeSize122').value||22,15,40),options={size},entries=[];for(let i=0;i<4;i++){const glyph='今日亲笔'[i],ink=rasterize(bins[i],ParticleBrush);entries.push({name:`${i+1}-${glyph}-正面阴文-背面镜像阳文.stl`,blob:block(ink.mask,ink.res,options)})}entries.push({name:'四字收纳盒.stl',blob:box(options)},{name:'在Blender中运行.py',blob:new Blob([blender],{type:'text/x-python'})},{name:'打印说明.txt',blob:new Blob(['今日亲笔四枚活字：正面为正常阅读方向的阴文，背面翻转观察为镜像阳文。\n请先在 Blender 检查每字分组和尺寸，再用拓竹工作室导入 STL、摆放、切片，检查薄壁与悬垂支撑后发送到已连接的打印机。\n活字与盒子请分盘或调整排布打印。\n'],{type:'text/plain'})});const archive=await WorkZip(entries),url=URL.createObjectURL(archive),a=document.createElement('a');a.href=url;a.download='今日亲笔-双面活字与收纳盒.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);status.textContent='模型包已生成。请在 Blender 检查字形，再导入拓竹工作室切片。'}catch(error){status.textContent=error.message||'模型生成失败，请重试'}finally{button.disabled=false}}})();
})();
