(function(root){
 function timestamp(value){if(typeof value==='number')return Number.isFinite(value)?value:0;if(!value)return 0;const n=Date.parse(String(value).replace(/年|月/g,'/').replace(/日/g,''));return Number.isFinite(n)?n:0}
 function time(work){return timestamp(work?.updated)||timestamp(work?.updated_at)||timestamp(work?.created)||timestamp(work?.date)}
 function relative(ms,now=Date.now()){if(!ms)return'书写时间待补';const elapsed=Math.max(0,now-ms),d=new Date(ms),n=new Date(now);if(elapsed<60000)return'刚刚';if(elapsed<3600000)return Math.floor(elapsed/60000)+' 分钟前';if(elapsed<86400000&&d.toDateString()===n.toDateString())return Math.floor(elapsed/3600000)+' 小时前';const yesterday=new Date(now);yesterday.setDate(yesterday.getDate()-1);if(d.toDateString()===yesterday.toDateString())return'昨天 '+d.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});return d.toLocaleString('zh-CN',{year:d.getFullYear()===n.getFullYear()?undefined:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false})}
 function group(ms,now=Date.now()){if(!ms)return'早期作品';const d=new Date(ms),n=new Date(now),y=new Date(now);y.setDate(y.getDate()-1);return d.toDateString()===n.toDateString()?'今天':d.toDateString()===y.toDateString()?'昨天':d.getFullYear()+' 年 '+(d.getMonth()+1)+' 月'}
 root.WorkTime181={timestamp,time,relative,group};if(!root.document)return;
 function init(){const grid=document.getElementById('worksGrid'),cloud=document.getElementById('cloudOnly111');if(!root.Revision161?.ready||!grid||!cloud){setTimeout(init,80);return}const wrap=document.createElement('section');wrap.className='chronology181';grid.before(wrap);wrap.append(grid,cloud);let queued=false,flight=false;
 async function paint(){queued=false;if(flight)return;flight=true;try{const index=await DraftStore.get('works-index')||[],meta=new Map(index.map(w=>[w.id,w]));const cards=[...grid.querySelectorAll('.workCard'),...cloud.querySelectorAll('.cloudWork75')];const rows=cards.map(card=>({card,ms:Number(card.dataset.workTime181)||time(meta.get(card.dataset.workId))})).sort((a,b)=>b.ms-a.ms);const headings=[];let last='',order=0;for(const{card,ms}of rows){const text=group(ms);if(!card.hidden&&last!==text){const h=document.createElement('h3');h.className='workDate181';h.textContent=text;h.style.order=String(order++);headings.push(h);last=text}const style=String(order++);if(card.style.order!==style)card.style.order=style;let stamp=card.querySelector('.workTime181');if(!stamp){stamp=document.createElement('time');stamp.className='workTime181';card.append(stamp)}const label='书写于 '+relative(ms);if(stamp.textContent!==label)stamp.textContent=label;if(ms)stamp.dateTime=new Date(ms).toISOString();}wrap.querySelectorAll(':scope>.workDate181').forEach(h=>h.remove());wrap.append(...headings);}finally{flight=false}}
 function schedule(){if(queued||flight)return;queued=true;requestAnimationFrame(paint)}new MutationObserver(schedule).observe(grid,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden']});new MutationObserver(schedule).observe(cloud,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden']});document.getElementById('worksDialog').addEventListener('toggle',schedule);document.addEventListener('work-albums-updated84',schedule);schedule();}
 init();
})(typeof window==='undefined'?globalThis:window);
