/* V87: concise work title, no date/time, automatic city detection with timezone fallback. */
(function(root){
 function dateOnly(value){const date=new Date(value||Date.now());if(Number.isNaN(date.getTime()))return '';const parts=new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date),get=type=>parts.find(p=>p.type===type)?.value;return [get('year'),get('month'),get('day')].join('.')}
 function quote(title=''){const bracket=/写【([^】]+)】/.exec(title);if(bracket){const parts=bracket[1].split('·');return {author:parts.length>1?parts.shift().trim():'',title:parts.join('·').trim()}}const modern=/写《([^》]+)》/.exec(title);if(modern)return{author:'',title:modern[1].trim()};const old=/写\s*(.+?)《([^》]+)》/.exec(title);return old?{author:old[1].trim(),title:old[2].trim()}:{author:'',title:''}}
 function owner(title=''){return /^(.+?)\s*·\s*\d{4}[./-]\d{1,2}[./-]\d{1,2}\s*写【/.exec(title)?.[1]?.trim()||/^(.+?)\s+写《/.exec(title)?.[1]?.trim()||''}
 function day(title='',fallback){const match=/(\d{4})[./-](\d{1,2})[./-](\d{1,2})/.exec(title);return match?[match[1],match[2].padStart(2,'0'),match[3].padStart(2,'0')].join('.'):dateOnly(fallback)}
 const cityByZone={'Asia/Kuala_Lumpur':'吉隆坡','Asia/Shanghai':'上海','Asia/Hong_Kong':'香港','Asia/Singapore':'新加坡','Asia/Tokyo':'东京','Asia/Seoul':'首尔','Asia/Taipei':'台北','Europe/London':'伦敦','Europe/Paris':'巴黎','America/New_York':'纽约','America/Los_Angeles':'洛杉矶','Australia/Sydney':'悉尼'};
 let detecting=false;
 function fallbackCity(){try{const saved=localStorage.getItem('iinnkk.city87');if(saved)return saved}catch{}const zone=Intl.DateTimeFormat().resolvedOptions().timeZone||'';return cityByZone[zone]||zone.split('/').pop()?.replaceAll('_',' ')||'此地'}
 function city(){return fallbackCity()}
 function detectCity(){if(detecting||typeof navigator==='undefined'||!navigator.geolocation)return Promise.resolve(city());detecting=true;return new Promise(resolve=>navigator.geolocation.getCurrentPosition(async pos=>{let name='';try{const {latitude,longitude}=pos.coords;const res=await fetch('https://nominatim.openstreetmap.org/reverse?format=jsonv2&zoom=10&accept-language=zh-CN&lat='+encodeURIComponent(latitude)+'&lon='+encodeURIComponent(longitude),{headers:{Accept:'application/json'}});if(res.ok){const j=await res.json();const a=j.address||{};name=a.city||a.town||a.municipality||a.county||a.state_district||''}}catch{}if(name){try{localStorage.setItem('iinnkk.city87',name)}catch{}document.dispatchEvent(new CustomEvent('work-city87',{detail:name}))}detecting=false;resolve(name||city())},()=>{detecting=false;resolve(city())},{enableHighAccuracy:false,timeout:4500,maximumAge:86400000}))}
 function format(name,title,created,author='',work='',place=''){const q=quote(title);author=author||q.author;work=work||q.title;const subject=work?[author,work].filter(Boolean).join('·'):String(title||'亲笔真迹').replace(/^亲笔真迹\s*·\s*.+$/,'随手书写');return (name||owner(title)||'亲笔书家')+' 写《'+subject+'》于 '+(place||city())}
 root.WorkMeta84={dateOnly,quote,owner,day,city,detectCity,format};
})(typeof window==='undefined'?globalThis:window);
