(function init(){if(!window.AnnotationApp?.ready){setTimeout(init,40);return}const $=id=>document.getElementById(id);const tracks=[{"key": "strauss", "title": "施特劳斯 · 蓝色多瑙河", "artist": "United States Marine Band", "license": "美国联邦政府作品 · 公有领域", "licenseUrl": "https://commons.wikimedia.org/wiki/Template:PD-USGov-Military-Marines", "source": "https://commons.wikimedia.org/wiki/File:\"An der schönen, blauen Donau\" performed by the U.S. Marine Band.flac"},{"key": "mozart", "title": "莫扎特 · G大调弦乐小夜曲·快板", "artist": "Advent Chamber Orchestra；Roxanna Pavel Goldstein（音乐指导）", "license": "CC BY-SA 2.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0", "source": "https://commons.wikimedia.org/wiki/File:Mozart - Eine kleine Nachtmusik - 1. Allegro.ogg"},{"key": "chopin", "title": "肖邦 · 降E大调夜曲 Op.9 No.2", "artist": "Beeswaxcandle at English Wikisource and Londonjackbooks at English Wikisource", "license": "CC BY-SA 3.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0", "source": "https://commons.wikimedia.org/wiki/File:Chopin Nocturne Op 9 No 2.ogg"},
{key:'guqin',title:'阳关三叠 · 古琴',artist:'Charlie Huang',license:'CC BY-SA 3.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/3.0/',source:'https://commons.wikimedia.org/wiki/File:Guqin-Yangguan_Sandie.ogg'},
{key:'fisher',title:'醉渔唱晚 · 古琴',artist:'Charlie Huang',license:'CC BY-SA 3.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/3.0/',source:'https://commons.wikimedia.org/wiki/File:Guqin-Zuiyu_Changwan.ogg'},
{key:'spring',title:'维瓦尔第 · 四季·春·广板',artist:'John Harrison（小提琴）；Robert Turizziani（指挥）；Wichita State University Chamber Players',license:'CC BY-SA 4.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/',source:'https://commons.wikimedia.org/wiki/File:Vivaldi_-_Four_Seasons_1_Spring_mvt_2_Largo_-_John_Harrison_violin.oga'},
{key:'bach',title:'巴赫 · 第一大提琴组曲·前奏曲',artist:'John Michel（大提琴）',license:'CC BY-SA 3.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/3.0/',source:'https://commons.wikimedia.org/wiki/File:JOHN_MICHEL_CELLO-J_S_BACH_CELLO_SUITE_1_in_G_Prelude.ogg'}];
const box=document.createElement('section');box.id='writingMusic';box.innerHTML='<h3>伴写音乐</h3><label>选择音乐<select id="writingTrack"></select></label><div class="musicActions"><button id="musicPlay">播放</button><button id="musicStop">暂停</button><label>音量<input id="musicVolume" type="range" min="0" max="100" value="25"></label></div><p id="musicCredit" class="note"></p><p class="note">广陵散、高山流水、笑傲江湖、马友友演奏版可从下方导入你的音频。内置曲目为标明演奏者的开放授权录音，按需加载。伴写音乐不自动混入过程视频，视频配乐可单独设置。</p><label>我的伴写音乐<input id="writingAudio" type="file" accept="audio/*"></label><p id="musicStatus" role="status"></p>';$('paperDialog').querySelector('.dialogBody').append(box);const quick=document.createElement('button');quick.id='musicSettings';quick.textContent='伴写音乐';quick.onclick=()=>{AnnotationApp.openDialog('paperDialog');box.scrollIntoView({block:'center'})};$('quickCompose').append(quick);const select=$('writingTrack');for(const item of tracks)select.add(new Option(item.title,item.key));const audio=new Audio();audio.preload='none';audio.loop=true;audio.volume=.25;let custom=null,customURL='',playingRequest=0;
function credit(){const item=tracks.find(x=>x.key===select.value),el=$('musicCredit');el.textContent='';if(item){el.append(document.createTextNode(item.artist+' · '));const a=document.createElement('a');a.href=item.source;a.target='_blank';a.rel='noopener';a.textContent='录音来源';const l=a.cloneNode();l.href=item.licenseUrl;l.textContent=item.license;el.append(a,document.createTextNode(' · '),l,document.createTextNode(' · MP3转码，未改编'))}else el.textContent='我的本机音频'}
async function play(){const request=++playingRequest;audio.pause();const key=select.value;audio.src=key==='custom'?customURL:'music/'+key+'.mp3';if(!audio.src)return;$('musicStatus').textContent='正在加载…';try{await audio.play();if(request!==playingRequest)return;quick.textContent='♫ '+(tracks.find(x=>x.key===key)?.title||'我的音乐');$('musicStatus').textContent='正在播放';await DraftStore.set('annotation.music.preference',{key,volume:audio.volume})}catch{if(request===playingRequest)$('musicStatus').textContent='暂未播放，请点击播放重试。'}}
function pause(){playingRequest++;audio.pause();quick.textContent='伴写音乐';$('musicStatus').textContent='已暂停'}$('musicPlay').onclick=play;$('musicStop').onclick=pause;select.onchange=()=>{const was=!audio.paused;credit();if(was)play()};$('musicVolume').oninput=e=>{audio.volume=+e.target.value/100;DraftStore.set('annotation.music.preference',{key:select.value,volume:audio.volume}).catch(()=>{})};$('writingAudio').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>40*1024*1024){$('musicStatus').textContent='请选择40MB以内的音频';return}pause();try{await DraftStore.set('annotation.music.custom',{blob:f,name:f.name});setCustom(f);select.value='custom';credit();$('musicStatus').textContent='已保存到本机，点击播放'}catch{$('musicStatus').textContent='本机空间不足，音频未保存'}};
function setCustom(file){custom=file;if(customURL)URL.revokeObjectURL(customURL);customURL=URL.createObjectURL(file);let opt=[...select.options].find(x=>x.value==='custom');if(!opt){opt=new Option('我的音乐','custom');select.add(opt)}opt.textContent='我的音乐 · '+(file.name||'本机音频')}
Promise.all([DraftStore.get('annotation.music.preference'),DraftStore.get('annotation.music.custom')]).then(([pref,own])=>{if(own?.blob)setCustom(own.blob);if(pref){if([...select.options].some(o=>o.value===pref.key))select.value=pref.key;audio.volume=Math.max(0,Math.min(1,pref.volume??.25));$('musicVolume').value=Math.round(audio.volume*100)}credit()}).catch(credit);credit();document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});window.WritingMusic={tracks,play,pause,audio};})();
