import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync('cloud-drafts141.js','utf8');
const env={Blob,Response,CompressionStream,DecompressionStream,Uint8Array,console};
vm.runInNewContext(fs.readFileSync('cloud-draft-codec141.js','utf8'),env);
vm.runInNewContext(source,env);
const codec=env.DraftCodec141;
function harness(confirm=()=>false){
 const records=new Map(),objects=new Map(),rows=new Map();let serial=0,deleteError=false,conflict=false;
 const store={get:async k=>records.get(k),set:async(k,v)=>records.set(k,structuredClone(v)),delete:async k=>records.delete(k),saveWork:async r=>records.set(r.id,structuredClone(r)),entries:async p=>[...records].filter(([k])=>k.startsWith(p))};
 const storage={from:bucket=>({upload:async(path,blob)=>{objects.set(bucket+':'+path,blob);return{data:{path}}},download:async path=>objects.has(bucket+':'+path)?{data:objects.get(bucket+':'+path)}:{error:{message:'missing private file'}},remove:async paths=>{paths.forEach(p=>objects.delete(bucket+':'+p));return{data:paths}}})};
 function query(){let op='select',values,filters=[];const q={select(){return q},is(k,v){filters.push(r=>(r[k]??null)===v);return q},order(){return q},limit(){return q},neq(k,v){filters.push(r=>r[k]!==v);return q},eq(k,v){filters.push(r=>r[k]===v);return q},like(k,v){filters.push(r=>String(r[k]).endsWith(v.slice(1)));return q},update(v){op='update';values=v;return q},insert(v){op='insert';values=v;return q},delete(){op='delete';return q},maybeSingle:()=>run(true),single:()=>run(true),then(a,b){return run(false).then(a,b)}};
 async function run(single){let result=[...rows.values()].filter(r=>filters.every(f=>f(r)));if(op==='delete'){if(deleteError)return{error:{message:'delete denied'}};result.forEach(r=>rows.delete(r.id))}if(op==='update'){if(conflict)result=[];else result=result.map(r=>{const n={...r,...values};rows.set(r.id,n);return n})}if(op==='insert'){const row={...values,id:'cloud-'+(++serial)};rows.set(row.id,row);result=[row]}return{data:single?result[0]||null:result}}
 return q}
 const cloud={user:{id:'owner'},cloudLocalId:id=>'copy:book|'+id,client:{storage,from:query}},app={editSavedWork:async id=>{app.edited=id;return true},toast(){}};
 const service=env.CloudDraftService141.create({cloud,store,codec,app,confirm,online:()=>true,uuid:()=> 'revision-'+(++serial)});
 const record={sharedRoom142:'test-room',id:'work:1',title:'敬源 临写 赵孟頫 赤壁赋',created:1,draft:{flow:{strokes:[{settings:{size:15},points:[{x:.2,y:.3,p:.4,t:123}],geometry:{x:1,y:2,k:.5}}]},brush:{size:37},photos:[],values:{zoom:'500'}},blob:new Blob(['image'])};
 const upload=r=>service.upload(r,{local_id:cloud.cloudLocalId(r.id),title:r.title,image:r.blob,published:false});
 return{records,objects,rows,store,cloud,service,record,upload,app,setDeleteError:v=>deleteError=v,setConflict:v=>conflict=v};
}
test('gzip draft roundtrip preserves exact pressure, geometry, seals, zoom and diameter',async()=>{const h=harness(),value={version:141,id:h.record.id,draft:{...h.record.draft,extraSeals:[{text:'亲笔',x:.33333333333333}]}};const packed=await codec.pack(value);assert.equal(packed.extension,'json.gz');assert.deepEqual(JSON.parse(JSON.stringify(await codec.unpack(packed.blob))),value)});
test('another device with empty local storage loads cloud strokes and edits the same work ID',async()=>{const h=harness();await h.store.saveWork(h.record);await h.upload(h.record);const row=[...h.rows.values()][0];h.records.clear();const restored=await h.service.edit(row);assert.equal(h.app.edited,'work:1');assert.equal(restored.draft.brush.size,37);assert.equal(restored.draft.flow.strokes[0].points[0].p,.4);restored.draft.flow.strokes.push({points:[]});await h.upload(restored);assert.equal(h.rows.size,1);assert.equal([...h.rows.values()][0].id,row.id);assert.equal([...h.rows.values()][0].local_id,'copy:book|work:1');assert.equal(h.objects.size,2,'obsolete revisions are cleaned only after pointer commit')});
test('stale device and conditional-update race cannot overwrite newer original strokes',async()=>{const h=harness();await h.upload(h.record);const row=[...h.rows.values()][0];h.rows.set(row.id,{...row,updated_at:'2099-01-01T00:00:00.000Z'});await assert.rejects(h.upload(h.record),/较新原笔迹/);assert.equal(h.objects.size,2);h.record.cloud141.updatedAt='2099-01-01T00:00:00.000Z';h.setConflict(true);await assert.rejects(h.upload(h.record),/另一设备/);assert.equal(h.objects.size,2);assert.equal(h.rows.get(row.id).draft_path,row.draft_path)});
test('other accounts cannot read, edit, delete or upload a bound original',async()=>{const h=harness();await h.upload(h.record);const row=[...h.rows.values()][0];h.cloud.user={id:'other'};await assert.rejects(h.service.load(row),/自己的作品/);await assert.rejects(h.service.remove(row),/自己的作品/);await assert.rejects(h.upload(h.record),/另一账号/);assert.equal(h.rows.size,1)});
test('switching accounts while preparing a first image cannot upload an unbound draft to the new account',async()=>{const h=harness();h.cloud.user={id:'other'};await assert.rejects(h.service.upload(h.record,{owner:'owner',local_id:'work:1',title:'旧账号草稿',image:h.record.blob}),/账号已切换/);assert.equal(h.rows.size,0);assert.equal(h.objects.size,0)});
test('cloud delete removes private strokes, cancels outbox and prevents queued resurrection',async()=>{const h=harness();await h.upload(h.record);await h.store.set('cloud-outbox101:owner:work:1',{owner:'owner',id:'work:1'});const id=await h.service.remove([...h.rows.values()][0]);assert.equal(id,'work:1');assert.equal(h.rows.size,0);assert.equal(h.objects.size,0);assert.equal((await h.store.entries('cloud-outbox101:')).length,0);assert.equal((await h.upload(h.record)).deleted,true);h.records.clear();await assert.rejects(h.upload(h.record),/已被删除/)});
test('failed deletion clears tombstone without deleting local or remote original',async()=>{const h=harness();await h.store.saveWork(h.record);await h.upload(h.record);h.setDeleteError(true);await assert.rejects(h.service.deleteLocal(h.record.id),/delete denied/);assert.equal(await h.service.deleted(h.record,'owner'),false);assert.equal(h.rows.size,1);assert.ok(await h.store.get(h.record.id))});
test('old image-only work remains loadable; private draft read failure never silently flattens strokes',async()=>{const h=harness();const row={id:'legacy',owner:'owner',local_id:'old:1',image_path:'owner/old.jpg',title:'旧作',updated_at:'2020-01-01'};h.rows.set(row.id,row);h.objects.set('ink-works:'+row.image_path,new Blob(['legacy']));const old=await h.service.load(row);assert.equal(old.draft,null);assert.equal(old.id,'old:1');h.rows.set(row.id,{...row,draft_path:'owner/missing.json.gz'});await assert.rejects(h.service.load(row),/missing private file/);assert.equal((await h.store.get('old:1')).draft,null)});
test('pending local changes block a cloud download that would overwrite them',async()=>{const h=harness();await h.store.saveWork(h.record);await h.upload(h.record);await h.store.set('cloud-outbox101:owner:work:1',{owner:'owner',id:'work:1'});await assert.rejects(h.service.load([...h.rows.values()][0]),/待同步修改/);assert.equal((await h.store.get('work:1')).draft.brush.size,37)});
test('autosave queued before first upload acknowledgement can update the same session revision',async()=>{const h=harness(),queued=structuredClone(h.record);await h.upload(h.record);queued.draft.brush.size=49;await h.upload(queued);assert.equal(h.rows.size,1);assert.equal(queued.cloud141.id,h.record.cloud141.id)});
test('old duplicate rows sharing one image do not lose that image when one record is upgraded or deleted',async()=>{const h=harness(),path='owner/shared-old.jpg';h.objects.set('ink-works:'+path,new Blob(['shared']));h.rows.set('old-one',{id:'old-one',owner:'owner',local_id:'copy:book|work:1',image_path:path,updated_at:'2020-01-01'});h.rows.set('old-two',{id:'old-two',owner:'owner',local_id:'other-book|work:1',image_path:path,updated_at:'2020-01-01'});await h.upload(h.record);assert.ok(h.objects.has('ink-works:'+path));await h.service.remove(h.rows.get('old-two'));assert.ok(h.rows.has('old-one'));assert.ok(h.objects.has('ink-drafts:'+h.rows.get('old-one').draft_path));assert.equal(h.objects.has('ink-works:'+path),false)});
test('cloud edit resolves a pending conflict only after explicit consent and a separate local-stroke backup',async()=>{const h=harness(()=>true);await h.store.saveWork(h.record);await h.upload(h.record);const modified=await h.store.get(h.record.id);modified.draft.brush.size=72;await h.store.set(modified.id,modified);await h.store.set('cloud-outbox101:owner:work:1',{owner:'owner',id:'work:1'});const edited=await h.service.edit([...h.rows.values()][0]);const backup=[...h.records.values()].find(r=>r?.title?.endsWith('本机备份'));assert.ok(backup);assert.equal(backup.draft.brush.size,72);assert.equal(backup.cloud141,null);assert.equal(edited.draft.brush.size,37);assert.equal((await h.store.entries('cloud-outbox101:')).length,0)});
test('legacy works sharing a native ID remain separately editable and delete does not target the other local work',async()=>{const h=harness();await h.store.saveWork(h.record);await h.upload(h.record);const first=[...h.rows.values()][0],legacy={id:'legacy-copy',owner:'owner',local_id:'old-prefix|work:1',title:'旧版副本',image_path:'owner/legacy.jpg',updated_at:'2020-01-01'};h.rows.set(legacy.id,legacy);h.objects.set('ink-works:'+legacy.image_path,new Blob(['old']));const opened=await h.service.load(legacy);assert.equal(opened.id,'cloud141:legacy-copy');assert.equal(opened.draft,null);assert.equal((await h.store.get('work:1')).cloud141.id,first.id);await h.store.set('works-index',[{id:'work:1'},{id:opened.id}]);const removed=await h.service.remove(legacy);assert.equal(removed,opened.id);assert.ok(h.rows.has(first.id));assert.equal((await h.store.get('work:1')).cloud141.id,first.id)});
test('one album accepts 150 images but rejects the 151st including append to existing pages',()=>{const e={};vm.runInNewContext(fs.readFileSync('reference-upload138.js','utf8'),e);const p=Array.from({length:149},(_,i)=>'old'+i+'.jpg'),file={name:'150.jpg'};assert.equal(e.ReferenceUpload138.published({pages:p},{pages:p},[file],['150.jpg']).pages.length,150);assert.throws(()=>e.ReferenceUpload138.published({pages:p},{pages:p},[file,{name:'151.jpg'}],['150.jpg','151.jpg']),/150/)});
test('only the group owner can rename; rename is owner-filtered and updates the existing group',async()=>{const src=fs.readFileSync('collaboration128.js','utf8'),line=src.split('\n').find(l=>l.trim().startsWith('async function renameRoom141('));let saved,filters=[];const q={eq(k,v){filters.push([k,v]);return q},select(){return q},single:async()=>({data:{id:'r',title:saved,participants:['owner','child']}})};const e={uid:()=> 'owner',navigator:{onLine:true},db:{from:()=>({update:v=>{saved=v.title;return q}})},check:r=>r.data,room:{id:'r'},persistCache133:async()=>{}};vm.runInNewContext(line,e);await assert.rejects(e.renameRoom141({id:'r',owner:'child'},'新组名'),/只有发起人/);const group={id:'r',owner:'owner',title:'旧组名'};await e.renameRoom141(group,'上海与吉隆坡');assert.equal(group.title,'上海与吉隆坡');assert.deepEqual(filters,[['id','r'],['owner','owner']]);assert.deepEqual(Array.from(group.participants),['owner','child'])});
test('group heading places the member names directly below the title without online-presence claims',async()=>{const src=fs.readFileSync('collaboration128.js','utf8'),line=src.split('\n').find(l=>l.trim().startsWith('async function roomHeading141('));class Node{children=[];append(...n){this.children.push(...n)}}const host=new Node(),group={title:'家人练字',participants:['p','c'],memberNames141:{p:'爸爸',c:'孩子'}};const e={room:group,uid:()=> 'p',navigator:{onLine:false},document:{createElement:()=>new Node()},cloud:{user:{}},button(){}};vm.runInNewContext(line,e);await e.roomHeading141(host,group,false);assert.equal(host.children[0].children[0].textContent,'家人练字');assert.equal(host.children[0].children[1].textContent,'共同书写：爸爸、孩子')});

test('cloud uploads use URL-stable storage names for work IDs containing colons and separators',async()=>{const h=harness();h.record.id='copy:book|work:1';await h.upload(h.record);const row=[...h.rows.values()][0];assert.equal(row.image_path.includes('%'),false);assert.equal(row.image_path.includes('|'),false);assert.equal(row.image_path.split('/')[1],'copy_book_work_1');assert.ok(h.objects.has('ink-works:'+row.image_path));assert.ok(h.objects.has('ink-drafts:'+row.draft_path))});

test('editable cloud checkpoints retain the group and page needed to resume the same shared work on another device',async()=>{const h=harness();h.record.sharedRoom142='same-room';h.record.sharedPage151='same-page';h.record.sharedWriter151='me';await h.upload(h.record);const row=[...h.rows.values()][0];h.records.clear();const loaded=await h.service.load(row);assert.equal(loaded.sharedRoom142,'same-room');assert.equal(loaded.sharedPage151,'same-page');assert.equal(loaded.sharedWriter151,'me');assert.equal(loaded.id,h.record.id);assert.equal(loaded.draft.flow.strokes.length,h.record.draft.flow.strokes.length)});
test('ordinary publication uploads the display image without uploading editable strokes',async()=>{const h=harness();delete h.record.sharedRoom142;await h.upload(h.record);const row=[...h.rows.values()][0];assert.equal(row.draft_path,null);assert.ok([...h.objects.keys()].some(k=>k.startsWith('ink-works:')));assert.equal([...h.objects.keys()].some(k=>k.startsWith('ink-drafts:')),false);assert.equal(h.record.draft.flow.strokes.length,1)});
