import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const ctx={structuredClone};vm.runInNewContext(readFileSync('context149.js','utf8'),ctx);const M=ctx.SharedContext149;
test('restoring a shared page retains its canonical reference and paper but keeps each writer’s pending ink',()=>{const canonical={values:{ratio:'2',rows:'8'},referenceData111:'six-script',writingMode149:'copy',referenceAlignment146:{rect:{x:0,y:0,w:4,h:2}}},local={values:{ratio:'.75'},referenceData111:'personal',flow:{strokes:[{id:'pending'}]},signatureStrokes:[{id:'signature'}],extraSeals:[{id:'seal'}],sharedContext149:{roomId:'room',pageId:'page'}};const result=M.restore(canonical,local);assert.equal(result.referenceData111,'six-script');assert.equal(result.writingMode149,'copy');assert.equal(result.values.ratio,'2');assert.equal(result.flow,local.flow);assert.equal(result.extraSeals,local.extraSeals);assert.equal(result.sharedContext149.pageId,'page');result.values.rows='12';assert.equal(canonical.values.rows,'8')});
test('environment updates accept only the founder’s authenticated operation rows and never replace ink',()=>{const base={values:{ratio:'2'},flow:{strokes:[{id:'original'}]}},rows=[{writer:'member',payload:[{kind:'environment149',value:{values:{ratio:'.75'},flow:{strokes:[]}}}]},{writer:'founder',payload:[{kind:'environment149',value:{values:{ratio:'3'},flow:{strokes:[]}}}]}];const result=M.latest(base,rows,'founder');assert.equal(M.latest(base,rows.slice(0,1),'founder').values.ratio,'2');assert.equal(result.values.ratio,'3');assert.equal(result.flow,base.flow)});

test('changing a shared palette never retransmits an unchanged source image or ink',()=>{const before={referenceData111:'large-original',values:{papercolor:'#fff'},flow:{strokes:[{id:'s'}]}},after={...before,values:{papercolor:'#eee'}};const patch=M.delta(before,after);assert.equal(patch.referenceData111,undefined);assert.equal(patch.flow,undefined);assert.equal(patch.values.papercolor,'#eee');assert.equal(M.latest(before,[{writer:'owner',payload:[{kind:'environment149',value:patch}]}],'owner').referenceData111,'large-original')});
