import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const ctx={structuredClone};vm.runInNewContext(readFileSync('context149.js','utf8'),ctx);const M=ctx.SharedContext149;
test('restoring a shared page retains its canonical reference and paper but keeps each writer’s pending ink',()=>{const canonical={values:{ratio:'2',rows:'8'},referenceData111:'six-script',writingMode149:'copy',referenceAlignment146:{rect:{x:0,y:0,w:4,h:2}}},local={values:{ratio:'.75'},referenceData111:'personal',flow:{strokes:[{id:'pending'}]},signatureStrokes:[{id:'signature'}],extraSeals:[{id:'seal'}],sharedContext149:{roomId:'room',pageId:'page'}};const result=M.restore(canonical,local);assert.equal(result.referenceData111,'six-script');assert.equal(result.writingMode149,'copy');assert.equal(result.values.ratio,'2');assert.equal(result.flow,local.flow);assert.equal(result.extraSeals,local.extraSeals);assert.equal(result.sharedContext149.pageId,'page');result.values.rows='12';assert.equal(canonical.values.rows,'8')});
test('environment updates accept only the founder’s authenticated operation rows and never replace ink',()=>{const base={values:{ratio:'2'},flow:{strokes:[{id:'original'}]}},rows=[{writer:'member',payload:[{kind:'environment149',value:{values:{ratio:'.75'},flow:{strokes:[]}}}]},{writer:'founder',payload:[{kind:'environment149',value:{values:{ratio:'3'},flow:{strokes:[]}}}]}];const result=M.latest(base,rows,'founder');assert.equal(M.latest(base,rows.slice(0,1),'founder').values.ratio,'2');assert.equal(result.values.ratio,'3');assert.equal(result.flow,base.flow)});

test('personal brush and palette are excluded from founder synchronization',()=>{const before={referenceData111:'original',values:{ratio:'2',papercolor:'#fff',inkcolor:'#111'},brush:{size:20}},after={...before,values:{...before.values,papercolor:'#eee'},brush:{size:40}};assert.equal(Object.keys(M.delta(before,after)).length,0);const restored=M.restore(before,after);assert.equal(restored.values.papercolor,'#eee');assert.equal(restored.brush.size,40);assert.equal(M.lockedConfig150({preset:'zhang',brushPatch:{size:40},values:{papercolor:'#eee'}}),false);assert.equal(M.lockedConfig150({values:{ratio:'3'}}),true)});
