const {chromium}=require('playwright');const fs=require('fs'),http=require('http'),path=require('path');
(async()=>{const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{const p=path.join(root,decodeURI(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));try{res.setHeader('Content-Type',({'js':'application/javascript','html':'text/html','css':'text/css','png':'image/png','woff':'font/woff'})[p.split('.').pop()]||'application/octet-stream');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end()}}).listen(8765,'127.0.0.1');const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--no-zygote','--single-process'],headless:true});const p=await b.newPage({viewport:{width:820,height:1180}});p.on('pageerror',e=>console.log('PAGEERROR',e.stack));await p.route(/https?:\/\/(?!127\.0\.0\.1)/,r=>r.abort());await p.goto('http://127.0.0.1:8765');await p.waitForFunction(()=>document.documentElement.dataset.appReady==='true');
await p.waitForFunction(()=>window.AnnotationHome);const assert=require('assert').strict;const set=async(id,value,event='change')=>p.evaluate(({id,value,event})=>{const e=document.getElementById(id);e.value=value;e.dispatchEvent(new Event(event,{bubbles:true}))},{id,value,event});
const click=async id=>p.evaluate(id=>document.getElementById(id).click(),id);
const snap=()=>p.evaluate(async()=>{await ZhenjiBackup.flush();return DraftStore.get('draft')});

assert.equal(await p.title(),'今日批注 · 亲手表达，留下真迹。');await p.waitForFunction(()=>document.querySelector('.annotationSlide').dataset.loaded==='yes');await p.screenshot({path:'/tmp/annotation36-home.png'});assert.equal(await p.locator('#annotationCategories button').count(),7);
await click('useAnnotation');await p.waitForFunction(()=>!document.body.classList.contains('home-open'));let d=await snap();assert.equal(d.values.sceneChoice,'annotation:film');assert.equal(d.values.panSpeed,'300');assert.equal(d.values.ratio,'0.75');assert.equal(await p.locator('#funCarrier').count(),0);assert.equal(await p.locator('#quickFun').count(),0);
await p.locator('#photoUpload').setInputFiles(path.join(root,'museums/louvre.webp'));await p.waitForTimeout(250);await click('editPhoto');assert.equal(await p.locator('#photoEditFrame').isVisible(),true);await click('photoCropMode');await p.evaluate(()=>{const e=document.getElementById('photoEditFrame'),r=e.getBoundingClientRect();e.setPointerCapture=()=>{};for(const [type,id,x]of [['pointerdown',10,40],['pointerdown',11,100],['pointermove',11,160],['pointerup',11,160],['pointerup',10,40]])e.dispatchEvent(new PointerEvent(type,{pointerId:id,clientX:r.x+x,clientY:r.y+50,bubbles:true,pointerType:'touch'}))});assert.ok((await snap()).photos[0].crop.zoom>1);await click('finishPhoto');await click('removePhoto');await set('zoom','50','input');assert.equal((await snap()).brush.size,110);assert.equal(await p.locator('#zoomHUD').isVisible(),true);await p.waitForTimeout(600);assert.equal(await p.locator('#zoomHUD').isVisible(),false);
for(const key of ['music','book','exhibition','heritage','moment','now']){await p.evaluate(key=>AnnotationApp.applyTemplate(key),key);assert.equal((await snap()).values.sceneChoice,'annotation:'+key)}
await set('quickScene','none');await set('autoScroll','off');await set('zoom','100','input');await p.evaluate(()=>AnnotationApp.refresh());const before=await snap();await p.evaluate(()=>{const e=document.getElementById('live'),r=e.getBoundingClientRect();const events=[['pointerdown',1,140,200],['pointerdown',2,240,200],['pointerdown',3,340,200],['pointermove',1,180,240],['pointermove',2,280,240],['pointermove',3,380,240],['pointerup',1,180,240],['pointerup',2,280,240],['pointerup',3,380,240]];e.setPointerCapture=()=>{};for(const [type,id,x,y]of events)e.dispatchEvent(new PointerEvent(type,{pointerId:id,clientX:r.x+x,clientY:r.y+y,bubbles:true,pointerType:'touch'}))});await p.waitForTimeout(120);const after=await snap();assert.equal(after.values.zoom,before.values.zoom);assert.equal(after.flow.strokes.length,before.flow.strokes.length);
await click('fitView');await p.locator('[data-seal-key="head"]').click();const sealBefore=await snap();await set('selectedSealType','yang');assert.equal((await snap()).values.headType,'yang');await click('undo');assert.equal((await snap()).values.headType,sealBefore.values.headType);await click('redo');assert.equal((await snap()).values.headType,'yang');await p.locator('[data-seal-key="head"]').click();await set('selectedSealSize','15');assert.equal(+(await snap()).values.headSize,15);await click('undo');assert.equal((await snap()).values.headSize,sealBefore.values.headSize);
await click('calendarMoments');await p.locator('#momentTitle').fill('重要毕业日');await p.locator('#momentDate').fill('2026-09-20');await p.locator('#momentForm button').click();await p.waitForFunction(async()=>!!(await DraftStore.get('annotation.moments.v1'))?.events.length);assert.ok((await p.locator('#personalMoments').textContent()).includes('重要毕业日'));const download=p.waitForEvent('download');await p.locator('#personalMoments button').filter({hasText:'日历'}).click();await (await download).saveAs('/tmp/annotation-moment.ics');await click('closeMoments');
for(let i=0;i<5;i++){await click('topToggle');await click('topToggle');await p.waitForTimeout(80);assert.equal(await p.locator('#topActions').isVisible(),true);assert.ok((await p.locator('#topActions').boundingBox()).width>200)}
await click('fitView');await set('autoScroll','off');await set('videoMusic','default');await click('recordProcess');await p.waitForFunction(()=>ProcessVideo.isRecording());await p.waitForTimeout(1800);assert.equal(await p.evaluate(()=>ProcessVideo.stats().state),'paused');const r=await p.locator('#board').boundingBox();await p.mouse.move(r.x+200,r.y+280);await p.mouse.down();await p.mouse.move(r.x+300,r.y+420,{steps:25});await p.mouse.up();await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>ProcessVideo.stats().state),'recording');await click('recordProcess');await p.waitForFunction(()=>!document.getElementById('processVideo').hidden,{timeout:15000});const vid=p.waitForEvent('download');await click('downloadVideo');await (await vid).saveAs('/tmp/annotation-process.webm');
console.log('PASS home, seven templates, 55 zoom baseline, 3-finger no accidental ink/pinch, seal type/size undo redo, personal moments and ICS, five toolbar toggles, video idle skip and playable download');await b.close();server.close()})().catch(e=>{console.error(e);process.exit(1)});
