const {chromium}=require('playwright');const fs=require('fs'),http=require('http'),path=require('path');
(async()=>{const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{const p=path.join(root,decodeURI(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));try{res.setHeader('Content-Type',({'js':'application/javascript','html':'text/html','css':'text/css','png':'image/png','woff':'font/woff'})[p.split('.').pop()]||'application/octet-stream');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end()}}).listen(8765,'127.0.0.1');const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--no-zygote','--single-process'],headless:true});const p=await b.newPage({viewport:{width:820,height:1180}});const imageRequests=[];p.on('request',r=>{if(/\/(museums|scenes)\//.test(r.url()))imageRequests.push(r.url())});p.on('pageerror',e=>console.log('PAGEERROR',e.stack));await p.route(/https?:\/\/(?!127\.0\.0\.1)/,r=>r.abort());await p.goto('http://127.0.0.1:8765');await p.waitForFunction(()=>document.documentElement.dataset.appReady==='true');
const assert=require('assert').strict;const set=async(id,value,event='change')=>p.evaluate(({id,value,event})=>{const e=document.getElementById(id);e.value=value;e.dispatchEvent(new Event(event,{bubbles:true}))},{id,value,event});
const click=async id=>p.evaluate(id=>document.getElementById(id).click(),id);
const snap=()=>p.evaluate(async()=>{await ZhenjiBackup.flush();return DraftStore.get('draft')});

assert.equal(imageRequests.length,0,'no exhibition images on startup');const errors=[];p.on('pageerror',e=>errors.push(e.message));
assert.equal(await p.evaluate(()=>Poetry100.length),100);assert.equal(await p.evaluate(()=>new Set(Poetry100.map(q=>q.id)).size),100);
await p.evaluate(()=>selectPoem('poetry-072'));await click('pinPoem');assert.equal(await p.locator('#poetryReference').isVisible(),true);assert.ok((await p.locator('#poetryReference pre').textContent()).length>50);await p.locator('#poetryReference button').click();
await click('manageTemplates');assert.equal(await p.locator('#templateManager').isVisible(),true);await p.locator('button[aria-label="删除模板 拉斐尔 · 纸上雅典"]').click();assert.equal(await p.locator('#quickScene option[value="museum:raphael"]').count(),0);await p.reload();await p.waitForFunction(()=>document.documentElement.dataset.appReady==='true');assert.equal(await p.locator('#quickScene option[value="museum:raphael"]').count(),0);await click('manageTemplates');await click('restoreTemplates');await p.locator('#templateManager .dialogHead button').click();assert.equal(await p.locator('#quickScene option[value="museum:raphael"]').count(),1);
assert.equal(await p.locator('#quickFun').isVisible(),false);assert.equal(await p.locator('#sceneChoice option[value="1"]').count(),0);
await p.evaluate(async()=>{for(let i=0;i<30;i++)await DraftStore.saveWork({id:'work:bulk'+i,title:'批次作品'+i,date:'2026',created:i,blob:new Blob(['PNG'+i],{type:'image/png'})});await DraftStore.saveWork({id:'work:keep',title:'保留作品',date:'2026',created:31,blob:new Blob(['keep'],{type:'image/png'})})});
await click('myWorks');await p.waitForFunction(()=>document.querySelectorAll('.workCard').length===24);await p.locator('#worksSearch').fill('批次');await click('batchMode');await click('batchAll');assert.equal(await p.locator('#batchCount').textContent(),'已选 30 幅');const download=p.waitForEvent('download');await click('batchDownload');const zip=await download;await zip.saveAs('/tmp/zhenji-bulk.zip');p.once('dialog',d=>d.accept());await click('batchDelete');await p.waitForFunction(async()=>{return (await DraftStore.get('works-index')).length===1});assert.ok(await p.evaluate(()=>DraftStore.get('work:keep')));assert.equal(await p.evaluate(()=>DraftStore.get('work:bulk0')),undefined);
assert.deepEqual(errors,[]);console.log('PASS 100 poems, reading panel, persistent template deletion/restore, all 30 selected beyond first page, ZIP download, atomic bulk delete retains unselected work');await b.close();server.close()})().catch(e=>{console.error(e);process.exit(1)});
