import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const source=readFileSync(new URL('../app.js',import.meta.url),'utf8');
function setup(overview=false){
 const handlers={},frames=[],rendered=[],target={closest:s=>s==='#board'?{}:null},board={addEventListener:(k,fn)=>handlers[k]=fn,setPointerCapture(){},getBoundingClientRect:()=>({left:0,top:0})},controls={ratio:{value:'.75'},zoom:{value:'200'},inkMode:{value:'raw'}};
 const c=vm.createContext({window:{},board,live:board,console,requestAnimationFrame:fn=>{frames.push(fn);return frames.length},clearTimeout(){},$:id=>controls[id]||{value:'',click(){}},overview,photoEditing:false,selectedSeal:null,active:null,state:null,pointer:null,singleTap:null,secondTap:null,wrapFocus:null,moveTarget:null,writeMoved:false,pendingWrap:null,previewTap:null,cacheArea:null,gesturing:false,gestureCenter:null,pinchDistance:0,gestureTap:null,previousTap:null,threeFingerPan:false,flow:{strokes:[],undo:[],redo:[]},touches:new Map(),brush:{size:30,color:'#000000'},camera:{x:1,y:2},S:100,W:400,H:600,focused:true,followTrail:[],followDebt:0,lastTouch:null,scrollClock:0,writingOnPhoto:true,endAwait38:null,
  cancelAutoMove(){},focusAt(){},sheetBounds:()=>({w:20,h:20}),sample:e=>({x:e.clientX/100,y:e.clientY/100,t:e.timeStamp,pressure:.5}),trackPressure(){},schedule(){rendered.push('scheduled')},update(){},clearStrokeSurface(){},presentInk(){},redraw(){},afterLift(){},fitPaper(){},showPhotoMenu(){throw Error('unexpected photo edit')},photoHit:()=>-1,clampCamera(){},background(){},ensureCache(){},updateGuide(){},saveSoon(){},drawOverview(){},previewView:{zoom:1,x:0,y:0},centroid:()=>{const p=[...c.touches.values()];return{x:p.reduce((s,p)=>s+p.clientX,0)/p.length,y:p.reduce((s,p)=>s+p.clientY,0)/p.length}},writeAtPreview96(x,y){rendered.push(['locate',x,y]);c.overview=false},finish(){if(c.active){c.flow.strokes.push(c.active);c.active=null;c.pointer=null}},endPhotoEdit(){c.photoEditing=false}});
 vm.runInContext(source.slice(source.indexOf('let writingViewFrame=0'),source.indexOf('function zoomPreview66')),c);
 vm.runInContext(source.split('\n').find(s=>s.startsWith("board.addEventListener('pointerup'")),c);
 return {c,handlers,rendered,target,flush(){while(frames.length)frames.shift()()},event:(id,x,y,t)=>({pointerId:id,clientX:x,clientY:y,timeStamp:t,button:0,pressure:.5,target,preventDefault(){}})};
}
test('real handlers receive a stroke through a decorative layer and finish it',()=>{const s=setup();s.handlers.pointerdown(s.event(1,100,100,0));s.handlers.pointermove(s.event(1,160,180,300));s.handlers.pointerup(s.event(1,160,180,400));assert.equal(s.c.flow.strokes.length,1);assert.equal(s.c.flow.strokes[0].points.length,3);assert.equal(s.c.touches.size,0);assert.equal(s.c.active,null);assert.equal(s.rendered.length,2)});
test('real two-finger handler moves camera and releases both pointers',()=>{const s=setup();s.handlers.pointerdown(s.event(1,100,100,0));s.handlers.pointerdown(s.event(2,200,100,20));s.handlers.pointermove(s.event(1,140,120,100));s.handlers.pointermove(s.event(2,240,120,110));s.flush();assert.ok(Math.abs(s.c.camera.x-.6)<1e-9);assert.equal(s.c.camera.y,1.8);s.handlers.pointerup(s.event(1,140,120,130));s.handlers.pointerup(s.event(2,240,120,140));assert.equal(s.c.gesturing,false);assert.equal(s.c.touches.size,0)});
test('core preview double tap locates once at requested screen point',()=>{const s=setup(true);for(const t of [0,160]){s.handlers.pointerdown(s.event(1,180,220,t));s.handlers.pointerup(s.event(1,180,220,t+30))}assert.deepEqual(s.rendered,[['locate',180,220]]);assert.equal(s.c.overview,false);assert.equal(s.c.touches.size,0)});
test('controls do not start ink; stale photo-edit flag is cleared on paper input',()=>{const s=setup();const e=s.event(1,100,100,0);e.target={closest:()=>({})};s.handlers.pointerdown(e);assert.equal(s.c.active,null);s.c.photoEditing=true;s.handlers.pointerdown(s.event(2,100,100,0));assert.equal(s.c.photoEditing,false);assert.ok(s.c.active)});
