import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const ctx={crypto:{randomUUID:()=> 'new-page'}};vm.runInNewContext(fs.readFileSync('copy-integrity181.js','utf8'),ctx);const M=ctx.CopyIntegrity181;
const draft=(album,page)=>({writingMode149:'copy',copyPage181:{albumId179:album,pageId179:page},flow:{strokes:[{points:[{x:1,y:1,t:1}]}]}});
function store(entries=[]){const map=new Map(entries);return{map,get:async k=>map.get(k),set:async(k,v)=>map.set(k,v),delete:async k=>map.delete(k)}}
test('old single-work previews and cached art are detached without deleting the historical artwork',async()=>{const book={id:'book',pages:[{id128:'p',image:'original',workIds:['old-single'],preview159:'wrong',draft:{writingMode149:'letter',flow:{strokes:[1]}}}]},s=store([['old-single',{blob:'old art'}],['book:art161:p','wrong art']]);await M.clean(book,s);assert.equal(book.pages[0].preview159,'');assert.equal(book.pages[0].draft,null);assert.deepEqual(Array.from(book.pages[0].workIds),[]);assert.equal(s.map.get('old-single').blob,'old art');assert.equal(s.map.has('book:art161:p'),false);assert.ok(s.map.has('copy-quarantine181:book:p'))});
test('matching original alone cannot pull a different session into a page',async()=>{const book={id:'new-book',pages:[{id128:'p',image:'same',workIds:['prior'],preview159:'wrong'}]},s=store([['prior',{copySource141:{albumId179:'prior-book',pageId179:'p',pageImage:'same'},draft:draft('prior-book','p')}]]);await M.clean(book,s);assert.equal(book.pages[0].invalid179,true);assert.equal(book.pages[0].owned181,false)});
test('owned local sidecars survive migration and do not get substituted by another page',async()=>{const book={id:'book',pages:[{id128:'p1',image:'one',preview159:'own',previewPage181:{albumId179:'book',pageId179:'p1'},workIds:[]},{id128:'p2',image:'two',draft:draft('book','p1'),preview159:'wrong',workIds:[]}]},s=store([['book:page:p1',draft('book','p1')]]);await M.clean(book,s);assert.equal(book.pages[0].owned181,true);assert.equal(book.pages[0].preview159,'own');assert.equal(book.pages[1].invalid179,true);assert.equal(book.pages[1].preview159,'')});
test('explicit work-page ownership restores legitimate older copy strokes',async()=>{const book={id:'book',pages:[{id128:'p',image:'original',workIds:['real']}]},s=store([['real',{copySource141:{albumId179:'book',pageId179:'p'},draft:{writingMode149:'copy',flow:{strokes:[1]}}}]]);await M.clean(book,s);assert.equal(book.pages[0].owned181,true);assert.equal(book.pages[0].draft.flow.strokes[0],1);assert.deepEqual(Array.from(book.pages[0].workIds),['real'])});
test('export cannot read a cached sidecar from another book',async()=>{const ctx={};vm.runInNewContext(fs.readFileSync('copy-integrity181.js','utf8'),ctx);globalThis.CopyIntegrity181=ctx.CopyIntegrity181;const m=await import('../copy-download181.js');const art=await m.artwork({id:'book',pages:[{id128:'p',owned181:true}]},0,{get:async()=>draft('other','p')});assert.equal(art,null);delete globalThis.CopyIntegrity181});
