const {chromium}=require('playwright');const fs=require('fs'),http=require('http'),path=require('path');
(async()=>{const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{const p=path.join(root,decodeURI(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));try{res.setHeader('Content-Type',({'js':'application/javascript','html':'text/html','css':'text/css','png':'image/png','woff':'font/woff'})[p.split('.').pop()]||'application/octet-stream');res.end(fs.readFileSync(process.env.BENCH_BASELINE&&p.endsWith('/app.js')?'/tmp/app36baseline.js':p))}catch{res.statusCode=404;res.end()}}).listen(8765,'127.0.0.1');const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--no-zygote','--single-process'],headless:true});const p=await b.newPage({viewport:{width:820,height:1180}});p.on('pageerror',e=>console.log('PAGEERROR',e.stack));await p.route(/https?:\/\/(?!127\.0\.0\.1)/,r=>r.abort());await p.goto('http://127.0.0.1:8765');await p.waitForFunction(()=>document.documentElement.dataset.appReady==='true');
await p.waitForFunction(()=>window.AnnotationHome);const assert=require('assert').strict;const set=async(id,value,event='change')=>p.evaluate(({id,value,event})=>{const e=document.getElementById(id);e.value=value;e.dispatchEvent(new Event(event,{bubbles:true}))},{id,value,event});
const click=async id=>p.evaluate(id=>document.getElementById(id).click(),id);
const snap=()=>p.evaluate(async()=>{await ZhenjiBackup.flush();return DraftStore.get('draft')});



await click('continueWriting');await set('autoScroll','off');await set('paperPattern','none');
await p.evaluate(()=>{window.calls=0;const old=ParticleBrush.render;ParticleBrush.render=(...a)=>{window.calls++;return old(...a)}});
const r=await p.locator('#board').boundingBox();for(let i=0;i<80;i++){await p.mouse.move(r.x+80+i%10*50,r.y+120+Math.floor(i/10)*85);await p.mouse.down();await p.mouse.move(r.x+110+i%10*50,r.y+155+Math.floor(i/10)*85,{steps:12});await p.mouse.up()}
await p.waitForTimeout(300);await p.evaluate(()=>window.calls=0);const timings=[];for(let i=0;i<5;i++){let t=Date.now();await click('fitView');timings.push(Date.now()-t);await click('fitView')}console.log('SWITCH',timings,'RENDERS',await p.evaluate(()=>window.calls));
await p.evaluate(()=>window.calls=0);let t=Date.now();for(let v=100;v<=180;v+=2)await set('zoom',String(v),'input');console.log('ZOOM',Date.now()-t,'RENDERS',await p.evaluate(()=>window.calls));await p.waitForTimeout(700);console.log('IDLE RENDERS',await p.evaluate(()=>window.calls));const count=(await snap()).flow.strokes.length;await p.evaluate(()=>{window.calls=0;const e=document.getElementById('live'),r=e.getBoundingClientRect();e.setPointerCapture=()=>{};function send(type,id,x,y){e.dispatchEvent(new PointerEvent(type,{pointerId:id,clientX:r.x+x,clientY:r.y+y,bubbles:true,pointerType:'touch'}))}send('pointerdown',81,200,250);send('pointerdown',82,350,250);for(let i=0;i<30;i++)send('pointermove',82,350+i*3,250);window.gestureRenders=window.calls;send('pointerup',82,437,250);send('pointerup',81,200,250)});assert.equal((await snap()).flow.strokes.length,count);console.log('PINCH RENDERS',await p.evaluate(()=>window.gestureRenders));await p.waitForTimeout(1200);await p.screenshot({path:'/tmp/perf37.png'});await b.close();server.close()})().catch(e=>{console.error(e);process.exit(1)});