const {chromium}=require('playwright');const fs=require('fs'),http=require('http'),path=require('path');
(async()=>{const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{const p=path.join(root,decodeURI(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));try{res.setHeader('Content-Type',({'js':'application/javascript','html':'text/html','css':'text/css','png':'image/png','woff':'font/woff'})[p.split('.').pop()]||'application/octet-stream');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end()}}).listen(8765,'127.0.0.1');const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--no-zygote','--single-process'],headless:true});const p=await b.newPage({viewport:{width:820,height:1180}});p.on('pageerror',e=>console.log('PAGEERROR',e.stack));await p.route(/https?:\/\/(?!127\.0\.0\.1)/,r=>r.abort());await p.goto('http://127.0.0.1:8765');await p.waitForFunction(()=>document.documentElement.dataset.appReady==='true');
await p.waitForFunction(()=>window.AnnotationHome);const assert=require('assert').strict;const set=async(id,value,event='change')=>p.evaluate(({id,value,event})=>{const e=document.getElementById(id);e.value=value;e.dispatchEvent(new Event(event,{bubbles:true}))},{id,value,event});
const click=async id=>p.evaluate(id=>document.getElementById(id).click(),id);
const snap=()=>p.evaluate(async()=>{await ZhenjiBackup.flush();return DraftStore.get('draft')});


await click('continueWriting');await set('autoScroll','off');await set('quickSizeNumber','80');const r=await p.locator('#board').boundingBox();for(let i=0;i<6;i++){await p.mouse.move(r.x+150+i*45,r.y+240);await p.mouse.down();await p.mouse.move(r.x+200+i*45,r.y+460,{steps:24});await p.mouse.up()}await p.waitForTimeout(100);const pixels=await p.evaluate(()=>document.getElementById('ink').toDataURL());await p.evaluate(()=>AnnotationApp.refresh());await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>document.getElementById('ink').toDataURL()),pixels,'historical rebuild preserves exact sharp pixels');
await click('fitView');const sealState=await snap();const seal=await p.locator('[data-seal-key="head"]').boundingBox();await p.mouse.move(seal.x+seal.width/2,seal.y+seal.height/2);await p.mouse.down();await p.mouse.move(seal.x+seal.width/2-40,seal.y+seal.height/2+30,{steps:4});await p.mouse.up();assert.notDeepEqual((await snap()).sealPositions,sealState.sealPositions);await click('undo');assert.deepEqual((await snap()).sealPositions,sealState.sealPositions);await click('redo');assert.notDeepEqual((await snap()).sealPositions,sealState.sealPositions);await p.setViewportSize({width:390,height:844});for(let i=0;i<3;i++){await click('topToggle');await click('topToggle');await p.waitForTimeout(100);assert.ok((await p.locator('#topActions').boundingBox()).width>200)}await p.evaluate(()=>AnnotationHome.show());await p.waitForTimeout(100);await p.screenshot({path:'/tmp/annotation36-mobile.png'});await click('continueWriting');
await click('export');const start=Date.now();await click('generateDownload');await p.waitForFunction(()=>document.getElementById('imageDialog').open);const ms=Date.now()-start;const bytes=await p.evaluate(async()=>Array.from(new Uint8Array(await (await fetch(document.getElementById('savedImage').src)).arrayBuffer())));fs.writeFileSync('/tmp/annotation-export.png',Buffer.from(bytes));await p.waitForFunction(async()=>!!(await DraftStore.get('works-index'))?.length);console.log('PASS six-stroke export '+ms+' ms, exact ink pixels preserved after viewport cache rebuild, archive saves after image appears');await b.close();server.close()})().catch(e=>{console.error(e);process.exit(1)});
