import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const read=name=>fs.readFileSync(name,'utf8');
test('retained photo and shared entrances become one text-only shared entrance after creation',()=>{const s=read('studio50.js'),ctx={};vm.runInNewContext(s.slice(s.indexOf('function coreNavigation129('),s.indexOf('function normalize(raw)'))+';this.nav=coreNavigation129',ctx);const original=[{id:'single'},{id:'copy'},{id:'photo',title:'共书'},{id:'letter',title:'创作'},{id:'shared',title:'共书'}],out=ctx.nav(original);assert.deepEqual(Array.from(out,n=>n.id),['single','copy','letter','shared']);assert.equal(out[2].title,'独创');assert.equal(original[2].id,'photo')});
test('reference image loading uses a detached image and falls back when Pages has not served a new upload',async()=>{const urls=[],ctx={Blob,URL,location:{href:'https://iinnkk.me/?v=129'},setTimeout,clearTimeout,Image:class{set src(url){urls.push(url);queueMicrotask(()=>{if(url.startsWith('https://iinnkk.me/'))this.onerror();else{this.naturalWidth=900;this.naturalHeight=1200;this.onload()}})}}};vm.runInNewContext(read('reference-io129.js'),ctx);const image=await ctx.ReferenceIO129.load('timeline/pages/hanshi/a-0.jpg');assert.equal(image.naturalWidth,900);assert.equal(urls.length,2);assert.equal(urls[1],'https://raw.githubusercontent.com/jearns/iinnkk/main/timeline/pages/hanshi/a-0.jpg');assert.equal(image.crossOrigin,'anonymous')});
function floatContext(){const s=read('revision129.js');let resolve,captures=0,replaces=0;const ref={width:900,height:1200},image={naturalWidth:900,naturalHeight:1200,replaceWith(){replaces++}},ctx={document:{body:{classList:{contains:()=>false}}},localStorage:{getItem:()=> 'copy'},image,settings:{floating:true},window:{},loadedCrop137:'',pendingCrop137:'',displayCrop137:{x:0,y:0,w:1,h:1},current:{row:0,col:0},ReferenceGeometry133:{retainCell137:(_,__,current)=>current},A:{getReference:()=>ref,referenceCells128:()=>[]},C:{active:{index:0,title:'新帖',pages:[{name:'第01页.jpg'}]}},imageGeneration:0,loadedReference:null,pendingReference:null,pendingImage:null,manuallySized:false,manuallyMoved140:false,floatSide140:'left',ReferenceIO129:{capture:()=>{captures++;return new Promise(r=>resolve=r)},fitWindow:(w,h,mw,mh)=>{const k=Math.min(mw/w,mh/h);return{width:Math.round(w*k),height:Math.round(h*k)}}},floating:{hidden:true,style:{},querySelector:()=>({})},$:()=>({getBoundingClientRect:()=>({width:375,height:600})}),fit(){},navState(){},Math};vm.runInNewContext(s.slice(s.indexOf(' function sizeFloat()'),s.indexOf(' function navState()'))+';this.load=loadImage',ctx);return {ctx,get captures(){return captures},get replaces(){return replaces},resolve:()=>resolve({naturalWidth:900,naturalHeight:1200})}}
test('repeated floating-window requests share a pixel capture without interrupting image decoding',async()=>{const f=floatContext(),first=f.ctx.load(),second=f.ctx.load();assert.equal(f.captures,1);f.resolve();await Promise.all([first,second]);assert.equal(f.replaces,1);assert.equal(f.ctx.floating.hidden,false);assert.equal(f.ctx.floating.style.width,'168px');assert.equal(f.ctx.floating.style.height,'224px')});
test('closing a floating window during image preparation does not reopen it afterwards',async()=>{const f=floatContext(),loading=f.ctx.load();f.ctx.settings.floating=false;await f.ctx.load();f.resolve();await loading;assert.equal(f.ctx.floating.hidden,true);assert.equal(f.replaces,0)});
test('failure to read a new book leaves the active book and current page intact',async()=>{const s=read('copy-albums38.js'),start=s.indexOf('openPages55:')+12,end=s.indexOf(',pause:async',start);let saved=0;const active={id:'prior',index:2},ctx={startupAlbums143:Promise.resolve(),busy:false,active,loadImage:async()=>{throw Error('bad image')},storePage:async()=>saved++};vm.runInNewContext('this.open='+s.slice(start,end),ctx);await assert.rejects(ctx.open({pages:[{image:'bad.jpg'}]}),/bad image/);assert.equal(ctx.active,active);assert.equal(ctx.active.index,2);assert.equal(saved,0)});
test('a valid new book opens directly even if restoring the previous copy mode would fail',async()=>{const s=read('timeline73.js'),start=s.indexOf(' async function openCopy('),end=s.indexOf(' async function edit(',start);let opened=0;const ctx={chapterData:()=>({pages:['timeline/pages/hanshi/a-0.jpg'],title:'新帖',style:'su'}),modal:{open:false},U:{config:{nav:[{id:'copy'}]},applyMode:async()=>{throw Error('old reference is gone')}},CopyAlbums38:{openPages55:async()=>opened++},A:{presets:{su:{}},configure47:async()=>{},showWriter(){},isOverview55:()=>true},window:{Reference129:{openSettings(){}}}};vm.runInNewContext(s.slice(start,end)+';this.open=openCopy',ctx);await ctx.open({id:'hanshi'});assert.equal(opened,1)});
test('pen-up movement waits 1.6 seconds and wrapping waits 2.4 seconds; another stroke cancels it',()=>{const s=read('app.js'),start=s.indexOf('function afterLift('),end=s.indexOf('function emptyGlyph(',start);for(const [wrap,delay] of [[false,1600],[true,2400]]){let scheduled,cleared=false;const ctx={$:id=>({value:id==='autoScroll'?'on':id==='motionMode'?'lift':'450'}),signatureReturn110:null,nextPaperTarget:()=>({wrap,point:{},camera:{}}),autoMoveToken:0,liftTimer:0,active:null,gesturing:false,touches:new Map(),overview:false,cancelAutoMove(){ctx.autoMoveToken++;cleared=true},setTimeout:(fn,ms)=>(scheduled={fn,ms},1),glideCamera(){throw Error('a canceled movement must not run')},toast(){},vertical:()=>true,Math};vm.runInNewContext(s.slice(start,end)+';this.after=afterLift',ctx);ctx.after({});assert.equal(scheduled.ms,delay);ctx.cancelAutoMove();assert.equal(cleared,true);if(wrap)scheduled.fn()}});
test('homepage never starts reference capture even with a retained reference and copy mode',async()=>{const f=floatContext();f.ctx.document.body.classList.contains=()=>true;await f.ctx.load();assert.equal(f.captures,0);assert.equal(f.ctx.floating.hidden,true)});
test('navigation home during async crop preparation keeps the reference hidden',async()=>{const f=floatContext(),job=f.ctx.load();f.ctx.document.body.classList.contains=()=>true;f.resolve();await job;assert.equal(f.ctx.floating.hidden,true);assert.equal(f.replaces,0)});
