import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync('revision131.js','utf8');
class Node{
 constructor(tag='div'){this.tagName=tag;this.children=[];this.attrs={};this.dataset={};this.events={};this.hidden=false;this.style={};this.textContent='';this.classes=new Set();this.classList={contains:c=>this.classes.has(c),toggle:(c,on)=>on?this.classes.add(c):this.classes.delete(c)};this.rect={left:0,top:0,width:400,height:600,bottom:600};}
 append(...items){for(const n of items){n.parentElement=this;this.children.push(n)}}
 before(n){const list=this.parentElement.children;list.splice(list.indexOf(this),0,n);n.parentElement=this.parentElement}
 replaceChildren(...items){this.children=[];this.append(...items)}
 set innerHTML(v){this.children=[];if(v.includes('<span>'))this.append(new Node('span'))}
 setAttribute(k,v){this.attrs[k]=String(v)}
 getAttribute(k){return this.attrs[k]}
 addEventListener(type,fn){(this.events[type]??=[]).push(fn)}
 getBoundingClientRect(){return this.rect}
 setPointerCapture(){}
 showModal(){this.open=true}
 close(){this.open=false;(this.events.close||[]).forEach(fn=>fn())}
 remove(){this.parentElement.children=this.parentElement.children.filter(x=>x!==this)}
 querySelectorAll(selector){const matches=n=>selector.startsWith('.')?n.className?.split(' ').includes(selector.slice(1)):selector.startsWith('[')?n.attrs['aria-current']==='true':n.tagName===selector;const result=[];function walk(n){for(const c of n.children){if(matches(c))result.push(c);walk(c)}}walk(this);return result}
 querySelector(selector){if(selector==='.annotationBrand h1')return this.hero;return this.querySelectorAll(selector)[0]||null}
}
function setup(){const nodes={},events={},draws=[];const body=new Node('body');body.classes.add('home-open');const doc={body,getElementById:id=>nodes[id]||null,createElement:tag=>{const n=new Node(tag);if(tag==='canvas'){const t={fillRect(){},strokeRect(){},drawImage(...args){draws.push({alpha:this.globalAlpha,args})}};n.getContext=()=>t}return n},addEventListener:(type,fn)=>(events[type]??=[]).push(fn)};
 for(const id of ['writerModes53','live','copyLayout111','previewEffects55','homeBrand79','annotationHome']){nodes[id]=new Node(id==='copyLayout111'?'input':'div');body.append(nodes[id])}nodes.copyLayout111.type='hidden';nodes.copyLayout111.value='background';
 const rail=new Node();rail.className='finalRail54';const tab=new Node('button');tab.textContent='临帖';tab.setAttribute('aria-current',true);nodes.previewEffects55.append(tab,rail);const hero=new Node('h1');hero.rect.bottom=100;nodes.annotationHome.hero=hero;const album={index:0,pages:[{id128:'a',name:'原图01.jpg',image:'01.jpg'},{id128:'b',name:'原图02.jpg',image:'02.jpg'}]};let refreshes=0;
 const ctx={document:doc,console,URL,location:{href:'https://iinnkk.me/'},setTimeout:()=>1,clearTimeout(){},addEventListener:(type,fn)=>(events[type]??=[]).push(fn),MutationObserver:class{observe(){}},localStorage:{getItem:()=> 'copy',setItem(){}},AnnotationApp:{getReference:()=>({width:1000,height:2000,naturalWidth:1000,naturalHeight:2000}),getState:()=>({values:{papercolor:'#faf6ec'}}),refresh(){refreshes++},persist(){},isOverview55:()=>true,toast(){},showWriter(){},configure47:async()=>{},setLineProfile108(){}},CopyAlbums38:{active:album,persist129:async()=>{},select128:async i=>album.index=i,reorder128:async()=>{}},TouchOrder129:{icon:()=>'<svg></svg>',render(host,pages,options){host.replaceChildren();for(const p of pages){const card=new Node('article'),span=new Node('span');span.textContent=p.name;card.append(span);host.append(card)}host.options=options}}};ctx.Reference129={ready:true,settings:{floating:false},refreshSettings(){if(ctx.Reference131)ctx.Reference131.renderControls(rail)},renderPreview:host=>ctx.Reference131.renderControls(host),loadImage:async()=>{},entered:async()=>ctx.Reference131.entered(),openSettings(){},openPicker(){}};
 vm.runInNewContext(source,ctx);return{ctx,nodes,events,draws,body,rail,album,hero,get refreshes(){return refreshes}};
}
test('hidden layout input permits full initialization, eight reference controls, and active thumbnails',()=>{const ui=setup();assert.ok(ui.ctx.Reference131);assert.equal(ui.nodes.copyLayout111.options,undefined);assert.equal(ui.rail.querySelectorAll('button').length,8);const strip=ui.body.children.find(n=>n.className==='referenceStrip131');assert.equal(strip.querySelectorAll('article').length,2);assert.equal(strip.hidden,false);assert.equal(strip.children[0].attrs['aria-current'],'true');});
test('full reference toggles off and back on; thumbnail switches reference then enters preview',async()=>{const ui=setup(),button=ui.rail.querySelectorAll('button')[0];await button.onclick();assert.equal(ui.album.pages[0].reference131.enabled,false);await ui.rail.querySelectorAll('button')[0].onclick();assert.equal(ui.album.pages[0].reference131.enabled,true);const strip=ui.body.children.find(n=>n.className==='referenceStrip131');await strip.options.open(ui.album.pages[1],1);assert.equal(ui.album.index,1);assert.equal(ui.album.pages[1].reference131.enabled,true)});
test('scrolling the hero out of view reveals logo inside home navigation and restores it on return',()=>{const ui=setup();assert.equal(ui.nodes.homeBrand79.attrs['aria-hidden'],'true');ui.hero.rect.bottom=-20;ui.events.scroll.forEach(fn=>fn());assert.equal(ui.nodes.homeBrand79.classList.contains('visible85'),true);assert.equal(ui.nodes.homeBrand79.tabIndex,0);ui.hero.rect.bottom=100;ui.events.scroll.forEach(fn=>fn());assert.equal(ui.nodes.homeBrand79.attrs['aria-hidden'],'true')});
test('fixed crop dialog repaints image immediately when transparency changes',()=>{const ui=setup();ui.ctx.Reference131.editor();const d=ui.body.children.find(n=>n.className==='referenceCrop131');assert.equal(d.dataset.fixedDialog,'true');const slider=d.querySelector('input'),before=ui.draws.length;slider.value='30';slider.oninput();assert.equal(ui.draws.length,before+2);assert.equal(ui.draws.at(-1).alpha,.7);assert.equal(d.querySelector('output').textContent,'30%');assert.equal(ui.album.pages[0].reference131,undefined);const labels=d.querySelectorAll('label');assert.equal(labels[0].textContent,'透明度 ')});
test('free crop resizes just one edge and moves independently of aspect ratio',()=>{const ctx={};vm.runInNewContext(source,ctx);const c={x:.2,y:.1,w:.5,h:.8},m=ctx.ReferenceModel131;let n=m.editCrop(c,'l',.1,.6);assert.ok(Math.abs(n.w-.4)<1e-9);assert.ok(Math.abs(n.h-.8)<1e-9);n=m.editCrop(c,'move',1,-1);assert.equal(n.x,.5);assert.equal(n.y,0);assert.equal(n.w,.5);assert.equal(n.h,.8)});
test('global dialog dragging leaves crop canvas gestures alone',()=>{const s=fs.readFileSync('revision103.js','utf8'),a=s.indexOf("document.addEventListener('pointerdown',e=>")+"document.addEventListener('pointerdown',".length,b=s.indexOf(',true);',a);const ctx={drag:null};vm.runInNewContext('this.down='+s.slice(a,b),ctx);let prevented=false;ctx.down({target:{closest:selector=>selector==='dialog,#paperPen100'?{dataset:{fixedDialog:'true'}}:null},preventDefault(){prevented=true}});assert.equal(ctx.drag,null);assert.equal(prevented,false)});
test('floating reference can be dragged beyond the board and to browser navigation origin',()=>{const s=fs.readFileSync('revision129.js','utf8'),a=s.indexOf('floating.onpointermove=e=>')+'floating.onpointermove='.length,b=s.indexOf(';floating.onpointerup=',a),ctx={windowDrag:{id:2,x:100,y:100,left:10,top:60,resize:false},floating:{style:{}}};vm.runInNewContext('this.move='+s.slice(a,b),ctx);ctx.move({pointerId:2,clientX:90,clientY:40});assert.equal(ctx.floating.style.left,'0px');assert.equal(ctx.floating.style.top,'0px');ctx.move({pointerId:2,clientX:-10,clientY:-20});assert.equal(ctx.floating.style.left,'-100px');assert.equal(ctx.floating.style.top,'-60px');assert.match(s,/document\.body\.append\(floating\)/)});
