const {chromium}=require('playwright');const fs=require('fs'),http=require('http'),path=require('path');
(async()=>{const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{const p=path.join(root,decodeURI(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));try{res.setHeader('Content-Type',({'js':'application/javascript','html':'text/html','css':'text/css','png':'image/png','woff':'font/woff'})[p.split('.').pop()]||'application/octet-stream');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end()}}).listen(8765,'127.0.0.1');const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--no-zygote','--single-process'],headless:true});const p=await b.newPage({viewport:{width:820,height:1180}});p.on('pageerror',e=>console.log('PAGEERROR',e.stack));await p.route(/https?:\/\/(?!127\.0\.0\.1)/,r=>r.abort());await p.goto('http://127.0.0.1:8765');await p.waitForFunction(()=>document.documentElement.dataset.appReady==='true');
await p.waitForFunction(()=>window.AnnotationHome);await p.evaluate(()=>document.getElementById('continueWriting').click());const assert=require('assert').strict;const set=async(id,value,event='change')=>p.evaluate(({id,value,event})=>{const e=document.getElementById(id);e.value=value;e.dispatchEvent(new Event(event,{bubbles:true}))},{id,value,event});
const click=async id=>p.evaluate(id=>document.getElementById(id).click(),id);
const snap=()=>p.evaluate(async()=>{await ZhenjiBackup.flush();return DraftStore.get('draft')});
let d=await snap();assert.equal(d.brush.name.startsWith('张旭'),true);assert.equal(+d.values.ratio,.75);assert.equal(d.values.showLines,'no');assert.equal(d.values.material,'plain');assert.equal(d.values.paperPattern,'dragon');
for(const expected of [60,80,100,200,400,600,1000,60]){await click('topSize');assert.equal((await snap()).brush.size,expected)}
for(const value of ['vertical','horizontal','mi','hidden']){await click('topLines');d=await snap();assert.equal(d.values.showLines==='yes'?d.values.ruling:'hidden',value)}
await set('quickStyle','huaisu');await set('quickSizeNumber','240');const brush=(await snap()).brush;for(const r of ['1','0.75','0.333']){await set('ratio',r);assert.deepEqual((await snap()).brush,brush)}
for(const key of await p.evaluate(()=>Object.keys(Mounting.presets))){await set('quickMount',key);await click('fitView');await click('fitView')}
await set('quickMount','square');await set('ratio','.75');await set('ratio','0.75');await set('autoScroll','off');await click('fitView');await click('fitView');
// Add two actual pointer strokes to the writing canvas.
await p.evaluate(()=>{document.querySelectorAll('dialog').forEach(d=>d.close())});const board=await p.locator('#board').boundingBox();for(const dx of [180,330]){await p.mouse.move(board.x+dx,board.y+260);await p.mouse.down();await p.mouse.move(board.x+dx+70,board.y+360,{steps:12});await p.mouse.up()}
d=await snap();assert.ok(d.flow.strokes.length>=2,'writing strokes exist');const count=d.flow.strokes.length;await click('undo');assert.equal((await snap()).flow.strokes.length,count-1);await click('redo');assert.equal((await snap()).flow.strokes.length,count);
await click('saveSettings');await p.waitForTimeout(100);await set('quickSizeNumber','60');await click('resetSettings');assert.equal((await snap()).brush.size,240);assert.equal((await snap()).flow.strokes.length,count);
// Store and restore editable work, global settings and toolbar ordering across reload.
await p.evaluate(async()=>{const d=await DraftStore.get('draft');await DraftStore.saveWork({id:'work:regression',title:'改名前',date:'2026',created:1,blob:new Blob(['test'],{type:'image/png'}),thumbnail:null,draft:d});await DraftStore.editWork('work:regression','改名后')});
await p.reload();await p.waitForFunction(()=>document.documentElement.dataset.appReady==='true'&&window.AnnotationHome);await click('continueWriting');d=await snap();assert.equal(d.flow.strokes.length,count);assert.equal(d.brush.size,240);await click('myWorks');await p.waitForFunction(()=>document.getElementById('worksGrid').textContent.includes('改名后'));await p.locator('.workCard button').filter({hasText:'编辑'}).click();await p.waitForFunction(()=>!document.getElementById('editWorkBar').hidden);await click('discardEditedWork');

// Frame editing and crop editing remain independent.
await p.locator('#photoUpload').setInputFiles(path.join(root,'museums/louvre.webp'));await p.waitForTimeout(300);await click('editPhoto');await p.waitForFunction(()=>!document.getElementById('photoEditFrame').hidden);await set('photoAspect','1');let before=await snap();assert.equal(before.photos[0].frame.w,before.photos[0].frame.h);
const frame=await p.locator('#photoEditFrame').boundingBox();await p.mouse.move(frame.x+frame.width/2,frame.y+frame.height/2);await p.mouse.down();await p.mouse.move(frame.x+frame.width/2+20,frame.y+frame.height/2+30);await p.mouse.up();let after=await snap();assert.equal(after.photos[0].crop.zoom,before.photos[0].crop.zoom);assert.notDeepEqual(after.photos[0].frame,before.photos[0].frame);
await click('photoCropMode');before=await snap();await p.evaluate(()=>{const e=document.getElementById('photoEditFrame'),r=e.getBoundingClientRect();e.setPointerCapture=()=>{};for(const [type,id,x]of [['pointerdown',10,40],['pointerdown',11,100],['pointermove',11,160],['pointerup',11,160],['pointerup',10,40]])e.dispatchEvent(new PointerEvent(type,{pointerId:id,clientX:r.x+x,clientY:r.y+50,bubbles:true,pointerType:'touch'}))});after=await snap();assert.deepEqual(after.photos[0].frame,before.photos[0].frame);assert.ok(after.photos[0].crop.zoom>before.photos[0].crop.zoom);await click('finishPhoto');
await click('removePhoto');await click('fitView');await click('fitView');await p.locator('[data-seal-key="head"]').click();await p.waitForTimeout(100);assert.equal(await p.locator('#sealInspector').isVisible(),true);const panel=await p.locator('#sealInspector').boundingBox(),seal=await p.locator('[data-seal-key="head"]').boundingBox();assert.ok(panel.width<=270);assert.ok(panel.x+panel.width<=seal.x||seal.x+seal.width<=panel.x||panel.y+panel.height<=seal.y||seal.y+seal.height<=panel.y,'seal popup does not cover seal');await set('selectedSealType','yang');assert.equal((await snap()).values.headType,'yang');await click('finishSealSelection');
await set('zoom','50','input');assert.equal((await snap()).brush.size,110);assert.equal(await p.locator('#zoomReadout').textContent(),'50%');
for(const value of ['0','8','grid','museum:louvre','museum:michelangelo','museum:raphael','none']){await set('quickScene',value);if(value!=='none')await p.waitForFunction(v=>CreativePaper.ready(v),value);await p.waitForTimeout(80);assert.equal((await snap()).values.sceneChoice,value)}
for(const [w,h]of [[390,844],[1180,820],[820,1180]]){await p.setViewportSize({width:w,height:h});await click('dockToggle');await click('dockToggle');await p.waitForTimeout(100);const bounds=await p.locator('#bottomDock').boundingBox();assert.ok(Math.abs(bounds.y+bounds.height-h)<3,'dock flush with viewport');await p.evaluate(()=>document.getElementById('topActions').scrollLeft=0);assert.ok((await p.locator('#menuToggle').boundingBox()).x>=0,'menu reachable')}
await p.evaluate(async()=>{const blob=await PortableBackup.exportData();await PortableBackup.importData(new File([blob],'backup.json'));const w=await DraftStore.get('work:regression');if(w.title!=='改名后'||!(w.blob instanceof Blob))throw Error('Backup roundtrip failed')});
console.log('PASS photo frame/crop, seal popup/type, zoom compensation, legacy and new scenes, three responsive viewports and portable backup');
console.log('PASS startup, seven brush sizes, four grids, all mount previews, ratio preservation, drawing, undo/redo, saved preferences, reload and work rename/edit');
await p.screenshot({path:'/tmp/annotation36-after.png'});
await b.close();server.close()})().catch(e=>{console.error(e);process.exit(1)});
