import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const env={Blob,Response,CompressionStream,DecompressionStream,Uint8Array};
for(const file of ['cloud-draft-codec141.js','relay-model144.js','shared-service142.js','collaboration128.js'])vm.runInNewContext(fs.readFileSync(file,'utf8'),env);
function harness(){
 const objects=new Map(),rooms=new Map(),pages=new Map(),ops=[],calls=[];let serial=0,failRPC=false,uncertain=false,failRead=false;
 const cloud={user:{id:'owner'},client:{}};
 const bucket={upload:async(path,blob,options)=>{assert.equal(options.upsert,false);objects.set(path,blob);calls.push('upload');return{data:{path}}},download:async path=>objects.has(path)?{data:objects.get(path)}:{error:{message:'missing original'}},remove:async paths=>{paths.forEach(p=>objects.delete(p));return{data:paths}},list:async prefix=>({data:[...new Set([...objects.keys()].filter(p=>p.startsWith(prefix+'/')).map(p=>p.slice(prefix.length+1).split('/')[0]))].map(name=>({name}))})};
 function from(table){const source=table==='ink_shared_rooms128'?rooms:pages;let action='select',value,filters=[],limit=Infinity;const q={select(){return q},eq(k,v){filters.push(r=>r[k]===v);return q},gt(k,v){filters.push(r=>r[k]>v);return q},order(){return q},limit(n){limit=n;return q},insert(v){action='insert';value=v;return q},update(v){action='update';value=v;return q},delete(){action='delete';return q},single:()=>run(true),maybeSingle:()=>run(true),then(a,b){return run(false).then(a,b)}};
 async function run(single){if(failRead)return{error:{message:'offline'}};let list=(table==='ink_shared_ops128'?ops:[...source.values()]).filter(r=>filters.every(f=>f(r))).slice(0,limit);if(action==='update')list=list.map(r=>{const updated={...r,...value};source.set(r.id,updated);return updated});if(action==='delete'){calls.push('delete-room');list.forEach(r=>{source.delete(r.id);for(const p of pages.values())if(p.room===r.id)pages.delete(p.id)})}if(action==='insert'){source.set(value.id,value);list=[value]}return{data:single?list[0]||null:list}}
 return q}
 cloud.client={storage:{from:name=>{assert.equal(name,'ink-shared142');return bucket}},from,rpc:async(name,v)=>{assert.equal(name,'ink_create_shared142');assert.ok(JSON.stringify(v).length<1000,'RPC never carries base64 original or stroke geometry');calls.push('atomic-rpc');if(failRPC&&!uncertain)return{error:{message:'server timeout'}};const r=rooms.get(v.room_id)||{id:v.room_id,owner:'owner',title:v.room_title,participants:['owner']},p=pages.get(v.page_id)||{id:v.page_id,room:r.id,author:'owner',draft_path142:v.draft_path,draft:{flow:{strokes:[]}},thumbnail142:v.thumbnail};rooms.set(r.id,r);pages.set(p.id,p);return uncertain?{error:{message:'response lost'}}:{data:{room:r,page:p}}}};
 const service=env.SharedService142.create({cloud,codec:env.DraftCodec141,uuid:()=>String(++serial)}),room={id:'room',owner:'owner',title:'家人练字'},page={id:'page',room:'room',author:'owner',title:'page',draft:{referenceData111:'原帖'.repeat(500000),brush:{size:37},extraSeals:[{x:.2}],photos:[{data:'original photo'}],flow:{strokes:[{id128:'original',points:[{x:.123456789,p:.456789,t:1}],geometry:{x:5,k:.6}}]}}};
 return{service,cloud,objects,rooms,pages,ops,calls,room,page,setFailure:v=>failRPC=v,setUncertain:v=>uncertain=v,setReadFailure:v=>failRead=v};
}
test('large shared original is losslessly compressed privately; atomic RPC carries small metadata',async()=>{const h=harness(),saved=await h.service.create(h.room,h.page);assert.deepEqual(h.calls,['upload','atomic-rpc']);assert.equal(h.rooms.size,1);const path=h.pages.get('page').draft_path142;assert.match(path,/^owner\/room\/owner\/page-/);assert.equal(h.pages.get('page').draft.flow.strokes.length,0);const hydrated=await h.service.hydrate(h.pages.get('page'));assert.equal(hydrated.draft.referenceData111,h.page.draft.referenceData111);assert.equal(hydrated.draft.flow.strokes[0].points[0].p,.456789);assert.equal(saved.page.draft.brush.size,37)});
test('failed atomic creation leaves no room or page and cleans only its unused upload',async()=>{const h=harness();h.setFailure(true);await assert.rejects(h.service.create(h.room,h.page),/server timeout/);assert.equal(h.rooms.size,0);assert.equal(h.pages.size,0);assert.equal(h.objects.size,0);assert.equal(h.page.draft.flow.strokes.length,1)});
test('lost response after committed atomic creation recovers the same room and original',async()=>{const h=harness();h.setUncertain(true);const saved=await h.service.create(h.room,h.page);assert.equal(saved.page.draft.flow.strokes[0].geometry.k,.6);await h.service.create(h.room,h.page);assert.equal(h.rooms.size,1);assert.equal(h.pages.size,1);assert.equal(h.objects.size,1)});
test('uncertain commit with failed recovery read never deletes an original that may be referenced',async()=>{const h=harness();h.setUncertain(true);h.setReadFailure(true);await assert.rejects(h.service.create(h.room,h.page),/response lost/);assert.equal(h.objects.size,1);assert.equal(h.rooms.size,1)});
test('final shared snapshot paginates beyond 500 operations and preserves reference, seals and photos',async()=>{const h=harness();await h.service.create(h.room,h.page);for(let seq=1;seq<=1101;seq++)h.ops.push({seq,page:'page',payload:[{kind:'put',stroke:{id128:'member-'+seq,points:[{p:seq/2000}]}}]});h.ops.push({seq:1102,page:'page',payload:[{kind:'delete',id:'original'}]});const draft=await h.service.snapshot(h.pages.get('page'));assert.equal(draft.flow.strokes.length,1101);assert.equal(draft.flow.strokes.at(-1).id128,'member-1101');assert.equal(draft.photos[0].data,'original photo');assert.equal(draft.extraSeals[0].x,.2);assert.equal(draft.referenceData111,h.page.draft.referenceData111)});
test('only owner can end/delete; end removes invitations while delete also clears private originals',async()=>{const h=harness();await h.service.create(h.room,h.page);h.rooms.get('room').participants.push('child');h.cloud.user={id:'child'};await assert.rejects(h.service.close(h.room),/只有发起人/);await assert.rejects(h.service.remove(h.room),/只有发起人/);assert.equal(h.calls.includes('delete-room'),false);h.cloud.user={id:'owner'};const closed=await h.service.close(h.room);assert.equal(closed.closed142,true);assert.deepEqual(Array.from(closed.participants),['owner']);assert.equal(h.pages.size,1);await h.service.remove(h.room);assert.equal(h.rooms.size,0);assert.equal(h.pages.size,0);assert.equal(h.objects.size,0)});

const source=fs.readFileSync('collaboration128.js','utf8');
function lifecycleHarness({cloudError=false}={}){
 const calls=[],records=new Map(),r={id:'r',owner:'owner',title:'亲笔家人'},pages=[{id:'p1',title:'第1页'},{id:'p2',title:'第2页'}];
 const q={select(){return q},eq(){return q},order:async()=>({data:pages})};
 const context={uid:()=> 'owner',room:r,page:null,closing142:false,generation:0,timer:0,backup:null,cached:{},navigator:{onLine:true},confirm:()=>true,clearInterval(){},setInterval(){},Date,Object,Error,document:{dispatchEvent(){}},Event:class{},dialog:{open:true},check:v=>v.data,mark:text=>calls.push(text),A:{finish(){},workExport135:async({draft})=>{calls.push('render-'+draft.page);return new Blob(['4K'])},toast(){},setWorkIdentity128(){}},db:{from:()=>q},service142:{close:async()=>{calls.push('close');return{closed142:true,participants:['owner']}},snapshot:async p=>({page:p.id,flow:{strokes:[{id128:'all-members'}]}}),remove:async()=>{calls.push('delete');return{cleanupPending:false}}},DraftStore:{get:async id=>records.get(id),saveWork:async record=>{calls.push('local-'+record.id);records.set(record.id,record)}},cloud:{saveNow101:async record=>{calls.push('cloud-'+record.id);if(cloudError)throw Error('network failed');return true}},forget142:async()=>calls.push('forget'),open:async()=>calls.push('open')};
 const line=source.split('\n').find(l=>l.trim().startsWith('async function lifecycle142('));vm.runInNewContext(line,context);return{context,r,calls,records};
}
test('end archives every page locally and to editable cloud before deleting the shared group',async()=>{const h=lifecycleHarness();await h.context.lifecycle142(h.r);assert.equal(h.records.size,2);assert.ok(h.calls.indexOf('close')<h.calls.indexOf('render-p1'));assert.ok(h.calls.indexOf('cloud-shared-final:r:p2')<h.calls.indexOf('delete'));assert.equal(h.context.closing142,false);assert.equal([...h.records.values()][0].draft.flow.strokes[0].id128,'all-members')});
test('cloud archive failure retains closed shared pages for retry and preserves local original',async()=>{const h=lifecycleHarness({cloudError:true});await assert.rejects(h.context.lifecycle142(h.r),/network failed/);assert.equal(h.r.closed142,true);assert.equal(h.records.size,1);assert.equal(h.calls.includes('delete'),false);assert.equal(h.calls.includes('forget'),false);assert.equal(h.context.closing142,false)});
test('failed start never assigns a partial room or replaces current writing',async()=>{const original={flow:{strokes:[{points:[{x:1,p:.8}]}]},brush:{size:37},editingWork110:{id:'original'}},ctx={uid:()=> 'owner',page:null,room:null,A:{finish(){},getState:()=>original,sharedThumbnail142:()=> 'data:image/jpeg;base64,dGVzdA=='},crypto:{randomUUID:()=> 'new-id'},clone142:structuredClone,identify:(s,i,id)=>({...s,id128:id+'-'+i}),navigator:{onLine:true},service142:{create:async()=>{throw Error('creation failed')}},mark(){},persistCache133(){throw Error('must not persist partial room')},cached:{pages:{}}};vm.runInNewContext(source.split('\n').find(l=>l.trim().startsWith('async function create142(')),ctx);await assert.rejects(ctx.create142(original,'家人'),/creation failed/);assert.equal(ctx.room,null);assert.equal(original.flow.strokes[0].id128,undefined);assert.equal(original.editingWork110.id,'original');assert.equal(Object.keys(ctx.cached.pages).length,0)});
test('account switch during original compression cannot upload to the new account',async()=>{const h=harness(),service=env.SharedService142.create({cloud:h.cloud,uuid:()=> 'revision',codec:{pack:async value=>{h.cloud.user={id:'other'};return env.DraftCodec141.pack(value)}}});await assert.rejects(service.create(h.room,h.page),/账号已切换/);assert.equal(h.objects.size,0);assert.equal(h.rooms.size,0)});
test('canceling end leaves invitations, shared pages and personal works untouched',async()=>{const h=lifecycleHarness();h.context.confirm=()=>false;await h.context.lifecycle142(h.r);assert.equal(h.calls.length,0);assert.equal(h.r.closed142,undefined);assert.equal(h.records.size,0)});
test('delete removes associated own co-writing copies and invitations, while original source work remains',async()=>{const h=lifecycleHarness(),c=h.context;const sourceWork={id:'source',title:'原作品'},shared={id:'shared-copy',sharedRoom142:'r',cloud141:{owner:'owner'}};h.records.set(sourceWork.id,sourceWork);h.records.set(shared.id,shared);c.cached={pages:{r:[]},drafts:{}};const q={select(){return q},eq(k,v){assert.equal(k,'owner');assert.equal(v,'owner');return q},or(filter){assert.match(filter,/shared:r\|%/);return Promise.resolve({data:[]})}};c.db.from=table=>{assert.ok(['ink_shared_pages128','ink_works'].includes(table),'never delete users');return table==='ink_works'?q:{select(){return this},eq(){return this},order:async()=>({data:[]})}};c.DraftStore.get=async id=>id==='works-index'?[{id:'source'},{id:'shared-copy'}]:h.records.get(id);c.DraftStore.deleteWorks=async ids=>{for(const id of ids)h.records.delete(id)};const deleted=[];c.CloudDraft141={deleteLocal:async id=>deleted.push(id)};await c.lifecycle142(h.r,true);assert.deepEqual(deleted,['shared-copy']);assert.ok(h.records.has('source'));assert.equal(h.records.has('shared-copy'),false);assert.ok(h.calls.includes('close'));assert.ok(h.calls.includes('delete'));assert.equal(h.calls.some(call=>call.startsWith('render-')),false)});
