import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
const worker=fs.readFileSync('sw.js','utf8');
function sw(fetch,put=async()=>{}){const listeners={},pending=[],entries=new Map(),cache={put:async(k,r)=>{await put();entries.set(typeof k==='string'?k:k.url,r)},match:async k=>entries.get(typeof k==='string'?k:k.url)?.clone()};const ctx={URL,Response,Request,Promise,Map,setTimeout,clearTimeout,fetch,caches:{open:async()=>cache,keys:async()=>[],delete:async()=>{}},self:{location:{origin:'https://iinnkk.me'},registration:{scope:'https://iinnkk.me/'},addEventListener:(n,fn)=>listeners[n]=fn}};vm.createContext(ctx);vm.runInContext(worker,ctx);async function request(url,nav=false){let result;const r=new Request('https://iinnkk.me/'+url);if(nav)Object.defineProperty(r,'mode',{value:'navigate'});listeners.fetch({request:r,waitUntil:p=>pending.push(p),respondWith:p=>result=p});return result}return{ctx,request,pending,entries};}
test('opening a writer document does not fetch its runtime dependencies again',async()=>{const calls=[];const h=sw(async req=>{calls.push(req.url);return new Response('<script src="app-runtime.abcdef.js"></script>')});assert.equal((await h.request('engine165.html',true)).status,200);await Promise.all(h.pending);assert.equal(calls.length,1)});
test('concurrent runtime requests share one fetch and do not wait for a slow cache write',async()=>{let calls=0,unlock;const h=sw(async()=>{calls++;return new Response('ready')},()=>new Promise(r=>unlock=r));const [a,b]=await Promise.all([h.request('app-runtime.abcdef.js'),h.request('app-runtime.abcdef.js')]);assert.equal(await a.text(),'ready');assert.equal(await b.text(),'ready');assert.equal(calls,1);unlock();await Promise.all(h.pending);assert.equal(await(await h.request('app-runtime.abcdef.js')).text(),'ready');assert.equal(calls,1)});
test('cache quota failure cannot turn a successful resource response into a loading failure',async()=>{const h=sw(async()=>new Response('available'),async()=>{throw Error('quota')});assert.equal(await(await h.request('app-runtime.abcdef.js')).text(),'available');await Promise.all(h.pending)});
test('only content-addressed runtime files use the persistent runtime policy',()=>{const h=sw(()=>{});assert.equal(vm.runInContext("immutableRuntime165(new URL('https://iinnkk.me/app-runtime.a123.js'))",h.ctx),true);assert.equal(vm.runInContext("immutableRuntime165(new URL('https://iinnkk.me/revision65.js'))",h.ctx),false)});
test('seal fonts are demand loaded, deduplicated and never preload unrelated families',async()=>{const calls=[],events=[],timers=[];const ctx={Map,Set,Event,setTimeout:fn=>timers.push(fn),document:{fonts:{load:async(...a)=>{calls.push(a);return[{}]}},dispatchEvent:e=>events.push(e.type)}};vm.runInNewContext(fs.readFileSync('seal.js','utf8'),ctx);assert.equal(calls.length,0);const p=ctx.SealEngine.ensureFont('yishan','手笔');assert.equal(p,ctx.SealEngine.ensureFont('yishan','笔手'));await p;assert.equal(calls.length,1);assert.match(calls[0][0],/YiShanBeiSeal/);await ctx.SealEngine.ensureFont('chongxi','手');assert.equal(calls.length,2);assert.equal(timers.length,1);timers[0]();assert.deepEqual(events,['seal-font-ready165']);assert.equal(ctx.chongxiSealReady,true)});
test('navigation is owned by the existing preview panel before its configuration tabs',()=>{const nodes=new Map();function node(id){const n={id,children:[],append(...items){this.children.push(...items)},parentElement:{append(){}}};nodes.set(id,n);return n}const nav=node('writerModes53'),steps=node('steps'),rail=node('rail'),note=node('note');node('board');const source=fs.readFileSync('revision54.js','utf8');const mount=source.match(/const effects=E\('section',\{id:'previewEffects55',hidden:''\}\);.*?;\$\('board'\)\.parentElement.append\(effects\);/)[0];const ctx={E:(_tag,a)=>node(a.id),$:id=>nodes.get(id),steps,rail,note};vm.runInNewContext(mount,ctx);assert.deepEqual(nodes.get('previewEffects55').children,[nav,steps,rail,note]);const runtime=JSON.parse(fs.readFileSync('runtime-sources106.json'));assert.ok(!runtime.scripts.includes('revision164.js'));assert.ok(!fs.readFileSync('revision161.js','utf8').includes('document.body.append(nav)'))});
