import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';

test('public cross-device catalogue loads without a token, and one atomic commit publishes metadata',async()=>{
 const writes=[],calls=[];
 const data={version:74,entries:{oracle:{title:'甲骨文',place:'中国·河南安阳',museum:'殷墟',pages:['timeline/pages/oracle/a.jpg']}}};
 const payload=Buffer.from(JSON.stringify(data)).toString('base64');
 const respond=(body,status=200)=>({ok:status<400,status,json:async()=>body});
 const fetch=async(url,opts={})=>{url=String(url);calls.push([url,opts]);if(url==='https://iinnkk.me/timeline/manifest.json')return respond(data);if(url.endsWith('/contents/timeline/manifest.json?ref=main'))return respond({content:payload});if(url.endsWith('/git/ref/heads/main'))return respond({object:{sha:'parent'}});if(url.endsWith('/git/commits/parent'))return respond({tree:{sha:'base-tree'}});if(url.endsWith('/git/blobs'))return respond({sha:'manifest-blob'});if(url.endsWith('/git/trees')){writes.push(JSON.parse(opts.body));return respond({sha:'new-tree'})}if(url.endsWith('/git/commits'))return respond({sha:'new-commit'});if(url.endsWith('/git/refs/heads/main'))return respond({ref:'heads/main'});throw Error(url)};
 const sandbox={setTimeout:()=>1,clearTimeout(){},AbortController,navigator:{onLine:false},window:{},location:{href:'https://iinnkk.me/'},fetch,URL,Blob,Uint8Array,TextDecoder,atob,btoa,Date,CustomEvent:class{constructor(type){this.type=type}},document:{dispatchEvent:()=>{}}};
 vm.runInNewContext(readFileSync('reference-upload138.js','utf8'),sandbox);sandbox.ReferenceUpload138=sandbox.window.ReferenceUpload138;vm.runInNewContext(readFileSync('cover-crop145.js','utf8'),sandbox);sandbox.CoverCrop145=sandbox.window.CoverCrop145;vm.runInNewContext(readFileSync('timeline74-cloud.js','utf8'),sandbox);
 const cloud=sandbox.window.TimelineCloud74;
 await cloud.ready;
 assert.equal(cloud.get('oracle').pages[0],'timeline/pages/oracle/a.jpg');
 assert.equal(calls[0][1].headers?.Authorization,undefined);
 cloud.connect('github_pat_example_secret');
 await cloud.publish('oracle',{title:'甲骨文（已修订）',place:'中国·安阳',museum:'殷墟',pages:[]});
 assert.equal(cloud.get('oracle').pages.length,0);
 assert.deepEqual(writes[0].tree.map(item=>item.path),['timeline/manifest.json']);
 assert.ok(calls.filter(([,opts])=>opts.method==='POST').every(([,opts])=>opts.headers.Authorization==='Bearer github_pat_example_secret'));
});
test('real publish path uploads only added files, keeps prior pages and maps mixed drag order into one commit',async()=>{const old='timeline/pages/hanshi/old.jpg',file=new Blob(['new-image']);file.name='补页02.jpg';const data={version:74,entries:{hanshi:{pages:[old],pageNames:['原页01.jpg']}}},payload=Buffer.from(JSON.stringify(data)).toString('base64');let tree,manifest;const response=b=>({ok:true,json:async()=>b});const fetch=async(url,options={})=>{url=String(url);if(url==='https://iinnkk.me/timeline/manifest.json')return response(data);if(url.includes('/contents/timeline/manifest.json?ref=main'))return response({content:payload});if(url.endsWith('/git/ref/heads/main'))return response({object:{sha:'parent'}});if(url.endsWith('/git/commits/parent'))return response({tree:{sha:'base-tree'}});if(url.endsWith('/git/blobs')){const body=JSON.parse(options.body);if(body.encoding==='utf-8')manifest=JSON.parse(body.content);return response({sha:body.encoding==='base64'?'new-image':'manifest'})}if(url.endsWith('/git/trees')){tree=JSON.parse(options.body);return response({sha:'tree'})}if(url.endsWith('/git/commits'))return response({sha:'commit'});if(url.endsWith('/git/refs/heads/main'))return response({});throw Error(url)};const sandbox={setTimeout:()=>1,clearTimeout(){},AbortController,navigator:{onLine:false},window:{},location:{href:'https://iinnkk.me/'},fetch,URL,Blob,Uint8Array,TextDecoder,atob,btoa,Date,CustomEvent:class{},Image:class{naturalWidth=900;naturalHeight=1200;async decode(){}},document:{dispatchEvent(){},createElement:()=>({getContext:()=>({fillRect(){},drawImage(){}}),toBlob:cb=>cb(new Blob(['encoded-image']))})}};vm.runInNewContext(readFileSync('reference-upload138.js','utf8'),sandbox);sandbox.ReferenceUpload138=sandbox.window.ReferenceUpload138;vm.runInNewContext(readFileSync('cover-crop145.js','utf8'),sandbox);sandbox.CoverCrop145=sandbox.window.CoverCrop145;vm.runInNewContext(readFileSync('timeline74-cloud.js','utf8'),sandbox);const cloud=sandbox.window.TimelineCloud74;await cloud.ready;cloud.connect('github_pat_test');const result=await cloud.publish('hanshi',{cover143:file,coverCrop145:{zoom:2,x:25,y:75},pages:[file,old],pageNames:[file.name,'原页01.jpg']},[file]);assert.equal(result.cover143,result.pages[0]);assert.deepEqual(JSON.parse(JSON.stringify(result.coverCrop145)),{zoom:2,x:25,y:75});assert.equal(result.pages.length,2);assert.equal(result.pages[1],old);assert.equal(result.pageNames[0],file.name);assert.equal(manifest.entries.hanshi.pages[1],old);assert.equal(tree.base_tree,'base-tree');assert.equal(tree.tree.length,2);assert.ok(tree.tree[0].path.endsWith('/'+file.name))});
