const{chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),fixture=Function('return '+fs.readFileSync(path.join(__dirname,'ui93.cjs'),'utf8').match(/const fixture=(`[^]*?`);/)[1])();
const server=http.createServer((req,res)=>{try{const file=path.join(root,req.url.split('?')[0]==='/'?'index.html':req.url.split('?')[0]);res.setHeader('Content-Type',({js:'application/javascript',html:'text/html',css:'text/css',webp:'image/webp',png:'image/png'})[path.extname(file).slice(1)]||'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end()}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});for(const width of [320,390,768,1280]){
const p=await browser.newPage({viewport:{width,height:width===768?1366:1000},hasTouch:true,serviceWorkers:'block'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/supabase51.js*',r=>r.fulfill({contentType:'application/javascript',body:fixture}));await p.route(/https:\/\/.*supabase.co\/auth\/v1\/settings/,r=>r.fulfill({json:{external:{}}}));await p.route(/https?:\/\/(?!127\.0\.0\.1)(?!.*supabase.co\/auth\/v1\/settings)/,r=>r.abort());await p.goto('http://127.0.0.1:'+server.address().port);await p.waitForFunction(()=>window.Revision104?.ready);if(process.env.QA_CJK_FONT){await p.addStyleTag({content:'@font-face{font-family:QA94;src:url(data:font/otf;base64,'+fs.readFileSync(process.env.QA_CJK_FONT).toString('base64')+')}body,button,.heroPerson94,#annotationHome .annotationIntro :is(strong,small),#paletteNote94{font-family:QA94,system-ui!important}'});await p.evaluate(()=>document.fonts.ready)}
const coverage=await p.evaluate(()=>HeritageCoverage102);assert.equal(coverage.total,1273);assert.equal(coverage.countries.length,173);for(const id of ['writerLeft90','bottomIcons39','board','quoteExpanded'])assert(await p.locator('#'+id).evaluate(el=>{const e=new MouseEvent('contextmenu',{bubbles:true,cancelable:true});el.dispatchEvent(e);return e.defaultPrevented}));await p.evaluate(()=>{document.body.classList.remove('home-open');AnnotationApp.showWriter();document.getElementById('sceneChoice').value='none';AnnotationApp.refresh()});await p.waitForTimeout(250);
assert(await p.locator('#writingHint100').isVisible());
await p.locator('#topSize').click();assert(await p.locator('#paperPen100').isVisible());assert.deepEqual(await p.locator('#paperPen100 [data-source=sizeNumber] div button').allTextContents(),['5','10','15','20','30','60','120']);assert.deepEqual(await p.locator('#paperPen100 [data-source=zoom] div button').allTextContents(),['50%','100%','150%','200%','300%','400%','500%']);const initial=await p.locator('#paperPen100 [data-source=sizeNumber] input').inputValue();await p.locator('#paperPen100 [data-source=sizeNumber] .adjust103 button').last().click();assert.equal(+await p.locator('#paperPen100 [data-source=sizeNumber] input').inputValue(),+initial+1);const pb=await p.locator('#paperPen100').boundingBox();await p.mouse.move(pb.x+80,pb.y+18);await p.mouse.down();await p.mouse.move(pb.x+100,pb.y+50);await p.mouse.up();const dragged=await p.locator('#paperPen100').boundingBox();assert(dragged.y>pb.y);await p.locator('#paperPen100 header button').click();

await p.evaluate(()=>document.getElementById('readQuote').click());await p.waitForTimeout(100);
const readerBefore=await p.locator('#dailyDialog').boundingBox(),textBox=await p.locator('#quoteExpanded').boundingBox(),startX=textBox.x+textBox.width*.5,startY=textBox.y+Math.min(20,textBox.height/2);const dragSession=await p.context().newCDPSession(p);
await dragSession.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:startX,y:startY,id:1}]});await dragSession.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:startX+25,y:startY+35,id:1}]});await dragSession.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(50);const readerAfter=await p.locator('#dailyDialog').boundingBox();assert(Math.abs(readerAfter.y-readerBefore.y)>10);const css=await p.locator('#quoteExpanded').evaluate(el=>({select:getComputedStyle(el).userSelect,callout:getComputedStyle(el).getPropertyValue('-webkit-touch-callout'),touch:getComputedStyle(el).touchAction}));assert.equal(css.select,'none');assert.equal(css.touch,'none');assert.equal(await p.locator('#board').evaluate(el=>{const e=new MouseEvent('contextmenu',{bubbles:true,cancelable:true});el.dispatchEvent(e);return e.defaultPrevented}),true);await dragSession.detach();await p.evaluate(()=>document.getElementById('dailyDialog').close());
const head=await p.evaluate(()=>AnnotationApp.sealItems().find(v=>v.key==='head'));assert.equal(head.config.text,'今日亲笔');assert.equal(head.config.font,'yishan');assert.equal(head.config.type,'yang');assert.equal(head.config.shape,'tall');assert.equal(head.config.layout,'horizontal');
await p.evaluate(()=>AnnotationApp.editSeal('head',{x:.96,y:.001}));const movedHead=await p.evaluate(()=>AnnotationApp.sealItems().find(v=>v.key==='head'));assert.equal(movedHead.x,.96);assert.equal(movedHead.y,.001);
for(const pos of [.25,.7]){
await p.evaluate(()=>{if(!AnnotationApp.isOverview55())document.getElementById('fitView').click()});await p.waitForTimeout(150);
const nav=await p.locator('#previewEffects55 .finalSteps54').evaluate(el=>({padding:getComputedStyle(el).paddingRight,justify:getComputedStyle(el).justifyContent}));assert.equal(nav.justify,'center');assert.equal(await p.locator('#previewFloating97 button:visible').count(),0);assert.equal(await p.locator('#previewEffects55 .finalSteps54 button:visible').filter({hasText:'流变'}).count(),0);assert.equal(await p.locator('#previewEffects55 .finalSteps54 button:visible').filter({hasText:'文创'}).count(),0);
if(pos===.7){const c=await p.context().newCDPSession(p),b=await p.locator('#live').boundingBox(),cx=b.x+b.width/2,cy=b.y+b.height/2;const send=(type,d)=>c.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'?[]:[{x:cx-d,y:cy,id:1},{x:cx+d,y:cy,id:2}]});await send('touchStart',30);await send('touchMove',70);await send('touchEnd',0);await p.waitForTimeout(120);assert(await p.evaluate(()=>AnnotationApp.isOverview55()));await c.detach()}
const before=await p.evaluate(pos=>{const f=AnnotationApp.previewFrame94(),r=document.getElementById('live').getBoundingClientRect();return{f,r:r.toJSON(),state:AnnotationApp.getState(),pos}},pos);
const box=await p.locator('#live').boundingBox();const x=box.x+box.width*.5,y=box.y+box.height*pos;
await p.touchscreen.tap(x,y);await p.waitForTimeout(70);assert(await p.evaluate(()=>AnnotationApp.isOverview55()));await p.touchscreen.tap(x,y);await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>AnnotationApp.isOverview55()),false);assert(await p.locator('#previewEffects55').isHidden());assert.equal(await p.evaluate(()=>document.body.classList.contains('preview-open56')),false);
const after=await p.evaluate(()=>AnnotationApp.getState());assert.equal(after.flow.strokes.length,before.state.flow.strokes.length);if(pos===.25)global.firstCamera=after.camera;else assert(Math.abs(after.camera.y-global.firstCamera.y)>.05);
}
assert(await p.locator('#export + #previewRandom79 svg').count());await p.locator('#export').click();assert(await p.locator('#downloadDialog').isVisible());for(const key of ['qr','credit','palette'])assert(await p.locator('#download_'+key).isChecked());await p.evaluate(()=>document.getElementById('downloadDialog').close());
await p.evaluate(()=>AnnotationApp.focusPoint({x:2,y:3}));await p.waitForTimeout(120);
const c=await p.context().newCDPSession(p),b=await p.locator('#live').boundingBox(),cx=b.x+b.width/2,cy=b.y+b.height/2;
const startZoom=await p.evaluate(()=>+document.getElementById('zoom').value);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx-30,y:cy,id:1},{x:cx+30,y:cy,id:2}]});await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx-70,y:cy,id:1},{x:cx+70,y:cy,id:2}]});await p.waitForTimeout(100);assert(await p.locator('#paperPen100').isVisible());assert.notEqual(await p.evaluate(()=>+document.getElementById('zoom').value),startZoom);await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.locator('#paperPen100 header button').click();
const send=(type,dx=0,dy=0)=>c.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'?[]:[{x:cx-30+dx,y:cy+dy,id:1},{x:cx+30+dx,y:cy+dy,id:2}]});
for(const dy of [-65,65]){await send('touchStart');await send('touchMove',0,dy);await send('touchEnd');await p.waitForTimeout(150);const flags=await p.evaluate(()=>Revision97.flags);assert.equal(flags.top,dy<0);assert.equal(flags.bottom,dy<0);assert.equal(await p.evaluate(()=>AnnotationApp.isOverview55()),false)}
await send('touchStart');await send('touchEnd');await p.waitForTimeout(70);assert.equal(await p.evaluate(()=>AnnotationApp.isOverview55()),false);await send('touchStart');await send('touchEnd');await p.waitForTimeout(120);assert(await p.evaluate(()=>AnnotationApp.isOverview55()));assert.deepEqual(await p.evaluate(()=>Revision97.flags),{top:true,bottom:true,config:true});await p.evaluate(()=>{for(const part of ['top','bottom','config'])Revision97.setPart(part,false)});await p.waitForTimeout(100);await c.detach();
const credit=await p.evaluate(async()=>{const chosen=Revision94.palettes[0];Revision94.apply(chosen);if(!AnnotationApp.getState().paletteCredit96.idea.startsWith(chosen.idea.replace(/[。！？；，\s]+$/,'')))throw Error('Original idea lost');const saved=AnnotationApp.getState();await AnnotationApp.restoreDraft(saved);const calls=[],original=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(text,x,y,...args){if(String(text).includes('设计理念｜')||String(text).includes('今日亲笔·')||(this.canvas.id==='paper'&&this.font.includes('system-ui,-apple-system,sans-serif')))calls.push({text,x,y,w:this.canvas.width,h:this.canvas.height});return original.call(this,text,x,y,...args)};try{document.getElementById('fitView').click();await new Promise(r=>setTimeout(r,100));const previewCalls=calls.splice(0);if(!previewCalls.some(v=>v.text.startsWith('设计理念｜')))throw Error('Preview credit missing');if(previewCalls.some(v=>v.text.includes('今日亲笔·')))throw Error('Preview brand must be hidden');const canvas=await AnnotationApp.finalPreview54(1500);window.qaExport96=canvas;const rows=[...new Set(previewCalls.filter(v=>!v.text.includes('今日亲笔·')).map(v=>v.y))];if(rows.length>2)throw Error('More than two idea rows');return {calls,state:AnnotationApp.getState()}}finally{CanvasRenderingContext2D.prototype.fillText=original}});
const off=await p.evaluate(async()=>{const saved=AnnotationApp.getState(),s=structuredClone(saved);s.exportPrefs={...s.exportPrefs,qr:false,credit:false,palette:false};await AnnotationApp.restoreDraft(s);const calls=[],orig=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(t,...a){calls.push(String(t));return orig.call(this,t,...a)};try{AnnotationApp.exportCanvas(1000)}finally{CanvasRenderingContext2D.prototype.fillText=orig;await AnnotationApp.restoreDraft(saved)}return calls});assert(!off.some(t=>t.includes('设计理念｜')||t.includes('今日亲笔·')));assert(credit.state.paletteCredit96);const idea=credit.calls.find(v=>v.text.startsWith('设计理念｜')),caption=credit.calls.find(v=>v.text==='今日亲笔·iinnkk.me·见墨如我');assert(idea&&caption);assert.equal(idea.x,idea.w/2);assert(caption.x>caption.w/2);assert(idea.y>caption.y&&idea.y<idea.h);
await p.evaluate(()=>{if(!AnnotationApp.isOverview55())document.getElementById('fitView').click()});await p.waitForTimeout(200);
const slide=async(dx,dy)=>{const box=await p.locator('#live').boundingBox(),x=box.x+box.width*.5,y=box.y+box.height*.5,cdp=await p.context().newCDPSession(p);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx,y:y+dy,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(200);await cdp.detach()};
await slide(0,-80);assert.deepEqual(await p.evaluate(()=>Revision97.flags),{top:true,bottom:true,config:true});assert(await p.evaluate(()=>AnnotationApp.isOverview55()));const paletteBefore=await p.evaluate(()=>AnnotationApp.getState().paletteCredit96?.name);await slide(0,-80);assert.notEqual(await p.evaluate(()=>AnnotationApp.getState().paletteCredit96?.name),paletteBefore);const mountBefore=await p.evaluate(()=>AnnotationApp.getState().mountKey);await slide(-80,0);assert.notEqual(await p.evaluate(()=>AnnotationApp.getState().mountKey),mountBefore);await slide(80,0);assert.equal(await p.evaluate(()=>AnnotationApp.getState().mountKey),mountBefore);await slide(0,80);assert.deepEqual(await p.evaluate(()=>Revision97.flags),{top:false,bottom:true,config:false});assert(await p.locator('#bottomIcons39').isHidden());
assert(await p.locator('#previewEffects55 .finalNote54').isVisible());assert(await p.locator('#previewEffects55 .finalSteps54').isVisible());assert(await p.locator('#previewEffects55 .finalSteps54 button').filter({hasText:/^比例$/}).isVisible());assert.equal(await p.title(),'今日亲笔');await p.evaluate(()=>document.title='旧标题');await p.waitForTimeout(30);assert.equal(await p.title(),'今日亲笔');assert.equal(await p.locator('dialog input[type=number]:visible').count(),0);await p.evaluate(()=>document.querySelector('#previewEffects55 .finalSteps54 button:nth-child(2)').click());const artists=await p.locator('#previewEffects55 .finalRail54 button').allTextContents();assert(artists.includes('史籀')&&artists.includes('钟繇')&&artists.includes('王铎'));const layout=await p.evaluate(()=>({bottom:document.getElementById('previewEffects55').getBoundingClientRect().bottom,height:innerHeight}));assert(Math.abs(layout.height-layout.bottom)<4,JSON.stringify(layout));const tabs=p.locator('#previewEffects55 .finalSteps54 button');let limit=0;for(let i=0;i<await tabs.count();i++){const t=tabs.nth(i);if(!await t.isVisible())continue;await t.click();await p.waitForTimeout(60);const h=await p.locator('#previewEffects55 .finalRail54').evaluate(el=>el.getBoundingClientRect().height);if(!limit)limit=h;assert(h<=limit+1,JSON.stringify({label:await t.textContent(),h,limit}))}const photosBefore=await p.evaluate(()=>AnnotationApp.getState().photos.length);const photo=tabs.filter({hasText:/^图文$/});await photo.click();for(const name of ['明信片','签名照','世界遗产','电影海报','音乐专辑封面','书籍封面']){await p.locator('#previewEffects55 .finalRail54 button').filter({hasText:new RegExp('^'+name+'$')}).click();assert.equal(await p.evaluate(()=>Revision62.getOverlay()),'');assert.equal(await p.evaluate(()=>AnnotationApp.getState().photos.length),photosBefore)}
if(width===768)await p.screenshot({path:'/tmp/preview97.png'});console.log('preview gestures / compact options / title-free photo layouts',width,'PASS');await p.close()
}}finally{await browser?.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
