const {chromium}=require('playwright');

const fs=require('fs'),path=require('path'),http=require('http');const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{const name=path.join(root,req.url.split('?')[0]==='/'?'index.html':req.url.split('?')[0]);try{res.setHeader('Content-Type',({'js':'application/javascript','css':'text/css','html':'text/html','svg':'image/svg+xml','png':'image/png','woff':'font/woff','woff2':'font/woff2'})[name.split('.').pop()]||'application/octet-stream');res.end(fs.readFileSync(name))}catch{res.statusCode=404;res.end()}}).listen(8765,'127.0.0.1');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const errors=[];try{
for(const width of [320,390,768,1280]){
 const p=await browser.newPage({viewport:{width,height:900},serviceWorkers:'block'});p.on('pageerror',e=>{errors.push(e.message);console.log('BROWSER ERROR',e.stack)});await p.route(/https?:\/\/(?!127\.0\.0\.1)/,r=>r.abort());await p.goto('http://127.0.0.1:8765');await p.waitForFunction(()=>window.Revision90?.ready);
 const layout=await p.evaluate(()=>{const r=id=>document.getElementById(id).getBoundingClientRect().toJSON();return {theme:r('themeSwitch90'),reminder:r('homeMoments'),account:r('account47'),hero:document.querySelector('.annotationBrand h1').getBoundingClientRect().toJSON(),nav:r('homeQuick47'),sub:document.querySelector('.annotationBrand p').getBoundingClientRect().width}});
 assert(layout.theme.right<=layout.reminder.left+1,'theme beside reminder '+width);assert(Math.abs(layout.theme.y-layout.account.y)<3,'header alignment '+width);assert(layout.hero.right<=layout.theme.left+1,'header overlap '+width);assert(layout.sub<=layout.hero.width+1);assert(layout.nav.height<80,'one navigation row');
 for(const [name,id] of [['大字','single'],['临帖','copy'],['图文','photo'],['创作','letter']]){
 await p.evaluate(()=>{document.body.classList.add('home-open');document.getElementById('annotationHome').scrollTop=0});await p.locator('#homeQuick47 button').filter({hasText:new RegExp('^'+name+'$')}).click();await p.waitForFunction(()=>!document.body.classList.contains('home-open'),{timeout:15000});await p.waitForTimeout(300);
 assert(await p.evaluate(()=>!document.body.classList.contains('home-open')),'mode enters writer '+name);
 const state=await p.evaluate(()=>({open:document.getElementById('dailyDialog').open,tools:[...document.querySelectorAll('#topActions button')].filter(e=>e.offsetWidth&&getComputedStyle(e).display!=='none').map(e=>({id:e.id,right:e.getBoundingClientRect().right,left:e.getBoundingClientRect().left,svg:e.querySelectorAll('svg').length,caption:e.querySelectorAll('span').length})),quotes:getComputedStyle(document.getElementById('topQuotes')).display}));
 assert.equal(state.open,id==='letter','reader default '+name);assert(state.tools.every(t=>t.right<=width+1&&t.left>=0),'toolbar fits '+width+' '+name);assert(state.tools.every(t=>t.svg===1&&t.caption===1),'one icon/caption '+name);assert.notEqual(state.quotes,'none');assert(state.tools.some(t=>t.id==='topQuotes'),'good quotes permanent');
 if(id==='letter'){await p.locator('#readerTitle90').click();assert(await p.locator('#readerJump90').isVisible());assert(await p.locator('.readerList90 button').count()>0);await p.locator('.readerList90 button').first().click();assert(!await p.locator('#readerJump90').isVisible());await p.evaluate(()=>document.getElementById('dailyDialog').close())}
 }
 if(width===390){
  await p.locator('#menuToggle').click();await p.locator('#writerSettings90').click();assert(await p.locator('#brushDialog').isVisible());await p.evaluate(()=>document.getElementById('brushDialog').close());await p.locator('#menuToggle').click();
  for(const cat of await p.evaluate(()=>[...new Set(DailyQuotes38.all().map(q=>q.cat))])){await p.evaluate(cat=>{DailyQuotes38.select(cat);document.getElementById('readQuote').click()},cat);const colour=await p.evaluate(()=>({ink:AnnotationApp.getState().brush.color,bg:getComputedStyle(document.getElementById('dailyDialog')).backgroundColor,head:getComputedStyle(document.querySelector('#dailyDialog .dialogHead')).backgroundColor,body:getComputedStyle(document.querySelector('#dailyDialog .dialogBody')).backgroundColor}));assert.equal(colour.head,'rgba(0, 0, 0, 0)');assert.equal(colour.body,'rgba(0, 0, 0, 0)');assert(colour.bg.includes('0.7'),'translucent reader '+cat);await p.evaluate(()=>document.getElementById('dailyDialog').close())}
  await p.evaluate(()=>{if(!AnnotationApp.isOverview55())document.getElementById('fitView').click()});assert(await p.locator('#previewWatermark90').isVisible());await p.locator('#board').dblclick({position:{x:170,y:250}});await p.waitForTimeout(400);assert(!await p.locator('#previewWatermark90').isVisible(),'double tap enters writing');
  const before=await p.evaluate(()=>AnnotationApp.getState().flow.strokes.length);const r=await p.locator('#board').boundingBox();await p.mouse.move(r.x+160,r.y+240);await p.mouse.down();await p.mouse.move(r.x+190,r.y+270,{steps:12});await p.mouse.up();await p.waitForTimeout(150);const written=await p.evaluate(()=>AnnotationApp.getState().flow.strokes.length);assert(written>before,'actual stroke');await p.locator('#undo').click();assert.equal(await p.evaluate(()=>AnnotationApp.getState().flow.strokes.length),before);await p.locator('#redo').click();assert.equal(await p.evaluate(()=>AnnotationApp.getState().flow.strokes.length),written,'redo restores stroke');
 }
 if(process.env.SCREENSHOT_DIR)await p.screenshot({path:path.join(process.env.SCREENSHOT_DIR,'ink-writer-'+width+'.png')});console.log('PASS viewport '+width+'; four modes');
}
const clock=await browser.newPage({viewport:{width:390,height:844},timezoneId:'Asia/Kuala_Lumpur',serviceWorkers:'block'});
clock.on('pageerror',e=>errors.push(e.message));await clock.route(/https?:\/\/(?!127\.0\.0\.1)/,r=>r.abort());
await clock.goto('http://127.0.0.1:8765');await clock.waitForFunction(()=>window.Revision90?.ready);await clock.clock.setFixedTime(new Date('2026-09-30T09:59:00Z'));await clock.evaluate(()=>Revision90.autoTheme());assert.equal(await clock.evaluate(()=>document.body.dataset.homeTheme),'river');
await clock.clock.setFixedTime(new Date('2026-09-30T10:00:00Z'));await clock.evaluate(()=>Revision90.autoTheme());assert.equal(await clock.evaluate(()=>document.body.dataset.homeTheme),'stars');
await clock.locator('#themeSwitch90').click();assert.equal(await clock.evaluate(()=>document.body.dataset.homeTheme),'river');await clock.evaluate(()=>Revision90.autoTheme());assert.equal(await clock.evaluate(()=>document.body.dataset.homeTheme),'river');
await clock.clock.setFixedTime(new Date('2026-09-30T22:00:00Z'));await clock.evaluate(()=>Revision90.autoTheme());assert.equal(await clock.evaluate(()=>document.body.dataset.homeTheme),'river');
await clock.evaluate(()=>{const h=document.getElementById('annotationHome');h.querySelector('footer').style.minHeight='2000px';h.scrollTop=300});await clock.waitForTimeout(400);assert(await clock.locator('#homeBrand79').evaluate(e=>e.classList.contains('visible85')));await clock.evaluate(()=>document.getElementById('annotationHome').scrollTop=0);await clock.waitForTimeout(400);assert(!await clock.locator('#homeBrand79').evaluate(e=>e.classList.contains('visible85')));
console.log('PASS local 06:00/18:00 boundaries, manual override and scrolling brand');
assert.deepEqual(errors,[]);console.log('PASS reader categories, quick jump, preview double tap and stroke undo/redo; no browser errors');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
