const{chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),fixture=Function('return '+fs.readFileSync(path.join(__dirname,'ui93.cjs'),'utf8').match(/const fixture=(`[^]*?`);/)[1])();
const server=http.createServer((req,res)=>{try{const file=path.join(root,req.url.split('?')[0]==='/'?'index.html':req.url.split('?')[0]);res.setHeader('Content-Type',({js:'application/javascript',html:'text/html',css:'text/css',webp:'image/webp',png:'image/png'})[path.extname(file).slice(1)]||'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end()}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});for(const width of [320,390,768,1280,1920]){
const p=await browser.newPage({viewport:{width,height:1000},hasTouch:true,serviceWorkers:'block'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/supabase51.js*',r=>r.fulfill({contentType:'application/javascript',body:fixture}));await p.route(/https:\/\/.*supabase.co\/auth\/v1\/settings/,r=>r.fulfill({json:{external:{}}}));await p.route(/https?:\/\/(?!127\.0\.0\.1)(?!.*supabase.co\/auth\/v1\/settings)/,r=>r.abort());await p.goto('http://127.0.0.1:'+server.address().port);await p.waitForFunction(()=>window.Revision94?.ready);if(process.env.QA_CJK_FONT){await p.addStyleTag({content:'@font-face{font-family:QA94;src:url(data:font/otf;base64,'+fs.readFileSync(process.env.QA_CJK_FONT).toString('base64')+')}body,button,.heroPerson94,#annotationHome .annotationIntro :is(strong,small),#paletteNote94{font-family:QA94,system-ui!important}'});await p.evaluate(()=>document.fonts.ready)}
await p.locator('.heroPicture94 img').evaluate(img=>img.decode());const hero=await p.locator('.annotationIntro').boundingBox();assert(Math.abs(hero.width-width)<2);assert(Math.abs(hero.x)<2);assert.equal(await p.locator('.heroPerson94').count(),8);const imageSrc=await p.locator('.heroPicture94 img').evaluate(img=>img.currentSrc);assert(imageSrc.includes(width<=600?'hero-mobile94.webp':'hero-wide94.webp'));const labels=await p.locator('.heroPerson94').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().toJSON()));assert(labels.every(r=>r.left>=-1&&r.right<=width+2));const colours=await p.locator('.annotationIntro strong').first().evaluate(n=>getComputedStyle(n).color);assert.equal(colours,width<=600?'rgb(255, 247, 233)':'rgb(25, 58, 66)');assert(await p.locator('[data-id="arabic-bawwab94"]').count()>0);if(width===390||width===1280)await p.screenshot({path:'/tmp/ink94-home-'+width+'.png'});
await p.evaluate(()=>{document.getElementById('annotationHome').scrollTop=500;document.querySelector('.annotationBrand').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}))});assert.equal(await p.locator('#annotationHome').evaluate(h=>h.scrollTop),0);if(width<=600){await p.evaluate(()=>{const h=document.getElementById('annotationHome');h.scrollTop=500;for(let i=0;i<2;i++)h.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerType:'touch',clientY:20}))});assert.equal(await p.locator('#annotationHome').evaluate(h=>h.scrollTop),0)}
await p.locator('#account47').click();await p.waitForTimeout(200);assert.equal(await p.locator('#supplierEntry80').isVisible(),false);assert(await p.locator('.accountClose94').isVisible());await p.locator('#cloudAccount75 [aria-label="邮箱"]').fill('writer@example.com');await p.locator('#cloudAccount75 [aria-label="密码"]').fill('valid password94');await p.getByRole('button',{name:'登录书房',exact:true}).click();await p.locator('.profilePrivacy93').waitFor();assert(await p.locator('#cloudAccount75>.cloud75-head .accountExit94').isVisible());const close=await p.locator('.accountClose94').boundingBox(),exit=await p.locator('.accountExit94').boundingBox();assert(close.x>exit.x);await p.locator('.accountClose94').click();
await p.locator('#homeQuick47 button').filter({hasText:/^大字$/}).click();await p.waitForFunction(()=>!document.body.classList.contains('home-open'));assert.equal(await p.locator('#writerLeft90').evaluate(n=>n.firstElementChild.id),'annotationHomeButton');const toolbar=await p.locator('#writerLeft90').boundingBox(),logo=await p.locator('#annotationHomeButton').boundingBox();assert(Math.abs(toolbar.x-logo.x)<2);
if(!await p.evaluate(()=>AnnotationApp.isOverview55()))await p.locator('#fitView').click();await p.evaluate(()=>{const q=document.getElementById('quickMount');q.value='song';q.dispatchEvent(new Event('change'))});await p.locator('#previewRandom79').click();await p.locator('#paletteNote94').waitFor({state:'visible'});const frame=await p.evaluate(()=>AnnotationApp.previewFrame94()),note=await p.locator('#paletteNote94').evaluate(n=>n.getBoundingClientRect().toJSON()),board=await p.locator('#board').boundingBox();assert(note.top>=board.y+frame.sheetBottom);assert(note.right<=board.x+frame.x+frame.width+1);assert(note.bottom<=board.y+frame.sheetBottom+frame.gap+1);
const stories=await p.evaluate(()=>({size:Revision94.palettes.length,names:new Set(Revision94.palettes.map(p=>p.name)).size,contrast:Revision94.palettes.every(p=>Revision93.contrast(p.paper,p.ink)>=4.5),ideas:Revision94.palettes.every(p=>p.idea)}));assert.deepEqual(stories,{size:50,names:50,contrast:true,ideas:true});const actions=await p.locator('.previewActions93').boundingBox(),keys=await p.locator('.previewActions93 button').evaluateAll(ns=>ns.map(n=>n.getBoundingClientRect().toJSON()));assert(actions.width<=286&&actions.height<=36);assert(keys.every(k=>k.height<=34&&Math.abs(k.width-keys[0].width)<1));await p.locator('#previewReset73').click();assert(!await p.locator('#paletteNote94').isVisible());await p.locator('#previewRandom79').click();if(width===390)await p.screenshot({path:'/tmp/ink94-preview.png'});
await p.locator('#annotationHomeButton').click();await p.waitForFunction(()=>document.body.classList.contains('home-open'));assert.equal(await p.locator('#annotationHome').evaluate(n=>n.scrollTop),0);assert.deepEqual(errors,[]);await p.close();console.log('PASS '+width+': responsive ensemble, account header, left logo, Arabic milestone, 50 colour stories, paperweight and anchored caption');
}}finally{await browser?.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
