const{chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),fixture=Function('return '+fs.readFileSync(path.join(__dirname,'ui93.cjs'),'utf8').match(/const fixture=(`[^]*?`);/)[1])();
const server=http.createServer((req,res)=>{try{const file=path.join(root,req.url.split('?')[0]==='/'?'index.html':req.url.split('?')[0]);res.setHeader('Content-Type',({js:'application/javascript',html:'text/html',css:'text/css',webp:'image/webp',png:'image/png'})[path.extname(file).slice(1)]||'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end()}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});for(const width of [320,390,768,1280]){
const p=await browser.newPage({viewport:{width,height:1000},hasTouch:true,serviceWorkers:'block'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/supabase51.js*',r=>r.fulfill({contentType:'application/javascript',body:fixture}));await p.route(/https:\/\/.*supabase.co\/auth\/v1\/settings/,r=>r.fulfill({json:{external:{}}}));await p.route(/https?:\/\/(?!127\.0\.0\.1)(?!.*supabase.co\/auth\/v1\/settings)/,r=>r.abort());await p.goto('http://127.0.0.1:'+server.address().port);await p.waitForFunction(()=>window.Revision94?.ready);if(process.env.QA_CJK_FONT){await p.addStyleTag({content:'@font-face{font-family:QA94;src:url(data:font/otf;base64,'+fs.readFileSync(process.env.QA_CJK_FONT).toString('base64')+')}body,button,.heroPerson94,#annotationHome .annotationIntro :is(strong,small),#paletteNote94{font-family:QA94,system-ui!important}'});await p.evaluate(()=>document.fonts.ready)}
await p.evaluate(()=>{document.body.classList.remove('home-open');AnnotationApp.showWriter();document.getElementById('sceneChoice').value='none';AnnotationApp.refresh()});await p.waitForTimeout(250);
for(const pos of [.25,.7]){
await p.evaluate(()=>{if(!AnnotationApp.isOverview55())document.getElementById('fitView').click()});await p.waitForTimeout(150);
if(pos===.7){const c=await p.context().newCDPSession(p),b=await p.locator('#live').boundingBox(),cx=b.x+b.width/2,cy=b.y+b.height/2;const send=(type,d)=>c.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'?[]:[{x:cx-d,y:cy,id:1},{x:cx+d,y:cy,id:2}]});await send('touchStart',30);await send('touchMove',70);await send('touchEnd',0);await p.waitForTimeout(120);assert(await p.evaluate(()=>AnnotationApp.isOverview55()));await c.detach()}
const before=await p.evaluate(pos=>{const f=AnnotationApp.previewFrame94(),r=document.getElementById('live').getBoundingClientRect();return{f,r:r.toJSON(),state:AnnotationApp.getState(),pos}},pos);
const box=await p.locator('#live').boundingBox();const x=box.x+box.width*.5,y=box.y+box.height*pos;
await p.touchscreen.tap(x,y);await p.waitForTimeout(70);assert(await p.evaluate(()=>AnnotationApp.isOverview55()));await p.touchscreen.tap(x,y);await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>AnnotationApp.isOverview55()),false);assert(await p.locator('#previewEffects55').isHidden());assert.equal(await p.evaluate(()=>document.body.classList.contains('preview-open56')),false);
const after=await p.evaluate(()=>AnnotationApp.getState());assert.equal(after.flow.strokes.length,before.state.flow.strokes.length);if(pos===.25)global.firstCamera=after.camera;else assert(Math.abs(after.camera.y-global.firstCamera.y)>.05);
}
await p.evaluate(()=>AnnotationApp.focusPoint({x:2,y:3}));await p.waitForTimeout(120);
const c=await p.context().newCDPSession(p),b=await p.locator('#live').boundingBox(),cx=b.x+b.width/2,cy=b.y+b.height/2;
const send=(type,dx=0,dy=0)=>c.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'?[]:[{x:cx-30+dx,y:cy+dy,id:1},{x:cx+30+dx,y:cy+dy,id:2}]});
for(const [dx,dy] of [[65,0],[-65,0],[0,65],[0,-65]]){const before=await p.evaluate(()=>AnnotationApp.getState());await send('touchStart');await send('touchMove',dx,dy);await send('touchEnd');await p.waitForTimeout(120);const after=await p.evaluate(()=>AnnotationApp.getState());const scale=Math.max(b.width/4,b.height/(4/(+before.values.ratio||.75)))*(+documentDummy(before)/100);function documentDummy(v){return +v.values.zoom||200}const axis=dx?'x':'y',sheet=axis==='x'?4:4/(+before.values.ratio||.75),screen=(dx?b.width:b.height)/scale,expected=Math.max(0,Math.min(sheet-screen,before.camera[axis]+Math.sign(dx||dy)*screen));assert(Math.abs(after.camera[axis]-expected)<.02,JSON.stringify({width,dx,dy,before:before.camera,after:after.camera,expected,scale,zoom:before.values.zoom,ratio:before.values.ratio}));assert.equal(after.flow.strokes.length,before.flow.strokes.length)}
await send('touchStart');await send('touchEnd');await p.waitForTimeout(70);assert.equal(await p.evaluate(()=>AnnotationApp.isOverview55()),false);await send('touchStart');await send('touchEnd');await p.waitForTimeout(120);assert(await p.evaluate(()=>AnnotationApp.isOverview55()));await c.detach();
const credit=await p.evaluate(async()=>{Revision94.apply(Revision94.palettes[0]);const saved=AnnotationApp.getState();await AnnotationApp.restoreDraft(saved);const calls=[],original=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(text,x,y,...args){if(String(text).includes('配色理念｜')||String(text).includes('今日亲笔·'))calls.push({text,x,y,w:this.canvas.width,h:this.canvas.height});return original.call(this,text,x,y,...args)};try{const canvas=await AnnotationApp.finalPreview54(1500);window.qaExport96=canvas;return {calls,state:AnnotationApp.getState()}}finally{CanvasRenderingContext2D.prototype.fillText=original}});
assert(credit.state.paletteCredit96);const idea=credit.calls.find(v=>v.text.startsWith('配色理念｜')),caption=credit.calls.find(v=>v.text==='今日亲笔·iinnkk.me·见墨如我');assert(idea&&caption);assert.equal(idea.x,idea.w/2);assert.equal(caption.x,caption.w/2);assert(idea.y>caption.y&&idea.y<idea.h);if(width===390){await p.evaluate(()=>{document.body.replaceChildren(window.qaExport96);window.qaExport96.style.width='390px'});await p.screenshot({path:'/tmp/export96.png',fullPage:true})}
console.log('preview / four-direction page swipe / two-finger double tap / export credit',width,'PASS');await p.close()
}}finally{await browser?.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
