import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const src=readFileSync(new URL('../app.js',import.meta.url),'utf8');const code=src.slice(src.indexOf('let writingTapTimer96='),src.indexOf('let writingViewFrame='));
function harness(){const actions=[],timers=new Map();let id=0;const s={previousTap:null,overview:false,photoEditing:false,touches:new Map(),signatureReturn110:null,document:{body:{classList:{contains:()=>false}}},fitPaper:()=>actions.push('preview'),toggleSignature110:()=>actions.push('signature'),$:()=>({click:()=>actions.push('undo')}),requestAnimationFrame:fn=>fn(),window:{},setTimeout:fn=>{timers.set(++id,fn);return id},clearTimeout:id=>timers.delete(id)};vm.createContext(s);vm.runInContext(code,s);return{s,actions,tap:t=>s.recordWritingTap96({c:{x:100,y:100}},t),flush:()=>{for(const fn of [...timers.values()])fn()}}}
for(const [count,action]of [[1,null],[2,'preview'],[3,'signature'],[4,'undo']])test(count+' two-finger taps resolve once without triggering shorter gestures',()=>{const h=harness();for(let i=0;i<count;i++)h.tap(i*150);assert.deepEqual(h.actions,[]);h.flush();assert.deepEqual(h.actions,action?[action]:[])});
test('drag or cancellation cancels pending multi-tap',()=>{const h=harness();h.tap(0);h.tap(150);h.s.resetWritingTap96();h.flush();assert.deepEqual(h.actions,[])});
test('preview or ongoing contact prevents deferred writing action',()=>{for(const key of ['overview','contact']){const h=harness();h.tap(0);h.tap(150);if(key==='overview')h.s.overview=true;else h.s.touches.set(1,{});h.flush();assert.deepEqual(h.actions,[])}});
test('new sequence after long gap starts fresh',()=>{const h=harness();h.tap(0);h.tap(500);h.flush();assert.deepEqual(h.actions,[])});
test('double tap in signature returns to body instead of preview',()=>{const h=harness();h.s.signatureReturn110={size:70,zoom:100};h.tap(0);h.tap(150);h.flush();assert.deepEqual(h.actions,['signature'])});
test('preview bitmap resolution follows physical screen pixels within memory budget',()=>{const code=src.slice(src.indexOf('function previewInkUnit('),src.indexOf('function previewInkBitmap('));const s={dpr:2};vm.createContext(s);vm.runInContext(code,s);assert.equal(s.previewInkUnit({w:4,h:4},250),500);const b={w:4,h:200},unit=s.previewInkUnit(b,1000);assert.ok(unit*unit*b.w*b.h<=8000000);assert.ok(unit*Math.max(b.w,b.h)<=8192)});
