/* Official-account JS-SDK signing. A website-login AppID is NOT a public-account AppID. */
let access={value:'',expires:0},ticket={value:'',expires:0};
const env=(k:string)=>Deno.env.get(k)||'';
export async function handler(request:Request){const origins=env('SITE_ORIGINS').split(',').map(s=>s.trim()).filter(Boolean),origin=request.headers.get('Origin')||'';if(!origins.includes(origin))return new Response('Forbidden',{status:403});const headers={'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Methods':'POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Vary':'Origin','Cache-Control':'no-store'};if(request.method==='OPTIONS')return new Response(null,{status:204,headers});if(request.method!=='POST')return new Response('Method not allowed',{status:405,headers});try{
 if(!env('WECHAT_MP_APP_ID')||!env('WECHAT_MP_APP_SECRET'))return Response.json({error:'not_configured'},{status:503,headers});const data=await request.json(),url=new URL(data.url);if(!origins.includes(url.origin)||url.hash||url.username||url.password)return new Response('Forbidden',{status:403,headers});const now=Date.now();
 if(access.expires<now){const target=new URL('https://api.weixin.qq.com/cgi-bin/token');target.search=new URLSearchParams({grant_type:'client_credential',appid:env('WECHAT_MP_APP_ID'),secret:env('WECHAT_MP_APP_SECRET')}).toString();const r=await fetch(target),d=await r.json();if(!r.ok||d.errcode||!d.access_token)throw Error();access={value:d.access_token,expires:now+(Number(d.expires_in)-300)*1000}}
 if(ticket.expires<now){const r=await fetch('https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token='+encodeURIComponent(access.value)+'&type=jsapi'),d=await r.json();if(!r.ok||d.errcode||!d.ticket)throw Error();ticket={value:d.ticket,expires:now+(Number(d.expires_in)-300)*1000}}
 const nonceStr=crypto.randomUUID(),timestamp=Math.floor(now/1000),payload=`jsapi_ticket=${ticket.value}&noncestr=${nonceStr}&timestamp=${timestamp}&url=${url.href}`,digest=await crypto.subtle.digest('SHA-1',new TextEncoder().encode(payload)),signature=Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');return Response.json({appId:env('WECHAT_MP_APP_ID'),nonceStr,timestamp,signature},{headers});
 }catch{return Response.json({error:'wechat_signature_unavailable'},{status:502,headers})}}
Deno.serve(handler);
