import {createRemoteJWKSet,jwtVerify} from 'jose';
export const uid=()=>crypto.randomUUID();
export const hash=async s=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(v=>v.toString(16).padStart(2,'0')).join('');
const cookie=(r,k)=>r.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith(k+'='))?.slice(k.length+1);
export const entitled=u=>!!u&&(u.role==='founder'||u.role==='saint'||Date.now()-u.created<7*86400000);
export async function register(env,identity,name){let u=await env.DB.prepare('SELECT * FROM users WHERE identity=?').bind(identity).first();if(u)return u;const id=uid();await env.DB.batch([env.DB.prepare('INSERT OR IGNORE INTO users(id,identity,name,role,created) VALUES (?,?,?,?,?)').bind(id,identity,String(name||'亲笔书家').slice(0,50),'member',Date.now()),env.DB.prepare("INSERT OR IGNORE INTO site_state(key,value) SELECT 'founder', id FROM users WHERE identity=?").bind(identity),env.DB.prepare("UPDATE users SET role='founder' WHERE id=(SELECT value FROM site_state WHERE key='founder')")]);return env.DB.prepare('SELECT * FROM users WHERE identity=?').bind(identity).first()}
export async function user(request,env){const token=cookie(request,'ink_session');if(token){const u=await env.DB.prepare('SELECT u.* FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.id=? AND s.expires>?').bind(await hash(token),Date.now()).first();if(u)return u}
// These headers are used only on the trusted Sites dispatcher deployment, never on a self-hosted Worker.
if(env.SITES_AUTH==='enabled'){const id=request.headers.get('oai-authenticated-user-id');if(id){let name=request.headers.get('oai-authenticated-user-full-name');try{if(request.headers.get('oai-authenticated-user-full-name-encoding')==='percent-encoded-utf8'||request.headers.get('oai-authenticated-user-full-name-encoding')==='percent-encoded-utf-8')name=decodeURIComponent(name||'')}catch{}return register(env,'sites:'+id,name||'亲笔书家')}}return null}
export const providerNames={wechat:'微信',xiaohongshu:'小红书',huawei:'华为',apple:'Apple',google:'Google'};
function config(env,p){let all={};try{all=JSON.parse(env.OIDC_PROVIDERS||'{}')}catch{}const c=all[p];return c?.clientId&&c?.clientSecret&&c?.issuer&&c?.discovery?c:null}
export function providers(env){return Object.entries(providerNames).map(([id,name])=>({id,name,enabled:id==='wechat'?!!(env.WECHAT_APP_ID&&env.WECHAT_APP_SECRET):!!config(env,id)}))}
async function metadata(c){const u=new URL(c.discovery);if(u.protocol!=='https:')throw Error('Identity configuration requires HTTPS');const r=await fetch(u,{signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('登录服务暂不可用');const m=await r.json();if(m.issuer!==c.issuer)throw Error('Identity issuer mismatch');for(const k of ['authorization_endpoint','token_endpoint','jwks_uri'])if(new URL(m[k]).protocol!=='https:')throw Error('Identity endpoint requires HTTPS');return m}
export async function auth(request,env,path){const origin=new URL(request.url).origin,p=path.split('/')[3];if(path==='/api/auth/logout'){if(request.method!=='POST')return new Response('Method not allowed',{status:405});const t=cookie(request,'ink_session');if(t)await env.DB.prepare('DELETE FROM sessions WHERE id=?').bind(await hash(t)).run();return new Response('{}',{headers:{'content-type':'application/json','set-cookie':'ink_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'}})}
if(!providerNames[p])return new Response('Unknown provider',{status:404});const c=config(env,p),wechat=p==='wechat'&&env.WECHAT_APP_ID&&env.WECHAT_APP_SECRET;if(!c&&!wechat)return Response.json({error:'该账号登录尚未完成平台授权，请先使用已启用的登录方式。'},{status:503});
const callback=origin+'/api/auth/'+p+'/callback';
if(path.endsWith('/start')){const state=uid(),nonce=uid(),verifier=uid()+uid();await env.DB.prepare('INSERT INTO oauth_states(id,provider,verifier,nonce,expires) VALUES (?,?,?,?,?)').bind(await hash(state),p,verifier,nonce,Date.now()+600000).run();let url;if(wechat){url=new URL('https://open.weixin.qq.com/connect/qrconnect');url.search=new URLSearchParams({appid:env.WECHAT_APP_ID,redirect_uri:callback,response_type:'code',scope:'snsapi_login',state}).toString();url.hash='wechat_redirect'}else{const m=await metadata(c);url=new URL(m.authorization_endpoint);const challenge=btoa(String.fromCharCode(...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=/g,'');url.search=new URLSearchParams({client_id:c.clientId,response_type:'code',redirect_uri:callback,scope:c.scope||'openid profile email',state,nonce,...(p==='apple'?{response_mode:'form_post'}:{code_challenge:challenge,code_challenge_method:'S256'})}).toString()}
return new Response(null,{status:302,headers:{location:url.href,'set-cookie':`ink_oauth=${state}; Path=/api/auth; HttpOnly; Secure; SameSite=${p==='apple'?'None':'Lax'}; Max-Age=600`,'cache-control':'no-store'}})}
if(path.endsWith('/callback')){const params=request.method==='POST'?new URLSearchParams(await request.text()):new URL(request.url).searchParams;const state=params.get('state');if(!state||cookie(request,'ink_oauth')!==state||!params.get('code'))return new Response('登录验证失败，请重新登录',{status:400});const row=await env.DB.prepare('DELETE FROM oauth_states WHERE id=? AND provider=? AND expires>? RETURNING *').bind(await hash(state),p,Date.now()).first();if(!row)return new Response('登录已过期',{status:400});let identity,name;if(wechat){const url=new URL('https://api.weixin.qq.com/sns/oauth2/access_token');url.search=new URLSearchParams({appid:env.WECHAT_APP_ID,secret:env.WECHAT_APP_SECRET,code:params.get('code'),grant_type:'authorization_code'}).toString();const t=await fetch(url).then(r=>r.json());if(!t.openid||!t.access_token)throw Error('微信授权失败');const u=new URL('https://api.weixin.qq.com/sns/userinfo');u.search=new URLSearchParams({access_token:t.access_token,openid:t.openid,lang:'zh_CN'}).toString();const info=await fetch(u).then(r=>r.json());identity='wechat:'+t.openid;name=info.nickname}else{const m=await metadata(c);const t=await fetch(m.token_endpoint,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,grant_type:'authorization_code',code:params.get('code'),redirect_uri:callback,...(p==='apple'?{}:{code_verifier:row.verifier})}),signal:AbortSignal.timeout(15000)}).then(r=>r.json());if(!t.id_token)throw Error('账号授权失败');const {payload}=await jwtVerify(t.id_token,createRemoteJWKSet(new URL(m.jwks_uri)),{issuer:c.issuer,audience:c.clientId,algorithms:['RS256','ES256']});if(payload.nonce!==row.nonce||!payload.sub)throw Error('账号验证失败');identity=p+':'+payload.sub;name=payload.name||'亲笔书家'}
const u=await register(env,identity,name),token=uid()+uid();await env.DB.prepare('INSERT INTO sessions(id,user_id,expires) VALUES (?,?,?)').bind(await hash(token),u.id,Date.now()+30*86400000).run();return new Response(null,{status:303,headers:{location:'/?signedIn=1','set-cookie':`ink_session=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`,'cache-control':'no-store'}})}return new Response('Not found',{status:404})}
