import {nearby} from './nearby47.mjs';
import {auth,user,entitled,providers,uid} from './auth47.mjs';
const json=(body,status=200)=>Response.json(body,{status,headers:{'cache-control':'no-store','x-content-type-options':'nosniff'}});
class Problem extends Error{constructor(status,message){super(message);this.status=status}}
const need=(ok,status=403,message='没有此操作权限')=>{if(!ok)throw new Problem(status,message)};
const text=(v,max=100)=>String(v||'').trim().slice(0,max);
const num=(v,min,max)=>Math.max(min,Math.min(max,Number(v)||0));
async function body(r,max=100000){need(Number(r.headers.get('content-length')||0)<=max,413,'内容太大');const s=await r.text();need(new TextEncoder().encode(s).length<=max,413,'内容太大');try{return JSON.parse(s)}catch{throw new Problem(400,'提交内容格式不正确')}}
const publicUser=u=>u?{id:u.id,name:u.name,role:u.role,created:u.created,full:entitled(u),trialUntil:u.created+7*86400000}:null;
const q=(env,sql,...args)=>env.DB.prepare(sql).bind(...args);
async function getWork(env,id,u){const w=await q(env,'SELECT w.*,u.name author FROM works w JOIN users u ON u.id=w.owner WHERE w.id=?',id).first();need(w,404,'作品不存在');need(w.visibility==='public'||w.owner===u?.id||u?.role==='founder',404,'作品未公开');return w}
async function workList(env,where,args=[]){return (await q(env,`SELECT w.id,w.owner,w.title,w.visibility,w.featured,w.parent,w.created,w.allow_copy,u.name author,(SELECT COUNT(*) FROM likes WHERE work_id=w.id) likes,(SELECT COUNT(*) FROM comments WHERE work_id=w.id) comments FROM works w JOIN users u ON u.id=w.owner WHERE ${where} ORDER BY w.featured DESC,w.created DESC LIMIT 100`,...args).all()).results}
const mediaURL=id=>'/api/media/'+encodeURIComponent(id);
async function route(r,env){const url=new URL(r.url),path=url.pathname,method=r.method;
if(!path.startsWith('/api/'))return env.ASSETS?env.ASSETS.fetch(r):new Response('Not found',{status:404});
need(env.DB&&env.BUCKET,503,'在线服务尚未配置，本机书写和作品仍可使用');
if(!['GET','HEAD','OPTIONS'].includes(method)&&!path.endsWith('/callback'))need(r.headers.get('origin')===url.origin,403,'请从本站页面提交');
if(path.startsWith('/api/auth/'))return auth(r,env,path);
const u=await user(r,env);const logged=()=>need(u,401,'请先登录');const founder=()=>{logged();need(u.role==='founder',403,'仅书仙可管理网站')};
if(path==='/api/session')return json({user:publicUser(u),providers:providers(env),sitesSignIn:env.SITES_AUTH==='enabled'});
if(path==='/api/site'&&method==='GET'){const row=await q(env,"SELECT value,revision FROM site_state WHERE key='content'").first();return json({content:row?JSON.parse(row.value):{},revision:row?.revision||0,templates:(await q(env,'SELECT * FROM templates WHERE hidden=0 ORDER BY position').all()).results.map(t=>({...t,config:JSON.parse(t.config)}))})}
if(path==='/api/settings'){logged();if(method==='GET')return json(JSON.parse(u.settings));if(method==='PUT'){const data=await body(r,150000);await q(env,'UPDATE users SET settings=? WHERE id=?',JSON.stringify(data),u.id).run();return json({saved:true})}}
if(path==='/api/profile'&&method==='PATCH'){logged();const data=await body(r);need(text(data.name),400,'请输入名称');await q(env,'UPDATE users SET name=? WHERE id=?',text(data.name,50),u.id).run();return json({saved:true})}
if(path==='/api/stats'){logged();if(method==='POST'){const d=await body(r);need(/^[0-9a-f-]{36}$/.test(d.id||''),400,'记录编号不正确');need(/^\d{4}-\d{2}-\d{2}$/.test(d.day||''),400,'日期不正确');await q(env,'INSERT OR IGNORE INTO activity(id,user_id,day,seconds,characters,strokes) VALUES (?,?,?,?,?,?)',d.id,u.id,d.day,num(d.seconds,0,3600),num(d.characters,0,10000),num(d.strokes,0,10000)).run();return json({saved:true})}const stats=await q(env,'SELECT COUNT(DISTINCT day) days,COALESCE(SUM(seconds),0) seconds,COALESCE(SUM(characters),0) characters,COALESCE(SUM(strokes),0) strokes FROM activity WHERE user_id=?',u.id).first();return json(stats)}
if(path==='/api/works'){if(method==='GET'){const mine=url.searchParams.get('mine');if(mine)logged();return json({works:await workList(env,mine?'w.owner=?':"w.visibility='public'",mine?[u.id]:[])})}if(method==='POST'){logged();const d=await body(r);let parent=null;if(d.parent){const orig=await getWork(env,text(d.parent),u);need(orig.allow_copy,403,'作者尚未开放临摹');parent=orig.id}const id=uid(),now=Date.now();await q(env,'INSERT INTO works(id,owner,title,parent,created,updated) VALUES (?,?,?,?,?,?)',id,u.id,text(d.title)||'亲笔真迹',parent,now,now).run();return json({id,shareURL:url.origin+'/?work='+id})}}
const wm=path.match(/^\/api\/works\/([\w-]+)(?:\/(image|draft|like|comments|series))?$/);if(wm){const [,id,op]=wm,w=await getWork(env,id,u);if(['PUT','PATCH','DELETE'].includes(method)&&!['like','comments'].includes(op)){logged();need(w.owner===u.id||u.role==='founder')}
if(!op&&method==='GET')return json({work:{...w,image:mediaURL(id),draft:undefined},comments:(await q(env,'SELECT c.id,c.body,c.created,u.name author FROM comments c JOIN users u ON u.id=c.user_id WHERE c.work_id=? ORDER BY c.created LIMIT 100',id).all()).results,likes:(await q(env,'SELECT COUNT(*) count FROM likes WHERE work_id=?',id).first()).count});
if(!op&&method==='PATCH'){const d=await body(r);need(!d.visibility||['private','public'].includes(d.visibility),400,'可见性设置不正确');if(d.visibility==='public')need(w.image,400,'请先上传作品图片');await q(env,'UPDATE works SET title=?,visibility=?,allow_copy=?,featured=CASE WHEN ?=\'private\' THEN 0 ELSE featured END,updated=? WHERE id=?',text(d.title)||w.title,d.visibility||w.visibility,d.allowCopy===undefined?w.allow_copy:Number(!!d.allowCopy),d.visibility||w.visibility,Date.now(),id).run();return json({saved:true})}
if(!op&&method==='DELETE'){await env.DB.batch([q(env,'DELETE FROM likes WHERE work_id=?',id),q(env,'DELETE FROM comments WHERE work_id=?',id),q(env,'UPDATE works SET parent=NULL WHERE parent=?',id),q(env,'DELETE FROM works WHERE id=?',id)]);await Promise.all([w.image&&env.BUCKET.delete(w.image),w.draft&&env.BUCKET.delete(w.draft)]);return json({deleted:true})}
if(op==='image'&&method==='PUT'){const data=await r.arrayBuffer();need(data.byteLength<=12*1024*1024,413,'作品图片请小于12MB');const b=new Uint8Array(data);need(b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71,400,'请上传PNG作品');const key='works/'+id+'/image.png';await env.BUCKET.put(key,data,{httpMetadata:{contentType:'image/png'}});await q(env,'UPDATE works SET image=?,updated=? WHERE id=?',key,Date.now(),id).run();return json({saved:true})}
if(op==='draft'){logged();need(w.owner===u.id||u.role==='founder');need(entitled(u),403,'试用已结束，书圣可使用云端再次编辑');if(method==='PUT'){const d=await body(r,20*1024*1024);need(Array.isArray(d.flow?.strokes),400,'笔迹数据不完整');const key='works/'+id+'/draft.json';await env.BUCKET.put(key,JSON.stringify(d),{httpMetadata:{contentType:'application/json'}});await q(env,'UPDATE works SET draft=? WHERE id=?',key,id).run();return json({saved:true})}need(w.draft,404,'此作品未保存可编辑笔迹');const obj=await env.BUCKET.get(w.draft);need(obj,404,'笔迹暂不可用');return new Response(obj.body,{headers:{'content-type':'application/json','cache-control':'no-store'}})}
if(op==='like'&&method==='POST'){logged();need(w.visibility==='public',400,'作品尚未公开');const d=await body(r);await q(env,d.liked?'INSERT OR IGNORE INTO likes(user_id,work_id) VALUES (?,?)':'DELETE FROM likes WHERE user_id=? AND work_id=?',u.id,id).run();return json({saved:true})}
if(op==='comments'&&method==='POST'){logged();need(w.visibility==='public',400,'作品尚未公开');const d=await body(r),content=text(d.body,1000);need(content,400,'请写下点评');const recent=await q(env,'SELECT COUNT(*) n FROM comments WHERE user_id=? AND created>?',u.id,Date.now()-60000).first();need(recent.n<6,429,'请稍后再点评');await q(env,'INSERT INTO comments(id,user_id,work_id,body,created) VALUES (?,?,?,?,?)',uid(),u.id,id,content,Date.now()).run();return json({saved:true})}
if(op==='series')return json({works:await workList(env,"(w.id=? OR w.parent=? OR w.id=?) AND w.visibility='public'",[w.parent||id,w.parent||id,id])});}
if(path.startsWith('/api/media/')){const id=path.slice(11),w=await getWork(env,id,u);need(w.image,404,'图片尚未上传');const obj=await env.BUCKET.get(w.image);need(obj,404,'图片暂不可用');return new Response(obj.body,{headers:{'content-type':'image/png','cache-control':'private, no-store','x-content-type-options':'nosniff'}})}
if(path.startsWith('/api/uploads/')){const id=path.slice(13),record=await q(env,'SELECT * FROM uploads WHERE id=?',id).first();need(record,404,'原帖不存在');const obj=await env.BUCKET.get(record.key);need(obj,404,'原帖暂不可用');return new Response(obj.body,{headers:{'content-type':record.type,'cache-control':'public,max-age=86400','x-content-type-options':'nosniff'}})}
if(path.startsWith('/api/admin/')){founder();if(path==='/api/admin/users'){if(method==='GET')return json({users:(await q(env,'SELECT id,name,role,created FROM users ORDER BY created LIMIT 300').all()).results});const d=await body(r);need(['saint','member'].includes(d.role),400,'请选择书圣或书家');await q(env,"UPDATE users SET role=? WHERE id=? AND role!='founder'",d.role,text(d.id)).run();return json({saved:true})}
if(path==='/api/admin/site'){const d=await body(r,250000);need(d.content&&typeof d.content==='object',400,'内容不能为空');const old=await q(env,"SELECT revision FROM site_state WHERE key='content'").first();need((old?.revision||0)===d.revision,409,'另一处已修改，请刷新后再保存');const row=await q(env,"INSERT INTO site_state(key,value,revision) VALUES ('content',?,1) ON CONFLICT(key) DO UPDATE SET value=excluded.value,revision=site_state.revision+1 WHERE site_state.revision=? RETURNING revision",JSON.stringify(d.content),d.revision).first();need(row,409,'版本冲突，请刷新');return json(row)}
if(path==='/api/admin/feature'){const d=await body(r);await q(env,"UPDATE works SET featured=? WHERE id=? AND visibility='public'",d.featured?1:0,text(d.id)).run();return json({saved:true})}
if(path==='/api/admin/templates'){if(method==='GET')return json({templates:(await q(env,'SELECT * FROM templates ORDER BY position').all()).results.map(t=>({...t,config:JSON.parse(t.config)}))});const d=await body(r,150000);need(['scene','copybook'].includes(d.kind),400,'模板类别不正确');const id=text(d.id)||uid();await q(env,'INSERT INTO templates(id,title,kind,config,position,hidden) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,kind=excluded.kind,config=excluded.config,position=excluded.position,hidden=excluded.hidden',id,text(d.title),d.kind,JSON.stringify(d.config||{}),num(d.position,0,1000),d.hidden?1:0).run();return json({id})}
if(path==='/api/admin/upload'){const data=await r.arrayBuffer(),b=new Uint8Array(data);need(data.byteLength<=20*1024*1024,413,'原帖每张最多20MB');let type=b[0]===137&&b[1]===80?'image/png':b[0]===255&&b[1]===216?'image/jpeg':b[0]===82&&b[1]===73&&b[8]===87?'image/webp':null;need(type,400,'仅支持PNG、JPEG、WebP图片');const id=uid(),key='copybooks/'+id;await env.BUCKET.put(key,data,{httpMetadata:{contentType:type}});await q(env,'INSERT INTO uploads(id,owner,key,type) VALUES (?,?,?,?)',id,u.id,key,type).run();return json({url:'/api/uploads/'+id})}}
if(path==='/api/nearby'){const lat=Number(url.searchParams.get('lat')),lon=Number(url.searchParams.get('lon'));need(Number.isFinite(lat)&&Math.abs(lat)<=90&&Number.isFinite(lon)&&Math.abs(lon)<=180,400,'位置不正确');const row=await q(env,"SELECT value FROM site_state WHERE key='content'").first();const events=row?(JSON.parse(row.value).places||[]):[];const radians=n=>n*Math.PI/180;const distance=(a,b)=>{const dlat=radians(a-lat),dlon=radians(b-lon);return 6371*2*Math.asin(Math.sqrt(Math.sin(dlat/2)**2+Math.cos(radians(lat))*Math.cos(radians(a))*Math.sin(dlon/2)**2))};const curated=events.map(e=>({...e,distance:distance(Number(e.lat),Number(e.lon))})).filter(e=>Number.isFinite(e.distance)&&e.distance<=10&&e.year&&e.source).sort((a,b)=>a.distance-b.distance).slice(0,8);return json({events:curated.length?curated:await nearby(lat,lon),notice:'只显示有来源的附近历史记录；没有匹配时不生成故事。'})}
return json({error:'接口不存在'},404)}
export default {async fetch(request,env,ctx){try{return await route(request,env)}catch(e){if(!e.status)console.error('Request failed',new URL(request.url).pathname,e.name);return json({error:e.status?e.message:'在线服务暂不可用，请稍后重试'},e.status||503)}}};
