import {sqliteTable,text,integer,uniqueIndex,index} from 'drizzle-orm/sqlite-core';
export const users=sqliteTable('users',{id:text('id').primaryKey(),identity:text('identity').notNull().unique(),name:text('name').notNull(),role:text('role').notNull().default('member'),created:integer('created').notNull(),settings:text('settings').notNull().default('{}')});
export const siteState=sqliteTable('site_state',{key:text('key').primaryKey(),value:text('value').notNull(),revision:integer('revision').notNull().default(0)});
export const sessions=sqliteTable('sessions',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),expires:integer('expires').notNull()});
export const oauthStates=sqliteTable('oauth_states',{id:text('id').primaryKey(),provider:text('provider').notNull(),verifier:text('verifier').notNull(),nonce:text('nonce').notNull(),expires:integer('expires').notNull()});
export const works=sqliteTable('works',{id:text('id').primaryKey(),owner:text('owner').notNull().references(()=>users.id),title:text('title').notNull(),visibility:text('visibility').notNull().default('private'),featured:integer('featured').notNull().default(0),parent:text('parent'),created:integer('created').notNull(),updated:integer('updated').notNull(),image:text('image').notNull().default(''),draft:text('draft').notNull().default(''),allowCopy:integer('allow_copy').notNull().default(1)},t=>[index('works_owner').on(t.owner),index('works_parent').on(t.parent)]);
export const likes=sqliteTable('likes',{userId:text('user_id').notNull().references(()=>users.id),workId:text('work_id').notNull().references(()=>works.id)},t=>[uniqueIndex('likes_once').on(t.userId,t.workId)]);
export const comments=sqliteTable('comments',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),workId:text('work_id').notNull().references(()=>works.id),body:text('body').notNull(),created:integer('created').notNull()},t=>[index('comments_work').on(t.workId)]);
export const activity=sqliteTable('activity',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),day:text('day').notNull(),seconds:integer('seconds').notNull(),characters:integer('characters').notNull(),strokes:integer('strokes').notNull()});
export const templates=sqliteTable('templates',{id:text('id').primaryKey(),title:text('title').notNull(),kind:text('kind').notNull(),config:text('config').notNull(),position:integer('position').notNull().default(0),hidden:integer('hidden').notNull().default(0)});
export const uploads=sqliteTable('uploads',{id:text('id').primaryKey(),owner:text('owner').notNull().references(()=>users.id),key:text('key').notNull(),type:text('type').notNull()});


export const passwordAccounts=sqliteTable('password_accounts',{username:text('username').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),salt:text('salt').notNull(),digest:text('digest').notNull()});
export const authLimits=sqliteTable('auth_limits',{key:text('key').primaryKey(),attempts:integer('attempts').notNull(),expires:integer('expires').notNull()});
