import * as T from 'three';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
window.InkCraft3D50={create(host,ink){
 const renderer=new T.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xf2eee6,1);host.replaceChildren(renderer.domElement);const scene=new T.Scene(),camera=new T.PerspectiveCamera(35,1,.01,20);camera.position.set(0,.025,.34);camera.lookAt(0,0,0);scene.add(new T.HemisphereLight(0xffffff,0x777060,3));const light=new T.DirectionalLight(0xffffff,4);light.position.set(1,2,3);scene.add(light);let model=new T.Group();scene.add(model);let type='mug',color='#ede5d7',disposed=false;const placement={scale:.85,x:0,y:0};
 const texCanvas=document.createElement('canvas');texCanvas.width=texCanvas.height=1024;const texture=new T.CanvasTexture(texCanvas);texture.colorSpace=T.SRGBColorSpace;texture.anisotropy=renderer.capabilities.getMaxAnisotropy();
 function draw(){if(!disposed)renderer.render(scene,camera)}
 function updateTexture(){const c=texCanvas.getContext('2d');c.clearRect(0,0,1024,1024);const s=Math.min(900/ink.width,900/ink.height)*placement.scale,w=ink.width*s,h=ink.height*s;c.drawImage(ink,(1024-w)/2+placement.x*1024,(1024-h)/2-placement.y*1024,w,h);texture.needsUpdate=true;draw()}
 function clean(){model.traverse(o=>{o.geometry?.dispose();if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose())});scene.remove(model)}
 function mesh(g,m,x=0,y=0,z=0){const o=new T.Mesh(g,m);o.position.set(x,y,z);model.add(o);return o}
 function build(){clean();model=new T.Group();scene.add(model);const mat=new T.MeshStandardMaterial({color,roughness:type==='shirt'?.95:.35,side:T.DoubleSide}),decal=new T.MeshStandardMaterial({map:texture,transparent:true,roughness:.8,depthWrite:false,side:T.DoubleSide});
 if(type==='mug'){const points=[new T.Vector2(.001,-.06),new T.Vector2(.045,-.06),new T.Vector2(.047,.06),new T.Vector2(.042,.06),new T.Vector2(.04,-.055),new T.Vector2(.001,-.055)];mesh(new T.LatheGeometry(points,72),mat);const handle=mesh(new T.TorusGeometry(.035,.008,16,48),mat,.063,0,0);handle.scale.x=.8;mesh(new T.CylinderGeometry(.0478,.0468,.10,64,1,true,-Math.PI/2,Math.PI),decal,0,0,.0005);}
 if(type==='shirt'){const s=new T.Shape();s.moveTo(-.035,.115);s.lineTo(-.075,.10);s.lineTo(-.115,.045);s.lineTo(-.077,.025);s.lineTo(-.06,.05);s.lineTo(-.06,-.11);s.lineTo(.06,-.11);s.lineTo(.06,.05);s.lineTo(.077,.025);s.lineTo(.115,.045);s.lineTo(.075,.10);s.lineTo(.035,.115);s.quadraticCurveTo(0,.065,-.035,.115);const g=new T.ExtrudeGeometry(s,{depth:.009,bevelEnabled:true,bevelSize:.003,bevelThickness:.002,bevelSegments:3,steps:1});mesh(g,mat);mesh(new T.PlaneGeometry(.112,.14),decal,0,-.007,.012);}
 if(type==='base'){mesh(new T.BoxGeometry(.19,.10,.055),mat,0,-.05);mesh(new T.PlaneGeometry(.176,.088),decal,0,-.05,.028);const brass=new T.MeshStandardMaterial({color:0xa18b59,metalness:.6,roughness:.4});mesh(new T.SphereGeometry(.025,32,24),brass,0,.09);const body=mesh(new T.TorusKnotGeometry(.029,.008,80,12),brass,0,.025);body.rotation.z=.5;}
 model.rotation.y=-.18;camera.position.z=type==='mug'?.34:type==='shirt'?.53:.46;camera.lookAt(0,0,0);draw();}
 let pointers=new Map(),last=null;const el=renderer.domElement;el.style.touchAction='none';function pos(){const a=[...pointers.values()];return a.length>1?{d:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)}:a[0]}
 el.onpointerdown=e=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});el.setPointerCapture(e.pointerId);last=pos()};el.onpointermove=e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const p=pos();if(p.d&&last?.d)camera.position.z=T.MathUtils.clamp(camera.position.z*last.d/p.d,.25,1.2);else if(p.x!==undefined&&last?.x!==undefined){model.rotation.y+=(p.x-last.x)*.01;model.rotation.x=T.MathUtils.clamp(model.rotation.x+(p.y-last.y)*.01,-1,1)}last=p;draw()};el.onpointerup=el.onpointercancel=e=>{pointers.delete(e.pointerId);last=pos()};el.onwheel=e=>{e.preventDefault();camera.position.z=T.MathUtils.clamp(camera.position.z*Math.exp(e.deltaY*.001),.25,1.2);draw()};
 const resize=new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight||360;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();draw()});resize.observe(host);build();updateTexture();
 return{setType(v){type=v;build()},setColor(v){color=v;build()},setPlacement(v){Object.assign(placement,v);updateTexture()},get placement(){return{...placement}},async exportGLB(){const clone=model.clone();clone.rotation.set(0,0,0);return new GLTFExporter().parseAsync(clone,{binary:true,onlyVisible:true})},dispose(){disposed=true;resize.disconnect();clean();texture.dispose();renderer.dispose();renderer.forceContextLoss();el.remove();pointers.clear()}};
}};
