import * as T from 'three';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
function solidFiles(trace,widthMM){
 if(trace.paths.length>4000)throw Error('轮廓过密；提高阈值后再生成 3D 实体。');
 const scale=widthMM/trace.width,area=p=>p.reduce((sum,v,i)=>{const w=p[(i+1)%p.length];return sum+v[0]*w[1]-w[0]*v[1]},0),paths=trace.paths.map(p=>({points:p,area:area(p)})).filter(x=>Math.abs(x.area)>3);if(!paths.length)throw Error('没有足够的实体轮廓');
 const outerSign=Math.sign(paths.reduce((best,x)=>Math.abs(x.area)>Math.abs(best)?x.area:best,0)),outer=paths.filter(x=>Math.sign(x.area)===outerSign),holes=paths.filter(x=>Math.sign(x.area)!==outerSign);
 const contains=(poly,p)=>{let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside}return inside};
 const shapeOf=p=>{const s=new T.Shape();p.forEach(([x,y],i)=>i?s.lineTo(x*scale,(trace.height-y)*scale):s.moveTo(x*scale,(trace.height-y)*scale));s.closePath();return s};
 const group=new T.Group(),geometries=[];for(const o of outer){const shape=shapeOf(o.points);for(const h of holes)if(contains(o.points,h.points[0]))shape.holes.push(shapeOf(h.points));const geometry=new T.ExtrudeGeometry(shape,{depth:3,steps:1,bevelEnabled:false,curveSegments:1});geometry.computeVertexNormals();const mesh=new T.Mesh(geometry,new T.MeshStandardMaterial({color:0x9a754d,metalness:.2,roughness:.6,side:T.DoubleSide}));group.add(mesh);geometries.push(geometry)}
 const triangles=geometries.reduce((n,g)=>n+(g.index?g.index.count:g.attributes.position.count)/3,0),buffer=new ArrayBuffer(84+triangles*50),view=new DataView(buffer);view.setUint32(80,triangles,true);let offset=84;for(const g of geometries){const a=g.attributes.position,index=g.index;for(let i=0;i<(index?index.count:a.count);i+=3){const ids=[0,1,2].map(k=>index?index.getX(i+k):i+k),v=ids.map(id=>new T.Vector3().fromBufferAttribute(a,id)),n=new T.Vector3().subVectors(v[1],v[0]).cross(new T.Vector3().subVectors(v[2],v[0])).normalize();for(const x of [n,...v])for(const f of [x.x,x.y,x.z]){view.setFloat32(offset,f,true);offset+=4}offset+=2}}
 group.scale.setScalar(.001);return{group,stl:buffer,dispose:()=>geometries.forEach(g=>g.dispose())};
}
window.InkCraft3D50={async solidFiles(trace,widthMM){const solid=solidFiles(trace,widthMM);try{return{stl:solid.stl,glb:await new GLTFExporter().parseAsync(solid.group,{binary:true,onlyVisible:true})}}finally{solid.dispose()}},create(host,ink){
 const renderer=new T.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xf2eee6,1);host.replaceChildren(renderer.domElement);const scene=new T.Scene(),camera=new T.PerspectiveCamera(35,1,.01,20);camera.position.set(0,.025,.34);camera.lookAt(0,0,0);scene.add(new T.HemisphereLight(0xffffff,0x777060,3));const light=new T.DirectionalLight(0xffffff,4);light.position.set(1,2,3);scene.add(light);let model=new T.Group();scene.add(model);let type='phone',color='#ede5d7',disposed=false;const placement={scale:.85,x:0,y:0};
 const texCanvas=document.createElement('canvas');texCanvas.width=texCanvas.height=1024;const texture=new T.CanvasTexture(texCanvas);texture.colorSpace=T.SRGBColorSpace;texture.anisotropy=renderer.capabilities.getMaxAnisotropy();
 function draw(){if(!disposed)renderer.render(scene,camera)}
 function updateTexture(){const c=texCanvas.getContext('2d');c.clearRect(0,0,1024,1024);const s=Math.min(900/ink.width,900/ink.height)*placement.scale,w=ink.width*s,h=ink.height*s;c.drawImage(ink,(1024-w)/2+placement.x*1024,(1024-h)/2-placement.y*1024,w,h);texture.needsUpdate=true;draw()}
 function clean(){model.traverse(o=>{o.geometry?.dispose();if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose())});scene.remove(model)}
 function mesh(g,m,x=0,y=0,z=0){const o=new T.Mesh(g,m);o.position.set(x,y,z);model.add(o);return o}
 function build(){clean();model=new T.Group();scene.add(model);const mat=new T.MeshStandardMaterial({color,roughness:type==='shirt'?.95:.35,side:T.DoubleSide}),decal=new T.MeshStandardMaterial({map:texture,transparent:true,roughness:.8,depthWrite:false,side:T.DoubleSide});
 if(type==='mug'){const ceramic=new T.MeshStandardMaterial({color,roughness:.28});const foot=new T.MeshStandardMaterial({color:0xb29a71,metalness:.45,roughness:.32});const points=[new T.Vector2(.001,-.068),new T.Vector2(.041,-.068),new T.Vector2(.047,-.058),new T.Vector2(.048,.052),new T.Vector2(.045,.066),new T.Vector2(.039,.066),new T.Vector2(.038,-.057),new T.Vector2(.001,-.057)];mesh(new T.LatheGeometry(points,72),ceramic);mesh(new T.TorusGeometry(.048,.0025,10,72),foot,0,-.058);const handle=mesh(new T.TorusGeometry(.035,.007,16,48),ceramic,.064,-.002,0);handle.scale.x=.86;mesh(new T.CylinderGeometry(.0485,.0485,.095,72,1,true,-Math.PI/2,Math.PI),decal,0,0,.0005);}
 if(type==='shirt'){const s=new T.Shape();s.moveTo(-.041,.112);s.lineTo(-.088,.094);s.lineTo(-.119,.035);s.lineTo(-.082,.014);s.lineTo(-.065,.047);s.lineTo(-.065,-.115);s.quadraticCurveTo(0,-.12,.065,-.115);s.lineTo(.065,.047);s.lineTo(.082,.014);s.lineTo(.119,.035);s.lineTo(.088,.094);s.lineTo(.041,.112);s.absarc(0,.112,.041,0,Math.PI,true);const g=new T.ExtrudeGeometry(s,{depth:.012,bevelEnabled:true,bevelSize:.003,bevelThickness:.003,bevelSegments:4});mesh(g,mat);const collar=new T.MeshStandardMaterial({color:type==='shirt'?color:'#eae5d7',roughness:1});const rib=mesh(new T.TorusGeometry(.038,.002,8,32,Math.PI),collar,0,.112,.016);rib.rotation.z=Math.PI;mesh(new T.PlaneGeometry(.082,.102),decal,0,-.016,.017);}
 if(type==='phone'){const shell=new T.MeshStandardMaterial({color:0x1d3842,metalness:.23,roughness:.4});const trim=new T.MeshStandardMaterial({color:0xc7a56a,metalness:.73,roughness:.28});mesh(new T.BoxGeometry(.102,.205,.012),shell);mesh(new T.BoxGeometry(.095,.198,.002),new T.MeshStandardMaterial({color,roughness:.72}),0,0,.007);const panel=mesh(new T.PlaneGeometry(.078,.125),decal,0,-.026,.009);for(const x of [-.042,.042]){const line=mesh(new T.BoxGeometry(.001,.16,.001),trim,x,-.012,.009);line.rotation.z=x<0?-.015:.015}mesh(new T.CylinderGeometry(.011,.011,.003,24),shell,-.027,.075,.01);mesh(new T.CylinderGeometry(.008,.008,.004,24),trim,-.027,.075,.013);}
 if(type==='print'){const brass=new T.MeshStandardMaterial({color:0xbd9560,metalness:.75,roughness:.24}),base=new T.MeshStandardMaterial({color:0x263b3d,roughness:.48});mesh(new T.CylinderGeometry(.08,.085,.013,64),base,0,-.087);mesh(new T.CylinderGeometry(.076,.078,.004,64),brass,0,-.078);const frame=mesh(new T.BoxGeometry(.11,.137,.014),brass,0,0);mesh(new T.PlaneGeometry(.104,.132),decal,0,0,.008);mesh(new T.BoxGeometry(.025,.014,.015),brass,0,-.071);}
 model.rotation.y=-.18;camera.position.z=type==='mug'?.34:type==='shirt'?.58:type==='phone'?.4:.48;camera.lookAt(0,0,0);draw();}
 let pointers=new Map(),last=null;const el=renderer.domElement;el.style.touchAction='none';function pos(){const a=[...pointers.values()];return a.length>1?{d:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)}:a[0]}
 el.onpointerdown=e=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});el.setPointerCapture(e.pointerId);last=pos()};el.onpointermove=e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const p=pos();if(p.d&&last?.d)camera.position.z=T.MathUtils.clamp(camera.position.z*last.d/p.d,.25,1.2);else if(p.x!==undefined&&last?.x!==undefined){model.rotation.y+=(p.x-last.x)*.01;model.rotation.x=T.MathUtils.clamp(model.rotation.x+(p.y-last.y)*.01,-1,1)}last=p;draw()};el.onpointerup=el.onpointercancel=e=>{pointers.delete(e.pointerId);last=pos()};el.onwheel=e=>{e.preventDefault();camera.position.z=T.MathUtils.clamp(camera.position.z*Math.exp(e.deltaY*.001),.25,1.2);draw()};
 const resize=new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight||360;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();draw()});resize.observe(host);build();updateTexture();
 return{setType(v){type=v;build()},setColor(v){color=v;build()},setPlacement(v){Object.assign(placement,v);updateTexture()},get placement(){return{...placement}},async exportGLB(){const clone=model.clone();clone.rotation.set(0,0,0);return new GLTFExporter().parseAsync(clone,{binary:true,onlyVisible:true})},dispose(){disposed=true;resize.disconnect();clean();texture.dispose();renderer.dispose();renderer.forceContextLoss();el.remove();pointers.clear()}};
}};
