import{readFile,writeFile,readdir,unlink}from'node:fs/promises';
import{createHash}from'node:crypto';
import{transform}from'esbuild';
const{scripts,styles}=JSON.parse(await readFile('runtime-sources106.json','utf8'));
const raw=(await Promise.all(scripts.map(p=>readFile(p,'utf8')))).join('\n;\n');
const js=(await transform(raw,{minify:true,target:['safari14'],charset:'utf8',legalComments:'none'})).code;
const css=(await transform((await Promise.all(styles.map(p=>readFile(p,'utf8')))).join('\n')+'\ndialog.fallbackDialog106{position:fixed!important;z-index:2000!important;max-height:85vh;overflow:auto}dialog.fallbackDialog106:not([open]){display:none!important}',{loader:'css',minify:true,target:['safari14'],charset:'utf8'})).code;
const hash=s=>createHash('sha256').update(s).digest('hex').slice(0,16),jn='app-runtime.'+hash(js)+'.js',cn='app-runtime.'+hash(css)+'.css';
for(const p of await readdir('.'))if(/^app-runtime\.[a-f0-9]+\.(js|css)$/.test(p)&&p!==jn&&p!==cn)await unlink(p);
await writeFile(jn,js);await writeFile(cn,css);await writeFile('index.html',(await readFile('index-source106.html','utf8')).replace('__RUNTIME_JS__',jn).replace('__RUNTIME_CSS__',cn));
console.log('Complete runtime:',jn,cn);
